package typingsSlinky.qunitDashDom

import org.scalajs.dom.raw.Element
import org.scalajs.dom.raw.Node
import typingsSlinky.std.HTMLAnchorElement
import typingsSlinky.std.HTMLAppletElement
import typingsSlinky.std.HTMLAreaElement
import typingsSlinky.std.HTMLAudioElement
import typingsSlinky.std.HTMLBRElement
import typingsSlinky.std.HTMLBaseElement
import typingsSlinky.std.HTMLBaseFontElement
import typingsSlinky.std.HTMLBodyElement
import typingsSlinky.std.HTMLButtonElement
import typingsSlinky.std.HTMLCanvasElement
import typingsSlinky.std.HTMLDListElement
import typingsSlinky.std.HTMLDataElement
import typingsSlinky.std.HTMLDataListElement
import typingsSlinky.std.HTMLDetailsElement
import typingsSlinky.std.HTMLDialogElement
import typingsSlinky.std.HTMLDirectoryElement
import typingsSlinky.std.HTMLDivElement
import typingsSlinky.std.HTMLElement
import typingsSlinky.std.HTMLEmbedElement
import typingsSlinky.std.HTMLFieldSetElement
import typingsSlinky.std.HTMLFontElement
import typingsSlinky.std.HTMLFormElement
import typingsSlinky.std.HTMLFrameElement
import typingsSlinky.std.HTMLFrameSetElement
import typingsSlinky.std.HTMLHRElement
import typingsSlinky.std.HTMLHeadElement
import typingsSlinky.std.HTMLHeadingElement
import typingsSlinky.std.HTMLHtmlElement
import typingsSlinky.std.HTMLIFrameElement
import typingsSlinky.std.HTMLImageElement
import typingsSlinky.std.HTMLInputElement
import typingsSlinky.std.HTMLLIElement
import typingsSlinky.std.HTMLLabelElement
import typingsSlinky.std.HTMLLegendElement
import typingsSlinky.std.HTMLLinkElement
import typingsSlinky.std.HTMLMapElement
import typingsSlinky.std.HTMLMarqueeElement
import typingsSlinky.std.HTMLMenuElement
import typingsSlinky.std.HTMLMetaElement
import typingsSlinky.std.HTMLMeterElement
import typingsSlinky.std.HTMLModElement
import typingsSlinky.std.HTMLOListElement
import typingsSlinky.std.HTMLObjectElement
import typingsSlinky.std.HTMLOptGroupElement
import typingsSlinky.std.HTMLOptionElement
import typingsSlinky.std.HTMLOutputElement
import typingsSlinky.std.HTMLParagraphElement
import typingsSlinky.std.HTMLParamElement
import typingsSlinky.std.HTMLPictureElement
import typingsSlinky.std.HTMLPreElement
import typingsSlinky.std.HTMLProgressElement
import typingsSlinky.std.HTMLQuoteElement
import typingsSlinky.std.HTMLScriptElement
import typingsSlinky.std.HTMLSelectElement
import typingsSlinky.std.HTMLSlotElement
import typingsSlinky.std.HTMLSourceElement
import typingsSlinky.std.HTMLSpanElement
import typingsSlinky.std.HTMLStyleElement
import typingsSlinky.std.HTMLTableCaptionElement
import typingsSlinky.std.HTMLTableColElement
import typingsSlinky.std.HTMLTableDataCellElement
import typingsSlinky.std.HTMLTableElement
import typingsSlinky.std.HTMLTableHeaderCellElement
import typingsSlinky.std.HTMLTableRowElement
import typingsSlinky.std.HTMLTableSectionElement
import typingsSlinky.std.HTMLTemplateElement
import typingsSlinky.std.HTMLTextAreaElement
import typingsSlinky.std.HTMLTimeElement
import typingsSlinky.std.HTMLTitleElement
import typingsSlinky.std.HTMLTrackElement
import typingsSlinky.std.HTMLUListElement
import typingsSlinky.std.HTMLVideoElement
import typingsSlinky.std.NodeList
import typingsSlinky.std.NodeListOf
import typingsSlinky.std.SVGAElement
import typingsSlinky.std.SVGCircleElement
import typingsSlinky.std.SVGClipPathElement
import typingsSlinky.std.SVGDefsElement
import typingsSlinky.std.SVGDescElement
import typingsSlinky.std.SVGEllipseElement
import typingsSlinky.std.SVGFEBlendElement
import typingsSlinky.std.SVGFEColorMatrixElement
import typingsSlinky.std.SVGFEComponentTransferElement
import typingsSlinky.std.SVGFECompositeElement
import typingsSlinky.std.SVGFEConvolveMatrixElement
import typingsSlinky.std.SVGFEDiffuseLightingElement
import typingsSlinky.std.SVGFEDisplacementMapElement
import typingsSlinky.std.SVGFEDistantLightElement
import typingsSlinky.std.SVGFEFloodElement
import typingsSlinky.std.SVGFEFuncAElement
import typingsSlinky.std.SVGFEFuncBElement
import typingsSlinky.std.SVGFEFuncGElement
import typingsSlinky.std.SVGFEFuncRElement
import typingsSlinky.std.SVGFEGaussianBlurElement
import typingsSlinky.std.SVGFEImageElement
import typingsSlinky.std.SVGFEMergeElement
import typingsSlinky.std.SVGFEMergeNodeElement
import typingsSlinky.std.SVGFEMorphologyElement
import typingsSlinky.std.SVGFEOffsetElement
import typingsSlinky.std.SVGFEPointLightElement
import typingsSlinky.std.SVGFESpecularLightingElement
import typingsSlinky.std.SVGFESpotLightElement
import typingsSlinky.std.SVGFETileElement
import typingsSlinky.std.SVGFETurbulenceElement
import typingsSlinky.std.SVGFilterElement
import typingsSlinky.std.SVGForeignObjectElement
import typingsSlinky.std.SVGGElement
import typingsSlinky.std.SVGImageElement
import typingsSlinky.std.SVGLineElement
import typingsSlinky.std.SVGLinearGradientElement
import typingsSlinky.std.SVGMarkerElement
import typingsSlinky.std.SVGMaskElement
import typingsSlinky.std.SVGMetadataElement
import typingsSlinky.std.SVGPathElement
import typingsSlinky.std.SVGPatternElement
import typingsSlinky.std.SVGPolygonElement
import typingsSlinky.std.SVGPolylineElement
import typingsSlinky.std.SVGRadialGradientElement
import typingsSlinky.std.SVGRectElement
import typingsSlinky.std.SVGSVGElement
import typingsSlinky.std.SVGScriptElement
import typingsSlinky.std.SVGStopElement
import typingsSlinky.std.SVGStyleElement
import typingsSlinky.std.SVGSwitchElement
import typingsSlinky.std.SVGSymbolElement
import typingsSlinky.std.SVGTSpanElement
import typingsSlinky.std.SVGTextElement
import typingsSlinky.std.SVGTextPathElement
import typingsSlinky.std.SVGTitleElement
import typingsSlinky.std.SVGUseElement
import typingsSlinky.std.SVGViewElement
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@JSImport("qunit-dom/dist/helpers/node-list", JSImport.Namespace)
@js.native
object distHelpersNodeDashListMod extends js.Object {
  def toArray(list: NodeList): js.Array[Node] = js.native
  def toArray(
    selectors: NodeListOf[
      HTMLAnchorElement | HTMLAppletElement | HTMLAreaElement | HTMLAudioElement | HTMLBRElement | HTMLBaseElement | HTMLBaseFontElement | HTMLBodyElement | HTMLButtonElement | HTMLCanvasElement | HTMLDListElement | HTMLDataElement | HTMLDataListElement | HTMLDetailsElement | HTMLDialogElement | HTMLDirectoryElement | HTMLDivElement | HTMLElement | HTMLEmbedElement | HTMLFieldSetElement | HTMLFontElement | HTMLFormElement | HTMLFrameElement | HTMLFrameSetElement | HTMLHRElement | HTMLHeadElement | HTMLHeadingElement | HTMLHtmlElement | HTMLIFrameElement | HTMLImageElement | HTMLInputElement | HTMLLIElement | HTMLLabelElement | HTMLLegendElement | HTMLLinkElement | HTMLMapElement | HTMLMarqueeElement | HTMLMenuElement | HTMLMetaElement | HTMLMeterElement | HTMLModElement | HTMLOListElement | HTMLObjectElement | HTMLOptGroupElement | HTMLOptionElement | HTMLOutputElement | HTMLParagraphElement | HTMLParamElement | HTMLPictureElement | HTMLPreElement | HTMLProgressElement | HTMLQuoteElement | HTMLScriptElement | HTMLSelectElement | HTMLSlotElement | HTMLSourceElement | HTMLSpanElement | HTMLStyleElement | HTMLTableCaptionElement | HTMLTableColElement | HTMLTableDataCellElement | HTMLTableElement | HTMLTableHeaderCellElement | HTMLTableRowElement | HTMLTableSectionElement | HTMLTemplateElement | HTMLTextAreaElement | HTMLTimeElement | HTMLTitleElement | HTMLTrackElement | HTMLUListElement | HTMLVideoElement | SVGAElement | SVGCircleElement | SVGClipPathElement | SVGDefsElement | SVGDescElement | SVGEllipseElement | SVGFEBlendElement | SVGFEColorMatrixElement | SVGFEComponentTransferElement | SVGFECompositeElement | SVGFEConvolveMatrixElement | SVGFEDiffuseLightingElement | SVGFEDisplacementMapElement | SVGFEDistantLightElement | SVGFEFloodElement | SVGFEFuncAElement | SVGFEFuncBElement | SVGFEFuncGElement | SVGFEFuncRElement | SVGFEGaussianBlurElement | SVGFEImageElement | SVGFEMergeElement | SVGFEMergeNodeElement | SVGFEMorphologyElement | SVGFEOffsetElement | SVGFEPointLightElement | SVGFESpecularLightingElement | SVGFESpotLightElement | SVGFETileElement | SVGFETurbulenceElement | SVGFilterElement | SVGForeignObjectElement | SVGGElement | SVGImageElement | SVGLineElement | SVGLinearGradientElement | SVGMarkerElement | SVGMaskElement | SVGMetadataElement | SVGPathElement | SVGPatternElement | SVGPolygonElement | SVGPolylineElement | SVGRadialGradientElement | SVGRectElement | SVGSVGElement | SVGScriptElement | SVGStopElement | SVGStyleElement | SVGSwitchElement | SVGSymbolElement | SVGTSpanElement | SVGTextElement | SVGTextPathElement | SVGTitleElement | SVGUseElement | SVGViewElement
    ]
  ): js.Array[org.scalajs.dom.raw.HTMLAnchorElement] = js.native
  @JSName("toArray")
  def toArray_E_Element[E /* <: Element */](selectors: org.scalajs.dom.raw.NodeListOf[E with Node]): js.Array[E] = js.native
}

