package typingsSlinky.activexWord.Word

import typingsSlinky.activexOffice.Office.MsoEncoding
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait Options extends js.Object {
  var AddBiDirectionalMarksWhenSavingTextFile: Boolean
  var AddControlCharacters: Boolean
  var AddHebDoubleQuote: Boolean
  var AllowAccentedUppercase: Boolean
  var AllowClickAndTypeMouse: Boolean
  var AllowCombinedAuxiliaryForms: Boolean
  var AllowCompoundNounProcessing: Boolean
  var AllowDragAndDrop: Boolean
  var AllowFastSave: Boolean
  var AllowOpenInDraftView: Boolean
  var AllowPixelUnits: Boolean
  var AllowReadingMode: Boolean
  var AlwaysUseClearType: Boolean
  var AnimateScreenMovements: Boolean
  val Application: typingsSlinky.activexWord.Word.Application
  var ApplyFarEastFontsToAscii: Boolean
  var ArabicMode: WdAraSpeller
  var ArabicNumeral: WdArabicNumeral
  var AutoCreateNewDrawings: Boolean
  var AutoFormatApplyBulletedLists: Boolean
  var AutoFormatApplyFirstIndents: Boolean
  var AutoFormatApplyHeadings: Boolean
  var AutoFormatApplyLists: Boolean
  var AutoFormatApplyOtherParas: Boolean
  var AutoFormatAsYouTypeApplyBorders: Boolean
  var AutoFormatAsYouTypeApplyBulletedLists: Boolean
  var AutoFormatAsYouTypeApplyClosings: Boolean
  var AutoFormatAsYouTypeApplyDates: Boolean
  var AutoFormatAsYouTypeApplyFirstIndents: Boolean
  var AutoFormatAsYouTypeApplyHeadings: Boolean
  var AutoFormatAsYouTypeApplyNumberedLists: Boolean
  var AutoFormatAsYouTypeApplyTables: Boolean
  var AutoFormatAsYouTypeAutoLetterWizard: Boolean
  var AutoFormatAsYouTypeDefineStyles: Boolean
  var AutoFormatAsYouTypeDeleteAutoSpaces: Boolean
  var AutoFormatAsYouTypeFormatListItemBeginning: Boolean
  var AutoFormatAsYouTypeInsertClosings: Boolean
  var AutoFormatAsYouTypeInsertOvers: Boolean
  var AutoFormatAsYouTypeMatchParentheses: Boolean
  var AutoFormatAsYouTypeReplaceFarEastDashes: Boolean
  var AutoFormatAsYouTypeReplaceFractions: Boolean
  var AutoFormatAsYouTypeReplaceHyperlinks: Boolean
  var AutoFormatAsYouTypeReplaceOrdinals: Boolean
  var AutoFormatAsYouTypeReplacePlainTextEmphasis: Boolean
  var AutoFormatAsYouTypeReplaceQuotes: Boolean
  var AutoFormatAsYouTypeReplaceSymbols: Boolean
  var AutoFormatDeleteAutoSpaces: Boolean
  var AutoFormatMatchParentheses: Boolean
  var AutoFormatPlainTextWordMail: Boolean
  var AutoFormatPreserveStyles: Boolean
  var AutoFormatReplaceFarEastDashes: Boolean
  var AutoFormatReplaceFractions: Boolean
  var AutoFormatReplaceHyperlinks: Boolean
  var AutoFormatReplaceOrdinals: Boolean
  var AutoFormatReplacePlainTextEmphasis: Boolean
  var AutoFormatReplaceQuotes: Boolean
  var AutoFormatReplaceSymbols: Boolean
  var AutoKeyboardSwitching: Boolean
  var AutoWordSelection: Boolean
  var BackgroundOpen: Boolean
  var BackgroundSave: Boolean
  var BibliographySort: String
  var BibliographyStyle: String
  var BlueScreen: Boolean
  var BrazilReform: WdPortugueseReform
  var ButtonFieldClicks: Double
  var CheckGrammarAsYouType: Boolean
  var CheckGrammarWithSpelling: Boolean
  var CheckHangulEndings: Boolean
  var CheckSpellingAsYouType: Boolean
  var CommentsColor: WdColorIndex
  var ConfirmConversions: Boolean
  var ContextualSpeller: Boolean
  var ConvertHighAnsiToFarEast: Boolean
  var CreateBackup: Boolean
  val Creator: Double
  var CtrlClickHyperlinkToOpen: Boolean
  var CursorMovement: WdCursorMovement
  var DefaultBorderColor: WdColor
  var DefaultBorderColorIndex: WdColorIndex
  var DefaultBorderLineStyle: WdLineStyle
  var DefaultBorderLineWidth: WdLineWidth
  var DefaultEPostageApp: String
  var DefaultHighlightColorIndex: WdColorIndex
  var DefaultOpenFormat: WdOpenFormat
  var DefaultTextEncoding: MsoEncoding
  var DefaultTray: String
  var DefaultTrayID: Double
  var DeletedCellColor: WdCellColor
  var DeletedTextColor: WdColorIndex
  var DeletedTextMark: WdDeletedTextMark
  var DiacriticColorVal: WdColor
  var DisableFeaturesIntroducedAfterbyDefault: WdDisableFeaturesIntroducedAfter
  var DisableFeaturesbyDefault: Boolean
  var DisplayGridLines: Boolean
  var DisplayPasteOptions: Boolean
  var DisplaySmartTagButtons: Boolean
  var DoNotPromptForConvert: Boolean
  var DocumentViewDirection: WdDocumentViewDirection
  var EnableHangulHanjaRecentOrdering: Boolean
  var EnableLegacyIMEMode: Boolean
  var EnableLivePreview: Boolean
  var EnableMisusedWordsDictionary: Boolean
  var EnableSound: Boolean
  val EnvelopeFeederInstalled: Boolean
  var FormatScanning: Boolean
  var FrenchReform: WdFrenchSpeller
  var GridDistanceHorizontal: Double
  var GridDistanceVertical: Double
  var GridOriginHorizontal: Double
  var GridOriginVertical: Double
  var HangulHanjaFastConversion: Boolean
  var HebrewMode: WdHebSpellStart
  var IMEAutomaticControl: Boolean
  var INSKeyForOvertype: Boolean
  var INSKeyForPaste: Boolean
  var IgnoreInternetAndFileAddresses: Boolean
  var IgnoreMixedDigits: Boolean
  var IgnoreUppercase: Boolean
  var InlineConversion: Boolean
  var InsertedCellColor: WdCellColor
  var InsertedTextColor: WdColorIndex
  var InsertedTextMark: WdInsertedTextMark
  var InterpretHighAnsi: WdHighAnsiText
  var LabelSmartTags: Boolean
  var LocalNetworkFile: Boolean
  var MapPaperSize: Boolean
  var MatchFuzzyAY: Boolean
  var MatchFuzzyBV: Boolean
  var MatchFuzzyByte: Boolean
  var MatchFuzzyCase: Boolean
  var MatchFuzzyDZ: Boolean
  var MatchFuzzyDash: Boolean
  var MatchFuzzyHF: Boolean
  var MatchFuzzyHiragana: Boolean
  var MatchFuzzyIterationMark: Boolean
  var MatchFuzzyKanji: Boolean
  var MatchFuzzyKiKu: Boolean
  var MatchFuzzyOldKana: Boolean
  var MatchFuzzyProlongedSoundMark: Boolean
  var MatchFuzzyPunctuation: Boolean
  var MatchFuzzySmallKana: Boolean
  var MatchFuzzySpace: Boolean
  var MatchFuzzyTC: Boolean
  var MatchFuzzyZJ: Boolean
  var MeasurementUnit: WdMeasurementUnits
  var MergedCellColor: WdCellColor
  var MonthNames: WdMonthNames
  var MoveFromTextColor: WdColorIndex
  var MoveFromTextMark: WdMoveFromTextMark
  var MoveToTextColor: WdColorIndex
  var MoveToTextMark: WdMoveToTextMark
  var MultipleWordConversionsMode: WdMultipleWordConversionsMode
  var OMathAutoBuildUp: Boolean
  var OMathCopyLF: Boolean
  var OptimizeForWord97byDefault: Boolean
  var Overtype: Boolean
  var Pagination: Boolean
  val Parent: js.Any
  var PasteAdjustParagraphSpacing: Boolean
  var PasteAdjustTableFormatting: Boolean
  var PasteAdjustWordSpacing: Boolean
  var PasteFormatBetweenDocuments: WdPasteOptions
  var PasteFormatBetweenStyledDocuments: WdPasteOptions
  var PasteFormatFromExternalSource: WdPasteOptions
  var PasteFormatWithinDocument: WdPasteOptions
  var PasteMergeFromPPT: Boolean
  var PasteMergeFromXL: Boolean
  var PasteMergeLists: Boolean
  var PasteOptionKeepBulletsAndNumbers: Boolean
  var PasteSmartCutPaste: Boolean
  var PasteSmartStyleBehavior: Boolean
  var PictureEditor: String
  var PictureWrapType: WdWrapTypeMerged
  var PortugalReform: WdPortugueseReform
  var PrecisePositioning: Boolean
  var PrintBackground: Boolean
  var PrintBackgrounds: Boolean
  var PrintComments: Boolean
  var PrintDraft: Boolean
  var PrintDrawingObjects: Boolean
  var PrintEvenPagesInAscendingOrder: Boolean
  var PrintFieldCodes: Boolean
  var PrintHiddenText: Boolean
  var PrintOddPagesInAscendingOrder: Boolean
  var PrintProperties: Boolean
  var PrintReverse: Boolean
  var PrintXMLTag: Boolean
  var PromptUpdateStyle: Boolean
  var RTFInClipboard: Boolean
  var RepeatWord: Boolean
  var ReplaceSelection: Boolean
  var RevisedLinesColor: WdColorIndex
  var RevisedLinesMark: WdRevisedLinesMark
  var RevisedPropertiesColor: WdColorIndex
  var RevisedPropertiesMark: WdRevisedPropertiesMark
  var RevisionsBalloonPrintOrientation: WdRevisionsBalloonPrintOrientation
  var SaveInterval: Double
  var SaveNormalPrompt: Boolean
  var SavePropertiesPrompt: Boolean
  var SendMailAttach: Boolean
  var SequenceCheck: Boolean
  var ShortMenuNames: Boolean
  var ShowControlCharacters: Boolean
  var ShowDevTools: Boolean
  var ShowDiacritics: Boolean
  var ShowFormatError: Boolean
  var ShowMarkupOpenSave: Boolean
  var ShowMenuFloaties: Boolean
  var ShowReadabilityStatistics: Boolean
  var ShowSelectionFloaties: Boolean
  var SmartCursoring: Boolean
  var SmartCutPaste: Boolean
  var SmartParaSelection: Boolean
  var SnapToGrid: Boolean
  var SnapToShapes: Boolean
  var SpanishMode: WdSpanishSpeller
  var SplitCellColor: WdCellColor
  var StoreRSIDOnSave: Boolean
  var StrictFinalYaa: Boolean
  var StrictInitialAlefHamza: Boolean
  var StrictRussianE: Boolean
  var StrictTaaMarboota: Boolean
  var SuggestFromMainDictionaryOnly: Boolean
  var SuggestSpellingCorrections: Boolean
  var TabIndentKey: Boolean
  var TypeNReplace: Boolean
  var UpdateFieldsAtPrint: Boolean
  var UpdateFieldsWithTrackedChangesAtPrint: Boolean
  var UpdateLinksAtOpen: Boolean
  var UpdateLinksAtPrint: Boolean
  var UpdateStyleListBehavior: WdUpdateStyleListBehavior
  var UseCharacterUnit: Boolean
  var UseDiffDiacColor: Boolean
  var UseGermanSpellingReform: Boolean
  var UseNormalStyleForList: Boolean
  var VirusProtection: Boolean
  var VisualSelection: WdVisualSelection
  var WPDocNavKeys: Boolean
  var WPHelp: Boolean
  var WarnBeforeSavingPrintingSendingMarkup: Boolean
  @JSName("Word.Options_typekey")
  var WordDotOptions_typekey: Options
  def DefaultFilePath(Path: WdDefaultFilePath): String
  def SetWPHelpOptions(
    CommandKeyHelp: js.UndefOr[js.Any],
    DocNavigationKeys: js.UndefOr[js.Any],
    MouseSimulation: js.UndefOr[js.Any],
    DemoGuidance: js.UndefOr[js.Any],
    DemoSpeed: js.UndefOr[js.Any],
    HelpType: js.UndefOr[js.Any]
  ): Unit
}

