package typingsSlinky.awsSdkClientCodecommitNode.mergePullRequestByFastForwardExceptionsUnionMod

import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionIntegrityChecksFailedExceptionMod.EncryptionIntegrityChecksFailedException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyAccessDeniedExceptionMod.EncryptionKeyAccessDeniedException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyDisabledExceptionMod.EncryptionKeyDisabledException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyNotFoundExceptionMod.EncryptionKeyNotFoundException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyUnavailableExceptionMod.EncryptionKeyUnavailableException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidCommitIdExceptionMod.InvalidCommitIdException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidPullRequestIdExceptionMod.InvalidPullRequestIdException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryNameExceptionMod.InvalidRepositoryNameException
import typingsSlinky.awsSdkClientCodecommitNode.typesManualMergeRequiredExceptionMod.ManualMergeRequiredException
import typingsSlinky.awsSdkClientCodecommitNode.typesPullRequestAlreadyClosedExceptionMod.PullRequestAlreadyClosedException
import typingsSlinky.awsSdkClientCodecommitNode.typesPullRequestDoesNotExistExceptionMod.PullRequestDoesNotExistException
import typingsSlinky.awsSdkClientCodecommitNode.typesPullRequestIdRequiredExceptionMod.PullRequestIdRequiredException
import typingsSlinky.awsSdkClientCodecommitNode.typesReferenceDoesNotExistExceptionMod.ReferenceDoesNotExistException
import typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryDoesNotExistExceptionMod.RepositoryDoesNotExistException
import typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryNameRequiredExceptionMod.RepositoryNameRequiredException
import typingsSlinky.awsSdkClientCodecommitNode.typesTipOfSourceReferenceIsDifferentExceptionMod.TipOfSourceReferenceIsDifferentException
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - typingsSlinky.awsSdkClientCodecommitNode.typesManualMergeRequiredExceptionMod.ManualMergeRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesPullRequestAlreadyClosedExceptionMod.PullRequestAlreadyClosedException
  - typingsSlinky.awsSdkClientCodecommitNode.typesPullRequestDoesNotExistExceptionMod.PullRequestDoesNotExistException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidPullRequestIdExceptionMod.InvalidPullRequestIdException
  - typingsSlinky.awsSdkClientCodecommitNode.typesPullRequestIdRequiredExceptionMod.PullRequestIdRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesTipOfSourceReferenceIsDifferentExceptionMod.TipOfSourceReferenceIsDifferentException
  - typingsSlinky.awsSdkClientCodecommitNode.typesReferenceDoesNotExistExceptionMod.ReferenceDoesNotExistException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidCommitIdExceptionMod.InvalidCommitIdException
  - typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryNameRequiredExceptionMod.RepositoryNameRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryNameExceptionMod.InvalidRepositoryNameException
  - typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryDoesNotExistExceptionMod.RepositoryDoesNotExistException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionIntegrityChecksFailedExceptionMod.EncryptionIntegrityChecksFailedException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyAccessDeniedExceptionMod.EncryptionKeyAccessDeniedException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyDisabledExceptionMod.EncryptionKeyDisabledException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyNotFoundExceptionMod.EncryptionKeyNotFoundException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyUnavailableExceptionMod.EncryptionKeyUnavailableException
*/
trait MergePullRequestByFastForwardExceptionsUnion extends js.Object

object MergePullRequestByFastForwardExceptionsUnion {
  @scala.inline
  implicit def apply(value: EncryptionIntegrityChecksFailedException): MergePullRequestByFastForwardExceptionsUnion = value.asInstanceOf[MergePullRequestByFastForwardExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyAccessDeniedException): MergePullRequestByFastForwardExceptionsUnion = value.asInstanceOf[MergePullRequestByFastForwardExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyDisabledException): MergePullRequestByFastForwardExceptionsUnion = value.asInstanceOf[MergePullRequestByFastForwardExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyNotFoundException): MergePullRequestByFastForwardExceptionsUnion = value.asInstanceOf[MergePullRequestByFastForwardExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyUnavailableException): MergePullRequestByFastForwardExceptionsUnion = value.asInstanceOf[MergePullRequestByFastForwardExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidCommitIdException): MergePullRequestByFastForwardExceptionsUnion = value.asInstanceOf[MergePullRequestByFastForwardExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidPullRequestIdException): MergePullRequestByFastForwardExceptionsUnion = value.asInstanceOf[MergePullRequestByFastForwardExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidRepositoryNameException): MergePullRequestByFastForwardExceptionsUnion = value.asInstanceOf[MergePullRequestByFastForwardExceptionsUnion]
  @scala.inline
  implicit def apply(value: ManualMergeRequiredException): MergePullRequestByFastForwardExceptionsUnion = value.asInstanceOf[MergePullRequestByFastForwardExceptionsUnion]
  @scala.inline
  implicit def apply(value: PullRequestAlreadyClosedException): MergePullRequestByFastForwardExceptionsUnion = value.asInstanceOf[MergePullRequestByFastForwardExceptionsUnion]
  @scala.inline
  implicit def apply(value: PullRequestDoesNotExistException): MergePullRequestByFastForwardExceptionsUnion = value.asInstanceOf[MergePullRequestByFastForwardExceptionsUnion]
  @scala.inline
  implicit def apply(value: PullRequestIdRequiredException): MergePullRequestByFastForwardExceptionsUnion = value.asInstanceOf[MergePullRequestByFastForwardExceptionsUnion]
  @scala.inline
  implicit def apply(value: ReferenceDoesNotExistException): MergePullRequestByFastForwardExceptionsUnion = value.asInstanceOf[MergePullRequestByFastForwardExceptionsUnion]
  @scala.inline
  implicit def apply(value: RepositoryDoesNotExistException): MergePullRequestByFastForwardExceptionsUnion = value.asInstanceOf[MergePullRequestByFastForwardExceptionsUnion]
  @scala.inline
  implicit def apply(value: RepositoryNameRequiredException): MergePullRequestByFastForwardExceptionsUnion = value.asInstanceOf[MergePullRequestByFastForwardExceptionsUnion]
  @scala.inline
  implicit def apply(value: TipOfSourceReferenceIsDifferentException): MergePullRequestByFastForwardExceptionsUnion = value.asInstanceOf[MergePullRequestByFastForwardExceptionsUnion]
}

