package typingsSlinky.atAwsDashSdkClientDashLambdaDashNode.typesTooManyRequestsExceptionMod

import typingsSlinky.atAwsDashSdkClientDashLambdaDashNode.typesAddPermissionExceptionsUnionMod.AddPermissionExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashLambdaDashNode.typesCreateAliasExceptionsUnionMod.CreateAliasExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashLambdaDashNode.typesCreateEventSourceMappingExceptionsUnionMod.CreateEventSourceMappingExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashLambdaDashNode.typesCreateFunctionExceptionsUnionMod.CreateFunctionExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashLambdaDashNode.typesDeleteAliasExceptionsUnionMod.DeleteAliasExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashLambdaDashNode.typesDeleteEventSourceMappingExceptionsUnionMod.DeleteEventSourceMappingExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashLambdaDashNode.typesDeleteFunctionConcurrencyExceptionsUnionMod.DeleteFunctionConcurrencyExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashLambdaDashNode.typesDeleteFunctionExceptionsUnionMod.DeleteFunctionExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashLambdaDashNode.typesGetAccountSettingsExceptionsUnionMod.GetAccountSettingsExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashLambdaDashNode.typesGetAliasExceptionsUnionMod.GetAliasExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashLambdaDashNode.typesGetEventSourceMappingExceptionsUnionMod.GetEventSourceMappingExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashLambdaDashNode.typesGetFunctionConfigurationExceptionsUnionMod.GetFunctionConfigurationExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashLambdaDashNode.typesGetFunctionExceptionsUnionMod.GetFunctionExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashLambdaDashNode.typesGetPolicyExceptionsUnionMod.GetPolicyExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashLambdaDashNode.typesInvokeExceptionsUnionMod.InvokeExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashLambdaDashNode.typesListAliasesExceptionsUnionMod.ListAliasesExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashLambdaDashNode.typesListEventSourceMappingsExceptionsUnionMod.ListEventSourceMappingsExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashLambdaDashNode.typesListFunctionsExceptionsUnionMod.ListFunctionsExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashLambdaDashNode.typesListTagsExceptionsUnionMod.ListTagsExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashLambdaDashNode.typesListVersionsByFunctionExceptionsUnionMod.ListVersionsByFunctionExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashLambdaDashNode.typesPublishVersionExceptionsUnionMod.PublishVersionExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashLambdaDashNode.typesPutFunctionConcurrencyExceptionsUnionMod.PutFunctionConcurrencyExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashLambdaDashNode.typesRemovePermissionExceptionsUnionMod.RemovePermissionExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashLambdaDashNode.typesTagResourceExceptionsUnionMod.TagResourceExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashLambdaDashNode.typesUntagResourceExceptionsUnionMod.UntagResourceExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashLambdaDashNode.typesUpdateAliasExceptionsUnionMod.UpdateAliasExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashLambdaDashNode.typesUpdateEventSourceMappingExceptionsUnionMod.UpdateEventSourceMappingExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashLambdaDashNode.typesUpdateFunctionCodeExceptionsUnionMod.UpdateFunctionCodeExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashLambdaDashNode.typesUpdateFunctionConfigurationExceptionsUnionMod.UpdateFunctionConfigurationExceptionsUnion
import typingsSlinky.atAwsDashSdkTypes.buildExceptionMod.ServiceException
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait TooManyRequestsException
  extends ServiceException[_TooManyRequestsExceptionDetails]
     with AddPermissionExceptionsUnion
     with CreateAliasExceptionsUnion
     with CreateEventSourceMappingExceptionsUnion
     with CreateFunctionExceptionsUnion
     with DeleteAliasExceptionsUnion
     with DeleteEventSourceMappingExceptionsUnion
     with DeleteFunctionConcurrencyExceptionsUnion
     with DeleteFunctionExceptionsUnion
     with GetAccountSettingsExceptionsUnion
     with GetAliasExceptionsUnion
     with GetEventSourceMappingExceptionsUnion
     with GetFunctionConfigurationExceptionsUnion
     with GetFunctionExceptionsUnion
     with GetPolicyExceptionsUnion
     with InvokeExceptionsUnion
     with ListAliasesExceptionsUnion
     with ListEventSourceMappingsExceptionsUnion
     with ListFunctionsExceptionsUnion
     with ListTagsExceptionsUnion
     with ListVersionsByFunctionExceptionsUnion
     with PublishVersionExceptionsUnion
     with PutFunctionConcurrencyExceptionsUnion
     with RemovePermissionExceptionsUnion
     with TagResourceExceptionsUnion
     with UntagResourceExceptionsUnion
     with UpdateAliasExceptionsUnion
     with UpdateEventSourceMappingExceptionsUnion
     with UpdateFunctionCodeExceptionsUnion
     with UpdateFunctionConfigurationExceptionsUnion {
  @JSName("name")
  var name_TooManyRequestsException: typingsSlinky.atAwsDashSdkClientDashLambdaDashNode.atAwsDashSdkClientDashLambdaDashNodeStrings.TooManyRequestsException = js.native
}

