package typingsSlinky.atAngularCompiler.srcCompilerMod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@JSImport("@angular/compiler/src/compiler", "R3Identifiers")
@js.native
class R3Identifiers ()
  extends typingsSlinky.atAngularCompiler.srcRender3R3UnderscoreIdentifiersMod.Identifiers

/* static members */
@JSImport("@angular/compiler/src/compiler", "R3Identifiers")
@js.native
object R3Identifiers extends js.Object {
  var BaseDef: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var ComponentDefWithMeta: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var DirectiveDefWithMeta: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var InheritDefinitionFeature: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var InjectorDef: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var NEW_METHOD: String = js.native
  var NgModuleDefWithMeta: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var NgOnChangesFeature: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var PATCH_DEPS: String = js.native
  var PipeDefWithMeta: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var ProvidersFeature: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var TRANSFORM_METHOD: String = js.native
  var allocHostVars: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var attribute: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var attributeInterpolate1: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var attributeInterpolate2: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var attributeInterpolate3: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var attributeInterpolate4: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var attributeInterpolate5: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var attributeInterpolate6: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var attributeInterpolate7: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var attributeInterpolate8: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var attributeInterpolateV: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var classMap: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var classMapInterpolate1: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var classMapInterpolate2: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var classMapInterpolate3: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var classMapInterpolate4: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var classMapInterpolate5: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var classMapInterpolate6: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var classMapInterpolate7: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var classMapInterpolate8: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var classMapInterpolateV: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var classProp: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var componentHostSyntheticListener: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var containerCreate: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var contentQuery: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var defaultStyleSanitizer: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var defineBase: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var defineComponent: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var defineDirective: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var defineInjector: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var defineNgModule: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var definePipe: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var directiveInject: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var disableBindings: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var element: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var elementContainer: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var elementContainerEnd: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var elementContainerStart: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var elementEnd: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var elementHostAttrs: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var elementStart: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var enableBindings: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var getCurrentView: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var getFactoryOf: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var getInheritedFactory: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var hostProperty: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var i18n: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var i18nApply: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var i18nAttributes: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var i18nEnd: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var i18nExp: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var i18nLocalize: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var i18nPostprocess: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var i18nStart: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var inject: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var injectAttribute: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var injectPipeChangeDetectorRef: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var listener: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var load: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var loadContentQuery: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var loadViewQuery: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var namespaceHTML: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var namespaceMathML: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var namespaceSVG: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var nextContext: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var pipe: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var pipeBind1: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var pipeBind2: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var pipeBind3: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var pipeBind4: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var pipeBindV: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var projection: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var projectionDef: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var property: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var propertyInterpolate: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var propertyInterpolate1: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var propertyInterpolate2: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var propertyInterpolate3: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var propertyInterpolate4: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var propertyInterpolate5: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var propertyInterpolate6: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var propertyInterpolate7: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var propertyInterpolate8: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var propertyInterpolateV: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var pureFunction0: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var pureFunction1: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var pureFunction2: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var pureFunction3: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var pureFunction4: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var pureFunction5: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var pureFunction6: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var pureFunction7: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var pureFunction8: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var pureFunctionV: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var queryRefresh: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var reference: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var resolveBody: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var resolveDocument: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var resolveWindow: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var restoreView: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var sanitizeHtml: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var sanitizeResourceUrl: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var sanitizeScript: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var sanitizeStyle: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var sanitizeUrl: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var sanitizeUrlOrResourceUrl: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var select: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var setComponentScope: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var setNgModuleScope: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var staticContentQuery: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var staticViewQuery: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var styleMap: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var styleProp: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var stylePropInterpolate1: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var stylePropInterpolate2: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var stylePropInterpolate3: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var stylePropInterpolate4: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var stylePropInterpolate5: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var stylePropInterpolate6: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var stylePropInterpolate7: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var stylePropInterpolate8: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var stylePropInterpolateV: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var styleSanitizer: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var styling: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var stylingApply: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var templateCreate: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var templateRefExtractor: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var text: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var textBinding: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var textInterpolate: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var textInterpolate1: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var textInterpolate2: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var textInterpolate3: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var textInterpolate4: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var textInterpolate5: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var textInterpolate6: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var textInterpolate7: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var textInterpolate8: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var textInterpolateV: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var updateSyntheticHostBinding: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
  var viewQuery: typingsSlinky.atAngularCompiler.srcOutputOutputUnderscoreAstMod.ExternalReference = js.native
}

