package typingsSlinky.awsSdkClientKmsBrowser.generateDataKeyWithoutPlaintextExceptionsUnionMod

import typingsSlinky.awsSdkClientKmsBrowser.typesDependencyTimeoutExceptionMod.DependencyTimeoutException
import typingsSlinky.awsSdkClientKmsBrowser.typesDisabledExceptionMod.DisabledException
import typingsSlinky.awsSdkClientKmsBrowser.typesInvalidGrantTokenExceptionMod.InvalidGrantTokenException
import typingsSlinky.awsSdkClientKmsBrowser.typesInvalidKeyUsageExceptionMod.InvalidKeyUsageException
import typingsSlinky.awsSdkClientKmsBrowser.typesKeyUnavailableExceptionMod.KeyUnavailableException
import typingsSlinky.awsSdkClientKmsBrowser.typesKmsinternalexceptionMod.KMSInternalException
import typingsSlinky.awsSdkClientKmsBrowser.typesKmsinvalidstateexceptionMod.KMSInvalidStateException
import typingsSlinky.awsSdkClientKmsBrowser.typesNotFoundExceptionMod.NotFoundException
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - typingsSlinky.awsSdkClientKmsBrowser.typesNotFoundExceptionMod.NotFoundException
  - typingsSlinky.awsSdkClientKmsBrowser.typesDisabledExceptionMod.DisabledException
  - typingsSlinky.awsSdkClientKmsBrowser.typesKeyUnavailableExceptionMod.KeyUnavailableException
  - typingsSlinky.awsSdkClientKmsBrowser.typesDependencyTimeoutExceptionMod.DependencyTimeoutException
  - typingsSlinky.awsSdkClientKmsBrowser.typesInvalidKeyUsageExceptionMod.InvalidKeyUsageException
  - typingsSlinky.awsSdkClientKmsBrowser.typesInvalidGrantTokenExceptionMod.InvalidGrantTokenException
  - typingsSlinky.awsSdkClientKmsBrowser.typesKmsinternalexceptionMod.KMSInternalException
  - typingsSlinky.awsSdkClientKmsBrowser.typesKmsinvalidstateexceptionMod.KMSInvalidStateException
*/
trait GenerateDataKeyWithoutPlaintextExceptionsUnion extends js.Object

object GenerateDataKeyWithoutPlaintextExceptionsUnion {
  @scala.inline
  implicit def apply(value: DependencyTimeoutException): GenerateDataKeyWithoutPlaintextExceptionsUnion = value.asInstanceOf[GenerateDataKeyWithoutPlaintextExceptionsUnion]
  @scala.inline
  implicit def apply(value: DisabledException): GenerateDataKeyWithoutPlaintextExceptionsUnion = value.asInstanceOf[GenerateDataKeyWithoutPlaintextExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidGrantTokenException): GenerateDataKeyWithoutPlaintextExceptionsUnion = value.asInstanceOf[GenerateDataKeyWithoutPlaintextExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidKeyUsageException): GenerateDataKeyWithoutPlaintextExceptionsUnion = value.asInstanceOf[GenerateDataKeyWithoutPlaintextExceptionsUnion]
  @scala.inline
  implicit def apply(value: KMSInternalException): GenerateDataKeyWithoutPlaintextExceptionsUnion = value.asInstanceOf[GenerateDataKeyWithoutPlaintextExceptionsUnion]
  @scala.inline
  implicit def apply(value: KMSInvalidStateException): GenerateDataKeyWithoutPlaintextExceptionsUnion = value.asInstanceOf[GenerateDataKeyWithoutPlaintextExceptionsUnion]
  @scala.inline
  implicit def apply(value: KeyUnavailableException): GenerateDataKeyWithoutPlaintextExceptionsUnion = value.asInstanceOf[GenerateDataKeyWithoutPlaintextExceptionsUnion]
  @scala.inline
  implicit def apply(value: NotFoundException): GenerateDataKeyWithoutPlaintextExceptionsUnion = value.asInstanceOf[GenerateDataKeyWithoutPlaintextExceptionsUnion]
}

