package typingsSlinky.awsSdkClientCodecommitNode.updatePullRequestTitleExceptionsUnionMod

import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidPullRequestIdExceptionMod.InvalidPullRequestIdException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidTitleExceptionMod.InvalidTitleException
import typingsSlinky.awsSdkClientCodecommitNode.typesPullRequestAlreadyClosedExceptionMod.PullRequestAlreadyClosedException
import typingsSlinky.awsSdkClientCodecommitNode.typesPullRequestDoesNotExistExceptionMod.PullRequestDoesNotExistException
import typingsSlinky.awsSdkClientCodecommitNode.typesPullRequestIdRequiredExceptionMod.PullRequestIdRequiredException
import typingsSlinky.awsSdkClientCodecommitNode.typesTitleRequiredExceptionMod.TitleRequiredException
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - typingsSlinky.awsSdkClientCodecommitNode.typesPullRequestDoesNotExistExceptionMod.PullRequestDoesNotExistException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidPullRequestIdExceptionMod.InvalidPullRequestIdException
  - typingsSlinky.awsSdkClientCodecommitNode.typesPullRequestIdRequiredExceptionMod.PullRequestIdRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesTitleRequiredExceptionMod.TitleRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidTitleExceptionMod.InvalidTitleException
  - typingsSlinky.awsSdkClientCodecommitNode.typesPullRequestAlreadyClosedExceptionMod.PullRequestAlreadyClosedException
*/
trait UpdatePullRequestTitleExceptionsUnion extends js.Object

object UpdatePullRequestTitleExceptionsUnion {
  @scala.inline
  implicit def apply(value: InvalidPullRequestIdException): UpdatePullRequestTitleExceptionsUnion = value.asInstanceOf[UpdatePullRequestTitleExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidTitleException): UpdatePullRequestTitleExceptionsUnion = value.asInstanceOf[UpdatePullRequestTitleExceptionsUnion]
  @scala.inline
  implicit def apply(value: PullRequestAlreadyClosedException): UpdatePullRequestTitleExceptionsUnion = value.asInstanceOf[UpdatePullRequestTitleExceptionsUnion]
  @scala.inline
  implicit def apply(value: PullRequestDoesNotExistException): UpdatePullRequestTitleExceptionsUnion = value.asInstanceOf[UpdatePullRequestTitleExceptionsUnion]
  @scala.inline
  implicit def apply(value: PullRequestIdRequiredException): UpdatePullRequestTitleExceptionsUnion = value.asInstanceOf[UpdatePullRequestTitleExceptionsUnion]
  @scala.inline
  implicit def apply(value: TitleRequiredException): UpdatePullRequestTitleExceptionsUnion = value.asInstanceOf[UpdatePullRequestTitleExceptionsUnion]
}

