package typingsSlinky.javascriptDashObfuscator

import typingsSlinky.javascriptDashObfuscator.javascriptDashObfuscatorStrings.compact
import typingsSlinky.javascriptDashObfuscator.javascriptDashObfuscatorStrings.controlFlowFlattening
import typingsSlinky.javascriptDashObfuscator.javascriptDashObfuscatorStrings.controlFlowFlatteningThreshold
import typingsSlinky.javascriptDashObfuscator.javascriptDashObfuscatorStrings.deadCodeInjection
import typingsSlinky.javascriptDashObfuscator.javascriptDashObfuscatorStrings.deadCodeInjectionThreshold
import typingsSlinky.javascriptDashObfuscator.javascriptDashObfuscatorStrings.debugProtection
import typingsSlinky.javascriptDashObfuscator.javascriptDashObfuscatorStrings.debugProtectionInterval
import typingsSlinky.javascriptDashObfuscator.javascriptDashObfuscatorStrings.disableConsoleOutput
import typingsSlinky.javascriptDashObfuscator.javascriptDashObfuscatorStrings.domainLock
import typingsSlinky.javascriptDashObfuscator.javascriptDashObfuscatorStrings.identifierNamesGenerator
import typingsSlinky.javascriptDashObfuscator.javascriptDashObfuscatorStrings.identifiersPrefix
import typingsSlinky.javascriptDashObfuscator.javascriptDashObfuscatorStrings.inputFileName
import typingsSlinky.javascriptDashObfuscator.javascriptDashObfuscatorStrings.log
import typingsSlinky.javascriptDashObfuscator.javascriptDashObfuscatorStrings.renameGlobals
import typingsSlinky.javascriptDashObfuscator.javascriptDashObfuscatorStrings.reservedNames
import typingsSlinky.javascriptDashObfuscator.javascriptDashObfuscatorStrings.reservedStrings
import typingsSlinky.javascriptDashObfuscator.javascriptDashObfuscatorStrings.rotateStringArray
import typingsSlinky.javascriptDashObfuscator.javascriptDashObfuscatorStrings.seed
import typingsSlinky.javascriptDashObfuscator.javascriptDashObfuscatorStrings.selfDefending
import typingsSlinky.javascriptDashObfuscator.javascriptDashObfuscatorStrings.sourceMap
import typingsSlinky.javascriptDashObfuscator.javascriptDashObfuscatorStrings.sourceMapBaseUrl
import typingsSlinky.javascriptDashObfuscator.javascriptDashObfuscatorStrings.sourceMapFileName
import typingsSlinky.javascriptDashObfuscator.javascriptDashObfuscatorStrings.sourceMapMode
import typingsSlinky.javascriptDashObfuscator.javascriptDashObfuscatorStrings.stringArray
import typingsSlinky.javascriptDashObfuscator.javascriptDashObfuscatorStrings.stringArrayEncoding
import typingsSlinky.javascriptDashObfuscator.javascriptDashObfuscatorStrings.stringArrayThreshold
import typingsSlinky.javascriptDashObfuscator.javascriptDashObfuscatorStrings.target
import typingsSlinky.javascriptDashObfuscator.javascriptDashObfuscatorStrings.transformObjectKeys
import typingsSlinky.javascriptDashObfuscator.javascriptDashObfuscatorStrings.unicodeEscapeSequence
import typingsSlinky.javascriptDashObfuscator.srcInterfacesOptionsIOptionsMod.IOptions
import typingsSlinky.javascriptDashObfuscator.srcTypesTObjectMod.TObject
import typingsSlinky.std.Partial
import typingsSlinky.std.Pick
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@JSImport("javascript-obfuscator/src/types/options/TInputOptions", JSImport.Namespace)
@js.native
object srcTypesOptionsTInputOptionsMod extends js.Object {
  type TInputOptions = (Partial[
    Pick[
      IOptions, 
      compact | controlFlowFlattening | controlFlowFlatteningThreshold | deadCodeInjection | deadCodeInjectionThreshold | debugProtection | debugProtectionInterval | disableConsoleOutput | domainLock | identifierNamesGenerator | identifiersPrefix | inputFileName | log | renameGlobals | reservedNames | reservedStrings | rotateStringArray | seed | selfDefending | sourceMap | sourceMapBaseUrl | sourceMapFileName | sourceMapMode | stringArray | stringArrayEncoding | stringArrayThreshold | target | transformObjectKeys | unicodeEscapeSequence
    ]
  ]) with TObject[_]
}

