package typingsSlinky.jsonSchemaTyped

import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

package object mod {
  
  @scala.inline
  def JSONSchemaKeys: js.Array[
    typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.$comment | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.$id | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.$ref | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.$schema | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.additionalItems | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.additionalProperties | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.allOf | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.anyOf | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.const | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.contains | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.contentEncoding | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.contentMediaType | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.default | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.definitions | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.dependencies | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.description | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.`else` | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.enum | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.examples | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.exclusiveMaximum | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.exclusiveMinimum | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.format | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.`if` | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.items | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.maximum | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.maxItems | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.maxLength | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.maxProperties | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.minimum | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.minLength | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.minItems | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.minProperties | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.multipleOf | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.not | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.oneOf | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.pattern | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.patternProperties | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.properties | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.propertyNames | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.readOnly | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.required | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.`then` | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.title | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.`type` | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.uniqueItems | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.writeOnly
  ] = typingsSlinky.jsonSchemaTyped.mod.^.asInstanceOf[js.Dynamic].selectDynamic("JSONSchemaKeys").asInstanceOf[js.Array[
    typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.$comment | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.$id | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.$ref | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.$schema | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.additionalItems | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.additionalProperties | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.allOf | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.anyOf | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.const | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.contains | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.contentEncoding | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.contentMediaType | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.default | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.definitions | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.dependencies | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.description | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.`else` | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.enum | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.examples | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.exclusiveMaximum | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.exclusiveMinimum | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.format | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.`if` | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.items | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.maximum | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.maxItems | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.maxLength | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.maxProperties | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.minimum | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.minLength | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.minItems | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.minProperties | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.multipleOf | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.not | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.oneOf | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.pattern | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.patternProperties | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.properties | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.propertyNames | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.readOnly | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.required | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.`then` | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.title | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.`type` | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.uniqueItems | typingsSlinky.jsonSchemaTyped.jsonSchemaTypedStrings.writeOnly
  ]]
  
  /* Rewritten from type alias, can be one of: 
    - typingsSlinky.jsonSchemaTyped.mod.JSONSchemaTypeName
    - typingsSlinky.jsonSchemaTyped.mod.JSONSchemaType
    - js.Array[
  typingsSlinky.jsonSchemaTyped.mod.JSONSchemaType | typingsSlinky.jsonSchemaTyped.mod.JSONSchemaTypeName]
  */
  type JSONSchemaTypeValue = typingsSlinky.jsonSchemaTyped.mod._JSONSchemaTypeValue | (js.Array[
    typingsSlinky.jsonSchemaTyped.mod.JSONSchemaType | typingsSlinky.jsonSchemaTyped.mod.JSONSchemaTypeName
  ])
}
