package typingsSlinky.atAngularCore

import typingsSlinky.atAngularCore.schematicsMigrationsStaticDashQueriesAngularNgUnderscoreQueryUnderscoreVisitorMod.ClassMetadataMap
import typingsSlinky.atAngularCore.schematicsMigrationsStaticDashQueriesStrategiesUsageUnderscoreStrategyDeclarationUnderscoreUsageUnderscoreVisitorMod.FunctionContext
import typingsSlinky.typescript.typescriptMod.ClassDeclaration
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@JSImport("@angular/core/schematics/migrations/static-queries/strategies/usage_strategy/super_class_context", JSImport.Namespace)
@js.native
object schematicsMigrationsStaticDashQueriesStrategiesUsageUnderscoreStrategySuperUnderscoreClassUnderscoreContextMod extends js.Object {
  def updateSuperClassAbstractMembersContext(baseClass: ClassDeclaration, context: FunctionContext, classMetadataMap: ClassMetadataMap): Unit = js.native
}

