package typingsSlinky.semanticDashUiDashReact.distCommonjsElementsPlaceholderPlaceholderMod

import typingsSlinky.react.reactMod.FunctionComponent
import typingsSlinky.semanticDashUiDashReact.distCommonjsElementsPlaceholderPlaceholderHeaderMod.PlaceholderHeaderComponent
import typingsSlinky.semanticDashUiDashReact.distCommonjsElementsPlaceholderPlaceholderImageMod.PlaceholderImageComponent
import typingsSlinky.semanticDashUiDashReact.distCommonjsElementsPlaceholderPlaceholderLineMod.PlaceholderLineComponent
import typingsSlinky.semanticDashUiDashReact.distCommonjsElementsPlaceholderPlaceholderParagraphMod.PlaceholderParagraphComponent
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait PlaceholderComponent extends FunctionComponent[PlaceholderProps] {
  var Header: PlaceholderHeaderComponent = js.native
  var Image: PlaceholderImageComponent = js.native
  var Line: PlaceholderLineComponent = js.native
  var Paragraph: PlaceholderParagraphComponent = js.native
}

