package typingsSlinky.dexie.mod.Dexie

import typingsSlinky.dexie.dexieStrings.Error
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

// errnames - handy spellcheck in switch (error.name) {} cases.        
@JSImport("dexie", "Dexie.errnames")
@js.native
object errnames extends js.Object {
  var Abort: typingsSlinky.dexie.dexieStrings.AbortError = js.native
  var Constraint: typingsSlinky.dexie.dexieStrings.ConstraintError = js.native
  var Data: typingsSlinky.dexie.dexieStrings.DataError = js.native
  var DataClone: typingsSlinky.dexie.dexieStrings.DataCloneError = js.native
  var DatabaseClosed: typingsSlinky.dexie.dexieStrings.DatabaseClosedError = js.native
  var Internal: typingsSlinky.dexie.dexieStrings.InternalError = js.native
  var InvalidAccess: typingsSlinky.dexie.dexieStrings.InvalidAccessError = js.native
  var InvalidArgument: typingsSlinky.dexie.dexieStrings.InvalidArgumentError = js.native
  var InvalidState: typingsSlinky.dexie.dexieStrings.InvalidStateError = js.native
  var InvalidTable: typingsSlinky.dexie.dexieStrings.InvalidTableError = js.native
  var MissingAPI: typingsSlinky.dexie.dexieStrings.MissingAPIError = js.native
  // Dexie-specific error names:
  var Modify: typingsSlinky.dexie.dexieStrings.ModifyError = js.native
  var NoSuchDatabase: typingsSlinky.dexie.dexieStrings.NoSuchDatabaseError = js.native
  var NotFound: typingsSlinky.dexie.dexieStrings.NotFoundError = js.native
  var OpenFailed: typingsSlinky.dexie.dexieStrings.OpenFailedError = js.native
  var QuotaExceeded: typingsSlinky.dexie.dexieStrings.QuotaExceededError = js.native
  var ReadOnly: typingsSlinky.dexie.dexieStrings.ReadOnlyError = js.native
  var Schema: typingsSlinky.dexie.dexieStrings.SchemaError = js.native
  var SubTransaction: Error = js.native
  var Syntax: typingsSlinky.dexie.dexieStrings.SyntaxError = js.native
  var Timeout: typingsSlinky.dexie.dexieStrings.TimeoutError = js.native
  var TransactionInactive: typingsSlinky.dexie.dexieStrings.TransactionInactiveError = js.native
  // Error names generated by indexedDB:
  var Unknown: typingsSlinky.dexie.dexieStrings.UnknownError = js.native
  var Unsupported: typingsSlinky.dexie.dexieStrings.UnsupportedError = js.native
  var Upgrade: typingsSlinky.dexie.dexieStrings.UpgradeError = js.native
  var Version: typingsSlinky.dexie.dexieStrings.VersionError = js.native
  var VersionChange: typingsSlinky.dexie.dexieStrings.VersionChangeError = js.native
}

