package typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesInvalidParameterValueExceptionMod

import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesAbortMultipartUploadExceptionsUnionMod.AbortMultipartUploadExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesAbortVaultLockExceptionsUnionMod.AbortVaultLockExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesAddTagsToVaultExceptionsUnionMod.AddTagsToVaultExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesCompleteMultipartUploadExceptionsUnionMod.CompleteMultipartUploadExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesCompleteVaultLockExceptionsUnionMod.CompleteVaultLockExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesCreateVaultExceptionsUnionMod.CreateVaultExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesDeleteArchiveExceptionsUnionMod.DeleteArchiveExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesDeleteVaultAccessPolicyExceptionsUnionMod.DeleteVaultAccessPolicyExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesDeleteVaultExceptionsUnionMod.DeleteVaultExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesDeleteVaultNotificationsExceptionsUnionMod.DeleteVaultNotificationsExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesDescribeJobExceptionsUnionMod.DescribeJobExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesDescribeVaultExceptionsUnionMod.DescribeVaultExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesGetDataRetrievalPolicyExceptionsUnionMod.GetDataRetrievalPolicyExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesGetJobOutputExceptionsUnionMod.GetJobOutputExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesGetVaultAccessPolicyExceptionsUnionMod.GetVaultAccessPolicyExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesGetVaultLockExceptionsUnionMod.GetVaultLockExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesGetVaultNotificationsExceptionsUnionMod.GetVaultNotificationsExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesInitiateJobExceptionsUnionMod.InitiateJobExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesInitiateMultipartUploadExceptionsUnionMod.InitiateMultipartUploadExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesInitiateVaultLockExceptionsUnionMod.InitiateVaultLockExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesListJobsExceptionsUnionMod.ListJobsExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesListMultipartUploadsExceptionsUnionMod.ListMultipartUploadsExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesListPartsExceptionsUnionMod.ListPartsExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesListProvisionedCapacityExceptionsUnionMod.ListProvisionedCapacityExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesListTagsForVaultExceptionsUnionMod.ListTagsForVaultExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesListVaultsExceptionsUnionMod.ListVaultsExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesPurchaseProvisionedCapacityExceptionsUnionMod.PurchaseProvisionedCapacityExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesRemoveTagsFromVaultExceptionsUnionMod.RemoveTagsFromVaultExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesSetDataRetrievalPolicyExceptionsUnionMod.SetDataRetrievalPolicyExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesSetVaultAccessPolicyExceptionsUnionMod.SetVaultAccessPolicyExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesSetVaultNotificationsExceptionsUnionMod.SetVaultNotificationsExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesUploadArchiveExceptionsUnionMod.UploadArchiveExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.typesUploadMultipartPartExceptionsUnionMod.UploadMultipartPartExceptionsUnion
import typingsSlinky.atAwsDashSdkTypes.buildExceptionMod.ServiceException
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait InvalidParameterValueException
  extends ServiceException[_InvalidParameterValueExceptionDetails]
     with AbortMultipartUploadExceptionsUnion
     with AbortVaultLockExceptionsUnion
     with AddTagsToVaultExceptionsUnion
     with CompleteMultipartUploadExceptionsUnion
     with CompleteVaultLockExceptionsUnion
     with CreateVaultExceptionsUnion
     with DeleteArchiveExceptionsUnion
     with DeleteVaultAccessPolicyExceptionsUnion
     with DeleteVaultExceptionsUnion
     with DeleteVaultNotificationsExceptionsUnion
     with DescribeJobExceptionsUnion
     with DescribeVaultExceptionsUnion
     with GetDataRetrievalPolicyExceptionsUnion
     with GetJobOutputExceptionsUnion
     with GetVaultAccessPolicyExceptionsUnion
     with GetVaultLockExceptionsUnion
     with GetVaultNotificationsExceptionsUnion
     with InitiateJobExceptionsUnion
     with InitiateMultipartUploadExceptionsUnion
     with InitiateVaultLockExceptionsUnion
     with ListJobsExceptionsUnion
     with ListMultipartUploadsExceptionsUnion
     with ListPartsExceptionsUnion
     with ListProvisionedCapacityExceptionsUnion
     with ListTagsForVaultExceptionsUnion
     with ListVaultsExceptionsUnion
     with PurchaseProvisionedCapacityExceptionsUnion
     with RemoveTagsFromVaultExceptionsUnion
     with SetDataRetrievalPolicyExceptionsUnion
     with SetVaultAccessPolicyExceptionsUnion
     with SetVaultNotificationsExceptionsUnion
     with UploadArchiveExceptionsUnion
     with UploadMultipartPartExceptionsUnion {
  @JSName("name")
  var name_InvalidParameterValueException: typingsSlinky.atAwsDashSdkClientDashGlacierDashNode.atAwsDashSdkClientDashGlacierDashNodeStrings.InvalidParameterValueException = js.native
}

