package typingsSlinky.atAwsDashSdkClientDashXrayDashNode.typesInvalidRequestExceptionMod

import typingsSlinky.atAwsDashSdkClientDashXrayDashNode.typesBatchGetTracesExceptionsUnionMod.BatchGetTracesExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashXrayDashNode.typesCreateSamplingRuleExceptionsUnionMod.CreateSamplingRuleExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashXrayDashNode.typesDeleteSamplingRuleExceptionsUnionMod.DeleteSamplingRuleExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashXrayDashNode.typesGetEncryptionConfigExceptionsUnionMod.GetEncryptionConfigExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashXrayDashNode.typesGetSamplingRulesExceptionsUnionMod.GetSamplingRulesExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashXrayDashNode.typesGetSamplingStatisticSummariesExceptionsUnionMod.GetSamplingStatisticSummariesExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashXrayDashNode.typesGetSamplingTargetsExceptionsUnionMod.GetSamplingTargetsExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashXrayDashNode.typesGetServiceGraphExceptionsUnionMod.GetServiceGraphExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashXrayDashNode.typesGetTraceGraphExceptionsUnionMod.GetTraceGraphExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashXrayDashNode.typesGetTraceSummariesExceptionsUnionMod.GetTraceSummariesExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashXrayDashNode.typesPutEncryptionConfigExceptionsUnionMod.PutEncryptionConfigExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashXrayDashNode.typesPutTelemetryRecordsExceptionsUnionMod.PutTelemetryRecordsExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashXrayDashNode.typesPutTraceSegmentsExceptionsUnionMod.PutTraceSegmentsExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashXrayDashNode.typesUpdateSamplingRuleExceptionsUnionMod.UpdateSamplingRuleExceptionsUnion
import typingsSlinky.atAwsDashSdkTypes.buildExceptionMod.ServiceException
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait InvalidRequestException
  extends ServiceException[_InvalidRequestExceptionDetails]
     with BatchGetTracesExceptionsUnion
     with CreateSamplingRuleExceptionsUnion
     with DeleteSamplingRuleExceptionsUnion
     with GetEncryptionConfigExceptionsUnion
     with GetSamplingRulesExceptionsUnion
     with GetSamplingStatisticSummariesExceptionsUnion
     with GetSamplingTargetsExceptionsUnion
     with GetServiceGraphExceptionsUnion
     with GetTraceGraphExceptionsUnion
     with GetTraceSummariesExceptionsUnion
     with PutEncryptionConfigExceptionsUnion
     with PutTelemetryRecordsExceptionsUnion
     with PutTraceSegmentsExceptionsUnion
     with UpdateSamplingRuleExceptionsUnion {
  @JSName("name")
  var name_InvalidRequestException: typingsSlinky.atAwsDashSdkClientDashXrayDashNode.atAwsDashSdkClientDashXrayDashNodeStrings.InvalidRequestException = js.native
}

