package typingsSlinky.angularCompiler.mod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@JSImport("@angular/compiler", "R3Identifiers")
@js.native
class R3Identifiers ()
  extends typingsSlinky.angularCompiler.compilerMod.R3Identifiers

/* static members */
@JSImport("@angular/compiler", "R3Identifiers")
@js.native
object R3Identifiers extends js.Object {
  var ComponentDefWithMeta: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var CopyDefinitionFeature: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var DirectiveDefWithMeta: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var FactoryDef: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var InheritDefinitionFeature: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var InjectorDef: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var ModuleWithProviders: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var NEW_METHOD: String = js.native
  var NgModuleDefWithMeta: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var NgOnChangesFeature: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var PATCH_DEPS: String = js.native
  var PipeDefWithMeta: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var ProvidersFeature: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var TRANSFORM_METHOD: String = js.native
  var advance: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var attribute: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var attributeInterpolate1: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var attributeInterpolate2: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var attributeInterpolate3: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var attributeInterpolate4: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var attributeInterpolate5: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var attributeInterpolate6: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var attributeInterpolate7: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var attributeInterpolate8: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var attributeInterpolateV: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var classMap: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var classMapInterpolate1: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var classMapInterpolate2: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var classMapInterpolate3: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var classMapInterpolate4: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var classMapInterpolate5: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var classMapInterpolate6: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var classMapInterpolate7: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var classMapInterpolate8: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var classMapInterpolateV: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var classProp: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var contentQuery: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var defineComponent: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var defineDirective: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var defineInjector: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var defineNgModule: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var definePipe: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var directiveInject: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var disableBindings: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var element: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var elementContainer: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var elementContainerEnd: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var elementContainerStart: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var elementEnd: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var elementStart: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var enableBindings: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var getCurrentView: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var getFactoryOf: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var getInheritedFactory: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var hostProperty: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var i18n: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var i18nApply: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var i18nAttributes: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var i18nEnd: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var i18nExp: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var i18nPostprocess: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var i18nStart: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var inject: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var injectAttribute: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var injectPipeChangeDetectorRef: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var invalidFactory: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var invalidFactoryDep: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var listener: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var loadQuery: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var namespaceHTML: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var namespaceMathML: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var namespaceSVG: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var nextContext: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var pipe: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var pipeBind1: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var pipeBind2: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var pipeBind3: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var pipeBind4: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var pipeBindV: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var projection: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var projectionDef: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var property: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var propertyInterpolate: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var propertyInterpolate1: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var propertyInterpolate2: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var propertyInterpolate3: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var propertyInterpolate4: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var propertyInterpolate5: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var propertyInterpolate6: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var propertyInterpolate7: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var propertyInterpolate8: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var propertyInterpolateV: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var pureFunction0: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var pureFunction1: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var pureFunction2: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var pureFunction3: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var pureFunction4: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var pureFunction5: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var pureFunction6: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var pureFunction7: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var pureFunction8: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var pureFunctionV: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var queryRefresh: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var reference: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var resolveBody: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var resolveDocument: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var resolveWindow: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var restoreView: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var sanitizeHtml: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var sanitizeResourceUrl: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var sanitizeScript: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var sanitizeStyle: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var sanitizeUrl: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var sanitizeUrlOrResourceUrl: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var select: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var setComponentScope: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var setNgModuleScope: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var staticContentQuery: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var staticViewQuery: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var styleMap: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var styleMapInterpolate1: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var styleMapInterpolate2: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var styleMapInterpolate3: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var styleMapInterpolate4: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var styleMapInterpolate5: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var styleMapInterpolate6: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var styleMapInterpolate7: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var styleMapInterpolate8: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var styleMapInterpolateV: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var styleProp: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var stylePropInterpolate1: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var stylePropInterpolate2: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var stylePropInterpolate3: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var stylePropInterpolate4: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var stylePropInterpolate5: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var stylePropInterpolate6: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var stylePropInterpolate7: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var stylePropInterpolate8: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var stylePropInterpolateV: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var syntheticHostListener: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var syntheticHostProperty: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var templateCreate: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var templateRefExtractor: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var text: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var textInterpolate: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var textInterpolate1: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var textInterpolate2: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var textInterpolate3: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var textInterpolate4: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var textInterpolate5: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var textInterpolate6: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var textInterpolate7: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var textInterpolate8: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var textInterpolateV: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
  var viewQuery: typingsSlinky.angularCompiler.outputAstMod.ExternalReference = js.native
}

