package typingsSlinky.awsSdk.stsMod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait AssumedRoleUser extends js.Object {
  /**
    * The ARN of the temporary security credentials that are returned from the AssumeRole action. For more information about ARNs and how to use them in policies, see IAM Identifiers in the IAM User Guide.
    */
  var Arn: arnType = js.native
  /**
    * A unique identifier that contains the role ID and the role session name of the role that is being assumed. The role ID is generated by AWS when the role is created.
    */
  var AssumedRoleId: assumedRoleIdType = js.native
}

object AssumedRoleUser {
  @scala.inline
  def apply(Arn: arnType, AssumedRoleId: assumedRoleIdType): AssumedRoleUser = {
    val __obj = js.Dynamic.literal(Arn = Arn.asInstanceOf[js.Any], AssumedRoleId = AssumedRoleId.asInstanceOf[js.Any])
    __obj.asInstanceOf[AssumedRoleUser]
  }
  @scala.inline
  implicit class AssumedRoleUserOps[Self <: AssumedRoleUser] (val x: Self) extends AnyVal {
    @scala.inline
    def duplicate: Self = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x)).asInstanceOf[Self]
    @scala.inline
    def combineWith[Other <: js.Any](other: Other): Self with Other = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x, other.asInstanceOf[js.Any])).asInstanceOf[Self with Other]
    @scala.inline
    def withArn(value: arnType): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("Arn")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withAssumedRoleId(value: assumedRoleIdType): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("AssumedRoleId")(value.asInstanceOf[js.Any])
        ret
    }
  }
  
}

