package typingsSlinky.awsSdkClientCodecommitNode.createPullRequestExceptionsUnionMod

import typingsSlinky.awsSdkClientCodecommitNode.typesClientRequestTokenRequiredExceptionMod.ClientRequestTokenRequiredException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionIntegrityChecksFailedExceptionMod.EncryptionIntegrityChecksFailedException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyAccessDeniedExceptionMod.EncryptionKeyAccessDeniedException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyDisabledExceptionMod.EncryptionKeyDisabledException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyNotFoundExceptionMod.EncryptionKeyNotFoundException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyUnavailableExceptionMod.EncryptionKeyUnavailableException
import typingsSlinky.awsSdkClientCodecommitNode.typesIdempotencyParameterMismatchExceptionMod.IdempotencyParameterMismatchException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidClientRequestTokenExceptionMod.InvalidClientRequestTokenException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidDescriptionExceptionMod.InvalidDescriptionException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidReferenceNameExceptionMod.InvalidReferenceNameException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryNameExceptionMod.InvalidRepositoryNameException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidTargetExceptionMod.InvalidTargetException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidTargetsExceptionMod.InvalidTargetsException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidTitleExceptionMod.InvalidTitleException
import typingsSlinky.awsSdkClientCodecommitNode.typesMaximumOpenPullRequestsExceededExceptionMod.MaximumOpenPullRequestsExceededException
import typingsSlinky.awsSdkClientCodecommitNode.typesMultipleRepositoriesInPullRequestExceptionMod.MultipleRepositoriesInPullRequestException
import typingsSlinky.awsSdkClientCodecommitNode.typesReferenceDoesNotExistExceptionMod.ReferenceDoesNotExistException
import typingsSlinky.awsSdkClientCodecommitNode.typesReferenceNameRequiredExceptionMod.ReferenceNameRequiredException
import typingsSlinky.awsSdkClientCodecommitNode.typesReferenceTypeNotSupportedExceptionMod.ReferenceTypeNotSupportedException
import typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryDoesNotExistExceptionMod.RepositoryDoesNotExistException
import typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryNameRequiredExceptionMod.RepositoryNameRequiredException
import typingsSlinky.awsSdkClientCodecommitNode.typesSourceAndDestinationAreSameExceptionMod.SourceAndDestinationAreSameException
import typingsSlinky.awsSdkClientCodecommitNode.typesTargetRequiredExceptionMod.TargetRequiredException
import typingsSlinky.awsSdkClientCodecommitNode.typesTargetsRequiredExceptionMod.TargetsRequiredException
import typingsSlinky.awsSdkClientCodecommitNode.typesTitleRequiredExceptionMod.TitleRequiredException
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryNameRequiredExceptionMod.RepositoryNameRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryNameExceptionMod.InvalidRepositoryNameException
  - typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryDoesNotExistExceptionMod.RepositoryDoesNotExistException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionIntegrityChecksFailedExceptionMod.EncryptionIntegrityChecksFailedException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyAccessDeniedExceptionMod.EncryptionKeyAccessDeniedException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyDisabledExceptionMod.EncryptionKeyDisabledException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyNotFoundExceptionMod.EncryptionKeyNotFoundException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyUnavailableExceptionMod.EncryptionKeyUnavailableException
  - typingsSlinky.awsSdkClientCodecommitNode.typesClientRequestTokenRequiredExceptionMod.ClientRequestTokenRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidClientRequestTokenExceptionMod.InvalidClientRequestTokenException
  - typingsSlinky.awsSdkClientCodecommitNode.typesIdempotencyParameterMismatchExceptionMod.IdempotencyParameterMismatchException
  - typingsSlinky.awsSdkClientCodecommitNode.typesReferenceNameRequiredExceptionMod.ReferenceNameRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidReferenceNameExceptionMod.InvalidReferenceNameException
  - typingsSlinky.awsSdkClientCodecommitNode.typesReferenceDoesNotExistExceptionMod.ReferenceDoesNotExistException
  - typingsSlinky.awsSdkClientCodecommitNode.typesReferenceTypeNotSupportedExceptionMod.ReferenceTypeNotSupportedException
  - typingsSlinky.awsSdkClientCodecommitNode.typesTitleRequiredExceptionMod.TitleRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidTitleExceptionMod.InvalidTitleException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidDescriptionExceptionMod.InvalidDescriptionException
  - typingsSlinky.awsSdkClientCodecommitNode.typesTargetsRequiredExceptionMod.TargetsRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidTargetsExceptionMod.InvalidTargetsException
  - typingsSlinky.awsSdkClientCodecommitNode.typesTargetRequiredExceptionMod.TargetRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidTargetExceptionMod.InvalidTargetException
  - typingsSlinky.awsSdkClientCodecommitNode.typesMultipleRepositoriesInPullRequestExceptionMod.MultipleRepositoriesInPullRequestException
  - typingsSlinky.awsSdkClientCodecommitNode.typesMaximumOpenPullRequestsExceededExceptionMod.MaximumOpenPullRequestsExceededException
  - typingsSlinky.awsSdkClientCodecommitNode.typesSourceAndDestinationAreSameExceptionMod.SourceAndDestinationAreSameException
*/
trait CreatePullRequestExceptionsUnion extends js.Object

object CreatePullRequestExceptionsUnion {
  @scala.inline
  implicit def apply(value: ClientRequestTokenRequiredException): CreatePullRequestExceptionsUnion = value.asInstanceOf[CreatePullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionIntegrityChecksFailedException): CreatePullRequestExceptionsUnion = value.asInstanceOf[CreatePullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyAccessDeniedException): CreatePullRequestExceptionsUnion = value.asInstanceOf[CreatePullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyDisabledException): CreatePullRequestExceptionsUnion = value.asInstanceOf[CreatePullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyNotFoundException): CreatePullRequestExceptionsUnion = value.asInstanceOf[CreatePullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyUnavailableException): CreatePullRequestExceptionsUnion = value.asInstanceOf[CreatePullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: IdempotencyParameterMismatchException): CreatePullRequestExceptionsUnion = value.asInstanceOf[CreatePullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidClientRequestTokenException): CreatePullRequestExceptionsUnion = value.asInstanceOf[CreatePullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidDescriptionException): CreatePullRequestExceptionsUnion = value.asInstanceOf[CreatePullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidReferenceNameException): CreatePullRequestExceptionsUnion = value.asInstanceOf[CreatePullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidRepositoryNameException): CreatePullRequestExceptionsUnion = value.asInstanceOf[CreatePullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidTargetException): CreatePullRequestExceptionsUnion = value.asInstanceOf[CreatePullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidTargetsException): CreatePullRequestExceptionsUnion = value.asInstanceOf[CreatePullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidTitleException): CreatePullRequestExceptionsUnion = value.asInstanceOf[CreatePullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: MaximumOpenPullRequestsExceededException): CreatePullRequestExceptionsUnion = value.asInstanceOf[CreatePullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: MultipleRepositoriesInPullRequestException): CreatePullRequestExceptionsUnion = value.asInstanceOf[CreatePullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: ReferenceDoesNotExistException): CreatePullRequestExceptionsUnion = value.asInstanceOf[CreatePullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: ReferenceNameRequiredException): CreatePullRequestExceptionsUnion = value.asInstanceOf[CreatePullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: ReferenceTypeNotSupportedException): CreatePullRequestExceptionsUnion = value.asInstanceOf[CreatePullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: RepositoryDoesNotExistException): CreatePullRequestExceptionsUnion = value.asInstanceOf[CreatePullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: RepositoryNameRequiredException): CreatePullRequestExceptionsUnion = value.asInstanceOf[CreatePullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: SourceAndDestinationAreSameException): CreatePullRequestExceptionsUnion = value.asInstanceOf[CreatePullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: TargetRequiredException): CreatePullRequestExceptionsUnion = value.asInstanceOf[CreatePullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: TargetsRequiredException): CreatePullRequestExceptionsUnion = value.asInstanceOf[CreatePullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: TitleRequiredException): CreatePullRequestExceptionsUnion = value.asInstanceOf[CreatePullRequestExceptionsUnion]
}

