package typingsSlinky.awsSdkClientCognitoIdentityBrowser.lookupDeveloperIdentityExceptionsUnionMod

import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesInternalErrorExceptionMod.InternalErrorException
import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesInvalidParameterExceptionMod.InvalidParameterException
import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesNotAuthorizedExceptionMod.NotAuthorizedException
import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesResourceConflictExceptionMod.ResourceConflictException
import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesResourceNotFoundExceptionMod.ResourceNotFoundException
import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesTooManyRequestsExceptionMod.TooManyRequestsException
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesInvalidParameterExceptionMod.InvalidParameterException
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesResourceNotFoundExceptionMod.ResourceNotFoundException
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesNotAuthorizedExceptionMod.NotAuthorizedException
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesResourceConflictExceptionMod.ResourceConflictException
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesTooManyRequestsExceptionMod.TooManyRequestsException
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesInternalErrorExceptionMod.InternalErrorException
*/
trait LookupDeveloperIdentityExceptionsUnion extends js.Object

object LookupDeveloperIdentityExceptionsUnion {
  @scala.inline
  implicit def apply(value: InternalErrorException): LookupDeveloperIdentityExceptionsUnion = value.asInstanceOf[LookupDeveloperIdentityExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidParameterException): LookupDeveloperIdentityExceptionsUnion = value.asInstanceOf[LookupDeveloperIdentityExceptionsUnion]
  @scala.inline
  implicit def apply(value: NotAuthorizedException): LookupDeveloperIdentityExceptionsUnion = value.asInstanceOf[LookupDeveloperIdentityExceptionsUnion]
  @scala.inline
  implicit def apply(value: ResourceConflictException): LookupDeveloperIdentityExceptionsUnion = value.asInstanceOf[LookupDeveloperIdentityExceptionsUnion]
  @scala.inline
  implicit def apply(value: ResourceNotFoundException): LookupDeveloperIdentityExceptionsUnion = value.asInstanceOf[LookupDeveloperIdentityExceptionsUnion]
  @scala.inline
  implicit def apply(value: TooManyRequestsException): LookupDeveloperIdentityExceptionsUnion = value.asInstanceOf[LookupDeveloperIdentityExceptionsUnion]
}

