package typingsSlinky.kendoUi.kendo

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object ui {
  type AutoCompleteChangeEvent = typingsSlinky.kendoUi.kendo.ui.AutoCompleteEvent
  type AutoCompleteCloseEvent = typingsSlinky.kendoUi.kendo.ui.AutoCompleteEvent
  type AutoCompleteDataBoundEvent = typingsSlinky.kendoUi.kendo.ui.AutoCompleteEvent
  type AutoCompleteOpenEvent = typingsSlinky.kendoUi.kendo.ui.AutoCompleteEvent
  type ChatTypingEndEvent = typingsSlinky.kendoUi.kendo.ui.ChatEvent
  type ChatTypingStartEvent = typingsSlinky.kendoUi.kendo.ui.ChatEvent
  type ComboBoxCascadeEvent = typingsSlinky.kendoUi.kendo.ui.ComboBoxEvent
  type ComboBoxChangeEvent = typingsSlinky.kendoUi.kendo.ui.ComboBoxEvent
  type ComboBoxCloseEvent = typingsSlinky.kendoUi.kendo.ui.ComboBoxEvent
  type ComboBoxDataBoundEvent = typingsSlinky.kendoUi.kendo.ui.ComboBoxEvent
  type ComboBoxOpenEvent = typingsSlinky.kendoUi.kendo.ui.ComboBoxEvent
  type DateInputChangeEvent = typingsSlinky.kendoUi.kendo.ui.DateInputEvent
  type DatePickerChangeEvent = typingsSlinky.kendoUi.kendo.ui.DatePickerEvent
  type DatePickerCloseEvent = typingsSlinky.kendoUi.kendo.ui.DatePickerEvent
  type DatePickerOpenEvent = typingsSlinky.kendoUi.kendo.ui.DatePickerEvent
  type DateRangePickerChangeEvent = typingsSlinky.kendoUi.kendo.ui.DateRangePickerEvent
  type DateRangePickerCloseEvent = typingsSlinky.kendoUi.kendo.ui.DateRangePickerEvent
  type DateRangePickerOpenEvent = typingsSlinky.kendoUi.kendo.ui.DateRangePickerEvent
  type DateTimePickerChangeEvent = typingsSlinky.kendoUi.kendo.ui.DateTimePickerEvent
  type DrawerHideEvent = typingsSlinky.kendoUi.kendo.ui.DrawerEvent
  type DropDownListCascadeEvent = typingsSlinky.kendoUi.kendo.ui.DropDownListEvent
  type DropDownListChangeEvent = typingsSlinky.kendoUi.kendo.ui.DropDownListEvent
  type DropDownListCloseEvent = typingsSlinky.kendoUi.kendo.ui.DropDownListEvent
  type DropDownListDataBoundEvent = typingsSlinky.kendoUi.kendo.ui.DropDownListEvent
  type DropDownListOpenEvent = typingsSlinky.kendoUi.kendo.ui.DropDownListEvent
  type DropDownTreeChangeEvent = typingsSlinky.kendoUi.kendo.ui.DropDownTreeEvent
  type DropDownTreeCloseEvent = typingsSlinky.kendoUi.kendo.ui.DropDownTreeEvent
  type DropDownTreeDataBoundEvent = typingsSlinky.kendoUi.kendo.ui.DropDownTreeEvent
  type DropDownTreeOpenEvent = typingsSlinky.kendoUi.kendo.ui.DropDownTreeEvent
  type DropTargetDragenterEvent = typingsSlinky.kendoUi.kendo.ui.DropTargetEvent
  type DropTargetDragleaveEvent = typingsSlinky.kendoUi.kendo.ui.DropTargetEvent
  type DropTargetDropEvent = typingsSlinky.kendoUi.kendo.ui.DropTargetEvent
  type GanttChangeEvent = typingsSlinky.kendoUi.kendo.ui.GanttEvent
  type GanttDataBindingEvent = typingsSlinky.kendoUi.kendo.ui.GanttEvent
  type GanttDataBoundEvent = typingsSlinky.kendoUi.kendo.ui.GanttEvent
  type GridChangeEvent = typingsSlinky.kendoUi.kendo.ui.GridEvent
  type GridDataBoundEvent = typingsSlinky.kendoUi.kendo.ui.GridEvent
  type GridSaveChangesEvent = typingsSlinky.kendoUi.kendo.ui.GridEvent
  type MaskedTextBoxChangeEvent = typingsSlinky.kendoUi.kendo.ui.MaskedTextBoxEvent
  type MultiColumnComboBoxCascadeEvent = typingsSlinky.kendoUi.kendo.ui.MultiColumnComboBoxEvent
  type MultiColumnComboBoxChangeEvent = typingsSlinky.kendoUi.kendo.ui.MultiColumnComboBoxEvent
  type MultiColumnComboBoxCloseEvent = typingsSlinky.kendoUi.kendo.ui.MultiColumnComboBoxEvent
  type MultiColumnComboBoxDataBoundEvent = typingsSlinky.kendoUi.kendo.ui.MultiColumnComboBoxEvent
  type MultiColumnComboBoxOpenEvent = typingsSlinky.kendoUi.kendo.ui.MultiColumnComboBoxEvent
  type MultiSelectChangeEvent = typingsSlinky.kendoUi.kendo.ui.MultiSelectEvent
  type MultiSelectCloseEvent = typingsSlinky.kendoUi.kendo.ui.MultiSelectEvent
  type MultiSelectDataBoundEvent = typingsSlinky.kendoUi.kendo.ui.MultiSelectEvent
  type MultiSelectOpenEvent = typingsSlinky.kendoUi.kendo.ui.MultiSelectEvent
  type NumericTextBoxChangeEvent = typingsSlinky.kendoUi.kendo.ui.NumericTextBoxEvent
  type NumericTextBoxSpinEvent = typingsSlinky.kendoUi.kendo.ui.NumericTextBoxEvent
  type PagerChangeEvent = typingsSlinky.kendoUi.kendo.ui.PagerEvent
  type PivotGridDataBindingEvent = typingsSlinky.kendoUi.kendo.ui.PivotGridEvent
  type PivotGridDataBoundEvent = typingsSlinky.kendoUi.kendo.ui.PivotGridEvent
  type PopupActivateEvent = typingsSlinky.kendoUi.kendo.ui.PopupEvent
  type PopupCloseEvent = typingsSlinky.kendoUi.kendo.ui.PopupEvent
  type PopupDeactivateEvent = typingsSlinky.kendoUi.kendo.ui.PopupEvent
  type PopupOpenEvent = typingsSlinky.kendoUi.kendo.ui.PopupEvent
  type SchedulerDataBindingEvent = typingsSlinky.kendoUi.kendo.ui.SchedulerEvent
  type SchedulerDataBoundEvent = typingsSlinky.kendoUi.kendo.ui.SchedulerEvent
  type SpreadsheetInsertSheetEvent = typingsSlinky.kendoUi.kendo.ui.SpreadsheetEvent
  type SpreadsheetRenderEvent = typingsSlinky.kendoUi.kendo.ui.SpreadsheetEvent
  type TimePickerChangeEvent = typingsSlinky.kendoUi.kendo.ui.TimePickerEvent
  type TimePickerCloseEvent = typingsSlinky.kendoUi.kendo.ui.TimePickerEvent
  type TimePickerOpenEvent = typingsSlinky.kendoUi.kendo.ui.TimePickerEvent
  type TimelineDataBoundEvent = typingsSlinky.kendoUi.kendo.ui.TimelineEvent
  type ToolBarOverflowCloseEvent = typingsSlinky.kendoUi.kendo.ui.ToolBarEvent
  type ToolBarOverflowOpenEvent = typingsSlinky.kendoUi.kendo.ui.ToolBarEvent
  type TreeListChangeEvent = typingsSlinky.kendoUi.kendo.ui.TreeListEvent
  type TreeListDataBindingEvent = typingsSlinky.kendoUi.kendo.ui.TreeListEvent
  type TreeListDataBoundEvent = typingsSlinky.kendoUi.kendo.ui.TreeListEvent
  type TreeListSaveChangesEvent = typingsSlinky.kendoUi.kendo.ui.TreeListEvent
}
