package typingsSlinky.awsSdkClientPinpointBrowser.updateApnsVoipSandboxChannelExceptionsUnionMod

import typingsSlinky.awsSdkClientPinpointBrowser.typesBadRequestExceptionMod.BadRequestException
import typingsSlinky.awsSdkClientPinpointBrowser.typesForbiddenExceptionMod.ForbiddenException
import typingsSlinky.awsSdkClientPinpointBrowser.typesInternalServerErrorExceptionMod.InternalServerErrorException
import typingsSlinky.awsSdkClientPinpointBrowser.typesMethodNotAllowedExceptionMod.MethodNotAllowedException
import typingsSlinky.awsSdkClientPinpointBrowser.typesNotFoundExceptionMod.NotFoundException
import typingsSlinky.awsSdkClientPinpointBrowser.typesTooManyRequestsExceptionMod.TooManyRequestsException
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - typingsSlinky.awsSdkClientPinpointBrowser.typesBadRequestExceptionMod.BadRequestException
  - typingsSlinky.awsSdkClientPinpointBrowser.typesInternalServerErrorExceptionMod.InternalServerErrorException
  - typingsSlinky.awsSdkClientPinpointBrowser.typesForbiddenExceptionMod.ForbiddenException
  - typingsSlinky.awsSdkClientPinpointBrowser.typesNotFoundExceptionMod.NotFoundException
  - typingsSlinky.awsSdkClientPinpointBrowser.typesMethodNotAllowedExceptionMod.MethodNotAllowedException
  - typingsSlinky.awsSdkClientPinpointBrowser.typesTooManyRequestsExceptionMod.TooManyRequestsException
*/
trait UpdateApnsVoipSandboxChannelExceptionsUnion extends js.Object

object UpdateApnsVoipSandboxChannelExceptionsUnion {
  @scala.inline
  implicit def apply(value: BadRequestException): UpdateApnsVoipSandboxChannelExceptionsUnion = value.asInstanceOf[UpdateApnsVoipSandboxChannelExceptionsUnion]
  @scala.inline
  implicit def apply(value: ForbiddenException): UpdateApnsVoipSandboxChannelExceptionsUnion = value.asInstanceOf[UpdateApnsVoipSandboxChannelExceptionsUnion]
  @scala.inline
  implicit def apply(value: InternalServerErrorException): UpdateApnsVoipSandboxChannelExceptionsUnion = value.asInstanceOf[UpdateApnsVoipSandboxChannelExceptionsUnion]
  @scala.inline
  implicit def apply(value: MethodNotAllowedException): UpdateApnsVoipSandboxChannelExceptionsUnion = value.asInstanceOf[UpdateApnsVoipSandboxChannelExceptionsUnion]
  @scala.inline
  implicit def apply(value: NotFoundException): UpdateApnsVoipSandboxChannelExceptionsUnion = value.asInstanceOf[UpdateApnsVoipSandboxChannelExceptionsUnion]
  @scala.inline
  implicit def apply(value: TooManyRequestsException): UpdateApnsVoipSandboxChannelExceptionsUnion = value.asInstanceOf[UpdateApnsVoipSandboxChannelExceptionsUnion]
}

