package typingsSlinky.awsSdkClientCodecommitNode.updatePullRequestStatusExceptionsUnionMod

import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionIntegrityChecksFailedExceptionMod.EncryptionIntegrityChecksFailedException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyAccessDeniedExceptionMod.EncryptionKeyAccessDeniedException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyDisabledExceptionMod.EncryptionKeyDisabledException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyNotFoundExceptionMod.EncryptionKeyNotFoundException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyUnavailableExceptionMod.EncryptionKeyUnavailableException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidPullRequestIdExceptionMod.InvalidPullRequestIdException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidPullRequestStatusExceptionMod.InvalidPullRequestStatusException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidPullRequestStatusUpdateExceptionMod.InvalidPullRequestStatusUpdateException
import typingsSlinky.awsSdkClientCodecommitNode.typesPullRequestDoesNotExistExceptionMod.PullRequestDoesNotExistException
import typingsSlinky.awsSdkClientCodecommitNode.typesPullRequestIdRequiredExceptionMod.PullRequestIdRequiredException
import typingsSlinky.awsSdkClientCodecommitNode.typesPullRequestStatusRequiredExceptionMod.PullRequestStatusRequiredException
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - typingsSlinky.awsSdkClientCodecommitNode.typesPullRequestDoesNotExistExceptionMod.PullRequestDoesNotExistException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidPullRequestIdExceptionMod.InvalidPullRequestIdException
  - typingsSlinky.awsSdkClientCodecommitNode.typesPullRequestIdRequiredExceptionMod.PullRequestIdRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidPullRequestStatusUpdateExceptionMod.InvalidPullRequestStatusUpdateException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidPullRequestStatusExceptionMod.InvalidPullRequestStatusException
  - typingsSlinky.awsSdkClientCodecommitNode.typesPullRequestStatusRequiredExceptionMod.PullRequestStatusRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionIntegrityChecksFailedExceptionMod.EncryptionIntegrityChecksFailedException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyAccessDeniedExceptionMod.EncryptionKeyAccessDeniedException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyDisabledExceptionMod.EncryptionKeyDisabledException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyNotFoundExceptionMod.EncryptionKeyNotFoundException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyUnavailableExceptionMod.EncryptionKeyUnavailableException
*/
trait UpdatePullRequestStatusExceptionsUnion extends js.Object

object UpdatePullRequestStatusExceptionsUnion {
  @scala.inline
  implicit def apply(value: EncryptionIntegrityChecksFailedException): UpdatePullRequestStatusExceptionsUnion = value.asInstanceOf[UpdatePullRequestStatusExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyAccessDeniedException): UpdatePullRequestStatusExceptionsUnion = value.asInstanceOf[UpdatePullRequestStatusExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyDisabledException): UpdatePullRequestStatusExceptionsUnion = value.asInstanceOf[UpdatePullRequestStatusExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyNotFoundException): UpdatePullRequestStatusExceptionsUnion = value.asInstanceOf[UpdatePullRequestStatusExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyUnavailableException): UpdatePullRequestStatusExceptionsUnion = value.asInstanceOf[UpdatePullRequestStatusExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidPullRequestIdException): UpdatePullRequestStatusExceptionsUnion = value.asInstanceOf[UpdatePullRequestStatusExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidPullRequestStatusException): UpdatePullRequestStatusExceptionsUnion = value.asInstanceOf[UpdatePullRequestStatusExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidPullRequestStatusUpdateException): UpdatePullRequestStatusExceptionsUnion = value.asInstanceOf[UpdatePullRequestStatusExceptionsUnion]
  @scala.inline
  implicit def apply(value: PullRequestDoesNotExistException): UpdatePullRequestStatusExceptionsUnion = value.asInstanceOf[UpdatePullRequestStatusExceptionsUnion]
  @scala.inline
  implicit def apply(value: PullRequestIdRequiredException): UpdatePullRequestStatusExceptionsUnion = value.asInstanceOf[UpdatePullRequestStatusExceptionsUnion]
  @scala.inline
  implicit def apply(value: PullRequestStatusRequiredException): UpdatePullRequestStatusExceptionsUnion = value.asInstanceOf[UpdatePullRequestStatusExceptionsUnion]
}

