package typingsSlinky.vscodeLanguageserverProtocol

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object protocolMod {
  type ClientCapabilities = typingsSlinky.vscodeLanguageserverProtocol.protocolMod._ClientCapabilities with typingsSlinky.vscodeLanguageserverProtocol.protocolImplementationMod.ImplementationClientCapabilities with typingsSlinky.vscodeLanguageserverProtocol.protocolTypeDefinitionMod.TypeDefinitionClientCapabilities with typingsSlinky.vscodeLanguageserverProtocol.protocolWorkspaceFoldersMod.WorkspaceFoldersClientCapabilities with typingsSlinky.vscodeLanguageserverProtocol.protocolConfigurationMod.ConfigurationClientCapabilities with typingsSlinky.vscodeLanguageserverProtocol.protocolColorProviderMod.ColorClientCapabilities with typingsSlinky.vscodeLanguageserverProtocol.protocolFoldingRangeMod.FoldingRangeClientCapabilities with typingsSlinky.vscodeLanguageserverProtocol.protocolDeclarationMod.DeclarationClientCapabilities
  type DocumentSelector = js.Array[
    java.lang.String | typingsSlinky.vscodeLanguageserverProtocol.protocolMod.DocumentFilter
  ]
  type ExecuteCommandRegistrationOptions = typingsSlinky.vscodeLanguageserverProtocol.protocolMod.ExecuteCommandOptions
  type InitializeParams = typingsSlinky.vscodeLanguageserverProtocol.protocolMod._InitializeParams with typingsSlinky.vscodeLanguageserverProtocol.protocolWorkspaceFoldersMod.WorkspaceFoldersInitializeParams
  type ServerCapabilities = typingsSlinky.vscodeLanguageserverProtocol.protocolMod._ServerCapabilities with typingsSlinky.vscodeLanguageserverProtocol.protocolImplementationMod.ImplementationServerCapabilities with typingsSlinky.vscodeLanguageserverProtocol.protocolTypeDefinitionMod.TypeDefinitionServerCapabilities with typingsSlinky.vscodeLanguageserverProtocol.protocolWorkspaceFoldersMod.WorkspaceFoldersServerCapabilities with typingsSlinky.vscodeLanguageserverProtocol.protocolColorProviderMod.ColorServerCapabilities with typingsSlinky.vscodeLanguageserverProtocol.protocolFoldingRangeMod.FoldingRangeServerCapabilities with typingsSlinky.vscodeLanguageserverProtocol.protocolDeclarationMod.DeclarationServerCapabilities
}
