package typingsSlinky.googleapis.polyV1Mod.polyV1

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/**
  * A message generated by the asset import process.
  */
@js.native
trait SchemaAssetImportMessage extends js.Object {
  /**
    * The code associated with this message.
    */
  var code: js.UndefOr[String] = js.native
  /**
    * An optional file path. Only present for those error codes that specify
    * it.
    */
  var filePath: js.UndefOr[String] = js.native
  /**
    * An optional image error. Only present for INVALID_IMAGE_FILE.
    */
  var imageError: js.UndefOr[SchemaImageError] = js.native
  /**
    * An optional OBJ parse error. Only present for OBJ_PARSE_ERROR.
    */
  var objParseError: js.UndefOr[SchemaObjParseError] = js.native
}

object SchemaAssetImportMessage {
  @scala.inline
  def apply(): SchemaAssetImportMessage = {
    val __obj = js.Dynamic.literal()
    __obj.asInstanceOf[SchemaAssetImportMessage]
  }
  @scala.inline
  implicit class SchemaAssetImportMessageOps[Self <: SchemaAssetImportMessage] (val x: Self) extends AnyVal {
    @scala.inline
    def duplicate: Self = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x)).asInstanceOf[Self]
    @scala.inline
    def combineWith[Other <: js.Any](other: Other): Self with Other = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x, other.asInstanceOf[js.Any])).asInstanceOf[Self with Other]
    @scala.inline
    def withCode(value: String): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("code")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutCode: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("code")(js.undefined)
        ret
    }
    @scala.inline
    def withFilePath(value: String): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("filePath")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutFilePath: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("filePath")(js.undefined)
        ret
    }
    @scala.inline
    def withImageError(value: SchemaImageError): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("imageError")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutImageError: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("imageError")(js.undefined)
        ret
    }
    @scala.inline
    def withObjParseError(value: SchemaObjParseError): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("objParseError")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutObjParseError: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("objParseError")(js.undefined)
        ret
    }
  }
  
}

