package typingsSlinky.awsSdkClientCodecommitNode.postCommentForComparedCommitExceptionsUnionMod

import typingsSlinky.awsSdkClientCodecommitNode.typesBeforeCommitIdAndAfterCommitIdAreSameExceptionMod.BeforeCommitIdAndAfterCommitIdAreSameException
import typingsSlinky.awsSdkClientCodecommitNode.typesClientRequestTokenRequiredExceptionMod.ClientRequestTokenRequiredException
import typingsSlinky.awsSdkClientCodecommitNode.typesCommentContentRequiredExceptionMod.CommentContentRequiredException
import typingsSlinky.awsSdkClientCodecommitNode.typesCommentContentSizeLimitExceededExceptionMod.CommentContentSizeLimitExceededException
import typingsSlinky.awsSdkClientCodecommitNode.typesCommitDoesNotExistExceptionMod.CommitDoesNotExistException
import typingsSlinky.awsSdkClientCodecommitNode.typesCommitIdRequiredExceptionMod.CommitIdRequiredException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionIntegrityChecksFailedExceptionMod.EncryptionIntegrityChecksFailedException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyAccessDeniedExceptionMod.EncryptionKeyAccessDeniedException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyDisabledExceptionMod.EncryptionKeyDisabledException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyNotFoundExceptionMod.EncryptionKeyNotFoundException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyUnavailableExceptionMod.EncryptionKeyUnavailableException
import typingsSlinky.awsSdkClientCodecommitNode.typesIdempotencyParameterMismatchExceptionMod.IdempotencyParameterMismatchException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidClientRequestTokenExceptionMod.InvalidClientRequestTokenException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidCommitIdExceptionMod.InvalidCommitIdException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidFileLocationExceptionMod.InvalidFileLocationException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidFilePositionExceptionMod.InvalidFilePositionException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidPathExceptionMod.InvalidPathException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRelativeFileVersionEnumExceptionMod.InvalidRelativeFileVersionEnumException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryNameExceptionMod.InvalidRepositoryNameException
import typingsSlinky.awsSdkClientCodecommitNode.typesPathDoesNotExistExceptionMod.PathDoesNotExistException
import typingsSlinky.awsSdkClientCodecommitNode.typesPathRequiredExceptionMod.PathRequiredException
import typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryDoesNotExistExceptionMod.RepositoryDoesNotExistException
import typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryNameRequiredExceptionMod.RepositoryNameRequiredException
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryNameRequiredExceptionMod.RepositoryNameRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryDoesNotExistExceptionMod.RepositoryDoesNotExistException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryNameExceptionMod.InvalidRepositoryNameException
  - typingsSlinky.awsSdkClientCodecommitNode.typesClientRequestTokenRequiredExceptionMod.ClientRequestTokenRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidClientRequestTokenExceptionMod.InvalidClientRequestTokenException
  - typingsSlinky.awsSdkClientCodecommitNode.typesIdempotencyParameterMismatchExceptionMod.IdempotencyParameterMismatchException
  - typingsSlinky.awsSdkClientCodecommitNode.typesCommentContentRequiredExceptionMod.CommentContentRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesCommentContentSizeLimitExceededExceptionMod.CommentContentSizeLimitExceededException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidFileLocationExceptionMod.InvalidFileLocationException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRelativeFileVersionEnumExceptionMod.InvalidRelativeFileVersionEnumException
  - typingsSlinky.awsSdkClientCodecommitNode.typesPathRequiredExceptionMod.PathRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidFilePositionExceptionMod.InvalidFilePositionException
  - typingsSlinky.awsSdkClientCodecommitNode.typesCommitIdRequiredExceptionMod.CommitIdRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidCommitIdExceptionMod.InvalidCommitIdException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionIntegrityChecksFailedExceptionMod.EncryptionIntegrityChecksFailedException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyAccessDeniedExceptionMod.EncryptionKeyAccessDeniedException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyDisabledExceptionMod.EncryptionKeyDisabledException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyNotFoundExceptionMod.EncryptionKeyNotFoundException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyUnavailableExceptionMod.EncryptionKeyUnavailableException
  - typingsSlinky.awsSdkClientCodecommitNode.typesBeforeCommitIdAndAfterCommitIdAreSameExceptionMod.BeforeCommitIdAndAfterCommitIdAreSameException
  - typingsSlinky.awsSdkClientCodecommitNode.typesCommitDoesNotExistExceptionMod.CommitDoesNotExistException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidPathExceptionMod.InvalidPathException
  - typingsSlinky.awsSdkClientCodecommitNode.typesPathDoesNotExistExceptionMod.PathDoesNotExistException
*/
trait PostCommentForComparedCommitExceptionsUnion extends js.Object

object PostCommentForComparedCommitExceptionsUnion {
  @scala.inline
  implicit def apply(value: BeforeCommitIdAndAfterCommitIdAreSameException): PostCommentForComparedCommitExceptionsUnion = value.asInstanceOf[PostCommentForComparedCommitExceptionsUnion]
  @scala.inline
  implicit def apply(value: ClientRequestTokenRequiredException): PostCommentForComparedCommitExceptionsUnion = value.asInstanceOf[PostCommentForComparedCommitExceptionsUnion]
  @scala.inline
  implicit def apply(value: CommentContentRequiredException): PostCommentForComparedCommitExceptionsUnion = value.asInstanceOf[PostCommentForComparedCommitExceptionsUnion]
  @scala.inline
  implicit def apply(value: CommentContentSizeLimitExceededException): PostCommentForComparedCommitExceptionsUnion = value.asInstanceOf[PostCommentForComparedCommitExceptionsUnion]
  @scala.inline
  implicit def apply(value: CommitDoesNotExistException): PostCommentForComparedCommitExceptionsUnion = value.asInstanceOf[PostCommentForComparedCommitExceptionsUnion]
  @scala.inline
  implicit def apply(value: CommitIdRequiredException): PostCommentForComparedCommitExceptionsUnion = value.asInstanceOf[PostCommentForComparedCommitExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionIntegrityChecksFailedException): PostCommentForComparedCommitExceptionsUnion = value.asInstanceOf[PostCommentForComparedCommitExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyAccessDeniedException): PostCommentForComparedCommitExceptionsUnion = value.asInstanceOf[PostCommentForComparedCommitExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyDisabledException): PostCommentForComparedCommitExceptionsUnion = value.asInstanceOf[PostCommentForComparedCommitExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyNotFoundException): PostCommentForComparedCommitExceptionsUnion = value.asInstanceOf[PostCommentForComparedCommitExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyUnavailableException): PostCommentForComparedCommitExceptionsUnion = value.asInstanceOf[PostCommentForComparedCommitExceptionsUnion]
  @scala.inline
  implicit def apply(value: IdempotencyParameterMismatchException): PostCommentForComparedCommitExceptionsUnion = value.asInstanceOf[PostCommentForComparedCommitExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidClientRequestTokenException): PostCommentForComparedCommitExceptionsUnion = value.asInstanceOf[PostCommentForComparedCommitExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidCommitIdException): PostCommentForComparedCommitExceptionsUnion = value.asInstanceOf[PostCommentForComparedCommitExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidFileLocationException): PostCommentForComparedCommitExceptionsUnion = value.asInstanceOf[PostCommentForComparedCommitExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidFilePositionException): PostCommentForComparedCommitExceptionsUnion = value.asInstanceOf[PostCommentForComparedCommitExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidPathException): PostCommentForComparedCommitExceptionsUnion = value.asInstanceOf[PostCommentForComparedCommitExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidRelativeFileVersionEnumException): PostCommentForComparedCommitExceptionsUnion = value.asInstanceOf[PostCommentForComparedCommitExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidRepositoryNameException): PostCommentForComparedCommitExceptionsUnion = value.asInstanceOf[PostCommentForComparedCommitExceptionsUnion]
  @scala.inline
  implicit def apply(value: PathDoesNotExistException): PostCommentForComparedCommitExceptionsUnion = value.asInstanceOf[PostCommentForComparedCommitExceptionsUnion]
  @scala.inline
  implicit def apply(value: PathRequiredException): PostCommentForComparedCommitExceptionsUnion = value.asInstanceOf[PostCommentForComparedCommitExceptionsUnion]
  @scala.inline
  implicit def apply(value: RepositoryDoesNotExistException): PostCommentForComparedCommitExceptionsUnion = value.asInstanceOf[PostCommentForComparedCommitExceptionsUnion]
  @scala.inline
  implicit def apply(value: RepositoryNameRequiredException): PostCommentForComparedCommitExceptionsUnion = value.asInstanceOf[PostCommentForComparedCommitExceptionsUnion]
}

