package typingsSlinky.awsSdkClientDynamodbNode

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object typesAutoScalingTargetTrackingScalingPolicyConfigurationDescriptionMod {
  type UnmarshalledAutoScalingTargetTrackingScalingPolicyConfigurationDescription = typingsSlinky.awsSdkClientDynamodbNode.typesAutoScalingTargetTrackingScalingPolicyConfigurationDescriptionMod.AutoScalingTargetTrackingScalingPolicyConfigurationDescription
}
