package typingsSlinky.awsSdkClientDynamodbNode

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

package object typesAutoScalingTargetTrackingScalingPolicyConfigurationDescriptionMod {
  
  type UnmarshalledAutoScalingTargetTrackingScalingPolicyConfigurationDescription = typingsSlinky.awsSdkClientDynamodbNode.typesAutoScalingTargetTrackingScalingPolicyConfigurationDescriptionMod.AutoScalingTargetTrackingScalingPolicyConfigurationDescription
}
