package typingsSlinky.awsSdkClientPinpointBrowser.typesForbiddenExceptionMod

import typingsSlinky.awsSdkClientPinpointBrowser.createAppExceptionsUnionMod.CreateAppExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.createCampaignExceptionsUnionMod.CreateCampaignExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.createExportJobExceptionsUnionMod.CreateExportJobExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.createImportJobExceptionsUnionMod.CreateImportJobExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.createSegmentExceptionsUnionMod.CreateSegmentExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.deleteAdmChannelExceptionsUnionMod.DeleteAdmChannelExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.deleteApnsChannelExceptionsUnionMod.DeleteApnsChannelExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.deleteApnsSandboxChannelExceptionsUnionMod.DeleteApnsSandboxChannelExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.deleteApnsVoipChannelExceptionsUnionMod.DeleteApnsVoipChannelExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.deleteApnsVoipSandboxChannelExceptionsUnionMod.DeleteApnsVoipSandboxChannelExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.deleteAppExceptionsUnionMod.DeleteAppExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.deleteBaiduChannelExceptionsUnionMod.DeleteBaiduChannelExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.deleteCampaignExceptionsUnionMod.DeleteCampaignExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.deleteEmailChannelExceptionsUnionMod.DeleteEmailChannelExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.deleteEndpointExceptionsUnionMod.DeleteEndpointExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.deleteEventStreamExceptionsUnionMod.DeleteEventStreamExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.deleteGcmChannelExceptionsUnionMod.DeleteGcmChannelExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.deleteSegmentExceptionsUnionMod.DeleteSegmentExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.deleteSmsChannelExceptionsUnionMod.DeleteSmsChannelExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.deleteUserEndpointsExceptionsUnionMod.DeleteUserEndpointsExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.getAdmChannelExceptionsUnionMod.GetAdmChannelExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.getApnsChannelExceptionsUnionMod.GetApnsChannelExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.getApnsSandboxChannelExceptionsUnionMod.GetApnsSandboxChannelExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.getApnsVoipChannelExceptionsUnionMod.GetApnsVoipChannelExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.getApnsVoipSandboxChannelExceptionsUnionMod.GetApnsVoipSandboxChannelExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.getAppExceptionsUnionMod.GetAppExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.getApplicationSettingsExceptionsUnionMod.GetApplicationSettingsExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.getAppsExceptionsUnionMod.GetAppsExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.getBaiduChannelExceptionsUnionMod.GetBaiduChannelExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.getCampaignActivitiesExceptionsUnionMod.GetCampaignActivitiesExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.getCampaignExceptionsUnionMod.GetCampaignExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.getCampaignVersionExceptionsUnionMod.GetCampaignVersionExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.getCampaignVersionsExceptionsUnionMod.GetCampaignVersionsExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.getCampaignsExceptionsUnionMod.GetCampaignsExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.getChannelsExceptionsUnionMod.GetChannelsExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.getEmailChannelExceptionsUnionMod.GetEmailChannelExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.getEndpointExceptionsUnionMod.GetEndpointExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.getEventStreamExceptionsUnionMod.GetEventStreamExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.getExportJobExceptionsUnionMod.GetExportJobExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.getExportJobsExceptionsUnionMod.GetExportJobsExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.getGcmChannelExceptionsUnionMod.GetGcmChannelExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.getImportJobExceptionsUnionMod.GetImportJobExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.getImportJobsExceptionsUnionMod.GetImportJobsExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.getSegmentExceptionsUnionMod.GetSegmentExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.getSegmentExportJobsExceptionsUnionMod.GetSegmentExportJobsExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.getSegmentImportJobsExceptionsUnionMod.GetSegmentImportJobsExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.getSegmentVersionExceptionsUnionMod.GetSegmentVersionExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.getSegmentVersionsExceptionsUnionMod.GetSegmentVersionsExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.getSegmentsExceptionsUnionMod.GetSegmentsExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.getSmsChannelExceptionsUnionMod.GetSmsChannelExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.getUserEndpointsExceptionsUnionMod.GetUserEndpointsExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.phoneNumberValidateExceptionsUnionMod.PhoneNumberValidateExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.putEventStreamExceptionsUnionMod.PutEventStreamExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.putEventsExceptionsUnionMod.PutEventsExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.removeAttributesExceptionsUnionMod.RemoveAttributesExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.sendMessagesExceptionsUnionMod.SendMessagesExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.sendUsersMessagesExceptionsUnionMod.SendUsersMessagesExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.updateAdmChannelExceptionsUnionMod.UpdateAdmChannelExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.updateApnsChannelExceptionsUnionMod.UpdateApnsChannelExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.updateApnsSandboxChannelExceptionsUnionMod.UpdateApnsSandboxChannelExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.updateApnsVoipChannelExceptionsUnionMod.UpdateApnsVoipChannelExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.updateApnsVoipSandboxChannelExceptionsUnionMod.UpdateApnsVoipSandboxChannelExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.updateApplicationSettingsExceptionsUnionMod.UpdateApplicationSettingsExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.updateBaiduChannelExceptionsUnionMod.UpdateBaiduChannelExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.updateCampaignExceptionsUnionMod.UpdateCampaignExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.updateEmailChannelExceptionsUnionMod.UpdateEmailChannelExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.updateEndpointExceptionsUnionMod.UpdateEndpointExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.updateEndpointsBatchExceptionsUnionMod.UpdateEndpointsBatchExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.updateGcmChannelExceptionsUnionMod.UpdateGcmChannelExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.updateSegmentExceptionsUnionMod.UpdateSegmentExceptionsUnion
import typingsSlinky.awsSdkClientPinpointBrowser.updateSmsChannelExceptionsUnionMod.UpdateSmsChannelExceptionsUnion
import typingsSlinky.awsSdkTypes.exceptionMod.ServiceException
import typingsSlinky.awsSdkTypes.responseMod.ResponseMetadata
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

@js.native
trait ForbiddenException
  extends ServiceException[ForbiddenExceptionDetails]
     with CreateAppExceptionsUnion
     with CreateCampaignExceptionsUnion
     with CreateExportJobExceptionsUnion
     with CreateImportJobExceptionsUnion
     with CreateSegmentExceptionsUnion
     with DeleteAdmChannelExceptionsUnion
     with DeleteApnsChannelExceptionsUnion
     with DeleteApnsSandboxChannelExceptionsUnion
     with DeleteApnsVoipChannelExceptionsUnion
     with DeleteApnsVoipSandboxChannelExceptionsUnion
     with DeleteAppExceptionsUnion
     with DeleteBaiduChannelExceptionsUnion
     with DeleteCampaignExceptionsUnion
     with DeleteEmailChannelExceptionsUnion
     with DeleteEndpointExceptionsUnion
     with DeleteEventStreamExceptionsUnion
     with DeleteGcmChannelExceptionsUnion
     with DeleteSegmentExceptionsUnion
     with DeleteSmsChannelExceptionsUnion
     with DeleteUserEndpointsExceptionsUnion
     with GetAdmChannelExceptionsUnion
     with GetApnsChannelExceptionsUnion
     with GetApnsSandboxChannelExceptionsUnion
     with GetApnsVoipChannelExceptionsUnion
     with GetApnsVoipSandboxChannelExceptionsUnion
     with GetAppExceptionsUnion
     with GetApplicationSettingsExceptionsUnion
     with GetAppsExceptionsUnion
     with GetBaiduChannelExceptionsUnion
     with GetCampaignActivitiesExceptionsUnion
     with GetCampaignExceptionsUnion
     with GetCampaignVersionExceptionsUnion
     with GetCampaignVersionsExceptionsUnion
     with GetCampaignsExceptionsUnion
     with GetChannelsExceptionsUnion
     with GetEmailChannelExceptionsUnion
     with GetEndpointExceptionsUnion
     with GetEventStreamExceptionsUnion
     with GetExportJobExceptionsUnion
     with GetExportJobsExceptionsUnion
     with GetGcmChannelExceptionsUnion
     with GetImportJobExceptionsUnion
     with GetImportJobsExceptionsUnion
     with GetSegmentExceptionsUnion
     with GetSegmentExportJobsExceptionsUnion
     with GetSegmentImportJobsExceptionsUnion
     with GetSegmentVersionExceptionsUnion
     with GetSegmentVersionsExceptionsUnion
     with GetSegmentsExceptionsUnion
     with GetSmsChannelExceptionsUnion
     with GetUserEndpointsExceptionsUnion
     with PhoneNumberValidateExceptionsUnion
     with PutEventStreamExceptionsUnion
     with PutEventsExceptionsUnion
     with RemoveAttributesExceptionsUnion
     with SendMessagesExceptionsUnion
     with SendUsersMessagesExceptionsUnion
     with UpdateAdmChannelExceptionsUnion
     with UpdateApnsChannelExceptionsUnion
     with UpdateApnsSandboxChannelExceptionsUnion
     with UpdateApnsVoipChannelExceptionsUnion
     with UpdateApnsVoipSandboxChannelExceptionsUnion
     with UpdateApplicationSettingsExceptionsUnion
     with UpdateBaiduChannelExceptionsUnion
     with UpdateCampaignExceptionsUnion
     with UpdateEmailChannelExceptionsUnion
     with UpdateEndpointExceptionsUnion
     with UpdateEndpointsBatchExceptionsUnion
     with UpdateGcmChannelExceptionsUnion
     with UpdateSegmentExceptionsUnion
     with UpdateSmsChannelExceptionsUnion {
  
  @JSName("name")
  var name_ForbiddenException: typingsSlinky.awsSdkClientPinpointBrowser.awsSdkClientPinpointBrowserStrings.ForbiddenException = js.native
}
object ForbiddenException {
  
  @scala.inline
  def apply(
    $metadata: ResponseMetadata,
    details: ForbiddenExceptionDetails,
    message: String,
    name: typingsSlinky.awsSdkClientPinpointBrowser.awsSdkClientPinpointBrowserStrings.ForbiddenException
  ): ForbiddenException = {
    val __obj = js.Dynamic.literal($metadata = $metadata.asInstanceOf[js.Any], details = details.asInstanceOf[js.Any], message = message.asInstanceOf[js.Any], name = name.asInstanceOf[js.Any])
    __obj.asInstanceOf[ForbiddenException]
  }
  
  @scala.inline
  implicit class ForbiddenExceptionOps[Self <: ForbiddenException] (val x: Self) extends AnyVal {
    
    @scala.inline
    def duplicate: Self = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x)).asInstanceOf[Self]
    
    @scala.inline
    def combineWith[Other <: js.Any](other: Other): Self with Other = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x, other.asInstanceOf[js.Any])).asInstanceOf[Self with Other]
    
    @scala.inline
    def set(key: String, value: js.Any): Self = {
      x.asInstanceOf[js.Dynamic].updateDynamic(key)(value)
      x
    }
    
    @scala.inline
    def setName(
      value: typingsSlinky.awsSdkClientPinpointBrowser.awsSdkClientPinpointBrowserStrings.ForbiddenException
    ): Self = this.set("name", value.asInstanceOf[js.Any])
  }
}
