package typingsSlinky.officeJs.Office

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/**
  * Provides options for configuring the prompt and identifying the binding that is created.
  */
@js.native
trait AddBindingFromPromptOptions extends js.Object {
  /**
    * A user-defined item of any type that is returned, unchanged, in the asyncContext property of the AsyncResult object that is passed to a callback.
    */
  var asyncContext: js.UndefOr[js.Any] = js.native
  /**
    * The unique ID of the binding. Autogenerated if not supplied.
    */
  var id: js.UndefOr[String] = js.native
  /**
    * Specifies the string to display in the prompt UI that tells the user what to select. Limited to 200 characters. 
    * If no promptText argument is passed, "Please make a selection" is displayed.
    */
  var promptText: js.UndefOr[String] = js.native
  /**
    * Specifies a table of sample data displayed in the prompt UI as an example of the kinds of fields (columns) that can be bound by your add-in. 
    * The headers provided in the TableData object specify the labels used in the field selection UI.
    * 
    * **Note**: This parameter is used only in add-ins for Access. It is ignored if provided when calling the method in an add-in for Excel.
    * 
    * **Important**: We no longer recommend that you create and use Access web apps and databases in SharePoint.
    * As an alternative, we recommend that you use {@link https://powerapps.microsoft.com/ | Microsoft PowerApps}
    * to build no-code business solutions for web and mobile devices.
    */
  var sampleData: js.UndefOr[TableData] = js.native
}

object AddBindingFromPromptOptions {
  @scala.inline
  def apply(): AddBindingFromPromptOptions = {
    val __obj = js.Dynamic.literal()
    __obj.asInstanceOf[AddBindingFromPromptOptions]
  }
  @scala.inline
  implicit class AddBindingFromPromptOptionsOps[Self <: AddBindingFromPromptOptions] (val x: Self) extends AnyVal {
    @scala.inline
    def duplicate: Self = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x)).asInstanceOf[Self]
    @scala.inline
    def combineWith[Other <: js.Any](other: Other): Self with Other = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x, other.asInstanceOf[js.Any])).asInstanceOf[Self with Other]
    @scala.inline
    def withAsyncContext(value: js.Any): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("asyncContext")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutAsyncContext: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("asyncContext")(js.undefined)
        ret
    }
    @scala.inline
    def withId(value: String): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("id")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutId: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("id")(js.undefined)
        ret
    }
    @scala.inline
    def withPromptText(value: String): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("promptText")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutPromptText: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("promptText")(js.undefined)
        ret
    }
    @scala.inline
    def withSampleData(value: TableData): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("sampleData")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutSampleData: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("sampleData")(js.undefined)
        ret
    }
  }
  
}

