package typingsSlinky.googleapis.appengineV1betaMod.appengineV1beta

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait SchemaOAuth2ClientInfo extends js.Object {
  /**
    * Application name to be used in OAuth consent screen.
    */
  var applicationName: js.UndefOr[String] = js.native
  /**
    * Nameof the client to be generated. Optional - If not provided, the name
    * will be autogenerated by the backend.
    */
  var clientName: js.UndefOr[String] = js.native
  /**
    * Developer&#39;s information to be used in OAuth consent screen.
    */
  var developerEmailAddress: js.UndefOr[String] = js.native
}

object SchemaOAuth2ClientInfo {
  @scala.inline
  def apply(): SchemaOAuth2ClientInfo = {
    val __obj = js.Dynamic.literal()
    __obj.asInstanceOf[SchemaOAuth2ClientInfo]
  }
  @scala.inline
  implicit class SchemaOAuth2ClientInfoOps[Self <: SchemaOAuth2ClientInfo] (val x: Self) extends AnyVal {
    @scala.inline
    def duplicate: Self = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x)).asInstanceOf[Self]
    @scala.inline
    def combineWith[Other <: js.Any](other: Other): Self with Other = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x, other.asInstanceOf[js.Any])).asInstanceOf[Self with Other]
    @scala.inline
    def withApplicationName(value: String): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("applicationName")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutApplicationName: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("applicationName")(js.undefined)
        ret
    }
    @scala.inline
    def withClientName(value: String): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("clientName")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutClientName: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("clientName")(js.undefined)
        ret
    }
    @scala.inline
    def withDeveloperEmailAddress(value: String): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("developerEmailAddress")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutDeveloperEmailAddress: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("developerEmailAddress")(js.undefined)
        ret
    }
  }
  
}

