package typingsSlinky.atAwsDashSdkClientDashCodecommitDashNode.typesDirectoryNameConflictsWithFileNameExceptionMod

import typingsSlinky.atAwsDashSdkClientDashCodecommitDashNode.typesPutFileExceptionsUnionMod.PutFileExceptionsUnion
import typingsSlinky.atAwsDashSdkTypes.buildExceptionMod.ServiceException
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait DirectoryNameConflictsWithFileNameException
  extends ServiceException[_DirectoryNameConflictsWithFileNameExceptionDetails]
     with PutFileExceptionsUnion {
  @JSName("name")
  var name_DirectoryNameConflictsWithFileNameException: typingsSlinky.atAwsDashSdkClientDashCodecommitDashNode.atAwsDashSdkClientDashCodecommitDashNodeStrings.DirectoryNameConflictsWithFileNameException = js.native
}

