package typingsSlinky.awsSdkClientCodecommitNode.updateRepositoryDescriptionExceptionsUnionMod

import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionIntegrityChecksFailedExceptionMod.EncryptionIntegrityChecksFailedException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyAccessDeniedExceptionMod.EncryptionKeyAccessDeniedException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyDisabledExceptionMod.EncryptionKeyDisabledException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyNotFoundExceptionMod.EncryptionKeyNotFoundException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyUnavailableExceptionMod.EncryptionKeyUnavailableException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryDescriptionExceptionMod.InvalidRepositoryDescriptionException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryNameExceptionMod.InvalidRepositoryNameException
import typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryDoesNotExistExceptionMod.RepositoryDoesNotExistException
import typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryNameRequiredExceptionMod.RepositoryNameRequiredException
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryNameRequiredExceptionMod.RepositoryNameRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryDoesNotExistExceptionMod.RepositoryDoesNotExistException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryNameExceptionMod.InvalidRepositoryNameException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryDescriptionExceptionMod.InvalidRepositoryDescriptionException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionIntegrityChecksFailedExceptionMod.EncryptionIntegrityChecksFailedException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyAccessDeniedExceptionMod.EncryptionKeyAccessDeniedException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyDisabledExceptionMod.EncryptionKeyDisabledException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyNotFoundExceptionMod.EncryptionKeyNotFoundException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyUnavailableExceptionMod.EncryptionKeyUnavailableException
*/
trait UpdateRepositoryDescriptionExceptionsUnion extends js.Object

object UpdateRepositoryDescriptionExceptionsUnion {
  @scala.inline
  implicit def apply(value: EncryptionIntegrityChecksFailedException): UpdateRepositoryDescriptionExceptionsUnion = value.asInstanceOf[UpdateRepositoryDescriptionExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyAccessDeniedException): UpdateRepositoryDescriptionExceptionsUnion = value.asInstanceOf[UpdateRepositoryDescriptionExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyDisabledException): UpdateRepositoryDescriptionExceptionsUnion = value.asInstanceOf[UpdateRepositoryDescriptionExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyNotFoundException): UpdateRepositoryDescriptionExceptionsUnion = value.asInstanceOf[UpdateRepositoryDescriptionExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyUnavailableException): UpdateRepositoryDescriptionExceptionsUnion = value.asInstanceOf[UpdateRepositoryDescriptionExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidRepositoryDescriptionException): UpdateRepositoryDescriptionExceptionsUnion = value.asInstanceOf[UpdateRepositoryDescriptionExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidRepositoryNameException): UpdateRepositoryDescriptionExceptionsUnion = value.asInstanceOf[UpdateRepositoryDescriptionExceptionsUnion]
  @scala.inline
  implicit def apply(value: RepositoryDoesNotExistException): UpdateRepositoryDescriptionExceptionsUnion = value.asInstanceOf[UpdateRepositoryDescriptionExceptionsUnion]
  @scala.inline
  implicit def apply(value: RepositoryNameRequiredException): UpdateRepositoryDescriptionExceptionsUnion = value.asInstanceOf[UpdateRepositoryDescriptionExceptionsUnion]
}

