package typingsSlinky.chromeApps.chrome.webViewRequest

import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

/* Rewritten from type alias, can be one of: 
  - typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotAddRequestCookie
  - typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotAddResponseCookie
  - typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotAddResponseHeader
  - typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotCancelRequest
  - typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotEditRequestCookie
  - typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotEditResponseCookie
  - typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotRedirectRequest
  - typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotRedirectToTransparentImage
  - typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotRedirectToEmptyDocument
  - typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotRedirectByRegEx
  - typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotRemoveRequestCookie
  - typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotRemoveResponseCookie
  - typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotRemoveRequestHeader
  - typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotRemoveResponseHeader
  - typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotSetRequestHeader
  - typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotSendMessageToExtension
  - typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotIgnoreRules
*/
trait DeclarativeWebRequestActionsList extends StObject
object DeclarativeWebRequestActionsList {
  
  @scala.inline
  def declarativeWebRequestDotAddRequestCookie: typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotAddRequestCookie = "declarativeWebRequest.AddRequestCookie".asInstanceOf[typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotAddRequestCookie]
  
  @scala.inline
  def declarativeWebRequestDotAddResponseCookie: typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotAddResponseCookie = "declarativeWebRequest.AddResponseCookie".asInstanceOf[typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotAddResponseCookie]
  
  @scala.inline
  def declarativeWebRequestDotAddResponseHeader: typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotAddResponseHeader = "declarativeWebRequest.AddResponseHeader".asInstanceOf[typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotAddResponseHeader]
  
  @scala.inline
  def declarativeWebRequestDotCancelRequest: typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotCancelRequest = "declarativeWebRequest.CancelRequest".asInstanceOf[typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotCancelRequest]
  
  @scala.inline
  def declarativeWebRequestDotEditRequestCookie: typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotEditRequestCookie = "declarativeWebRequest.EditRequestCookie".asInstanceOf[typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotEditRequestCookie]
  
  @scala.inline
  def declarativeWebRequestDotEditResponseCookie: typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotEditResponseCookie = "declarativeWebRequest.EditResponseCookie".asInstanceOf[typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotEditResponseCookie]
  
  @scala.inline
  def declarativeWebRequestDotIgnoreRules: typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotIgnoreRules = "declarativeWebRequest.IgnoreRules".asInstanceOf[typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotIgnoreRules]
  
  @scala.inline
  def declarativeWebRequestDotRedirectByRegEx: typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotRedirectByRegEx = "declarativeWebRequest.RedirectByRegEx".asInstanceOf[typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotRedirectByRegEx]
  
  @scala.inline
  def declarativeWebRequestDotRedirectRequest: typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotRedirectRequest = "declarativeWebRequest.RedirectRequest".asInstanceOf[typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotRedirectRequest]
  
  @scala.inline
  def declarativeWebRequestDotRedirectToEmptyDocument: typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotRedirectToEmptyDocument = "declarativeWebRequest.RedirectToEmptyDocument".asInstanceOf[typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotRedirectToEmptyDocument]
  
  @scala.inline
  def declarativeWebRequestDotRedirectToTransparentImage: typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotRedirectToTransparentImage = "declarativeWebRequest.RedirectToTransparentImage".asInstanceOf[typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotRedirectToTransparentImage]
  
  @scala.inline
  def declarativeWebRequestDotRemoveRequestCookie: typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotRemoveRequestCookie = "declarativeWebRequest.RemoveRequestCookie".asInstanceOf[typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotRemoveRequestCookie]
  
  @scala.inline
  def declarativeWebRequestDotRemoveRequestHeader: typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotRemoveRequestHeader = "declarativeWebRequest.RemoveRequestHeader".asInstanceOf[typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotRemoveRequestHeader]
  
  @scala.inline
  def declarativeWebRequestDotRemoveResponseCookie: typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotRemoveResponseCookie = "declarativeWebRequest.RemoveResponseCookie".asInstanceOf[typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotRemoveResponseCookie]
  
  @scala.inline
  def declarativeWebRequestDotRemoveResponseHeader: typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotRemoveResponseHeader = "declarativeWebRequest.RemoveResponseHeader".asInstanceOf[typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotRemoveResponseHeader]
  
  @scala.inline
  def declarativeWebRequestDotSendMessageToExtension: typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotSendMessageToExtension = "declarativeWebRequest.SendMessageToExtension".asInstanceOf[typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotSendMessageToExtension]
  
  @scala.inline
  def declarativeWebRequestDotSetRequestHeader: typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotSetRequestHeader = "declarativeWebRequest.SetRequestHeader".asInstanceOf[typingsSlinky.chromeApps.chromeAppsStrings.declarativeWebRequestDotSetRequestHeader]
}
