package typingsSlinky.officeJsPreview.global.Word

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/**
  * [Api set: WordApi]
  */
@JSGlobal("Word.Style")
@js.native
object Style extends js.Object {
  /* "Bibliography" */ val bibliography: typingsSlinky.officeJsPreview.Word.Style.bibliography with String = js.native
  /* "BookTitle" */ val bookTitle: typingsSlinky.officeJsPreview.Word.Style.bookTitle with String = js.native
  /* "Caption" */ val caption: typingsSlinky.officeJsPreview.Word.Style.caption with String = js.native
  /* "Emphasis" */ val emphasis: typingsSlinky.officeJsPreview.Word.Style.emphasis with String = js.native
  /* "EndnoteReference" */ val endnoteReference: typingsSlinky.officeJsPreview.Word.Style.endnoteReference with String = js.native
  /* "EndnoteText" */ val endnoteText: typingsSlinky.officeJsPreview.Word.Style.endnoteText with String = js.native
  /* "Footer" */ val footer: typingsSlinky.officeJsPreview.Word.Style.footer with String = js.native
  /* "FootnoteReference" */ val footnoteReference: typingsSlinky.officeJsPreview.Word.Style.footnoteReference with String = js.native
  /* "FootnoteText" */ val footnoteText: typingsSlinky.officeJsPreview.Word.Style.footnoteText with String = js.native
  /* "GridTable1Light" */ val gridTable1Light: typingsSlinky.officeJsPreview.Word.Style.gridTable1Light with String = js.native
  /* "GridTable1Light_Accent1" */ val gridTable1Light_Accent1: typingsSlinky.officeJsPreview.Word.Style.gridTable1Light_Accent1 with String = js.native
  /* "GridTable1Light_Accent2" */ val gridTable1Light_Accent2: typingsSlinky.officeJsPreview.Word.Style.gridTable1Light_Accent2 with String = js.native
  /* "GridTable1Light_Accent3" */ val gridTable1Light_Accent3: typingsSlinky.officeJsPreview.Word.Style.gridTable1Light_Accent3 with String = js.native
  /* "GridTable1Light_Accent4" */ val gridTable1Light_Accent4: typingsSlinky.officeJsPreview.Word.Style.gridTable1Light_Accent4 with String = js.native
  /* "GridTable1Light_Accent5" */ val gridTable1Light_Accent5: typingsSlinky.officeJsPreview.Word.Style.gridTable1Light_Accent5 with String = js.native
  /* "GridTable1Light_Accent6" */ val gridTable1Light_Accent6: typingsSlinky.officeJsPreview.Word.Style.gridTable1Light_Accent6 with String = js.native
  /* "GridTable2" */ val gridTable2: typingsSlinky.officeJsPreview.Word.Style.gridTable2 with String = js.native
  /* "GridTable2_Accent1" */ val gridTable2_Accent1: typingsSlinky.officeJsPreview.Word.Style.gridTable2_Accent1 with String = js.native
  /* "GridTable2_Accent2" */ val gridTable2_Accent2: typingsSlinky.officeJsPreview.Word.Style.gridTable2_Accent2 with String = js.native
  /* "GridTable2_Accent3" */ val gridTable2_Accent3: typingsSlinky.officeJsPreview.Word.Style.gridTable2_Accent3 with String = js.native
  /* "GridTable2_Accent4" */ val gridTable2_Accent4: typingsSlinky.officeJsPreview.Word.Style.gridTable2_Accent4 with String = js.native
  /* "GridTable2_Accent5" */ val gridTable2_Accent5: typingsSlinky.officeJsPreview.Word.Style.gridTable2_Accent5 with String = js.native
  /* "GridTable2_Accent6" */ val gridTable2_Accent6: typingsSlinky.officeJsPreview.Word.Style.gridTable2_Accent6 with String = js.native
  /* "GridTable3" */ val gridTable3: typingsSlinky.officeJsPreview.Word.Style.gridTable3 with String = js.native
  /* "GridTable3_Accent1" */ val gridTable3_Accent1: typingsSlinky.officeJsPreview.Word.Style.gridTable3_Accent1 with String = js.native
  /* "GridTable3_Accent2" */ val gridTable3_Accent2: typingsSlinky.officeJsPreview.Word.Style.gridTable3_Accent2 with String = js.native
  /* "GridTable3_Accent3" */ val gridTable3_Accent3: typingsSlinky.officeJsPreview.Word.Style.gridTable3_Accent3 with String = js.native
  /* "GridTable3_Accent4" */ val gridTable3_Accent4: typingsSlinky.officeJsPreview.Word.Style.gridTable3_Accent4 with String = js.native
  /* "GridTable3_Accent5" */ val gridTable3_Accent5: typingsSlinky.officeJsPreview.Word.Style.gridTable3_Accent5 with String = js.native
  /* "GridTable3_Accent6" */ val gridTable3_Accent6: typingsSlinky.officeJsPreview.Word.Style.gridTable3_Accent6 with String = js.native
  /* "GridTable4" */ val gridTable4: typingsSlinky.officeJsPreview.Word.Style.gridTable4 with String = js.native
  /* "GridTable4_Accent1" */ val gridTable4_Accent1: typingsSlinky.officeJsPreview.Word.Style.gridTable4_Accent1 with String = js.native
  /* "GridTable4_Accent2" */ val gridTable4_Accent2: typingsSlinky.officeJsPreview.Word.Style.gridTable4_Accent2 with String = js.native
  /* "GridTable4_Accent3" */ val gridTable4_Accent3: typingsSlinky.officeJsPreview.Word.Style.gridTable4_Accent3 with String = js.native
  /* "GridTable4_Accent4" */ val gridTable4_Accent4: typingsSlinky.officeJsPreview.Word.Style.gridTable4_Accent4 with String = js.native
  /* "GridTable4_Accent5" */ val gridTable4_Accent5: typingsSlinky.officeJsPreview.Word.Style.gridTable4_Accent5 with String = js.native
  /* "GridTable4_Accent6" */ val gridTable4_Accent6: typingsSlinky.officeJsPreview.Word.Style.gridTable4_Accent6 with String = js.native
  /* "GridTable5Dark" */ val gridTable5Dark: typingsSlinky.officeJsPreview.Word.Style.gridTable5Dark with String = js.native
  /* "GridTable5Dark_Accent1" */ val gridTable5Dark_Accent1: typingsSlinky.officeJsPreview.Word.Style.gridTable5Dark_Accent1 with String = js.native
  /* "GridTable5Dark_Accent2" */ val gridTable5Dark_Accent2: typingsSlinky.officeJsPreview.Word.Style.gridTable5Dark_Accent2 with String = js.native
  /* "GridTable5Dark_Accent3" */ val gridTable5Dark_Accent3: typingsSlinky.officeJsPreview.Word.Style.gridTable5Dark_Accent3 with String = js.native
  /* "GridTable5Dark_Accent4" */ val gridTable5Dark_Accent4: typingsSlinky.officeJsPreview.Word.Style.gridTable5Dark_Accent4 with String = js.native
  /* "GridTable5Dark_Accent5" */ val gridTable5Dark_Accent5: typingsSlinky.officeJsPreview.Word.Style.gridTable5Dark_Accent5 with String = js.native
  /* "GridTable5Dark_Accent6" */ val gridTable5Dark_Accent6: typingsSlinky.officeJsPreview.Word.Style.gridTable5Dark_Accent6 with String = js.native
  /* "GridTable6Colorful" */ val gridTable6Colorful: typingsSlinky.officeJsPreview.Word.Style.gridTable6Colorful with String = js.native
  /* "GridTable6Colorful_Accent1" */ val gridTable6Colorful_Accent1: typingsSlinky.officeJsPreview.Word.Style.gridTable6Colorful_Accent1 with String = js.native
  /* "GridTable6Colorful_Accent2" */ val gridTable6Colorful_Accent2: typingsSlinky.officeJsPreview.Word.Style.gridTable6Colorful_Accent2 with String = js.native
  /* "GridTable6Colorful_Accent3" */ val gridTable6Colorful_Accent3: typingsSlinky.officeJsPreview.Word.Style.gridTable6Colorful_Accent3 with String = js.native
  /* "GridTable6Colorful_Accent4" */ val gridTable6Colorful_Accent4: typingsSlinky.officeJsPreview.Word.Style.gridTable6Colorful_Accent4 with String = js.native
  /* "GridTable6Colorful_Accent5" */ val gridTable6Colorful_Accent5: typingsSlinky.officeJsPreview.Word.Style.gridTable6Colorful_Accent5 with String = js.native
  /* "GridTable6Colorful_Accent6" */ val gridTable6Colorful_Accent6: typingsSlinky.officeJsPreview.Word.Style.gridTable6Colorful_Accent6 with String = js.native
  /* "GridTable7Colorful" */ val gridTable7Colorful: typingsSlinky.officeJsPreview.Word.Style.gridTable7Colorful with String = js.native
  /* "GridTable7Colorful_Accent1" */ val gridTable7Colorful_Accent1: typingsSlinky.officeJsPreview.Word.Style.gridTable7Colorful_Accent1 with String = js.native
  /* "GridTable7Colorful_Accent2" */ val gridTable7Colorful_Accent2: typingsSlinky.officeJsPreview.Word.Style.gridTable7Colorful_Accent2 with String = js.native
  /* "GridTable7Colorful_Accent3" */ val gridTable7Colorful_Accent3: typingsSlinky.officeJsPreview.Word.Style.gridTable7Colorful_Accent3 with String = js.native
  /* "GridTable7Colorful_Accent4" */ val gridTable7Colorful_Accent4: typingsSlinky.officeJsPreview.Word.Style.gridTable7Colorful_Accent4 with String = js.native
  /* "GridTable7Colorful_Accent5" */ val gridTable7Colorful_Accent5: typingsSlinky.officeJsPreview.Word.Style.gridTable7Colorful_Accent5 with String = js.native
  /* "GridTable7Colorful_Accent6" */ val gridTable7Colorful_Accent6: typingsSlinky.officeJsPreview.Word.Style.gridTable7Colorful_Accent6 with String = js.native
  /* "Header" */ val header: typingsSlinky.officeJsPreview.Word.Style.header with String = js.native
  /* "Heading1" */ val heading1: typingsSlinky.officeJsPreview.Word.Style.heading1 with String = js.native
  /* "Heading2" */ val heading2: typingsSlinky.officeJsPreview.Word.Style.heading2 with String = js.native
  /* "Heading3" */ val heading3: typingsSlinky.officeJsPreview.Word.Style.heading3 with String = js.native
  /* "Heading4" */ val heading4: typingsSlinky.officeJsPreview.Word.Style.heading4 with String = js.native
  /* "Heading5" */ val heading5: typingsSlinky.officeJsPreview.Word.Style.heading5 with String = js.native
  /* "Heading6" */ val heading6: typingsSlinky.officeJsPreview.Word.Style.heading6 with String = js.native
  /* "Heading7" */ val heading7: typingsSlinky.officeJsPreview.Word.Style.heading7 with String = js.native
  /* "Heading8" */ val heading8: typingsSlinky.officeJsPreview.Word.Style.heading8 with String = js.native
  /* "Heading9" */ val heading9: typingsSlinky.officeJsPreview.Word.Style.heading9 with String = js.native
  /* "Hyperlink" */ val hyperlink: typingsSlinky.officeJsPreview.Word.Style.hyperlink with String = js.native
  /* "IntenseEmphasis" */ val intenseEmphasis: typingsSlinky.officeJsPreview.Word.Style.intenseEmphasis with String = js.native
  /* "IntenseQuote" */ val intenseQuote: typingsSlinky.officeJsPreview.Word.Style.intenseQuote with String = js.native
  /* "IntenseReference" */ val intenseReference: typingsSlinky.officeJsPreview.Word.Style.intenseReference with String = js.native
  /* "ListParagraph" */ val listParagraph: typingsSlinky.officeJsPreview.Word.Style.listParagraph with String = js.native
  /* "ListTable1Light" */ val listTable1Light: typingsSlinky.officeJsPreview.Word.Style.listTable1Light with String = js.native
  /* "ListTable1Light_Accent1" */ val listTable1Light_Accent1: typingsSlinky.officeJsPreview.Word.Style.listTable1Light_Accent1 with String = js.native
  /* "ListTable1Light_Accent2" */ val listTable1Light_Accent2: typingsSlinky.officeJsPreview.Word.Style.listTable1Light_Accent2 with String = js.native
  /* "ListTable1Light_Accent3" */ val listTable1Light_Accent3: typingsSlinky.officeJsPreview.Word.Style.listTable1Light_Accent3 with String = js.native
  /* "ListTable1Light_Accent4" */ val listTable1Light_Accent4: typingsSlinky.officeJsPreview.Word.Style.listTable1Light_Accent4 with String = js.native
  /* "ListTable1Light_Accent5" */ val listTable1Light_Accent5: typingsSlinky.officeJsPreview.Word.Style.listTable1Light_Accent5 with String = js.native
  /* "ListTable1Light_Accent6" */ val listTable1Light_Accent6: typingsSlinky.officeJsPreview.Word.Style.listTable1Light_Accent6 with String = js.native
  /* "ListTable2" */ val listTable2: typingsSlinky.officeJsPreview.Word.Style.listTable2 with String = js.native
  /* "ListTable2_Accent1" */ val listTable2_Accent1: typingsSlinky.officeJsPreview.Word.Style.listTable2_Accent1 with String = js.native
  /* "ListTable2_Accent2" */ val listTable2_Accent2: typingsSlinky.officeJsPreview.Word.Style.listTable2_Accent2 with String = js.native
  /* "ListTable2_Accent3" */ val listTable2_Accent3: typingsSlinky.officeJsPreview.Word.Style.listTable2_Accent3 with String = js.native
  /* "ListTable2_Accent4" */ val listTable2_Accent4: typingsSlinky.officeJsPreview.Word.Style.listTable2_Accent4 with String = js.native
  /* "ListTable2_Accent5" */ val listTable2_Accent5: typingsSlinky.officeJsPreview.Word.Style.listTable2_Accent5 with String = js.native
  /* "ListTable2_Accent6" */ val listTable2_Accent6: typingsSlinky.officeJsPreview.Word.Style.listTable2_Accent6 with String = js.native
  /* "ListTable3" */ val listTable3: typingsSlinky.officeJsPreview.Word.Style.listTable3 with String = js.native
  /* "ListTable3_Accent1" */ val listTable3_Accent1: typingsSlinky.officeJsPreview.Word.Style.listTable3_Accent1 with String = js.native
  /* "ListTable3_Accent2" */ val listTable3_Accent2: typingsSlinky.officeJsPreview.Word.Style.listTable3_Accent2 with String = js.native
  /* "ListTable3_Accent3" */ val listTable3_Accent3: typingsSlinky.officeJsPreview.Word.Style.listTable3_Accent3 with String = js.native
  /* "ListTable3_Accent4" */ val listTable3_Accent4: typingsSlinky.officeJsPreview.Word.Style.listTable3_Accent4 with String = js.native
  /* "ListTable3_Accent5" */ val listTable3_Accent5: typingsSlinky.officeJsPreview.Word.Style.listTable3_Accent5 with String = js.native
  /* "ListTable3_Accent6" */ val listTable3_Accent6: typingsSlinky.officeJsPreview.Word.Style.listTable3_Accent6 with String = js.native
  /* "ListTable4" */ val listTable4: typingsSlinky.officeJsPreview.Word.Style.listTable4 with String = js.native
  /* "ListTable4_Accent1" */ val listTable4_Accent1: typingsSlinky.officeJsPreview.Word.Style.listTable4_Accent1 with String = js.native
  /* "ListTable4_Accent2" */ val listTable4_Accent2: typingsSlinky.officeJsPreview.Word.Style.listTable4_Accent2 with String = js.native
  /* "ListTable4_Accent3" */ val listTable4_Accent3: typingsSlinky.officeJsPreview.Word.Style.listTable4_Accent3 with String = js.native
  /* "ListTable4_Accent4" */ val listTable4_Accent4: typingsSlinky.officeJsPreview.Word.Style.listTable4_Accent4 with String = js.native
  /* "ListTable4_Accent5" */ val listTable4_Accent5: typingsSlinky.officeJsPreview.Word.Style.listTable4_Accent5 with String = js.native
  /* "ListTable4_Accent6" */ val listTable4_Accent6: typingsSlinky.officeJsPreview.Word.Style.listTable4_Accent6 with String = js.native
  /* "ListTable5Dark" */ val listTable5Dark: typingsSlinky.officeJsPreview.Word.Style.listTable5Dark with String = js.native
  /* "ListTable5Dark_Accent1" */ val listTable5Dark_Accent1: typingsSlinky.officeJsPreview.Word.Style.listTable5Dark_Accent1 with String = js.native
  /* "ListTable5Dark_Accent2" */ val listTable5Dark_Accent2: typingsSlinky.officeJsPreview.Word.Style.listTable5Dark_Accent2 with String = js.native
  /* "ListTable5Dark_Accent3" */ val listTable5Dark_Accent3: typingsSlinky.officeJsPreview.Word.Style.listTable5Dark_Accent3 with String = js.native
  /* "ListTable5Dark_Accent4" */ val listTable5Dark_Accent4: typingsSlinky.officeJsPreview.Word.Style.listTable5Dark_Accent4 with String = js.native
  /* "ListTable5Dark_Accent5" */ val listTable5Dark_Accent5: typingsSlinky.officeJsPreview.Word.Style.listTable5Dark_Accent5 with String = js.native
  /* "ListTable5Dark_Accent6" */ val listTable5Dark_Accent6: typingsSlinky.officeJsPreview.Word.Style.listTable5Dark_Accent6 with String = js.native
  /* "ListTable6Colorful" */ val listTable6Colorful: typingsSlinky.officeJsPreview.Word.Style.listTable6Colorful with String = js.native
  /* "ListTable6Colorful_Accent1" */ val listTable6Colorful_Accent1: typingsSlinky.officeJsPreview.Word.Style.listTable6Colorful_Accent1 with String = js.native
  /* "ListTable6Colorful_Accent2" */ val listTable6Colorful_Accent2: typingsSlinky.officeJsPreview.Word.Style.listTable6Colorful_Accent2 with String = js.native
  /* "ListTable6Colorful_Accent3" */ val listTable6Colorful_Accent3: typingsSlinky.officeJsPreview.Word.Style.listTable6Colorful_Accent3 with String = js.native
  /* "ListTable6Colorful_Accent4" */ val listTable6Colorful_Accent4: typingsSlinky.officeJsPreview.Word.Style.listTable6Colorful_Accent4 with String = js.native
  /* "ListTable6Colorful_Accent5" */ val listTable6Colorful_Accent5: typingsSlinky.officeJsPreview.Word.Style.listTable6Colorful_Accent5 with String = js.native
  /* "ListTable6Colorful_Accent6" */ val listTable6Colorful_Accent6: typingsSlinky.officeJsPreview.Word.Style.listTable6Colorful_Accent6 with String = js.native
  /* "ListTable7Colorful" */ val listTable7Colorful: typingsSlinky.officeJsPreview.Word.Style.listTable7Colorful with String = js.native
  /* "ListTable7Colorful_Accent1" */ val listTable7Colorful_Accent1: typingsSlinky.officeJsPreview.Word.Style.listTable7Colorful_Accent1 with String = js.native
  /* "ListTable7Colorful_Accent2" */ val listTable7Colorful_Accent2: typingsSlinky.officeJsPreview.Word.Style.listTable7Colorful_Accent2 with String = js.native
  /* "ListTable7Colorful_Accent3" */ val listTable7Colorful_Accent3: typingsSlinky.officeJsPreview.Word.Style.listTable7Colorful_Accent3 with String = js.native
  /* "ListTable7Colorful_Accent4" */ val listTable7Colorful_Accent4: typingsSlinky.officeJsPreview.Word.Style.listTable7Colorful_Accent4 with String = js.native
  /* "ListTable7Colorful_Accent5" */ val listTable7Colorful_Accent5: typingsSlinky.officeJsPreview.Word.Style.listTable7Colorful_Accent5 with String = js.native
  /* "ListTable7Colorful_Accent6" */ val listTable7Colorful_Accent6: typingsSlinky.officeJsPreview.Word.Style.listTable7Colorful_Accent6 with String = js.native
  /* "NoSpacing" */ val noSpacing: typingsSlinky.officeJsPreview.Word.Style.noSpacing with String = js.native
  /* "Normal" */ val normal: typingsSlinky.officeJsPreview.Word.Style.normal with String = js.native
  /* "Other" */ val other: typingsSlinky.officeJsPreview.Word.Style.other with String = js.native
  /* "PlainTable1" */ val plainTable1: typingsSlinky.officeJsPreview.Word.Style.plainTable1 with String = js.native
  /* "PlainTable2" */ val plainTable2: typingsSlinky.officeJsPreview.Word.Style.plainTable2 with String = js.native
  /* "PlainTable3" */ val plainTable3: typingsSlinky.officeJsPreview.Word.Style.plainTable3 with String = js.native
  /* "PlainTable4" */ val plainTable4: typingsSlinky.officeJsPreview.Word.Style.plainTable4 with String = js.native
  /* "PlainTable5" */ val plainTable5: typingsSlinky.officeJsPreview.Word.Style.plainTable5 with String = js.native
  /* "Quote" */ val quote: typingsSlinky.officeJsPreview.Word.Style.quote with String = js.native
  /* "Strong" */ val strong: typingsSlinky.officeJsPreview.Word.Style.strong with String = js.native
  /* "Subtitle" */ val subtitle: typingsSlinky.officeJsPreview.Word.Style.subtitle with String = js.native
  /* "SubtleEmphasis" */ val subtleEmphasis: typingsSlinky.officeJsPreview.Word.Style.subtleEmphasis with String = js.native
  /* "SubtleReference" */ val subtleReference: typingsSlinky.officeJsPreview.Word.Style.subtleReference with String = js.native
  /* "TableGrid" */ val tableGrid: typingsSlinky.officeJsPreview.Word.Style.tableGrid with String = js.native
  /* "TableGridLight" */ val tableGridLight: typingsSlinky.officeJsPreview.Word.Style.tableGridLight with String = js.native
  /* "Title" */ val title: typingsSlinky.officeJsPreview.Word.Style.title with String = js.native
  /* "Toc1" */ val toc1: typingsSlinky.officeJsPreview.Word.Style.toc1 with String = js.native
  /* "Toc2" */ val toc2: typingsSlinky.officeJsPreview.Word.Style.toc2 with String = js.native
  /* "Toc3" */ val toc3: typingsSlinky.officeJsPreview.Word.Style.toc3 with String = js.native
  /* "Toc4" */ val toc4: typingsSlinky.officeJsPreview.Word.Style.toc4 with String = js.native
  /* "Toc5" */ val toc5: typingsSlinky.officeJsPreview.Word.Style.toc5 with String = js.native
  /* "Toc6" */ val toc6: typingsSlinky.officeJsPreview.Word.Style.toc6 with String = js.native
  /* "Toc7" */ val toc7: typingsSlinky.officeJsPreview.Word.Style.toc7 with String = js.native
  /* "Toc8" */ val toc8: typingsSlinky.officeJsPreview.Word.Style.toc8 with String = js.native
  /* "Toc9" */ val toc9: typingsSlinky.officeJsPreview.Word.Style.toc9 with String = js.native
  /* "TocHeading" */ val tocHeading: typingsSlinky.officeJsPreview.Word.Style.tocHeading with String = js.native
  @JSBracketAccess
  def apply(value: String): js.UndefOr[typingsSlinky.officeJsPreview.Word.Style with String] = js.native
}

