package typingsSlinky.awsSdkClientCodecommitNode.describePullRequestEventsExceptionsUnionMod

import typingsSlinky.awsSdkClientCodecommitNode.typesActorDoesNotExistExceptionMod.ActorDoesNotExistException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionIntegrityChecksFailedExceptionMod.EncryptionIntegrityChecksFailedException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyAccessDeniedExceptionMod.EncryptionKeyAccessDeniedException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyDisabledExceptionMod.EncryptionKeyDisabledException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyNotFoundExceptionMod.EncryptionKeyNotFoundException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyUnavailableExceptionMod.EncryptionKeyUnavailableException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidActorArnExceptionMod.InvalidActorArnException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidContinuationTokenExceptionMod.InvalidContinuationTokenException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidMaxResultsExceptionMod.InvalidMaxResultsException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidPullRequestEventTypeExceptionMod.InvalidPullRequestEventTypeException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidPullRequestIdExceptionMod.InvalidPullRequestIdException
import typingsSlinky.awsSdkClientCodecommitNode.typesPullRequestDoesNotExistExceptionMod.PullRequestDoesNotExistException
import typingsSlinky.awsSdkClientCodecommitNode.typesPullRequestIdRequiredExceptionMod.PullRequestIdRequiredException
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - typingsSlinky.awsSdkClientCodecommitNode.typesPullRequestDoesNotExistExceptionMod.PullRequestDoesNotExistException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidPullRequestIdExceptionMod.InvalidPullRequestIdException
  - typingsSlinky.awsSdkClientCodecommitNode.typesPullRequestIdRequiredExceptionMod.PullRequestIdRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidPullRequestEventTypeExceptionMod.InvalidPullRequestEventTypeException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidActorArnExceptionMod.InvalidActorArnException
  - typingsSlinky.awsSdkClientCodecommitNode.typesActorDoesNotExistExceptionMod.ActorDoesNotExistException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidMaxResultsExceptionMod.InvalidMaxResultsException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidContinuationTokenExceptionMod.InvalidContinuationTokenException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionIntegrityChecksFailedExceptionMod.EncryptionIntegrityChecksFailedException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyAccessDeniedExceptionMod.EncryptionKeyAccessDeniedException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyDisabledExceptionMod.EncryptionKeyDisabledException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyNotFoundExceptionMod.EncryptionKeyNotFoundException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyUnavailableExceptionMod.EncryptionKeyUnavailableException
*/
trait DescribePullRequestEventsExceptionsUnion extends js.Object

object DescribePullRequestEventsExceptionsUnion {
  @scala.inline
  implicit def apply(value: ActorDoesNotExistException): DescribePullRequestEventsExceptionsUnion = value.asInstanceOf[DescribePullRequestEventsExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionIntegrityChecksFailedException): DescribePullRequestEventsExceptionsUnion = value.asInstanceOf[DescribePullRequestEventsExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyAccessDeniedException): DescribePullRequestEventsExceptionsUnion = value.asInstanceOf[DescribePullRequestEventsExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyDisabledException): DescribePullRequestEventsExceptionsUnion = value.asInstanceOf[DescribePullRequestEventsExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyNotFoundException): DescribePullRequestEventsExceptionsUnion = value.asInstanceOf[DescribePullRequestEventsExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyUnavailableException): DescribePullRequestEventsExceptionsUnion = value.asInstanceOf[DescribePullRequestEventsExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidActorArnException): DescribePullRequestEventsExceptionsUnion = value.asInstanceOf[DescribePullRequestEventsExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidContinuationTokenException): DescribePullRequestEventsExceptionsUnion = value.asInstanceOf[DescribePullRequestEventsExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidMaxResultsException): DescribePullRequestEventsExceptionsUnion = value.asInstanceOf[DescribePullRequestEventsExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidPullRequestEventTypeException): DescribePullRequestEventsExceptionsUnion = value.asInstanceOf[DescribePullRequestEventsExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidPullRequestIdException): DescribePullRequestEventsExceptionsUnion = value.asInstanceOf[DescribePullRequestEventsExceptionsUnion]
  @scala.inline
  implicit def apply(value: PullRequestDoesNotExistException): DescribePullRequestEventsExceptionsUnion = value.asInstanceOf[DescribePullRequestEventsExceptionsUnion]
  @scala.inline
  implicit def apply(value: PullRequestIdRequiredException): DescribePullRequestEventsExceptionsUnion = value.asInstanceOf[DescribePullRequestEventsExceptionsUnion]
}

