package typingsSlinky.domDashHelpers

import typingsSlinky.domDashHelpers.cjsAddEventListenerMod.EventHandler
import typingsSlinky.domDashHelpers.domDashHelpersStrings.abort
import typingsSlinky.domDashHelpers.domDashHelpersStrings.animationcancel
import typingsSlinky.domDashHelpers.domDashHelpersStrings.animationend
import typingsSlinky.domDashHelpers.domDashHelpersStrings.animationiteration
import typingsSlinky.domDashHelpers.domDashHelpersStrings.animationstart
import typingsSlinky.domDashHelpers.domDashHelpersStrings.auxclick
import typingsSlinky.domDashHelpers.domDashHelpersStrings.blur
import typingsSlinky.domDashHelpers.domDashHelpersStrings.cancel
import typingsSlinky.domDashHelpers.domDashHelpersStrings.canplay
import typingsSlinky.domDashHelpers.domDashHelpersStrings.canplaythrough
import typingsSlinky.domDashHelpers.domDashHelpersStrings.change
import typingsSlinky.domDashHelpers.domDashHelpersStrings.click
import typingsSlinky.domDashHelpers.domDashHelpersStrings.close
import typingsSlinky.domDashHelpers.domDashHelpersStrings.contextmenu
import typingsSlinky.domDashHelpers.domDashHelpersStrings.copy
import typingsSlinky.domDashHelpers.domDashHelpersStrings.cuechange
import typingsSlinky.domDashHelpers.domDashHelpersStrings.cut
import typingsSlinky.domDashHelpers.domDashHelpersStrings.dblclick
import typingsSlinky.domDashHelpers.domDashHelpersStrings.drag
import typingsSlinky.domDashHelpers.domDashHelpersStrings.dragend
import typingsSlinky.domDashHelpers.domDashHelpersStrings.dragenter
import typingsSlinky.domDashHelpers.domDashHelpersStrings.dragexit
import typingsSlinky.domDashHelpers.domDashHelpersStrings.dragleave
import typingsSlinky.domDashHelpers.domDashHelpersStrings.dragover
import typingsSlinky.domDashHelpers.domDashHelpersStrings.dragstart
import typingsSlinky.domDashHelpers.domDashHelpersStrings.drop
import typingsSlinky.domDashHelpers.domDashHelpersStrings.durationchange
import typingsSlinky.domDashHelpers.domDashHelpersStrings.emptied
import typingsSlinky.domDashHelpers.domDashHelpersStrings.ended
import typingsSlinky.domDashHelpers.domDashHelpersStrings.error
import typingsSlinky.domDashHelpers.domDashHelpersStrings.focus
import typingsSlinky.domDashHelpers.domDashHelpersStrings.focusin
import typingsSlinky.domDashHelpers.domDashHelpersStrings.focusout
import typingsSlinky.domDashHelpers.domDashHelpersStrings.fullscreenchange
import typingsSlinky.domDashHelpers.domDashHelpersStrings.fullscreenerror
import typingsSlinky.domDashHelpers.domDashHelpersStrings.gotpointercapture
import typingsSlinky.domDashHelpers.domDashHelpersStrings.input
import typingsSlinky.domDashHelpers.domDashHelpersStrings.invalid
import typingsSlinky.domDashHelpers.domDashHelpersStrings.keydown
import typingsSlinky.domDashHelpers.domDashHelpersStrings.keypress
import typingsSlinky.domDashHelpers.domDashHelpersStrings.keyup
import typingsSlinky.domDashHelpers.domDashHelpersStrings.load
import typingsSlinky.domDashHelpers.domDashHelpersStrings.loadeddata
import typingsSlinky.domDashHelpers.domDashHelpersStrings.loadedmetadata
import typingsSlinky.domDashHelpers.domDashHelpersStrings.loadend
import typingsSlinky.domDashHelpers.domDashHelpersStrings.loadstart
import typingsSlinky.domDashHelpers.domDashHelpersStrings.lostpointercapture
import typingsSlinky.domDashHelpers.domDashHelpersStrings.mousedown
import typingsSlinky.domDashHelpers.domDashHelpersStrings.mouseenter
import typingsSlinky.domDashHelpers.domDashHelpersStrings.mouseleave
import typingsSlinky.domDashHelpers.domDashHelpersStrings.mousemove
import typingsSlinky.domDashHelpers.domDashHelpersStrings.mouseout
import typingsSlinky.domDashHelpers.domDashHelpersStrings.mouseover
import typingsSlinky.domDashHelpers.domDashHelpersStrings.mouseup
import typingsSlinky.domDashHelpers.domDashHelpersStrings.paste
import typingsSlinky.domDashHelpers.domDashHelpersStrings.pause
import typingsSlinky.domDashHelpers.domDashHelpersStrings.play
import typingsSlinky.domDashHelpers.domDashHelpersStrings.playing
import typingsSlinky.domDashHelpers.domDashHelpersStrings.pointercancel
import typingsSlinky.domDashHelpers.domDashHelpersStrings.pointerdown
import typingsSlinky.domDashHelpers.domDashHelpersStrings.pointerenter
import typingsSlinky.domDashHelpers.domDashHelpersStrings.pointerleave
import typingsSlinky.domDashHelpers.domDashHelpersStrings.pointermove
import typingsSlinky.domDashHelpers.domDashHelpersStrings.pointerout
import typingsSlinky.domDashHelpers.domDashHelpersStrings.pointerover
import typingsSlinky.domDashHelpers.domDashHelpersStrings.pointerup
import typingsSlinky.domDashHelpers.domDashHelpersStrings.progress
import typingsSlinky.domDashHelpers.domDashHelpersStrings.ratechange
import typingsSlinky.domDashHelpers.domDashHelpersStrings.reset
import typingsSlinky.domDashHelpers.domDashHelpersStrings.resize
import typingsSlinky.domDashHelpers.domDashHelpersStrings.scroll
import typingsSlinky.domDashHelpers.domDashHelpersStrings.securitypolicyviolation
import typingsSlinky.domDashHelpers.domDashHelpersStrings.seeked
import typingsSlinky.domDashHelpers.domDashHelpersStrings.seeking
import typingsSlinky.domDashHelpers.domDashHelpersStrings.select
import typingsSlinky.domDashHelpers.domDashHelpersStrings.selectionchange
import typingsSlinky.domDashHelpers.domDashHelpersStrings.selectstart
import typingsSlinky.domDashHelpers.domDashHelpersStrings.stalled
import typingsSlinky.domDashHelpers.domDashHelpersStrings.submit
import typingsSlinky.domDashHelpers.domDashHelpersStrings.suspend
import typingsSlinky.domDashHelpers.domDashHelpersStrings.timeupdate
import typingsSlinky.domDashHelpers.domDashHelpersStrings.toggle
import typingsSlinky.domDashHelpers.domDashHelpersStrings.touchcancel
import typingsSlinky.domDashHelpers.domDashHelpersStrings.touchend
import typingsSlinky.domDashHelpers.domDashHelpersStrings.touchmove
import typingsSlinky.domDashHelpers.domDashHelpersStrings.touchstart
import typingsSlinky.domDashHelpers.domDashHelpersStrings.transitioncancel
import typingsSlinky.domDashHelpers.domDashHelpersStrings.transitionend
import typingsSlinky.domDashHelpers.domDashHelpersStrings.transitionrun
import typingsSlinky.domDashHelpers.domDashHelpersStrings.transitionstart
import typingsSlinky.domDashHelpers.domDashHelpersStrings.volumechange
import typingsSlinky.domDashHelpers.domDashHelpersStrings.waiting
import typingsSlinky.domDashHelpers.domDashHelpersStrings.wheel
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait Fn_AbortAnimationcancelAnimationend extends js.Object {
  def apply(
    selector: String,
    handler: EventHandler[
      abort | animationcancel | animationend | animationiteration | animationstart | auxclick | blur | cancel | canplay | canplaythrough | change | click | close | contextmenu | copy | cuechange | cut | dblclick | drag | dragend | dragenter | dragexit | dragleave | dragover | dragstart | drop | durationchange | emptied | ended | error | focus | focusin | focusout | fullscreenchange | fullscreenerror | gotpointercapture | input | invalid | keydown | keypress | keyup | load | loadeddata | loadedmetadata | loadend | loadstart | lostpointercapture | mousedown | mouseenter | mouseleave | mousemove | mouseout | mouseover | mouseup | paste | pause | play | playing | pointercancel | pointerdown | pointerenter | pointerleave | pointermove | pointerout | pointerover | pointerup | progress | ratechange | reset | resize | scroll | securitypolicyviolation | seeked | seeking | select | selectionchange | selectstart | stalled | submit | suspend | timeupdate | toggle | touchcancel | touchend | touchmove | touchstart | transitioncancel | transitionend | transitionrun | transitionstart | volumechange | waiting | wheel
    ]
  ): EventHandler[fullscreenchange] = js.native
}

