package typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener

import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.abort
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.animationcancel
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.animationend
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.animationiteration
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.animationstart
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.auxclick
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.blur
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.cancel
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.canplay
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.canplaythrough
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.change
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.click
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.close
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.contextmenu
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.copy
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.cuechange
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.cut
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.dblclick
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.drag
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.dragend
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.dragenter
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.dragexit
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.dragleave
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.dragover
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.dragstart
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.drop
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.durationchange
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.emptied
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.ended
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.error
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.focus
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.focusin
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.focusout
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.fullscreenchange
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.fullscreenerror
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.gotpointercapture
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.input
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.invalid
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.keydown
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.keypress
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.keyup
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.load
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.loadeddata
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.loadedmetadata
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.loadend
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.loadstart
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.lostpointercapture
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.mousedown
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.mouseenter
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.mouseleave
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.mousemove
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.mouseout
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.mouseover
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.mouseup
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.paste
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.pause
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.play
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.playing
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.pointercancel
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.pointerdown
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.pointerenter
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.pointerleave
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.pointerlockchange
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.pointerlockerror
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.pointermove
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.pointerout
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.pointerover
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.pointerup
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.progress
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.ratechange
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.readystatechange
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.reset
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.resize
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.scroll
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.securitypolicyviolation
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.seeked
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.seeking
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.select
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.selectionchange
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.selectstart
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.stalled
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.submit
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.suspend
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.timeupdate
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.toggle
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.touchcancel
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.touchend
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.touchmove
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.touchstart
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.transitioncancel
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.transitionend
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.transitionrun
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.transitionstart
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.visibilitychange
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.volumechange
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.waiting
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.atStardustDashUiReactDashComponentDashEventDashListenerStrings.wheel
import typingsSlinky.atStardustDashUiReactDashComponentDashEventDashListener.distEsTypesMod.EventListenerOptions
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@JSImport("@stardust-ui/react-component-event-listener/dist/es/EventListener", JSImport.Namespace)
@js.native
object distEsEventListenerMod extends js.Object {
  @js.native
  object default extends js.Object {
    var displayName: String = js.native
    var propTypes: Anon_Abort | Anon_Capture = js.native
    def apply(
      props: EventListenerOptions[
          abort | animationcancel | animationend | animationiteration | animationstart | auxclick | blur | cancel | canplay | canplaythrough | change | click | close | contextmenu | copy | cuechange | cut | dblclick | drag | dragend | dragenter | dragexit | dragleave | dragover | dragstart | drop | durationchange | emptied | ended | error | focus | focusin | focusout | fullscreenchange | fullscreenerror | gotpointercapture | input | invalid | keydown | keypress | keyup | load | loadeddata | loadedmetadata | loadend | loadstart | lostpointercapture | mousedown | mouseenter | mouseleave | mousemove | mouseout | mouseover | mouseup | paste | pause | play | playing | pointercancel | pointerdown | pointerenter | pointerleave | pointerlockchange | pointerlockerror | pointermove | pointerout | pointerover | pointerup | progress | ratechange | readystatechange | reset | resize | scroll | securitypolicyviolation | seeked | seeking | select | selectionchange | selectstart | stalled | submit | suspend | timeupdate | toggle | touchcancel | touchend | touchmove | touchstart | transitioncancel | transitionend | transitionrun | transitionstart | visibilitychange | volumechange | waiting | wheel
        ]
    ): js.Any = js.native
    @js.native
    object defaultProps extends js.Object {
      var capture: Boolean = js.native
    }
    
  }
  
}

