package typingsSlinky.pulumiAws.iamMod

import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashAWSLambdaInvocation-DynamoDB`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashAWSMarketplaceRead-only`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashAmazonMobileAnalyticsNon-financialReportAccess`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashjob-functionSlashBilling`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashjob-functionSlashDataScientist`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashjob-functionSlashDatabaseAdministrator`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashjob-functionSlashNetworkAdministrator`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashjob-functionSlashSupportUser`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashjob-functionSlashSystemAdministrator`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashjob-functionSlashViewOnlyAccess`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSBatchServiceRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSCloudHSMRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSCodeDeployRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSCodeStarServiceRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSConfigRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSConfigRulesExecutionRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSDataPipelineRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSElasticBeanstalkEnhancedHealth`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSElasticBeanstalkService`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSGreengrassResourceAccessRolePolicy`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSIoTLogging`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSIoTRuleActions`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSLambdaBasicExecutionRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSLambdaDynamoDBExecutionRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSLambdaENIManagementAccess`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSLambdaKinesisExecutionRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSLambdaRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSLambdaSQSQueueExecutionRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSLambdaVPCAccessExecutionRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSMobileHub_ServiceUseOnly`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSOpsWorksCMServiceRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSOpsWorksRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSQuickSightDescribeRDS`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSQuickSightDescribeRedshift`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSQuickSightListIAM`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSQuicksightAthenaAccess`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonAPIGatewayPushToCloudWatchLogs`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonAppStreamServiceAccess`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonDMSCloudWatchLogsRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonDMSRedshiftS3Role`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonDMSVPCManagementRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonEC2ContainerServiceAutoscaleRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonEC2ContainerServiceRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonEC2ContainerServiceforEC2Role`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonEC2RoleforAWSCodeDeploy`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonEC2RoleforDataPipelineRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonEC2RoleforSSM`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonEC2SpotFleetAutoscaleRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonEC2SpotFleetRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonEC2SpotFleetTaggingRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonElasticMapReduceRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonElasticMapReduceforAutoScalingRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonElasticMapReduceforEC2Role`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonElasticTranscoderRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonMachineLearningRoleforRedshiftDataSource`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonRDSDirectoryServiceAccess`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonRDSEnhancedMonitoringRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonSNSRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonSSMAutomationRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonSSMMaintenanceWindowRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashApplicationAutoScalingForAmazonAppStreamAccess`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAutoScalingNotificationAccessRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashCloudWatchEventsBuiltInTargetExecutionAccess`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashCloudWatchEventsInvocationAccess`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashRDSCloudHsmAuthorizationRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashServerMigrationServiceRole`
import typingsSlinky.pulumiAws.pulumiAwsStrings.`arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashVMImportExportRoleForAWSConnector`
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSAccountActivityAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSAccountUsageReportAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSAgentlessDiscoveryService
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSApplicationDiscoveryAgentAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSApplicationDiscoveryServiceFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSBatchFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSCertificateManagerFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSCertificateManagerReadOnly
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSCloudFormationReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSCloudHSMFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSCloudHSMReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSCloudTrailFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSCloudTrailReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSCodeBuildAdminAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSCodeBuildDeveloperAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSCodeBuildReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSCodeCommitFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSCodeCommitPowerUser
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSCodeCommitReadOnly
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSCodeDeployDeployerAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSCodeDeployFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSCodeDeployReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSCodeDeployRoleForECS
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSCodePipelineApproverAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSCodePipelineCustomActionAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSCodePipelineFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSCodePipelineReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSCodeStarFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSConfigUserAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSConnector
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSDataPipeline_FullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSDataPipeline_PowerUser
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSDeviceFarmFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSDirectConnectFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSDirectConnectReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSDirectoryServiceFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSDirectoryServiceReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSElasticBeanstalkCustomPlatformforEC2Role
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSElasticBeanstalkFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSElasticBeanstalkMulticontainerDocker
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSElasticBeanstalkReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSElasticBeanstalkWebTier
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSElasticBeanstalkWorkerTier
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSGreengrassFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSHealthFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSImportExportFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSImportExportReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSIoTConfigAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSIoTConfigReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSIoTDataAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSIoTFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSKeyManagementServicePowerUser
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSLambdaExecute
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSLambdaFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSLambdaReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSMarketplaceFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSMarketplaceGetEntitlements
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSMarketplaceManageSubscriptions
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSMarketplaceMeteringFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSMobileHub_FullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSMobileHub_ReadOnly
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSOpsWorksCMInstanceProfileRole
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSOpsWorksCloudWatchLogs
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSOpsWorksFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSOpsWorksInstanceRegistration
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSOpsWorksRegisterCLI
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSStepFunctionsConsoleFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSStepFunctionsFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSStepFunctionsReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSStorageGatewayFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSStorageGatewayReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSSupportAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSWAFFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSWAFReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSXRayDaemonWriteAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSXrayFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSXrayReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAWSXrayWriteOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAdministratorAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonAPIGatewayAdministrator
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonAPIGatewayInvokeFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonAppStreamFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonAppStreamReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonAthenaFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonCloudDirectoryFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonCloudDirectoryReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonCognitoDeveloperAuthenticatedIdentities
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonCognitoPowerUser
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonCognitoReadOnly
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonDRSVPCManagement
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonDynamoDBFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonDynamoDBFullAccesswithDataPipeline
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonDynamoDBReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonEC2ContainerRegistryFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonEC2ContainerRegistryPowerUser
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonEC2ContainerRegistryReadOnly
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonEC2ContainerServiceFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonEC2FullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonEC2ReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonEC2ReportsAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonESFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonESReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonElastiCacheFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonElastiCacheReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonElasticFileSystemFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonElasticFileSystemReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonElasticMapReduceFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonElasticMapReduceReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonElasticTranscoderFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonElasticTranscoderJobsSubmitter
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonElasticTranscoderReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonGlacierFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonGlacierReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonInspectorFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonInspectorReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonKinesisAnalyticsFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonKinesisAnalyticsReadOnly
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonKinesisFirehoseFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonKinesisFirehoseReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonKinesisFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonKinesisReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonLexFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonLexReadOnly
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonLexRunBotsOnly
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonMachineLearningBatchPredictionsAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonMachineLearningCreateOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonMachineLearningFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonMachineLearningManageRealTimeEndpointOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonMachineLearningReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonMachineLearningRealTimePredictionOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonMechanicalTurkFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonMechanicalTurkReadOnly
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonMobileAnalyticsFinancialReportAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonMobileAnalyticsFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonMobileAnalyticsWriteOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonPollyFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonPollyReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonRDSDataFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonRDSFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonRDSReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonRedshiftFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonRedshiftReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonRekognitionFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonRekognitionReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonRoute53DomainsFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonRoute53DomainsReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonRoute53FullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonRoute53ReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonS3FullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonS3ReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonSESFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonSESReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonSNSFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonSNSReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonSQSFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonSQSReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonSSMAutomationApproverAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonSSMDirectoryServiceAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonSSMFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonSSMManagedInstanceCore
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonSSMPatchAssociation
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonSSMReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonVPCFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonVPCReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonWorkMailFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonWorkMailReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonWorkSpacesAdmin
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonWorkSpacesApplicationManagerAdminAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonZocaloFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAmazonZocaloReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAutoScalingConsoleFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAutoScalingConsoleReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAutoScalingFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashAutoScalingReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashCloudFrontFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashCloudFrontReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashCloudSearchFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashCloudSearchReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashCloudWatchActionsEC2Access
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashCloudWatchEventsFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashCloudWatchEventsReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashCloudWatchFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashCloudWatchLogsFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashCloudWatchLogsReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashCloudWatchReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashIAMFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashIAMReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashIAMSelfManageServiceSpecificCredentials
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashIAMUserChangePassword
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashIAMUserSSHKeys
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashPowerUserAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashResourceGroupsandTagEditorFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashResourceGroupsandTagEditorReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashSecurityAudit
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashServerMigrationConnector
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashServiceCatalogAdminFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashServiceCatalogAdminReadOnlyAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashServiceCatalogEndUserAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashServiceCatalogEndUserFullAccess
import typingsSlinky.pulumiAws.pulumiAwsStrings.arnColonawsColoniamColonColonawsColonpolicySlashSimpleWorkflowFullAccess
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

@JSImport("@pulumi/aws/iam", "ManagedPolicy")
@js.native
object ManagedPolicy extends js.Object {
  
  val AWSAccountActivityAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSAccountActivityAccess = js.native
  
  val AWSAccountUsageReportAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSAccountUsageReportAccess = js.native
  
  val AWSAgentlessDiscoveryService: arnColonawsColoniamColonColonawsColonpolicySlashAWSAgentlessDiscoveryService = js.native
  
  val AWSApplicationDiscoveryAgentAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSApplicationDiscoveryAgentAccess = js.native
  
  val AWSApplicationDiscoveryServiceFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSApplicationDiscoveryServiceFullAccess = js.native
  
  val AWSBatchFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSBatchFullAccess = js.native
  
  val AWSBatchServiceRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSBatchServiceRole` = js.native
  
  val AWSCertificateManagerFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSCertificateManagerFullAccess = js.native
  
  val AWSCertificateManagerReadOnly: arnColonawsColoniamColonColonawsColonpolicySlashAWSCertificateManagerReadOnly = js.native
  
  val AWSCloudFormationReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSCloudFormationReadOnlyAccess = js.native
  
  val AWSCloudHSMFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSCloudHSMFullAccess = js.native
  
  val AWSCloudHSMReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSCloudHSMReadOnlyAccess = js.native
  
  val AWSCloudHSMRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSCloudHSMRole` = js.native
  
  val AWSCloudTrailFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSCloudTrailFullAccess = js.native
  
  val AWSCloudTrailReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSCloudTrailReadOnlyAccess = js.native
  
  val AWSCodeBuildAdminAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSCodeBuildAdminAccess = js.native
  
  val AWSCodeBuildDeveloperAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSCodeBuildDeveloperAccess = js.native
  
  val AWSCodeBuildReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSCodeBuildReadOnlyAccess = js.native
  
  val AWSCodeCommitFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSCodeCommitFullAccess = js.native
  
  val AWSCodeCommitPowerUser: arnColonawsColoniamColonColonawsColonpolicySlashAWSCodeCommitPowerUser = js.native
  
  val AWSCodeCommitReadOnly: arnColonawsColoniamColonColonawsColonpolicySlashAWSCodeCommitReadOnly = js.native
  
  val AWSCodeDeployDeployerAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSCodeDeployDeployerAccess = js.native
  
  val AWSCodeDeployFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSCodeDeployFullAccess = js.native
  
  val AWSCodeDeployReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSCodeDeployReadOnlyAccess = js.native
  
  val AWSCodeDeployRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSCodeDeployRole` = js.native
  
  val AWSCodeDeployRoleForECS: arnColonawsColoniamColonColonawsColonpolicySlashAWSCodeDeployRoleForECS = js.native
  
  val AWSCodePipelineApproverAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSCodePipelineApproverAccess = js.native
  
  val AWSCodePipelineCustomActionAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSCodePipelineCustomActionAccess = js.native
  
  val AWSCodePipelineFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSCodePipelineFullAccess = js.native
  
  val AWSCodePipelineReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSCodePipelineReadOnlyAccess = js.native
  
  val AWSCodeStarFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSCodeStarFullAccess = js.native
  
  val AWSCodeStarServiceRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSCodeStarServiceRole` = js.native
  
  val AWSConfigRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSConfigRole` = js.native
  
  val AWSConfigRulesExecutionRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSConfigRulesExecutionRole` = js.native
  
  val AWSConfigUserAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSConfigUserAccess = js.native
  
  val AWSConnector: arnColonawsColoniamColonColonawsColonpolicySlashAWSConnector = js.native
  
  val AWSDataPipelineRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSDataPipelineRole` = js.native
  
  val AWSDataPipeline_FullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSDataPipeline_FullAccess = js.native
  
  val AWSDataPipeline_PowerUser: arnColonawsColoniamColonColonawsColonpolicySlashAWSDataPipeline_PowerUser = js.native
  
  val AWSDeviceFarmFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSDeviceFarmFullAccess = js.native
  
  val AWSDirectConnectFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSDirectConnectFullAccess = js.native
  
  val AWSDirectConnectReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSDirectConnectReadOnlyAccess = js.native
  
  val AWSDirectoryServiceFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSDirectoryServiceFullAccess = js.native
  
  val AWSDirectoryServiceReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSDirectoryServiceReadOnlyAccess = js.native
  
  val AWSElasticBeanstakWorkerTier: arnColonawsColoniamColonColonawsColonpolicySlashAWSElasticBeanstalkWorkerTier = js.native
  
  val AWSElasticBeanstalkCustomPlatformforEC2Role: arnColonawsColoniamColonColonawsColonpolicySlashAWSElasticBeanstalkCustomPlatformforEC2Role = js.native
  
  val AWSElasticBeanstalkEnhancedHealth: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSElasticBeanstalkEnhancedHealth` = js.native
  
  val AWSElasticBeanstalkFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSElasticBeanstalkFullAccess = js.native
  
  val AWSElasticBeanstalkMulticontainerDocker: arnColonawsColoniamColonColonawsColonpolicySlashAWSElasticBeanstalkMulticontainerDocker = js.native
  
  val AWSElasticBeanstalkReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSElasticBeanstalkReadOnlyAccess = js.native
  
  val AWSElasticBeanstalkService: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSElasticBeanstalkService` = js.native
  
  val AWSElasticBeanstalkWebTier: arnColonawsColoniamColonColonawsColonpolicySlashAWSElasticBeanstalkWebTier = js.native
  
  val AWSGreengrassFullccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSGreengrassFullAccess = js.native
  
  val AWSGreengrassResourceAccessRolePolicy: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSGreengrassResourceAccessRolePolicy` = js.native
  
  val AWSHealthFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSHealthFullAccess = js.native
  
  val AWSImportExportFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSImportExportFullAccess = js.native
  
  val AWSImportExportReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSImportExportReadOnlyAccess = js.native
  
  val AWSIoTConfigAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSIoTConfigAccess = js.native
  
  val AWSIoTConfigReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSIoTConfigReadOnlyAccess = js.native
  
  val AWSIoTDataAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSIoTDataAccess = js.native
  
  val AWSIoTFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSIoTFullAccess = js.native
  
  val AWSIoTLogging: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSIoTLogging` = js.native
  
  val AWSIoTRuleActions: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSIoTRuleActions` = js.native
  
  val AWSKeyManagementServicePowerUser: arnColonawsColoniamColonColonawsColonpolicySlashAWSKeyManagementServicePowerUser = js.native
  
  val AWSLambdaBasicExecutionRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSLambdaBasicExecutionRole` = js.native
  
  val AWSLambdaDynamoDBExecutionRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSLambdaDynamoDBExecutionRole` = js.native
  
  val AWSLambdaENIManagementAccess: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSLambdaENIManagementAccess` = js.native
  
  val AWSLambdaExecute: arnColonawsColoniamColonColonawsColonpolicySlashAWSLambdaExecute = js.native
  
  val AWSLambdaFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSLambdaFullAccess = js.native
  
  val AWSLambdaInvocationDynamoDB: `arnColonawsColoniamColonColonawsColonpolicySlashAWSLambdaInvocation-DynamoDB` = js.native
  
  val AWSLambdaKinesisExecutionRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSLambdaKinesisExecutionRole` = js.native
  
  val AWSLambdaReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSLambdaReadOnlyAccess = js.native
  
  val AWSLambdaRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSLambdaRole` = js.native
  
  val AWSLambdaSQSQueueExecutionRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSLambdaSQSQueueExecutionRole` = js.native
  
  val AWSLambdaVPCAccessExecutionRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSLambdaVPCAccessExecutionRole` = js.native
  
  val AWSMarketplaceFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSMarketplaceFullAccess = js.native
  
  val AWSMarketplaceGetEntitlements: arnColonawsColoniamColonColonawsColonpolicySlashAWSMarketplaceGetEntitlements = js.native
  
  val AWSMarketplaceManageSubscriptions: arnColonawsColoniamColonColonawsColonpolicySlashAWSMarketplaceManageSubscriptions = js.native
  
  val AWSMarketplaceMeteringFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSMarketplaceMeteringFullAccess = js.native
  
  val AWSMarketplaceReadonly: `arnColonawsColoniamColonColonawsColonpolicySlashAWSMarketplaceRead-only` = js.native
  
  val AWSMobileHub_FullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSMobileHub_FullAccess = js.native
  
  val AWSMobileHub_ReadOnly: arnColonawsColoniamColonColonawsColonpolicySlashAWSMobileHub_ReadOnly = js.native
  
  val AWSMobileHub_ServiceUseOnly: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSMobileHub_ServiceUseOnly` = js.native
  
  val AWSOpsWorksCMInstanceProfileRole: arnColonawsColoniamColonColonawsColonpolicySlashAWSOpsWorksCMInstanceProfileRole = js.native
  
  val AWSOpsWorksCMServiceRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSOpsWorksCMServiceRole` = js.native
  
  val AWSOpsWorksCloudWatchLogs: arnColonawsColoniamColonColonawsColonpolicySlashAWSOpsWorksCloudWatchLogs = js.native
  
  val AWSOpsWorksFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSOpsWorksFullAccess = js.native
  
  val AWSOpsWorksInstanceRegistration: arnColonawsColoniamColonColonawsColonpolicySlashAWSOpsWorksInstanceRegistration = js.native
  
  val AWSOpsWorksRegisterCLI: arnColonawsColoniamColonColonawsColonpolicySlashAWSOpsWorksRegisterCLI = js.native
  
  val AWSOpsWorksRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSOpsWorksRole` = js.native
  
  val AWSQuickSightDescribeRD: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSQuickSightDescribeRDS` = js.native
  
  val AWSQuickSightDescribeRedshift: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSQuickSightDescribeRedshift` = js.native
  
  val AWSQuickSightListIAM: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSQuickSightListIAM` = js.native
  
  val AWSQuicksightAthenaAccess: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAWSQuicksightAthenaAccess` = js.native
  
  val AWSStepFunctionsConsoleFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSStepFunctionsConsoleFullAccess = js.native
  
  val AWSStepFunctionsFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSStepFunctionsFullAccess = js.native
  
  val AWSStepFunctionsReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSStepFunctionsReadOnlyAccess = js.native
  
  val AWSStorageGatewayFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSStorageGatewayFullAccess = js.native
  
  val AWSStorageGatewayReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSStorageGatewayReadOnlyAccess = js.native
  
  val AWSSupportAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSSupportAccess = js.native
  
  val AWSWAFFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSWAFFullAccess = js.native
  
  val AWSWAFReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSWAFReadOnlyAccess = js.native
  
  val AWSXRayDaemonWriteAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSXRayDaemonWriteAccess = js.native
  
  val AWSXrayFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSXrayFullAccess = js.native
  
  val AWSXrayReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSXrayReadOnlyAccess = js.native
  
  val AWSXrayWriteOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAWSXrayWriteOnlyAccess = js.native
  
  val AdministratorAccess: arnColonawsColoniamColonColonawsColonpolicySlashAdministratorAccess = js.native
  
  val AmazonAPIGatewayAdministrator: arnColonawsColoniamColonColonawsColonpolicySlashAmazonAPIGatewayAdministrator = js.native
  
  val AmazonAPIGatewayInvokeFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonAPIGatewayInvokeFullAccess = js.native
  
  val AmazonAPIGatewayPushToCloudWatchLogs: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonAPIGatewayPushToCloudWatchLogs` = js.native
  
  val AmazonAppStreamFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonAppStreamFullAccess = js.native
  
  val AmazonAppStreamReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonAppStreamReadOnlyAccess = js.native
  
  val AmazonAppStreamServiceAccess: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonAppStreamServiceAccess` = js.native
  
  val AmazonAthenaFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonAthenaFullAccess = js.native
  
  val AmazonCloudDirectoryFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonCloudDirectoryFullAccess = js.native
  
  val AmazonCloudDirectoryReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonCloudDirectoryReadOnlyAccess = js.native
  
  val AmazonCognitoDeveloperAuthenticatedIdentities: arnColonawsColoniamColonColonawsColonpolicySlashAmazonCognitoDeveloperAuthenticatedIdentities = js.native
  
  val AmazonCognitoPowerUser: arnColonawsColoniamColonColonawsColonpolicySlashAmazonCognitoPowerUser = js.native
  
  val AmazonCognitoReadOnly: arnColonawsColoniamColonColonawsColonpolicySlashAmazonCognitoReadOnly = js.native
  
  val AmazonDMSCloudWatchLogsRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonDMSCloudWatchLogsRole` = js.native
  
  val AmazonDMSRedshiftS3Role: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonDMSRedshiftS3Role` = js.native
  
  val AmazonDMSVPCManagementRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonDMSVPCManagementRole` = js.native
  
  val AmazonDRSVPCManagement: arnColonawsColoniamColonColonawsColonpolicySlashAmazonDRSVPCManagement = js.native
  
  val AmazonDynamoDBFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonDynamoDBFullAccess = js.native
  
  val AmazonDynamoDBFullAccesswithDataPipeline: arnColonawsColoniamColonColonawsColonpolicySlashAmazonDynamoDBFullAccesswithDataPipeline = js.native
  
  val AmazonDynamoDBReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonDynamoDBReadOnlyAccess = js.native
  
  val AmazonEC2ContainerRegistryFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonEC2ContainerRegistryFullAccess = js.native
  
  val AmazonEC2ContainerRegistryPowerUser: arnColonawsColoniamColonColonawsColonpolicySlashAmazonEC2ContainerRegistryPowerUser = js.native
  
  val AmazonEC2ContainerRegistryReadOnly: arnColonawsColoniamColonColonawsColonpolicySlashAmazonEC2ContainerRegistryReadOnly = js.native
  
  val AmazonEC2ContainerServiceAutoscaleRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonEC2ContainerServiceAutoscaleRole` = js.native
  
  val AmazonEC2ContainerServiceFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonEC2ContainerServiceFullAccess = js.native
  
  val AmazonEC2ContainerServiceRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonEC2ContainerServiceRole` = js.native
  
  val AmazonEC2ContainerServiceforEC2Role: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonEC2ContainerServiceforEC2Role` = js.native
  
  val AmazonEC2FullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonEC2FullAccess = js.native
  
  val AmazonEC2ReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonEC2ReadOnlyAccess = js.native
  
  val AmazonEC2ReportsAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonEC2ReportsAccess = js.native
  
  val AmazonEC2RoleforAWSCodeDeploy: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonEC2RoleforAWSCodeDeploy` = js.native
  
  val AmazonEC2RoleforDataPipelineRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonEC2RoleforDataPipelineRole` = js.native
  
  val AmazonEC2RoleforSSM: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonEC2RoleforSSM` = js.native
  
  val AmazonEC2SpotFleetAutoscaleRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonEC2SpotFleetAutoscaleRole` = js.native
  
  val AmazonEC2SpotFleetRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonEC2SpotFleetRole` = js.native
  
  val AmazonEC2SpotFleetTaggingRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonEC2SpotFleetTaggingRole` = js.native
  
  val AmazonESFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonESFullAccess = js.native
  
  val AmazonESReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonESReadOnlyAccess = js.native
  
  val AmazonElastiCacheFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonElastiCacheFullAccess = js.native
  
  val AmazonElastiCacheReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonElastiCacheReadOnlyAccess = js.native
  
  val AmazonElasticFileSystemFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonElasticFileSystemFullAccess = js.native
  
  val AmazonElasticFileSystemReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonElasticFileSystemReadOnlyAccess = js.native
  
  val AmazonElasticMapReduceFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonElasticMapReduceFullAccess = js.native
  
  val AmazonElasticMapReduceReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonElasticMapReduceReadOnlyAccess = js.native
  
  val AmazonElasticMapReduceRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonElasticMapReduceRole` = js.native
  
  val AmazonElasticMapReduceforAutoScalingRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonElasticMapReduceforAutoScalingRole` = js.native
  
  val AmazonElasticMapReduceforEC2Role: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonElasticMapReduceforEC2Role` = js.native
  
  val AmazonElasticTranscoderFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonElasticTranscoderFullAccess = js.native
  
  val AmazonElasticTranscoderJobsSubmitter: arnColonawsColoniamColonColonawsColonpolicySlashAmazonElasticTranscoderJobsSubmitter = js.native
  
  val AmazonElasticTranscoderReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonElasticTranscoderReadOnlyAccess = js.native
  
  val AmazonElasticTranscoderRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonElasticTranscoderRole` = js.native
  
  val AmazonGlacierFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonGlacierFullAccess = js.native
  
  val AmazonGlacierReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonGlacierReadOnlyAccess = js.native
  
  val AmazonInspectorFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonInspectorFullAccess = js.native
  
  val AmazonInspectorReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonInspectorReadOnlyAccess = js.native
  
  val AmazonKinesisAnalyticsFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonKinesisAnalyticsFullAccess = js.native
  
  val AmazonKinesisAnalyticsReadOnly: arnColonawsColoniamColonColonawsColonpolicySlashAmazonKinesisAnalyticsReadOnly = js.native
  
  val AmazonKinesisFirehoseFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonKinesisFirehoseFullAccess = js.native
  
  val AmazonKinesisFirehoseReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonKinesisFirehoseReadOnlyAccess = js.native
  
  val AmazonKinesisFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonKinesisFullAccess = js.native
  
  val AmazonKinesisReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonKinesisReadOnlyAccess = js.native
  
  val AmazonLexFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonLexFullAccess = js.native
  
  val AmazonLexReadOnly: arnColonawsColoniamColonColonawsColonpolicySlashAmazonLexReadOnly = js.native
  
  val AmazonLexRunBotsOnly: arnColonawsColoniamColonColonawsColonpolicySlashAmazonLexRunBotsOnly = js.native
  
  val AmazonMachineLearningBatchPredictionsAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonMachineLearningBatchPredictionsAccess = js.native
  
  val AmazonMachineLearningCreateOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonMachineLearningCreateOnlyAccess = js.native
  
  val AmazonMachineLearningFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonMachineLearningFullAccess = js.native
  
  val AmazonMachineLearningManageRealTimeEndpointOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonMachineLearningManageRealTimeEndpointOnlyAccess = js.native
  
  val AmazonMachineLearningReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonMachineLearningReadOnlyAccess = js.native
  
  val AmazonMachineLearningRealTimePredictionOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonMachineLearningRealTimePredictionOnlyAccess = js.native
  
  val AmazonMachineLearningRoleforRedshiftDataSource: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonMachineLearningRoleforRedshiftDataSource` = js.native
  
  val AmazonMechanicalTurkFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonMechanicalTurkFullAccess = js.native
  
  val AmazonMechanicalTurkReadOnly: arnColonawsColoniamColonColonawsColonpolicySlashAmazonMechanicalTurkReadOnly = js.native
  
  val AmazonMobileAnalyticsFinancialReportAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonMobileAnalyticsFinancialReportAccess = js.native
  
  val AmazonMobileAnalyticsFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonMobileAnalyticsFullAccess = js.native
  
  val AmazonMobileAnalyticsNonfinancialReportAccess: `arnColonawsColoniamColonColonawsColonpolicySlashAmazonMobileAnalyticsNon-financialReportAccess` = js.native
  
  val AmazonMobileAnalyticsWriteOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonMobileAnalyticsWriteOnlyAccess = js.native
  
  val AmazonPollyFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonPollyFullAccess = js.native
  
  val AmazonPollyReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonPollyReadOnlyAccess = js.native
  
  val AmazonRDSDataFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonRDSDataFullAccess = js.native
  
  val AmazonRDSDirectoryServiceAccess: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonRDSDirectoryServiceAccess` = js.native
  
  val AmazonRDSEnhancedMonitoringRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonRDSEnhancedMonitoringRole` = js.native
  
  val AmazonRDSFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonRDSFullAccess = js.native
  
  val AmazonRDSReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonRDSReadOnlyAccess = js.native
  
  val AmazonRedshiftFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonRedshiftFullAccess = js.native
  
  val AmazonRedshiftReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonRedshiftReadOnlyAccess = js.native
  
  val AmazonRekognitionFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonRekognitionFullAccess = js.native
  
  val AmazonRekognitionReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonRekognitionReadOnlyAccess = js.native
  
  val AmazonRoute53DomainsFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonRoute53DomainsFullAccess = js.native
  
  val AmazonRoute53DomainsReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonRoute53DomainsReadOnlyAccess = js.native
  
  val AmazonRoute53FullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonRoute53FullAccess = js.native
  
  val AmazonRoute53ReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonRoute53ReadOnlyAccess = js.native
  
  val AmazonS3FullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonS3FullAccess = js.native
  
  val AmazonS3ReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonS3ReadOnlyAccess = js.native
  
  val AmazonSESFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonSESFullAccess = js.native
  
  val AmazonSESReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonSESReadOnlyAccess = js.native
  
  val AmazonSNSFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonSNSFullAccess = js.native
  
  val AmazonSNSReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonSNSReadOnlyAccess = js.native
  
  val AmazonSNSRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonSNSRole` = js.native
  
  val AmazonSQSFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonSQSFullAccess = js.native
  
  val AmazonSQSReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonSQSReadOnlyAccess = js.native
  
  val AmazonSSMAutomationApproverAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonSSMAutomationApproverAccess = js.native
  
  val AmazonSSMAutomationRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonSSMAutomationRole` = js.native
  
  val AmazonSSMDirectoryServiceAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonSSMDirectoryServiceAccess = js.native
  
  val AmazonSSMFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonSSMFullAccess = js.native
  
  val AmazonSSMMaintenanceWindowRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAmazonSSMMaintenanceWindowRole` = js.native
  
  val AmazonSSMManagedInstanceCore: arnColonawsColoniamColonColonawsColonpolicySlashAmazonSSMManagedInstanceCore = js.native
  
  val AmazonSSMPatchAssociation: arnColonawsColoniamColonColonawsColonpolicySlashAmazonSSMPatchAssociation = js.native
  
  val AmazonSSMReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonSSMReadOnlyAccess = js.native
  
  val AmazonVPCFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonVPCFullAccess = js.native
  
  val AmazonVPCReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonVPCReadOnlyAccess = js.native
  
  val AmazonWorkMailFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonWorkMailFullAccess = js.native
  
  val AmazonWorkMailReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonWorkMailReadOnlyAccess = js.native
  
  val AmazonWorkSpacesAdmin: arnColonawsColoniamColonColonawsColonpolicySlashAmazonWorkSpacesAdmin = js.native
  
  val AmazonWorkSpacesApplicationManagerAdminAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonWorkSpacesApplicationManagerAdminAccess = js.native
  
  val AmazonZocaloFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonZocaloFullAccess = js.native
  
  val AmazonZocaloReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAmazonZocaloReadOnlyAccess = js.native
  
  val ApplicationAutoScalingForAmazonAppStreamAccess: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashApplicationAutoScalingForAmazonAppStreamAccess` = js.native
  
  val AutoScalingConsoleFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAutoScalingConsoleFullAccess = js.native
  
  val AutoScalingConsoleReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAutoScalingConsoleReadOnlyAccess = js.native
  
  val AutoScalingFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashAutoScalingFullAccess = js.native
  
  val AutoScalingNotificationAccessRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashAutoScalingNotificationAccessRole` = js.native
  
  val AutoScalingReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashAutoScalingReadOnlyAccess = js.native
  
  val Billing: `arnColonawsColoniamColonColonawsColonpolicySlashjob-functionSlashBilling` = js.native
  
  val CloudFrontFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashCloudFrontFullAccess = js.native
  
  val CloudFrontReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashCloudFrontReadOnlyAccess = js.native
  
  val CloudSearchFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashCloudSearchFullAccess = js.native
  
  val CloudSearchReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashCloudSearchReadOnlyAccess = js.native
  
  val CloudWatchActionsEC2Access: arnColonawsColoniamColonColonawsColonpolicySlashCloudWatchActionsEC2Access = js.native
  
  val CloudWatchEventsBuiltInTargetExecutionAccess: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashCloudWatchEventsBuiltInTargetExecutionAccess` = js.native
  
  val CloudWatchEventsFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashCloudWatchEventsFullAccess = js.native
  
  val CloudWatchEventsInvocationAccess: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashCloudWatchEventsInvocationAccess` = js.native
  
  val CloudWatchEventsReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashCloudWatchEventsReadOnlyAccess = js.native
  
  val CloudWatchFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashCloudWatchFullAccess = js.native
  
  val CloudWatchLogsFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashCloudWatchLogsFullAccess = js.native
  
  val CloudWatchLogsReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashCloudWatchLogsReadOnlyAccess = js.native
  
  val CloudWatchReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashCloudWatchReadOnlyAccess = js.native
  
  val DataScientist: `arnColonawsColoniamColonColonawsColonpolicySlashjob-functionSlashDataScientist` = js.native
  
  val DatabaseAdministrator: `arnColonawsColoniamColonColonawsColonpolicySlashjob-functionSlashDatabaseAdministrator` = js.native
  
  val IAMFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashIAMFullAccess = js.native
  
  val IAMReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashIAMReadOnlyAccess = js.native
  
  val IAMSelfManageServiceSpecificCredentials: arnColonawsColoniamColonColonawsColonpolicySlashIAMSelfManageServiceSpecificCredentials = js.native
  
  val IAMUserChangePassword: arnColonawsColoniamColonColonawsColonpolicySlashIAMUserChangePassword = js.native
  
  val IAMUserSSHKeys: arnColonawsColoniamColonColonawsColonpolicySlashIAMUserSSHKeys = js.native
  
  val NetworkAdministrator: `arnColonawsColoniamColonColonawsColonpolicySlashjob-functionSlashNetworkAdministrator` = js.native
  
  val PowerUserAccess: arnColonawsColoniamColonColonawsColonpolicySlashPowerUserAccess = js.native
  
  val RDSCloudHsmAuthorizationRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashRDSCloudHsmAuthorizationRole` = js.native
  
  val ReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashReadOnlyAccess = js.native
  
  val ResourceGroupsandTagEditorFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashResourceGroupsandTagEditorFullAccess = js.native
  
  val ResourceGroupsandTagEditorReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashResourceGroupsandTagEditorReadOnlyAccess = js.native
  
  val SecurityAudit: arnColonawsColoniamColonColonawsColonpolicySlashSecurityAudit = js.native
  
  val ServerMigrationConnector: arnColonawsColoniamColonColonawsColonpolicySlashServerMigrationConnector = js.native
  
  val ServerMigrationServiceRole: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashServerMigrationServiceRole` = js.native
  
  val ServiceCatalogAdminFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashServiceCatalogAdminFullAccess = js.native
  
  val ServiceCatalogAdminReadOnlyAccess: arnColonawsColoniamColonColonawsColonpolicySlashServiceCatalogAdminReadOnlyAccess = js.native
  
  val ServiceCatalogEndUserAccess: arnColonawsColoniamColonColonawsColonpolicySlashServiceCatalogEndUserAccess = js.native
  
  val ServiceCatalogEndUserFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashServiceCatalogEndUserFullAccess = js.native
  
  val SimpleWorkflowFullAccess: arnColonawsColoniamColonColonawsColonpolicySlashSimpleWorkflowFullAccess = js.native
  
  val SupportUser: `arnColonawsColoniamColonColonawsColonpolicySlashjob-functionSlashSupportUser` = js.native
  
  val SystemAdministrator: `arnColonawsColoniamColonColonawsColonpolicySlashjob-functionSlashSystemAdministrator` = js.native
  
  val VMImportExportRoleForAWSConnector: `arnColonawsColoniamColonColonawsColonpolicySlashservice-roleSlashVMImportExportRoleForAWSConnector` = js.native
  
  val ViewOnlyAccess: `arnColonawsColoniamColonColonawsColonpolicySlashjob-functionSlashViewOnlyAccess` = js.native
}
