package typingsSlinky.pulumiAws.domainDkimMod

import typingsSlinky.pulumiPulumi.outputMod.Input
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait DomainDkimState extends js.Object {
  /**
    * DKIM tokens generated by SES.
    * These tokens should be used to create CNAME records used to verify SES Easy DKIM.
    * See below for an example of how this might be achieved
    * when the domain is hosted in Route 53 and managed by this provider.
    * Find out more about verifying domains in Amazon SES
    * in the [AWS SES docs](http://docs.aws.amazon.com/ses/latest/DeveloperGuide/easy-dkim-dns-records.html).
    */
  val dkimTokens: js.UndefOr[Input[js.Array[Input[String]]]] = js.native
  /**
    * Verified domain name to generate DKIM tokens for.
    */
  val domain: js.UndefOr[Input[String]] = js.native
}

object DomainDkimState {
  @scala.inline
  def apply(): DomainDkimState = {
    val __obj = js.Dynamic.literal()
    __obj.asInstanceOf[DomainDkimState]
  }
  @scala.inline
  implicit class DomainDkimStateOps[Self <: DomainDkimState] (val x: Self) extends AnyVal {
    @scala.inline
    def duplicate: Self = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x)).asInstanceOf[Self]
    @scala.inline
    def combineWith[Other <: js.Any](other: Other): Self with Other = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x, other.asInstanceOf[js.Any])).asInstanceOf[Self with Other]
    @scala.inline
    def withDkimTokens(value: Input[js.Array[Input[String]]]): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("dkimTokens")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutDkimTokens: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("dkimTokens")(js.undefined)
        ret
    }
    @scala.inline
    def withDomain(value: Input[String]): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("domain")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutDomain: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("domain")(js.undefined)
        ret
    }
  }
  
}

