package typingsSlinky.gapiClientGenomics.gapi.client.genomics

import typingsSlinky.std.Record
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait ImportVariantsRequest extends js.Object {
  /**
    * The format of the variant data being imported. If unspecified, defaults to
    * to `VCF`.
    */
  var format: js.UndefOr[String] = js.native
  /**
    * A mapping between info field keys and the InfoMergeOperations to
    * be performed on them. This is plumbed down to the MergeVariantRequests
    * generated by the resulting import job.
    */
  var infoMergeConfig: js.UndefOr[Record[String, String]] = js.native
  /**
    * Convert reference names to the canonical representation.
    * hg19 haploytypes (those reference names containing "_hap")
    * are not modified in any way.
    * All other reference names are modified according to the following rules:
    * The reference name is capitalized.
    * The "chr" prefix is dropped for all autosomes and sex chromsomes.
    * For example "chr17" becomes "17" and "chrX" becomes "X".
    * All mitochondrial chromosomes ("chrM", "chrMT", etc) become "MT".
    */
  var normalizeReferenceNames: js.UndefOr[Boolean] = js.native
  /**
    * A list of URIs referencing variant files in Google Cloud Storage. URIs can
    * include wildcards [as described
    * here](https://cloud.google.com/storage/docs/gsutil/addlhelp/WildcardNames).
    * Note that recursive wildcards ('&#42;&#42;') are not supported.
    */
  var sourceUris: js.UndefOr[js.Array[String]] = js.native
  /** Required. The variant set to which variant data should be imported. */
  var variantSetId: js.UndefOr[String] = js.native
}

object ImportVariantsRequest {
  @scala.inline
  def apply(): ImportVariantsRequest = {
    val __obj = js.Dynamic.literal()
    __obj.asInstanceOf[ImportVariantsRequest]
  }
  @scala.inline
  implicit class ImportVariantsRequestOps[Self <: ImportVariantsRequest] (val x: Self) extends AnyVal {
    @scala.inline
    def duplicate: Self = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x)).asInstanceOf[Self]
    @scala.inline
    def combineWith[Other <: js.Any](other: Other): Self with Other = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x, other.asInstanceOf[js.Any])).asInstanceOf[Self with Other]
    @scala.inline
    def withFormat(value: String): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("format")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutFormat: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("format")(js.undefined)
        ret
    }
    @scala.inline
    def withInfoMergeConfig(value: Record[String, String]): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("infoMergeConfig")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutInfoMergeConfig: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("infoMergeConfig")(js.undefined)
        ret
    }
    @scala.inline
    def withNormalizeReferenceNames(value: Boolean): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("normalizeReferenceNames")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutNormalizeReferenceNames: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("normalizeReferenceNames")(js.undefined)
        ret
    }
    @scala.inline
    def withSourceUris(value: js.Array[String]): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("sourceUris")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutSourceUris: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("sourceUris")(js.undefined)
        ret
    }
    @scala.inline
    def withVariantSetId(value: String): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("variantSetId")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutVariantSetId: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("variantSetId")(js.undefined)
        ret
    }
  }
  
}

