package typingsSlinky.csstype.mod.DataType

import typingsSlinky.csstype.mod.Property._Border
import typingsSlinky.csstype.mod.Property._BorderBlock
import typingsSlinky.csstype.mod.Property._BorderBlockEnd
import typingsSlinky.csstype.mod.Property._BorderBlockEndWidth
import typingsSlinky.csstype.mod.Property._BorderBlockStart
import typingsSlinky.csstype.mod.Property._BorderBlockStartWidth
import typingsSlinky.csstype.mod.Property._BorderBlockWidth
import typingsSlinky.csstype.mod.Property._BorderBottom
import typingsSlinky.csstype.mod.Property._BorderBottomWidth
import typingsSlinky.csstype.mod.Property._BorderInline
import typingsSlinky.csstype.mod.Property._BorderInlineEnd
import typingsSlinky.csstype.mod.Property._BorderInlineEndWidth
import typingsSlinky.csstype.mod.Property._BorderInlineStart
import typingsSlinky.csstype.mod.Property._BorderInlineStartWidth
import typingsSlinky.csstype.mod.Property._BorderInlineWidth
import typingsSlinky.csstype.mod.Property._BorderLeft
import typingsSlinky.csstype.mod.Property._BorderLeftWidth
import typingsSlinky.csstype.mod.Property._BorderRight
import typingsSlinky.csstype.mod.Property._BorderRightWidth
import typingsSlinky.csstype.mod.Property._BorderTop
import typingsSlinky.csstype.mod.Property._BorderTopWidth
import typingsSlinky.csstype.mod.Property._BorderWidth
import typingsSlinky.csstype.mod.Property._ColumnRule
import typingsSlinky.csstype.mod.Property._ColumnRuleWidth
import typingsSlinky.csstype.mod.Property._Outline
import typingsSlinky.csstype.mod.Property._OutlineWidth
import typingsSlinky.csstype.mod.Property._WebkitBorderBefore
import typingsSlinky.csstype.mod.Property._WebkitBorderBeforeWidth
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

trait _LineWidth[TLength]
  extends _Border[TLength]
     with _BorderBlock[TLength]
     with _BorderBlockEnd[TLength]
     with _BorderBlockEndWidth[TLength]
     with _BorderBlockStart[TLength]
     with _BorderBlockStartWidth[TLength]
     with _BorderBlockWidth[TLength]
     with _BorderBottom[TLength]
     with _BorderBottomWidth[TLength]
     with _BorderInline[TLength]
     with _BorderInlineEnd[TLength]
     with _BorderInlineEndWidth[TLength]
     with _BorderInlineStart[TLength]
     with _BorderInlineStartWidth[TLength]
     with _BorderInlineWidth[TLength]
     with _BorderLeft[TLength]
     with _BorderLeftWidth[TLength]
     with _BorderRight[TLength]
     with _BorderRightWidth[TLength]
     with _BorderTop[TLength]
     with _BorderTopWidth[TLength]
     with _BorderWidth[TLength]
     with _ColumnRule[TLength]
     with _ColumnRuleWidth[TLength]
     with _Outline[TLength]
     with _OutlineWidth[TLength]
     with _WebkitBorderBefore[TLength]
     with _WebkitBorderBeforeWidth[TLength]
