package typingsSlinky.atAwsDashSdkClientDashKinesisDashBrowser.typesResourceNotFoundExceptionMod

import typingsSlinky.atAwsDashSdkClientDashKinesisDashBrowser.typesAddTagsToStreamExceptionsUnionMod.AddTagsToStreamExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashKinesisDashBrowser.typesDecreaseStreamRetentionPeriodExceptionsUnionMod.DecreaseStreamRetentionPeriodExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashKinesisDashBrowser.typesDeleteStreamExceptionsUnionMod.DeleteStreamExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashKinesisDashBrowser.typesDeregisterStreamConsumerExceptionsUnionMod.DeregisterStreamConsumerExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashKinesisDashBrowser.typesDescribeStreamConsumerExceptionsUnionMod.DescribeStreamConsumerExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashKinesisDashBrowser.typesDescribeStreamExceptionsUnionMod.DescribeStreamExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashKinesisDashBrowser.typesDescribeStreamSummaryExceptionsUnionMod.DescribeStreamSummaryExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashKinesisDashBrowser.typesDisableEnhancedMonitoringExceptionsUnionMod.DisableEnhancedMonitoringExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashKinesisDashBrowser.typesEnableEnhancedMonitoringExceptionsUnionMod.EnableEnhancedMonitoringExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashKinesisDashBrowser.typesGetRecordsExceptionsUnionMod.GetRecordsExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashKinesisDashBrowser.typesGetShardIteratorExceptionsUnionMod.GetShardIteratorExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashKinesisDashBrowser.typesIncreaseStreamRetentionPeriodExceptionsUnionMod.IncreaseStreamRetentionPeriodExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashKinesisDashBrowser.typesListShardsExceptionsUnionMod.ListShardsExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashKinesisDashBrowser.typesListStreamConsumersExceptionsUnionMod.ListStreamConsumersExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashKinesisDashBrowser.typesListTagsForStreamExceptionsUnionMod.ListTagsForStreamExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashKinesisDashBrowser.typesMergeShardsExceptionsUnionMod.MergeShardsExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashKinesisDashBrowser.typesPutRecordExceptionsUnionMod.PutRecordExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashKinesisDashBrowser.typesPutRecordsExceptionsUnionMod.PutRecordsExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashKinesisDashBrowser.typesRegisterStreamConsumerExceptionsUnionMod.RegisterStreamConsumerExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashKinesisDashBrowser.typesRemoveTagsFromStreamExceptionsUnionMod.RemoveTagsFromStreamExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashKinesisDashBrowser.typesSplitShardExceptionsUnionMod.SplitShardExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashKinesisDashBrowser.typesStartStreamEncryptionExceptionsUnionMod.StartStreamEncryptionExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashKinesisDashBrowser.typesStopStreamEncryptionExceptionsUnionMod.StopStreamEncryptionExceptionsUnion
import typingsSlinky.atAwsDashSdkClientDashKinesisDashBrowser.typesUpdateShardCountExceptionsUnionMod.UpdateShardCountExceptionsUnion
import typingsSlinky.atAwsDashSdkTypes.buildExceptionMod.ServiceException
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait ResourceNotFoundException
  extends ServiceException[_ResourceNotFoundExceptionDetails]
     with AddTagsToStreamExceptionsUnion
     with DecreaseStreamRetentionPeriodExceptionsUnion
     with DeleteStreamExceptionsUnion
     with DeregisterStreamConsumerExceptionsUnion
     with DescribeStreamConsumerExceptionsUnion
     with DescribeStreamExceptionsUnion
     with DescribeStreamSummaryExceptionsUnion
     with DisableEnhancedMonitoringExceptionsUnion
     with EnableEnhancedMonitoringExceptionsUnion
     with GetRecordsExceptionsUnion
     with GetShardIteratorExceptionsUnion
     with IncreaseStreamRetentionPeriodExceptionsUnion
     with ListShardsExceptionsUnion
     with ListStreamConsumersExceptionsUnion
     with ListTagsForStreamExceptionsUnion
     with MergeShardsExceptionsUnion
     with PutRecordExceptionsUnion
     with PutRecordsExceptionsUnion
     with RegisterStreamConsumerExceptionsUnion
     with RemoveTagsFromStreamExceptionsUnion
     with SplitShardExceptionsUnion
     with StartStreamEncryptionExceptionsUnion
     with StopStreamEncryptionExceptionsUnion
     with UpdateShardCountExceptionsUnion {
  @JSName("name")
  var name_ResourceNotFoundException: typingsSlinky.atAwsDashSdkClientDashKinesisDashBrowser.atAwsDashSdkClientDashKinesisDashBrowserStrings.ResourceNotFoundException = js.native
}

