package typingsSlinky.csstype.mod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - typingsSlinky.csstype.csstypeStrings.`-moz-initial`
  - typingsSlinky.csstype.csstypeStrings.inherit
  - typingsSlinky.csstype.csstypeStrings.initial
  - typingsSlinky.csstype.csstypeStrings.revert
  - typingsSlinky.csstype.csstypeStrings.unset
*/
trait Globals
  extends AlignContentProperty
     with AlignItemsProperty
     with AlignSelfProperty
     with AnimationDirectionProperty
     with AnimationFillModeProperty
     with AnimationIterationCountProperty
     with AnimationNameProperty
     with AnimationPlayStateProperty
     with AnimationProperty
     with AnimationTimingFunctionProperty
     with BackdropFilterProperty
     with BackgroundAttachmentProperty
     with BackgroundBlendModeProperty
     with BackgroundClipProperty
     with BackgroundColorProperty
     with BackgroundImageProperty
     with BackgroundOriginProperty
     with BackgroundPositionProperty[js.Any]
     with BackgroundPositionXProperty[js.Any]
     with BackgroundPositionYProperty[js.Any]
     with BackgroundProperty[js.Any]
     with BackgroundRepeatProperty
     with BackgroundSizeProperty[js.Any]
     with BaselineShiftProperty[js.Any]
     with BlockOverflowProperty
     with BlockSizeProperty[js.Any]
     with BorderBlockColorProperty
     with BorderBlockEndColorProperty
     with BorderBlockEndProperty[js.Any]
     with BorderBlockEndWidthProperty[js.Any]
     with BorderBlockProperty[js.Any]
     with BorderBlockStartColorProperty
     with BorderBlockStartProperty[js.Any]
     with BorderBlockStartWidthProperty[js.Any]
     with BorderBlockWidthProperty[js.Any]
     with BorderBottomColorProperty
     with BorderBottomLeftRadiusProperty[js.Any]
     with BorderBottomProperty[js.Any]
     with BorderBottomRightRadiusProperty[js.Any]
     with BorderBottomWidthProperty[js.Any]
     with BorderColorProperty
     with BorderEndEndRadiusProperty[js.Any]
     with BorderEndStartRadiusProperty[js.Any]
     with BorderImageOutsetProperty[js.Any]
     with BorderImageProperty
     with BorderImageRepeatProperty
     with BorderImageSliceProperty
     with BorderImageSourceProperty
     with BorderImageWidthProperty[js.Any]
     with BorderInlineColorProperty
     with BorderInlineEndColorProperty
     with BorderInlineEndProperty[js.Any]
     with BorderInlineEndWidthProperty[js.Any]
     with BorderInlineProperty[js.Any]
     with BorderInlineStartColorProperty
     with BorderInlineStartProperty[js.Any]
     with BorderInlineStartWidthProperty[js.Any]
     with BorderInlineWidthProperty[js.Any]
     with BorderLeftColorProperty
     with BorderLeftProperty[js.Any]
     with BorderLeftWidthProperty[js.Any]
     with BorderProperty[js.Any]
     with BorderRadiusProperty[js.Any]
     with BorderRightColorProperty
     with BorderRightProperty[js.Any]
     with BorderRightWidthProperty[js.Any]
     with BorderSpacingProperty[js.Any]
     with BorderStartEndRadiusProperty[js.Any]
     with BorderStartStartRadiusProperty[js.Any]
     with BorderStyleProperty
     with BorderTopColorProperty
     with BorderTopLeftRadiusProperty[js.Any]
     with BorderTopProperty[js.Any]
     with BorderTopRightRadiusProperty[js.Any]
     with BorderTopWidthProperty[js.Any]
     with BorderWidthProperty[js.Any]
     with BottomProperty[js.Any]
     with BoxShadowProperty
     with CaretColorProperty
     with ClipPathProperty
     with ClipProperty
     with ColorProperty
     with ColumnCountProperty
     with ColumnGapProperty[js.Any]
     with ColumnRuleColorProperty
     with ColumnRuleProperty[js.Any]
     with ColumnRuleStyleProperty
     with ColumnRuleWidthProperty[js.Any]
     with ColumnWidthProperty[js.Any]
     with ColumnsProperty[js.Any]
     with ContainProperty
     with ContentProperty
     with CounterIncrementProperty
     with CounterResetProperty
     with CounterSetProperty
     with CursorProperty
     with DisplayProperty
     with FillProperty
     with FilterProperty
     with FlexBasisProperty[js.Any]
     with FlexFlowProperty
     with FlexProperty[js.Any]
     with FloodColorProperty
     with FontFamilyProperty
     with FontFeatureSettingsProperty
     with FontLanguageOverrideProperty
     with FontProperty
     with FontSizeAdjustProperty
     with FontSizeProperty[js.Any]
     with FontStretchProperty
     with FontStyleProperty
     with FontSynthesisProperty
     with FontVariantAlternatesProperty
     with FontVariantEastAsianProperty
     with FontVariantLigaturesProperty
     with FontVariantNumericProperty
     with FontVariantProperty
     with FontVariationSettingsProperty
     with FontWeightProperty
     with GapProperty[js.Any]
     with GlobalsNumber
     with GlobalsString
     with GlyphOrientationVerticalProperty
     with GridAreaProperty
     with GridAutoColumnsProperty[js.Any]
     with GridAutoFlowProperty
     with GridAutoRowsProperty[js.Any]
     with GridColumnEndProperty
     with GridColumnGapProperty[js.Any]
     with GridColumnProperty
     with GridColumnStartProperty
     with GridGapProperty[js.Any]
     with GridProperty
     with GridRowEndProperty
     with GridRowGapProperty[js.Any]
     with GridRowProperty
     with GridRowStartProperty
     with GridTemplateAreasProperty
     with GridTemplateColumnsProperty[js.Any]
     with GridTemplateProperty
     with GridTemplateRowsProperty[js.Any]
     with HangingPunctuationProperty
     with HeightProperty[js.Any]
     with ImageOrientationProperty
     with ImageResolutionProperty
     with InitialLetterProperty
     with InlineSizeProperty[js.Any]
     with InsetBlockEndProperty[js.Any]
     with InsetBlockProperty[js.Any]
     with InsetBlockStartProperty[js.Any]
     with InsetInlineEndProperty[js.Any]
     with InsetInlineProperty[js.Any]
     with InsetInlineStartProperty[js.Any]
     with InsetProperty[js.Any]
     with JustifyContentProperty
     with JustifyItemsProperty
     with JustifySelfProperty
     with LeftProperty[js.Any]
     with LetterSpacingProperty[js.Any]
     with LightingColorProperty
     with LineClampProperty
     with LineHeightProperty[js.Any]
     with LineHeightStepProperty[js.Any]
     with ListStyleImageProperty
     with ListStyleProperty
     with ListStyleTypeProperty
     with MarginBlockEndProperty[js.Any]
     with MarginBlockProperty[js.Any]
     with MarginBlockStartProperty[js.Any]
     with MarginBottomProperty[js.Any]
     with MarginInlineEndProperty[js.Any]
     with MarginInlineProperty[js.Any]
     with MarginInlineStartProperty[js.Any]
     with MarginLeftProperty[js.Any]
     with MarginProperty[js.Any]
     with MarginRightProperty[js.Any]
     with MarginTopProperty[js.Any]
     with MarkerEndProperty
     with MarkerMidProperty
     with MarkerProperty
     with MarkerStartProperty
     with MaskBorderOutsetProperty[js.Any]
     with MaskBorderProperty
     with MaskBorderRepeatProperty
     with MaskBorderSliceProperty
     with MaskBorderSourceProperty
     with MaskBorderWidthProperty[js.Any]
     with MaskClipProperty
     with MaskCompositeProperty
     with MaskImageProperty
     with MaskModeProperty
     with MaskOriginProperty
     with MaskPositionProperty[js.Any]
     with MaskProperty[js.Any]
     with MaskRepeatProperty
     with MaskSizeProperty[js.Any]
     with MaxBlockSizeProperty[js.Any]
     with MaxHeightProperty[js.Any]
     with MaxInlineSizeProperty[js.Any]
     with MaxLinesProperty
     with MaxWidthProperty[js.Any]
     with MinBlockSizeProperty[js.Any]
     with MinHeightProperty[js.Any]
     with MinInlineSizeProperty[js.Any]
     with MinWidthProperty[js.Any]
     with MozBindingProperty
     with MozBorderBottomColorsProperty
     with MozBorderLeftColorsProperty
     with MozBorderRightColorsProperty
     with MozBorderTopColorsProperty
     with MozContextPropertiesProperty
     with MozImageRegionProperty
     with MozOutlineRadiusBottomleftProperty[js.Any]
     with MozOutlineRadiusBottomrightProperty[js.Any]
     with MozOutlineRadiusProperty[js.Any]
     with MozOutlineRadiusTopleftProperty[js.Any]
     with MozOutlineRadiusToprightProperty[js.Any]
     with MsContentZoomSnapProperty
     with MsFlowFromProperty
     with MsFlowIntoProperty
     with MsHyphenateLimitCharsProperty
     with MsHyphenateLimitLinesProperty
     with MsHyphenateLimitZoneProperty[js.Any]
     with MsScrollLimitXMaxProperty[js.Any]
     with MsScrollLimitXMinProperty[js.Any]
     with MsScrollLimitYMaxProperty[js.Any]
     with MsScrollLimitYMinProperty[js.Any]
     with MsScrollbar3dlightColorProperty
     with MsScrollbarArrowColorProperty
     with MsScrollbarBaseColorProperty
     with MsScrollbarDarkshadowColorProperty
     with MsScrollbarFaceColorProperty
     with MsScrollbarHighlightColorProperty
     with MsScrollbarShadowColorProperty
     with MsScrollbarTrackColorProperty
     with MsWrapMarginProperty[js.Any]
     with ObjectPositionProperty[js.Any]
     with OffsetAnchorProperty[js.Any]
     with OffsetDistanceProperty[js.Any]
     with OffsetPathProperty
     with OffsetPositionProperty[js.Any]
     with OffsetProperty[js.Any]
     with OffsetRotateProperty
     with OutlineColorProperty
     with OutlineOffsetProperty[js.Any]
     with OutlineProperty[js.Any]
     with OutlineStyleProperty
     with OutlineWidthProperty[js.Any]
     with OverflowProperty
     with OverscrollBehaviorProperty
     with PaddingBlockEndProperty[js.Any]
     with PaddingBlockProperty[js.Any]
     with PaddingBlockStartProperty[js.Any]
     with PaddingBottomProperty[js.Any]
     with PaddingInlineEndProperty[js.Any]
     with PaddingInlineProperty[js.Any]
     with PaddingInlineStartProperty[js.Any]
     with PaddingLeftProperty[js.Any]
     with PaddingProperty[js.Any]
     with PaddingRightProperty[js.Any]
     with PaddingTopProperty[js.Any]
     with PaintOrderProperty
     with PerspectiveOriginProperty[js.Any]
     with PerspectiveProperty[js.Any]
     with PlaceContentProperty
     with PlaceItemsProperty
     with PlaceSelfProperty
     with QuotesProperty
     with RightProperty[js.Any]
     with RotateProperty
     with RowGapProperty[js.Any]
     with ScaleProperty
     with ScrollMarginBlockEndProperty[js.Any]
     with ScrollMarginBlockProperty[js.Any]
     with ScrollMarginBlockStartProperty[js.Any]
     with ScrollMarginBottomProperty[js.Any]
     with ScrollMarginInlineEndProperty[js.Any]
     with ScrollMarginInlineProperty[js.Any]
     with ScrollMarginInlineStartProperty[js.Any]
     with ScrollMarginLeftProperty[js.Any]
     with ScrollMarginProperty[js.Any]
     with ScrollMarginRightProperty[js.Any]
     with ScrollMarginTopProperty[js.Any]
     with ScrollPaddingBlockEndProperty[js.Any]
     with ScrollPaddingBlockProperty[js.Any]
     with ScrollPaddingBlockStartProperty[js.Any]
     with ScrollPaddingBottomProperty[js.Any]
     with ScrollPaddingInlineEndProperty[js.Any]
     with ScrollPaddingInlineProperty[js.Any]
     with ScrollPaddingInlineStartProperty[js.Any]
     with ScrollPaddingLeftProperty[js.Any]
     with ScrollPaddingProperty[js.Any]
     with ScrollPaddingRightProperty[js.Any]
     with ScrollPaddingTopProperty[js.Any]
     with ScrollSnapAlignProperty
     with ScrollSnapCoordinateProperty[js.Any]
     with ScrollSnapDestinationProperty[js.Any]
     with ScrollSnapPointsXProperty
     with ScrollSnapPointsYProperty
     with ScrollSnapTypeProperty
     with ScrollbarColorProperty
     with ShapeMarginProperty[js.Any]
     with ShapeOutsideProperty
     with StopColorProperty
     with StrokeDasharrayProperty[js.Any]
     with StrokeDashoffsetProperty[js.Any]
     with StrokeProperty
     with StrokeWidthProperty[js.Any]
     with TabSizeProperty[js.Any]
     with TextCombineUprightProperty
     with TextDecorationColorProperty
     with TextDecorationLineProperty
     with TextDecorationProperty
     with TextDecorationSkipProperty
     with TextEmphasisColorProperty
     with TextEmphasisProperty
     with TextEmphasisStyleProperty
     with TextIndentProperty[js.Any]
     with TextOverflowProperty
     with TextShadowProperty
     with TextSizeAdjustProperty
     with TextUnderlinePositionProperty
     with TopProperty[js.Any]
     with TouchActionProperty
     with TransformOriginProperty[js.Any]
     with TransformProperty
     with TransitionProperty
     with TransitionPropertyProperty
     with TransitionTimingFunctionProperty
     with TranslateProperty[js.Any]
     with VerticalAlignProperty[js.Any]
     with WebkitBorderBeforeColorProperty
     with WebkitBorderBeforeProperty[js.Any]
     with WebkitBorderBeforeStyleProperty
     with WebkitBorderBeforeWidthProperty[js.Any]
     with WebkitBoxReflectProperty[js.Any]
     with WebkitLineClampProperty
     with WebkitMaskAttachmentProperty
     with WebkitMaskClipProperty
     with WebkitMaskCompositeProperty
     with WebkitMaskImageProperty
     with WebkitMaskOriginProperty
     with WebkitMaskPositionProperty[js.Any]
     with WebkitMaskPositionXProperty[js.Any]
     with WebkitMaskPositionYProperty[js.Any]
     with WebkitMaskProperty[js.Any]
     with WebkitMaskRepeatProperty
     with WebkitMaskSizeProperty[js.Any]
     with WebkitTapHighlightColorProperty
     with WebkitTextFillColorProperty
     with WebkitTextStrokeColorProperty
     with WebkitTextStrokeProperty[js.Any]
     with WebkitTextStrokeWidthProperty[js.Any]
     with WidthProperty[js.Any]
     with WillChangeProperty
     with WordSpacingProperty[js.Any]
     with ZIndexProperty
     with ZoomProperty

object Globals {
  @scala.inline
  def `-moz-initial`: typingsSlinky.csstype.csstypeStrings.`-moz-initial` = "-moz-initial".asInstanceOf[typingsSlinky.csstype.csstypeStrings.`-moz-initial`]
  @scala.inline
  def inherit: typingsSlinky.csstype.csstypeStrings.inherit = "inherit".asInstanceOf[typingsSlinky.csstype.csstypeStrings.inherit]
  @scala.inline
  def initial: typingsSlinky.csstype.csstypeStrings.initial = "initial".asInstanceOf[typingsSlinky.csstype.csstypeStrings.initial]
  @scala.inline
  def revert: typingsSlinky.csstype.csstypeStrings.revert = "revert".asInstanceOf[typingsSlinky.csstype.csstypeStrings.revert]
  @scala.inline
  def unset: typingsSlinky.csstype.csstypeStrings.unset = "unset".asInstanceOf[typingsSlinky.csstype.csstypeStrings.unset]
}

