package typingsSlinky.csstype.mod

import typingsSlinky.csstype.mod.Property._AlignContent
import typingsSlinky.csstype.mod.Property._AlignItems
import typingsSlinky.csstype.mod.Property._AlignSelf
import typingsSlinky.csstype.mod.Property._Animation
import typingsSlinky.csstype.mod.Property._AnimationDirection
import typingsSlinky.csstype.mod.Property._AnimationFillMode
import typingsSlinky.csstype.mod.Property._AnimationIterationCount
import typingsSlinky.csstype.mod.Property._AnimationName
import typingsSlinky.csstype.mod.Property._AnimationPlayState
import typingsSlinky.csstype.mod.Property._AnimationTimingFunction
import typingsSlinky.csstype.mod.Property._AspectRatio
import typingsSlinky.csstype.mod.Property._BackdropFilter
import typingsSlinky.csstype.mod.Property._Background
import typingsSlinky.csstype.mod.Property._BackgroundAttachment
import typingsSlinky.csstype.mod.Property._BackgroundBlendMode
import typingsSlinky.csstype.mod.Property._BackgroundClip
import typingsSlinky.csstype.mod.Property._BackgroundColor
import typingsSlinky.csstype.mod.Property._BackgroundImage
import typingsSlinky.csstype.mod.Property._BackgroundOrigin
import typingsSlinky.csstype.mod.Property._BackgroundPosition
import typingsSlinky.csstype.mod.Property._BackgroundPositionX
import typingsSlinky.csstype.mod.Property._BackgroundPositionY
import typingsSlinky.csstype.mod.Property._BackgroundRepeat
import typingsSlinky.csstype.mod.Property._BackgroundSize
import typingsSlinky.csstype.mod.Property._BaselineShift
import typingsSlinky.csstype.mod.Property._BlockOverflow
import typingsSlinky.csstype.mod.Property._BlockSize
import typingsSlinky.csstype.mod.Property._Border
import typingsSlinky.csstype.mod.Property._BorderBlock
import typingsSlinky.csstype.mod.Property._BorderBlockColor
import typingsSlinky.csstype.mod.Property._BorderBlockEnd
import typingsSlinky.csstype.mod.Property._BorderBlockEndColor
import typingsSlinky.csstype.mod.Property._BorderBlockEndWidth
import typingsSlinky.csstype.mod.Property._BorderBlockStart
import typingsSlinky.csstype.mod.Property._BorderBlockStartColor
import typingsSlinky.csstype.mod.Property._BorderBlockStartWidth
import typingsSlinky.csstype.mod.Property._BorderBlockWidth
import typingsSlinky.csstype.mod.Property._BorderBottom
import typingsSlinky.csstype.mod.Property._BorderBottomColor
import typingsSlinky.csstype.mod.Property._BorderBottomWidth
import typingsSlinky.csstype.mod.Property._BorderColor
import typingsSlinky.csstype.mod.Property._BorderImage
import typingsSlinky.csstype.mod.Property._BorderImageRepeat
import typingsSlinky.csstype.mod.Property._BorderImageSource
import typingsSlinky.csstype.mod.Property._BorderImageWidth
import typingsSlinky.csstype.mod.Property._BorderInline
import typingsSlinky.csstype.mod.Property._BorderInlineColor
import typingsSlinky.csstype.mod.Property._BorderInlineEnd
import typingsSlinky.csstype.mod.Property._BorderInlineEndColor
import typingsSlinky.csstype.mod.Property._BorderInlineEndWidth
import typingsSlinky.csstype.mod.Property._BorderInlineStart
import typingsSlinky.csstype.mod.Property._BorderInlineStartColor
import typingsSlinky.csstype.mod.Property._BorderInlineStartWidth
import typingsSlinky.csstype.mod.Property._BorderInlineWidth
import typingsSlinky.csstype.mod.Property._BorderLeft
import typingsSlinky.csstype.mod.Property._BorderLeftColor
import typingsSlinky.csstype.mod.Property._BorderLeftWidth
import typingsSlinky.csstype.mod.Property._BorderRight
import typingsSlinky.csstype.mod.Property._BorderRightColor
import typingsSlinky.csstype.mod.Property._BorderRightWidth
import typingsSlinky.csstype.mod.Property._BorderStyle
import typingsSlinky.csstype.mod.Property._BorderTop
import typingsSlinky.csstype.mod.Property._BorderTopColor
import typingsSlinky.csstype.mod.Property._BorderTopWidth
import typingsSlinky.csstype.mod.Property._BorderWidth
import typingsSlinky.csstype.mod.Property._Bottom
import typingsSlinky.csstype.mod.Property._BoxShadow
import typingsSlinky.csstype.mod.Property._CaretColor
import typingsSlinky.csstype.mod.Property._Clip
import typingsSlinky.csstype.mod.Property._ClipPath
import typingsSlinky.csstype.mod.Property._Color
import typingsSlinky.csstype.mod.Property._ColumnCount
import typingsSlinky.csstype.mod.Property._ColumnGap
import typingsSlinky.csstype.mod.Property._ColumnRule
import typingsSlinky.csstype.mod.Property._ColumnRuleColor
import typingsSlinky.csstype.mod.Property._ColumnRuleStyle
import typingsSlinky.csstype.mod.Property._ColumnRuleWidth
import typingsSlinky.csstype.mod.Property._ColumnWidth
import typingsSlinky.csstype.mod.Property._Columns
import typingsSlinky.csstype.mod.Property._Contain
import typingsSlinky.csstype.mod.Property._Content
import typingsSlinky.csstype.mod.Property._CounterIncrement
import typingsSlinky.csstype.mod.Property._CounterReset
import typingsSlinky.csstype.mod.Property._CounterSet
import typingsSlinky.csstype.mod.Property._Cursor
import typingsSlinky.csstype.mod.Property._Display
import typingsSlinky.csstype.mod.Property._Fill
import typingsSlinky.csstype.mod.Property._Filter
import typingsSlinky.csstype.mod.Property._Flex
import typingsSlinky.csstype.mod.Property._FlexBasis
import typingsSlinky.csstype.mod.Property._FlexFlow
import typingsSlinky.csstype.mod.Property._FloodColor
import typingsSlinky.csstype.mod.Property._Font
import typingsSlinky.csstype.mod.Property._FontFamily
import typingsSlinky.csstype.mod.Property._FontFeatureSettings
import typingsSlinky.csstype.mod.Property._FontLanguageOverride
import typingsSlinky.csstype.mod.Property._FontSize
import typingsSlinky.csstype.mod.Property._FontSizeAdjust
import typingsSlinky.csstype.mod.Property._FontStretch
import typingsSlinky.csstype.mod.Property._FontStyle
import typingsSlinky.csstype.mod.Property._FontSynthesis
import typingsSlinky.csstype.mod.Property._FontVariant
import typingsSlinky.csstype.mod.Property._FontVariantAlternates
import typingsSlinky.csstype.mod.Property._FontVariantEastAsian
import typingsSlinky.csstype.mod.Property._FontVariantLigatures
import typingsSlinky.csstype.mod.Property._FontVariantNumeric
import typingsSlinky.csstype.mod.Property._FontVariationSettings
import typingsSlinky.csstype.mod.Property._FontWeight
import typingsSlinky.csstype.mod.Property._Gap
import typingsSlinky.csstype.mod.Property._GlyphOrientationVertical
import typingsSlinky.csstype.mod.Property._Grid
import typingsSlinky.csstype.mod.Property._GridAutoColumns
import typingsSlinky.csstype.mod.Property._GridAutoFlow
import typingsSlinky.csstype.mod.Property._GridAutoRows
import typingsSlinky.csstype.mod.Property._GridTemplate
import typingsSlinky.csstype.mod.Property._GridTemplateAreas
import typingsSlinky.csstype.mod.Property._GridTemplateColumns
import typingsSlinky.csstype.mod.Property._GridTemplateRows
import typingsSlinky.csstype.mod.Property._HangingPunctuation
import typingsSlinky.csstype.mod.Property._Height
import typingsSlinky.csstype.mod.Property._ImageOrientation
import typingsSlinky.csstype.mod.Property._ImageResolution
import typingsSlinky.csstype.mod.Property._InitialLetter
import typingsSlinky.csstype.mod.Property._InlineSize
import typingsSlinky.csstype.mod.Property._Inset
import typingsSlinky.csstype.mod.Property._InsetBlock
import typingsSlinky.csstype.mod.Property._InsetBlockEnd
import typingsSlinky.csstype.mod.Property._InsetBlockStart
import typingsSlinky.csstype.mod.Property._InsetInline
import typingsSlinky.csstype.mod.Property._InsetInlineEnd
import typingsSlinky.csstype.mod.Property._InsetInlineStart
import typingsSlinky.csstype.mod.Property._JustifyContent
import typingsSlinky.csstype.mod.Property._JustifyItems
import typingsSlinky.csstype.mod.Property._JustifySelf
import typingsSlinky.csstype.mod.Property._Left
import typingsSlinky.csstype.mod.Property._LetterSpacing
import typingsSlinky.csstype.mod.Property._LightingColor
import typingsSlinky.csstype.mod.Property._LineClamp
import typingsSlinky.csstype.mod.Property._LineHeight
import typingsSlinky.csstype.mod.Property._ListStyle
import typingsSlinky.csstype.mod.Property._ListStyleImage
import typingsSlinky.csstype.mod.Property._ListStyleType
import typingsSlinky.csstype.mod.Property._Margin
import typingsSlinky.csstype.mod.Property._MarginBlock
import typingsSlinky.csstype.mod.Property._MarginBlockEnd
import typingsSlinky.csstype.mod.Property._MarginBlockStart
import typingsSlinky.csstype.mod.Property._MarginBottom
import typingsSlinky.csstype.mod.Property._MarginInline
import typingsSlinky.csstype.mod.Property._MarginInlineEnd
import typingsSlinky.csstype.mod.Property._MarginInlineStart
import typingsSlinky.csstype.mod.Property._MarginLeft
import typingsSlinky.csstype.mod.Property._MarginRight
import typingsSlinky.csstype.mod.Property._MarginTop
import typingsSlinky.csstype.mod.Property._Marker
import typingsSlinky.csstype.mod.Property._MarkerEnd
import typingsSlinky.csstype.mod.Property._MarkerMid
import typingsSlinky.csstype.mod.Property._MarkerStart
import typingsSlinky.csstype.mod.Property._Mask
import typingsSlinky.csstype.mod.Property._MaskBorder
import typingsSlinky.csstype.mod.Property._MaskBorderRepeat
import typingsSlinky.csstype.mod.Property._MaskBorderSource
import typingsSlinky.csstype.mod.Property._MaskBorderWidth
import typingsSlinky.csstype.mod.Property._MaskClip
import typingsSlinky.csstype.mod.Property._MaskComposite
import typingsSlinky.csstype.mod.Property._MaskImage
import typingsSlinky.csstype.mod.Property._MaskMode
import typingsSlinky.csstype.mod.Property._MaskOrigin
import typingsSlinky.csstype.mod.Property._MaskPosition
import typingsSlinky.csstype.mod.Property._MaskRepeat
import typingsSlinky.csstype.mod.Property._MaskSize
import typingsSlinky.csstype.mod.Property._MaxBlockSize
import typingsSlinky.csstype.mod.Property._MaxHeight
import typingsSlinky.csstype.mod.Property._MaxInlineSize
import typingsSlinky.csstype.mod.Property._MaxLines
import typingsSlinky.csstype.mod.Property._MaxWidth
import typingsSlinky.csstype.mod.Property._MinBlockSize
import typingsSlinky.csstype.mod.Property._MinHeight
import typingsSlinky.csstype.mod.Property._MinInlineSize
import typingsSlinky.csstype.mod.Property._MinWidth
import typingsSlinky.csstype.mod.Property._MozBinding
import typingsSlinky.csstype.mod.Property._MozBorderBottomColors
import typingsSlinky.csstype.mod.Property._MozBorderLeftColors
import typingsSlinky.csstype.mod.Property._MozBorderRightColors
import typingsSlinky.csstype.mod.Property._MozBorderTopColors
import typingsSlinky.csstype.mod.Property._MozContextProperties
import typingsSlinky.csstype.mod.Property._MozImageRegion
import typingsSlinky.csstype.mod.Property._MsContentZoomSnap
import typingsSlinky.csstype.mod.Property._MsFlowFrom
import typingsSlinky.csstype.mod.Property._MsFlowInto
import typingsSlinky.csstype.mod.Property._MsHyphenateLimitChars
import typingsSlinky.csstype.mod.Property._MsHyphenateLimitLines
import typingsSlinky.csstype.mod.Property._MsScrollLimitXMax
import typingsSlinky.csstype.mod.Property._MsScrollLimitYMax
import typingsSlinky.csstype.mod.Property._MsScrollbar3dlightColor
import typingsSlinky.csstype.mod.Property._MsScrollbarArrowColor
import typingsSlinky.csstype.mod.Property._MsScrollbarBaseColor
import typingsSlinky.csstype.mod.Property._MsScrollbarDarkshadowColor
import typingsSlinky.csstype.mod.Property._MsScrollbarFaceColor
import typingsSlinky.csstype.mod.Property._MsScrollbarHighlightColor
import typingsSlinky.csstype.mod.Property._MsScrollbarShadowColor
import typingsSlinky.csstype.mod.Property._MsScrollbarTrackColor
import typingsSlinky.csstype.mod.Property._ObjectPosition
import typingsSlinky.csstype.mod.Property._Offset
import typingsSlinky.csstype.mod.Property._OffsetAnchor
import typingsSlinky.csstype.mod.Property._OffsetPath
import typingsSlinky.csstype.mod.Property._OffsetRotate
import typingsSlinky.csstype.mod.Property._Outline
import typingsSlinky.csstype.mod.Property._OutlineColor
import typingsSlinky.csstype.mod.Property._OutlineStyle
import typingsSlinky.csstype.mod.Property._OutlineWidth
import typingsSlinky.csstype.mod.Property._Overflow
import typingsSlinky.csstype.mod.Property._OverscrollBehavior
import typingsSlinky.csstype.mod.Property._PaintOrder
import typingsSlinky.csstype.mod.Property._Perspective
import typingsSlinky.csstype.mod.Property._PerspectiveOrigin
import typingsSlinky.csstype.mod.Property._PlaceContent
import typingsSlinky.csstype.mod.Property._PlaceItems
import typingsSlinky.csstype.mod.Property._PlaceSelf
import typingsSlinky.csstype.mod.Property._Quotes
import typingsSlinky.csstype.mod.Property._Right
import typingsSlinky.csstype.mod.Property._Rotate
import typingsSlinky.csstype.mod.Property._RowGap
import typingsSlinky.csstype.mod.Property._Scale
import typingsSlinky.csstype.mod.Property._ScrollPadding
import typingsSlinky.csstype.mod.Property._ScrollPaddingBlock
import typingsSlinky.csstype.mod.Property._ScrollPaddingBlockEnd
import typingsSlinky.csstype.mod.Property._ScrollPaddingBlockStart
import typingsSlinky.csstype.mod.Property._ScrollPaddingBottom
import typingsSlinky.csstype.mod.Property._ScrollPaddingInline
import typingsSlinky.csstype.mod.Property._ScrollPaddingInlineEnd
import typingsSlinky.csstype.mod.Property._ScrollPaddingInlineStart
import typingsSlinky.csstype.mod.Property._ScrollPaddingLeft
import typingsSlinky.csstype.mod.Property._ScrollPaddingRight
import typingsSlinky.csstype.mod.Property._ScrollPaddingTop
import typingsSlinky.csstype.mod.Property._ScrollSnapAlign
import typingsSlinky.csstype.mod.Property._ScrollSnapCoordinate
import typingsSlinky.csstype.mod.Property._ScrollSnapDestination
import typingsSlinky.csstype.mod.Property._ScrollSnapPointsX
import typingsSlinky.csstype.mod.Property._ScrollSnapPointsY
import typingsSlinky.csstype.mod.Property._ScrollSnapType
import typingsSlinky.csstype.mod.Property._ScrollbarColor
import typingsSlinky.csstype.mod.Property._ShapeOutside
import typingsSlinky.csstype.mod.Property._StopColor
import typingsSlinky.csstype.mod.Property._Stroke
import typingsSlinky.csstype.mod.Property._StrokeDasharray
import typingsSlinky.csstype.mod.Property._TextCombineUpright
import typingsSlinky.csstype.mod.Property._TextDecoration
import typingsSlinky.csstype.mod.Property._TextDecorationColor
import typingsSlinky.csstype.mod.Property._TextDecorationLine
import typingsSlinky.csstype.mod.Property._TextDecorationSkip
import typingsSlinky.csstype.mod.Property._TextDecorationThickness
import typingsSlinky.csstype.mod.Property._TextEmphasis
import typingsSlinky.csstype.mod.Property._TextEmphasisColor
import typingsSlinky.csstype.mod.Property._TextEmphasisStyle
import typingsSlinky.csstype.mod.Property._TextOverflow
import typingsSlinky.csstype.mod.Property._TextShadow
import typingsSlinky.csstype.mod.Property._TextSizeAdjust
import typingsSlinky.csstype.mod.Property._TextUnderlineOffset
import typingsSlinky.csstype.mod.Property._TextUnderlinePosition
import typingsSlinky.csstype.mod.Property._Top
import typingsSlinky.csstype.mod.Property._TouchAction
import typingsSlinky.csstype.mod.Property._Transform
import typingsSlinky.csstype.mod.Property._TransformOrigin
import typingsSlinky.csstype.mod.Property._Transition
import typingsSlinky.csstype.mod.Property._TransitionProperty
import typingsSlinky.csstype.mod.Property._TransitionTimingFunction
import typingsSlinky.csstype.mod.Property._Translate
import typingsSlinky.csstype.mod.Property._VerticalAlign
import typingsSlinky.csstype.mod.Property._WebkitBorderBefore
import typingsSlinky.csstype.mod.Property._WebkitBorderBeforeColor
import typingsSlinky.csstype.mod.Property._WebkitBorderBeforeStyle
import typingsSlinky.csstype.mod.Property._WebkitBorderBeforeWidth
import typingsSlinky.csstype.mod.Property._WebkitBoxReflect
import typingsSlinky.csstype.mod.Property._WebkitLineClamp
import typingsSlinky.csstype.mod.Property._WebkitMask
import typingsSlinky.csstype.mod.Property._WebkitMaskAttachment
import typingsSlinky.csstype.mod.Property._WebkitMaskClip
import typingsSlinky.csstype.mod.Property._WebkitMaskComposite
import typingsSlinky.csstype.mod.Property._WebkitMaskImage
import typingsSlinky.csstype.mod.Property._WebkitMaskOrigin
import typingsSlinky.csstype.mod.Property._WebkitMaskPosition
import typingsSlinky.csstype.mod.Property._WebkitMaskPositionX
import typingsSlinky.csstype.mod.Property._WebkitMaskPositionY
import typingsSlinky.csstype.mod.Property._WebkitMaskRepeat
import typingsSlinky.csstype.mod.Property._WebkitMaskSize
import typingsSlinky.csstype.mod.Property._WebkitTapHighlightColor
import typingsSlinky.csstype.mod.Property._WebkitTextFillColor
import typingsSlinky.csstype.mod.Property._WebkitTextStroke
import typingsSlinky.csstype.mod.Property._WebkitTextStrokeColor
import typingsSlinky.csstype.mod.Property._Width
import typingsSlinky.csstype.mod.Property._WillChange
import typingsSlinky.csstype.mod.Property._WordSpacing
import typingsSlinky.csstype.mod.Property._ZIndex
import typingsSlinky.csstype.mod.Property._Zoom
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

/* Rewritten from type alias, can be one of: 
  - typingsSlinky.csstype.csstypeStrings.`-moz-initial`
  - typingsSlinky.csstype.csstypeStrings.inherit
  - typingsSlinky.csstype.csstypeStrings.initial
  - typingsSlinky.csstype.csstypeStrings.revert
  - typingsSlinky.csstype.csstypeStrings.unset
*/
trait Globals
  extends _AlignContent
     with _AlignItems
     with _AlignSelf
     with _Animation[js.Any]
     with _AnimationDirection
     with _AnimationFillMode
     with _AnimationIterationCount
     with _AnimationName
     with _AnimationPlayState
     with _AnimationTimingFunction
     with _AspectRatio
     with _BackdropFilter
     with _Background[js.Any]
     with _BackgroundAttachment
     with _BackgroundBlendMode
     with _BackgroundClip
     with _BackgroundColor
     with _BackgroundImage
     with _BackgroundOrigin
     with _BackgroundPosition[js.Any]
     with _BackgroundPositionX[js.Any]
     with _BackgroundPositionY[js.Any]
     with _BackgroundRepeat
     with _BackgroundSize[js.Any]
     with _BaselineShift[js.Any]
     with _BlockOverflow
     with _BlockSize[js.Any]
     with _Border[js.Any]
     with _BorderBlock[js.Any]
     with _BorderBlockColor
     with _BorderBlockEnd[js.Any]
     with _BorderBlockEndColor
     with _BorderBlockEndWidth[js.Any]
     with _BorderBlockStart[js.Any]
     with _BorderBlockStartColor
     with _BorderBlockStartWidth[js.Any]
     with _BorderBlockWidth[js.Any]
     with _BorderBottom[js.Any]
     with _BorderBottomColor
     with _BorderBottomWidth[js.Any]
     with _BorderColor
     with _BorderImage
     with _BorderImageRepeat
     with _BorderImageSource
     with _BorderImageWidth[js.Any]
     with _BorderInline[js.Any]
     with _BorderInlineColor
     with _BorderInlineEnd[js.Any]
     with _BorderInlineEndColor
     with _BorderInlineEndWidth[js.Any]
     with _BorderInlineStart[js.Any]
     with _BorderInlineStartColor
     with _BorderInlineStartWidth[js.Any]
     with _BorderInlineWidth[js.Any]
     with _BorderLeft[js.Any]
     with _BorderLeftColor
     with _BorderLeftWidth[js.Any]
     with _BorderRight[js.Any]
     with _BorderRightColor
     with _BorderRightWidth[js.Any]
     with _BorderStyle
     with _BorderTop[js.Any]
     with _BorderTopColor
     with _BorderTopWidth[js.Any]
     with _BorderWidth[js.Any]
     with _Bottom[js.Any]
     with _BoxShadow
     with _CaretColor
     with _Clip
     with _ClipPath
     with _Color
     with _ColumnCount
     with _ColumnGap[js.Any]
     with _ColumnRule[js.Any]
     with _ColumnRuleColor
     with _ColumnRuleStyle
     with _ColumnRuleWidth[js.Any]
     with _ColumnWidth[js.Any]
     with _Columns[js.Any]
     with _Contain
     with _Content
     with _CounterIncrement
     with _CounterReset
     with _CounterSet
     with _Cursor
     with _Display
     with _Fill
     with _Filter
     with _Flex[js.Any]
     with _FlexBasis[js.Any]
     with _FlexFlow
     with _FloodColor
     with _Font
     with _FontFamily
     with _FontFeatureSettings
     with _FontLanguageOverride
     with _FontSize[js.Any]
     with _FontSizeAdjust
     with _FontStretch
     with _FontStyle
     with _FontSynthesis
     with _FontVariant
     with _FontVariantAlternates
     with _FontVariantEastAsian
     with _FontVariantLigatures
     with _FontVariantNumeric
     with _FontVariationSettings
     with _FontWeight
     with _Gap[js.Any]
     with _GlyphOrientationVertical
     with _Grid
     with _GridAutoColumns[js.Any]
     with _GridAutoFlow
     with _GridAutoRows[js.Any]
     with _GridTemplate
     with _GridTemplateAreas
     with _GridTemplateColumns[js.Any]
     with _GridTemplateRows[js.Any]
     with _HangingPunctuation
     with _Height[js.Any]
     with _ImageOrientation
     with _ImageResolution
     with _InitialLetter
     with _InlineSize[js.Any]
     with _Inset[js.Any]
     with _InsetBlock[js.Any]
     with _InsetBlockEnd[js.Any]
     with _InsetBlockStart[js.Any]
     with _InsetInline[js.Any]
     with _InsetInlineEnd[js.Any]
     with _InsetInlineStart[js.Any]
     with _JustifyContent
     with _JustifyItems
     with _JustifySelf
     with _Left[js.Any]
     with _LetterSpacing[js.Any]
     with _LightingColor
     with _LineClamp
     with _LineHeight[js.Any]
     with _ListStyle
     with _ListStyleImage
     with _ListStyleType
     with _Margin[js.Any]
     with _MarginBlock[js.Any]
     with _MarginBlockEnd[js.Any]
     with _MarginBlockStart[js.Any]
     with _MarginBottom[js.Any]
     with _MarginInline[js.Any]
     with _MarginInlineEnd[js.Any]
     with _MarginInlineStart[js.Any]
     with _MarginLeft[js.Any]
     with _MarginRight[js.Any]
     with _MarginTop[js.Any]
     with _Marker
     with _MarkerEnd
     with _MarkerMid
     with _MarkerStart
     with _Mask[js.Any]
     with _MaskBorder
     with _MaskBorderRepeat
     with _MaskBorderSource
     with _MaskBorderWidth[js.Any]
     with _MaskClip
     with _MaskComposite
     with _MaskImage
     with _MaskMode
     with _MaskOrigin
     with _MaskPosition[js.Any]
     with _MaskRepeat
     with _MaskSize[js.Any]
     with _MaxBlockSize[js.Any]
     with _MaxHeight[js.Any]
     with _MaxInlineSize[js.Any]
     with _MaxLines
     with _MaxWidth[js.Any]
     with _MinBlockSize[js.Any]
     with _MinHeight[js.Any]
     with _MinInlineSize[js.Any]
     with _MinWidth[js.Any]
     with _MozBinding
     with _MozBorderBottomColors
     with _MozBorderLeftColors
     with _MozBorderRightColors
     with _MozBorderTopColors
     with _MozContextProperties
     with _MozImageRegion
     with _MsContentZoomSnap
     with _MsFlowFrom
     with _MsFlowInto
     with _MsHyphenateLimitChars
     with _MsHyphenateLimitLines
     with _MsScrollLimitXMax[js.Any]
     with _MsScrollLimitYMax[js.Any]
     with _MsScrollbar3dlightColor
     with _MsScrollbarArrowColor
     with _MsScrollbarBaseColor
     with _MsScrollbarDarkshadowColor
     with _MsScrollbarFaceColor
     with _MsScrollbarHighlightColor
     with _MsScrollbarShadowColor
     with _MsScrollbarTrackColor
     with _ObjectPosition[js.Any]
     with _Offset[js.Any]
     with _OffsetAnchor[js.Any]
     with _OffsetPath
     with _OffsetRotate
     with _Outline[js.Any]
     with _OutlineColor
     with _OutlineStyle
     with _OutlineWidth[js.Any]
     with _Overflow
     with _OverscrollBehavior
     with _PaintOrder
     with _Perspective[js.Any]
     with _PerspectiveOrigin[js.Any]
     with _PlaceContent
     with _PlaceItems
     with _PlaceSelf
     with _Quotes
     with _Right[js.Any]
     with _Rotate
     with _RowGap[js.Any]
     with _Scale
     with _ScrollPadding[js.Any]
     with _ScrollPaddingBlock[js.Any]
     with _ScrollPaddingBlockEnd[js.Any]
     with _ScrollPaddingBlockStart[js.Any]
     with _ScrollPaddingBottom[js.Any]
     with _ScrollPaddingInline[js.Any]
     with _ScrollPaddingInlineEnd[js.Any]
     with _ScrollPaddingInlineStart[js.Any]
     with _ScrollPaddingLeft[js.Any]
     with _ScrollPaddingRight[js.Any]
     with _ScrollPaddingTop[js.Any]
     with _ScrollSnapAlign
     with _ScrollSnapCoordinate[js.Any]
     with _ScrollSnapDestination[js.Any]
     with _ScrollSnapPointsX
     with _ScrollSnapPointsY
     with _ScrollSnapType
     with _ScrollbarColor
     with _ShapeOutside
     with _StopColor
     with _Stroke
     with _StrokeDasharray[js.Any]
     with _TextCombineUpright
     with _TextDecoration[js.Any]
     with _TextDecorationColor
     with _TextDecorationLine
     with _TextDecorationSkip
     with _TextDecorationThickness[js.Any]
     with _TextEmphasis
     with _TextEmphasisColor
     with _TextEmphasisStyle
     with _TextOverflow
     with _TextShadow
     with _TextSizeAdjust
     with _TextUnderlineOffset[js.Any]
     with _TextUnderlinePosition
     with _Top[js.Any]
     with _TouchAction
     with _Transform
     with _TransformOrigin[js.Any]
     with _Transition[js.Any]
     with _TransitionProperty
     with _TransitionTimingFunction
     with _Translate[js.Any]
     with _VerticalAlign[js.Any]
     with _WebkitBorderBefore[js.Any]
     with _WebkitBorderBeforeColor
     with _WebkitBorderBeforeStyle
     with _WebkitBorderBeforeWidth[js.Any]
     with _WebkitBoxReflect[js.Any]
     with _WebkitLineClamp
     with _WebkitMask[js.Any]
     with _WebkitMaskAttachment
     with _WebkitMaskClip
     with _WebkitMaskComposite
     with _WebkitMaskImage
     with _WebkitMaskOrigin
     with _WebkitMaskPosition[js.Any]
     with _WebkitMaskPositionX[js.Any]
     with _WebkitMaskPositionY[js.Any]
     with _WebkitMaskRepeat
     with _WebkitMaskSize[js.Any]
     with _WebkitTapHighlightColor
     with _WebkitTextFillColor
     with _WebkitTextStroke[js.Any]
     with _WebkitTextStrokeColor
     with _Width[js.Any]
     with _WillChange
     with _WordSpacing[js.Any]
     with _ZIndex
     with _Zoom
object Globals {
  
  @scala.inline
  def `-moz-initial`: typingsSlinky.csstype.csstypeStrings.`-moz-initial` = "-moz-initial".asInstanceOf[typingsSlinky.csstype.csstypeStrings.`-moz-initial`]
  
  @scala.inline
  def inherit: typingsSlinky.csstype.csstypeStrings.inherit = "inherit".asInstanceOf[typingsSlinky.csstype.csstypeStrings.inherit]
  
  @scala.inline
  def initial: typingsSlinky.csstype.csstypeStrings.initial = "initial".asInstanceOf[typingsSlinky.csstype.csstypeStrings.initial]
  
  @scala.inline
  def revert: typingsSlinky.csstype.csstypeStrings.revert = "revert".asInstanceOf[typingsSlinky.csstype.csstypeStrings.revert]
  
  @scala.inline
  def unset: typingsSlinky.csstype.csstypeStrings.unset = "unset".asInstanceOf[typingsSlinky.csstype.csstypeStrings.unset]
}
