package typingsSlinky.awsSdkClientCognitoIdentityBrowser.getCredentialsForIdentityExceptionsUnionMod

import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesExternalServiceExceptionMod.ExternalServiceException
import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesInternalErrorExceptionMod.InternalErrorException
import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesInvalidIdentityPoolConfigurationExceptionMod.InvalidIdentityPoolConfigurationException
import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesInvalidParameterExceptionMod.InvalidParameterException
import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesNotAuthorizedExceptionMod.NotAuthorizedException
import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesResourceConflictExceptionMod.ResourceConflictException
import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesResourceNotFoundExceptionMod.ResourceNotFoundException
import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesTooManyRequestsExceptionMod.TooManyRequestsException
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesInvalidParameterExceptionMod.InvalidParameterException
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesResourceNotFoundExceptionMod.ResourceNotFoundException
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesNotAuthorizedExceptionMod.NotAuthorizedException
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesResourceConflictExceptionMod.ResourceConflictException
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesTooManyRequestsExceptionMod.TooManyRequestsException
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesInvalidIdentityPoolConfigurationExceptionMod.InvalidIdentityPoolConfigurationException
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesInternalErrorExceptionMod.InternalErrorException
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesExternalServiceExceptionMod.ExternalServiceException
*/
trait GetCredentialsForIdentityExceptionsUnion extends js.Object

object GetCredentialsForIdentityExceptionsUnion {
  @scala.inline
  implicit def apply(value: ExternalServiceException): GetCredentialsForIdentityExceptionsUnion = value.asInstanceOf[GetCredentialsForIdentityExceptionsUnion]
  @scala.inline
  implicit def apply(value: InternalErrorException): GetCredentialsForIdentityExceptionsUnion = value.asInstanceOf[GetCredentialsForIdentityExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidIdentityPoolConfigurationException): GetCredentialsForIdentityExceptionsUnion = value.asInstanceOf[GetCredentialsForIdentityExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidParameterException): GetCredentialsForIdentityExceptionsUnion = value.asInstanceOf[GetCredentialsForIdentityExceptionsUnion]
  @scala.inline
  implicit def apply(value: NotAuthorizedException): GetCredentialsForIdentityExceptionsUnion = value.asInstanceOf[GetCredentialsForIdentityExceptionsUnion]
  @scala.inline
  implicit def apply(value: ResourceConflictException): GetCredentialsForIdentityExceptionsUnion = value.asInstanceOf[GetCredentialsForIdentityExceptionsUnion]
  @scala.inline
  implicit def apply(value: ResourceNotFoundException): GetCredentialsForIdentityExceptionsUnion = value.asInstanceOf[GetCredentialsForIdentityExceptionsUnion]
  @scala.inline
  implicit def apply(value: TooManyRequestsException): GetCredentialsForIdentityExceptionsUnion = value.asInstanceOf[GetCredentialsForIdentityExceptionsUnion]
}

