package typingsSlinky.officeJs.global.Excel

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/**
  *
  * Specifies the shape type for a GeometricShape object.
  *
  * [Api set: ExcelApi 1.9]
  */
@JSGlobal("Excel.GeometricShapeType")
@js.native
object GeometricShapeType extends js.Object {
  /* "AccentBorderCallout1" */ val accentBorderCallout1: typingsSlinky.officeJs.Excel.GeometricShapeType.accentBorderCallout1 with String = js.native
  /* "AccentBorderCallout2" */ val accentBorderCallout2: typingsSlinky.officeJs.Excel.GeometricShapeType.accentBorderCallout2 with String = js.native
  /* "AccentBorderCallout3" */ val accentBorderCallout3: typingsSlinky.officeJs.Excel.GeometricShapeType.accentBorderCallout3 with String = js.native
  /* "AccentCallout1" */ val accentCallout1: typingsSlinky.officeJs.Excel.GeometricShapeType.accentCallout1 with String = js.native
  /* "AccentCallout2" */ val accentCallout2: typingsSlinky.officeJs.Excel.GeometricShapeType.accentCallout2 with String = js.native
  /* "AccentCallout3" */ val accentCallout3: typingsSlinky.officeJs.Excel.GeometricShapeType.accentCallout3 with String = js.native
  /* "ActionButtonBackPrevious" */ val actionButtonBackPrevious: typingsSlinky.officeJs.Excel.GeometricShapeType.actionButtonBackPrevious with String = js.native
  /* "ActionButtonBeginning" */ val actionButtonBeginning: typingsSlinky.officeJs.Excel.GeometricShapeType.actionButtonBeginning with String = js.native
  /* "ActionButtonBlank" */ val actionButtonBlank: typingsSlinky.officeJs.Excel.GeometricShapeType.actionButtonBlank with String = js.native
  /* "ActionButtonDocument" */ val actionButtonDocument: typingsSlinky.officeJs.Excel.GeometricShapeType.actionButtonDocument with String = js.native
  /* "ActionButtonEnd" */ val actionButtonEnd: typingsSlinky.officeJs.Excel.GeometricShapeType.actionButtonEnd with String = js.native
  /* "ActionButtonForwardNext" */ val actionButtonForwardNext: typingsSlinky.officeJs.Excel.GeometricShapeType.actionButtonForwardNext with String = js.native
  /* "ActionButtonHelp" */ val actionButtonHelp: typingsSlinky.officeJs.Excel.GeometricShapeType.actionButtonHelp with String = js.native
  /* "ActionButtonHome" */ val actionButtonHome: typingsSlinky.officeJs.Excel.GeometricShapeType.actionButtonHome with String = js.native
  /* "ActionButtonInformation" */ val actionButtonInformation: typingsSlinky.officeJs.Excel.GeometricShapeType.actionButtonInformation with String = js.native
  /* "ActionButtonMovie" */ val actionButtonMovie: typingsSlinky.officeJs.Excel.GeometricShapeType.actionButtonMovie with String = js.native
  /* "ActionButtonReturn" */ val actionButtonReturn: typingsSlinky.officeJs.Excel.GeometricShapeType.actionButtonReturn with String = js.native
  /* "ActionButtonSound" */ val actionButtonSound: typingsSlinky.officeJs.Excel.GeometricShapeType.actionButtonSound with String = js.native
  /* "Arc" */ val arc: typingsSlinky.officeJs.Excel.GeometricShapeType.arc with String = js.native
  /* "BentArrow" */ val bentArrow: typingsSlinky.officeJs.Excel.GeometricShapeType.bentArrow with String = js.native
  /* "BentUpArrow" */ val bentUpArrow: typingsSlinky.officeJs.Excel.GeometricShapeType.bentUpArrow with String = js.native
  /* "Bevel" */ val bevel: typingsSlinky.officeJs.Excel.GeometricShapeType.bevel with String = js.native
  /* "BlockArc" */ val blockArc: typingsSlinky.officeJs.Excel.GeometricShapeType.blockArc with String = js.native
  /* "BorderCallout1" */ val borderCallout1: typingsSlinky.officeJs.Excel.GeometricShapeType.borderCallout1 with String = js.native
  /* "BorderCallout2" */ val borderCallout2: typingsSlinky.officeJs.Excel.GeometricShapeType.borderCallout2 with String = js.native
  /* "BorderCallout3" */ val borderCallout3: typingsSlinky.officeJs.Excel.GeometricShapeType.borderCallout3 with String = js.native
  /* "BracePair" */ val bracePair: typingsSlinky.officeJs.Excel.GeometricShapeType.bracePair with String = js.native
  /* "BracketPair" */ val bracketPair: typingsSlinky.officeJs.Excel.GeometricShapeType.bracketPair with String = js.native
  /* "Callout1" */ val callout1: typingsSlinky.officeJs.Excel.GeometricShapeType.callout1 with String = js.native
  /* "Callout2" */ val callout2: typingsSlinky.officeJs.Excel.GeometricShapeType.callout2 with String = js.native
  /* "Callout3" */ val callout3: typingsSlinky.officeJs.Excel.GeometricShapeType.callout3 with String = js.native
  /* "Can" */ val can: typingsSlinky.officeJs.Excel.GeometricShapeType.can with String = js.native
  /* "ChartPlus" */ val chartPlus: typingsSlinky.officeJs.Excel.GeometricShapeType.chartPlus with String = js.native
  /* "ChartStar" */ val chartStar: typingsSlinky.officeJs.Excel.GeometricShapeType.chartStar with String = js.native
  /* "ChartX" */ val chartX: typingsSlinky.officeJs.Excel.GeometricShapeType.chartX with String = js.native
  /* "Chevron" */ val chevron: typingsSlinky.officeJs.Excel.GeometricShapeType.chevron with String = js.native
  /* "Chord" */ val chord: typingsSlinky.officeJs.Excel.GeometricShapeType.chord with String = js.native
  /* "CircularArrow" */ val circularArrow: typingsSlinky.officeJs.Excel.GeometricShapeType.circularArrow with String = js.native
  /* "Cloud" */ val cloud: typingsSlinky.officeJs.Excel.GeometricShapeType.cloud with String = js.native
  /* "CloudCallout" */ val cloudCallout: typingsSlinky.officeJs.Excel.GeometricShapeType.cloudCallout with String = js.native
  /* "Corner" */ val corner: typingsSlinky.officeJs.Excel.GeometricShapeType.corner with String = js.native
  /* "CornerTabs" */ val cornerTabs: typingsSlinky.officeJs.Excel.GeometricShapeType.cornerTabs with String = js.native
  /* "Cube" */ val cube: typingsSlinky.officeJs.Excel.GeometricShapeType.cube with String = js.native
  /* "CurvedDownArrow" */ val curvedDownArrow: typingsSlinky.officeJs.Excel.GeometricShapeType.curvedDownArrow with String = js.native
  /* "CurvedLeftArrow" */ val curvedLeftArrow: typingsSlinky.officeJs.Excel.GeometricShapeType.curvedLeftArrow with String = js.native
  /* "CurvedRightArrow" */ val curvedRightArrow: typingsSlinky.officeJs.Excel.GeometricShapeType.curvedRightArrow with String = js.native
  /* "CurvedUpArrow" */ val curvedUpArrow: typingsSlinky.officeJs.Excel.GeometricShapeType.curvedUpArrow with String = js.native
  /* "Decagon" */ val decagon: typingsSlinky.officeJs.Excel.GeometricShapeType.decagon with String = js.native
  /* "DiagonalStripe" */ val diagonalStripe: typingsSlinky.officeJs.Excel.GeometricShapeType.diagonalStripe with String = js.native
  /* "Diamond" */ val diamond: typingsSlinky.officeJs.Excel.GeometricShapeType.diamond with String = js.native
  /* "Dodecagon" */ val dodecagon: typingsSlinky.officeJs.Excel.GeometricShapeType.dodecagon with String = js.native
  /* "Donut" */ val donut: typingsSlinky.officeJs.Excel.GeometricShapeType.donut with String = js.native
  /* "DoubleWave" */ val doubleWave: typingsSlinky.officeJs.Excel.GeometricShapeType.doubleWave with String = js.native
  /* "DownArrow" */ val downArrow: typingsSlinky.officeJs.Excel.GeometricShapeType.downArrow with String = js.native
  /* "DownArrowCallout" */ val downArrowCallout: typingsSlinky.officeJs.Excel.GeometricShapeType.downArrowCallout with String = js.native
  /* "Ellipse" */ val ellipse: typingsSlinky.officeJs.Excel.GeometricShapeType.ellipse with String = js.native
  /* "EllipseRibbon" */ val ellipseRibbon: typingsSlinky.officeJs.Excel.GeometricShapeType.ellipseRibbon with String = js.native
  /* "EllipseRibbon2" */ val ellipseRibbon2: typingsSlinky.officeJs.Excel.GeometricShapeType.ellipseRibbon2 with String = js.native
  /* "FlowChartAlternateProcess" */ val flowChartAlternateProcess: typingsSlinky.officeJs.Excel.GeometricShapeType.flowChartAlternateProcess with String = js.native
  /* "FlowChartCollate" */ val flowChartCollate: typingsSlinky.officeJs.Excel.GeometricShapeType.flowChartCollate with String = js.native
  /* "FlowChartConnector" */ val flowChartConnector: typingsSlinky.officeJs.Excel.GeometricShapeType.flowChartConnector with String = js.native
  /* "FlowChartDecision" */ val flowChartDecision: typingsSlinky.officeJs.Excel.GeometricShapeType.flowChartDecision with String = js.native
  /* "FlowChartDelay" */ val flowChartDelay: typingsSlinky.officeJs.Excel.GeometricShapeType.flowChartDelay with String = js.native
  /* "FlowChartDisplay" */ val flowChartDisplay: typingsSlinky.officeJs.Excel.GeometricShapeType.flowChartDisplay with String = js.native
  /* "FlowChartDocument" */ val flowChartDocument: typingsSlinky.officeJs.Excel.GeometricShapeType.flowChartDocument with String = js.native
  /* "FlowChartExtract" */ val flowChartExtract: typingsSlinky.officeJs.Excel.GeometricShapeType.flowChartExtract with String = js.native
  /* "FlowChartInputOutput" */ val flowChartInputOutput: typingsSlinky.officeJs.Excel.GeometricShapeType.flowChartInputOutput with String = js.native
  /* "FlowChartInternalStorage" */ val flowChartInternalStorage: typingsSlinky.officeJs.Excel.GeometricShapeType.flowChartInternalStorage with String = js.native
  /* "FlowChartMagneticDisk" */ val flowChartMagneticDisk: typingsSlinky.officeJs.Excel.GeometricShapeType.flowChartMagneticDisk with String = js.native
  /* "FlowChartMagneticDrum" */ val flowChartMagneticDrum: typingsSlinky.officeJs.Excel.GeometricShapeType.flowChartMagneticDrum with String = js.native
  /* "FlowChartMagneticTape" */ val flowChartMagneticTape: typingsSlinky.officeJs.Excel.GeometricShapeType.flowChartMagneticTape with String = js.native
  /* "FlowChartManualInput" */ val flowChartManualInput: typingsSlinky.officeJs.Excel.GeometricShapeType.flowChartManualInput with String = js.native
  /* "FlowChartManualOperation" */ val flowChartManualOperation: typingsSlinky.officeJs.Excel.GeometricShapeType.flowChartManualOperation with String = js.native
  /* "FlowChartMerge" */ val flowChartMerge: typingsSlinky.officeJs.Excel.GeometricShapeType.flowChartMerge with String = js.native
  /* "FlowChartMultidocument" */ val flowChartMultidocument: typingsSlinky.officeJs.Excel.GeometricShapeType.flowChartMultidocument with String = js.native
  /* "FlowChartOfflineStorage" */ val flowChartOfflineStorage: typingsSlinky.officeJs.Excel.GeometricShapeType.flowChartOfflineStorage with String = js.native
  /* "FlowChartOffpageConnector" */ val flowChartOffpageConnector: typingsSlinky.officeJs.Excel.GeometricShapeType.flowChartOffpageConnector with String = js.native
  /* "FlowChartOnlineStorage" */ val flowChartOnlineStorage: typingsSlinky.officeJs.Excel.GeometricShapeType.flowChartOnlineStorage with String = js.native
  /* "FlowChartOr" */ val flowChartOr: typingsSlinky.officeJs.Excel.GeometricShapeType.flowChartOr with String = js.native
  /* "FlowChartPredefinedProcess" */ val flowChartPredefinedProcess: typingsSlinky.officeJs.Excel.GeometricShapeType.flowChartPredefinedProcess with String = js.native
  /* "FlowChartPreparation" */ val flowChartPreparation: typingsSlinky.officeJs.Excel.GeometricShapeType.flowChartPreparation with String = js.native
  /* "FlowChartProcess" */ val flowChartProcess: typingsSlinky.officeJs.Excel.GeometricShapeType.flowChartProcess with String = js.native
  /* "FlowChartPunchedCard" */ val flowChartPunchedCard: typingsSlinky.officeJs.Excel.GeometricShapeType.flowChartPunchedCard with String = js.native
  /* "FlowChartPunchedTape" */ val flowChartPunchedTape: typingsSlinky.officeJs.Excel.GeometricShapeType.flowChartPunchedTape with String = js.native
  /* "FlowChartSort" */ val flowChartSort: typingsSlinky.officeJs.Excel.GeometricShapeType.flowChartSort with String = js.native
  /* "FlowChartSummingJunction" */ val flowChartSummingJunction: typingsSlinky.officeJs.Excel.GeometricShapeType.flowChartSummingJunction with String = js.native
  /* "FlowChartTerminator" */ val flowChartTerminator: typingsSlinky.officeJs.Excel.GeometricShapeType.flowChartTerminator with String = js.native
  /* "FoldedCorner" */ val foldedCorner: typingsSlinky.officeJs.Excel.GeometricShapeType.foldedCorner with String = js.native
  /* "Frame" */ val frame: typingsSlinky.officeJs.Excel.GeometricShapeType.frame with String = js.native
  /* "Funnel" */ val funnel: typingsSlinky.officeJs.Excel.GeometricShapeType.funnel with String = js.native
  /* "Gear6" */ val gear6: typingsSlinky.officeJs.Excel.GeometricShapeType.gear6 with String = js.native
  /* "Gear9" */ val gear9: typingsSlinky.officeJs.Excel.GeometricShapeType.gear9 with String = js.native
  /* "HalfFrame" */ val halfFrame: typingsSlinky.officeJs.Excel.GeometricShapeType.halfFrame with String = js.native
  /* "Heart" */ val heart: typingsSlinky.officeJs.Excel.GeometricShapeType.heart with String = js.native
  /* "Heptagon" */ val heptagon: typingsSlinky.officeJs.Excel.GeometricShapeType.heptagon with String = js.native
  /* "Hexagon" */ val hexagon: typingsSlinky.officeJs.Excel.GeometricShapeType.hexagon with String = js.native
  /* "HomePlate" */ val homePlate: typingsSlinky.officeJs.Excel.GeometricShapeType.homePlate with String = js.native
  /* "HorizontalScroll" */ val horizontalScroll: typingsSlinky.officeJs.Excel.GeometricShapeType.horizontalScroll with String = js.native
  /* "IrregularSeal1" */ val irregularSeal1: typingsSlinky.officeJs.Excel.GeometricShapeType.irregularSeal1 with String = js.native
  /* "IrregularSeal2" */ val irregularSeal2: typingsSlinky.officeJs.Excel.GeometricShapeType.irregularSeal2 with String = js.native
  /* "LeftArrow" */ val leftArrow: typingsSlinky.officeJs.Excel.GeometricShapeType.leftArrow with String = js.native
  /* "LeftArrowCallout" */ val leftArrowCallout: typingsSlinky.officeJs.Excel.GeometricShapeType.leftArrowCallout with String = js.native
  /* "LeftBrace" */ val leftBrace: typingsSlinky.officeJs.Excel.GeometricShapeType.leftBrace with String = js.native
  /* "LeftBracket" */ val leftBracket: typingsSlinky.officeJs.Excel.GeometricShapeType.leftBracket with String = js.native
  /* "LeftCircularArrow" */ val leftCircularArrow: typingsSlinky.officeJs.Excel.GeometricShapeType.leftCircularArrow with String = js.native
  /* "LeftRightArrow" */ val leftRightArrow: typingsSlinky.officeJs.Excel.GeometricShapeType.leftRightArrow with String = js.native
  /* "LeftRightArrowCallout" */ val leftRightArrowCallout: typingsSlinky.officeJs.Excel.GeometricShapeType.leftRightArrowCallout with String = js.native
  /* "LeftRightCircularArrow" */ val leftRightCircularArrow: typingsSlinky.officeJs.Excel.GeometricShapeType.leftRightCircularArrow with String = js.native
  /* "LeftRightRibbon" */ val leftRightRibbon: typingsSlinky.officeJs.Excel.GeometricShapeType.leftRightRibbon with String = js.native
  /* "LeftRightUpArrow" */ val leftRightUpArrow: typingsSlinky.officeJs.Excel.GeometricShapeType.leftRightUpArrow with String = js.native
  /* "LeftUpArrow" */ val leftUpArrow: typingsSlinky.officeJs.Excel.GeometricShapeType.leftUpArrow with String = js.native
  /* "LightningBolt" */ val lightningBolt: typingsSlinky.officeJs.Excel.GeometricShapeType.lightningBolt with String = js.native
  /* "LineInverse" */ val lineInverse: typingsSlinky.officeJs.Excel.GeometricShapeType.lineInverse with String = js.native
  /* "MathDivide" */ val mathDivide: typingsSlinky.officeJs.Excel.GeometricShapeType.mathDivide with String = js.native
  /* "MathEqual" */ val mathEqual: typingsSlinky.officeJs.Excel.GeometricShapeType.mathEqual with String = js.native
  /* "MathMinus" */ val mathMinus: typingsSlinky.officeJs.Excel.GeometricShapeType.mathMinus with String = js.native
  /* "MathMultiply" */ val mathMultiply: typingsSlinky.officeJs.Excel.GeometricShapeType.mathMultiply with String = js.native
  /* "MathNotEqual" */ val mathNotEqual: typingsSlinky.officeJs.Excel.GeometricShapeType.mathNotEqual with String = js.native
  /* "MathPlus" */ val mathPlus: typingsSlinky.officeJs.Excel.GeometricShapeType.mathPlus with String = js.native
  /* "Moon" */ val moon: typingsSlinky.officeJs.Excel.GeometricShapeType.moon with String = js.native
  /* "NoSmoking" */ val noSmoking: typingsSlinky.officeJs.Excel.GeometricShapeType.noSmoking with String = js.native
  /* "NonIsoscelesTrapezoid" */ val nonIsoscelesTrapezoid: typingsSlinky.officeJs.Excel.GeometricShapeType.nonIsoscelesTrapezoid with String = js.native
  /* "NotchedRightArrow" */ val notchedRightArrow: typingsSlinky.officeJs.Excel.GeometricShapeType.notchedRightArrow with String = js.native
  /* "Octagon" */ val octagon: typingsSlinky.officeJs.Excel.GeometricShapeType.octagon with String = js.native
  /* "Parallelogram" */ val parallelogram: typingsSlinky.officeJs.Excel.GeometricShapeType.parallelogram with String = js.native
  /* "Pentagon" */ val pentagon: typingsSlinky.officeJs.Excel.GeometricShapeType.pentagon with String = js.native
  /* "Pie" */ val pie: typingsSlinky.officeJs.Excel.GeometricShapeType.pie with String = js.native
  /* "PieWedge" */ val pieWedge: typingsSlinky.officeJs.Excel.GeometricShapeType.pieWedge with String = js.native
  /* "Plaque" */ val plaque: typingsSlinky.officeJs.Excel.GeometricShapeType.plaque with String = js.native
  /* "PlaqueTabs" */ val plaqueTabs: typingsSlinky.officeJs.Excel.GeometricShapeType.plaqueTabs with String = js.native
  /* "Plus" */ val plus: typingsSlinky.officeJs.Excel.GeometricShapeType.plus with String = js.native
  /* "QuadArrow" */ val quadArrow: typingsSlinky.officeJs.Excel.GeometricShapeType.quadArrow with String = js.native
  /* "QuadArrowCallout" */ val quadArrowCallout: typingsSlinky.officeJs.Excel.GeometricShapeType.quadArrowCallout with String = js.native
  /* "Rectangle" */ val rectangle: typingsSlinky.officeJs.Excel.GeometricShapeType.rectangle with String = js.native
  /* "Ribbon" */ val ribbon: typingsSlinky.officeJs.Excel.GeometricShapeType.ribbon with String = js.native
  /* "Ribbon2" */ val ribbon2: typingsSlinky.officeJs.Excel.GeometricShapeType.ribbon2 with String = js.native
  /* "RightArrow" */ val rightArrow: typingsSlinky.officeJs.Excel.GeometricShapeType.rightArrow with String = js.native
  /* "RightArrowCallout" */ val rightArrowCallout: typingsSlinky.officeJs.Excel.GeometricShapeType.rightArrowCallout with String = js.native
  /* "RightBrace" */ val rightBrace: typingsSlinky.officeJs.Excel.GeometricShapeType.rightBrace with String = js.native
  /* "RightBracket" */ val rightBracket: typingsSlinky.officeJs.Excel.GeometricShapeType.rightBracket with String = js.native
  /* "RightTriangle" */ val rightTriangle: typingsSlinky.officeJs.Excel.GeometricShapeType.rightTriangle with String = js.native
  /* "Round1Rectangle" */ val round1Rectangle: typingsSlinky.officeJs.Excel.GeometricShapeType.round1Rectangle with String = js.native
  /* "Round2DiagonalRectangle" */ val round2DiagonalRectangle: typingsSlinky.officeJs.Excel.GeometricShapeType.round2DiagonalRectangle with String = js.native
  /* "Round2SameRectangle" */ val round2SameRectangle: typingsSlinky.officeJs.Excel.GeometricShapeType.round2SameRectangle with String = js.native
  /* "RoundRectangle" */ val roundRectangle: typingsSlinky.officeJs.Excel.GeometricShapeType.roundRectangle with String = js.native
  /* "SmileyFace" */ val smileyFace: typingsSlinky.officeJs.Excel.GeometricShapeType.smileyFace with String = js.native
  /* "Snip1Rectangle" */ val snip1Rectangle: typingsSlinky.officeJs.Excel.GeometricShapeType.snip1Rectangle with String = js.native
  /* "Snip2DiagonalRectangle" */ val snip2DiagonalRectangle: typingsSlinky.officeJs.Excel.GeometricShapeType.snip2DiagonalRectangle with String = js.native
  /* "Snip2SameRectangle" */ val snip2SameRectangle: typingsSlinky.officeJs.Excel.GeometricShapeType.snip2SameRectangle with String = js.native
  /* "SnipRoundRectangle" */ val snipRoundRectangle: typingsSlinky.officeJs.Excel.GeometricShapeType.snipRoundRectangle with String = js.native
  /* "SquareTabs" */ val squareTabs: typingsSlinky.officeJs.Excel.GeometricShapeType.squareTabs with String = js.native
  /* "Star10" */ val star10: typingsSlinky.officeJs.Excel.GeometricShapeType.star10 with String = js.native
  /* "Star12" */ val star12: typingsSlinky.officeJs.Excel.GeometricShapeType.star12 with String = js.native
  /* "Star16" */ val star16: typingsSlinky.officeJs.Excel.GeometricShapeType.star16 with String = js.native
  /* "Star24" */ val star24: typingsSlinky.officeJs.Excel.GeometricShapeType.star24 with String = js.native
  /* "Star32" */ val star32: typingsSlinky.officeJs.Excel.GeometricShapeType.star32 with String = js.native
  /* "Star4" */ val star4: typingsSlinky.officeJs.Excel.GeometricShapeType.star4 with String = js.native
  /* "Star5" */ val star5: typingsSlinky.officeJs.Excel.GeometricShapeType.star5 with String = js.native
  /* "Star6" */ val star6: typingsSlinky.officeJs.Excel.GeometricShapeType.star6 with String = js.native
  /* "Star7" */ val star7: typingsSlinky.officeJs.Excel.GeometricShapeType.star7 with String = js.native
  /* "Star8" */ val star8: typingsSlinky.officeJs.Excel.GeometricShapeType.star8 with String = js.native
  /* "StripedRightArrow" */ val stripedRightArrow: typingsSlinky.officeJs.Excel.GeometricShapeType.stripedRightArrow with String = js.native
  /* "Sun" */ val sun: typingsSlinky.officeJs.Excel.GeometricShapeType.sun with String = js.native
  /* "SwooshArrow" */ val swooshArrow: typingsSlinky.officeJs.Excel.GeometricShapeType.swooshArrow with String = js.native
  /* "Teardrop" */ val teardrop: typingsSlinky.officeJs.Excel.GeometricShapeType.teardrop with String = js.native
  /* "Trapezoid" */ val trapezoid: typingsSlinky.officeJs.Excel.GeometricShapeType.trapezoid with String = js.native
  /* "Triangle" */ val triangle: typingsSlinky.officeJs.Excel.GeometricShapeType.triangle with String = js.native
  /* "UpArrow" */ val upArrow: typingsSlinky.officeJs.Excel.GeometricShapeType.upArrow with String = js.native
  /* "UpArrowCallout" */ val upArrowCallout: typingsSlinky.officeJs.Excel.GeometricShapeType.upArrowCallout with String = js.native
  /* "UpDownArrow" */ val upDownArrow: typingsSlinky.officeJs.Excel.GeometricShapeType.upDownArrow with String = js.native
  /* "UpDownArrowCallout" */ val upDownArrowCallout: typingsSlinky.officeJs.Excel.GeometricShapeType.upDownArrowCallout with String = js.native
  /* "UturnArrow" */ val uturnArrow: typingsSlinky.officeJs.Excel.GeometricShapeType.uturnArrow with String = js.native
  /* "VerticalScroll" */ val verticalScroll: typingsSlinky.officeJs.Excel.GeometricShapeType.verticalScroll with String = js.native
  /* "Wave" */ val wave: typingsSlinky.officeJs.Excel.GeometricShapeType.wave with String = js.native
  /* "WedgeEllipseCallout" */ val wedgeEllipseCallout: typingsSlinky.officeJs.Excel.GeometricShapeType.wedgeEllipseCallout with String = js.native
  /* "WedgeRRectCallout" */ val wedgeRRectCallout: typingsSlinky.officeJs.Excel.GeometricShapeType.wedgeRRectCallout with String = js.native
  /* "WedgeRectCallout" */ val wedgeRectCallout: typingsSlinky.officeJs.Excel.GeometricShapeType.wedgeRectCallout with String = js.native
  @JSBracketAccess
  def apply(value: String): js.UndefOr[typingsSlinky.officeJs.Excel.GeometricShapeType with String] = js.native
}

