package typingsSlinky.awsSdk.mediatailorMod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait DashConfiguration extends js.Object {
  /**
    * The URL generated by MediaTailor to initiate a playback session. The session uses server-side reporting. This setting is ignored in PUT operations. 
    */
  var ManifestEndpointPrefix: js.UndefOr[string] = js.native
  /**
    * The setting that controls whether MediaTailor includes the Location tag in DASH manifests. MediaTailor populates the Location tag with the URL for manifest update requests, to be used by players that don't support sticky redirects. Disable this if you have CDN routing rules set up for accessing MediaTailor manifests, and you are either using client-side reporting or your players support sticky HTTP redirects. Valid values are DISABLED and EMT_DEFAULT. The EMT_DEFAULT setting enables the inclusion of the tag and is the default value. 
    */
  var MpdLocation: js.UndefOr[string] = js.native
  /**
    * The setting that controls whether MediaTailor handles manifests from the origin server as multi-period manifests or single-period manifests. If your origin server produces single-period manifests, set this to SINGLE_PERIOD. The default setting is MULTI_PERIOD. For multi-period manifests, omit this setting or set it to MULTI_PERIOD. 
    */
  var OriginManifestType: js.UndefOr[typingsSlinky.awsSdk.mediatailorMod.OriginManifestType] = js.native
}

object DashConfiguration {
  @scala.inline
  def apply(): DashConfiguration = {
    val __obj = js.Dynamic.literal()
    __obj.asInstanceOf[DashConfiguration]
  }
  @scala.inline
  implicit class DashConfigurationOps[Self <: DashConfiguration] (val x: Self) extends AnyVal {
    @scala.inline
    def duplicate: Self = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x)).asInstanceOf[Self]
    @scala.inline
    def combineWith[Other <: js.Any](other: Other): Self with Other = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x, other.asInstanceOf[js.Any])).asInstanceOf[Self with Other]
    @scala.inline
    def withManifestEndpointPrefix(value: string): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("ManifestEndpointPrefix")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutManifestEndpointPrefix: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("ManifestEndpointPrefix")(js.undefined)
        ret
    }
    @scala.inline
    def withMpdLocation(value: string): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("MpdLocation")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutMpdLocation: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("MpdLocation")(js.undefined)
        ret
    }
    @scala.inline
    def withOriginManifestType(value: OriginManifestType): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("OriginManifestType")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutOriginManifestType: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("OriginManifestType")(js.undefined)
        ret
    }
  }
  
}

