package typingsSlinky.fluentuiReactComponentEventListener

import slinky.core.facade.ReactRef
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.abort
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.animationcancel
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.animationend
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.animationiteration
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.animationstart
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.auxclick
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.blur
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.cancel
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.canplay
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.canplaythrough
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.change
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.click
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.close
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.contextmenu
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.copy
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.cuechange
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.cut
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.dblclick
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.drag
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.dragend
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.dragenter
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.dragexit
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.dragleave
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.dragover
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.dragstart
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.drop
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.durationchange
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.emptied
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.ended
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.error
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.focus
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.focusin
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.focusout
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.fullscreenchange
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.fullscreenerror
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.gotpointercapture
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.input
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.invalid
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.keydown
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.keypress
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.keyup
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.load
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.loadeddata
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.loadedmetadata
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.loadstart
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.lostpointercapture
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.mousedown
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.mouseenter
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.mouseleave
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.mousemove
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.mouseout
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.mouseover
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.mouseup
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.paste
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.pause
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.play
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.playing
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.pointercancel
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.pointerdown
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.pointerenter
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.pointerleave
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.pointerlockchange
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.pointerlockerror
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.pointermove
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.pointerout
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.pointerover
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.pointerup
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.progress
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.ratechange
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.readystatechange
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.reset
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.resize
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.scroll
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.securitypolicyviolation
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.seeked
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.seeking
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.select
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.selectionchange
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.selectstart
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.stalled
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.submit
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.suspend
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.timeupdate
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.toggle
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.touchcancel
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.touchend
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.touchmove
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.touchstart
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.transitioncancel
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.transitionend
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.transitionrun
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.transitionstart
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.visibilitychange
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.volumechange
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.waiting
import typingsSlinky.fluentuiReactComponentEventListener.fluentuiReactComponentEventListenerStrings.wheel
import typingsSlinky.fluentuiReactComponentEventListener.typesMod.EventListenerOptions
import typingsSlinky.fluentuiReactComponentEventListener.typesMod.Target
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

@JSImport("@fluentui/react-component-event-listener", JSImport.Namespace)
@js.native
object mod extends js.Object {
  
  val documentRef: ReactRef[Target] = js.native
  
  def useEventListener[T /* <: /* import warning: LimitUnionLength.leaveTypeRef Was union type with length 97 */ js.Any */](options: EventListenerOptions[T]): Unit = js.native
  
  val windowRef: ReactRef[Target] = js.native
  
  @js.native
  object EventListener extends js.Object {
    
    def apply(
      props: EventListenerOptions[
          abort | animationcancel | animationend | animationiteration | animationstart | auxclick | blur | cancel | canplay | canplaythrough | change | click | close | contextmenu | copy | cuechange | cut | dblclick | drag | dragend | dragenter | dragexit | dragleave | dragover | dragstart | drop | durationchange | emptied | ended | error | focus | focusin | focusout | fullscreenchange | fullscreenerror | gotpointercapture | input | invalid | keydown | keypress | keyup | load | loadeddata | loadedmetadata | loadstart | lostpointercapture | mousedown | mouseenter | mouseleave | mousemove | mouseout | mouseover | mouseup | paste | pause | play | playing | pointercancel | pointerdown | pointerenter | pointerleave | pointerlockchange | pointerlockerror | pointermove | pointerout | pointerover | pointerup | progress | ratechange | readystatechange | reset | resize | scroll | securitypolicyviolation | seeked | seeking | select | selectionchange | selectstart | stalled | submit | suspend | timeupdate | toggle | touchcancel | touchend | touchmove | touchstart | transitioncancel | transitionend | transitionrun | transitionstart | visibilitychange | volumechange | waiting | wheel
        ]
    ): Null = js.native
    
    @js.native
    object defaultProps extends js.Object {
      
      var capture: Boolean = js.native
    }
  }
}
