package typingsSlinky.awsSdkClientCodecommitNode.getCommentsForPullRequestExceptionsUnionMod

import typingsSlinky.awsSdkClientCodecommitNode.typesCommitDoesNotExistExceptionMod.CommitDoesNotExistException
import typingsSlinky.awsSdkClientCodecommitNode.typesCommitIdRequiredExceptionMod.CommitIdRequiredException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionIntegrityChecksFailedExceptionMod.EncryptionIntegrityChecksFailedException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyAccessDeniedExceptionMod.EncryptionKeyAccessDeniedException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyDisabledExceptionMod.EncryptionKeyDisabledException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyNotFoundExceptionMod.EncryptionKeyNotFoundException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyUnavailableExceptionMod.EncryptionKeyUnavailableException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidCommitIdExceptionMod.InvalidCommitIdException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidContinuationTokenExceptionMod.InvalidContinuationTokenException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidMaxResultsExceptionMod.InvalidMaxResultsException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidPullRequestIdExceptionMod.InvalidPullRequestIdException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryNameExceptionMod.InvalidRepositoryNameException
import typingsSlinky.awsSdkClientCodecommitNode.typesPullRequestDoesNotExistExceptionMod.PullRequestDoesNotExistException
import typingsSlinky.awsSdkClientCodecommitNode.typesPullRequestIdRequiredExceptionMod.PullRequestIdRequiredException
import typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryDoesNotExistExceptionMod.RepositoryDoesNotExistException
import typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryNameRequiredExceptionMod.RepositoryNameRequiredException
import typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryNotAssociatedWithPullRequestExceptionMod.RepositoryNotAssociatedWithPullRequestException
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - typingsSlinky.awsSdkClientCodecommitNode.typesPullRequestIdRequiredExceptionMod.PullRequestIdRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesPullRequestDoesNotExistExceptionMod.PullRequestDoesNotExistException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidPullRequestIdExceptionMod.InvalidPullRequestIdException
  - typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryNameRequiredExceptionMod.RepositoryNameRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryDoesNotExistExceptionMod.RepositoryDoesNotExistException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryNameExceptionMod.InvalidRepositoryNameException
  - typingsSlinky.awsSdkClientCodecommitNode.typesCommitIdRequiredExceptionMod.CommitIdRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidCommitIdExceptionMod.InvalidCommitIdException
  - typingsSlinky.awsSdkClientCodecommitNode.typesCommitDoesNotExistExceptionMod.CommitDoesNotExistException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidMaxResultsExceptionMod.InvalidMaxResultsException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidContinuationTokenExceptionMod.InvalidContinuationTokenException
  - typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryNotAssociatedWithPullRequestExceptionMod.RepositoryNotAssociatedWithPullRequestException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionIntegrityChecksFailedExceptionMod.EncryptionIntegrityChecksFailedException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyAccessDeniedExceptionMod.EncryptionKeyAccessDeniedException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyDisabledExceptionMod.EncryptionKeyDisabledException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyNotFoundExceptionMod.EncryptionKeyNotFoundException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyUnavailableExceptionMod.EncryptionKeyUnavailableException
*/
trait GetCommentsForPullRequestExceptionsUnion extends js.Object

object GetCommentsForPullRequestExceptionsUnion {
  @scala.inline
  implicit def apply(value: CommitDoesNotExistException): GetCommentsForPullRequestExceptionsUnion = value.asInstanceOf[GetCommentsForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: CommitIdRequiredException): GetCommentsForPullRequestExceptionsUnion = value.asInstanceOf[GetCommentsForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionIntegrityChecksFailedException): GetCommentsForPullRequestExceptionsUnion = value.asInstanceOf[GetCommentsForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyAccessDeniedException): GetCommentsForPullRequestExceptionsUnion = value.asInstanceOf[GetCommentsForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyDisabledException): GetCommentsForPullRequestExceptionsUnion = value.asInstanceOf[GetCommentsForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyNotFoundException): GetCommentsForPullRequestExceptionsUnion = value.asInstanceOf[GetCommentsForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyUnavailableException): GetCommentsForPullRequestExceptionsUnion = value.asInstanceOf[GetCommentsForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidCommitIdException): GetCommentsForPullRequestExceptionsUnion = value.asInstanceOf[GetCommentsForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidContinuationTokenException): GetCommentsForPullRequestExceptionsUnion = value.asInstanceOf[GetCommentsForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidMaxResultsException): GetCommentsForPullRequestExceptionsUnion = value.asInstanceOf[GetCommentsForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidPullRequestIdException): GetCommentsForPullRequestExceptionsUnion = value.asInstanceOf[GetCommentsForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidRepositoryNameException): GetCommentsForPullRequestExceptionsUnion = value.asInstanceOf[GetCommentsForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: PullRequestDoesNotExistException): GetCommentsForPullRequestExceptionsUnion = value.asInstanceOf[GetCommentsForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: PullRequestIdRequiredException): GetCommentsForPullRequestExceptionsUnion = value.asInstanceOf[GetCommentsForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: RepositoryDoesNotExistException): GetCommentsForPullRequestExceptionsUnion = value.asInstanceOf[GetCommentsForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: RepositoryNameRequiredException): GetCommentsForPullRequestExceptionsUnion = value.asInstanceOf[GetCommentsForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: RepositoryNotAssociatedWithPullRequestException): GetCommentsForPullRequestExceptionsUnion = value.asInstanceOf[GetCommentsForPullRequestExceptionsUnion]
}

