package typingsSlinky.antd.anon

import org.scalajs.dom.raw.HTMLSpanElement
import typingsSlinky.react.mod.Key
import typingsSlinky.react.mod.Ref
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Inlined std.Pick</ * import warning: transforms.QualifyReferences#resolveTypeRef many Couldn't qualify imported_AntdIcon.AntdIconProps * / any, 'children' | 'size' | 'cite' | 'data' | 'form' | 'label' | 'slot' | 'span' | 'style' | 'summary' | 'title' | 'pattern' | 'className' | 'disabled' | 'dir' | 'max' | 'required' | 'high' | 'low' | 'default' | 'start' | 'open' | 'media' | 'hidden' | 'async' | 'defer' | 'manifest' | 'color' | 'content' | 'wrap' | 'multiple' | 'key' | 'list' | 'step' | 'aria-label' | 'spin' | 'rotate' | 'accept' | 'acceptCharset' | 'action' | 'allowFullScreen' | 'allowTransparency' | 'alt' | 'as' | 'autoComplete' | 'autoFocus' | 'autoPlay' | 'capture' | 'cellPadding' | 'cellSpacing' | 'charSet' | 'challenge' | 'checked' | 'classID' | 'cols' | 'colSpan' | 'controls' | 'coords' | 'crossOrigin' | 'dateTime' | 'download' | 'encType' | 'formAction' | 'formEncType' | 'formMethod' | 'formNoValidate' | 'formTarget' | 'frameBorder' | 'headers' | 'height' | 'href' | 'hrefLang' | 'htmlFor' | 'httpEquiv' | 'integrity' | 'keyParams' | 'keyType' | 'kind' | 'loop' | 'marginHeight' | 'marginWidth' | 'maxLength' | 'mediaGroup' | 'method' | 'min' | 'minLength' | 'muted' | 'name' | 'nonce' | 'noValidate' | 'optimum' | 'placeholder' | 'playsInline' | 'poster' | 'preload' | 'readOnly' | 'rel' | 'reversed' | 'rows' | 'rowSpan' | 'sandbox' | 'scope' | 'scoped' | 'scrolling' | 'seamless' | 'selected' | 'shape' | 'sizes' | 'src' | 'srcDoc' | 'srcLang' | 'srcSet' | 'target' | 'type' | 'useMap' | 'value' | 'width' | 'wmode' | 'defaultChecked' | 'defaultValue' | 'suppressContentEditableWarning' | 'suppressHydrationWarning' | 'accessKey' | 'contentEditable' | 'contextMenu' | 'draggable' | 'id' | 'lang' | 'spellCheck' | 'tabIndex' | 'translate' | 'radioGroup' | 'role' | 'about' | 'datatype' | 'inlist' | 'prefix' | 'property' | 'resource' | 'typeof' | 'vocab' | 'autoCapitalize' | 'autoCorrect' | 'autoSave' | 'itemProp' | 'itemScope' | 'itemType' | 'itemID' | 'itemRef' | 'results' | 'security' | 'unselectable' | 'inputMode' | 'is' | 'aria-activedescendant' | 'aria-atomic' | 'aria-autocomplete' | 'aria-busy' | 'aria-checked' | 'aria-colcount' | 'aria-colindex' | 'aria-colspan' | 'aria-controls' | 'aria-current' | 'aria-describedby' | 'aria-details' | 'aria-disabled' | 'aria-dropeffect' | 'aria-errormessage' | 'aria-expanded' | 'aria-flowto' | 'aria-grabbed' | 'aria-haspopup' | 'aria-hidden' | 'aria-invalid' | 'aria-keyshortcuts' | 'aria-labelledby' | 'aria-level' | 'aria-live' | 'aria-modal' | 'aria-multiline' | 'aria-multiselectable' | 'aria-orientation' | 'aria-owns' | 'aria-placeholder' | 'aria-posinset' | 'aria-pressed' | 'aria-readonly' | 'aria-relevant' | 'aria-required' | 'aria-roledescription' | 'aria-rowcount' | 'aria-rowindex' | 'aria-rowspan' | 'aria-selected' | 'aria-setsize' | 'aria-sort' | 'aria-valuemax' | 'aria-valuemin' | 'aria-valuenow' | 'aria-valuetext' | 'dangerouslySetInnerHTML' | 'onCopy' | 'onCopyCapture' | 'onCut' | 'onCutCapture' | 'onPaste' | 'onPasteCapture' | 'onCompositionEnd' | 'onCompositionEndCapture' | 'onCompositionStart' | 'onCompositionStartCapture' | 'onCompositionUpdate' | 'onCompositionUpdateCapture' | 'onFocus' | 'onFocusCapture' | 'onBlur' | 'onBlurCapture' | 'onChange' | 'onChangeCapture' | 'onBeforeInput' | 'onBeforeInputCapture' | 'onInput' | 'onInputCapture' | 'onReset' | 'onResetCapture' | 'onSubmit' | 'onSubmitCapture' | 'onInvalid' | 'onInvalidCapture' | 'onLoad' | 'onLoadCapture' | 'onError' | 'onErrorCapture' | 'onKeyDown' | 'onKeyDownCapture' | 'onKeyPress' | 'onKeyPressCapture' | 'onKeyUp' | 'onKeyUpCapture' | 'onAbort' | 'onAbortCapture' | 'onCanPlay' | 'onCanPlayCapture' | 'onCanPlayThrough' | 'onCanPlayThroughCapture' | 'onDurationChange' | 'onDurationChangeCapture' | 'onEmptied' | 'onEmptiedCapture' | 'onEncrypted' | 'onEncryptedCapture' | 'onEnded' | 'onEndedCapture' | 'onLoadedData' | 'onLoadedDataCapture' | 'onLoadedMetadata' | 'onLoadedMetadataCapture' | 'onLoadStart' | 'onLoadStartCapture' | 'onPause' | 'onPauseCapture' | 'onPlay' | 'onPlayCapture' | 'onPlaying' | 'onPlayingCapture' | 'onProgress' | 'onProgressCapture' | 'onRateChange' | 'onRateChangeCapture' | 'onSeeked' | 'onSeekedCapture' | 'onSeeking' | 'onSeekingCapture' | 'onStalled' | 'onStalledCapture' | 'onSuspend' | 'onSuspendCapture' | 'onTimeUpdate' | 'onTimeUpdateCapture' | 'onVolumeChange' | 'onVolumeChangeCapture' | 'onWaiting' | 'onWaitingCapture' | 'onAuxClick' | 'onAuxClickCapture' | 'onClick' | 'onClickCapture' | 'onContextMenu' | 'onContextMenuCapture' | 'onDoubleClick' | 'onDoubleClickCapture' | 'onDrag' | 'onDragCapture' | 'onDragEnd' | 'onDragEndCapture' | 'onDragEnter' | 'onDragEnterCapture' | 'onDragExit' | 'onDragExitCapture' | 'onDragLeave' | 'onDragLeaveCapture' | 'onDragOver' | 'onDragOverCapture' | 'onDragStart' | 'onDragStartCapture' | 'onDrop' | 'onDropCapture' | 'onMouseDown' | 'onMouseDownCapture' | 'onMouseEnter' | 'onMouseLeave' | 'onMouseMove' | 'onMouseMoveCapture' | 'onMouseOut' | 'onMouseOutCapture' | 'onMouseOver' | 'onMouseOverCapture' | 'onMouseUp' | 'onMouseUpCapture' | 'onSelect' | 'onSelectCapture' | 'onTouchCancel' | 'onTouchCancelCapture' | 'onTouchEnd' | 'onTouchEndCapture' | 'onTouchMove' | 'onTouchMoveCapture' | 'onTouchStart' | 'onTouchStartCapture' | 'onPointerDown' | 'onPointerDownCapture' | 'onPointerMove' | 'onPointerMoveCapture' | 'onPointerUp' | 'onPointerUpCapture' | 'onPointerCancel' | 'onPointerCancelCapture' | 'onPointerEnter' | 'onPointerEnterCapture' | 'onPointerLeave' | 'onPointerLeaveCapture' | 'onPointerOver' | 'onPointerOverCapture' | 'onPointerOut' | 'onPointerOutCapture' | 'onGotPointerCapture' | 'onGotPointerCaptureCapture' | 'onLostPointerCapture' | 'onLostPointerCaptureCapture' | 'onScroll' | 'onScrollCapture' | 'onWheel' | 'onWheelCapture' | 'onAnimationStart' | 'onAnimationStartCapture' | 'onAnimationEnd' | 'onAnimationEndCapture' | 'onAnimationIteration' | 'onAnimationIterationCapture' | 'onTransitionEnd' | 'onTransitionEndCapture' | 'twoToneColor'> & react.react.RefAttributes<std.HTMLSpanElement> */
trait Pickanychildrensizeciteda extends js.Object {
  var about: js.UndefOr[js.Any] = js.undefined
  var accept: js.UndefOr[js.Any] = js.undefined
  var acceptCharset: js.UndefOr[js.Any] = js.undefined
  var accessKey: js.UndefOr[js.Any] = js.undefined
  var action: js.UndefOr[js.Any] = js.undefined
  var allowFullScreen: js.UndefOr[js.Any] = js.undefined
  var allowTransparency: js.UndefOr[js.Any] = js.undefined
  var alt: js.UndefOr[js.Any] = js.undefined
  var `aria-activedescendant`: js.UndefOr[js.Any] = js.undefined
  var `aria-atomic`: js.UndefOr[js.Any] = js.undefined
  var `aria-autocomplete`: js.UndefOr[js.Any] = js.undefined
  var `aria-busy`: js.UndefOr[js.Any] = js.undefined
  var `aria-checked`: js.UndefOr[js.Any] = js.undefined
  var `aria-colcount`: js.UndefOr[js.Any] = js.undefined
  var `aria-colindex`: js.UndefOr[js.Any] = js.undefined
  var `aria-colspan`: js.UndefOr[js.Any] = js.undefined
  var `aria-controls`: js.UndefOr[js.Any] = js.undefined
  var `aria-current`: js.UndefOr[js.Any] = js.undefined
  var `aria-describedby`: js.UndefOr[js.Any] = js.undefined
  var `aria-details`: js.UndefOr[js.Any] = js.undefined
  var `aria-disabled`: js.UndefOr[js.Any] = js.undefined
  var `aria-dropeffect`: js.UndefOr[js.Any] = js.undefined
  var `aria-errormessage`: js.UndefOr[js.Any] = js.undefined
  var `aria-expanded`: js.UndefOr[js.Any] = js.undefined
  var `aria-flowto`: js.UndefOr[js.Any] = js.undefined
  var `aria-grabbed`: js.UndefOr[js.Any] = js.undefined
  var `aria-haspopup`: js.UndefOr[js.Any] = js.undefined
  var `aria-hidden`: js.UndefOr[js.Any] = js.undefined
  var `aria-invalid`: js.UndefOr[js.Any] = js.undefined
  var `aria-keyshortcuts`: js.UndefOr[js.Any] = js.undefined
  var `aria-label`: js.UndefOr[js.Any] = js.undefined
  var `aria-labelledby`: js.UndefOr[js.Any] = js.undefined
  var `aria-level`: js.UndefOr[js.Any] = js.undefined
  var `aria-live`: js.UndefOr[js.Any] = js.undefined
  var `aria-modal`: js.UndefOr[js.Any] = js.undefined
  var `aria-multiline`: js.UndefOr[js.Any] = js.undefined
  var `aria-multiselectable`: js.UndefOr[js.Any] = js.undefined
  var `aria-orientation`: js.UndefOr[js.Any] = js.undefined
  var `aria-owns`: js.UndefOr[js.Any] = js.undefined
  var `aria-placeholder`: js.UndefOr[js.Any] = js.undefined
  var `aria-posinset`: js.UndefOr[js.Any] = js.undefined
  var `aria-pressed`: js.UndefOr[js.Any] = js.undefined
  var `aria-readonly`: js.UndefOr[js.Any] = js.undefined
  var `aria-relevant`: js.UndefOr[js.Any] = js.undefined
  var `aria-required`: js.UndefOr[js.Any] = js.undefined
  var `aria-roledescription`: js.UndefOr[js.Any] = js.undefined
  var `aria-rowcount`: js.UndefOr[js.Any] = js.undefined
  var `aria-rowindex`: js.UndefOr[js.Any] = js.undefined
  var `aria-rowspan`: js.UndefOr[js.Any] = js.undefined
  var `aria-selected`: js.UndefOr[js.Any] = js.undefined
  var `aria-setsize`: js.UndefOr[js.Any] = js.undefined
  var `aria-sort`: js.UndefOr[js.Any] = js.undefined
  var `aria-valuemax`: js.UndefOr[js.Any] = js.undefined
  var `aria-valuemin`: js.UndefOr[js.Any] = js.undefined
  var `aria-valuenow`: js.UndefOr[js.Any] = js.undefined
  var `aria-valuetext`: js.UndefOr[js.Any] = js.undefined
  var as: js.UndefOr[js.Any] = js.undefined
  var async: js.UndefOr[js.Any] = js.undefined
  var autoCapitalize: js.UndefOr[js.Any] = js.undefined
  var autoComplete: js.UndefOr[js.Any] = js.undefined
  var autoCorrect: js.UndefOr[js.Any] = js.undefined
  var autoFocus: js.UndefOr[js.Any] = js.undefined
  var autoPlay: js.UndefOr[js.Any] = js.undefined
  var autoSave: js.UndefOr[js.Any] = js.undefined
  var capture: js.UndefOr[js.Any] = js.undefined
  var cellPadding: js.UndefOr[js.Any] = js.undefined
  var cellSpacing: js.UndefOr[js.Any] = js.undefined
  var challenge: js.UndefOr[js.Any] = js.undefined
  var charSet: js.UndefOr[js.Any] = js.undefined
  var checked: js.UndefOr[js.Any] = js.undefined
  var children: js.UndefOr[js.Any] = js.undefined
  var cite: js.UndefOr[js.Any] = js.undefined
  var classID: js.UndefOr[js.Any] = js.undefined
  var className: js.UndefOr[js.Any] = js.undefined
  var colSpan: js.UndefOr[js.Any] = js.undefined
  var color: js.UndefOr[js.Any] = js.undefined
  var cols: js.UndefOr[js.Any] = js.undefined
  var content: js.UndefOr[js.Any] = js.undefined
  var contentEditable: js.UndefOr[js.Any] = js.undefined
  var contextMenu: js.UndefOr[js.Any] = js.undefined
  var controls: js.UndefOr[js.Any] = js.undefined
  var coords: js.UndefOr[js.Any] = js.undefined
  var crossOrigin: js.UndefOr[js.Any] = js.undefined
  var dangerouslySetInnerHTML: js.UndefOr[js.Any] = js.undefined
  var data: js.UndefOr[js.Any] = js.undefined
  var datatype: js.UndefOr[js.Any] = js.undefined
  var dateTime: js.UndefOr[js.Any] = js.undefined
  var default: js.UndefOr[js.Any] = js.undefined
  var defaultChecked: js.UndefOr[js.Any] = js.undefined
  var defaultValue: js.UndefOr[js.Any] = js.undefined
  var defer: js.UndefOr[js.Any] = js.undefined
  var dir: js.UndefOr[js.Any] = js.undefined
  var disabled: js.UndefOr[js.Any] = js.undefined
  var download: js.UndefOr[js.Any] = js.undefined
  var draggable: js.UndefOr[js.Any] = js.undefined
  var encType: js.UndefOr[js.Any] = js.undefined
  var form: js.UndefOr[js.Any] = js.undefined
  var formAction: js.UndefOr[js.Any] = js.undefined
  var formEncType: js.UndefOr[js.Any] = js.undefined
  var formMethod: js.UndefOr[js.Any] = js.undefined
  var formNoValidate: js.UndefOr[js.Any] = js.undefined
  var formTarget: js.UndefOr[js.Any] = js.undefined
  var frameBorder: js.UndefOr[js.Any] = js.undefined
  var headers: js.UndefOr[js.Any] = js.undefined
  var height: js.UndefOr[js.Any] = js.undefined
  var hidden: js.UndefOr[js.Any] = js.undefined
  var high: js.UndefOr[js.Any] = js.undefined
  var href: js.UndefOr[js.Any] = js.undefined
  var hrefLang: js.UndefOr[js.Any] = js.undefined
  var htmlFor: js.UndefOr[js.Any] = js.undefined
  var httpEquiv: js.UndefOr[js.Any] = js.undefined
  var id: js.UndefOr[js.Any] = js.undefined
  var inlist: js.UndefOr[js.Any] = js.undefined
  var inputMode: js.UndefOr[js.Any] = js.undefined
  var integrity: js.UndefOr[js.Any] = js.undefined
  var is: js.UndefOr[js.Any] = js.undefined
  var itemID: js.UndefOr[js.Any] = js.undefined
  var itemProp: js.UndefOr[js.Any] = js.undefined
  var itemRef: js.UndefOr[js.Any] = js.undefined
  var itemScope: js.UndefOr[js.Any] = js.undefined
  var itemType: js.UndefOr[js.Any] = js.undefined
  var key: js.UndefOr[js.Any with Key] = js.undefined
  var keyParams: js.UndefOr[js.Any] = js.undefined
  var keyType: js.UndefOr[js.Any] = js.undefined
  var kind: js.UndefOr[js.Any] = js.undefined
  var label: js.UndefOr[js.Any] = js.undefined
  var lang: js.UndefOr[js.Any] = js.undefined
  var list: js.UndefOr[js.Any] = js.undefined
  var loop: js.UndefOr[js.Any] = js.undefined
  var low: js.UndefOr[js.Any] = js.undefined
  var manifest: js.UndefOr[js.Any] = js.undefined
  var marginHeight: js.UndefOr[js.Any] = js.undefined
  var marginWidth: js.UndefOr[js.Any] = js.undefined
  var max: js.UndefOr[js.Any] = js.undefined
  var maxLength: js.UndefOr[js.Any] = js.undefined
  var media: js.UndefOr[js.Any] = js.undefined
  var mediaGroup: js.UndefOr[js.Any] = js.undefined
  var method: js.UndefOr[js.Any] = js.undefined
  var min: js.UndefOr[js.Any] = js.undefined
  var minLength: js.UndefOr[js.Any] = js.undefined
  var multiple: js.UndefOr[js.Any] = js.undefined
  var muted: js.UndefOr[js.Any] = js.undefined
  var name: js.UndefOr[js.Any] = js.undefined
  var noValidate: js.UndefOr[js.Any] = js.undefined
  var nonce: js.UndefOr[js.Any] = js.undefined
  var onAbort: js.UndefOr[js.Any] = js.undefined
  var onAbortCapture: js.UndefOr[js.Any] = js.undefined
  var onAnimationEnd: js.UndefOr[js.Any] = js.undefined
  var onAnimationEndCapture: js.UndefOr[js.Any] = js.undefined
  var onAnimationIteration: js.UndefOr[js.Any] = js.undefined
  var onAnimationIterationCapture: js.UndefOr[js.Any] = js.undefined
  var onAnimationStart: js.UndefOr[js.Any] = js.undefined
  var onAnimationStartCapture: js.UndefOr[js.Any] = js.undefined
  var onAuxClick: js.UndefOr[js.Any] = js.undefined
  var onAuxClickCapture: js.UndefOr[js.Any] = js.undefined
  var onBeforeInput: js.UndefOr[js.Any] = js.undefined
  var onBeforeInputCapture: js.UndefOr[js.Any] = js.undefined
  var onBlur: js.UndefOr[js.Any] = js.undefined
  var onBlurCapture: js.UndefOr[js.Any] = js.undefined
  var onCanPlay: js.UndefOr[js.Any] = js.undefined
  var onCanPlayCapture: js.UndefOr[js.Any] = js.undefined
  var onCanPlayThrough: js.UndefOr[js.Any] = js.undefined
  var onCanPlayThroughCapture: js.UndefOr[js.Any] = js.undefined
  var onChange: js.UndefOr[js.Any] = js.undefined
  var onChangeCapture: js.UndefOr[js.Any] = js.undefined
  var onClick: js.UndefOr[js.Any] = js.undefined
  var onClickCapture: js.UndefOr[js.Any] = js.undefined
  var onCompositionEnd: js.UndefOr[js.Any] = js.undefined
  var onCompositionEndCapture: js.UndefOr[js.Any] = js.undefined
  var onCompositionStart: js.UndefOr[js.Any] = js.undefined
  var onCompositionStartCapture: js.UndefOr[js.Any] = js.undefined
  var onCompositionUpdate: js.UndefOr[js.Any] = js.undefined
  var onCompositionUpdateCapture: js.UndefOr[js.Any] = js.undefined
  var onContextMenu: js.UndefOr[js.Any] = js.undefined
  var onContextMenuCapture: js.UndefOr[js.Any] = js.undefined
  var onCopy: js.UndefOr[js.Any] = js.undefined
  var onCopyCapture: js.UndefOr[js.Any] = js.undefined
  var onCut: js.UndefOr[js.Any] = js.undefined
  var onCutCapture: js.UndefOr[js.Any] = js.undefined
  var onDoubleClick: js.UndefOr[js.Any] = js.undefined
  var onDoubleClickCapture: js.UndefOr[js.Any] = js.undefined
  var onDrag: js.UndefOr[js.Any] = js.undefined
  var onDragCapture: js.UndefOr[js.Any] = js.undefined
  var onDragEnd: js.UndefOr[js.Any] = js.undefined
  var onDragEndCapture: js.UndefOr[js.Any] = js.undefined
  var onDragEnter: js.UndefOr[js.Any] = js.undefined
  var onDragEnterCapture: js.UndefOr[js.Any] = js.undefined
  var onDragExit: js.UndefOr[js.Any] = js.undefined
  var onDragExitCapture: js.UndefOr[js.Any] = js.undefined
  var onDragLeave: js.UndefOr[js.Any] = js.undefined
  var onDragLeaveCapture: js.UndefOr[js.Any] = js.undefined
  var onDragOver: js.UndefOr[js.Any] = js.undefined
  var onDragOverCapture: js.UndefOr[js.Any] = js.undefined
  var onDragStart: js.UndefOr[js.Any] = js.undefined
  var onDragStartCapture: js.UndefOr[js.Any] = js.undefined
  var onDrop: js.UndefOr[js.Any] = js.undefined
  var onDropCapture: js.UndefOr[js.Any] = js.undefined
  var onDurationChange: js.UndefOr[js.Any] = js.undefined
  var onDurationChangeCapture: js.UndefOr[js.Any] = js.undefined
  var onEmptied: js.UndefOr[js.Any] = js.undefined
  var onEmptiedCapture: js.UndefOr[js.Any] = js.undefined
  var onEncrypted: js.UndefOr[js.Any] = js.undefined
  var onEncryptedCapture: js.UndefOr[js.Any] = js.undefined
  var onEnded: js.UndefOr[js.Any] = js.undefined
  var onEndedCapture: js.UndefOr[js.Any] = js.undefined
  var onError: js.UndefOr[js.Any] = js.undefined
  var onErrorCapture: js.UndefOr[js.Any] = js.undefined
  var onFocus: js.UndefOr[js.Any] = js.undefined
  var onFocusCapture: js.UndefOr[js.Any] = js.undefined
  var onGotPointerCapture: js.UndefOr[js.Any] = js.undefined
  var onGotPointerCaptureCapture: js.UndefOr[js.Any] = js.undefined
  var onInput: js.UndefOr[js.Any] = js.undefined
  var onInputCapture: js.UndefOr[js.Any] = js.undefined
  var onInvalid: js.UndefOr[js.Any] = js.undefined
  var onInvalidCapture: js.UndefOr[js.Any] = js.undefined
  var onKeyDown: js.UndefOr[js.Any] = js.undefined
  var onKeyDownCapture: js.UndefOr[js.Any] = js.undefined
  var onKeyPress: js.UndefOr[js.Any] = js.undefined
  var onKeyPressCapture: js.UndefOr[js.Any] = js.undefined
  var onKeyUp: js.UndefOr[js.Any] = js.undefined
  var onKeyUpCapture: js.UndefOr[js.Any] = js.undefined
  var onLoad: js.UndefOr[js.Any] = js.undefined
  var onLoadCapture: js.UndefOr[js.Any] = js.undefined
  var onLoadStart: js.UndefOr[js.Any] = js.undefined
  var onLoadStartCapture: js.UndefOr[js.Any] = js.undefined
  var onLoadedData: js.UndefOr[js.Any] = js.undefined
  var onLoadedDataCapture: js.UndefOr[js.Any] = js.undefined
  var onLoadedMetadata: js.UndefOr[js.Any] = js.undefined
  var onLoadedMetadataCapture: js.UndefOr[js.Any] = js.undefined
  var onLostPointerCapture: js.UndefOr[js.Any] = js.undefined
  var onLostPointerCaptureCapture: js.UndefOr[js.Any] = js.undefined
  var onMouseDown: js.UndefOr[js.Any] = js.undefined
  var onMouseDownCapture: js.UndefOr[js.Any] = js.undefined
  var onMouseEnter: js.UndefOr[js.Any] = js.undefined
  var onMouseLeave: js.UndefOr[js.Any] = js.undefined
  var onMouseMove: js.UndefOr[js.Any] = js.undefined
  var onMouseMoveCapture: js.UndefOr[js.Any] = js.undefined
  var onMouseOut: js.UndefOr[js.Any] = js.undefined
  var onMouseOutCapture: js.UndefOr[js.Any] = js.undefined
  var onMouseOver: js.UndefOr[js.Any] = js.undefined
  var onMouseOverCapture: js.UndefOr[js.Any] = js.undefined
  var onMouseUp: js.UndefOr[js.Any] = js.undefined
  var onMouseUpCapture: js.UndefOr[js.Any] = js.undefined
  var onPaste: js.UndefOr[js.Any] = js.undefined
  var onPasteCapture: js.UndefOr[js.Any] = js.undefined
  var onPause: js.UndefOr[js.Any] = js.undefined
  var onPauseCapture: js.UndefOr[js.Any] = js.undefined
  var onPlay: js.UndefOr[js.Any] = js.undefined
  var onPlayCapture: js.UndefOr[js.Any] = js.undefined
  var onPlaying: js.UndefOr[js.Any] = js.undefined
  var onPlayingCapture: js.UndefOr[js.Any] = js.undefined
  var onPointerCancel: js.UndefOr[js.Any] = js.undefined
  var onPointerCancelCapture: js.UndefOr[js.Any] = js.undefined
  var onPointerDown: js.UndefOr[js.Any] = js.undefined
  var onPointerDownCapture: js.UndefOr[js.Any] = js.undefined
  var onPointerEnter: js.UndefOr[js.Any] = js.undefined
  var onPointerEnterCapture: js.UndefOr[js.Any] = js.undefined
  var onPointerLeave: js.UndefOr[js.Any] = js.undefined
  var onPointerLeaveCapture: js.UndefOr[js.Any] = js.undefined
  var onPointerMove: js.UndefOr[js.Any] = js.undefined
  var onPointerMoveCapture: js.UndefOr[js.Any] = js.undefined
  var onPointerOut: js.UndefOr[js.Any] = js.undefined
  var onPointerOutCapture: js.UndefOr[js.Any] = js.undefined
  var onPointerOver: js.UndefOr[js.Any] = js.undefined
  var onPointerOverCapture: js.UndefOr[js.Any] = js.undefined
  var onPointerUp: js.UndefOr[js.Any] = js.undefined
  var onPointerUpCapture: js.UndefOr[js.Any] = js.undefined
  var onProgress: js.UndefOr[js.Any] = js.undefined
  var onProgressCapture: js.UndefOr[js.Any] = js.undefined
  var onRateChange: js.UndefOr[js.Any] = js.undefined
  var onRateChangeCapture: js.UndefOr[js.Any] = js.undefined
  var onReset: js.UndefOr[js.Any] = js.undefined
  var onResetCapture: js.UndefOr[js.Any] = js.undefined
  var onScroll: js.UndefOr[js.Any] = js.undefined
  var onScrollCapture: js.UndefOr[js.Any] = js.undefined
  var onSeeked: js.UndefOr[js.Any] = js.undefined
  var onSeekedCapture: js.UndefOr[js.Any] = js.undefined
  var onSeeking: js.UndefOr[js.Any] = js.undefined
  var onSeekingCapture: js.UndefOr[js.Any] = js.undefined
  var onSelect: js.UndefOr[js.Any] = js.undefined
  var onSelectCapture: js.UndefOr[js.Any] = js.undefined
  var onStalled: js.UndefOr[js.Any] = js.undefined
  var onStalledCapture: js.UndefOr[js.Any] = js.undefined
  var onSubmit: js.UndefOr[js.Any] = js.undefined
  var onSubmitCapture: js.UndefOr[js.Any] = js.undefined
  var onSuspend: js.UndefOr[js.Any] = js.undefined
  var onSuspendCapture: js.UndefOr[js.Any] = js.undefined
  var onTimeUpdate: js.UndefOr[js.Any] = js.undefined
  var onTimeUpdateCapture: js.UndefOr[js.Any] = js.undefined
  var onTouchCancel: js.UndefOr[js.Any] = js.undefined
  var onTouchCancelCapture: js.UndefOr[js.Any] = js.undefined
  var onTouchEnd: js.UndefOr[js.Any] = js.undefined
  var onTouchEndCapture: js.UndefOr[js.Any] = js.undefined
  var onTouchMove: js.UndefOr[js.Any] = js.undefined
  var onTouchMoveCapture: js.UndefOr[js.Any] = js.undefined
  var onTouchStart: js.UndefOr[js.Any] = js.undefined
  var onTouchStartCapture: js.UndefOr[js.Any] = js.undefined
  var onTransitionEnd: js.UndefOr[js.Any] = js.undefined
  var onTransitionEndCapture: js.UndefOr[js.Any] = js.undefined
  var onVolumeChange: js.UndefOr[js.Any] = js.undefined
  var onVolumeChangeCapture: js.UndefOr[js.Any] = js.undefined
  var onWaiting: js.UndefOr[js.Any] = js.undefined
  var onWaitingCapture: js.UndefOr[js.Any] = js.undefined
  var onWheel: js.UndefOr[js.Any] = js.undefined
  var onWheelCapture: js.UndefOr[js.Any] = js.undefined
  var open: js.UndefOr[js.Any] = js.undefined
  var optimum: js.UndefOr[js.Any] = js.undefined
  var pattern: js.UndefOr[js.Any] = js.undefined
  var placeholder: js.UndefOr[js.Any] = js.undefined
  var playsInline: js.UndefOr[js.Any] = js.undefined
  var poster: js.UndefOr[js.Any] = js.undefined
  var prefix: js.UndefOr[js.Any] = js.undefined
  var preload: js.UndefOr[js.Any] = js.undefined
  var property: js.UndefOr[js.Any] = js.undefined
  var radioGroup: js.UndefOr[js.Any] = js.undefined
  var readOnly: js.UndefOr[js.Any] = js.undefined
  var ref: js.UndefOr[Ref[HTMLSpanElement]] = js.undefined
  var rel: js.UndefOr[js.Any] = js.undefined
  var required: js.UndefOr[js.Any] = js.undefined
  var resource: js.UndefOr[js.Any] = js.undefined
  var results: js.UndefOr[js.Any] = js.undefined
  var reversed: js.UndefOr[js.Any] = js.undefined
  var role: js.UndefOr[js.Any] = js.undefined
  var rotate: js.UndefOr[js.Any] = js.undefined
  var rowSpan: js.UndefOr[js.Any] = js.undefined
  var rows: js.UndefOr[js.Any] = js.undefined
  var sandbox: js.UndefOr[js.Any] = js.undefined
  var scope: js.UndefOr[js.Any] = js.undefined
  var scoped: js.UndefOr[js.Any] = js.undefined
  var scrolling: js.UndefOr[js.Any] = js.undefined
  var seamless: js.UndefOr[js.Any] = js.undefined
  var security: js.UndefOr[js.Any] = js.undefined
  var selected: js.UndefOr[js.Any] = js.undefined
  var shape: js.UndefOr[js.Any] = js.undefined
  var size: js.UndefOr[js.Any] = js.undefined
  var sizes: js.UndefOr[js.Any] = js.undefined
  var slot: js.UndefOr[js.Any] = js.undefined
  var span: js.UndefOr[js.Any] = js.undefined
  var spellCheck: js.UndefOr[js.Any] = js.undefined
  var spin: js.UndefOr[js.Any] = js.undefined
  var src: js.UndefOr[js.Any] = js.undefined
  var srcDoc: js.UndefOr[js.Any] = js.undefined
  var srcLang: js.UndefOr[js.Any] = js.undefined
  var srcSet: js.UndefOr[js.Any] = js.undefined
  var start: js.UndefOr[js.Any] = js.undefined
  var step: js.UndefOr[js.Any] = js.undefined
  var style: js.UndefOr[js.Any] = js.undefined
  var summary: js.UndefOr[js.Any] = js.undefined
  var suppressContentEditableWarning: js.UndefOr[js.Any] = js.undefined
  var suppressHydrationWarning: js.UndefOr[js.Any] = js.undefined
  var tabIndex: js.UndefOr[js.Any] = js.undefined
  var target: js.UndefOr[js.Any] = js.undefined
  var title: js.UndefOr[js.Any] = js.undefined
  var translate: js.UndefOr[js.Any] = js.undefined
  var twoToneColor: js.UndefOr[js.Any] = js.undefined
  var `type`: js.UndefOr[js.Any] = js.undefined
  var typeof: js.UndefOr[js.Any] = js.undefined
  var unselectable: js.UndefOr[js.Any] = js.undefined
  var useMap: js.UndefOr[js.Any] = js.undefined
  var value: js.UndefOr[js.Any] = js.undefined
  var vocab: js.UndefOr[js.Any] = js.undefined
  var width: js.UndefOr[js.Any] = js.undefined
  var wmode: js.UndefOr[js.Any] = js.undefined
  var wrap: js.UndefOr[js.Any] = js.undefined
}

object Pickanychildrensizeciteda {
  @scala.inline
  def apply(
    about: js.Any = null,
    accept: js.Any = null,
    acceptCharset: js.Any = null,
    accessKey: js.Any = null,
    action: js.Any = null,
    allowFullScreen: js.Any = null,
    allowTransparency: js.Any = null,
    alt: js.Any = null,
    `aria-activedescendant`: js.Any = null,
    `aria-atomic`: js.Any = null,
    `aria-autocomplete`: js.Any = null,
    `aria-busy`: js.Any = null,
    `aria-checked`: js.Any = null,
    `aria-colcount`: js.Any = null,
    `aria-colindex`: js.Any = null,
    `aria-colspan`: js.Any = null,
    `aria-controls`: js.Any = null,
    `aria-current`: js.Any = null,
    `aria-describedby`: js.Any = null,
    `aria-details`: js.Any = null,
    `aria-disabled`: js.Any = null,
    `aria-dropeffect`: js.Any = null,
    `aria-errormessage`: js.Any = null,
    `aria-expanded`: js.Any = null,
    `aria-flowto`: js.Any = null,
    `aria-grabbed`: js.Any = null,
    `aria-haspopup`: js.Any = null,
    `aria-hidden`: js.Any = null,
    `aria-invalid`: js.Any = null,
    `aria-keyshortcuts`: js.Any = null,
    `aria-label`: js.Any = null,
    `aria-labelledby`: js.Any = null,
    `aria-level`: js.Any = null,
    `aria-live`: js.Any = null,
    `aria-modal`: js.Any = null,
    `aria-multiline`: js.Any = null,
    `aria-multiselectable`: js.Any = null,
    `aria-orientation`: js.Any = null,
    `aria-owns`: js.Any = null,
    `aria-placeholder`: js.Any = null,
    `aria-posinset`: js.Any = null,
    `aria-pressed`: js.Any = null,
    `aria-readonly`: js.Any = null,
    `aria-relevant`: js.Any = null,
    `aria-required`: js.Any = null,
    `aria-roledescription`: js.Any = null,
    `aria-rowcount`: js.Any = null,
    `aria-rowindex`: js.Any = null,
    `aria-rowspan`: js.Any = null,
    `aria-selected`: js.Any = null,
    `aria-setsize`: js.Any = null,
    `aria-sort`: js.Any = null,
    `aria-valuemax`: js.Any = null,
    `aria-valuemin`: js.Any = null,
    `aria-valuenow`: js.Any = null,
    `aria-valuetext`: js.Any = null,
    as: js.Any = null,
    async: js.Any = null,
    autoCapitalize: js.Any = null,
    autoComplete: js.Any = null,
    autoCorrect: js.Any = null,
    autoFocus: js.Any = null,
    autoPlay: js.Any = null,
    autoSave: js.Any = null,
    capture: js.Any = null,
    cellPadding: js.Any = null,
    cellSpacing: js.Any = null,
    challenge: js.Any = null,
    charSet: js.Any = null,
    checked: js.Any = null,
    children: js.Any = null,
    cite: js.Any = null,
    classID: js.Any = null,
    className: js.Any = null,
    colSpan: js.Any = null,
    color: js.Any = null,
    cols: js.Any = null,
    content: js.Any = null,
    contentEditable: js.Any = null,
    contextMenu: js.Any = null,
    controls: js.Any = null,
    coords: js.Any = null,
    crossOrigin: js.Any = null,
    dangerouslySetInnerHTML: js.Any = null,
    data: js.Any = null,
    datatype: js.Any = null,
    dateTime: js.Any = null,
    default: js.Any = null,
    defaultChecked: js.Any = null,
    defaultValue: js.Any = null,
    defer: js.Any = null,
    dir: js.Any = null,
    disabled: js.Any = null,
    download: js.Any = null,
    draggable: js.Any = null,
    encType: js.Any = null,
    form: js.Any = null,
    formAction: js.Any = null,
    formEncType: js.Any = null,
    formMethod: js.Any = null,
    formNoValidate: js.Any = null,
    formTarget: js.Any = null,
    frameBorder: js.Any = null,
    headers: js.Any = null,
    height: js.Any = null,
    hidden: js.Any = null,
    high: js.Any = null,
    href: js.Any = null,
    hrefLang: js.Any = null,
    htmlFor: js.Any = null,
    httpEquiv: js.Any = null,
    id: js.Any = null,
    inlist: js.Any = null,
    inputMode: js.Any = null,
    integrity: js.Any = null,
    is: js.Any = null,
    itemID: js.Any = null,
    itemProp: js.Any = null,
    itemRef: js.Any = null,
    itemScope: js.Any = null,
    itemType: js.Any = null,
    key: js.Any with Key = null,
    keyParams: js.Any = null,
    keyType: js.Any = null,
    kind: js.Any = null,
    label: js.Any = null,
    lang: js.Any = null,
    list: js.Any = null,
    loop: js.Any = null,
    low: js.Any = null,
    manifest: js.Any = null,
    marginHeight: js.Any = null,
    marginWidth: js.Any = null,
    max: js.Any = null,
    maxLength: js.Any = null,
    media: js.Any = null,
    mediaGroup: js.Any = null,
    method: js.Any = null,
    min: js.Any = null,
    minLength: js.Any = null,
    multiple: js.Any = null,
    muted: js.Any = null,
    name: js.Any = null,
    noValidate: js.Any = null,
    nonce: js.Any = null,
    onAbort: js.Any = null,
    onAbortCapture: js.Any = null,
    onAnimationEnd: js.Any = null,
    onAnimationEndCapture: js.Any = null,
    onAnimationIteration: js.Any = null,
    onAnimationIterationCapture: js.Any = null,
    onAnimationStart: js.Any = null,
    onAnimationStartCapture: js.Any = null,
    onAuxClick: js.Any = null,
    onAuxClickCapture: js.Any = null,
    onBeforeInput: js.Any = null,
    onBeforeInputCapture: js.Any = null,
    onBlur: js.Any = null,
    onBlurCapture: js.Any = null,
    onCanPlay: js.Any = null,
    onCanPlayCapture: js.Any = null,
    onCanPlayThrough: js.Any = null,
    onCanPlayThroughCapture: js.Any = null,
    onChange: js.Any = null,
    onChangeCapture: js.Any = null,
    onClick: js.Any = null,
    onClickCapture: js.Any = null,
    onCompositionEnd: js.Any = null,
    onCompositionEndCapture: js.Any = null,
    onCompositionStart: js.Any = null,
    onCompositionStartCapture: js.Any = null,
    onCompositionUpdate: js.Any = null,
    onCompositionUpdateCapture: js.Any = null,
    onContextMenu: js.Any = null,
    onContextMenuCapture: js.Any = null,
    onCopy: js.Any = null,
    onCopyCapture: js.Any = null,
    onCut: js.Any = null,
    onCutCapture: js.Any = null,
    onDoubleClick: js.Any = null,
    onDoubleClickCapture: js.Any = null,
    onDrag: js.Any = null,
    onDragCapture: js.Any = null,
    onDragEnd: js.Any = null,
    onDragEndCapture: js.Any = null,
    onDragEnter: js.Any = null,
    onDragEnterCapture: js.Any = null,
    onDragExit: js.Any = null,
    onDragExitCapture: js.Any = null,
    onDragLeave: js.Any = null,
    onDragLeaveCapture: js.Any = null,
    onDragOver: js.Any = null,
    onDragOverCapture: js.Any = null,
    onDragStart: js.Any = null,
    onDragStartCapture: js.Any = null,
    onDrop: js.Any = null,
    onDropCapture: js.Any = null,
    onDurationChange: js.Any = null,
    onDurationChangeCapture: js.Any = null,
    onEmptied: js.Any = null,
    onEmptiedCapture: js.Any = null,
    onEncrypted: js.Any = null,
    onEncryptedCapture: js.Any = null,
    onEnded: js.Any = null,
    onEndedCapture: js.Any = null,
    onError: js.Any = null,
    onErrorCapture: js.Any = null,
    onFocus: js.Any = null,
    onFocusCapture: js.Any = null,
    onGotPointerCapture: js.Any = null,
    onGotPointerCaptureCapture: js.Any = null,
    onInput: js.Any = null,
    onInputCapture: js.Any = null,
    onInvalid: js.Any = null,
    onInvalidCapture: js.Any = null,
    onKeyDown: js.Any = null,
    onKeyDownCapture: js.Any = null,
    onKeyPress: js.Any = null,
    onKeyPressCapture: js.Any = null,
    onKeyUp: js.Any = null,
    onKeyUpCapture: js.Any = null,
    onLoad: js.Any = null,
    onLoadCapture: js.Any = null,
    onLoadStart: js.Any = null,
    onLoadStartCapture: js.Any = null,
    onLoadedData: js.Any = null,
    onLoadedDataCapture: js.Any = null,
    onLoadedMetadata: js.Any = null,
    onLoadedMetadataCapture: js.Any = null,
    onLostPointerCapture: js.Any = null,
    onLostPointerCaptureCapture: js.Any = null,
    onMouseDown: js.Any = null,
    onMouseDownCapture: js.Any = null,
    onMouseEnter: js.Any = null,
    onMouseLeave: js.Any = null,
    onMouseMove: js.Any = null,
    onMouseMoveCapture: js.Any = null,
    onMouseOut: js.Any = null,
    onMouseOutCapture: js.Any = null,
    onMouseOver: js.Any = null,
    onMouseOverCapture: js.Any = null,
    onMouseUp: js.Any = null,
    onMouseUpCapture: js.Any = null,
    onPaste: js.Any = null,
    onPasteCapture: js.Any = null,
    onPause: js.Any = null,
    onPauseCapture: js.Any = null,
    onPlay: js.Any = null,
    onPlayCapture: js.Any = null,
    onPlaying: js.Any = null,
    onPlayingCapture: js.Any = null,
    onPointerCancel: js.Any = null,
    onPointerCancelCapture: js.Any = null,
    onPointerDown: js.Any = null
  ): Pickanychildrensizeciteda = {
    val __obj = js.Dynamic.literal()
    if (about != null) __obj.updateDynamic("about")(about.asInstanceOf[js.Any])
    if (accept != null) __obj.updateDynamic("accept")(accept.asInstanceOf[js.Any])
    if (acceptCharset != null) __obj.updateDynamic("acceptCharset")(acceptCharset.asInstanceOf[js.Any])
    if (accessKey != null) __obj.updateDynamic("accessKey")(accessKey.asInstanceOf[js.Any])
    if (action != null) __obj.updateDynamic("action")(action.asInstanceOf[js.Any])
    if (allowFullScreen != null) __obj.updateDynamic("allowFullScreen")(allowFullScreen.asInstanceOf[js.Any])
    if (allowTransparency != null) __obj.updateDynamic("allowTransparency")(allowTransparency.asInstanceOf[js.Any])
    if (alt != null) __obj.updateDynamic("alt")(alt.asInstanceOf[js.Any])
    if (`aria-activedescendant` != null) __obj.updateDynamic("aria-activedescendant")(`aria-activedescendant`.asInstanceOf[js.Any])
    if (`aria-atomic` != null) __obj.updateDynamic("aria-atomic")(`aria-atomic`.asInstanceOf[js.Any])
    if (`aria-autocomplete` != null) __obj.updateDynamic("aria-autocomplete")(`aria-autocomplete`.asInstanceOf[js.Any])
    if (`aria-busy` != null) __obj.updateDynamic("aria-busy")(`aria-busy`.asInstanceOf[js.Any])
    if (`aria-checked` != null) __obj.updateDynamic("aria-checked")(`aria-checked`.asInstanceOf[js.Any])
    if (`aria-colcount` != null) __obj.updateDynamic("aria-colcount")(`aria-colcount`.asInstanceOf[js.Any])
    if (`aria-colindex` != null) __obj.updateDynamic("aria-colindex")(`aria-colindex`.asInstanceOf[js.Any])
    if (`aria-colspan` != null) __obj.updateDynamic("aria-colspan")(`aria-colspan`.asInstanceOf[js.Any])
    if (`aria-controls` != null) __obj.updateDynamic("aria-controls")(`aria-controls`.asInstanceOf[js.Any])
    if (`aria-current` != null) __obj.updateDynamic("aria-current")(`aria-current`.asInstanceOf[js.Any])
    if (`aria-describedby` != null) __obj.updateDynamic("aria-describedby")(`aria-describedby`.asInstanceOf[js.Any])
    if (`aria-details` != null) __obj.updateDynamic("aria-details")(`aria-details`.asInstanceOf[js.Any])
    if (`aria-disabled` != null) __obj.updateDynamic("aria-disabled")(`aria-disabled`.asInstanceOf[js.Any])
    if (`aria-dropeffect` != null) __obj.updateDynamic("aria-dropeffect")(`aria-dropeffect`.asInstanceOf[js.Any])
    if (`aria-errormessage` != null) __obj.updateDynamic("aria-errormessage")(`aria-errormessage`.asInstanceOf[js.Any])
    if (`aria-expanded` != null) __obj.updateDynamic("aria-expanded")(`aria-expanded`.asInstanceOf[js.Any])
    if (`aria-flowto` != null) __obj.updateDynamic("aria-flowto")(`aria-flowto`.asInstanceOf[js.Any])
    if (`aria-grabbed` != null) __obj.updateDynamic("aria-grabbed")(`aria-grabbed`.asInstanceOf[js.Any])
    if (`aria-haspopup` != null) __obj.updateDynamic("aria-haspopup")(`aria-haspopup`.asInstanceOf[js.Any])
    if (`aria-hidden` != null) __obj.updateDynamic("aria-hidden")(`aria-hidden`.asInstanceOf[js.Any])
    if (`aria-invalid` != null) __obj.updateDynamic("aria-invalid")(`aria-invalid`.asInstanceOf[js.Any])
    if (`aria-keyshortcuts` != null) __obj.updateDynamic("aria-keyshortcuts")(`aria-keyshortcuts`.asInstanceOf[js.Any])
    if (`aria-label` != null) __obj.updateDynamic("aria-label")(`aria-label`.asInstanceOf[js.Any])
    if (`aria-labelledby` != null) __obj.updateDynamic("aria-labelledby")(`aria-labelledby`.asInstanceOf[js.Any])
    if (`aria-level` != null) __obj.updateDynamic("aria-level")(`aria-level`.asInstanceOf[js.Any])
    if (`aria-live` != null) __obj.updateDynamic("aria-live")(`aria-live`.asInstanceOf[js.Any])
    if (`aria-modal` != null) __obj.updateDynamic("aria-modal")(`aria-modal`.asInstanceOf[js.Any])
    if (`aria-multiline` != null) __obj.updateDynamic("aria-multiline")(`aria-multiline`.asInstanceOf[js.Any])
    if (`aria-multiselectable` != null) __obj.updateDynamic("aria-multiselectable")(`aria-multiselectable`.asInstanceOf[js.Any])
    if (`aria-orientation` != null) __obj.updateDynamic("aria-orientation")(`aria-orientation`.asInstanceOf[js.Any])
    if (`aria-owns` != null) __obj.updateDynamic("aria-owns")(`aria-owns`.asInstanceOf[js.Any])
    if (`aria-placeholder` != null) __obj.updateDynamic("aria-placeholder")(`aria-placeholder`.asInstanceOf[js.Any])
    if (`aria-posinset` != null) __obj.updateDynamic("aria-posinset")(`aria-posinset`.asInstanceOf[js.Any])
    if (`aria-pressed` != null) __obj.updateDynamic("aria-pressed")(`aria-pressed`.asInstanceOf[js.Any])
    if (`aria-readonly` != null) __obj.updateDynamic("aria-readonly")(`aria-readonly`.asInstanceOf[js.Any])
    if (`aria-relevant` != null) __obj.updateDynamic("aria-relevant")(`aria-relevant`.asInstanceOf[js.Any])
    if (`aria-required` != null) __obj.updateDynamic("aria-required")(`aria-required`.asInstanceOf[js.Any])
    if (`aria-roledescription` != null) __obj.updateDynamic("aria-roledescription")(`aria-roledescription`.asInstanceOf[js.Any])
    if (`aria-rowcount` != null) __obj.updateDynamic("aria-rowcount")(`aria-rowcount`.asInstanceOf[js.Any])
    if (`aria-rowindex` != null) __obj.updateDynamic("aria-rowindex")(`aria-rowindex`.asInstanceOf[js.Any])
    if (`aria-rowspan` != null) __obj.updateDynamic("aria-rowspan")(`aria-rowspan`.asInstanceOf[js.Any])
    if (`aria-selected` != null) __obj.updateDynamic("aria-selected")(`aria-selected`.asInstanceOf[js.Any])
    if (`aria-setsize` != null) __obj.updateDynamic("aria-setsize")(`aria-setsize`.asInstanceOf[js.Any])
    if (`aria-sort` != null) __obj.updateDynamic("aria-sort")(`aria-sort`.asInstanceOf[js.Any])
    if (`aria-valuemax` != null) __obj.updateDynamic("aria-valuemax")(`aria-valuemax`.asInstanceOf[js.Any])
    if (`aria-valuemin` != null) __obj.updateDynamic("aria-valuemin")(`aria-valuemin`.asInstanceOf[js.Any])
    if (`aria-valuenow` != null) __obj.updateDynamic("aria-valuenow")(`aria-valuenow`.asInstanceOf[js.Any])
    if (`aria-valuetext` != null) __obj.updateDynamic("aria-valuetext")(`aria-valuetext`.asInstanceOf[js.Any])
    if (as != null) __obj.updateDynamic("as")(as.asInstanceOf[js.Any])
    if (async != null) __obj.updateDynamic("async")(async.asInstanceOf[js.Any])
    if (autoCapitalize != null) __obj.updateDynamic("autoCapitalize")(autoCapitalize.asInstanceOf[js.Any])
    if (autoComplete != null) __obj.updateDynamic("autoComplete")(autoComplete.asInstanceOf[js.Any])
    if (autoCorrect != null) __obj.updateDynamic("autoCorrect")(autoCorrect.asInstanceOf[js.Any])
    if (autoFocus != null) __obj.updateDynamic("autoFocus")(autoFocus.asInstanceOf[js.Any])
    if (autoPlay != null) __obj.updateDynamic("autoPlay")(autoPlay.asInstanceOf[js.Any])
    if (autoSave != null) __obj.updateDynamic("autoSave")(autoSave.asInstanceOf[js.Any])
    if (capture != null) __obj.updateDynamic("capture")(capture.asInstanceOf[js.Any])
    if (cellPadding != null) __obj.updateDynamic("cellPadding")(cellPadding.asInstanceOf[js.Any])
    if (cellSpacing != null) __obj.updateDynamic("cellSpacing")(cellSpacing.asInstanceOf[js.Any])
    if (challenge != null) __obj.updateDynamic("challenge")(challenge.asInstanceOf[js.Any])
    if (charSet != null) __obj.updateDynamic("charSet")(charSet.asInstanceOf[js.Any])
    if (checked != null) __obj.updateDynamic("checked")(checked.asInstanceOf[js.Any])
    if (children != null) __obj.updateDynamic("children")(children.asInstanceOf[js.Any])
    if (cite != null) __obj.updateDynamic("cite")(cite.asInstanceOf[js.Any])
    if (classID != null) __obj.updateDynamic("classID")(classID.asInstanceOf[js.Any])
    if (className != null) __obj.updateDynamic("className")(className.asInstanceOf[js.Any])
    if (colSpan != null) __obj.updateDynamic("colSpan")(colSpan.asInstanceOf[js.Any])
    if (color != null) __obj.updateDynamic("color")(color.asInstanceOf[js.Any])
    if (cols != null) __obj.updateDynamic("cols")(cols.asInstanceOf[js.Any])
    if (content != null) __obj.updateDynamic("content")(content.asInstanceOf[js.Any])
    if (contentEditable != null) __obj.updateDynamic("contentEditable")(contentEditable.asInstanceOf[js.Any])
    if (contextMenu != null) __obj.updateDynamic("contextMenu")(contextMenu.asInstanceOf[js.Any])
    if (controls != null) __obj.updateDynamic("controls")(controls.asInstanceOf[js.Any])
    if (coords != null) __obj.updateDynamic("coords")(coords.asInstanceOf[js.Any])
    if (crossOrigin != null) __obj.updateDynamic("crossOrigin")(crossOrigin.asInstanceOf[js.Any])
    if (dangerouslySetInnerHTML != null) __obj.updateDynamic("dangerouslySetInnerHTML")(dangerouslySetInnerHTML.asInstanceOf[js.Any])
    if (data != null) __obj.updateDynamic("data")(data.asInstanceOf[js.Any])
    if (datatype != null) __obj.updateDynamic("datatype")(datatype.asInstanceOf[js.Any])
    if (dateTime != null) __obj.updateDynamic("dateTime")(dateTime.asInstanceOf[js.Any])
    if (default != null) __obj.updateDynamic("default")(default.asInstanceOf[js.Any])
    if (defaultChecked != null) __obj.updateDynamic("defaultChecked")(defaultChecked.asInstanceOf[js.Any])
    if (defaultValue != null) __obj.updateDynamic("defaultValue")(defaultValue.asInstanceOf[js.Any])
    if (defer != null) __obj.updateDynamic("defer")(defer.asInstanceOf[js.Any])
    if (dir != null) __obj.updateDynamic("dir")(dir.asInstanceOf[js.Any])
    if (disabled != null) __obj.updateDynamic("disabled")(disabled.asInstanceOf[js.Any])
    if (download != null) __obj.updateDynamic("download")(download.asInstanceOf[js.Any])
    if (draggable != null) __obj.updateDynamic("draggable")(draggable.asInstanceOf[js.Any])
    if (encType != null) __obj.updateDynamic("encType")(encType.asInstanceOf[js.Any])
    if (form != null) __obj.updateDynamic("form")(form.asInstanceOf[js.Any])
    if (formAction != null) __obj.updateDynamic("formAction")(formAction.asInstanceOf[js.Any])
    if (formEncType != null) __obj.updateDynamic("formEncType")(formEncType.asInstanceOf[js.Any])
    if (formMethod != null) __obj.updateDynamic("formMethod")(formMethod.asInstanceOf[js.Any])
    if (formNoValidate != null) __obj.updateDynamic("formNoValidate")(formNoValidate.asInstanceOf[js.Any])
    if (formTarget != null) __obj.updateDynamic("formTarget")(formTarget.asInstanceOf[js.Any])
    if (frameBorder != null) __obj.updateDynamic("frameBorder")(frameBorder.asInstanceOf[js.Any])
    if (headers != null) __obj.updateDynamic("headers")(headers.asInstanceOf[js.Any])
    if (height != null) __obj.updateDynamic("height")(height.asInstanceOf[js.Any])
    if (hidden != null) __obj.updateDynamic("hidden")(hidden.asInstanceOf[js.Any])
    if (high != null) __obj.updateDynamic("high")(high.asInstanceOf[js.Any])
    if (href != null) __obj.updateDynamic("href")(href.asInstanceOf[js.Any])
    if (hrefLang != null) __obj.updateDynamic("hrefLang")(hrefLang.asInstanceOf[js.Any])
    if (htmlFor != null) __obj.updateDynamic("htmlFor")(htmlFor.asInstanceOf[js.Any])
    if (httpEquiv != null) __obj.updateDynamic("httpEquiv")(httpEquiv.asInstanceOf[js.Any])
    if (id != null) __obj.updateDynamic("id")(id.asInstanceOf[js.Any])
    if (inlist != null) __obj.updateDynamic("inlist")(inlist.asInstanceOf[js.Any])
    if (inputMode != null) __obj.updateDynamic("inputMode")(inputMode.asInstanceOf[js.Any])
    if (integrity != null) __obj.updateDynamic("integrity")(integrity.asInstanceOf[js.Any])
    if (is != null) __obj.updateDynamic("is")(is.asInstanceOf[js.Any])
    if (itemID != null) __obj.updateDynamic("itemID")(itemID.asInstanceOf[js.Any])
    if (itemProp != null) __obj.updateDynamic("itemProp")(itemProp.asInstanceOf[js.Any])
    if (itemRef != null) __obj.updateDynamic("itemRef")(itemRef.asInstanceOf[js.Any])
    if (itemScope != null) __obj.updateDynamic("itemScope")(itemScope.asInstanceOf[js.Any])
    if (itemType != null) __obj.updateDynamic("itemType")(itemType.asInstanceOf[js.Any])
    if (key != null) __obj.updateDynamic("key")(key.asInstanceOf[js.Any])
    if (keyParams != null) __obj.updateDynamic("keyParams")(keyParams.asInstanceOf[js.Any])
    if (keyType != null) __obj.updateDynamic("keyType")(keyType.asInstanceOf[js.Any])
    if (kind != null) __obj.updateDynamic("kind")(kind.asInstanceOf[js.Any])
    if (label != null) __obj.updateDynamic("label")(label.asInstanceOf[js.Any])
    if (lang != null) __obj.updateDynamic("lang")(lang.asInstanceOf[js.Any])
    if (list != null) __obj.updateDynamic("list")(list.asInstanceOf[js.Any])
    if (loop != null) __obj.updateDynamic("loop")(loop.asInstanceOf[js.Any])
    if (low != null) __obj.updateDynamic("low")(low.asInstanceOf[js.Any])
    if (manifest != null) __obj.updateDynamic("manifest")(manifest.asInstanceOf[js.Any])
    if (marginHeight != null) __obj.updateDynamic("marginHeight")(marginHeight.asInstanceOf[js.Any])
    if (marginWidth != null) __obj.updateDynamic("marginWidth")(marginWidth.asInstanceOf[js.Any])
    if (max != null) __obj.updateDynamic("max")(max.asInstanceOf[js.Any])
    if (maxLength != null) __obj.updateDynamic("maxLength")(maxLength.asInstanceOf[js.Any])
    if (media != null) __obj.updateDynamic("media")(media.asInstanceOf[js.Any])
    if (mediaGroup != null) __obj.updateDynamic("mediaGroup")(mediaGroup.asInstanceOf[js.Any])
    if (method != null) __obj.updateDynamic("method")(method.asInstanceOf[js.Any])
    if (min != null) __obj.updateDynamic("min")(min.asInstanceOf[js.Any])
    if (minLength != null) __obj.updateDynamic("minLength")(minLength.asInstanceOf[js.Any])
    if (multiple != null) __obj.updateDynamic("multiple")(multiple.asInstanceOf[js.Any])
    if (muted != null) __obj.updateDynamic("muted")(muted.asInstanceOf[js.Any])
    if (name != null) __obj.updateDynamic("name")(name.asInstanceOf[js.Any])
    if (noValidate != null) __obj.updateDynamic("noValidate")(noValidate.asInstanceOf[js.Any])
    if (nonce != null) __obj.updateDynamic("nonce")(nonce.asInstanceOf[js.Any])
    if (onAbort != null) __obj.updateDynamic("onAbort")(onAbort.asInstanceOf[js.Any])
    if (onAbortCapture != null) __obj.updateDynamic("onAbortCapture")(onAbortCapture.asInstanceOf[js.Any])
    if (onAnimationEnd != null) __obj.updateDynamic("onAnimationEnd")(onAnimationEnd.asInstanceOf[js.Any])
    if (onAnimationEndCapture != null) __obj.updateDynamic("onAnimationEndCapture")(onAnimationEndCapture.asInstanceOf[js.Any])
    if (onAnimationIteration != null) __obj.updateDynamic("onAnimationIteration")(onAnimationIteration.asInstanceOf[js.Any])
    if (onAnimationIterationCapture != null) __obj.updateDynamic("onAnimationIterationCapture")(onAnimationIterationCapture.asInstanceOf[js.Any])
    if (onAnimationStart != null) __obj.updateDynamic("onAnimationStart")(onAnimationStart.asInstanceOf[js.Any])
    if (onAnimationStartCapture != null) __obj.updateDynamic("onAnimationStartCapture")(onAnimationStartCapture.asInstanceOf[js.Any])
    if (onAuxClick != null) __obj.updateDynamic("onAuxClick")(onAuxClick.asInstanceOf[js.Any])
    if (onAuxClickCapture != null) __obj.updateDynamic("onAuxClickCapture")(onAuxClickCapture.asInstanceOf[js.Any])
    if (onBeforeInput != null) __obj.updateDynamic("onBeforeInput")(onBeforeInput.asInstanceOf[js.Any])
    if (onBeforeInputCapture != null) __obj.updateDynamic("onBeforeInputCapture")(onBeforeInputCapture.asInstanceOf[js.Any])
    if (onBlur != null) __obj.updateDynamic("onBlur")(onBlur.asInstanceOf[js.Any])
    if (onBlurCapture != null) __obj.updateDynamic("onBlurCapture")(onBlurCapture.asInstanceOf[js.Any])
    if (onCanPlay != null) __obj.updateDynamic("onCanPlay")(onCanPlay.asInstanceOf[js.Any])
    if (onCanPlayCapture != null) __obj.updateDynamic("onCanPlayCapture")(onCanPlayCapture.asInstanceOf[js.Any])
    if (onCanPlayThrough != null) __obj.updateDynamic("onCanPlayThrough")(onCanPlayThrough.asInstanceOf[js.Any])
    if (onCanPlayThroughCapture != null) __obj.updateDynamic("onCanPlayThroughCapture")(onCanPlayThroughCapture.asInstanceOf[js.Any])
    if (onChange != null) __obj.updateDynamic("onChange")(onChange.asInstanceOf[js.Any])
    if (onChangeCapture != null) __obj.updateDynamic("onChangeCapture")(onChangeCapture.asInstanceOf[js.Any])
    if (onClick != null) __obj.updateDynamic("onClick")(onClick.asInstanceOf[js.Any])
    if (onClickCapture != null) __obj.updateDynamic("onClickCapture")(onClickCapture.asInstanceOf[js.Any])
    if (onCompositionEnd != null) __obj.updateDynamic("onCompositionEnd")(onCompositionEnd.asInstanceOf[js.Any])
    if (onCompositionEndCapture != null) __obj.updateDynamic("onCompositionEndCapture")(onCompositionEndCapture.asInstanceOf[js.Any])
    if (onCompositionStart != null) __obj.updateDynamic("onCompositionStart")(onCompositionStart.asInstanceOf[js.Any])
    if (onCompositionStartCapture != null) __obj.updateDynamic("onCompositionStartCapture")(onCompositionStartCapture.asInstanceOf[js.Any])
    if (onCompositionUpdate != null) __obj.updateDynamic("onCompositionUpdate")(onCompositionUpdate.asInstanceOf[js.Any])
    if (onCompositionUpdateCapture != null) __obj.updateDynamic("onCompositionUpdateCapture")(onCompositionUpdateCapture.asInstanceOf[js.Any])
    if (onContextMenu != null) __obj.updateDynamic("onContextMenu")(onContextMenu.asInstanceOf[js.Any])
    if (onContextMenuCapture != null) __obj.updateDynamic("onContextMenuCapture")(onContextMenuCapture.asInstanceOf[js.Any])
    if (onCopy != null) __obj.updateDynamic("onCopy")(onCopy.asInstanceOf[js.Any])
    if (onCopyCapture != null) __obj.updateDynamic("onCopyCapture")(onCopyCapture.asInstanceOf[js.Any])
    if (onCut != null) __obj.updateDynamic("onCut")(onCut.asInstanceOf[js.Any])
    if (onCutCapture != null) __obj.updateDynamic("onCutCapture")(onCutCapture.asInstanceOf[js.Any])
    if (onDoubleClick != null) __obj.updateDynamic("onDoubleClick")(onDoubleClick.asInstanceOf[js.Any])
    if (onDoubleClickCapture != null) __obj.updateDynamic("onDoubleClickCapture")(onDoubleClickCapture.asInstanceOf[js.Any])
    if (onDrag != null) __obj.updateDynamic("onDrag")(onDrag.asInstanceOf[js.Any])
    if (onDragCapture != null) __obj.updateDynamic("onDragCapture")(onDragCapture.asInstanceOf[js.Any])
    if (onDragEnd != null) __obj.updateDynamic("onDragEnd")(onDragEnd.asInstanceOf[js.Any])
    if (onDragEndCapture != null) __obj.updateDynamic("onDragEndCapture")(onDragEndCapture.asInstanceOf[js.Any])
    if (onDragEnter != null) __obj.updateDynamic("onDragEnter")(onDragEnter.asInstanceOf[js.Any])
    if (onDragEnterCapture != null) __obj.updateDynamic("onDragEnterCapture")(onDragEnterCapture.asInstanceOf[js.Any])
    if (onDragExit != null) __obj.updateDynamic("onDragExit")(onDragExit.asInstanceOf[js.Any])
    if (onDragExitCapture != null) __obj.updateDynamic("onDragExitCapture")(onDragExitCapture.asInstanceOf[js.Any])
    if (onDragLeave != null) __obj.updateDynamic("onDragLeave")(onDragLeave.asInstanceOf[js.Any])
    if (onDragLeaveCapture != null) __obj.updateDynamic("onDragLeaveCapture")(onDragLeaveCapture.asInstanceOf[js.Any])
    if (onDragOver != null) __obj.updateDynamic("onDragOver")(onDragOver.asInstanceOf[js.Any])
    if (onDragOverCapture != null) __obj.updateDynamic("onDragOverCapture")(onDragOverCapture.asInstanceOf[js.Any])
    if (onDragStart != null) __obj.updateDynamic("onDragStart")(onDragStart.asInstanceOf[js.Any])
    if (onDragStartCapture != null) __obj.updateDynamic("onDragStartCapture")(onDragStartCapture.asInstanceOf[js.Any])
    if (onDrop != null) __obj.updateDynamic("onDrop")(onDrop.asInstanceOf[js.Any])
    if (onDropCapture != null) __obj.updateDynamic("onDropCapture")(onDropCapture.asInstanceOf[js.Any])
    if (onDurationChange != null) __obj.updateDynamic("onDurationChange")(onDurationChange.asInstanceOf[js.Any])
    if (onDurationChangeCapture != null) __obj.updateDynamic("onDurationChangeCapture")(onDurationChangeCapture.asInstanceOf[js.Any])
    if (onEmptied != null) __obj.updateDynamic("onEmptied")(onEmptied.asInstanceOf[js.Any])
    if (onEmptiedCapture != null) __obj.updateDynamic("onEmptiedCapture")(onEmptiedCapture.asInstanceOf[js.Any])
    if (onEncrypted != null) __obj.updateDynamic("onEncrypted")(onEncrypted.asInstanceOf[js.Any])
    if (onEncryptedCapture != null) __obj.updateDynamic("onEncryptedCapture")(onEncryptedCapture.asInstanceOf[js.Any])
    if (onEnded != null) __obj.updateDynamic("onEnded")(onEnded.asInstanceOf[js.Any])
    if (onEndedCapture != null) __obj.updateDynamic("onEndedCapture")(onEndedCapture.asInstanceOf[js.Any])
    if (onError != null) __obj.updateDynamic("onError")(onError.asInstanceOf[js.Any])
    if (onErrorCapture != null) __obj.updateDynamic("onErrorCapture")(onErrorCapture.asInstanceOf[js.Any])
    if (onFocus != null) __obj.updateDynamic("onFocus")(onFocus.asInstanceOf[js.Any])
    if (onFocusCapture != null) __obj.updateDynamic("onFocusCapture")(onFocusCapture.asInstanceOf[js.Any])
    if (onGotPointerCapture != null) __obj.updateDynamic("onGotPointerCapture")(onGotPointerCapture.asInstanceOf[js.Any])
    if (onGotPointerCaptureCapture != null) __obj.updateDynamic("onGotPointerCaptureCapture")(onGotPointerCaptureCapture.asInstanceOf[js.Any])
    if (onInput != null) __obj.updateDynamic("onInput")(onInput.asInstanceOf[js.Any])
    if (onInputCapture != null) __obj.updateDynamic("onInputCapture")(onInputCapture.asInstanceOf[js.Any])
    if (onInvalid != null) __obj.updateDynamic("onInvalid")(onInvalid.asInstanceOf[js.Any])
    if (onInvalidCapture != null) __obj.updateDynamic("onInvalidCapture")(onInvalidCapture.asInstanceOf[js.Any])
    if (onKeyDown != null) __obj.updateDynamic("onKeyDown")(onKeyDown.asInstanceOf[js.Any])
    if (onKeyDownCapture != null) __obj.updateDynamic("onKeyDownCapture")(onKeyDownCapture.asInstanceOf[js.Any])
    if (onKeyPress != null) __obj.updateDynamic("onKeyPress")(onKeyPress.asInstanceOf[js.Any])
    if (onKeyPressCapture != null) __obj.updateDynamic("onKeyPressCapture")(onKeyPressCapture.asInstanceOf[js.Any])
    if (onKeyUp != null) __obj.updateDynamic("onKeyUp")(onKeyUp.asInstanceOf[js.Any])
    if (onKeyUpCapture != null) __obj.updateDynamic("onKeyUpCapture")(onKeyUpCapture.asInstanceOf[js.Any])
    if (onLoad != null) __obj.updateDynamic("onLoad")(onLoad.asInstanceOf[js.Any])
    if (onLoadCapture != null) __obj.updateDynamic("onLoadCapture")(onLoadCapture.asInstanceOf[js.Any])
    if (onLoadStart != null) __obj.updateDynamic("onLoadStart")(onLoadStart.asInstanceOf[js.Any])
    if (onLoadStartCapture != null) __obj.updateDynamic("onLoadStartCapture")(onLoadStartCapture.asInstanceOf[js.Any])
    if (onLoadedData != null) __obj.updateDynamic("onLoadedData")(onLoadedData.asInstanceOf[js.Any])
    if (onLoadedDataCapture != null) __obj.updateDynamic("onLoadedDataCapture")(onLoadedDataCapture.asInstanceOf[js.Any])
    if (onLoadedMetadata != null) __obj.updateDynamic("onLoadedMetadata")(onLoadedMetadata.asInstanceOf[js.Any])
    if (onLoadedMetadataCapture != null) __obj.updateDynamic("onLoadedMetadataCapture")(onLoadedMetadataCapture.asInstanceOf[js.Any])
    if (onLostPointerCapture != null) __obj.updateDynamic("onLostPointerCapture")(onLostPointerCapture.asInstanceOf[js.Any])
    if (onLostPointerCaptureCapture != null) __obj.updateDynamic("onLostPointerCaptureCapture")(onLostPointerCaptureCapture.asInstanceOf[js.Any])
    if (onMouseDown != null) __obj.updateDynamic("onMouseDown")(onMouseDown.asInstanceOf[js.Any])
    if (onMouseDownCapture != null) __obj.updateDynamic("onMouseDownCapture")(onMouseDownCapture.asInstanceOf[js.Any])
    if (onMouseEnter != null) __obj.updateDynamic("onMouseEnter")(onMouseEnter.asInstanceOf[js.Any])
    if (onMouseLeave != null) __obj.updateDynamic("onMouseLeave")(onMouseLeave.asInstanceOf[js.Any])
    if (onMouseMove != null) __obj.updateDynamic("onMouseMove")(onMouseMove.asInstanceOf[js.Any])
    if (onMouseMoveCapture != null) __obj.updateDynamic("onMouseMoveCapture")(onMouseMoveCapture.asInstanceOf[js.Any])
    if (onMouseOut != null) __obj.updateDynamic("onMouseOut")(onMouseOut.asInstanceOf[js.Any])
    if (onMouseOutCapture != null) __obj.updateDynamic("onMouseOutCapture")(onMouseOutCapture.asInstanceOf[js.Any])
    if (onMouseOver != null) __obj.updateDynamic("onMouseOver")(onMouseOver.asInstanceOf[js.Any])
    if (onMouseOverCapture != null) __obj.updateDynamic("onMouseOverCapture")(onMouseOverCapture.asInstanceOf[js.Any])
    if (onMouseUp != null) __obj.updateDynamic("onMouseUp")(onMouseUp.asInstanceOf[js.Any])
    if (onMouseUpCapture != null) __obj.updateDynamic("onMouseUpCapture")(onMouseUpCapture.asInstanceOf[js.Any])
    if (onPaste != null) __obj.updateDynamic("onPaste")(onPaste.asInstanceOf[js.Any])
    if (onPasteCapture != null) __obj.updateDynamic("onPasteCapture")(onPasteCapture.asInstanceOf[js.Any])
    if (onPause != null) __obj.updateDynamic("onPause")(onPause.asInstanceOf[js.Any])
    if (onPauseCapture != null) __obj.updateDynamic("onPauseCapture")(onPauseCapture.asInstanceOf[js.Any])
    if (onPlay != null) __obj.updateDynamic("onPlay")(onPlay.asInstanceOf[js.Any])
    if (onPlayCapture != null) __obj.updateDynamic("onPlayCapture")(onPlayCapture.asInstanceOf[js.Any])
    if (onPlaying != null) __obj.updateDynamic("onPlaying")(onPlaying.asInstanceOf[js.Any])
    if (onPlayingCapture != null) __obj.updateDynamic("onPlayingCapture")(onPlayingCapture.asInstanceOf[js.Any])
    if (onPointerCancel != null) __obj.updateDynamic("onPointerCancel")(onPointerCancel.asInstanceOf[js.Any])
    if (onPointerCancelCapture != null) __obj.updateDynamic("onPointerCancelCapture")(onPointerCancelCapture.asInstanceOf[js.Any])
    if (onPointerDown != null) __obj.updateDynamic("onPointerDown")(onPointerDown.asInstanceOf[js.Any])
    __obj.asInstanceOf[Pickanychildrensizeciteda]
  }
}

