package typingsSlinky.semanticUiPopup.SemanticUI

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object PopupSettings {
  type Param = (typingsSlinky.semanticUiPopup.PickImplpopup | typingsSlinky.semanticUiPopup.PickImplexclusive | typingsSlinky.semanticUiPopup.PickImplmovePopup | typingsSlinky.semanticUiPopup.PickImplobserveChanges | typingsSlinky.semanticUiPopup.PickImplboundary | typingsSlinky.semanticUiPopup.PickImplcontext | typingsSlinky.semanticUiPopup.PickImplscrollContext | typingsSlinky.semanticUiPopup.PickImpljitter | typingsSlinky.semanticUiPopup.PickImplposition | typingsSlinky.semanticUiPopup.PickImplinline | typingsSlinky.semanticUiPopup.PickImplpreserve | typingsSlinky.semanticUiPopup.PickImplprefer | typingsSlinky.semanticUiPopup.PickImpllastResort | typingsSlinky.semanticUiPopup.PickImplon | typingsSlinky.semanticUiPopup.PickImpldelay | typingsSlinky.semanticUiPopup.PickImpltransition | typingsSlinky.semanticUiPopup.PickImplduration | typingsSlinky.semanticUiPopup.PickImplsetFluidWidth | typingsSlinky.semanticUiPopup.PickImplhoverable | typingsSlinky.semanticUiPopup.PickImplclosable | typingsSlinky.semanticUiPopup.PickImpladdTouchEvents | typingsSlinky.semanticUiPopup.PickImplhideOnScroll | typingsSlinky.semanticUiPopup.PickImpltarget | typingsSlinky.semanticUiPopup.PickImpldistanceAway | typingsSlinky.semanticUiPopup.PickImploffset | typingsSlinky.semanticUiPopup.PickImplmaxSearchDepth | typingsSlinky.semanticUiPopup.PickImplonCreate | typingsSlinky.semanticUiPopup.PickImplonRemove | typingsSlinky.semanticUiPopup.PickImplonShow | typingsSlinky.semanticUiPopup.PickImplonVisible | typingsSlinky.semanticUiPopup.PickImplonHide | typingsSlinky.semanticUiPopup.PickImplonHidden | typingsSlinky.semanticUiPopup.PickImplonUnplaceable | typingsSlinky.semanticUiPopup.PickImplvariation | typingsSlinky.semanticUiPopup.PickImplcontent | typingsSlinky.semanticUiPopup.PickImpltitle | typingsSlinky.semanticUiPopup.PickImplhtml | typingsSlinky.semanticUiPopup.PickImplselector | typingsSlinky.semanticUiPopup.PickImplmetadata | typingsSlinky.semanticUiPopup.PickImplclassName | typingsSlinky.semanticUiPopup.PickImplerror | typingsSlinky.semanticUiPopup.PickImplnamespace | typingsSlinky.semanticUiPopup.PickImplname | typingsSlinky.semanticUiPopup.PickImplsilent | typingsSlinky.semanticUiPopup.PickImpldebug | typingsSlinky.semanticUiPopup.PickImplperformance | typingsSlinky.semanticUiPopup.PickImplverbose) with typingsSlinky.semanticUiPopup.PartialPickImplkeyofImpl
}
