package typingsSlinky.semanticUiPopup.SemanticUI

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

package object PopupSettings {
  
  type Param = (typingsSlinky.semanticUiPopup.anon.PickImplpopup | typingsSlinky.semanticUiPopup.anon.PickImplexclusive | typingsSlinky.semanticUiPopup.anon.PickImplmovePopup | typingsSlinky.semanticUiPopup.anon.PickImplobserveChanges | typingsSlinky.semanticUiPopup.anon.PickImplboundary | typingsSlinky.semanticUiPopup.anon.PickImplcontext | typingsSlinky.semanticUiPopup.anon.PickImplscrollContext | typingsSlinky.semanticUiPopup.anon.PickImpljitter | typingsSlinky.semanticUiPopup.anon.PickImplposition | typingsSlinky.semanticUiPopup.anon.PickImplinline | typingsSlinky.semanticUiPopup.anon.PickImplpreserve | typingsSlinky.semanticUiPopup.anon.PickImplprefer | typingsSlinky.semanticUiPopup.anon.PickImpllastResort | typingsSlinky.semanticUiPopup.anon.PickImplon | typingsSlinky.semanticUiPopup.anon.PickImpldelay | typingsSlinky.semanticUiPopup.anon.PickImpltransition | typingsSlinky.semanticUiPopup.anon.PickImplduration | typingsSlinky.semanticUiPopup.anon.PickImplsetFluidWidth | typingsSlinky.semanticUiPopup.anon.PickImplhoverable | typingsSlinky.semanticUiPopup.anon.PickImplclosable | typingsSlinky.semanticUiPopup.anon.PickImpladdTouchEvents | typingsSlinky.semanticUiPopup.anon.PickImplhideOnScroll | typingsSlinky.semanticUiPopup.anon.PickImpltarget | typingsSlinky.semanticUiPopup.anon.PickImpldistanceAway | typingsSlinky.semanticUiPopup.anon.PickImploffset | typingsSlinky.semanticUiPopup.anon.PickImplmaxSearchDepth | typingsSlinky.semanticUiPopup.anon.PickImplonCreate | typingsSlinky.semanticUiPopup.anon.PickImplonRemove | typingsSlinky.semanticUiPopup.anon.PickImplonShow | typingsSlinky.semanticUiPopup.anon.PickImplonVisible | typingsSlinky.semanticUiPopup.anon.PickImplonHide | typingsSlinky.semanticUiPopup.anon.PickImplonHidden | typingsSlinky.semanticUiPopup.anon.PickImplonUnplaceable | typingsSlinky.semanticUiPopup.anon.PickImplvariation | typingsSlinky.semanticUiPopup.anon.PickImplcontent | typingsSlinky.semanticUiPopup.anon.PickImpltitle | typingsSlinky.semanticUiPopup.anon.PickImplhtml | typingsSlinky.semanticUiPopup.anon.PickImplselector | typingsSlinky.semanticUiPopup.anon.PickImplmetadata | typingsSlinky.semanticUiPopup.anon.PickImplclassName | typingsSlinky.semanticUiPopup.anon.PickImplerror | typingsSlinky.semanticUiPopup.anon.PickImplnamespace | typingsSlinky.semanticUiPopup.anon.PickImplname | typingsSlinky.semanticUiPopup.anon.PickImplsilent | typingsSlinky.semanticUiPopup.anon.PickImpldebug | typingsSlinky.semanticUiPopup.anon.PickImplperformance | typingsSlinky.semanticUiPopup.anon.PickImplverbose) with typingsSlinky.semanticUiPopup.anon.PartialPickImplkeyofImpl
}
