package typingsSlinky.awsSdkClientCodecommitNode.postCommentForPullRequestExceptionsUnionMod

import typingsSlinky.awsSdkClientCodecommitNode.typesBeforeCommitIdAndAfterCommitIdAreSameExceptionMod.BeforeCommitIdAndAfterCommitIdAreSameException
import typingsSlinky.awsSdkClientCodecommitNode.typesClientRequestTokenRequiredExceptionMod.ClientRequestTokenRequiredException
import typingsSlinky.awsSdkClientCodecommitNode.typesCommentContentRequiredExceptionMod.CommentContentRequiredException
import typingsSlinky.awsSdkClientCodecommitNode.typesCommentContentSizeLimitExceededExceptionMod.CommentContentSizeLimitExceededException
import typingsSlinky.awsSdkClientCodecommitNode.typesCommitDoesNotExistExceptionMod.CommitDoesNotExistException
import typingsSlinky.awsSdkClientCodecommitNode.typesCommitIdRequiredExceptionMod.CommitIdRequiredException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionIntegrityChecksFailedExceptionMod.EncryptionIntegrityChecksFailedException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyAccessDeniedExceptionMod.EncryptionKeyAccessDeniedException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyDisabledExceptionMod.EncryptionKeyDisabledException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyNotFoundExceptionMod.EncryptionKeyNotFoundException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyUnavailableExceptionMod.EncryptionKeyUnavailableException
import typingsSlinky.awsSdkClientCodecommitNode.typesIdempotencyParameterMismatchExceptionMod.IdempotencyParameterMismatchException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidClientRequestTokenExceptionMod.InvalidClientRequestTokenException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidCommitIdExceptionMod.InvalidCommitIdException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidFileLocationExceptionMod.InvalidFileLocationException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidFilePositionExceptionMod.InvalidFilePositionException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidPathExceptionMod.InvalidPathException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidPullRequestIdExceptionMod.InvalidPullRequestIdException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRelativeFileVersionEnumExceptionMod.InvalidRelativeFileVersionEnumException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryNameExceptionMod.InvalidRepositoryNameException
import typingsSlinky.awsSdkClientCodecommitNode.typesPathDoesNotExistExceptionMod.PathDoesNotExistException
import typingsSlinky.awsSdkClientCodecommitNode.typesPathRequiredExceptionMod.PathRequiredException
import typingsSlinky.awsSdkClientCodecommitNode.typesPullRequestDoesNotExistExceptionMod.PullRequestDoesNotExistException
import typingsSlinky.awsSdkClientCodecommitNode.typesPullRequestIdRequiredExceptionMod.PullRequestIdRequiredException
import typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryDoesNotExistExceptionMod.RepositoryDoesNotExistException
import typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryNameRequiredExceptionMod.RepositoryNameRequiredException
import typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryNotAssociatedWithPullRequestExceptionMod.RepositoryNotAssociatedWithPullRequestException
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - typingsSlinky.awsSdkClientCodecommitNode.typesPullRequestDoesNotExistExceptionMod.PullRequestDoesNotExistException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidPullRequestIdExceptionMod.InvalidPullRequestIdException
  - typingsSlinky.awsSdkClientCodecommitNode.typesPullRequestIdRequiredExceptionMod.PullRequestIdRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryNotAssociatedWithPullRequestExceptionMod.RepositoryNotAssociatedWithPullRequestException
  - typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryNameRequiredExceptionMod.RepositoryNameRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryDoesNotExistExceptionMod.RepositoryDoesNotExistException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryNameExceptionMod.InvalidRepositoryNameException
  - typingsSlinky.awsSdkClientCodecommitNode.typesClientRequestTokenRequiredExceptionMod.ClientRequestTokenRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidClientRequestTokenExceptionMod.InvalidClientRequestTokenException
  - typingsSlinky.awsSdkClientCodecommitNode.typesIdempotencyParameterMismatchExceptionMod.IdempotencyParameterMismatchException
  - typingsSlinky.awsSdkClientCodecommitNode.typesCommentContentRequiredExceptionMod.CommentContentRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesCommentContentSizeLimitExceededExceptionMod.CommentContentSizeLimitExceededException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidFileLocationExceptionMod.InvalidFileLocationException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRelativeFileVersionEnumExceptionMod.InvalidRelativeFileVersionEnumException
  - typingsSlinky.awsSdkClientCodecommitNode.typesPathRequiredExceptionMod.PathRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidFilePositionExceptionMod.InvalidFilePositionException
  - typingsSlinky.awsSdkClientCodecommitNode.typesCommitIdRequiredExceptionMod.CommitIdRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidCommitIdExceptionMod.InvalidCommitIdException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionIntegrityChecksFailedExceptionMod.EncryptionIntegrityChecksFailedException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyAccessDeniedExceptionMod.EncryptionKeyAccessDeniedException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyDisabledExceptionMod.EncryptionKeyDisabledException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyNotFoundExceptionMod.EncryptionKeyNotFoundException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyUnavailableExceptionMod.EncryptionKeyUnavailableException
  - typingsSlinky.awsSdkClientCodecommitNode.typesCommitDoesNotExistExceptionMod.CommitDoesNotExistException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidPathExceptionMod.InvalidPathException
  - typingsSlinky.awsSdkClientCodecommitNode.typesPathDoesNotExistExceptionMod.PathDoesNotExistException
  - typingsSlinky.awsSdkClientCodecommitNode.typesBeforeCommitIdAndAfterCommitIdAreSameExceptionMod.BeforeCommitIdAndAfterCommitIdAreSameException
*/
trait PostCommentForPullRequestExceptionsUnion extends js.Object

object PostCommentForPullRequestExceptionsUnion {
  @scala.inline
  implicit def apply(value: BeforeCommitIdAndAfterCommitIdAreSameException): PostCommentForPullRequestExceptionsUnion = value.asInstanceOf[PostCommentForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: ClientRequestTokenRequiredException): PostCommentForPullRequestExceptionsUnion = value.asInstanceOf[PostCommentForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: CommentContentRequiredException): PostCommentForPullRequestExceptionsUnion = value.asInstanceOf[PostCommentForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: CommentContentSizeLimitExceededException): PostCommentForPullRequestExceptionsUnion = value.asInstanceOf[PostCommentForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: CommitDoesNotExistException): PostCommentForPullRequestExceptionsUnion = value.asInstanceOf[PostCommentForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: CommitIdRequiredException): PostCommentForPullRequestExceptionsUnion = value.asInstanceOf[PostCommentForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionIntegrityChecksFailedException): PostCommentForPullRequestExceptionsUnion = value.asInstanceOf[PostCommentForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyAccessDeniedException): PostCommentForPullRequestExceptionsUnion = value.asInstanceOf[PostCommentForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyDisabledException): PostCommentForPullRequestExceptionsUnion = value.asInstanceOf[PostCommentForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyNotFoundException): PostCommentForPullRequestExceptionsUnion = value.asInstanceOf[PostCommentForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyUnavailableException): PostCommentForPullRequestExceptionsUnion = value.asInstanceOf[PostCommentForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: IdempotencyParameterMismatchException): PostCommentForPullRequestExceptionsUnion = value.asInstanceOf[PostCommentForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidClientRequestTokenException): PostCommentForPullRequestExceptionsUnion = value.asInstanceOf[PostCommentForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidCommitIdException): PostCommentForPullRequestExceptionsUnion = value.asInstanceOf[PostCommentForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidFileLocationException): PostCommentForPullRequestExceptionsUnion = value.asInstanceOf[PostCommentForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidFilePositionException): PostCommentForPullRequestExceptionsUnion = value.asInstanceOf[PostCommentForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidPathException): PostCommentForPullRequestExceptionsUnion = value.asInstanceOf[PostCommentForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidPullRequestIdException): PostCommentForPullRequestExceptionsUnion = value.asInstanceOf[PostCommentForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidRelativeFileVersionEnumException): PostCommentForPullRequestExceptionsUnion = value.asInstanceOf[PostCommentForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidRepositoryNameException): PostCommentForPullRequestExceptionsUnion = value.asInstanceOf[PostCommentForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: PathDoesNotExistException): PostCommentForPullRequestExceptionsUnion = value.asInstanceOf[PostCommentForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: PathRequiredException): PostCommentForPullRequestExceptionsUnion = value.asInstanceOf[PostCommentForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: PullRequestDoesNotExistException): PostCommentForPullRequestExceptionsUnion = value.asInstanceOf[PostCommentForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: PullRequestIdRequiredException): PostCommentForPullRequestExceptionsUnion = value.asInstanceOf[PostCommentForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: RepositoryDoesNotExistException): PostCommentForPullRequestExceptionsUnion = value.asInstanceOf[PostCommentForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: RepositoryNameRequiredException): PostCommentForPullRequestExceptionsUnion = value.asInstanceOf[PostCommentForPullRequestExceptionsUnion]
  @scala.inline
  implicit def apply(value: RepositoryNotAssociatedWithPullRequestException): PostCommentForPullRequestExceptionsUnion = value.asInstanceOf[PostCommentForPullRequestExceptionsUnion]
}

