package typingsSlinky.awsSdkClientDynamodbBrowser

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object typesAutoScalingTargetTrackingScalingPolicyConfigurationDescriptionMod {
  type UnmarshalledAutoScalingTargetTrackingScalingPolicyConfigurationDescription = typingsSlinky.awsSdkClientDynamodbBrowser.typesAutoScalingTargetTrackingScalingPolicyConfigurationDescriptionMod.AutoScalingTargetTrackingScalingPolicyConfigurationDescription
}
