package typingsSlinky.arcgisJsApi.algorithmicColorRampMod

import typingsSlinky.arcgisJsApi.esri.AlgorithmicColorRamp
import typingsSlinky.arcgisJsApi.esri.AlgorithmicColorRampProperties
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

@JSImport("esri/tasks/support/AlgorithmicColorRamp", JSImport.Namespace)
@js.native
/**
  * Create an algorithmic color ramp to define the range of colors used in the renderer generated by the GenerateRendererTask.
  *
  * [Read more...](https://developers.arcgis.com/javascript/latest/api-reference/esri-tasks-support-AlgorithmicColorRamp.html)
  */
class Class () extends AlgorithmicColorRamp {
  def this(properties: AlgorithmicColorRampProperties) = this()
}
