package typingsSlinky.googleAppsScript.GoogleAppsScript.YoutubePartner.Schema

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait VideoAdvertisingOption extends js.Object {
  var adBreaks: js.UndefOr[js.Array[AdBreak]] = js.native
  var adFormats: js.UndefOr[js.Array[String]] = js.native
  var autoGeneratedBreaks: js.UndefOr[Boolean] = js.native
  var breakPosition: js.UndefOr[js.Array[String]] = js.native
  var id: js.UndefOr[String] = js.native
  var kind: js.UndefOr[String] = js.native
  var tpAdServerVideoId: js.UndefOr[String] = js.native
  var tpTargetingUrl: js.UndefOr[String] = js.native
  var tpUrlParameters: js.UndefOr[String] = js.native
}

object VideoAdvertisingOption {
  @scala.inline
  def apply(): VideoAdvertisingOption = {
    val __obj = js.Dynamic.literal()
    __obj.asInstanceOf[VideoAdvertisingOption]
  }
  @scala.inline
  implicit class VideoAdvertisingOptionOps[Self <: VideoAdvertisingOption] (val x: Self) extends AnyVal {
    @scala.inline
    def duplicate: Self = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x)).asInstanceOf[Self]
    @scala.inline
    def combineWith[Other <: js.Any](other: Other): Self with Other = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x, other.asInstanceOf[js.Any])).asInstanceOf[Self with Other]
    @scala.inline
    def withAdBreaks(value: js.Array[AdBreak]): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("adBreaks")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutAdBreaks: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("adBreaks")(js.undefined)
        ret
    }
    @scala.inline
    def withAdFormats(value: js.Array[String]): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("adFormats")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutAdFormats: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("adFormats")(js.undefined)
        ret
    }
    @scala.inline
    def withAutoGeneratedBreaks(value: Boolean): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("autoGeneratedBreaks")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutAutoGeneratedBreaks: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("autoGeneratedBreaks")(js.undefined)
        ret
    }
    @scala.inline
    def withBreakPosition(value: js.Array[String]): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("breakPosition")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutBreakPosition: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("breakPosition")(js.undefined)
        ret
    }
    @scala.inline
    def withId(value: String): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("id")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutId: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("id")(js.undefined)
        ret
    }
    @scala.inline
    def withKind(value: String): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("kind")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutKind: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("kind")(js.undefined)
        ret
    }
    @scala.inline
    def withTpAdServerVideoId(value: String): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("tpAdServerVideoId")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutTpAdServerVideoId: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("tpAdServerVideoId")(js.undefined)
        ret
    }
    @scala.inline
    def withTpTargetingUrl(value: String): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("tpTargetingUrl")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutTpTargetingUrl: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("tpTargetingUrl")(js.undefined)
        ret
    }
    @scala.inline
    def withTpUrlParameters(value: String): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("tpUrlParameters")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutTpUrlParameters: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("tpUrlParameters")(js.undefined)
        ret
    }
  }
  
}

