package typingsSlinky.awsSdkClientCodecommitNode.updateCommentExceptionsUnionMod

import typingsSlinky.awsSdkClientCodecommitNode.typesCommentContentRequiredExceptionMod.CommentContentRequiredException
import typingsSlinky.awsSdkClientCodecommitNode.typesCommentContentSizeLimitExceededExceptionMod.CommentContentSizeLimitExceededException
import typingsSlinky.awsSdkClientCodecommitNode.typesCommentDeletedExceptionMod.CommentDeletedException
import typingsSlinky.awsSdkClientCodecommitNode.typesCommentDoesNotExistExceptionMod.CommentDoesNotExistException
import typingsSlinky.awsSdkClientCodecommitNode.typesCommentIdRequiredExceptionMod.CommentIdRequiredException
import typingsSlinky.awsSdkClientCodecommitNode.typesCommentNotCreatedByCallerExceptionMod.CommentNotCreatedByCallerException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidCommentIdExceptionMod.InvalidCommentIdException
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - typingsSlinky.awsSdkClientCodecommitNode.typesCommentContentRequiredExceptionMod.CommentContentRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesCommentContentSizeLimitExceededExceptionMod.CommentContentSizeLimitExceededException
  - typingsSlinky.awsSdkClientCodecommitNode.typesCommentDoesNotExistExceptionMod.CommentDoesNotExistException
  - typingsSlinky.awsSdkClientCodecommitNode.typesCommentIdRequiredExceptionMod.CommentIdRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidCommentIdExceptionMod.InvalidCommentIdException
  - typingsSlinky.awsSdkClientCodecommitNode.typesCommentNotCreatedByCallerExceptionMod.CommentNotCreatedByCallerException
  - typingsSlinky.awsSdkClientCodecommitNode.typesCommentDeletedExceptionMod.CommentDeletedException
*/
trait UpdateCommentExceptionsUnion extends js.Object

object UpdateCommentExceptionsUnion {
  @scala.inline
  implicit def apply(value: CommentContentRequiredException): UpdateCommentExceptionsUnion = value.asInstanceOf[UpdateCommentExceptionsUnion]
  @scala.inline
  implicit def apply(value: CommentContentSizeLimitExceededException): UpdateCommentExceptionsUnion = value.asInstanceOf[UpdateCommentExceptionsUnion]
  @scala.inline
  implicit def apply(value: CommentDeletedException): UpdateCommentExceptionsUnion = value.asInstanceOf[UpdateCommentExceptionsUnion]
  @scala.inline
  implicit def apply(value: CommentDoesNotExistException): UpdateCommentExceptionsUnion = value.asInstanceOf[UpdateCommentExceptionsUnion]
  @scala.inline
  implicit def apply(value: CommentIdRequiredException): UpdateCommentExceptionsUnion = value.asInstanceOf[UpdateCommentExceptionsUnion]
  @scala.inline
  implicit def apply(value: CommentNotCreatedByCallerException): UpdateCommentExceptionsUnion = value.asInstanceOf[UpdateCommentExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidCommentIdException): UpdateCommentExceptionsUnion = value.asInstanceOf[UpdateCommentExceptionsUnion]
}

