package typingsSlinky.awsSdkClientDynamodbNode.restoreTableToPointInTimeExceptionsUnionMod

import typingsSlinky.awsSdkClientDynamodbNode.typesInternalServerErrorMod.InternalServerError
import typingsSlinky.awsSdkClientDynamodbNode.typesInvalidRestoreTimeExceptionMod.InvalidRestoreTimeException
import typingsSlinky.awsSdkClientDynamodbNode.typesLimitExceededExceptionMod.LimitExceededException
import typingsSlinky.awsSdkClientDynamodbNode.typesPointInTimeRecoveryUnavailableExceptionMod.PointInTimeRecoveryUnavailableException
import typingsSlinky.awsSdkClientDynamodbNode.typesTableAlreadyExistsExceptionMod.TableAlreadyExistsException
import typingsSlinky.awsSdkClientDynamodbNode.typesTableInUseExceptionMod.TableInUseException
import typingsSlinky.awsSdkClientDynamodbNode.typesTableNotFoundExceptionMod.TableNotFoundException
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - typingsSlinky.awsSdkClientDynamodbNode.typesTableAlreadyExistsExceptionMod.TableAlreadyExistsException
  - typingsSlinky.awsSdkClientDynamodbNode.typesTableNotFoundExceptionMod.TableNotFoundException
  - typingsSlinky.awsSdkClientDynamodbNode.typesTableInUseExceptionMod.TableInUseException
  - typingsSlinky.awsSdkClientDynamodbNode.typesLimitExceededExceptionMod.LimitExceededException
  - typingsSlinky.awsSdkClientDynamodbNode.typesInvalidRestoreTimeExceptionMod.InvalidRestoreTimeException
  - typingsSlinky.awsSdkClientDynamodbNode.typesPointInTimeRecoveryUnavailableExceptionMod.PointInTimeRecoveryUnavailableException
  - typingsSlinky.awsSdkClientDynamodbNode.typesInternalServerErrorMod.InternalServerError
*/
trait RestoreTableToPointInTimeExceptionsUnion extends js.Object

object RestoreTableToPointInTimeExceptionsUnion {
  @scala.inline
  implicit def apply(value: InternalServerError): RestoreTableToPointInTimeExceptionsUnion = value.asInstanceOf[RestoreTableToPointInTimeExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidRestoreTimeException): RestoreTableToPointInTimeExceptionsUnion = value.asInstanceOf[RestoreTableToPointInTimeExceptionsUnion]
  @scala.inline
  implicit def apply(value: LimitExceededException): RestoreTableToPointInTimeExceptionsUnion = value.asInstanceOf[RestoreTableToPointInTimeExceptionsUnion]
  @scala.inline
  implicit def apply(value: PointInTimeRecoveryUnavailableException): RestoreTableToPointInTimeExceptionsUnion = value.asInstanceOf[RestoreTableToPointInTimeExceptionsUnion]
  @scala.inline
  implicit def apply(value: TableAlreadyExistsException): RestoreTableToPointInTimeExceptionsUnion = value.asInstanceOf[RestoreTableToPointInTimeExceptionsUnion]
  @scala.inline
  implicit def apply(value: TableInUseException): RestoreTableToPointInTimeExceptionsUnion = value.asInstanceOf[RestoreTableToPointInTimeExceptionsUnion]
  @scala.inline
  implicit def apply(value: TableNotFoundException): RestoreTableToPointInTimeExceptionsUnion = value.asInstanceOf[RestoreTableToPointInTimeExceptionsUnion]
}

