package typingsSlinky.awsDashSdk.libConfigUnderscoreServiceUnderscorePlaceholdersMod

import typingsSlinky.awsDashSdk.clientsAccessanalyzerMod.ClientConfiguration
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@JSImport("aws-sdk/lib/config_service_placeholders", "ConfigurationServicePlaceholders")
@js.native
abstract class ConfigurationServicePlaceholders () extends js.Object {
  var accessanalyzer: js.UndefOr[ClientConfiguration] = js.native
  var acm: js.UndefOr[typingsSlinky.awsDashSdk.clientsAcmMod.ClientConfiguration] = js.native
  var acmpca: js.UndefOr[typingsSlinky.awsDashSdk.clientsAcmpcaMod.ClientConfiguration] = js.native
  var alexaforbusiness: js.UndefOr[typingsSlinky.awsDashSdk.clientsAlexaforbusinessMod.ClientConfiguration] = js.native
  var amplify: js.UndefOr[typingsSlinky.awsDashSdk.clientsAmplifyMod.ClientConfiguration] = js.native
  var apigateway: js.UndefOr[typingsSlinky.awsDashSdk.clientsApigatewayMod.ClientConfiguration] = js.native
  var apigatewaymanagementapi: js.UndefOr[typingsSlinky.awsDashSdk.clientsApigatewaymanagementapiMod.ClientConfiguration] = js.native
  var apigatewayv2: js.UndefOr[typingsSlinky.awsDashSdk.clientsApigatewayv2Mod.ClientConfiguration] = js.native
  var appconfig: js.UndefOr[typingsSlinky.awsDashSdk.clientsAppconfigMod.ClientConfiguration] = js.native
  var applicationautoscaling: js.UndefOr[typingsSlinky.awsDashSdk.clientsApplicationautoscalingMod.ClientConfiguration] = js.native
  var applicationinsights: js.UndefOr[typingsSlinky.awsDashSdk.clientsApplicationinsightsMod.ClientConfiguration] = js.native
  var appmesh: js.UndefOr[typingsSlinky.awsDashSdk.clientsAppmeshMod.ClientConfiguration] = js.native
  var appstream: js.UndefOr[typingsSlinky.awsDashSdk.clientsAppstreamMod.ClientConfiguration] = js.native
  var appsync: js.UndefOr[typingsSlinky.awsDashSdk.clientsAppsyncMod.ClientConfiguration] = js.native
  var athena: js.UndefOr[typingsSlinky.awsDashSdk.clientsAthenaMod.ClientConfiguration] = js.native
  var augmentedairuntime: js.UndefOr[typingsSlinky.awsDashSdk.clientsAugmentedairuntimeMod.ClientConfiguration] = js.native
  var autoscaling: js.UndefOr[typingsSlinky.awsDashSdk.clientsAutoscalingMod.ClientConfiguration] = js.native
  var autoscalingplans: js.UndefOr[typingsSlinky.awsDashSdk.clientsAutoscalingplansMod.ClientConfiguration] = js.native
  var backup: js.UndefOr[typingsSlinky.awsDashSdk.clientsBackupMod.ClientConfiguration] = js.native
  var batch: js.UndefOr[typingsSlinky.awsDashSdk.clientsBatchMod.ClientConfiguration] = js.native
  var budgets: js.UndefOr[typingsSlinky.awsDashSdk.clientsBudgetsMod.ClientConfiguration] = js.native
  var chime: js.UndefOr[typingsSlinky.awsDashSdk.clientsChimeMod.ClientConfiguration] = js.native
  var cloud9: js.UndefOr[typingsSlinky.awsDashSdk.clientsCloud9Mod.ClientConfiguration] = js.native
  var clouddirectory: js.UndefOr[typingsSlinky.awsDashSdk.clientsClouddirectoryMod.ClientConfiguration] = js.native
  var cloudformation: js.UndefOr[typingsSlinky.awsDashSdk.clientsCloudformationMod.ClientConfiguration] = js.native
  var cloudfront: js.UndefOr[typingsSlinky.awsDashSdk.clientsCloudfrontMod.ClientConfiguration] = js.native
  var cloudhsm: js.UndefOr[typingsSlinky.awsDashSdk.clientsCloudhsmMod.ClientConfiguration] = js.native
  var cloudhsmv2: js.UndefOr[typingsSlinky.awsDashSdk.clientsCloudhsmv2Mod.ClientConfiguration] = js.native
  var cloudsearch: js.UndefOr[typingsSlinky.awsDashSdk.clientsCloudsearchMod.ClientConfiguration] = js.native
  var cloudsearchdomain: js.UndefOr[typingsSlinky.awsDashSdk.clientsCloudsearchdomainMod.ClientConfiguration] = js.native
  var cloudtrail: js.UndefOr[typingsSlinky.awsDashSdk.clientsCloudtrailMod.ClientConfiguration] = js.native
  var cloudwatch: js.UndefOr[typingsSlinky.awsDashSdk.clientsCloudwatchMod.ClientConfiguration] = js.native
  var cloudwatchevents: js.UndefOr[typingsSlinky.awsDashSdk.clientsCloudwatcheventsMod.ClientConfiguration] = js.native
  var cloudwatchlogs: js.UndefOr[typingsSlinky.awsDashSdk.clientsCloudwatchlogsMod.ClientConfiguration] = js.native
  var codebuild: js.UndefOr[typingsSlinky.awsDashSdk.clientsCodebuildMod.ClientConfiguration] = js.native
  var codecommit: js.UndefOr[typingsSlinky.awsDashSdk.clientsCodecommitMod.ClientConfiguration] = js.native
  var codedeploy: js.UndefOr[typingsSlinky.awsDashSdk.clientsCodedeployMod.ClientConfiguration] = js.native
  var codeguruprofiler: js.UndefOr[typingsSlinky.awsDashSdk.clientsCodeguruprofilerMod.ClientConfiguration] = js.native
  var codegurureviewer: js.UndefOr[typingsSlinky.awsDashSdk.clientsCodegurureviewerMod.ClientConfiguration] = js.native
  var codepipeline: js.UndefOr[typingsSlinky.awsDashSdk.clientsCodepipelineMod.ClientConfiguration] = js.native
  var codestar: js.UndefOr[typingsSlinky.awsDashSdk.clientsCodestarMod.ClientConfiguration] = js.native
  var codestarconnections: js.UndefOr[typingsSlinky.awsDashSdk.clientsCodestarconnectionsMod.ClientConfiguration] = js.native
  var codestarnotifications: js.UndefOr[typingsSlinky.awsDashSdk.clientsCodestarnotificationsMod.ClientConfiguration] = js.native
  var cognitoidentity: js.UndefOr[typingsSlinky.awsDashSdk.clientsCognitoidentityMod.ClientConfiguration] = js.native
  var cognitoidentityserviceprovider: js.UndefOr[
    typingsSlinky.awsDashSdk.clientsCognitoidentityserviceproviderMod.ClientConfiguration
  ] = js.native
  var cognitosync: js.UndefOr[typingsSlinky.awsDashSdk.clientsCognitosyncMod.ClientConfiguration] = js.native
  var comprehend: js.UndefOr[typingsSlinky.awsDashSdk.clientsComprehendMod.ClientConfiguration] = js.native
  var comprehendmedical: js.UndefOr[typingsSlinky.awsDashSdk.clientsComprehendmedicalMod.ClientConfiguration] = js.native
  var computeoptimizer: js.UndefOr[typingsSlinky.awsDashSdk.clientsComputeoptimizerMod.ClientConfiguration] = js.native
  var configservice: js.UndefOr[typingsSlinky.awsDashSdk.clientsConfigserviceMod.ClientConfiguration] = js.native
  var connect: js.UndefOr[typingsSlinky.awsDashSdk.clientsConnectMod.ClientConfiguration] = js.native
  var connectparticipant: js.UndefOr[typingsSlinky.awsDashSdk.clientsConnectparticipantMod.ClientConfiguration] = js.native
  var costexplorer: js.UndefOr[typingsSlinky.awsDashSdk.clientsCostexplorerMod.ClientConfiguration] = js.native
  var cur: js.UndefOr[typingsSlinky.awsDashSdk.clientsCurMod.ClientConfiguration] = js.native
  var dataexchange: js.UndefOr[typingsSlinky.awsDashSdk.clientsDataexchangeMod.ClientConfiguration] = js.native
  var datapipeline: js.UndefOr[typingsSlinky.awsDashSdk.clientsDatapipelineMod.ClientConfiguration] = js.native
  var datasync: js.UndefOr[typingsSlinky.awsDashSdk.clientsDatasyncMod.ClientConfiguration] = js.native
  var dax: js.UndefOr[typingsSlinky.awsDashSdk.clientsDaxMod.ClientConfiguration] = js.native
  var detective: js.UndefOr[typingsSlinky.awsDashSdk.clientsDetectiveMod.ClientConfiguration] = js.native
  var devicefarm: js.UndefOr[typingsSlinky.awsDashSdk.clientsDevicefarmMod.ClientConfiguration] = js.native
  var directconnect: js.UndefOr[typingsSlinky.awsDashSdk.clientsDirectconnectMod.ClientConfiguration] = js.native
  var directoryservice: js.UndefOr[typingsSlinky.awsDashSdk.clientsDirectoryserviceMod.ClientConfiguration] = js.native
  var discovery: js.UndefOr[typingsSlinky.awsDashSdk.clientsDiscoveryMod.ClientConfiguration] = js.native
  var dlm: js.UndefOr[typingsSlinky.awsDashSdk.clientsDlmMod.ClientConfiguration] = js.native
  var dms: js.UndefOr[typingsSlinky.awsDashSdk.clientsDmsMod.ClientConfiguration] = js.native
  var docdb: js.UndefOr[typingsSlinky.awsDashSdk.clientsDocdbMod.ClientConfiguration] = js.native
  var dynamodb: js.UndefOr[typingsSlinky.awsDashSdk.clientsDynamodbMod.ClientConfiguration] = js.native
  var dynamodbstreams: js.UndefOr[typingsSlinky.awsDashSdk.clientsDynamodbstreamsMod.ClientConfiguration] = js.native
  var ebs: js.UndefOr[typingsSlinky.awsDashSdk.clientsEbsMod.ClientConfiguration] = js.native
  var ec2: js.UndefOr[typingsSlinky.awsDashSdk.clientsEc2Mod.ClientConfiguration] = js.native
  var ec2instanceconnect: js.UndefOr[typingsSlinky.awsDashSdk.clientsEc2instanceconnectMod.ClientConfiguration] = js.native
  var ecr: js.UndefOr[typingsSlinky.awsDashSdk.clientsEcrMod.ClientConfiguration] = js.native
  var ecs: js.UndefOr[typingsSlinky.awsDashSdk.clientsEcsMod.ClientConfiguration] = js.native
  var efs: js.UndefOr[typingsSlinky.awsDashSdk.clientsEfsMod.ClientConfiguration] = js.native
  var eks: js.UndefOr[typingsSlinky.awsDashSdk.clientsEksMod.ClientConfiguration] = js.native
  var elasticache: js.UndefOr[typingsSlinky.awsDashSdk.clientsElasticacheMod.ClientConfiguration] = js.native
  var elasticbeanstalk: js.UndefOr[typingsSlinky.awsDashSdk.clientsElasticbeanstalkMod.ClientConfiguration] = js.native
  var elasticinference: js.UndefOr[typingsSlinky.awsDashSdk.clientsElasticinferenceMod.ClientConfiguration] = js.native
  var elastictranscoder: js.UndefOr[typingsSlinky.awsDashSdk.clientsElastictranscoderMod.ClientConfiguration] = js.native
  var elb: js.UndefOr[typingsSlinky.awsDashSdk.clientsElbMod.ClientConfiguration] = js.native
  var elbv2: js.UndefOr[typingsSlinky.awsDashSdk.clientsElbv2Mod.ClientConfiguration] = js.native
  var emr: js.UndefOr[typingsSlinky.awsDashSdk.clientsEmrMod.ClientConfiguration] = js.native
  var es: js.UndefOr[typingsSlinky.awsDashSdk.clientsEsMod.ClientConfiguration] = js.native
  var eventbridge: js.UndefOr[typingsSlinky.awsDashSdk.clientsEventbridgeMod.ClientConfiguration] = js.native
  var firehose: js.UndefOr[typingsSlinky.awsDashSdk.clientsFirehoseMod.ClientConfiguration] = js.native
  var fms: js.UndefOr[typingsSlinky.awsDashSdk.clientsFmsMod.ClientConfiguration] = js.native
  var forecastqueryservice: js.UndefOr[typingsSlinky.awsDashSdk.clientsForecastqueryserviceMod.ClientConfiguration] = js.native
  var forecastservice: js.UndefOr[typingsSlinky.awsDashSdk.clientsForecastserviceMod.ClientConfiguration] = js.native
  var frauddetector: js.UndefOr[typingsSlinky.awsDashSdk.clientsFrauddetectorMod.ClientConfiguration] = js.native
  var fsx: js.UndefOr[typingsSlinky.awsDashSdk.clientsFsxMod.ClientConfiguration] = js.native
  var gamelift: js.UndefOr[typingsSlinky.awsDashSdk.clientsGameliftMod.ClientConfiguration] = js.native
  var glacier: js.UndefOr[typingsSlinky.awsDashSdk.clientsGlacierMod.ClientConfiguration] = js.native
  var globalaccelerator: js.UndefOr[typingsSlinky.awsDashSdk.clientsGlobalacceleratorMod.ClientConfiguration] = js.native
  var glue: js.UndefOr[typingsSlinky.awsDashSdk.clientsGlueMod.ClientConfiguration] = js.native
  var greengrass: js.UndefOr[typingsSlinky.awsDashSdk.clientsGreengrassMod.ClientConfiguration] = js.native
  var groundstation: js.UndefOr[typingsSlinky.awsDashSdk.clientsGroundstationMod.ClientConfiguration] = js.native
  var guardduty: js.UndefOr[typingsSlinky.awsDashSdk.clientsGuarddutyMod.ClientConfiguration] = js.native
  var health: js.UndefOr[typingsSlinky.awsDashSdk.clientsHealthMod.ClientConfiguration] = js.native
  var iam: js.UndefOr[typingsSlinky.awsDashSdk.clientsIamMod.ClientConfiguration] = js.native
  var imagebuilder: js.UndefOr[typingsSlinky.awsDashSdk.clientsImagebuilderMod.ClientConfiguration] = js.native
  var importexport: js.UndefOr[typingsSlinky.awsDashSdk.clientsImportexportMod.ClientConfiguration] = js.native
  var inspector: js.UndefOr[typingsSlinky.awsDashSdk.clientsInspectorMod.ClientConfiguration] = js.native
  var iot: js.UndefOr[typingsSlinky.awsDashSdk.clientsIotMod.ClientConfiguration] = js.native
  var iot1clickdevicesservice: js.UndefOr[typingsSlinky.awsDashSdk.clientsIot1clickdevicesserviceMod.ClientConfiguration] = js.native
  var iot1clickprojects: js.UndefOr[typingsSlinky.awsDashSdk.clientsIot1clickprojectsMod.ClientConfiguration] = js.native
  var iotanalytics: js.UndefOr[typingsSlinky.awsDashSdk.clientsIotanalyticsMod.ClientConfiguration] = js.native
  var iotdata: js.UndefOr[typingsSlinky.awsDashSdk.clientsIotdataMod.ClientConfiguration] = js.native
  var iotevents: js.UndefOr[typingsSlinky.awsDashSdk.clientsIoteventsMod.ClientConfiguration] = js.native
  var ioteventsdata: js.UndefOr[typingsSlinky.awsDashSdk.clientsIoteventsdataMod.ClientConfiguration] = js.native
  var iotjobsdataplane: js.UndefOr[typingsSlinky.awsDashSdk.clientsIotjobsdataplaneMod.ClientConfiguration] = js.native
  var iotsecuretunneling: js.UndefOr[typingsSlinky.awsDashSdk.clientsIotsecuretunnelingMod.ClientConfiguration] = js.native
  var iotthingsgraph: js.UndefOr[typingsSlinky.awsDashSdk.clientsIotthingsgraphMod.ClientConfiguration] = js.native
  var kafka: js.UndefOr[typingsSlinky.awsDashSdk.clientsKafkaMod.ClientConfiguration] = js.native
  var kendra: js.UndefOr[typingsSlinky.awsDashSdk.clientsKendraMod.ClientConfiguration] = js.native
  var kinesis: js.UndefOr[typingsSlinky.awsDashSdk.clientsKinesisMod.ClientConfiguration] = js.native
  var kinesisanalytics: js.UndefOr[typingsSlinky.awsDashSdk.clientsKinesisanalyticsMod.ClientConfiguration] = js.native
  var kinesisanalyticsv2: js.UndefOr[typingsSlinky.awsDashSdk.clientsKinesisanalyticsv2Mod.ClientConfiguration] = js.native
  var kinesisvideo: js.UndefOr[typingsSlinky.awsDashSdk.clientsKinesisvideoMod.ClientConfiguration] = js.native
  var kinesisvideoarchivedmedia: js.UndefOr[typingsSlinky.awsDashSdk.clientsKinesisvideoarchivedmediaMod.ClientConfiguration] = js.native
  var kinesisvideomedia: js.UndefOr[typingsSlinky.awsDashSdk.clientsKinesisvideomediaMod.ClientConfiguration] = js.native
  var kinesisvideosignalingchannels: js.UndefOr[
    typingsSlinky.awsDashSdk.clientsKinesisvideosignalingchannelsMod.ClientConfiguration
  ] = js.native
  var kms: js.UndefOr[typingsSlinky.awsDashSdk.clientsKmsMod.ClientConfiguration] = js.native
  var lakeformation: js.UndefOr[typingsSlinky.awsDashSdk.clientsLakeformationMod.ClientConfiguration] = js.native
  var lambda: js.UndefOr[typingsSlinky.awsDashSdk.clientsLambdaMod.ClientConfiguration] = js.native
  var lexmodelbuildingservice: js.UndefOr[typingsSlinky.awsDashSdk.clientsLexmodelbuildingserviceMod.ClientConfiguration] = js.native
  var lexruntime: js.UndefOr[typingsSlinky.awsDashSdk.clientsLexruntimeMod.ClientConfiguration] = js.native
  var licensemanager: js.UndefOr[typingsSlinky.awsDashSdk.clientsLicensemanagerMod.ClientConfiguration] = js.native
  var lightsail: js.UndefOr[typingsSlinky.awsDashSdk.clientsLightsailMod.ClientConfiguration] = js.native
  var machinelearning: js.UndefOr[typingsSlinky.awsDashSdk.clientsMachinelearningMod.ClientConfiguration] = js.native
  var macie: js.UndefOr[typingsSlinky.awsDashSdk.clientsMacieMod.ClientConfiguration] = js.native
  var managedblockchain: js.UndefOr[typingsSlinky.awsDashSdk.clientsManagedblockchainMod.ClientConfiguration] = js.native
  var marketplacecatalog: js.UndefOr[typingsSlinky.awsDashSdk.clientsMarketplacecatalogMod.ClientConfiguration] = js.native
  var marketplacecommerceanalytics: js.UndefOr[
    typingsSlinky.awsDashSdk.clientsMarketplacecommerceanalyticsMod.ClientConfiguration
  ] = js.native
  var marketplaceentitlementservice: js.UndefOr[
    typingsSlinky.awsDashSdk.clientsMarketplaceentitlementserviceMod.ClientConfiguration
  ] = js.native
  var marketplacemetering: js.UndefOr[typingsSlinky.awsDashSdk.clientsMarketplacemeteringMod.ClientConfiguration] = js.native
  var mediaconnect: js.UndefOr[typingsSlinky.awsDashSdk.clientsMediaconnectMod.ClientConfiguration] = js.native
  var mediaconvert: js.UndefOr[typingsSlinky.awsDashSdk.clientsMediaconvertMod.ClientConfiguration] = js.native
  var medialive: js.UndefOr[typingsSlinky.awsDashSdk.clientsMedialiveMod.ClientConfiguration] = js.native
  var mediapackage: js.UndefOr[typingsSlinky.awsDashSdk.clientsMediapackageMod.ClientConfiguration] = js.native
  var mediapackagevod: js.UndefOr[typingsSlinky.awsDashSdk.clientsMediapackagevodMod.ClientConfiguration] = js.native
  var mediastore: js.UndefOr[typingsSlinky.awsDashSdk.clientsMediastoreMod.ClientConfiguration] = js.native
  var mediastoredata: js.UndefOr[typingsSlinky.awsDashSdk.clientsMediastoredataMod.ClientConfiguration] = js.native
  var mediatailor: js.UndefOr[typingsSlinky.awsDashSdk.clientsMediatailorMod.ClientConfiguration] = js.native
  var migrationhub: js.UndefOr[typingsSlinky.awsDashSdk.clientsMigrationhubMod.ClientConfiguration] = js.native
  var migrationhubconfig: js.UndefOr[typingsSlinky.awsDashSdk.clientsMigrationhubconfigMod.ClientConfiguration] = js.native
  var mobile: js.UndefOr[typingsSlinky.awsDashSdk.clientsMobileMod.ClientConfiguration] = js.native
  var mobileanalytics: js.UndefOr[typingsSlinky.awsDashSdk.clientsMobileanalyticsMod.ClientConfiguration] = js.native
  var mq: js.UndefOr[typingsSlinky.awsDashSdk.clientsMqMod.ClientConfiguration] = js.native
  var mturk: js.UndefOr[typingsSlinky.awsDashSdk.clientsMturkMod.ClientConfiguration] = js.native
  var neptune: js.UndefOr[typingsSlinky.awsDashSdk.clientsNeptuneMod.ClientConfiguration] = js.native
  var networkmanager: js.UndefOr[typingsSlinky.awsDashSdk.clientsNetworkmanagerMod.ClientConfiguration] = js.native
  var opsworks: js.UndefOr[typingsSlinky.awsDashSdk.clientsOpsworksMod.ClientConfiguration] = js.native
  var opsworkscm: js.UndefOr[typingsSlinky.awsDashSdk.clientsOpsworkscmMod.ClientConfiguration] = js.native
  var organizations: js.UndefOr[typingsSlinky.awsDashSdk.clientsOrganizationsMod.ClientConfiguration] = js.native
  var outposts: js.UndefOr[typingsSlinky.awsDashSdk.clientsOutpostsMod.ClientConfiguration] = js.native
  var personalize: js.UndefOr[typingsSlinky.awsDashSdk.clientsPersonalizeMod.ClientConfiguration] = js.native
  var personalizeevents: js.UndefOr[typingsSlinky.awsDashSdk.clientsPersonalizeeventsMod.ClientConfiguration] = js.native
  var personalizeruntime: js.UndefOr[typingsSlinky.awsDashSdk.clientsPersonalizeruntimeMod.ClientConfiguration] = js.native
  var pi: js.UndefOr[typingsSlinky.awsDashSdk.clientsPiMod.ClientConfiguration] = js.native
  var pinpoint: js.UndefOr[typingsSlinky.awsDashSdk.clientsPinpointMod.ClientConfiguration] = js.native
  var pinpointemail: js.UndefOr[typingsSlinky.awsDashSdk.clientsPinpointemailMod.ClientConfiguration] = js.native
  var pinpointsmsvoice: js.UndefOr[typingsSlinky.awsDashSdk.clientsPinpointsmsvoiceMod.ClientConfiguration] = js.native
  var polly: js.UndefOr[typingsSlinky.awsDashSdk.clientsPollyMod.ClientConfiguration] = js.native
  var pricing: js.UndefOr[typingsSlinky.awsDashSdk.clientsPricingMod.ClientConfiguration] = js.native
  var qldb: js.UndefOr[typingsSlinky.awsDashSdk.clientsQldbMod.ClientConfiguration] = js.native
  var qldbsession: js.UndefOr[typingsSlinky.awsDashSdk.clientsQldbsessionMod.ClientConfiguration] = js.native
  var quicksight: js.UndefOr[typingsSlinky.awsDashSdk.clientsQuicksightMod.ClientConfiguration] = js.native
  var ram: js.UndefOr[typingsSlinky.awsDashSdk.clientsRamMod.ClientConfiguration] = js.native
  var rds: js.UndefOr[typingsSlinky.awsDashSdk.clientsRdsMod.ClientConfiguration] = js.native
  var rdsdataservice: js.UndefOr[typingsSlinky.awsDashSdk.clientsRdsdataserviceMod.ClientConfiguration] = js.native
  var redshift: js.UndefOr[typingsSlinky.awsDashSdk.clientsRedshiftMod.ClientConfiguration] = js.native
  var rekognition: js.UndefOr[typingsSlinky.awsDashSdk.clientsRekognitionMod.ClientConfiguration] = js.native
  var resourcegroups: js.UndefOr[typingsSlinky.awsDashSdk.clientsResourcegroupsMod.ClientConfiguration] = js.native
  var resourcegroupstaggingapi: js.UndefOr[typingsSlinky.awsDashSdk.clientsResourcegroupstaggingapiMod.ClientConfiguration] = js.native
  var robomaker: js.UndefOr[typingsSlinky.awsDashSdk.clientsRobomakerMod.ClientConfiguration] = js.native
  var route53: js.UndefOr[typingsSlinky.awsDashSdk.clientsRoute53Mod.ClientConfiguration] = js.native
  var route53domains: js.UndefOr[typingsSlinky.awsDashSdk.clientsRoute53domainsMod.ClientConfiguration] = js.native
  var route53resolver: js.UndefOr[typingsSlinky.awsDashSdk.clientsRoute53resolverMod.ClientConfiguration] = js.native
  var s3: js.UndefOr[typingsSlinky.awsDashSdk.clientsS3Mod.ClientConfiguration] = js.native
  var s3control: js.UndefOr[typingsSlinky.awsDashSdk.clientsS3controlMod.ClientConfiguration] = js.native
  var sagemaker: js.UndefOr[typingsSlinky.awsDashSdk.clientsSagemakerMod.ClientConfiguration] = js.native
  var sagemakerruntime: js.UndefOr[typingsSlinky.awsDashSdk.clientsSagemakerruntimeMod.ClientConfiguration] = js.native
  var savingsplans: js.UndefOr[typingsSlinky.awsDashSdk.clientsSavingsplansMod.ClientConfiguration] = js.native
  var schemas: js.UndefOr[typingsSlinky.awsDashSdk.clientsSchemasMod.ClientConfiguration] = js.native
  var secretsmanager: js.UndefOr[typingsSlinky.awsDashSdk.clientsSecretsmanagerMod.ClientConfiguration] = js.native
  var securityhub: js.UndefOr[typingsSlinky.awsDashSdk.clientsSecurityhubMod.ClientConfiguration] = js.native
  var serverlessapplicationrepository: js.UndefOr[
    typingsSlinky.awsDashSdk.clientsServerlessapplicationrepositoryMod.ClientConfiguration
  ] = js.native
  var servicecatalog: js.UndefOr[typingsSlinky.awsDashSdk.clientsServicecatalogMod.ClientConfiguration] = js.native
  var servicediscovery: js.UndefOr[typingsSlinky.awsDashSdk.clientsServicediscoveryMod.ClientConfiguration] = js.native
  var servicequotas: js.UndefOr[typingsSlinky.awsDashSdk.clientsServicequotasMod.ClientConfiguration] = js.native
  var ses: js.UndefOr[typingsSlinky.awsDashSdk.clientsSesMod.ClientConfiguration] = js.native
  var sesv2: js.UndefOr[typingsSlinky.awsDashSdk.clientsSesv2Mod.ClientConfiguration] = js.native
  var shield: js.UndefOr[typingsSlinky.awsDashSdk.clientsShieldMod.ClientConfiguration] = js.native
  var signer: js.UndefOr[typingsSlinky.awsDashSdk.clientsSignerMod.ClientConfiguration] = js.native
  var simpledb: js.UndefOr[typingsSlinky.awsDashSdk.clientsSimpledbMod.ClientConfiguration] = js.native
  var sms: js.UndefOr[typingsSlinky.awsDashSdk.clientsSmsMod.ClientConfiguration] = js.native
  var snowball: js.UndefOr[typingsSlinky.awsDashSdk.clientsSnowballMod.ClientConfiguration] = js.native
  var sns: js.UndefOr[typingsSlinky.awsDashSdk.clientsSnsMod.ClientConfiguration] = js.native
  var sqs: js.UndefOr[typingsSlinky.awsDashSdk.clientsSqsMod.ClientConfiguration] = js.native
  var ssm: js.UndefOr[typingsSlinky.awsDashSdk.clientsSsmMod.ClientConfiguration] = js.native
  var sso: js.UndefOr[typingsSlinky.awsDashSdk.clientsSsoMod.ClientConfiguration] = js.native
  var ssooidc: js.UndefOr[typingsSlinky.awsDashSdk.clientsSsooidcMod.ClientConfiguration] = js.native
  var stepfunctions: js.UndefOr[typingsSlinky.awsDashSdk.clientsStepfunctionsMod.ClientConfiguration] = js.native
  var storagegateway: js.UndefOr[typingsSlinky.awsDashSdk.clientsStoragegatewayMod.ClientConfiguration] = js.native
  var sts: js.UndefOr[typingsSlinky.awsDashSdk.clientsStsMod.ClientConfiguration] = js.native
  var support: js.UndefOr[typingsSlinky.awsDashSdk.clientsSupportMod.ClientConfiguration] = js.native
  var swf: js.UndefOr[typingsSlinky.awsDashSdk.clientsSwfMod.ClientConfiguration] = js.native
  var textract: js.UndefOr[typingsSlinky.awsDashSdk.clientsTextractMod.ClientConfiguration] = js.native
  var transcribeservice: js.UndefOr[typingsSlinky.awsDashSdk.clientsTranscribeserviceMod.ClientConfiguration] = js.native
  var transfer: js.UndefOr[typingsSlinky.awsDashSdk.clientsTransferMod.ClientConfiguration] = js.native
  var translate: js.UndefOr[typingsSlinky.awsDashSdk.clientsTranslateMod.ClientConfiguration] = js.native
  var waf: js.UndefOr[typingsSlinky.awsDashSdk.clientsWafMod.ClientConfiguration] = js.native
  var wafregional: js.UndefOr[typingsSlinky.awsDashSdk.clientsWafregionalMod.ClientConfiguration] = js.native
  var wafv2: js.UndefOr[typingsSlinky.awsDashSdk.clientsWafv2Mod.ClientConfiguration] = js.native
  var workdocs: js.UndefOr[typingsSlinky.awsDashSdk.clientsWorkdocsMod.ClientConfiguration] = js.native
  var worklink: js.UndefOr[typingsSlinky.awsDashSdk.clientsWorklinkMod.ClientConfiguration] = js.native
  var workmail: js.UndefOr[typingsSlinky.awsDashSdk.clientsWorkmailMod.ClientConfiguration] = js.native
  var workmailmessageflow: js.UndefOr[typingsSlinky.awsDashSdk.clientsWorkmailmessageflowMod.ClientConfiguration] = js.native
  var workspaces: js.UndefOr[typingsSlinky.awsDashSdk.clientsWorkspacesMod.ClientConfiguration] = js.native
  var xray: js.UndefOr[typingsSlinky.awsDashSdk.clientsXrayMod.ClientConfiguration] = js.native
}

