package typingsSlinky.awsDashSdk.libConfigUnderscoreServiceUnderscorePlaceholdersMod

import typingsSlinky.awsDashSdk.clientsAccessanalyzerMod.apiVersion
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait ConfigurationServiceApiVersions extends js.Object {
  var accessanalyzer: js.UndefOr[apiVersion] = js.native
  var acm: js.UndefOr[typingsSlinky.awsDashSdk.clientsAcmMod.apiVersion] = js.native
  var acmpca: js.UndefOr[typingsSlinky.awsDashSdk.clientsAcmpcaMod.apiVersion] = js.native
  var alexaforbusiness: js.UndefOr[typingsSlinky.awsDashSdk.clientsAlexaforbusinessMod.apiVersion] = js.native
  var amplify: js.UndefOr[typingsSlinky.awsDashSdk.clientsAmplifyMod.apiVersion] = js.native
  var apigateway: js.UndefOr[typingsSlinky.awsDashSdk.clientsApigatewayMod.apiVersion] = js.native
  var apigatewaymanagementapi: js.UndefOr[typingsSlinky.awsDashSdk.clientsApigatewaymanagementapiMod.apiVersion] = js.native
  var apigatewayv2: js.UndefOr[typingsSlinky.awsDashSdk.clientsApigatewayv2Mod.apiVersion] = js.native
  var appconfig: js.UndefOr[typingsSlinky.awsDashSdk.clientsAppconfigMod.apiVersion] = js.native
  var applicationautoscaling: js.UndefOr[typingsSlinky.awsDashSdk.clientsApplicationautoscalingMod.apiVersion] = js.native
  var applicationinsights: js.UndefOr[typingsSlinky.awsDashSdk.clientsApplicationinsightsMod.apiVersion] = js.native
  var appmesh: js.UndefOr[typingsSlinky.awsDashSdk.clientsAppmeshMod.apiVersion] = js.native
  var appstream: js.UndefOr[typingsSlinky.awsDashSdk.clientsAppstreamMod.apiVersion] = js.native
  var appsync: js.UndefOr[typingsSlinky.awsDashSdk.clientsAppsyncMod.apiVersion] = js.native
  var athena: js.UndefOr[typingsSlinky.awsDashSdk.clientsAthenaMod.apiVersion] = js.native
  var augmentedairuntime: js.UndefOr[typingsSlinky.awsDashSdk.clientsAugmentedairuntimeMod.apiVersion] = js.native
  var autoscaling: js.UndefOr[typingsSlinky.awsDashSdk.clientsAutoscalingMod.apiVersion] = js.native
  var autoscalingplans: js.UndefOr[typingsSlinky.awsDashSdk.clientsAutoscalingplansMod.apiVersion] = js.native
  var backup: js.UndefOr[typingsSlinky.awsDashSdk.clientsBackupMod.apiVersion] = js.native
  var batch: js.UndefOr[typingsSlinky.awsDashSdk.clientsBatchMod.apiVersion] = js.native
  var budgets: js.UndefOr[typingsSlinky.awsDashSdk.clientsBudgetsMod.apiVersion] = js.native
  var chime: js.UndefOr[typingsSlinky.awsDashSdk.clientsChimeMod.apiVersion] = js.native
  var cloud9: js.UndefOr[typingsSlinky.awsDashSdk.clientsCloud9Mod.apiVersion] = js.native
  var clouddirectory: js.UndefOr[typingsSlinky.awsDashSdk.clientsClouddirectoryMod.apiVersion] = js.native
  var cloudformation: js.UndefOr[typingsSlinky.awsDashSdk.clientsCloudformationMod.apiVersion] = js.native
  var cloudfront: js.UndefOr[typingsSlinky.awsDashSdk.clientsCloudfrontMod.apiVersion] = js.native
  var cloudhsm: js.UndefOr[typingsSlinky.awsDashSdk.clientsCloudhsmMod.apiVersion] = js.native
  var cloudhsmv2: js.UndefOr[typingsSlinky.awsDashSdk.clientsCloudhsmv2Mod.apiVersion] = js.native
  var cloudsearch: js.UndefOr[typingsSlinky.awsDashSdk.clientsCloudsearchMod.apiVersion] = js.native
  var cloudsearchdomain: js.UndefOr[typingsSlinky.awsDashSdk.clientsCloudsearchdomainMod.apiVersion] = js.native
  var cloudtrail: js.UndefOr[typingsSlinky.awsDashSdk.clientsCloudtrailMod.apiVersion] = js.native
  var cloudwatch: js.UndefOr[typingsSlinky.awsDashSdk.clientsCloudwatchMod.apiVersion] = js.native
  var cloudwatchevents: js.UndefOr[typingsSlinky.awsDashSdk.clientsCloudwatcheventsMod.apiVersion] = js.native
  var cloudwatchlogs: js.UndefOr[typingsSlinky.awsDashSdk.clientsCloudwatchlogsMod.apiVersion] = js.native
  var codebuild: js.UndefOr[typingsSlinky.awsDashSdk.clientsCodebuildMod.apiVersion] = js.native
  var codecommit: js.UndefOr[typingsSlinky.awsDashSdk.clientsCodecommitMod.apiVersion] = js.native
  var codedeploy: js.UndefOr[typingsSlinky.awsDashSdk.clientsCodedeployMod.apiVersion] = js.native
  var codeguruprofiler: js.UndefOr[typingsSlinky.awsDashSdk.clientsCodeguruprofilerMod.apiVersion] = js.native
  var codegurureviewer: js.UndefOr[typingsSlinky.awsDashSdk.clientsCodegurureviewerMod.apiVersion] = js.native
  var codepipeline: js.UndefOr[typingsSlinky.awsDashSdk.clientsCodepipelineMod.apiVersion] = js.native
  var codestar: js.UndefOr[typingsSlinky.awsDashSdk.clientsCodestarMod.apiVersion] = js.native
  var codestarconnections: js.UndefOr[typingsSlinky.awsDashSdk.clientsCodestarconnectionsMod.apiVersion] = js.native
  var codestarnotifications: js.UndefOr[typingsSlinky.awsDashSdk.clientsCodestarnotificationsMod.apiVersion] = js.native
  var cognitoidentity: js.UndefOr[typingsSlinky.awsDashSdk.clientsCognitoidentityMod.apiVersion] = js.native
  var cognitoidentityserviceprovider: js.UndefOr[typingsSlinky.awsDashSdk.clientsCognitoidentityserviceproviderMod.apiVersion] = js.native
  var cognitosync: js.UndefOr[typingsSlinky.awsDashSdk.clientsCognitosyncMod.apiVersion] = js.native
  var comprehend: js.UndefOr[typingsSlinky.awsDashSdk.clientsComprehendMod.apiVersion] = js.native
  var comprehendmedical: js.UndefOr[typingsSlinky.awsDashSdk.clientsComprehendmedicalMod.apiVersion] = js.native
  var computeoptimizer: js.UndefOr[typingsSlinky.awsDashSdk.clientsComputeoptimizerMod.apiVersion] = js.native
  var configservice: js.UndefOr[typingsSlinky.awsDashSdk.clientsConfigserviceMod.apiVersion] = js.native
  var connect: js.UndefOr[typingsSlinky.awsDashSdk.clientsConnectMod.apiVersion] = js.native
  var connectparticipant: js.UndefOr[typingsSlinky.awsDashSdk.clientsConnectparticipantMod.apiVersion] = js.native
  var costexplorer: js.UndefOr[typingsSlinky.awsDashSdk.clientsCostexplorerMod.apiVersion] = js.native
  var cur: js.UndefOr[typingsSlinky.awsDashSdk.clientsCurMod.apiVersion] = js.native
  var dataexchange: js.UndefOr[typingsSlinky.awsDashSdk.clientsDataexchangeMod.apiVersion] = js.native
  var datapipeline: js.UndefOr[typingsSlinky.awsDashSdk.clientsDatapipelineMod.apiVersion] = js.native
  var datasync: js.UndefOr[typingsSlinky.awsDashSdk.clientsDatasyncMod.apiVersion] = js.native
  var dax: js.UndefOr[typingsSlinky.awsDashSdk.clientsDaxMod.apiVersion] = js.native
  var detective: js.UndefOr[typingsSlinky.awsDashSdk.clientsDetectiveMod.apiVersion] = js.native
  var devicefarm: js.UndefOr[typingsSlinky.awsDashSdk.clientsDevicefarmMod.apiVersion] = js.native
  var directconnect: js.UndefOr[typingsSlinky.awsDashSdk.clientsDirectconnectMod.apiVersion] = js.native
  var directoryservice: js.UndefOr[typingsSlinky.awsDashSdk.clientsDirectoryserviceMod.apiVersion] = js.native
  var discovery: js.UndefOr[typingsSlinky.awsDashSdk.clientsDiscoveryMod.apiVersion] = js.native
  var dlm: js.UndefOr[typingsSlinky.awsDashSdk.clientsDlmMod.apiVersion] = js.native
  var dms: js.UndefOr[typingsSlinky.awsDashSdk.clientsDmsMod.apiVersion] = js.native
  var docdb: js.UndefOr[typingsSlinky.awsDashSdk.clientsDocdbMod.apiVersion] = js.native
  var dynamodb: js.UndefOr[typingsSlinky.awsDashSdk.clientsDynamodbMod.apiVersion] = js.native
  var dynamodbstreams: js.UndefOr[typingsSlinky.awsDashSdk.clientsDynamodbstreamsMod.apiVersion] = js.native
  var ebs: js.UndefOr[typingsSlinky.awsDashSdk.clientsEbsMod.apiVersion] = js.native
  var ec2: js.UndefOr[typingsSlinky.awsDashSdk.clientsEc2Mod.apiVersion] = js.native
  var ec2instanceconnect: js.UndefOr[typingsSlinky.awsDashSdk.clientsEc2instanceconnectMod.apiVersion] = js.native
  var ecr: js.UndefOr[typingsSlinky.awsDashSdk.clientsEcrMod.apiVersion] = js.native
  var ecs: js.UndefOr[typingsSlinky.awsDashSdk.clientsEcsMod.apiVersion] = js.native
  var efs: js.UndefOr[typingsSlinky.awsDashSdk.clientsEfsMod.apiVersion] = js.native
  var eks: js.UndefOr[typingsSlinky.awsDashSdk.clientsEksMod.apiVersion] = js.native
  var elasticache: js.UndefOr[typingsSlinky.awsDashSdk.clientsElasticacheMod.apiVersion] = js.native
  var elasticbeanstalk: js.UndefOr[typingsSlinky.awsDashSdk.clientsElasticbeanstalkMod.apiVersion] = js.native
  var elasticinference: js.UndefOr[typingsSlinky.awsDashSdk.clientsElasticinferenceMod.apiVersion] = js.native
  var elastictranscoder: js.UndefOr[typingsSlinky.awsDashSdk.clientsElastictranscoderMod.apiVersion] = js.native
  var elb: js.UndefOr[typingsSlinky.awsDashSdk.clientsElbMod.apiVersion] = js.native
  var elbv2: js.UndefOr[typingsSlinky.awsDashSdk.clientsElbv2Mod.apiVersion] = js.native
  var emr: js.UndefOr[typingsSlinky.awsDashSdk.clientsEmrMod.apiVersion] = js.native
  var es: js.UndefOr[typingsSlinky.awsDashSdk.clientsEsMod.apiVersion] = js.native
  var eventbridge: js.UndefOr[typingsSlinky.awsDashSdk.clientsEventbridgeMod.apiVersion] = js.native
  var firehose: js.UndefOr[typingsSlinky.awsDashSdk.clientsFirehoseMod.apiVersion] = js.native
  var fms: js.UndefOr[typingsSlinky.awsDashSdk.clientsFmsMod.apiVersion] = js.native
  var forecastqueryservice: js.UndefOr[typingsSlinky.awsDashSdk.clientsForecastqueryserviceMod.apiVersion] = js.native
  var forecastservice: js.UndefOr[typingsSlinky.awsDashSdk.clientsForecastserviceMod.apiVersion] = js.native
  var frauddetector: js.UndefOr[typingsSlinky.awsDashSdk.clientsFrauddetectorMod.apiVersion] = js.native
  var fsx: js.UndefOr[typingsSlinky.awsDashSdk.clientsFsxMod.apiVersion] = js.native
  var gamelift: js.UndefOr[typingsSlinky.awsDashSdk.clientsGameliftMod.apiVersion] = js.native
  var glacier: js.UndefOr[typingsSlinky.awsDashSdk.clientsGlacierMod.apiVersion] = js.native
  var globalaccelerator: js.UndefOr[typingsSlinky.awsDashSdk.clientsGlobalacceleratorMod.apiVersion] = js.native
  var glue: js.UndefOr[typingsSlinky.awsDashSdk.clientsGlueMod.apiVersion] = js.native
  var greengrass: js.UndefOr[typingsSlinky.awsDashSdk.clientsGreengrassMod.apiVersion] = js.native
  var groundstation: js.UndefOr[typingsSlinky.awsDashSdk.clientsGroundstationMod.apiVersion] = js.native
  var guardduty: js.UndefOr[typingsSlinky.awsDashSdk.clientsGuarddutyMod.apiVersion] = js.native
  var health: js.UndefOr[typingsSlinky.awsDashSdk.clientsHealthMod.apiVersion] = js.native
  var iam: js.UndefOr[typingsSlinky.awsDashSdk.clientsIamMod.apiVersion] = js.native
  var imagebuilder: js.UndefOr[typingsSlinky.awsDashSdk.clientsImagebuilderMod.apiVersion] = js.native
  var importexport: js.UndefOr[typingsSlinky.awsDashSdk.clientsImportexportMod.apiVersion] = js.native
  var inspector: js.UndefOr[typingsSlinky.awsDashSdk.clientsInspectorMod.apiVersion] = js.native
  var iot: js.UndefOr[typingsSlinky.awsDashSdk.clientsIotMod.apiVersion] = js.native
  var iot1clickdevicesservice: js.UndefOr[typingsSlinky.awsDashSdk.clientsIot1clickdevicesserviceMod.apiVersion] = js.native
  var iot1clickprojects: js.UndefOr[typingsSlinky.awsDashSdk.clientsIot1clickprojectsMod.apiVersion] = js.native
  var iotanalytics: js.UndefOr[typingsSlinky.awsDashSdk.clientsIotanalyticsMod.apiVersion] = js.native
  var iotdata: js.UndefOr[typingsSlinky.awsDashSdk.clientsIotdataMod.apiVersion] = js.native
  var iotevents: js.UndefOr[typingsSlinky.awsDashSdk.clientsIoteventsMod.apiVersion] = js.native
  var ioteventsdata: js.UndefOr[typingsSlinky.awsDashSdk.clientsIoteventsdataMod.apiVersion] = js.native
  var iotjobsdataplane: js.UndefOr[typingsSlinky.awsDashSdk.clientsIotjobsdataplaneMod.apiVersion] = js.native
  var iotsecuretunneling: js.UndefOr[typingsSlinky.awsDashSdk.clientsIotsecuretunnelingMod.apiVersion] = js.native
  var iotthingsgraph: js.UndefOr[typingsSlinky.awsDashSdk.clientsIotthingsgraphMod.apiVersion] = js.native
  var kafka: js.UndefOr[typingsSlinky.awsDashSdk.clientsKafkaMod.apiVersion] = js.native
  var kendra: js.UndefOr[typingsSlinky.awsDashSdk.clientsKendraMod.apiVersion] = js.native
  var kinesis: js.UndefOr[typingsSlinky.awsDashSdk.clientsKinesisMod.apiVersion] = js.native
  var kinesisanalytics: js.UndefOr[typingsSlinky.awsDashSdk.clientsKinesisanalyticsMod.apiVersion] = js.native
  var kinesisanalyticsv2: js.UndefOr[typingsSlinky.awsDashSdk.clientsKinesisanalyticsv2Mod.apiVersion] = js.native
  var kinesisvideo: js.UndefOr[typingsSlinky.awsDashSdk.clientsKinesisvideoMod.apiVersion] = js.native
  var kinesisvideoarchivedmedia: js.UndefOr[typingsSlinky.awsDashSdk.clientsKinesisvideoarchivedmediaMod.apiVersion] = js.native
  var kinesisvideomedia: js.UndefOr[typingsSlinky.awsDashSdk.clientsKinesisvideomediaMod.apiVersion] = js.native
  var kinesisvideosignalingchannels: js.UndefOr[typingsSlinky.awsDashSdk.clientsKinesisvideosignalingchannelsMod.apiVersion] = js.native
  var kms: js.UndefOr[typingsSlinky.awsDashSdk.clientsKmsMod.apiVersion] = js.native
  var lakeformation: js.UndefOr[typingsSlinky.awsDashSdk.clientsLakeformationMod.apiVersion] = js.native
  var lambda: js.UndefOr[typingsSlinky.awsDashSdk.clientsLambdaMod.apiVersion] = js.native
  var lexmodelbuildingservice: js.UndefOr[typingsSlinky.awsDashSdk.clientsLexmodelbuildingserviceMod.apiVersion] = js.native
  var lexruntime: js.UndefOr[typingsSlinky.awsDashSdk.clientsLexruntimeMod.apiVersion] = js.native
  var licensemanager: js.UndefOr[typingsSlinky.awsDashSdk.clientsLicensemanagerMod.apiVersion] = js.native
  var lightsail: js.UndefOr[typingsSlinky.awsDashSdk.clientsLightsailMod.apiVersion] = js.native
  var machinelearning: js.UndefOr[typingsSlinky.awsDashSdk.clientsMachinelearningMod.apiVersion] = js.native
  var macie: js.UndefOr[typingsSlinky.awsDashSdk.clientsMacieMod.apiVersion] = js.native
  var managedblockchain: js.UndefOr[typingsSlinky.awsDashSdk.clientsManagedblockchainMod.apiVersion] = js.native
  var marketplacecatalog: js.UndefOr[typingsSlinky.awsDashSdk.clientsMarketplacecatalogMod.apiVersion] = js.native
  var marketplacecommerceanalytics: js.UndefOr[typingsSlinky.awsDashSdk.clientsMarketplacecommerceanalyticsMod.apiVersion] = js.native
  var marketplaceentitlementservice: js.UndefOr[typingsSlinky.awsDashSdk.clientsMarketplaceentitlementserviceMod.apiVersion] = js.native
  var marketplacemetering: js.UndefOr[typingsSlinky.awsDashSdk.clientsMarketplacemeteringMod.apiVersion] = js.native
  var mediaconnect: js.UndefOr[typingsSlinky.awsDashSdk.clientsMediaconnectMod.apiVersion] = js.native
  var mediaconvert: js.UndefOr[typingsSlinky.awsDashSdk.clientsMediaconvertMod.apiVersion] = js.native
  var medialive: js.UndefOr[typingsSlinky.awsDashSdk.clientsMedialiveMod.apiVersion] = js.native
  var mediapackage: js.UndefOr[typingsSlinky.awsDashSdk.clientsMediapackageMod.apiVersion] = js.native
  var mediapackagevod: js.UndefOr[typingsSlinky.awsDashSdk.clientsMediapackagevodMod.apiVersion] = js.native
  var mediastore: js.UndefOr[typingsSlinky.awsDashSdk.clientsMediastoreMod.apiVersion] = js.native
  var mediastoredata: js.UndefOr[typingsSlinky.awsDashSdk.clientsMediastoredataMod.apiVersion] = js.native
  var mediatailor: js.UndefOr[typingsSlinky.awsDashSdk.clientsMediatailorMod.apiVersion] = js.native
  var migrationhub: js.UndefOr[typingsSlinky.awsDashSdk.clientsMigrationhubMod.apiVersion] = js.native
  var migrationhubconfig: js.UndefOr[typingsSlinky.awsDashSdk.clientsMigrationhubconfigMod.apiVersion] = js.native
  var mobile: js.UndefOr[typingsSlinky.awsDashSdk.clientsMobileMod.apiVersion] = js.native
  var mobileanalytics: js.UndefOr[typingsSlinky.awsDashSdk.clientsMobileanalyticsMod.apiVersion] = js.native
  var mq: js.UndefOr[typingsSlinky.awsDashSdk.clientsMqMod.apiVersion] = js.native
  var mturk: js.UndefOr[typingsSlinky.awsDashSdk.clientsMturkMod.apiVersion] = js.native
  var neptune: js.UndefOr[typingsSlinky.awsDashSdk.clientsNeptuneMod.apiVersion] = js.native
  var networkmanager: js.UndefOr[typingsSlinky.awsDashSdk.clientsNetworkmanagerMod.apiVersion] = js.native
  var opsworks: js.UndefOr[typingsSlinky.awsDashSdk.clientsOpsworksMod.apiVersion] = js.native
  var opsworkscm: js.UndefOr[typingsSlinky.awsDashSdk.clientsOpsworkscmMod.apiVersion] = js.native
  var organizations: js.UndefOr[typingsSlinky.awsDashSdk.clientsOrganizationsMod.apiVersion] = js.native
  var outposts: js.UndefOr[typingsSlinky.awsDashSdk.clientsOutpostsMod.apiVersion] = js.native
  var personalize: js.UndefOr[typingsSlinky.awsDashSdk.clientsPersonalizeMod.apiVersion] = js.native
  var personalizeevents: js.UndefOr[typingsSlinky.awsDashSdk.clientsPersonalizeeventsMod.apiVersion] = js.native
  var personalizeruntime: js.UndefOr[typingsSlinky.awsDashSdk.clientsPersonalizeruntimeMod.apiVersion] = js.native
  var pi: js.UndefOr[typingsSlinky.awsDashSdk.clientsPiMod.apiVersion] = js.native
  var pinpoint: js.UndefOr[typingsSlinky.awsDashSdk.clientsPinpointMod.apiVersion] = js.native
  var pinpointemail: js.UndefOr[typingsSlinky.awsDashSdk.clientsPinpointemailMod.apiVersion] = js.native
  var pinpointsmsvoice: js.UndefOr[typingsSlinky.awsDashSdk.clientsPinpointsmsvoiceMod.apiVersion] = js.native
  var polly: js.UndefOr[typingsSlinky.awsDashSdk.clientsPollyMod.apiVersion] = js.native
  var pricing: js.UndefOr[typingsSlinky.awsDashSdk.clientsPricingMod.apiVersion] = js.native
  var qldb: js.UndefOr[typingsSlinky.awsDashSdk.clientsQldbMod.apiVersion] = js.native
  var qldbsession: js.UndefOr[typingsSlinky.awsDashSdk.clientsQldbsessionMod.apiVersion] = js.native
  var quicksight: js.UndefOr[typingsSlinky.awsDashSdk.clientsQuicksightMod.apiVersion] = js.native
  var ram: js.UndefOr[typingsSlinky.awsDashSdk.clientsRamMod.apiVersion] = js.native
  var rds: js.UndefOr[typingsSlinky.awsDashSdk.clientsRdsMod.apiVersion] = js.native
  var rdsdataservice: js.UndefOr[typingsSlinky.awsDashSdk.clientsRdsdataserviceMod.apiVersion] = js.native
  var redshift: js.UndefOr[typingsSlinky.awsDashSdk.clientsRedshiftMod.apiVersion] = js.native
  var rekognition: js.UndefOr[typingsSlinky.awsDashSdk.clientsRekognitionMod.apiVersion] = js.native
  var resourcegroups: js.UndefOr[typingsSlinky.awsDashSdk.clientsResourcegroupsMod.apiVersion] = js.native
  var resourcegroupstaggingapi: js.UndefOr[typingsSlinky.awsDashSdk.clientsResourcegroupstaggingapiMod.apiVersion] = js.native
  var robomaker: js.UndefOr[typingsSlinky.awsDashSdk.clientsRobomakerMod.apiVersion] = js.native
  var route53: js.UndefOr[typingsSlinky.awsDashSdk.clientsRoute53Mod.apiVersion] = js.native
  var route53domains: js.UndefOr[typingsSlinky.awsDashSdk.clientsRoute53domainsMod.apiVersion] = js.native
  var route53resolver: js.UndefOr[typingsSlinky.awsDashSdk.clientsRoute53resolverMod.apiVersion] = js.native
  var s3: js.UndefOr[typingsSlinky.awsDashSdk.clientsS3Mod.apiVersion] = js.native
  var s3control: js.UndefOr[typingsSlinky.awsDashSdk.clientsS3controlMod.apiVersion] = js.native
  var sagemaker: js.UndefOr[typingsSlinky.awsDashSdk.clientsSagemakerMod.apiVersion] = js.native
  var sagemakerruntime: js.UndefOr[typingsSlinky.awsDashSdk.clientsSagemakerruntimeMod.apiVersion] = js.native
  var savingsplans: js.UndefOr[typingsSlinky.awsDashSdk.clientsSavingsplansMod.apiVersion] = js.native
  var schemas: js.UndefOr[typingsSlinky.awsDashSdk.clientsSchemasMod.apiVersion] = js.native
  var secretsmanager: js.UndefOr[typingsSlinky.awsDashSdk.clientsSecretsmanagerMod.apiVersion] = js.native
  var securityhub: js.UndefOr[typingsSlinky.awsDashSdk.clientsSecurityhubMod.apiVersion] = js.native
  var serverlessapplicationrepository: js.UndefOr[typingsSlinky.awsDashSdk.clientsServerlessapplicationrepositoryMod.apiVersion] = js.native
  var servicecatalog: js.UndefOr[typingsSlinky.awsDashSdk.clientsServicecatalogMod.apiVersion] = js.native
  var servicediscovery: js.UndefOr[typingsSlinky.awsDashSdk.clientsServicediscoveryMod.apiVersion] = js.native
  var servicequotas: js.UndefOr[typingsSlinky.awsDashSdk.clientsServicequotasMod.apiVersion] = js.native
  var ses: js.UndefOr[typingsSlinky.awsDashSdk.clientsSesMod.apiVersion] = js.native
  var sesv2: js.UndefOr[typingsSlinky.awsDashSdk.clientsSesv2Mod.apiVersion] = js.native
  var shield: js.UndefOr[typingsSlinky.awsDashSdk.clientsShieldMod.apiVersion] = js.native
  var signer: js.UndefOr[typingsSlinky.awsDashSdk.clientsSignerMod.apiVersion] = js.native
  var simpledb: js.UndefOr[typingsSlinky.awsDashSdk.clientsSimpledbMod.apiVersion] = js.native
  var sms: js.UndefOr[typingsSlinky.awsDashSdk.clientsSmsMod.apiVersion] = js.native
  var snowball: js.UndefOr[typingsSlinky.awsDashSdk.clientsSnowballMod.apiVersion] = js.native
  var sns: js.UndefOr[typingsSlinky.awsDashSdk.clientsSnsMod.apiVersion] = js.native
  var sqs: js.UndefOr[typingsSlinky.awsDashSdk.clientsSqsMod.apiVersion] = js.native
  var ssm: js.UndefOr[typingsSlinky.awsDashSdk.clientsSsmMod.apiVersion] = js.native
  var sso: js.UndefOr[typingsSlinky.awsDashSdk.clientsSsoMod.apiVersion] = js.native
  var ssooidc: js.UndefOr[typingsSlinky.awsDashSdk.clientsSsooidcMod.apiVersion] = js.native
  var stepfunctions: js.UndefOr[typingsSlinky.awsDashSdk.clientsStepfunctionsMod.apiVersion] = js.native
  var storagegateway: js.UndefOr[typingsSlinky.awsDashSdk.clientsStoragegatewayMod.apiVersion] = js.native
  var sts: js.UndefOr[typingsSlinky.awsDashSdk.clientsStsMod.apiVersion] = js.native
  var support: js.UndefOr[typingsSlinky.awsDashSdk.clientsSupportMod.apiVersion] = js.native
  var swf: js.UndefOr[typingsSlinky.awsDashSdk.clientsSwfMod.apiVersion] = js.native
  var textract: js.UndefOr[typingsSlinky.awsDashSdk.clientsTextractMod.apiVersion] = js.native
  var transcribeservice: js.UndefOr[typingsSlinky.awsDashSdk.clientsTranscribeserviceMod.apiVersion] = js.native
  var transfer: js.UndefOr[typingsSlinky.awsDashSdk.clientsTransferMod.apiVersion] = js.native
  var translate: js.UndefOr[typingsSlinky.awsDashSdk.clientsTranslateMod.apiVersion] = js.native
  var waf: js.UndefOr[typingsSlinky.awsDashSdk.clientsWafMod.apiVersion] = js.native
  var wafregional: js.UndefOr[typingsSlinky.awsDashSdk.clientsWafregionalMod.apiVersion] = js.native
  var wafv2: js.UndefOr[typingsSlinky.awsDashSdk.clientsWafv2Mod.apiVersion] = js.native
  var workdocs: js.UndefOr[typingsSlinky.awsDashSdk.clientsWorkdocsMod.apiVersion] = js.native
  var worklink: js.UndefOr[typingsSlinky.awsDashSdk.clientsWorklinkMod.apiVersion] = js.native
  var workmail: js.UndefOr[typingsSlinky.awsDashSdk.clientsWorkmailMod.apiVersion] = js.native
  var workmailmessageflow: js.UndefOr[typingsSlinky.awsDashSdk.clientsWorkmailmessageflowMod.apiVersion] = js.native
  var workspaces: js.UndefOr[typingsSlinky.awsDashSdk.clientsWorkspacesMod.apiVersion] = js.native
  var xray: js.UndefOr[typingsSlinky.awsDashSdk.clientsXrayMod.apiVersion] = js.native
}

object ConfigurationServiceApiVersions {
  @scala.inline
  def apply(
    accessanalyzer: apiVersion = null,
    acm: typingsSlinky.awsDashSdk.clientsAcmMod.apiVersion = null,
    acmpca: typingsSlinky.awsDashSdk.clientsAcmpcaMod.apiVersion = null,
    alexaforbusiness: typingsSlinky.awsDashSdk.clientsAlexaforbusinessMod.apiVersion = null,
    amplify: typingsSlinky.awsDashSdk.clientsAmplifyMod.apiVersion = null,
    apigateway: typingsSlinky.awsDashSdk.clientsApigatewayMod.apiVersion = null,
    apigatewaymanagementapi: typingsSlinky.awsDashSdk.clientsApigatewaymanagementapiMod.apiVersion = null,
    apigatewayv2: typingsSlinky.awsDashSdk.clientsApigatewayv2Mod.apiVersion = null,
    appconfig: typingsSlinky.awsDashSdk.clientsAppconfigMod.apiVersion = null,
    applicationautoscaling: typingsSlinky.awsDashSdk.clientsApplicationautoscalingMod.apiVersion = null,
    applicationinsights: typingsSlinky.awsDashSdk.clientsApplicationinsightsMod.apiVersion = null,
    appmesh: typingsSlinky.awsDashSdk.clientsAppmeshMod.apiVersion = null,
    appstream: typingsSlinky.awsDashSdk.clientsAppstreamMod.apiVersion = null,
    appsync: typingsSlinky.awsDashSdk.clientsAppsyncMod.apiVersion = null,
    athena: typingsSlinky.awsDashSdk.clientsAthenaMod.apiVersion = null,
    augmentedairuntime: typingsSlinky.awsDashSdk.clientsAugmentedairuntimeMod.apiVersion = null,
    autoscaling: typingsSlinky.awsDashSdk.clientsAutoscalingMod.apiVersion = null,
    autoscalingplans: typingsSlinky.awsDashSdk.clientsAutoscalingplansMod.apiVersion = null,
    backup: typingsSlinky.awsDashSdk.clientsBackupMod.apiVersion = null,
    batch: typingsSlinky.awsDashSdk.clientsBatchMod.apiVersion = null,
    budgets: typingsSlinky.awsDashSdk.clientsBudgetsMod.apiVersion = null,
    chime: typingsSlinky.awsDashSdk.clientsChimeMod.apiVersion = null,
    cloud9: typingsSlinky.awsDashSdk.clientsCloud9Mod.apiVersion = null,
    clouddirectory: typingsSlinky.awsDashSdk.clientsClouddirectoryMod.apiVersion = null,
    cloudformation: typingsSlinky.awsDashSdk.clientsCloudformationMod.apiVersion = null,
    cloudfront: typingsSlinky.awsDashSdk.clientsCloudfrontMod.apiVersion = null,
    cloudhsm: typingsSlinky.awsDashSdk.clientsCloudhsmMod.apiVersion = null,
    cloudhsmv2: typingsSlinky.awsDashSdk.clientsCloudhsmv2Mod.apiVersion = null,
    cloudsearch: typingsSlinky.awsDashSdk.clientsCloudsearchMod.apiVersion = null,
    cloudsearchdomain: typingsSlinky.awsDashSdk.clientsCloudsearchdomainMod.apiVersion = null,
    cloudtrail: typingsSlinky.awsDashSdk.clientsCloudtrailMod.apiVersion = null,
    cloudwatch: typingsSlinky.awsDashSdk.clientsCloudwatchMod.apiVersion = null,
    cloudwatchevents: typingsSlinky.awsDashSdk.clientsCloudwatcheventsMod.apiVersion = null,
    cloudwatchlogs: typingsSlinky.awsDashSdk.clientsCloudwatchlogsMod.apiVersion = null,
    codebuild: typingsSlinky.awsDashSdk.clientsCodebuildMod.apiVersion = null,
    codecommit: typingsSlinky.awsDashSdk.clientsCodecommitMod.apiVersion = null,
    codedeploy: typingsSlinky.awsDashSdk.clientsCodedeployMod.apiVersion = null,
    codeguruprofiler: typingsSlinky.awsDashSdk.clientsCodeguruprofilerMod.apiVersion = null,
    codegurureviewer: typingsSlinky.awsDashSdk.clientsCodegurureviewerMod.apiVersion = null,
    codepipeline: typingsSlinky.awsDashSdk.clientsCodepipelineMod.apiVersion = null,
    codestar: typingsSlinky.awsDashSdk.clientsCodestarMod.apiVersion = null,
    codestarconnections: typingsSlinky.awsDashSdk.clientsCodestarconnectionsMod.apiVersion = null,
    codestarnotifications: typingsSlinky.awsDashSdk.clientsCodestarnotificationsMod.apiVersion = null,
    cognitoidentity: typingsSlinky.awsDashSdk.clientsCognitoidentityMod.apiVersion = null,
    cognitoidentityserviceprovider: typingsSlinky.awsDashSdk.clientsCognitoidentityserviceproviderMod.apiVersion = null,
    cognitosync: typingsSlinky.awsDashSdk.clientsCognitosyncMod.apiVersion = null,
    comprehend: typingsSlinky.awsDashSdk.clientsComprehendMod.apiVersion = null,
    comprehendmedical: typingsSlinky.awsDashSdk.clientsComprehendmedicalMod.apiVersion = null,
    computeoptimizer: typingsSlinky.awsDashSdk.clientsComputeoptimizerMod.apiVersion = null,
    configservice: typingsSlinky.awsDashSdk.clientsConfigserviceMod.apiVersion = null,
    connect: typingsSlinky.awsDashSdk.clientsConnectMod.apiVersion = null,
    connectparticipant: typingsSlinky.awsDashSdk.clientsConnectparticipantMod.apiVersion = null,
    costexplorer: typingsSlinky.awsDashSdk.clientsCostexplorerMod.apiVersion = null,
    cur: typingsSlinky.awsDashSdk.clientsCurMod.apiVersion = null,
    dataexchange: typingsSlinky.awsDashSdk.clientsDataexchangeMod.apiVersion = null,
    datapipeline: typingsSlinky.awsDashSdk.clientsDatapipelineMod.apiVersion = null,
    datasync: typingsSlinky.awsDashSdk.clientsDatasyncMod.apiVersion = null,
    dax: typingsSlinky.awsDashSdk.clientsDaxMod.apiVersion = null,
    detective: typingsSlinky.awsDashSdk.clientsDetectiveMod.apiVersion = null,
    devicefarm: typingsSlinky.awsDashSdk.clientsDevicefarmMod.apiVersion = null,
    directconnect: typingsSlinky.awsDashSdk.clientsDirectconnectMod.apiVersion = null,
    directoryservice: typingsSlinky.awsDashSdk.clientsDirectoryserviceMod.apiVersion = null,
    discovery: typingsSlinky.awsDashSdk.clientsDiscoveryMod.apiVersion = null,
    dlm: typingsSlinky.awsDashSdk.clientsDlmMod.apiVersion = null,
    dms: typingsSlinky.awsDashSdk.clientsDmsMod.apiVersion = null,
    docdb: typingsSlinky.awsDashSdk.clientsDocdbMod.apiVersion = null,
    dynamodb: typingsSlinky.awsDashSdk.clientsDynamodbMod.apiVersion = null,
    dynamodbstreams: typingsSlinky.awsDashSdk.clientsDynamodbstreamsMod.apiVersion = null,
    ebs: typingsSlinky.awsDashSdk.clientsEbsMod.apiVersion = null,
    ec2: typingsSlinky.awsDashSdk.clientsEc2Mod.apiVersion = null,
    ec2instanceconnect: typingsSlinky.awsDashSdk.clientsEc2instanceconnectMod.apiVersion = null,
    ecr: typingsSlinky.awsDashSdk.clientsEcrMod.apiVersion = null,
    ecs: typingsSlinky.awsDashSdk.clientsEcsMod.apiVersion = null,
    efs: typingsSlinky.awsDashSdk.clientsEfsMod.apiVersion = null,
    eks: typingsSlinky.awsDashSdk.clientsEksMod.apiVersion = null,
    elasticache: typingsSlinky.awsDashSdk.clientsElasticacheMod.apiVersion = null,
    elasticbeanstalk: typingsSlinky.awsDashSdk.clientsElasticbeanstalkMod.apiVersion = null,
    elasticinference: typingsSlinky.awsDashSdk.clientsElasticinferenceMod.apiVersion = null,
    elastictranscoder: typingsSlinky.awsDashSdk.clientsElastictranscoderMod.apiVersion = null,
    elb: typingsSlinky.awsDashSdk.clientsElbMod.apiVersion = null,
    elbv2: typingsSlinky.awsDashSdk.clientsElbv2Mod.apiVersion = null,
    emr: typingsSlinky.awsDashSdk.clientsEmrMod.apiVersion = null,
    es: typingsSlinky.awsDashSdk.clientsEsMod.apiVersion = null,
    eventbridge: typingsSlinky.awsDashSdk.clientsEventbridgeMod.apiVersion = null,
    firehose: typingsSlinky.awsDashSdk.clientsFirehoseMod.apiVersion = null,
    fms: typingsSlinky.awsDashSdk.clientsFmsMod.apiVersion = null,
    forecastqueryservice: typingsSlinky.awsDashSdk.clientsForecastqueryserviceMod.apiVersion = null,
    forecastservice: typingsSlinky.awsDashSdk.clientsForecastserviceMod.apiVersion = null,
    frauddetector: typingsSlinky.awsDashSdk.clientsFrauddetectorMod.apiVersion = null,
    fsx: typingsSlinky.awsDashSdk.clientsFsxMod.apiVersion = null,
    gamelift: typingsSlinky.awsDashSdk.clientsGameliftMod.apiVersion = null,
    glacier: typingsSlinky.awsDashSdk.clientsGlacierMod.apiVersion = null,
    globalaccelerator: typingsSlinky.awsDashSdk.clientsGlobalacceleratorMod.apiVersion = null,
    glue: typingsSlinky.awsDashSdk.clientsGlueMod.apiVersion = null,
    greengrass: typingsSlinky.awsDashSdk.clientsGreengrassMod.apiVersion = null,
    groundstation: typingsSlinky.awsDashSdk.clientsGroundstationMod.apiVersion = null,
    guardduty: typingsSlinky.awsDashSdk.clientsGuarddutyMod.apiVersion = null,
    health: typingsSlinky.awsDashSdk.clientsHealthMod.apiVersion = null,
    iam: typingsSlinky.awsDashSdk.clientsIamMod.apiVersion = null,
    imagebuilder: typingsSlinky.awsDashSdk.clientsImagebuilderMod.apiVersion = null,
    importexport: typingsSlinky.awsDashSdk.clientsImportexportMod.apiVersion = null,
    inspector: typingsSlinky.awsDashSdk.clientsInspectorMod.apiVersion = null,
    iot: typingsSlinky.awsDashSdk.clientsIotMod.apiVersion = null,
    iot1clickdevicesservice: typingsSlinky.awsDashSdk.clientsIot1clickdevicesserviceMod.apiVersion = null,
    iot1clickprojects: typingsSlinky.awsDashSdk.clientsIot1clickprojectsMod.apiVersion = null,
    iotanalytics: typingsSlinky.awsDashSdk.clientsIotanalyticsMod.apiVersion = null,
    iotdata: typingsSlinky.awsDashSdk.clientsIotdataMod.apiVersion = null,
    iotevents: typingsSlinky.awsDashSdk.clientsIoteventsMod.apiVersion = null,
    ioteventsdata: typingsSlinky.awsDashSdk.clientsIoteventsdataMod.apiVersion = null,
    iotjobsdataplane: typingsSlinky.awsDashSdk.clientsIotjobsdataplaneMod.apiVersion = null,
    iotsecuretunneling: typingsSlinky.awsDashSdk.clientsIotsecuretunnelingMod.apiVersion = null,
    iotthingsgraph: typingsSlinky.awsDashSdk.clientsIotthingsgraphMod.apiVersion = null,
    kafka: typingsSlinky.awsDashSdk.clientsKafkaMod.apiVersion = null,
    kendra: typingsSlinky.awsDashSdk.clientsKendraMod.apiVersion = null,
    kinesis: typingsSlinky.awsDashSdk.clientsKinesisMod.apiVersion = null,
    kinesisanalytics: typingsSlinky.awsDashSdk.clientsKinesisanalyticsMod.apiVersion = null,
    kinesisanalyticsv2: typingsSlinky.awsDashSdk.clientsKinesisanalyticsv2Mod.apiVersion = null,
    kinesisvideo: typingsSlinky.awsDashSdk.clientsKinesisvideoMod.apiVersion = null,
    kinesisvideoarchivedmedia: typingsSlinky.awsDashSdk.clientsKinesisvideoarchivedmediaMod.apiVersion = null,
    kinesisvideomedia: typingsSlinky.awsDashSdk.clientsKinesisvideomediaMod.apiVersion = null,
    kinesisvideosignalingchannels: typingsSlinky.awsDashSdk.clientsKinesisvideosignalingchannelsMod.apiVersion = null,
    kms: typingsSlinky.awsDashSdk.clientsKmsMod.apiVersion = null,
    lakeformation: typingsSlinky.awsDashSdk.clientsLakeformationMod.apiVersion = null,
    lambda: typingsSlinky.awsDashSdk.clientsLambdaMod.apiVersion = null,
    lexmodelbuildingservice: typingsSlinky.awsDashSdk.clientsLexmodelbuildingserviceMod.apiVersion = null,
    lexruntime: typingsSlinky.awsDashSdk.clientsLexruntimeMod.apiVersion = null,
    licensemanager: typingsSlinky.awsDashSdk.clientsLicensemanagerMod.apiVersion = null,
    lightsail: typingsSlinky.awsDashSdk.clientsLightsailMod.apiVersion = null,
    machinelearning: typingsSlinky.awsDashSdk.clientsMachinelearningMod.apiVersion = null,
    macie: typingsSlinky.awsDashSdk.clientsMacieMod.apiVersion = null,
    managedblockchain: typingsSlinky.awsDashSdk.clientsManagedblockchainMod.apiVersion = null,
    marketplacecatalog: typingsSlinky.awsDashSdk.clientsMarketplacecatalogMod.apiVersion = null,
    marketplacecommerceanalytics: typingsSlinky.awsDashSdk.clientsMarketplacecommerceanalyticsMod.apiVersion = null,
    marketplaceentitlementservice: typingsSlinky.awsDashSdk.clientsMarketplaceentitlementserviceMod.apiVersion = null,
    marketplacemetering: typingsSlinky.awsDashSdk.clientsMarketplacemeteringMod.apiVersion = null,
    mediaconnect: typingsSlinky.awsDashSdk.clientsMediaconnectMod.apiVersion = null,
    mediaconvert: typingsSlinky.awsDashSdk.clientsMediaconvertMod.apiVersion = null,
    medialive: typingsSlinky.awsDashSdk.clientsMedialiveMod.apiVersion = null,
    mediapackage: typingsSlinky.awsDashSdk.clientsMediapackageMod.apiVersion = null,
    mediapackagevod: typingsSlinky.awsDashSdk.clientsMediapackagevodMod.apiVersion = null,
    mediastore: typingsSlinky.awsDashSdk.clientsMediastoreMod.apiVersion = null,
    mediastoredata: typingsSlinky.awsDashSdk.clientsMediastoredataMod.apiVersion = null,
    mediatailor: typingsSlinky.awsDashSdk.clientsMediatailorMod.apiVersion = null,
    migrationhub: typingsSlinky.awsDashSdk.clientsMigrationhubMod.apiVersion = null,
    migrationhubconfig: typingsSlinky.awsDashSdk.clientsMigrationhubconfigMod.apiVersion = null,
    mobile: typingsSlinky.awsDashSdk.clientsMobileMod.apiVersion = null,
    mobileanalytics: typingsSlinky.awsDashSdk.clientsMobileanalyticsMod.apiVersion = null,
    mq: typingsSlinky.awsDashSdk.clientsMqMod.apiVersion = null,
    mturk: typingsSlinky.awsDashSdk.clientsMturkMod.apiVersion = null,
    neptune: typingsSlinky.awsDashSdk.clientsNeptuneMod.apiVersion = null,
    networkmanager: typingsSlinky.awsDashSdk.clientsNetworkmanagerMod.apiVersion = null,
    opsworks: typingsSlinky.awsDashSdk.clientsOpsworksMod.apiVersion = null,
    opsworkscm: typingsSlinky.awsDashSdk.clientsOpsworkscmMod.apiVersion = null,
    organizations: typingsSlinky.awsDashSdk.clientsOrganizationsMod.apiVersion = null,
    outposts: typingsSlinky.awsDashSdk.clientsOutpostsMod.apiVersion = null,
    personalize: typingsSlinky.awsDashSdk.clientsPersonalizeMod.apiVersion = null,
    personalizeevents: typingsSlinky.awsDashSdk.clientsPersonalizeeventsMod.apiVersion = null,
    personalizeruntime: typingsSlinky.awsDashSdk.clientsPersonalizeruntimeMod.apiVersion = null,
    pi: typingsSlinky.awsDashSdk.clientsPiMod.apiVersion = null,
    pinpoint: typingsSlinky.awsDashSdk.clientsPinpointMod.apiVersion = null,
    pinpointemail: typingsSlinky.awsDashSdk.clientsPinpointemailMod.apiVersion = null,
    pinpointsmsvoice: typingsSlinky.awsDashSdk.clientsPinpointsmsvoiceMod.apiVersion = null,
    polly: typingsSlinky.awsDashSdk.clientsPollyMod.apiVersion = null,
    pricing: typingsSlinky.awsDashSdk.clientsPricingMod.apiVersion = null,
    qldb: typingsSlinky.awsDashSdk.clientsQldbMod.apiVersion = null,
    qldbsession: typingsSlinky.awsDashSdk.clientsQldbsessionMod.apiVersion = null,
    quicksight: typingsSlinky.awsDashSdk.clientsQuicksightMod.apiVersion = null,
    ram: typingsSlinky.awsDashSdk.clientsRamMod.apiVersion = null,
    rds: typingsSlinky.awsDashSdk.clientsRdsMod.apiVersion = null,
    rdsdataservice: typingsSlinky.awsDashSdk.clientsRdsdataserviceMod.apiVersion = null,
    redshift: typingsSlinky.awsDashSdk.clientsRedshiftMod.apiVersion = null,
    rekognition: typingsSlinky.awsDashSdk.clientsRekognitionMod.apiVersion = null,
    resourcegroups: typingsSlinky.awsDashSdk.clientsResourcegroupsMod.apiVersion = null,
    resourcegroupstaggingapi: typingsSlinky.awsDashSdk.clientsResourcegroupstaggingapiMod.apiVersion = null,
    robomaker: typingsSlinky.awsDashSdk.clientsRobomakerMod.apiVersion = null,
    route53: typingsSlinky.awsDashSdk.clientsRoute53Mod.apiVersion = null,
    route53domains: typingsSlinky.awsDashSdk.clientsRoute53domainsMod.apiVersion = null,
    route53resolver: typingsSlinky.awsDashSdk.clientsRoute53resolverMod.apiVersion = null,
    s3: typingsSlinky.awsDashSdk.clientsS3Mod.apiVersion = null,
    s3control: typingsSlinky.awsDashSdk.clientsS3controlMod.apiVersion = null,
    sagemaker: typingsSlinky.awsDashSdk.clientsSagemakerMod.apiVersion = null,
    sagemakerruntime: typingsSlinky.awsDashSdk.clientsSagemakerruntimeMod.apiVersion = null,
    savingsplans: typingsSlinky.awsDashSdk.clientsSavingsplansMod.apiVersion = null,
    schemas: typingsSlinky.awsDashSdk.clientsSchemasMod.apiVersion = null,
    secretsmanager: typingsSlinky.awsDashSdk.clientsSecretsmanagerMod.apiVersion = null,
    securityhub: typingsSlinky.awsDashSdk.clientsSecurityhubMod.apiVersion = null,
    serverlessapplicationrepository: typingsSlinky.awsDashSdk.clientsServerlessapplicationrepositoryMod.apiVersion = null,
    servicecatalog: typingsSlinky.awsDashSdk.clientsServicecatalogMod.apiVersion = null,
    servicediscovery: typingsSlinky.awsDashSdk.clientsServicediscoveryMod.apiVersion = null,
    servicequotas: typingsSlinky.awsDashSdk.clientsServicequotasMod.apiVersion = null,
    ses: typingsSlinky.awsDashSdk.clientsSesMod.apiVersion = null,
    sesv2: typingsSlinky.awsDashSdk.clientsSesv2Mod.apiVersion = null,
    shield: typingsSlinky.awsDashSdk.clientsShieldMod.apiVersion = null,
    signer: typingsSlinky.awsDashSdk.clientsSignerMod.apiVersion = null,
    simpledb: typingsSlinky.awsDashSdk.clientsSimpledbMod.apiVersion = null,
    sms: typingsSlinky.awsDashSdk.clientsSmsMod.apiVersion = null,
    snowball: typingsSlinky.awsDashSdk.clientsSnowballMod.apiVersion = null,
    sns: typingsSlinky.awsDashSdk.clientsSnsMod.apiVersion = null,
    sqs: typingsSlinky.awsDashSdk.clientsSqsMod.apiVersion = null,
    ssm: typingsSlinky.awsDashSdk.clientsSsmMod.apiVersion = null,
    sso: typingsSlinky.awsDashSdk.clientsSsoMod.apiVersion = null,
    ssooidc: typingsSlinky.awsDashSdk.clientsSsooidcMod.apiVersion = null,
    stepfunctions: typingsSlinky.awsDashSdk.clientsStepfunctionsMod.apiVersion = null,
    storagegateway: typingsSlinky.awsDashSdk.clientsStoragegatewayMod.apiVersion = null,
    sts: typingsSlinky.awsDashSdk.clientsStsMod.apiVersion = null,
    support: typingsSlinky.awsDashSdk.clientsSupportMod.apiVersion = null,
    swf: typingsSlinky.awsDashSdk.clientsSwfMod.apiVersion = null,
    textract: typingsSlinky.awsDashSdk.clientsTextractMod.apiVersion = null,
    transcribeservice: typingsSlinky.awsDashSdk.clientsTranscribeserviceMod.apiVersion = null,
    transfer: typingsSlinky.awsDashSdk.clientsTransferMod.apiVersion = null,
    translate: typingsSlinky.awsDashSdk.clientsTranslateMod.apiVersion = null,
    waf: typingsSlinky.awsDashSdk.clientsWafMod.apiVersion = null,
    wafregional: typingsSlinky.awsDashSdk.clientsWafregionalMod.apiVersion = null,
    wafv2: typingsSlinky.awsDashSdk.clientsWafv2Mod.apiVersion = null,
    workdocs: typingsSlinky.awsDashSdk.clientsWorkdocsMod.apiVersion = null,
    worklink: typingsSlinky.awsDashSdk.clientsWorklinkMod.apiVersion = null,
    workmail: typingsSlinky.awsDashSdk.clientsWorkmailMod.apiVersion = null,
    workmailmessageflow: typingsSlinky.awsDashSdk.clientsWorkmailmessageflowMod.apiVersion = null,
    workspaces: typingsSlinky.awsDashSdk.clientsWorkspacesMod.apiVersion = null,
    xray: typingsSlinky.awsDashSdk.clientsXrayMod.apiVersion = null
  ): ConfigurationServiceApiVersions = {
    val __obj = js.Dynamic.literal()
    if (accessanalyzer != null) __obj.updateDynamic("accessanalyzer")(accessanalyzer.asInstanceOf[js.Any])
    if (acm != null) __obj.updateDynamic("acm")(acm.asInstanceOf[js.Any])
    if (acmpca != null) __obj.updateDynamic("acmpca")(acmpca.asInstanceOf[js.Any])
    if (alexaforbusiness != null) __obj.updateDynamic("alexaforbusiness")(alexaforbusiness.asInstanceOf[js.Any])
    if (amplify != null) __obj.updateDynamic("amplify")(amplify.asInstanceOf[js.Any])
    if (apigateway != null) __obj.updateDynamic("apigateway")(apigateway.asInstanceOf[js.Any])
    if (apigatewaymanagementapi != null) __obj.updateDynamic("apigatewaymanagementapi")(apigatewaymanagementapi.asInstanceOf[js.Any])
    if (apigatewayv2 != null) __obj.updateDynamic("apigatewayv2")(apigatewayv2.asInstanceOf[js.Any])
    if (appconfig != null) __obj.updateDynamic("appconfig")(appconfig.asInstanceOf[js.Any])
    if (applicationautoscaling != null) __obj.updateDynamic("applicationautoscaling")(applicationautoscaling.asInstanceOf[js.Any])
    if (applicationinsights != null) __obj.updateDynamic("applicationinsights")(applicationinsights.asInstanceOf[js.Any])
    if (appmesh != null) __obj.updateDynamic("appmesh")(appmesh.asInstanceOf[js.Any])
    if (appstream != null) __obj.updateDynamic("appstream")(appstream.asInstanceOf[js.Any])
    if (appsync != null) __obj.updateDynamic("appsync")(appsync.asInstanceOf[js.Any])
    if (athena != null) __obj.updateDynamic("athena")(athena.asInstanceOf[js.Any])
    if (augmentedairuntime != null) __obj.updateDynamic("augmentedairuntime")(augmentedairuntime.asInstanceOf[js.Any])
    if (autoscaling != null) __obj.updateDynamic("autoscaling")(autoscaling.asInstanceOf[js.Any])
    if (autoscalingplans != null) __obj.updateDynamic("autoscalingplans")(autoscalingplans.asInstanceOf[js.Any])
    if (backup != null) __obj.updateDynamic("backup")(backup.asInstanceOf[js.Any])
    if (batch != null) __obj.updateDynamic("batch")(batch.asInstanceOf[js.Any])
    if (budgets != null) __obj.updateDynamic("budgets")(budgets.asInstanceOf[js.Any])
    if (chime != null) __obj.updateDynamic("chime")(chime.asInstanceOf[js.Any])
    if (cloud9 != null) __obj.updateDynamic("cloud9")(cloud9.asInstanceOf[js.Any])
    if (clouddirectory != null) __obj.updateDynamic("clouddirectory")(clouddirectory.asInstanceOf[js.Any])
    if (cloudformation != null) __obj.updateDynamic("cloudformation")(cloudformation.asInstanceOf[js.Any])
    if (cloudfront != null) __obj.updateDynamic("cloudfront")(cloudfront.asInstanceOf[js.Any])
    if (cloudhsm != null) __obj.updateDynamic("cloudhsm")(cloudhsm.asInstanceOf[js.Any])
    if (cloudhsmv2 != null) __obj.updateDynamic("cloudhsmv2")(cloudhsmv2.asInstanceOf[js.Any])
    if (cloudsearch != null) __obj.updateDynamic("cloudsearch")(cloudsearch.asInstanceOf[js.Any])
    if (cloudsearchdomain != null) __obj.updateDynamic("cloudsearchdomain")(cloudsearchdomain.asInstanceOf[js.Any])
    if (cloudtrail != null) __obj.updateDynamic("cloudtrail")(cloudtrail.asInstanceOf[js.Any])
    if (cloudwatch != null) __obj.updateDynamic("cloudwatch")(cloudwatch.asInstanceOf[js.Any])
    if (cloudwatchevents != null) __obj.updateDynamic("cloudwatchevents")(cloudwatchevents.asInstanceOf[js.Any])
    if (cloudwatchlogs != null) __obj.updateDynamic("cloudwatchlogs")(cloudwatchlogs.asInstanceOf[js.Any])
    if (codebuild != null) __obj.updateDynamic("codebuild")(codebuild.asInstanceOf[js.Any])
    if (codecommit != null) __obj.updateDynamic("codecommit")(codecommit.asInstanceOf[js.Any])
    if (codedeploy != null) __obj.updateDynamic("codedeploy")(codedeploy.asInstanceOf[js.Any])
    if (codeguruprofiler != null) __obj.updateDynamic("codeguruprofiler")(codeguruprofiler.asInstanceOf[js.Any])
    if (codegurureviewer != null) __obj.updateDynamic("codegurureviewer")(codegurureviewer.asInstanceOf[js.Any])
    if (codepipeline != null) __obj.updateDynamic("codepipeline")(codepipeline.asInstanceOf[js.Any])
    if (codestar != null) __obj.updateDynamic("codestar")(codestar.asInstanceOf[js.Any])
    if (codestarconnections != null) __obj.updateDynamic("codestarconnections")(codestarconnections.asInstanceOf[js.Any])
    if (codestarnotifications != null) __obj.updateDynamic("codestarnotifications")(codestarnotifications.asInstanceOf[js.Any])
    if (cognitoidentity != null) __obj.updateDynamic("cognitoidentity")(cognitoidentity.asInstanceOf[js.Any])
    if (cognitoidentityserviceprovider != null) __obj.updateDynamic("cognitoidentityserviceprovider")(cognitoidentityserviceprovider.asInstanceOf[js.Any])
    if (cognitosync != null) __obj.updateDynamic("cognitosync")(cognitosync.asInstanceOf[js.Any])
    if (comprehend != null) __obj.updateDynamic("comprehend")(comprehend.asInstanceOf[js.Any])
    if (comprehendmedical != null) __obj.updateDynamic("comprehendmedical")(comprehendmedical.asInstanceOf[js.Any])
    if (computeoptimizer != null) __obj.updateDynamic("computeoptimizer")(computeoptimizer.asInstanceOf[js.Any])
    if (configservice != null) __obj.updateDynamic("configservice")(configservice.asInstanceOf[js.Any])
    if (connect != null) __obj.updateDynamic("connect")(connect.asInstanceOf[js.Any])
    if (connectparticipant != null) __obj.updateDynamic("connectparticipant")(connectparticipant.asInstanceOf[js.Any])
    if (costexplorer != null) __obj.updateDynamic("costexplorer")(costexplorer.asInstanceOf[js.Any])
    if (cur != null) __obj.updateDynamic("cur")(cur.asInstanceOf[js.Any])
    if (dataexchange != null) __obj.updateDynamic("dataexchange")(dataexchange.asInstanceOf[js.Any])
    if (datapipeline != null) __obj.updateDynamic("datapipeline")(datapipeline.asInstanceOf[js.Any])
    if (datasync != null) __obj.updateDynamic("datasync")(datasync.asInstanceOf[js.Any])
    if (dax != null) __obj.updateDynamic("dax")(dax.asInstanceOf[js.Any])
    if (detective != null) __obj.updateDynamic("detective")(detective.asInstanceOf[js.Any])
    if (devicefarm != null) __obj.updateDynamic("devicefarm")(devicefarm.asInstanceOf[js.Any])
    if (directconnect != null) __obj.updateDynamic("directconnect")(directconnect.asInstanceOf[js.Any])
    if (directoryservice != null) __obj.updateDynamic("directoryservice")(directoryservice.asInstanceOf[js.Any])
    if (discovery != null) __obj.updateDynamic("discovery")(discovery.asInstanceOf[js.Any])
    if (dlm != null) __obj.updateDynamic("dlm")(dlm.asInstanceOf[js.Any])
    if (dms != null) __obj.updateDynamic("dms")(dms.asInstanceOf[js.Any])
    if (docdb != null) __obj.updateDynamic("docdb")(docdb.asInstanceOf[js.Any])
    if (dynamodb != null) __obj.updateDynamic("dynamodb")(dynamodb.asInstanceOf[js.Any])
    if (dynamodbstreams != null) __obj.updateDynamic("dynamodbstreams")(dynamodbstreams.asInstanceOf[js.Any])
    if (ebs != null) __obj.updateDynamic("ebs")(ebs.asInstanceOf[js.Any])
    if (ec2 != null) __obj.updateDynamic("ec2")(ec2.asInstanceOf[js.Any])
    if (ec2instanceconnect != null) __obj.updateDynamic("ec2instanceconnect")(ec2instanceconnect.asInstanceOf[js.Any])
    if (ecr != null) __obj.updateDynamic("ecr")(ecr.asInstanceOf[js.Any])
    if (ecs != null) __obj.updateDynamic("ecs")(ecs.asInstanceOf[js.Any])
    if (efs != null) __obj.updateDynamic("efs")(efs.asInstanceOf[js.Any])
    if (eks != null) __obj.updateDynamic("eks")(eks.asInstanceOf[js.Any])
    if (elasticache != null) __obj.updateDynamic("elasticache")(elasticache.asInstanceOf[js.Any])
    if (elasticbeanstalk != null) __obj.updateDynamic("elasticbeanstalk")(elasticbeanstalk.asInstanceOf[js.Any])
    if (elasticinference != null) __obj.updateDynamic("elasticinference")(elasticinference.asInstanceOf[js.Any])
    if (elastictranscoder != null) __obj.updateDynamic("elastictranscoder")(elastictranscoder.asInstanceOf[js.Any])
    if (elb != null) __obj.updateDynamic("elb")(elb.asInstanceOf[js.Any])
    if (elbv2 != null) __obj.updateDynamic("elbv2")(elbv2.asInstanceOf[js.Any])
    if (emr != null) __obj.updateDynamic("emr")(emr.asInstanceOf[js.Any])
    if (es != null) __obj.updateDynamic("es")(es.asInstanceOf[js.Any])
    if (eventbridge != null) __obj.updateDynamic("eventbridge")(eventbridge.asInstanceOf[js.Any])
    if (firehose != null) __obj.updateDynamic("firehose")(firehose.asInstanceOf[js.Any])
    if (fms != null) __obj.updateDynamic("fms")(fms.asInstanceOf[js.Any])
    if (forecastqueryservice != null) __obj.updateDynamic("forecastqueryservice")(forecastqueryservice.asInstanceOf[js.Any])
    if (forecastservice != null) __obj.updateDynamic("forecastservice")(forecastservice.asInstanceOf[js.Any])
    if (frauddetector != null) __obj.updateDynamic("frauddetector")(frauddetector.asInstanceOf[js.Any])
    if (fsx != null) __obj.updateDynamic("fsx")(fsx.asInstanceOf[js.Any])
    if (gamelift != null) __obj.updateDynamic("gamelift")(gamelift.asInstanceOf[js.Any])
    if (glacier != null) __obj.updateDynamic("glacier")(glacier.asInstanceOf[js.Any])
    if (globalaccelerator != null) __obj.updateDynamic("globalaccelerator")(globalaccelerator.asInstanceOf[js.Any])
    if (glue != null) __obj.updateDynamic("glue")(glue.asInstanceOf[js.Any])
    if (greengrass != null) __obj.updateDynamic("greengrass")(greengrass.asInstanceOf[js.Any])
    if (groundstation != null) __obj.updateDynamic("groundstation")(groundstation.asInstanceOf[js.Any])
    if (guardduty != null) __obj.updateDynamic("guardduty")(guardduty.asInstanceOf[js.Any])
    if (health != null) __obj.updateDynamic("health")(health.asInstanceOf[js.Any])
    if (iam != null) __obj.updateDynamic("iam")(iam.asInstanceOf[js.Any])
    if (imagebuilder != null) __obj.updateDynamic("imagebuilder")(imagebuilder.asInstanceOf[js.Any])
    if (importexport != null) __obj.updateDynamic("importexport")(importexport.asInstanceOf[js.Any])
    if (inspector != null) __obj.updateDynamic("inspector")(inspector.asInstanceOf[js.Any])
    if (iot != null) __obj.updateDynamic("iot")(iot.asInstanceOf[js.Any])
    if (iot1clickdevicesservice != null) __obj.updateDynamic("iot1clickdevicesservice")(iot1clickdevicesservice.asInstanceOf[js.Any])
    if (iot1clickprojects != null) __obj.updateDynamic("iot1clickprojects")(iot1clickprojects.asInstanceOf[js.Any])
    if (iotanalytics != null) __obj.updateDynamic("iotanalytics")(iotanalytics.asInstanceOf[js.Any])
    if (iotdata != null) __obj.updateDynamic("iotdata")(iotdata.asInstanceOf[js.Any])
    if (iotevents != null) __obj.updateDynamic("iotevents")(iotevents.asInstanceOf[js.Any])
    if (ioteventsdata != null) __obj.updateDynamic("ioteventsdata")(ioteventsdata.asInstanceOf[js.Any])
    if (iotjobsdataplane != null) __obj.updateDynamic("iotjobsdataplane")(iotjobsdataplane.asInstanceOf[js.Any])
    if (iotsecuretunneling != null) __obj.updateDynamic("iotsecuretunneling")(iotsecuretunneling.asInstanceOf[js.Any])
    if (iotthingsgraph != null) __obj.updateDynamic("iotthingsgraph")(iotthingsgraph.asInstanceOf[js.Any])
    if (kafka != null) __obj.updateDynamic("kafka")(kafka.asInstanceOf[js.Any])
    if (kendra != null) __obj.updateDynamic("kendra")(kendra.asInstanceOf[js.Any])
    if (kinesis != null) __obj.updateDynamic("kinesis")(kinesis.asInstanceOf[js.Any])
    if (kinesisanalytics != null) __obj.updateDynamic("kinesisanalytics")(kinesisanalytics.asInstanceOf[js.Any])
    if (kinesisanalyticsv2 != null) __obj.updateDynamic("kinesisanalyticsv2")(kinesisanalyticsv2.asInstanceOf[js.Any])
    if (kinesisvideo != null) __obj.updateDynamic("kinesisvideo")(kinesisvideo.asInstanceOf[js.Any])
    if (kinesisvideoarchivedmedia != null) __obj.updateDynamic("kinesisvideoarchivedmedia")(kinesisvideoarchivedmedia.asInstanceOf[js.Any])
    if (kinesisvideomedia != null) __obj.updateDynamic("kinesisvideomedia")(kinesisvideomedia.asInstanceOf[js.Any])
    if (kinesisvideosignalingchannels != null) __obj.updateDynamic("kinesisvideosignalingchannels")(kinesisvideosignalingchannels.asInstanceOf[js.Any])
    if (kms != null) __obj.updateDynamic("kms")(kms.asInstanceOf[js.Any])
    if (lakeformation != null) __obj.updateDynamic("lakeformation")(lakeformation.asInstanceOf[js.Any])
    if (lambda != null) __obj.updateDynamic("lambda")(lambda.asInstanceOf[js.Any])
    if (lexmodelbuildingservice != null) __obj.updateDynamic("lexmodelbuildingservice")(lexmodelbuildingservice.asInstanceOf[js.Any])
    if (lexruntime != null) __obj.updateDynamic("lexruntime")(lexruntime.asInstanceOf[js.Any])
    if (licensemanager != null) __obj.updateDynamic("licensemanager")(licensemanager.asInstanceOf[js.Any])
    if (lightsail != null) __obj.updateDynamic("lightsail")(lightsail.asInstanceOf[js.Any])
    if (machinelearning != null) __obj.updateDynamic("machinelearning")(machinelearning.asInstanceOf[js.Any])
    if (macie != null) __obj.updateDynamic("macie")(macie.asInstanceOf[js.Any])
    if (managedblockchain != null) __obj.updateDynamic("managedblockchain")(managedblockchain.asInstanceOf[js.Any])
    if (marketplacecatalog != null) __obj.updateDynamic("marketplacecatalog")(marketplacecatalog.asInstanceOf[js.Any])
    if (marketplacecommerceanalytics != null) __obj.updateDynamic("marketplacecommerceanalytics")(marketplacecommerceanalytics.asInstanceOf[js.Any])
    if (marketplaceentitlementservice != null) __obj.updateDynamic("marketplaceentitlementservice")(marketplaceentitlementservice.asInstanceOf[js.Any])
    if (marketplacemetering != null) __obj.updateDynamic("marketplacemetering")(marketplacemetering.asInstanceOf[js.Any])
    if (mediaconnect != null) __obj.updateDynamic("mediaconnect")(mediaconnect.asInstanceOf[js.Any])
    if (mediaconvert != null) __obj.updateDynamic("mediaconvert")(mediaconvert.asInstanceOf[js.Any])
    if (medialive != null) __obj.updateDynamic("medialive")(medialive.asInstanceOf[js.Any])
    if (mediapackage != null) __obj.updateDynamic("mediapackage")(mediapackage.asInstanceOf[js.Any])
    if (mediapackagevod != null) __obj.updateDynamic("mediapackagevod")(mediapackagevod.asInstanceOf[js.Any])
    if (mediastore != null) __obj.updateDynamic("mediastore")(mediastore.asInstanceOf[js.Any])
    if (mediastoredata != null) __obj.updateDynamic("mediastoredata")(mediastoredata.asInstanceOf[js.Any])
    if (mediatailor != null) __obj.updateDynamic("mediatailor")(mediatailor.asInstanceOf[js.Any])
    if (migrationhub != null) __obj.updateDynamic("migrationhub")(migrationhub.asInstanceOf[js.Any])
    if (migrationhubconfig != null) __obj.updateDynamic("migrationhubconfig")(migrationhubconfig.asInstanceOf[js.Any])
    if (mobile != null) __obj.updateDynamic("mobile")(mobile.asInstanceOf[js.Any])
    if (mobileanalytics != null) __obj.updateDynamic("mobileanalytics")(mobileanalytics.asInstanceOf[js.Any])
    if (mq != null) __obj.updateDynamic("mq")(mq.asInstanceOf[js.Any])
    if (mturk != null) __obj.updateDynamic("mturk")(mturk.asInstanceOf[js.Any])
    if (neptune != null) __obj.updateDynamic("neptune")(neptune.asInstanceOf[js.Any])
    if (networkmanager != null) __obj.updateDynamic("networkmanager")(networkmanager.asInstanceOf[js.Any])
    if (opsworks != null) __obj.updateDynamic("opsworks")(opsworks.asInstanceOf[js.Any])
    if (opsworkscm != null) __obj.updateDynamic("opsworkscm")(opsworkscm.asInstanceOf[js.Any])
    if (organizations != null) __obj.updateDynamic("organizations")(organizations.asInstanceOf[js.Any])
    if (outposts != null) __obj.updateDynamic("outposts")(outposts.asInstanceOf[js.Any])
    if (personalize != null) __obj.updateDynamic("personalize")(personalize.asInstanceOf[js.Any])
    if (personalizeevents != null) __obj.updateDynamic("personalizeevents")(personalizeevents.asInstanceOf[js.Any])
    if (personalizeruntime != null) __obj.updateDynamic("personalizeruntime")(personalizeruntime.asInstanceOf[js.Any])
    if (pi != null) __obj.updateDynamic("pi")(pi.asInstanceOf[js.Any])
    if (pinpoint != null) __obj.updateDynamic("pinpoint")(pinpoint.asInstanceOf[js.Any])
    if (pinpointemail != null) __obj.updateDynamic("pinpointemail")(pinpointemail.asInstanceOf[js.Any])
    if (pinpointsmsvoice != null) __obj.updateDynamic("pinpointsmsvoice")(pinpointsmsvoice.asInstanceOf[js.Any])
    if (polly != null) __obj.updateDynamic("polly")(polly.asInstanceOf[js.Any])
    if (pricing != null) __obj.updateDynamic("pricing")(pricing.asInstanceOf[js.Any])
    if (qldb != null) __obj.updateDynamic("qldb")(qldb.asInstanceOf[js.Any])
    if (qldbsession != null) __obj.updateDynamic("qldbsession")(qldbsession.asInstanceOf[js.Any])
    if (quicksight != null) __obj.updateDynamic("quicksight")(quicksight.asInstanceOf[js.Any])
    if (ram != null) __obj.updateDynamic("ram")(ram.asInstanceOf[js.Any])
    if (rds != null) __obj.updateDynamic("rds")(rds.asInstanceOf[js.Any])
    if (rdsdataservice != null) __obj.updateDynamic("rdsdataservice")(rdsdataservice.asInstanceOf[js.Any])
    if (redshift != null) __obj.updateDynamic("redshift")(redshift.asInstanceOf[js.Any])
    if (rekognition != null) __obj.updateDynamic("rekognition")(rekognition.asInstanceOf[js.Any])
    if (resourcegroups != null) __obj.updateDynamic("resourcegroups")(resourcegroups.asInstanceOf[js.Any])
    if (resourcegroupstaggingapi != null) __obj.updateDynamic("resourcegroupstaggingapi")(resourcegroupstaggingapi.asInstanceOf[js.Any])
    if (robomaker != null) __obj.updateDynamic("robomaker")(robomaker.asInstanceOf[js.Any])
    if (route53 != null) __obj.updateDynamic("route53")(route53.asInstanceOf[js.Any])
    if (route53domains != null) __obj.updateDynamic("route53domains")(route53domains.asInstanceOf[js.Any])
    if (route53resolver != null) __obj.updateDynamic("route53resolver")(route53resolver.asInstanceOf[js.Any])
    if (s3 != null) __obj.updateDynamic("s3")(s3.asInstanceOf[js.Any])
    if (s3control != null) __obj.updateDynamic("s3control")(s3control.asInstanceOf[js.Any])
    if (sagemaker != null) __obj.updateDynamic("sagemaker")(sagemaker.asInstanceOf[js.Any])
    if (sagemakerruntime != null) __obj.updateDynamic("sagemakerruntime")(sagemakerruntime.asInstanceOf[js.Any])
    if (savingsplans != null) __obj.updateDynamic("savingsplans")(savingsplans.asInstanceOf[js.Any])
    if (schemas != null) __obj.updateDynamic("schemas")(schemas.asInstanceOf[js.Any])
    if (secretsmanager != null) __obj.updateDynamic("secretsmanager")(secretsmanager.asInstanceOf[js.Any])
    if (securityhub != null) __obj.updateDynamic("securityhub")(securityhub.asInstanceOf[js.Any])
    if (serverlessapplicationrepository != null) __obj.updateDynamic("serverlessapplicationrepository")(serverlessapplicationrepository.asInstanceOf[js.Any])
    if (servicecatalog != null) __obj.updateDynamic("servicecatalog")(servicecatalog.asInstanceOf[js.Any])
    if (servicediscovery != null) __obj.updateDynamic("servicediscovery")(servicediscovery.asInstanceOf[js.Any])
    if (servicequotas != null) __obj.updateDynamic("servicequotas")(servicequotas.asInstanceOf[js.Any])
    if (ses != null) __obj.updateDynamic("ses")(ses.asInstanceOf[js.Any])
    if (sesv2 != null) __obj.updateDynamic("sesv2")(sesv2.asInstanceOf[js.Any])
    if (shield != null) __obj.updateDynamic("shield")(shield.asInstanceOf[js.Any])
    if (signer != null) __obj.updateDynamic("signer")(signer.asInstanceOf[js.Any])
    if (simpledb != null) __obj.updateDynamic("simpledb")(simpledb.asInstanceOf[js.Any])
    if (sms != null) __obj.updateDynamic("sms")(sms.asInstanceOf[js.Any])
    if (snowball != null) __obj.updateDynamic("snowball")(snowball.asInstanceOf[js.Any])
    if (sns != null) __obj.updateDynamic("sns")(sns.asInstanceOf[js.Any])
    if (sqs != null) __obj.updateDynamic("sqs")(sqs.asInstanceOf[js.Any])
    if (ssm != null) __obj.updateDynamic("ssm")(ssm.asInstanceOf[js.Any])
    if (sso != null) __obj.updateDynamic("sso")(sso.asInstanceOf[js.Any])
    if (ssooidc != null) __obj.updateDynamic("ssooidc")(ssooidc.asInstanceOf[js.Any])
    if (stepfunctions != null) __obj.updateDynamic("stepfunctions")(stepfunctions.asInstanceOf[js.Any])
    if (storagegateway != null) __obj.updateDynamic("storagegateway")(storagegateway.asInstanceOf[js.Any])
    if (sts != null) __obj.updateDynamic("sts")(sts.asInstanceOf[js.Any])
    if (support != null) __obj.updateDynamic("support")(support.asInstanceOf[js.Any])
    if (swf != null) __obj.updateDynamic("swf")(swf.asInstanceOf[js.Any])
    if (textract != null) __obj.updateDynamic("textract")(textract.asInstanceOf[js.Any])
    if (transcribeservice != null) __obj.updateDynamic("transcribeservice")(transcribeservice.asInstanceOf[js.Any])
    if (transfer != null) __obj.updateDynamic("transfer")(transfer.asInstanceOf[js.Any])
    if (translate != null) __obj.updateDynamic("translate")(translate.asInstanceOf[js.Any])
    if (waf != null) __obj.updateDynamic("waf")(waf.asInstanceOf[js.Any])
    if (wafregional != null) __obj.updateDynamic("wafregional")(wafregional.asInstanceOf[js.Any])
    if (wafv2 != null) __obj.updateDynamic("wafv2")(wafv2.asInstanceOf[js.Any])
    if (workdocs != null) __obj.updateDynamic("workdocs")(workdocs.asInstanceOf[js.Any])
    if (worklink != null) __obj.updateDynamic("worklink")(worklink.asInstanceOf[js.Any])
    if (workmail != null) __obj.updateDynamic("workmail")(workmail.asInstanceOf[js.Any])
    if (workmailmessageflow != null) __obj.updateDynamic("workmailmessageflow")(workmailmessageflow.asInstanceOf[js.Any])
    if (workspaces != null) __obj.updateDynamic("workspaces")(workspaces.asInstanceOf[js.Any])
    if (xray != null) __obj.updateDynamic("xray")(xray.asInstanceOf[js.Any])
    __obj.asInstanceOf[ConfigurationServiceApiVersions]
  }
}

