package typingsSlinky.breeze.global.breeze

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@JSGlobal("breeze.AutoGeneratedKeyType")
@js.native
class AutoGeneratedKeyType ()
  extends typingsSlinky.breeze.breeze.AutoGeneratedKeyType

/* static members */
@JSGlobal("breeze.AutoGeneratedKeyType")
@js.native
object AutoGeneratedKeyType extends js.Object {
  var Identity: typingsSlinky.breeze.breeze.AutoGeneratedKeyType = js.native
  var KeyGenerator: typingsSlinky.breeze.breeze.AutoGeneratedKeyType = js.native
  var None: typingsSlinky.breeze.breeze.AutoGeneratedKeyType = js.native
}

