package typingsSlinky.tensorflowTfjsLayers

import typingsSlinky.tensorflowTfjsLayers.advancedActivationSerializationMod.AdvancedActivationLayerSerialization
import typingsSlinky.tensorflowTfjsLayers.convolutionalDepthwiseSerializationMod.ConvolutionalDepthwiseLayerSerialization
import typingsSlinky.tensorflowTfjsLayers.convolutionalSerializationMod.ConvolutionalLayerSerialization
import typingsSlinky.tensorflowTfjsLayers.coreSerializationMod.CoreLayerSerialization
import typingsSlinky.tensorflowTfjsLayers.embeddingsSerializationMod.EmbeddingLayerSerialization
import typingsSlinky.tensorflowTfjsLayers.inputConfigMod.InputLayerSerialization
import typingsSlinky.tensorflowTfjsLayers.mergeSerializationMod.MergeLayerSerialization
import typingsSlinky.tensorflowTfjsLayers.normalizationSerializationMod.NormalizationLayerSerialization
import typingsSlinky.tensorflowTfjsLayers.paddingSerializationMod.PaddingLayerSerialization
import typingsSlinky.tensorflowTfjsLayers.poolingSerializationMod.PoolingLayerSerialization
import typingsSlinky.tensorflowTfjsLayers.recurrentSerializationMod.RecurrentLayerSerialization
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@JSImport("@tensorflow/tfjs-layers/dist/keras_format/layers/layer_serialization", JSImport.Namespace)
@js.native
object layerSerializationMod extends js.Object {
  val layerClassNames: js.Array[LayerClassName] = js.native
  type LayerClassName = /* import warning: importer.ImportType#apply Failed type conversion: @tensorflow/tfjs-layers.@tensorflow/tfjs-layers/dist/keras_format/layers/layer_serialization.LayerSerialization['class_name'] */ js.Any
  type LayerSerialization = AdvancedActivationLayerSerialization | ConvolutionalDepthwiseLayerSerialization | ConvolutionalLayerSerialization | CoreLayerSerialization | EmbeddingLayerSerialization | MergeLayerSerialization | NormalizationLayerSerialization | PaddingLayerSerialization | PoolingLayerSerialization | RecurrentLayerSerialization | InputLayerSerialization
}

