package typingsSlinky.stardustUiReactComponentEventListener.typesMod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - typingsSlinky.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.fullscreenchange
  - typingsSlinky.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.fullscreenerror
  - typingsSlinky.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.pointerlockchange
  - typingsSlinky.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.pointerlockerror
  - typingsSlinky.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.readystatechange
  - typingsSlinky.stardustUiReactComponentEventListener.stardustUiReactComponentEventListenerStrings.visibilitychange
*/
trait EventTypes extends js.Object

