package typingsSlinky.awsSdkClientDynamodbBrowser

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object typesAutoScalingTargetTrackingScalingPolicyConfigurationUpdateMod {
  type UnmarshalledAutoScalingTargetTrackingScalingPolicyConfigurationUpdate = typingsSlinky.awsSdkClientDynamodbBrowser.typesAutoScalingTargetTrackingScalingPolicyConfigurationUpdateMod.AutoScalingTargetTrackingScalingPolicyConfigurationUpdate
}
