package typingsSlinky.awsSdkClientDynamodbBrowser

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

package object typesAutoScalingTargetTrackingScalingPolicyConfigurationUpdateMod {
  
  type UnmarshalledAutoScalingTargetTrackingScalingPolicyConfigurationUpdate = typingsSlinky.awsSdkClientDynamodbBrowser.typesAutoScalingTargetTrackingScalingPolicyConfigurationUpdateMod.AutoScalingTargetTrackingScalingPolicyConfigurationUpdate
}
