package typingsSlinky.awsSdkClientCognitoIdentityBrowser.updateIdentityPoolExceptionsUnionMod

import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesConcurrentModificationExceptionMod.ConcurrentModificationException
import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesInternalErrorExceptionMod.InternalErrorException
import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesInvalidParameterExceptionMod.InvalidParameterException
import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesLimitExceededExceptionMod.LimitExceededException
import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesNotAuthorizedExceptionMod.NotAuthorizedException
import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesResourceConflictExceptionMod.ResourceConflictException
import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesResourceNotFoundExceptionMod.ResourceNotFoundException
import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesTooManyRequestsExceptionMod.TooManyRequestsException
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesInvalidParameterExceptionMod.InvalidParameterException
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesResourceNotFoundExceptionMod.ResourceNotFoundException
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesNotAuthorizedExceptionMod.NotAuthorizedException
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesResourceConflictExceptionMod.ResourceConflictException
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesTooManyRequestsExceptionMod.TooManyRequestsException
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesInternalErrorExceptionMod.InternalErrorException
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesConcurrentModificationExceptionMod.ConcurrentModificationException
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesLimitExceededExceptionMod.LimitExceededException
*/
trait UpdateIdentityPoolExceptionsUnion extends js.Object

object UpdateIdentityPoolExceptionsUnion {
  @scala.inline
  implicit def apply(value: ConcurrentModificationException): UpdateIdentityPoolExceptionsUnion = value.asInstanceOf[UpdateIdentityPoolExceptionsUnion]
  @scala.inline
  implicit def apply(value: InternalErrorException): UpdateIdentityPoolExceptionsUnion = value.asInstanceOf[UpdateIdentityPoolExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidParameterException): UpdateIdentityPoolExceptionsUnion = value.asInstanceOf[UpdateIdentityPoolExceptionsUnion]
  @scala.inline
  implicit def apply(value: LimitExceededException): UpdateIdentityPoolExceptionsUnion = value.asInstanceOf[UpdateIdentityPoolExceptionsUnion]
  @scala.inline
  implicit def apply(value: NotAuthorizedException): UpdateIdentityPoolExceptionsUnion = value.asInstanceOf[UpdateIdentityPoolExceptionsUnion]
  @scala.inline
  implicit def apply(value: ResourceConflictException): UpdateIdentityPoolExceptionsUnion = value.asInstanceOf[UpdateIdentityPoolExceptionsUnion]
  @scala.inline
  implicit def apply(value: ResourceNotFoundException): UpdateIdentityPoolExceptionsUnion = value.asInstanceOf[UpdateIdentityPoolExceptionsUnion]
  @scala.inline
  implicit def apply(value: TooManyRequestsException): UpdateIdentityPoolExceptionsUnion = value.asInstanceOf[UpdateIdentityPoolExceptionsUnion]
}

