package typingsSlinky.breeze.breeze

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait EntityTypeOptions extends js.Object {
  var autoGeneratedKeyType: js.UndefOr[AutoGeneratedKeyType] = js.native
  var dataProperties: js.UndefOr[js.Array[DataProperty]] = js.native
  var defaultResourceName: js.UndefOr[String] = js.native
  var namespace: js.UndefOr[String] = js.native
  var navigationProperties: js.UndefOr[js.Array[NavigationProperty]] = js.native
  var shortName: js.UndefOr[String] = js.native
}

object EntityTypeOptions {
  @scala.inline
  def apply(): EntityTypeOptions = {
    val __obj = js.Dynamic.literal()
    __obj.asInstanceOf[EntityTypeOptions]
  }
  @scala.inline
  implicit class EntityTypeOptionsOps[Self <: EntityTypeOptions] (val x: Self) extends AnyVal {
    @scala.inline
    def duplicate: Self = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x)).asInstanceOf[Self]
    @scala.inline
    def combineWith[Other <: js.Any](other: Other): Self with Other = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x, other.asInstanceOf[js.Any])).asInstanceOf[Self with Other]
    @scala.inline
    def withAutoGeneratedKeyType(value: AutoGeneratedKeyType): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("autoGeneratedKeyType")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutAutoGeneratedKeyType: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("autoGeneratedKeyType")(js.undefined)
        ret
    }
    @scala.inline
    def withDataProperties(value: js.Array[DataProperty]): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("dataProperties")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutDataProperties: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("dataProperties")(js.undefined)
        ret
    }
    @scala.inline
    def withDefaultResourceName(value: String): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("defaultResourceName")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutDefaultResourceName: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("defaultResourceName")(js.undefined)
        ret
    }
    @scala.inline
    def withNamespace(value: String): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("namespace")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutNamespace: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("namespace")(js.undefined)
        ret
    }
    @scala.inline
    def withNavigationProperties(value: js.Array[NavigationProperty]): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("navigationProperties")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutNavigationProperties: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("navigationProperties")(js.undefined)
        ret
    }
    @scala.inline
    def withShortName(value: String): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("shortName")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutShortName: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("shortName")(js.undefined)
        ret
    }
  }
  
}

