package typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedMod

import org.scalablytyped.runtime.TopLevel
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.$comment
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.$id
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.$ref
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.$schema
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.`else`
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.`if`
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.`then`
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.`type`
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.additionalItems
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.additionalProperties
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.allOf
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.anyOf
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.const
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.contains
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.contentEncoding
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.contentMediaType
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.default
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.definitions
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.dependencies
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.description
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.enum
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.examples
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.exclusiveMaximum
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.exclusiveMinimum
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.format
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.items
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.maxItems
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.maxLength
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.maxProperties
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.maximum
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.minItems
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.minLength
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.minProperties
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.minimum
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.multipleOf
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.not
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.oneOf
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.pattern
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.patternProperties
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.properties
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.propertyNames
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.readOnly
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.required
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.title
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.uniqueItems
import typingsSlinky.jsonDashSchemaDashTyped.jsonDashSchemaDashTypedStrings.writeOnly
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@JSImport("json-schema-typed", "JSONSchemaKeys")
@js.native
object JSONSchemaKeys
  extends TopLevel[
      js.Array[
        $comment | $id | $ref | $schema | additionalItems | additionalProperties | allOf | anyOf | const | contains | contentEncoding | contentMediaType | default | definitions | dependencies | description | `else` | enum | examples | exclusiveMaximum | exclusiveMinimum | format | `if` | items | maximum | maxItems | maxLength | maxProperties | minimum | minLength | minItems | minProperties | multipleOf | not | oneOf | pattern | patternProperties | properties | propertyNames | readOnly | required | `then` | title | `type` | uniqueItems | writeOnly
      ]
    ]

