package typingsSlinky.awsSdk.codepipelineMod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait PutThirdPartyJobSuccessResultInput extends js.Object {
  /**
    * The clientToken portion of the clientId and clientToken pair used to verify that the calling entity is allowed access to the job and its details.
    */
  var clientToken: ClientToken = js.native
  /**
    * A token generated by a job worker, such as an AWS CodeDeploy deployment ID, that a successful job provides to identify a partner action in progress. Future jobs use this token to identify the running instance of the action. It can be reused to return more information about the progress of the partner action. When the action is complete, no continuation token should be supplied.
    */
  var continuationToken: js.UndefOr[ContinuationToken] = js.native
  /**
    * Represents information about a current revision.
    */
  var currentRevision: js.UndefOr[CurrentRevision] = js.native
  /**
    * The details of the actions taken and results produced on an artifact as it passes through stages in the pipeline. 
    */
  var executionDetails: js.UndefOr[ExecutionDetails] = js.native
  /**
    * The ID of the job that successfully completed. This is the same ID returned from PollForThirdPartyJobs.
    */
  var jobId: ThirdPartyJobId = js.native
}

object PutThirdPartyJobSuccessResultInput {
  @scala.inline
  def apply(clientToken: ClientToken, jobId: ThirdPartyJobId): PutThirdPartyJobSuccessResultInput = {
    val __obj = js.Dynamic.literal(clientToken = clientToken.asInstanceOf[js.Any], jobId = jobId.asInstanceOf[js.Any])
    __obj.asInstanceOf[PutThirdPartyJobSuccessResultInput]
  }
  @scala.inline
  implicit class PutThirdPartyJobSuccessResultInputOps[Self <: PutThirdPartyJobSuccessResultInput] (val x: Self) extends AnyVal {
    @scala.inline
    def duplicate: Self = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x)).asInstanceOf[Self]
    @scala.inline
    def combineWith[Other <: js.Any](other: Other): Self with Other = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x, other.asInstanceOf[js.Any])).asInstanceOf[Self with Other]
    @scala.inline
    def withClientToken(value: ClientToken): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("clientToken")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withJobId(value: ThirdPartyJobId): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("jobId")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withContinuationToken(value: ContinuationToken): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("continuationToken")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutContinuationToken: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("continuationToken")(js.undefined)
        ret
    }
    @scala.inline
    def withCurrentRevision(value: CurrentRevision): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("currentRevision")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutCurrentRevision: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("currentRevision")(js.undefined)
        ret
    }
    @scala.inline
    def withExecutionDetails(value: ExecutionDetails): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("executionDetails")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutExecutionDetails: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("executionDetails")(js.undefined)
        ret
    }
  }
  
}

