package typingsSlinky.awsSdkClientCodecommitNode

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object typesPullRequestSourceReferenceUpdatedEventMetadataMod {
  type UnmarshalledPullRequestSourceReferenceUpdatedEventMetadata = typingsSlinky.awsSdkClientCodecommitNode.typesPullRequestSourceReferenceUpdatedEventMetadataMod.PullRequestSourceReferenceUpdatedEventMetadata
}
