package typingsSlinky.semanticUiSearch.SemanticUI

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object SearchSettings {
  type Param = (typingsSlinky.semanticUiSearch.PickImplapiSettings | typingsSlinky.semanticUiSearch.PickImpltype | typingsSlinky.semanticUiSearch.PickImplminCharacters | typingsSlinky.semanticUiSearch.PickImpltransition | typingsSlinky.semanticUiSearch.PickImplduration | typingsSlinky.semanticUiSearch.PickImplmaxResults | typingsSlinky.semanticUiSearch.PickImplcache | typingsSlinky.semanticUiSearch.PickImplsource | typingsSlinky.semanticUiSearch.PickImplselectFirstResult | typingsSlinky.semanticUiSearch.PickImplshowNoResults | typingsSlinky.semanticUiSearch.PickImplsearchFullText | typingsSlinky.semanticUiSearch.PickImplfields | typingsSlinky.semanticUiSearch.PickImplsearchFields | typingsSlinky.semanticUiSearch.PickImplhideDelay | typingsSlinky.semanticUiSearch.PickImplsearchDelay | typingsSlinky.semanticUiSearch.PickImpleasing | typingsSlinky.semanticUiSearch.PickImplonSelect | typingsSlinky.semanticUiSearch.PickImplonResultsAdd | typingsSlinky.semanticUiSearch.PickImplonSearchQuery | typingsSlinky.semanticUiSearch.PickImplonResults | typingsSlinky.semanticUiSearch.PickImplonResultsOpen | typingsSlinky.semanticUiSearch.PickImplonResultsClose | typingsSlinky.semanticUiSearch.PickImpltemplates | typingsSlinky.semanticUiSearch.PickImplregExp | typingsSlinky.semanticUiSearch.PickImplselector | typingsSlinky.semanticUiSearch.PickImplmetadata | typingsSlinky.semanticUiSearch.PickImplclassName | typingsSlinky.semanticUiSearch.PickImplerror | typingsSlinky.semanticUiSearch.PickImplnamespace | typingsSlinky.semanticUiSearch.PickImplname | typingsSlinky.semanticUiSearch.PickImplsilent | typingsSlinky.semanticUiSearch.PickImpldebug | typingsSlinky.semanticUiSearch.PickImplperformance | typingsSlinky.semanticUiSearch.PickImplverbose) with typingsSlinky.semanticUiSearch.PartialPickImplkeyofImpl
}
