package typingsSlinky.semanticUiSearch.SemanticUI

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object SearchSettings {
  type Param = (typingsSlinky.semanticUiSearch.anon.PickImplapiSettings | typingsSlinky.semanticUiSearch.anon.PickImpltype | typingsSlinky.semanticUiSearch.anon.PickImplminCharacters | typingsSlinky.semanticUiSearch.anon.PickImpltransition | typingsSlinky.semanticUiSearch.anon.PickImplduration | typingsSlinky.semanticUiSearch.anon.PickImplmaxResults | typingsSlinky.semanticUiSearch.anon.PickImplcache | typingsSlinky.semanticUiSearch.anon.PickImplsource | typingsSlinky.semanticUiSearch.anon.PickImplselectFirstResult | typingsSlinky.semanticUiSearch.anon.PickImplshowNoResults | typingsSlinky.semanticUiSearch.anon.PickImplsearchFullText | typingsSlinky.semanticUiSearch.anon.PickImplfields | typingsSlinky.semanticUiSearch.anon.PickImplsearchFields | typingsSlinky.semanticUiSearch.anon.PickImplhideDelay | typingsSlinky.semanticUiSearch.anon.PickImplsearchDelay | typingsSlinky.semanticUiSearch.anon.PickImpleasing | typingsSlinky.semanticUiSearch.anon.PickImplonSelect | typingsSlinky.semanticUiSearch.anon.PickImplonResultsAdd | typingsSlinky.semanticUiSearch.anon.PickImplonSearchQuery | typingsSlinky.semanticUiSearch.anon.PickImplonResults | typingsSlinky.semanticUiSearch.anon.PickImplonResultsOpen | typingsSlinky.semanticUiSearch.anon.PickImplonResultsClose | typingsSlinky.semanticUiSearch.anon.PickImpltemplates | typingsSlinky.semanticUiSearch.anon.PickImplregExp | typingsSlinky.semanticUiSearch.anon.PickImplselector | typingsSlinky.semanticUiSearch.anon.PickImplmetadata | typingsSlinky.semanticUiSearch.anon.PickImplclassName | typingsSlinky.semanticUiSearch.anon.PickImplerror | typingsSlinky.semanticUiSearch.anon.PickImplnamespace | typingsSlinky.semanticUiSearch.anon.PickImplname | typingsSlinky.semanticUiSearch.anon.PickImplsilent | typingsSlinky.semanticUiSearch.anon.PickImpldebug | typingsSlinky.semanticUiSearch.anon.PickImplperformance | typingsSlinky.semanticUiSearch.anon.PickImplverbose) with typingsSlinky.semanticUiSearch.anon.PartialPickImplkeyofImpl
}
