package typingsSlinky.std

import org.scalablytyped.runtime.Instantiable0
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/** The results generated by evaluating an XPath expression within the context of a given node. */
@js.native
trait XPathResult extends js.Object {
  val ANY_TYPE: Double = js.native
  val ANY_UNORDERED_NODE_TYPE: Double = js.native
  val BOOLEAN_TYPE: Double = js.native
  val FIRST_ORDERED_NODE_TYPE: Double = js.native
  val NUMBER_TYPE: Double = js.native
  val ORDERED_NODE_ITERATOR_TYPE: Double = js.native
  val ORDERED_NODE_SNAPSHOT_TYPE: Double = js.native
  val STRING_TYPE: Double = js.native
  val UNORDERED_NODE_ITERATOR_TYPE: Double = js.native
  val UNORDERED_NODE_SNAPSHOT_TYPE: Double = js.native
  val booleanValue: scala.Boolean = js.native
  val invalidIteratorState: scala.Boolean = js.native
  val numberValue: Double = js.native
  val resultType: Double = js.native
  val singleNodeValue: org.scalajs.dom.raw.Node | Null = js.native
  val snapshotLength: Double = js.native
  val stringValue: java.lang.String = js.native
  def iterateNext(): org.scalajs.dom.raw.Node | Null = js.native
  def snapshotItem(index: Double): org.scalajs.dom.raw.Node | Null = js.native
}

@JSGlobal("XPathResult")
@js.native
object XPathResult
  extends Instantiable0[org.scalajs.dom.raw.XPathResult] {
  val ANY_TYPE: Double = js.native
  val ANY_UNORDERED_NODE_TYPE: Double = js.native
  val BOOLEAN_TYPE: Double = js.native
  val FIRST_ORDERED_NODE_TYPE: Double = js.native
  val NUMBER_TYPE: Double = js.native
  val ORDERED_NODE_ITERATOR_TYPE: Double = js.native
  val ORDERED_NODE_SNAPSHOT_TYPE: Double = js.native
  val STRING_TYPE: Double = js.native
  val UNORDERED_NODE_ITERATOR_TYPE: Double = js.native
  val UNORDERED_NODE_SNAPSHOT_TYPE: Double = js.native
}

