package typingsSlinky.awsSdkClientCognitoIdentityBrowser.getOpenIdTokenForDeveloperIdentityExceptionsUnionMod

import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesDeveloperUserAlreadyRegisteredExceptionMod.DeveloperUserAlreadyRegisteredException
import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesInternalErrorExceptionMod.InternalErrorException
import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesInvalidParameterExceptionMod.InvalidParameterException
import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesNotAuthorizedExceptionMod.NotAuthorizedException
import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesResourceConflictExceptionMod.ResourceConflictException
import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesResourceNotFoundExceptionMod.ResourceNotFoundException
import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesTooManyRequestsExceptionMod.TooManyRequestsException
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesInvalidParameterExceptionMod.InvalidParameterException
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesResourceNotFoundExceptionMod.ResourceNotFoundException
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesNotAuthorizedExceptionMod.NotAuthorizedException
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesResourceConflictExceptionMod.ResourceConflictException
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesTooManyRequestsExceptionMod.TooManyRequestsException
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesInternalErrorExceptionMod.InternalErrorException
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesDeveloperUserAlreadyRegisteredExceptionMod.DeveloperUserAlreadyRegisteredException
*/
trait GetOpenIdTokenForDeveloperIdentityExceptionsUnion extends js.Object

object GetOpenIdTokenForDeveloperIdentityExceptionsUnion {
  @scala.inline
  implicit def apply(value: DeveloperUserAlreadyRegisteredException): GetOpenIdTokenForDeveloperIdentityExceptionsUnion = value.asInstanceOf[GetOpenIdTokenForDeveloperIdentityExceptionsUnion]
  @scala.inline
  implicit def apply(value: InternalErrorException): GetOpenIdTokenForDeveloperIdentityExceptionsUnion = value.asInstanceOf[GetOpenIdTokenForDeveloperIdentityExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidParameterException): GetOpenIdTokenForDeveloperIdentityExceptionsUnion = value.asInstanceOf[GetOpenIdTokenForDeveloperIdentityExceptionsUnion]
  @scala.inline
  implicit def apply(value: NotAuthorizedException): GetOpenIdTokenForDeveloperIdentityExceptionsUnion = value.asInstanceOf[GetOpenIdTokenForDeveloperIdentityExceptionsUnion]
  @scala.inline
  implicit def apply(value: ResourceConflictException): GetOpenIdTokenForDeveloperIdentityExceptionsUnion = value.asInstanceOf[GetOpenIdTokenForDeveloperIdentityExceptionsUnion]
  @scala.inline
  implicit def apply(value: ResourceNotFoundException): GetOpenIdTokenForDeveloperIdentityExceptionsUnion = value.asInstanceOf[GetOpenIdTokenForDeveloperIdentityExceptionsUnion]
  @scala.inline
  implicit def apply(value: TooManyRequestsException): GetOpenIdTokenForDeveloperIdentityExceptionsUnion = value.asInstanceOf[GetOpenIdTokenForDeveloperIdentityExceptionsUnion]
}

