package typingsSlinky.awsSdkClientCognitoIdentityBrowser.setIdentityPoolRolesExceptionsUnionMod

import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesConcurrentModificationExceptionMod.ConcurrentModificationException
import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesInternalErrorExceptionMod.InternalErrorException
import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesInvalidParameterExceptionMod.InvalidParameterException
import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesNotAuthorizedExceptionMod.NotAuthorizedException
import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesResourceConflictExceptionMod.ResourceConflictException
import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesResourceNotFoundExceptionMod.ResourceNotFoundException
import typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesTooManyRequestsExceptionMod.TooManyRequestsException
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesInvalidParameterExceptionMod.InvalidParameterException
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesResourceNotFoundExceptionMod.ResourceNotFoundException
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesNotAuthorizedExceptionMod.NotAuthorizedException
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesResourceConflictExceptionMod.ResourceConflictException
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesTooManyRequestsExceptionMod.TooManyRequestsException
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesInternalErrorExceptionMod.InternalErrorException
  - typingsSlinky.awsSdkClientCognitoIdentityBrowser.typesConcurrentModificationExceptionMod.ConcurrentModificationException
*/
trait SetIdentityPoolRolesExceptionsUnion extends js.Object

object SetIdentityPoolRolesExceptionsUnion {
  @scala.inline
  implicit def apply(value: ConcurrentModificationException): SetIdentityPoolRolesExceptionsUnion = value.asInstanceOf[SetIdentityPoolRolesExceptionsUnion]
  @scala.inline
  implicit def apply(value: InternalErrorException): SetIdentityPoolRolesExceptionsUnion = value.asInstanceOf[SetIdentityPoolRolesExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidParameterException): SetIdentityPoolRolesExceptionsUnion = value.asInstanceOf[SetIdentityPoolRolesExceptionsUnion]
  @scala.inline
  implicit def apply(value: NotAuthorizedException): SetIdentityPoolRolesExceptionsUnion = value.asInstanceOf[SetIdentityPoolRolesExceptionsUnion]
  @scala.inline
  implicit def apply(value: ResourceConflictException): SetIdentityPoolRolesExceptionsUnion = value.asInstanceOf[SetIdentityPoolRolesExceptionsUnion]
  @scala.inline
  implicit def apply(value: ResourceNotFoundException): SetIdentityPoolRolesExceptionsUnion = value.asInstanceOf[SetIdentityPoolRolesExceptionsUnion]
  @scala.inline
  implicit def apply(value: TooManyRequestsException): SetIdentityPoolRolesExceptionsUnion = value.asInstanceOf[SetIdentityPoolRolesExceptionsUnion]
}

