package typingsSlinky.atAwsDashSdkClientDashCodecommitDashNode.typesMaximumOpenPullRequestsExceededExceptionMod

import typingsSlinky.atAwsDashSdkClientDashCodecommitDashNode.typesCreatePullRequestExceptionsUnionMod.CreatePullRequestExceptionsUnion
import typingsSlinky.atAwsDashSdkTypes.buildExceptionMod.ServiceException
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait MaximumOpenPullRequestsExceededException
  extends ServiceException[_MaximumOpenPullRequestsExceededExceptionDetails]
     with CreatePullRequestExceptionsUnion {
  @JSName("name")
  var name_MaximumOpenPullRequestsExceededException: typingsSlinky.atAwsDashSdkClientDashCodecommitDashNode.atAwsDashSdkClientDashCodecommitDashNodeStrings.MaximumOpenPullRequestsExceededException = js.native
}

