package typingsSlinky.googleapis.v1b3Mod.dataflowV1b3

import org.scalablytyped.runtime.StringDictionary
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/**
  * An output of an instruction.
  */
@js.native
trait SchemaInstructionOutput extends js.Object {
  /**
    * The codec to use to encode data being written via this output.
    */
  var codec: js.UndefOr[StringDictionary[js.Any]] = js.native
  /**
    * The user-provided name of this output.
    */
  var name: js.UndefOr[String] = js.native
  /**
    * For system-generated byte and mean byte metrics, certain instructions
    * should only report the key size.
    */
  var onlyCountKeyBytes: js.UndefOr[Boolean] = js.native
  /**
    * For system-generated byte and mean byte metrics, certain instructions
    * should only report the value size.
    */
  var onlyCountValueBytes: js.UndefOr[Boolean] = js.native
  /**
    * System-defined name for this output in the original workflow graph.
    * Outputs that do not contribute to an original instruction do not set
    * this.
    */
  var originalName: js.UndefOr[String] = js.native
  /**
    * System-defined name of this output. Unique across the workflow.
    */
  var systemName: js.UndefOr[String] = js.native
}

object SchemaInstructionOutput {
  @scala.inline
  def apply(): SchemaInstructionOutput = {
    val __obj = js.Dynamic.literal()
    __obj.asInstanceOf[SchemaInstructionOutput]
  }
  @scala.inline
  implicit class SchemaInstructionOutputOps[Self <: SchemaInstructionOutput] (val x: Self) extends AnyVal {
    @scala.inline
    def duplicate: Self = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x)).asInstanceOf[Self]
    @scala.inline
    def combineWith[Other <: js.Any](other: Other): Self with Other = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x, other.asInstanceOf[js.Any])).asInstanceOf[Self with Other]
    @scala.inline
    def withCodec(value: StringDictionary[js.Any]): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("codec")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutCodec: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("codec")(js.undefined)
        ret
    }
    @scala.inline
    def withName(value: String): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("name")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutName: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("name")(js.undefined)
        ret
    }
    @scala.inline
    def withOnlyCountKeyBytes(value: Boolean): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("onlyCountKeyBytes")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutOnlyCountKeyBytes: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("onlyCountKeyBytes")(js.undefined)
        ret
    }
    @scala.inline
    def withOnlyCountValueBytes(value: Boolean): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("onlyCountValueBytes")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutOnlyCountValueBytes: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("onlyCountValueBytes")(js.undefined)
        ret
    }
    @scala.inline
    def withOriginalName(value: String): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("originalName")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutOriginalName: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("originalName")(js.undefined)
        ret
    }
    @scala.inline
    def withSystemName(value: String): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("systemName")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutSystemName: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("systemName")(js.undefined)
        ret
    }
  }
  
}

