package typingsSlinky.atTensorflowTfjsDashLayers

import typingsSlinky.atTensorflowTfjsDashLayers.distKerasUnderscoreFormatInputUnderscoreConfigMod.InputLayerSerialization
import typingsSlinky.atTensorflowTfjsDashLayers.distKerasUnderscoreFormatLayersAdvancedUnderscoreActivationUnderscoreSerializationMod.AdvancedActivationLayerSerialization
import typingsSlinky.atTensorflowTfjsDashLayers.distKerasUnderscoreFormatLayersConvolutionalUnderscoreDepthwiseUnderscoreSerializationMod.ConvolutionalDepthwiseLayerSerialization
import typingsSlinky.atTensorflowTfjsDashLayers.distKerasUnderscoreFormatLayersConvolutionalUnderscoreSerializationMod.ConvolutionalLayerSerialization
import typingsSlinky.atTensorflowTfjsDashLayers.distKerasUnderscoreFormatLayersCoreUnderscoreSerializationMod.CoreLayerSerialization
import typingsSlinky.atTensorflowTfjsDashLayers.distKerasUnderscoreFormatLayersEmbeddingsUnderscoreSerializationMod.EmbeddingLayerSerialization
import typingsSlinky.atTensorflowTfjsDashLayers.distKerasUnderscoreFormatLayersMergeUnderscoreSerializationMod.MergeLayerSerialization
import typingsSlinky.atTensorflowTfjsDashLayers.distKerasUnderscoreFormatLayersNormalizationUnderscoreSerializationMod.NormalizationLayerSerialization
import typingsSlinky.atTensorflowTfjsDashLayers.distKerasUnderscoreFormatLayersPaddingUnderscoreSerializationMod.PaddingLayerSerialization
import typingsSlinky.atTensorflowTfjsDashLayers.distKerasUnderscoreFormatLayersPoolingUnderscoreSerializationMod.PoolingLayerSerialization
import typingsSlinky.atTensorflowTfjsDashLayers.distKerasUnderscoreFormatLayersRecurrentUnderscoreSerializationMod.RecurrentLayerSerialization
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@JSImport("@tensorflow/tfjs-layers/dist/keras_format/layers/layer_serialization", JSImport.Namespace)
@js.native
object distKerasUnderscoreFormatLayersLayerUnderscoreSerializationMod extends js.Object {
  val layerClassNames: js.Array[LayerClassName] = js.native
  type LayerClassName = /* import warning: importer.ImportType#apply Failed type conversion: @tensorflow/tfjs-layers.@tensorflow/tfjs-layers/dist/keras_format/layers/layer_serialization.LayerSerialization['class_name'] */ js.Any
  type LayerSerialization = AdvancedActivationLayerSerialization | ConvolutionalDepthwiseLayerSerialization | ConvolutionalLayerSerialization | CoreLayerSerialization | EmbeddingLayerSerialization | MergeLayerSerialization | NormalizationLayerSerialization | PaddingLayerSerialization | PoolingLayerSerialization | RecurrentLayerSerialization | InputLayerSerialization
}

