package typingsSlinky.markdownToJsx.anon

import org.scalablytyped.runtime.StringDictionary
import slinky.core.ReactComponentClass
import typingsSlinky.markdownToJsx.mod.ComponentOverride
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait Dictkey
  extends /** In addition to HTML tags, you can specify a custom component name which can be used within markdown text. */
/* key */ StringDictionary[js.UndefOr[ComponentOverride[_, _]]] {
  // As of 6.9.3, these tags are the only ones automatically generated by markdown-to-jsx.
  var a: js.UndefOr[ComponentOverride[_, _]] = js.native
  var br: js.UndefOr[ComponentOverride[_, _]] = js.native
  var button: js.UndefOr[ComponentOverride[_, _]] = js.native
  var code: js.UndefOr[ComponentOverride[_, _]] = js.native
  var del: js.UndefOr[ComponentOverride[_, _]] = js.native
  var div: js.UndefOr[ComponentOverride[_, _]] = js.native
  var em: js.UndefOr[ComponentOverride[_, _]] = js.native
  var footer: js.UndefOr[ComponentOverride[_, _]] = js.native
  var h1: js.UndefOr[ComponentOverride[_, _]] = js.native
  var h2: js.UndefOr[ComponentOverride[_, _]] = js.native
  var h3: js.UndefOr[ComponentOverride[_, _]] = js.native
  var h4: js.UndefOr[ComponentOverride[_, _]] = js.native
  var h5: js.UndefOr[ComponentOverride[_, _]] = js.native
  var h6: js.UndefOr[ComponentOverride[_, _]] = js.native
  var hr: js.UndefOr[ComponentOverride[_, _]] = js.native
  var img: js.UndefOr[ComponentOverride[_, _]] = js.native
  var input: js.UndefOr[ComponentOverride[_, _]] = js.native
  var ol: js.UndefOr[ComponentOverride[_, _]] = js.native
  var p: js.UndefOr[ComponentOverride[_, _]] = js.native
  var pre: js.UndefOr[ComponentOverride[_, _]] = js.native
  var span: js.UndefOr[ComponentOverride[_, _]] = js.native
  var strong: js.UndefOr[ComponentOverride[_, _]] = js.native
  var sub: js.UndefOr[ComponentOverride[_, _]] = js.native
  var sup: js.UndefOr[ComponentOverride[_, _]] = js.native
  var table: js.UndefOr[ComponentOverride[_, _]] = js.native
  var tbody: js.UndefOr[ComponentOverride[_, _]] = js.native
  var td: js.UndefOr[ComponentOverride[_, _]] = js.native
  var th: js.UndefOr[ComponentOverride[_, _]] = js.native
  var thead: js.UndefOr[ComponentOverride[_, _]] = js.native
  var tr: js.UndefOr[ComponentOverride[_, _]] = js.native
  var ul: js.UndefOr[ComponentOverride[_, _]] = js.native
}

object Dictkey {
  @scala.inline
  def apply(): Dictkey = {
    val __obj = js.Dynamic.literal()
    __obj.asInstanceOf[Dictkey]
  }
  @scala.inline
  implicit class DictkeyOps[Self <: Dictkey] (val x: Self) extends AnyVal {
    @scala.inline
    def duplicate: Self = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x)).asInstanceOf[Self]
    @scala.inline
    def combineWith[Other <: js.Any](other: Other): Self with Other = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x, other.asInstanceOf[js.Any])).asInstanceOf[Self with Other]
    @scala.inline
    def set(key: String, value: js.Any): Self = {
        x.asInstanceOf[js.Dynamic].updateDynamic(key)(value)
        x
    }
    @scala.inline
    def setAFunctionComponent(value: ReactComponentClass[_]): Self = this.set("a", value.asInstanceOf[js.Any])
    @scala.inline
    def setAComponentClass(value: ReactComponentClass[_]): Self = this.set("a", value.asInstanceOf[js.Any])
    @scala.inline
    def setA(value: ComponentOverride[_, _]): Self = this.set("a", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteA: Self = this.set("a", js.undefined)
    @scala.inline
    def setBrFunctionComponent(value: ReactComponentClass[_]): Self = this.set("br", value.asInstanceOf[js.Any])
    @scala.inline
    def setBrComponentClass(value: ReactComponentClass[_]): Self = this.set("br", value.asInstanceOf[js.Any])
    @scala.inline
    def setBr(value: ComponentOverride[_, _]): Self = this.set("br", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteBr: Self = this.set("br", js.undefined)
    @scala.inline
    def setButtonFunctionComponent(value: ReactComponentClass[_]): Self = this.set("button", value.asInstanceOf[js.Any])
    @scala.inline
    def setButtonComponentClass(value: ReactComponentClass[_]): Self = this.set("button", value.asInstanceOf[js.Any])
    @scala.inline
    def setButton(value: ComponentOverride[_, _]): Self = this.set("button", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteButton: Self = this.set("button", js.undefined)
    @scala.inline
    def setCodeFunctionComponent(value: ReactComponentClass[_]): Self = this.set("code", value.asInstanceOf[js.Any])
    @scala.inline
    def setCodeComponentClass(value: ReactComponentClass[_]): Self = this.set("code", value.asInstanceOf[js.Any])
    @scala.inline
    def setCode(value: ComponentOverride[_, _]): Self = this.set("code", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteCode: Self = this.set("code", js.undefined)
    @scala.inline
    def setDelFunctionComponent(value: ReactComponentClass[_]): Self = this.set("del", value.asInstanceOf[js.Any])
    @scala.inline
    def setDelComponentClass(value: ReactComponentClass[_]): Self = this.set("del", value.asInstanceOf[js.Any])
    @scala.inline
    def setDel(value: ComponentOverride[_, _]): Self = this.set("del", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteDel: Self = this.set("del", js.undefined)
    @scala.inline
    def setDivFunctionComponent(value: ReactComponentClass[_]): Self = this.set("div", value.asInstanceOf[js.Any])
    @scala.inline
    def setDivComponentClass(value: ReactComponentClass[_]): Self = this.set("div", value.asInstanceOf[js.Any])
    @scala.inline
    def setDiv(value: ComponentOverride[_, _]): Self = this.set("div", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteDiv: Self = this.set("div", js.undefined)
    @scala.inline
    def setEmFunctionComponent(value: ReactComponentClass[_]): Self = this.set("em", value.asInstanceOf[js.Any])
    @scala.inline
    def setEmComponentClass(value: ReactComponentClass[_]): Self = this.set("em", value.asInstanceOf[js.Any])
    @scala.inline
    def setEm(value: ComponentOverride[_, _]): Self = this.set("em", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteEm: Self = this.set("em", js.undefined)
    @scala.inline
    def setFooterFunctionComponent(value: ReactComponentClass[_]): Self = this.set("footer", value.asInstanceOf[js.Any])
    @scala.inline
    def setFooterComponentClass(value: ReactComponentClass[_]): Self = this.set("footer", value.asInstanceOf[js.Any])
    @scala.inline
    def setFooter(value: ComponentOverride[_, _]): Self = this.set("footer", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteFooter: Self = this.set("footer", js.undefined)
    @scala.inline
    def setH1FunctionComponent(value: ReactComponentClass[_]): Self = this.set("h1", value.asInstanceOf[js.Any])
    @scala.inline
    def setH1ComponentClass(value: ReactComponentClass[_]): Self = this.set("h1", value.asInstanceOf[js.Any])
    @scala.inline
    def setH1(value: ComponentOverride[_, _]): Self = this.set("h1", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteH1: Self = this.set("h1", js.undefined)
    @scala.inline
    def setH2FunctionComponent(value: ReactComponentClass[_]): Self = this.set("h2", value.asInstanceOf[js.Any])
    @scala.inline
    def setH2ComponentClass(value: ReactComponentClass[_]): Self = this.set("h2", value.asInstanceOf[js.Any])
    @scala.inline
    def setH2(value: ComponentOverride[_, _]): Self = this.set("h2", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteH2: Self = this.set("h2", js.undefined)
    @scala.inline
    def setH3FunctionComponent(value: ReactComponentClass[_]): Self = this.set("h3", value.asInstanceOf[js.Any])
    @scala.inline
    def setH3ComponentClass(value: ReactComponentClass[_]): Self = this.set("h3", value.asInstanceOf[js.Any])
    @scala.inline
    def setH3(value: ComponentOverride[_, _]): Self = this.set("h3", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteH3: Self = this.set("h3", js.undefined)
    @scala.inline
    def setH4FunctionComponent(value: ReactComponentClass[_]): Self = this.set("h4", value.asInstanceOf[js.Any])
    @scala.inline
    def setH4ComponentClass(value: ReactComponentClass[_]): Self = this.set("h4", value.asInstanceOf[js.Any])
    @scala.inline
    def setH4(value: ComponentOverride[_, _]): Self = this.set("h4", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteH4: Self = this.set("h4", js.undefined)
    @scala.inline
    def setH5FunctionComponent(value: ReactComponentClass[_]): Self = this.set("h5", value.asInstanceOf[js.Any])
    @scala.inline
    def setH5ComponentClass(value: ReactComponentClass[_]): Self = this.set("h5", value.asInstanceOf[js.Any])
    @scala.inline
    def setH5(value: ComponentOverride[_, _]): Self = this.set("h5", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteH5: Self = this.set("h5", js.undefined)
    @scala.inline
    def setH6FunctionComponent(value: ReactComponentClass[_]): Self = this.set("h6", value.asInstanceOf[js.Any])
    @scala.inline
    def setH6ComponentClass(value: ReactComponentClass[_]): Self = this.set("h6", value.asInstanceOf[js.Any])
    @scala.inline
    def setH6(value: ComponentOverride[_, _]): Self = this.set("h6", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteH6: Self = this.set("h6", js.undefined)
    @scala.inline
    def setHrFunctionComponent(value: ReactComponentClass[_]): Self = this.set("hr", value.asInstanceOf[js.Any])
    @scala.inline
    def setHrComponentClass(value: ReactComponentClass[_]): Self = this.set("hr", value.asInstanceOf[js.Any])
    @scala.inline
    def setHr(value: ComponentOverride[_, _]): Self = this.set("hr", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteHr: Self = this.set("hr", js.undefined)
    @scala.inline
    def setImgFunctionComponent(value: ReactComponentClass[_]): Self = this.set("img", value.asInstanceOf[js.Any])
    @scala.inline
    def setImgComponentClass(value: ReactComponentClass[_]): Self = this.set("img", value.asInstanceOf[js.Any])
    @scala.inline
    def setImg(value: ComponentOverride[_, _]): Self = this.set("img", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteImg: Self = this.set("img", js.undefined)
    @scala.inline
    def setInputFunctionComponent(value: ReactComponentClass[_]): Self = this.set("input", value.asInstanceOf[js.Any])
    @scala.inline
    def setInputComponentClass(value: ReactComponentClass[_]): Self = this.set("input", value.asInstanceOf[js.Any])
    @scala.inline
    def setInput(value: ComponentOverride[_, _]): Self = this.set("input", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteInput: Self = this.set("input", js.undefined)
    @scala.inline
    def setOlFunctionComponent(value: ReactComponentClass[_]): Self = this.set("ol", value.asInstanceOf[js.Any])
    @scala.inline
    def setOlComponentClass(value: ReactComponentClass[_]): Self = this.set("ol", value.asInstanceOf[js.Any])
    @scala.inline
    def setOl(value: ComponentOverride[_, _]): Self = this.set("ol", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteOl: Self = this.set("ol", js.undefined)
    @scala.inline
    def setPFunctionComponent(value: ReactComponentClass[_]): Self = this.set("p", value.asInstanceOf[js.Any])
    @scala.inline
    def setPComponentClass(value: ReactComponentClass[_]): Self = this.set("p", value.asInstanceOf[js.Any])
    @scala.inline
    def setP(value: ComponentOverride[_, _]): Self = this.set("p", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteP: Self = this.set("p", js.undefined)
    @scala.inline
    def setPreFunctionComponent(value: ReactComponentClass[_]): Self = this.set("pre", value.asInstanceOf[js.Any])
    @scala.inline
    def setPreComponentClass(value: ReactComponentClass[_]): Self = this.set("pre", value.asInstanceOf[js.Any])
    @scala.inline
    def setPre(value: ComponentOverride[_, _]): Self = this.set("pre", value.asInstanceOf[js.Any])
    @scala.inline
    def deletePre: Self = this.set("pre", js.undefined)
    @scala.inline
    def setSpanFunctionComponent(value: ReactComponentClass[_]): Self = this.set("span", value.asInstanceOf[js.Any])
    @scala.inline
    def setSpanComponentClass(value: ReactComponentClass[_]): Self = this.set("span", value.asInstanceOf[js.Any])
    @scala.inline
    def setSpan(value: ComponentOverride[_, _]): Self = this.set("span", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteSpan: Self = this.set("span", js.undefined)
    @scala.inline
    def setStrongFunctionComponent(value: ReactComponentClass[_]): Self = this.set("strong", value.asInstanceOf[js.Any])
    @scala.inline
    def setStrongComponentClass(value: ReactComponentClass[_]): Self = this.set("strong", value.asInstanceOf[js.Any])
    @scala.inline
    def setStrong(value: ComponentOverride[_, _]): Self = this.set("strong", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteStrong: Self = this.set("strong", js.undefined)
    @scala.inline
    def setSubFunctionComponent(value: ReactComponentClass[_]): Self = this.set("sub", value.asInstanceOf[js.Any])
    @scala.inline
    def setSubComponentClass(value: ReactComponentClass[_]): Self = this.set("sub", value.asInstanceOf[js.Any])
    @scala.inline
    def setSub(value: ComponentOverride[_, _]): Self = this.set("sub", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteSub: Self = this.set("sub", js.undefined)
    @scala.inline
    def setSupFunctionComponent(value: ReactComponentClass[_]): Self = this.set("sup", value.asInstanceOf[js.Any])
    @scala.inline
    def setSupComponentClass(value: ReactComponentClass[_]): Self = this.set("sup", value.asInstanceOf[js.Any])
    @scala.inline
    def setSup(value: ComponentOverride[_, _]): Self = this.set("sup", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteSup: Self = this.set("sup", js.undefined)
    @scala.inline
    def setTableFunctionComponent(value: ReactComponentClass[_]): Self = this.set("table", value.asInstanceOf[js.Any])
    @scala.inline
    def setTableComponentClass(value: ReactComponentClass[_]): Self = this.set("table", value.asInstanceOf[js.Any])
    @scala.inline
    def setTable(value: ComponentOverride[_, _]): Self = this.set("table", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteTable: Self = this.set("table", js.undefined)
    @scala.inline
    def setTbodyFunctionComponent(value: ReactComponentClass[_]): Self = this.set("tbody", value.asInstanceOf[js.Any])
    @scala.inline
    def setTbodyComponentClass(value: ReactComponentClass[_]): Self = this.set("tbody", value.asInstanceOf[js.Any])
    @scala.inline
    def setTbody(value: ComponentOverride[_, _]): Self = this.set("tbody", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteTbody: Self = this.set("tbody", js.undefined)
    @scala.inline
    def setTdFunctionComponent(value: ReactComponentClass[_]): Self = this.set("td", value.asInstanceOf[js.Any])
    @scala.inline
    def setTdComponentClass(value: ReactComponentClass[_]): Self = this.set("td", value.asInstanceOf[js.Any])
    @scala.inline
    def setTd(value: ComponentOverride[_, _]): Self = this.set("td", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteTd: Self = this.set("td", js.undefined)
    @scala.inline
    def setThFunctionComponent(value: ReactComponentClass[_]): Self = this.set("th", value.asInstanceOf[js.Any])
    @scala.inline
    def setThComponentClass(value: ReactComponentClass[_]): Self = this.set("th", value.asInstanceOf[js.Any])
    @scala.inline
    def setTh(value: ComponentOverride[_, _]): Self = this.set("th", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteTh: Self = this.set("th", js.undefined)
    @scala.inline
    def setTheadFunctionComponent(value: ReactComponentClass[_]): Self = this.set("thead", value.asInstanceOf[js.Any])
    @scala.inline
    def setTheadComponentClass(value: ReactComponentClass[_]): Self = this.set("thead", value.asInstanceOf[js.Any])
    @scala.inline
    def setThead(value: ComponentOverride[_, _]): Self = this.set("thead", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteThead: Self = this.set("thead", js.undefined)
    @scala.inline
    def setTrFunctionComponent(value: ReactComponentClass[_]): Self = this.set("tr", value.asInstanceOf[js.Any])
    @scala.inline
    def setTrComponentClass(value: ReactComponentClass[_]): Self = this.set("tr", value.asInstanceOf[js.Any])
    @scala.inline
    def setTr(value: ComponentOverride[_, _]): Self = this.set("tr", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteTr: Self = this.set("tr", js.undefined)
    @scala.inline
    def setUlFunctionComponent(value: ReactComponentClass[_]): Self = this.set("ul", value.asInstanceOf[js.Any])
    @scala.inline
    def setUlComponentClass(value: ReactComponentClass[_]): Self = this.set("ul", value.asInstanceOf[js.Any])
    @scala.inline
    def setUl(value: ComponentOverride[_, _]): Self = this.set("ul", value.asInstanceOf[js.Any])
    @scala.inline
    def deleteUl: Self = this.set("ul", js.undefined)
  }
  
}

