package typingsSlinky.wixUiIconsCommon

import slinky.core.ReactComponentClass
import typingsSlinky.wixUiIconsCommon.accessibilityMod.AccessibilityProps
import typingsSlinky.wixUiIconsCommon.accessibilitySmallMod.AccessibilitySmallProps
import typingsSlinky.wixUiIconsCommon.addChannelMod.AddChannelProps
import typingsSlinky.wixUiIconsCommon.addChannelSmallMod.AddChannelSmallProps
import typingsSlinky.wixUiIconsCommon.addMod.AddProps
import typingsSlinky.wixUiIconsCommon.addSmallMod.AddSmallProps
import typingsSlinky.wixUiIconsCommon.adjustMod.AdjustProps
import typingsSlinky.wixUiIconsCommon.adjustSmallMod.AdjustSmallProps
import typingsSlinky.wixUiIconsCommon.adminAccessMod.AdminAccessProps
import typingsSlinky.wixUiIconsCommon.adminAccessSmallMod.AdminAccessSmallProps
import typingsSlinky.wixUiIconsCommon.alignBottomMod.AlignBottomProps
import typingsSlinky.wixUiIconsCommon.alignBottomSmallMod.AlignBottomSmallProps
import typingsSlinky.wixUiIconsCommon.alignCenterHorizontallyMod.AlignCenterHorizontallyProps
import typingsSlinky.wixUiIconsCommon.alignCenterHorizontallySmallMod.AlignCenterHorizontallySmallProps
import typingsSlinky.wixUiIconsCommon.alignCenterVerticallyMod.AlignCenterVerticallyProps
import typingsSlinky.wixUiIconsCommon.alignCenterVerticallySmallMod.AlignCenterVerticallySmallProps
import typingsSlinky.wixUiIconsCommon.alignLeftMod.AlignLeftProps
import typingsSlinky.wixUiIconsCommon.alignLeftSmallMod.AlignLeftSmallProps
import typingsSlinky.wixUiIconsCommon.alignRightMod.AlignRightProps
import typingsSlinky.wixUiIconsCommon.alignRightSmallMod.AlignRightSmallProps
import typingsSlinky.wixUiIconsCommon.alignTopMod.AlignTopProps
import typingsSlinky.wixUiIconsCommon.alignTopSmallMod.AlignTopSmallProps
import typingsSlinky.wixUiIconsCommon.appMarketMod.AppMarketProps
import typingsSlinky.wixUiIconsCommon.appMarketSmallMod.AppMarketSmallProps
import typingsSlinky.wixUiIconsCommon.archiveMod.ArchiveProps
import typingsSlinky.wixUiIconsCommon.archiveSmallMod.ArchiveSmallProps
import typingsSlinky.wixUiIconsCommon.arrowDownMod.ArrowDownProps
import typingsSlinky.wixUiIconsCommon.arrowDownRightMod.ArrowDownRightProps
import typingsSlinky.wixUiIconsCommon.arrowDownRightSmallMod.ArrowDownRightSmallProps
import typingsSlinky.wixUiIconsCommon.arrowDownSmallMod.ArrowDownSmallProps
import typingsSlinky.wixUiIconsCommon.arrowLeftMod.ArrowLeftProps
import typingsSlinky.wixUiIconsCommon.arrowLeftSmallMod.ArrowLeftSmallProps
import typingsSlinky.wixUiIconsCommon.arrowRightMod.ArrowRightProps
import typingsSlinky.wixUiIconsCommon.arrowRightSmallMod.ArrowRightSmallProps
import typingsSlinky.wixUiIconsCommon.arrowUpMod.ArrowUpProps
import typingsSlinky.wixUiIconsCommon.arrowUpSmallMod.ArrowUpSmallProps
import typingsSlinky.wixUiIconsCommon.articleMod.ArticleProps
import typingsSlinky.wixUiIconsCommon.articleSmallMod.ArticleSmallProps
import typingsSlinky.wixUiIconsCommon.attachementMod.AttachementProps
import typingsSlinky.wixUiIconsCommon.attachmentMod.AttachmentProps
import typingsSlinky.wixUiIconsCommon.attachmentSmallMod.AttachmentSmallProps
import typingsSlinky.wixUiIconsCommon.automationsFilledMod.AutomationsFilledProps
import typingsSlinky.wixUiIconsCommon.automationsFilledSmallMod.AutomationsFilledSmallProps
import typingsSlinky.wixUiIconsCommon.automationsMod.AutomationsProps
import typingsSlinky.wixUiIconsCommon.automationsSmallMod.AutomationsSmallProps
import typingsSlinky.wixUiIconsCommon.backgroundMod.BackgroundProps
import typingsSlinky.wixUiIconsCommon.backgroundSmallMod.BackgroundSmallProps
import typingsSlinky.wixUiIconsCommon.backwardMod.BackwardProps
import typingsSlinky.wixUiIconsCommon.backwardSmallMod.BackwardSmallProps
import typingsSlinky.wixUiIconsCommon.badgeMod.BadgeProps
import typingsSlinky.wixUiIconsCommon.badgeSmallMod.BadgeSmallProps
import typingsSlinky.wixUiIconsCommon.barChartSplitMod.BarChartSplitProps
import typingsSlinky.wixUiIconsCommon.barChartSplitSmallMod.BarChartSplitSmallProps
import typingsSlinky.wixUiIconsCommon.bingMod.BingProps
import typingsSlinky.wixUiIconsCommon.bingSmallMod.BingSmallProps
import typingsSlinky.wixUiIconsCommon.blockMod.BlockProps
import typingsSlinky.wixUiIconsCommon.blockSmallMod.BlockSmallProps
import typingsSlinky.wixUiIconsCommon.bonusGiftMod.BonusGiftProps
import typingsSlinky.wixUiIconsCommon.bonusGiftSmallMod.BonusGiftSmallProps
import typingsSlinky.wixUiIconsCommon.bookmarkFilledMod.BookmarkFilledProps
import typingsSlinky.wixUiIconsCommon.bookmarkFilledSmallMod.BookmarkFilledSmallProps
import typingsSlinky.wixUiIconsCommon.bookmarkMod.BookmarkProps
import typingsSlinky.wixUiIconsCommon.bookmarkSmallMod.BookmarkSmallProps
import typingsSlinky.wixUiIconsCommon.bowMod.BowProps
import typingsSlinky.wixUiIconsCommon.bowSmallMod.BowSmallProps
import typingsSlinky.wixUiIconsCommon.brightnessMod.BrightnessProps
import typingsSlinky.wixUiIconsCommon.brightnessSmallMod.BrightnessSmallProps
import typingsSlinky.wixUiIconsCommon.cahtFilledSmallMod.CahtFilledSmallProps
import typingsSlinky.wixUiIconsCommon.cancelOrderMod.CancelOrderProps
import typingsSlinky.wixUiIconsCommon.cancelOrderSmallMod.CancelOrderSmallProps
import typingsSlinky.wixUiIconsCommon.cartMod.CartProps
import typingsSlinky.wixUiIconsCommon.cartSmallMod.CartSmallProps
import typingsSlinky.wixUiIconsCommon.categoryMod.CategoryProps
import typingsSlinky.wixUiIconsCommon.categorySmallMod.CategorySmallProps
import typingsSlinky.wixUiIconsCommon.chatDisabedMod.ChatDisabedProps
import typingsSlinky.wixUiIconsCommon.chatDisabledMod.ChatDisabledProps
import typingsSlinky.wixUiIconsCommon.chatDisabledSmallMod.ChatDisabledSmallProps
import typingsSlinky.wixUiIconsCommon.chatFilledMod.ChatFilledProps
import typingsSlinky.wixUiIconsCommon.chatFilledSmallMod.ChatFilledSmallProps
import typingsSlinky.wixUiIconsCommon.chatMod.ChatProps
import typingsSlinky.wixUiIconsCommon.chatReplyMod.ChatReplyProps
import typingsSlinky.wixUiIconsCommon.chatReplySmallMod.ChatReplySmallProps
import typingsSlinky.wixUiIconsCommon.chatSmallMod.ChatSmallProps
import typingsSlinky.wixUiIconsCommon.checkMod.CheckProps
import typingsSlinky.wixUiIconsCommon.chevronDownCircleMod.ChevronDownCircleProps
import typingsSlinky.wixUiIconsCommon.chevronDownCircleSmallMod.ChevronDownCircleSmallProps
import typingsSlinky.wixUiIconsCommon.chevronDownLargeMod.ChevronDownLargeProps
import typingsSlinky.wixUiIconsCommon.chevronDownLargeSmallMod.ChevronDownLargeSmallProps
import typingsSlinky.wixUiIconsCommon.chevronDownMod.ChevronDownProps
import typingsSlinky.wixUiIconsCommon.chevronDownSmallMod.ChevronDownSmallProps
import typingsSlinky.wixUiIconsCommon.chevronLeftCircleMod.ChevronLeftCircleProps
import typingsSlinky.wixUiIconsCommon.chevronLeftCircleSmallMod.ChevronLeftCircleSmallProps
import typingsSlinky.wixUiIconsCommon.chevronLeftLargeMod.ChevronLeftLargeProps
import typingsSlinky.wixUiIconsCommon.chevronLeftLargeSmallMod.ChevronLeftLargeSmallProps
import typingsSlinky.wixUiIconsCommon.chevronLeftMod.ChevronLeftProps
import typingsSlinky.wixUiIconsCommon.chevronLeftSmallMod.ChevronLeftSmallProps
import typingsSlinky.wixUiIconsCommon.chevronRightCircleMod.ChevronRightCircleProps
import typingsSlinky.wixUiIconsCommon.chevronRightCircleSmallMod.ChevronRightCircleSmallProps
import typingsSlinky.wixUiIconsCommon.chevronRightLargeMod.ChevronRightLargeProps
import typingsSlinky.wixUiIconsCommon.chevronRightLargeSmallMod.ChevronRightLargeSmallProps
import typingsSlinky.wixUiIconsCommon.chevronRightMod.ChevronRightProps
import typingsSlinky.wixUiIconsCommon.chevronRightSmallMod.ChevronRightSmallProps
import typingsSlinky.wixUiIconsCommon.chevronUpCircleMod.ChevronUpCircleProps
import typingsSlinky.wixUiIconsCommon.chevronUpCircleSmallMod.ChevronUpCircleSmallProps
import typingsSlinky.wixUiIconsCommon.chevronUpLargeMod.ChevronUpLargeProps
import typingsSlinky.wixUiIconsCommon.chevronUpLargeSmallMod.ChevronUpLargeSmallProps
import typingsSlinky.wixUiIconsCommon.chevronUpMod.ChevronUpProps
import typingsSlinky.wixUiIconsCommon.chevronUpSmallMod.ChevronUpSmallProps
import typingsSlinky.wixUiIconsCommon.circleLargeMod.CircleLargeProps
import typingsSlinky.wixUiIconsCommon.circleLargeSmallMod.CircleLargeSmallProps
import typingsSlinky.wixUiIconsCommon.circleSmallFilledMod.CircleSmallFilledProps
import typingsSlinky.wixUiIconsCommon.circleSmallFilledSmallMod.CircleSmallFilledSmallProps
import typingsSlinky.wixUiIconsCommon.codeMod.CodeProps
import typingsSlinky.wixUiIconsCommon.codeSmallMod.CodeSmallProps
import typingsSlinky.wixUiIconsCommon.collectionsMod.CollectionsProps
import typingsSlinky.wixUiIconsCommon.collectionsSmallMod.CollectionsSmallProps
import typingsSlinky.wixUiIconsCommon.colorDropMod.ColorDropProps
import typingsSlinky.wixUiIconsCommon.colorDropSmallMod.ColorDropSmallProps
import typingsSlinky.wixUiIconsCommon.composeMod.ComposeProps
import typingsSlinky.wixUiIconsCommon.composeSmallMod.ComposeSmallProps
import typingsSlinky.wixUiIconsCommon.confirmMod.ConfirmProps
import typingsSlinky.wixUiIconsCommon.confirmSmallMod.ConfirmSmallProps
import typingsSlinky.wixUiIconsCommon.contentFilterMod.ContentFilterProps
import typingsSlinky.wixUiIconsCommon.contentFilterSmallMod.ContentFilterSmallProps
import typingsSlinky.wixUiIconsCommon.contrastMod.ContrastProps
import typingsSlinky.wixUiIconsCommon.contrastSmallMod.ContrastSmallProps
import typingsSlinky.wixUiIconsCommon.couponMod.CouponProps
import typingsSlinky.wixUiIconsCommon.couponSmallMod.CouponSmallProps
import typingsSlinky.wixUiIconsCommon.cropMod.CropProps
import typingsSlinky.wixUiIconsCommon.cropRotateMod.CropRotateProps
import typingsSlinky.wixUiIconsCommon.cropRotateSmallMod.CropRotateSmallProps
import typingsSlinky.wixUiIconsCommon.cropSmallMod.CropSmallProps
import typingsSlinky.wixUiIconsCommon.cutOutMod.CutOutProps
import typingsSlinky.wixUiIconsCommon.cutOutSmallMod.CutOutSmallProps
import typingsSlinky.wixUiIconsCommon.cutleryMod.CutleryProps
import typingsSlinky.wixUiIconsCommon.cutlerySmallMod.CutlerySmallProps
import typingsSlinky.wixUiIconsCommon.dataCollectionMod.DataCollectionProps
import typingsSlinky.wixUiIconsCommon.dataCollectionSmallMod.DataCollectionSmallProps
import typingsSlinky.wixUiIconsCommon.databaseMod.DatabaseProps
import typingsSlinky.wixUiIconsCommon.databaseSmallMod.DatabaseSmallProps
import typingsSlinky.wixUiIconsCommon.dateAddMod.DateAddProps
import typingsSlinky.wixUiIconsCommon.dateAddSmallMod.DateAddSmallProps
import typingsSlinky.wixUiIconsCommon.dateAndTimeMod.DateAndTimeProps
import typingsSlinky.wixUiIconsCommon.dateAndTimeSmallMod.DateAndTimeSmallProps
import typingsSlinky.wixUiIconsCommon.dateCheckedMod.DateCheckedProps
import typingsSlinky.wixUiIconsCommon.dateCheckedSmallMod.DateCheckedSmallProps
import typingsSlinky.wixUiIconsCommon.dateMod.DateProps
import typingsSlinky.wixUiIconsCommon.dateSmallMod.DateSmallProps
import typingsSlinky.wixUiIconsCommon.deleteMod.DeleteProps
import typingsSlinky.wixUiIconsCommon.deleteSmallMod.DeleteSmallProps
import typingsSlinky.wixUiIconsCommon.desktopMod.DesktopProps
import typingsSlinky.wixUiIconsCommon.desktopSmallMod.DesktopSmallProps
import typingsSlinky.wixUiIconsCommon.dismissMod.DismissProps
import typingsSlinky.wixUiIconsCommon.dismissSmallMod.DismissSmallProps
import typingsSlinky.wixUiIconsCommon.distributeGlobeMod.DistributeGlobeProps
import typingsSlinky.wixUiIconsCommon.distributeGlobeSmallMod.DistributeGlobeSmallProps
import typingsSlinky.wixUiIconsCommon.distributeHorizontallyMod.DistributeHorizontallyProps
import typingsSlinky.wixUiIconsCommon.distributeHorizontallySmallMod.DistributeHorizontallySmallProps
import typingsSlinky.wixUiIconsCommon.distributeSmallMod.DistributeSmallProps
import typingsSlinky.wixUiIconsCommon.distributeVerticallyMod.DistributeVerticallyProps
import typingsSlinky.wixUiIconsCommon.distributeVerticallySmallMod.DistributeVerticallySmallProps
import typingsSlinky.wixUiIconsCommon.dividerMod.DividerProps
import typingsSlinky.wixUiIconsCommon.dividerSmallMod.DividerSmallProps
import typingsSlinky.wixUiIconsCommon.docDuplicateMod.DocDuplicateProps
import typingsSlinky.wixUiIconsCommon.docExpireMod.DocExpireProps
import typingsSlinky.wixUiIconsCommon.docExpireSmallMod.DocExpireSmallProps
import typingsSlinky.wixUiIconsCommon.docMovetoMod.DocMovetoProps
import typingsSlinky.wixUiIconsCommon.docMovetoSmallMod.DocMovetoSmallProps
import typingsSlinky.wixUiIconsCommon.docSendMod.DocSendProps
import typingsSlinky.wixUiIconsCommon.docSendSmallMod.DocSendSmallProps
import typingsSlinky.wixUiIconsCommon.documentExpireMod.DocumentExpireProps
import typingsSlinky.wixUiIconsCommon.documentExpireSmallMod.DocumentExpireSmallProps
import typingsSlinky.wixUiIconsCommon.documentMod.DocumentProps
import typingsSlinky.wixUiIconsCommon.documentSendMod.DocumentSendProps
import typingsSlinky.wixUiIconsCommon.documentSendSmallMod.DocumentSendSmallProps
import typingsSlinky.wixUiIconsCommon.documentSmallMod.DocumentSmallProps
import typingsSlinky.wixUiIconsCommon.downloadImportMod.DownloadImportProps
import typingsSlinky.wixUiIconsCommon.downloadImportSmallMod.DownloadImportSmallProps
import typingsSlinky.wixUiIconsCommon.downloadMod.DownloadProps
import typingsSlinky.wixUiIconsCommon.dropShadowBottomMod.DropShadowBottomProps
import typingsSlinky.wixUiIconsCommon.dropShadowBottomSmallMod.DropShadowBottomSmallProps
import typingsSlinky.wixUiIconsCommon.dropShadowLeftMod.DropShadowLeftProps
import typingsSlinky.wixUiIconsCommon.dropShadowLeftSmallMod.DropShadowLeftSmallProps
import typingsSlinky.wixUiIconsCommon.dropShadowRightMod.DropShadowRightProps
import typingsSlinky.wixUiIconsCommon.dropShadowRightSmallMod.DropShadowRightSmallProps
import typingsSlinky.wixUiIconsCommon.duplicateMod.DuplicateProps
import typingsSlinky.wixUiIconsCommon.duplicateSmallMod.DuplicateSmallProps
import typingsSlinky.wixUiIconsCommon.editMod.EditProps
import typingsSlinky.wixUiIconsCommon.editSmallMod.EditSmallProps
import typingsSlinky.wixUiIconsCommon.emailAlertMod.EmailAlertProps
import typingsSlinky.wixUiIconsCommon.emailAlertSmallMod.EmailAlertSmallProps
import typingsSlinky.wixUiIconsCommon.emailClickMod.EmailClickProps
import typingsSlinky.wixUiIconsCommon.emailClickSmallMod.EmailClickSmallProps
import typingsSlinky.wixUiIconsCommon.emailFilledMod.EmailFilledProps
import typingsSlinky.wixUiIconsCommon.emailFilledSmallMod.EmailFilledSmallProps
import typingsSlinky.wixUiIconsCommon.emailMod.EmailProps
import typingsSlinky.wixUiIconsCommon.emailOpenMod.EmailOpenProps
import typingsSlinky.wixUiIconsCommon.emailOpenSmallMod.EmailOpenSmallProps
import typingsSlinky.wixUiIconsCommon.emailSendMod.EmailSendProps
import typingsSlinky.wixUiIconsCommon.emailSendSmallMod.EmailSendSmallProps
import typingsSlinky.wixUiIconsCommon.emailSmallMod.EmailSmallProps
import typingsSlinky.wixUiIconsCommon.emptyTrashMod.EmptyTrashProps
import typingsSlinky.wixUiIconsCommon.emptyTrashSmallMod.EmptyTrashSmallProps
import typingsSlinky.wixUiIconsCommon.excludeMod.ExcludeProps
import typingsSlinky.wixUiIconsCommon.excludeSmallMod.ExcludeSmallProps
import typingsSlinky.wixUiIconsCommon.exposureMod.ExposureProps
import typingsSlinky.wixUiIconsCommon.exposureSmallMod.ExposureSmallProps
import typingsSlinky.wixUiIconsCommon.externalLinkMod.ExternalLinkProps
import typingsSlinky.wixUiIconsCommon.externalLinkSmallMod.ExternalLinkSmallProps
import typingsSlinky.wixUiIconsCommon.faceDisapointedMod.FaceDisapointedProps
import typingsSlinky.wixUiIconsCommon.faceFemaleMod.FaceFemaleProps
import typingsSlinky.wixUiIconsCommon.faceFemaleSmallMod.FaceFemaleSmallProps
import typingsSlinky.wixUiIconsCommon.faceFrowningMod.FaceFrowningProps
import typingsSlinky.wixUiIconsCommon.faceGriningMod.FaceGriningProps
import typingsSlinky.wixUiIconsCommon.faceNeutralMod.FaceNeutralProps
import typingsSlinky.wixUiIconsCommon.faceSmilingMod.FaceSmilingProps
import typingsSlinky.wixUiIconsCommon.facebookMod.FacebookProps
import typingsSlinky.wixUiIconsCommon.facebookSmallMod.FacebookSmallProps
import typingsSlinky.wixUiIconsCommon.favoriteFilledMod.FavoriteFilledProps
import typingsSlinky.wixUiIconsCommon.favoriteFilledSmallMod.FavoriteFilledSmallProps
import typingsSlinky.wixUiIconsCommon.favoriteMod.FavoriteProps
import typingsSlinky.wixUiIconsCommon.favoriteSmallMod.FavoriteSmallProps
import typingsSlinky.wixUiIconsCommon.faxMod.FaxProps
import typingsSlinky.wixUiIconsCommon.faxSmallMod.FaxSmallProps
import typingsSlinky.wixUiIconsCommon.fileDocumentSmallMod.FileDocumentSmallProps
import typingsSlinky.wixUiIconsCommon.filterSmallMod.FilterSmallProps
import typingsSlinky.wixUiIconsCommon.filtersMod.FiltersProps
import typingsSlinky.wixUiIconsCommon.filtersSmallMod.FiltersSmallProps
import typingsSlinky.wixUiIconsCommon.flagFilledMod.FlagFilledProps
import typingsSlinky.wixUiIconsCommon.flagFilledSmallMod.FlagFilledSmallProps
import typingsSlinky.wixUiIconsCommon.flagMod.FlagProps
import typingsSlinky.wixUiIconsCommon.flagSmallMod.FlagSmallProps
import typingsSlinky.wixUiIconsCommon.folderFindMod.FolderFindProps
import typingsSlinky.wixUiIconsCommon.folderFindSmallMod.FolderFindSmallProps
import typingsSlinky.wixUiIconsCommon.folderMod.FolderProps
import typingsSlinky.wixUiIconsCommon.folderMoveMod.FolderMoveProps
import typingsSlinky.wixUiIconsCommon.folderMoveSmallMod.FolderMoveSmallProps
import typingsSlinky.wixUiIconsCommon.folderSmallMod.FolderSmallProps
import typingsSlinky.wixUiIconsCommon.foodInStockMod.FoodInStockProps
import typingsSlinky.wixUiIconsCommon.foodInStockSmallMod.FoodInStockSmallProps
import typingsSlinky.wixUiIconsCommon.foodOutOfStockMod.FoodOutOfStockProps
import typingsSlinky.wixUiIconsCommon.foodOutOfStockSmallMod.FoodOutOfStockSmallProps
import typingsSlinky.wixUiIconsCommon.forwardMod.ForwardProps
import typingsSlinky.wixUiIconsCommon.forwardSmallMod.ForwardSmallProps
import typingsSlinky.wixUiIconsCommon.funnelChartMod.FunnelChartProps
import typingsSlinky.wixUiIconsCommon.funnelChartSmallMod.FunnelChartSmallProps
import typingsSlinky.wixUiIconsCommon.giftMod.GiftProps
import typingsSlinky.wixUiIconsCommon.giftSmallMod.GiftSmallProps
import typingsSlinky.wixUiIconsCommon.gitHubMod.GitHubProps
import typingsSlinky.wixUiIconsCommon.gitHubSmallMod.GitHubSmallProps
import typingsSlinky.wixUiIconsCommon.globeMod.GlobeProps
import typingsSlinky.wixUiIconsCommon.googleMod.GoogleProps
import typingsSlinky.wixUiIconsCommon.googleSmallMod.GoogleSmallProps
import typingsSlinky.wixUiIconsCommon.heartFilledMod.HeartFilledProps
import typingsSlinky.wixUiIconsCommon.heartFilledSmallMod.HeartFilledSmallProps
import typingsSlinky.wixUiIconsCommon.heartMod.HeartProps
import typingsSlinky.wixUiIconsCommon.heartSmallMod.HeartSmallProps
import typingsSlinky.wixUiIconsCommon.heatmapChartMod.HeatmapChartProps
import typingsSlinky.wixUiIconsCommon.heatmapChartSmallMod.HeatmapChartSmallProps
import typingsSlinky.wixUiIconsCommon.helpCircleMod.HelpCircleProps
import typingsSlinky.wixUiIconsCommon.helpCircleSmallMod.HelpCircleSmallProps
import typingsSlinky.wixUiIconsCommon.helpMod.HelpProps
import typingsSlinky.wixUiIconsCommon.helpSmallMod.HelpSmallProps
import typingsSlinky.wixUiIconsCommon.hiddenMod.HiddenProps
import typingsSlinky.wixUiIconsCommon.hiddenSmallMod.HiddenSmallProps
import typingsSlinky.wixUiIconsCommon.highlightsMod.HighlightsProps
import typingsSlinky.wixUiIconsCommon.highlightsSmallMod.HighlightsSmallProps
import typingsSlinky.wixUiIconsCommon.hintMod.HintProps
import typingsSlinky.wixUiIconsCommon.hintSmallMod.HintSmallProps
import typingsSlinky.wixUiIconsCommon.homeMod.HomeProps
import typingsSlinky.wixUiIconsCommon.homeSmallMod.HomeSmallProps
import typingsSlinky.wixUiIconsCommon.horizontalRatioCheckedMod.HorizontalRatioCheckedProps
import typingsSlinky.wixUiIconsCommon.horizontalRatioCheckedSmallMod.HorizontalRatioCheckedSmallProps
import typingsSlinky.wixUiIconsCommon.horizontalRatioMod.HorizontalRatioProps
import typingsSlinky.wixUiIconsCommon.horizontalRatioSmallMod.HorizontalRatioSmallProps
import typingsSlinky.wixUiIconsCommon.hotelMod.HotelProps
import typingsSlinky.wixUiIconsCommon.hotelSmallMod.HotelSmallProps
import typingsSlinky.wixUiIconsCommon.imageMod.ImageProps
import typingsSlinky.wixUiIconsCommon.imageSmallMod.ImageSmallProps
import typingsSlinky.wixUiIconsCommon.indoorLightMod.IndoorLightProps
import typingsSlinky.wixUiIconsCommon.indoorLightSmallMod.IndoorLightSmallProps
import typingsSlinky.wixUiIconsCommon.infoCircleMod.InfoCircleProps
import typingsSlinky.wixUiIconsCommon.infoCircleSmallMod.InfoCircleSmallProps
import typingsSlinky.wixUiIconsCommon.infoMod.InfoProps
import typingsSlinky.wixUiIconsCommon.infoSmallMod.InfoSmallProps
import typingsSlinky.wixUiIconsCommon.instagramMod.InstagramProps
import typingsSlinky.wixUiIconsCommon.instagramSmallMod.InstagramSmallProps
import typingsSlinky.wixUiIconsCommon.integrationsMod.IntegrationsProps
import typingsSlinky.wixUiIconsCommon.integrationsSmallMod.IntegrationsSmallProps
import typingsSlinky.wixUiIconsCommon.intersectMod.IntersectProps
import typingsSlinky.wixUiIconsCommon.intersectSmallMod.IntersectSmallProps
import typingsSlinky.wixUiIconsCommon.invoiceMod.InvoiceProps
import typingsSlinky.wixUiIconsCommon.invoiceSmallMod.InvoiceSmallProps
import typingsSlinky.wixUiIconsCommon.languagesMod.LanguagesProps
import typingsSlinky.wixUiIconsCommon.languagesSmallMod.LanguagesSmallProps
import typingsSlinky.wixUiIconsCommon.layersMod.LayersProps
import typingsSlinky.wixUiIconsCommon.layersSmallMod.LayersSmallProps
import typingsSlinky.wixUiIconsCommon.layoutGalleryMod.LayoutGalleryProps
import typingsSlinky.wixUiIconsCommon.layoutGallerySmallMod.LayoutGallerySmallProps
import typingsSlinky.wixUiIconsCommon.layoutGalleryWithPanelMod.LayoutGalleryWithPanelProps
import typingsSlinky.wixUiIconsCommon.layoutGalleryWithPanelSmallMod.LayoutGalleryWithPanelSmallProps
import typingsSlinky.wixUiIconsCommon.layoutListMod.LayoutListProps
import typingsSlinky.wixUiIconsCommon.layoutListSmallMod.LayoutListSmallProps
import typingsSlinky.wixUiIconsCommon.layoutListWithPanelMod.LayoutListWithPanelProps
import typingsSlinky.wixUiIconsCommon.layoutListWithPanelSmallMod.LayoutListWithPanelSmallProps
import typingsSlinky.wixUiIconsCommon.lineChartMod.LineChartProps
import typingsSlinky.wixUiIconsCommon.lineChartSmallMod.LineChartSmallProps
import typingsSlinky.wixUiIconsCommon.lineChartSplitMod.LineChartSplitProps
import typingsSlinky.wixUiIconsCommon.lineChartSplitSmallMod.LineChartSplitSmallProps
import typingsSlinky.wixUiIconsCommon.linkMod.LinkProps
import typingsSlinky.wixUiIconsCommon.linkSmallMod.LinkSmallProps
import typingsSlinky.wixUiIconsCommon.linkedInMod.LinkedInProps
import typingsSlinky.wixUiIconsCommon.linkedInSmallMod.LinkedInSmallProps
import typingsSlinky.wixUiIconsCommon.listMod.ListProps
import typingsSlinky.wixUiIconsCommon.listSmallMod.ListSmallProps
import typingsSlinky.wixUiIconsCommon.locationMod.LocationProps
import typingsSlinky.wixUiIconsCommon.locationSmallMod.LocationSmallProps
import typingsSlinky.wixUiIconsCommon.lockLockedMod.LockLockedProps
import typingsSlinky.wixUiIconsCommon.lockLockedSmallMod.LockLockedSmallProps
import typingsSlinky.wixUiIconsCommon.lockUnlockedMod.LockUnlockedProps
import typingsSlinky.wixUiIconsCommon.lockUnlockedSmallMod.LockUnlockedSmallProps
import typingsSlinky.wixUiIconsCommon.lowerCaseMod.LowerCaseProps
import typingsSlinky.wixUiIconsCommon.lowerCaseSmallMod.LowerCaseSmallProps
import typingsSlinky.wixUiIconsCommon.magicWandMod.MagicWandProps
import typingsSlinky.wixUiIconsCommon.magicWandSmallMod.MagicWandSmallProps
import typingsSlinky.wixUiIconsCommon.mapMod.MapProps
import typingsSlinky.wixUiIconsCommon.mapSmallMod.MapSmallProps
import typingsSlinky.wixUiIconsCommon.mergeMod.MergeProps
import typingsSlinky.wixUiIconsCommon.mergeSmallMod.MergeSmallProps
import typingsSlinky.wixUiIconsCommon.minusMod.MinusProps
import typingsSlinky.wixUiIconsCommon.minusSmallMod.MinusSmallProps
import typingsSlinky.wixUiIconsCommon.mirrorHorizontalMod.MirrorHorizontalProps
import typingsSlinky.wixUiIconsCommon.mirrorHorizontalSmallMod.MirrorHorizontalSmallProps
import typingsSlinky.wixUiIconsCommon.mirrorVerticalMod.MirrorVerticalProps
import typingsSlinky.wixUiIconsCommon.mirrorVerticalSmallMod.MirrorVerticalSmallProps
import typingsSlinky.wixUiIconsCommon.mobileMod.MobileProps
import typingsSlinky.wixUiIconsCommon.mobileSmallMod.MobileSmallProps
import typingsSlinky.wixUiIconsCommon.modalSmallMod.ModalSmallProps
import typingsSlinky.wixUiIconsCommon.moreMod.MoreProps
import typingsSlinky.wixUiIconsCommon.moreSmallMod.MoreSmallProps
import typingsSlinky.wixUiIconsCommon.moveToMod.MoveToProps
import typingsSlinky.wixUiIconsCommon.moveToSmallMod.MoveToSmallProps
import typingsSlinky.wixUiIconsCommon.multipleChoicesMod.MultipleChoicesProps
import typingsSlinky.wixUiIconsCommon.multipleChoicesSmallMod.MultipleChoicesSmallProps
import typingsSlinky.wixUiIconsCommon.musicMod.MusicProps
import typingsSlinky.wixUiIconsCommon.musicSmallMod.MusicSmallProps
import typingsSlinky.wixUiIconsCommon.newFolderMod.NewFolderProps
import typingsSlinky.wixUiIconsCommon.newFolderSmallMod.NewFolderSmallProps
import typingsSlinky.wixUiIconsCommon.noteMod.NoteProps
import typingsSlinky.wixUiIconsCommon.noteSmallMod.NoteSmallProps
import typingsSlinky.wixUiIconsCommon.notificationMod.NotificationProps
import typingsSlinky.wixUiIconsCommon.notificationSmallMod.NotificationSmallProps
import typingsSlinky.wixUiIconsCommon.numberMod.NumberProps
import typingsSlinky.wixUiIconsCommon.numberSmallMod.NumberSmallProps
import typingsSlinky.wixUiIconsCommon.objectsMod.ObjectsProps
import typingsSlinky.wixUiIconsCommon.objectsSmallMod.ObjectsSmallProps
import typingsSlinky.wixUiIconsCommon.openModalMod.OpenModalProps
import typingsSlinky.wixUiIconsCommon.openModalSmallMod.OpenModalSmallProps
import typingsSlinky.wixUiIconsCommon.orderAddMod.OrderAddProps
import typingsSlinky.wixUiIconsCommon.orderAddSmallMod.OrderAddSmallProps
import typingsSlinky.wixUiIconsCommon.orderMod.OrderProps
import typingsSlinky.wixUiIconsCommon.orderSmallMod.OrderSmallProps
import typingsSlinky.wixUiIconsCommon.overlayMod.OverlayProps
import typingsSlinky.wixUiIconsCommon.overlaySmallMod.OverlaySmallProps
import typingsSlinky.wixUiIconsCommon.pauseFilledMod.PauseFilledProps
import typingsSlinky.wixUiIconsCommon.pauseFilledSmallMod.PauseFilledSmallProps
import typingsSlinky.wixUiIconsCommon.pauseMod.PauseProps
import typingsSlinky.wixUiIconsCommon.pauseSmallMod.PauseSmallProps
import typingsSlinky.wixUiIconsCommon.paymentMod.PaymentProps
import typingsSlinky.wixUiIconsCommon.paymentSmallMod.PaymentSmallProps
import typingsSlinky.wixUiIconsCommon.penNibAddMod.PenNibAddProps
import typingsSlinky.wixUiIconsCommon.penNibAddSmallMod.PenNibAddSmallProps
import typingsSlinky.wixUiIconsCommon.penNibMod.PenNibProps
import typingsSlinky.wixUiIconsCommon.penNibSmallMod.PenNibSmallProps
import typingsSlinky.wixUiIconsCommon.phoneFilledMod.PhoneFilledProps
import typingsSlinky.wixUiIconsCommon.phoneFilledSmallMod.PhoneFilledSmallProps
import typingsSlinky.wixUiIconsCommon.phoneMod.PhoneProps
import typingsSlinky.wixUiIconsCommon.phoneSmallMod.PhoneSmallProps
import typingsSlinky.wixUiIconsCommon.photoCameraMod.PhotoCameraProps
import typingsSlinky.wixUiIconsCommon.photoCameraSmallMod.PhotoCameraSmallProps
import typingsSlinky.wixUiIconsCommon.pieChartMod.PieChartProps
import typingsSlinky.wixUiIconsCommon.pieChartSmallMod.PieChartSmallProps
import typingsSlinky.wixUiIconsCommon.pinMod.PinProps
import typingsSlinky.wixUiIconsCommon.pinSmallMod.PinSmallProps
import typingsSlinky.wixUiIconsCommon.pinterestMod.PinterestProps
import typingsSlinky.wixUiIconsCommon.pinterestSmallMod.PinterestSmallProps
import typingsSlinky.wixUiIconsCommon.playFilledMod.PlayFilledProps
import typingsSlinky.wixUiIconsCommon.playFilledSmallMod.PlayFilledSmallProps
import typingsSlinky.wixUiIconsCommon.playMod.PlayProps
import typingsSlinky.wixUiIconsCommon.playSmallMod.PlaySmallProps
import typingsSlinky.wixUiIconsCommon.premiumMod.PremiumProps
import typingsSlinky.wixUiIconsCommon.premiumSmallMod.PremiumSmallProps
import typingsSlinky.wixUiIconsCommon.previewMod.PreviewProps
import typingsSlinky.wixUiIconsCommon.previewSmallMod.PreviewSmallProps
import typingsSlinky.wixUiIconsCommon.printMod.PrintProps
import typingsSlinky.wixUiIconsCommon.printSmallMod.PrintSmallProps
import typingsSlinky.wixUiIconsCommon.promoteFilledMod.PromoteFilledProps
import typingsSlinky.wixUiIconsCommon.promoteFilledSmallMod.PromoteFilledSmallProps
import typingsSlinky.wixUiIconsCommon.promoteMod.PromoteProps
import typingsSlinky.wixUiIconsCommon.promoteSmallMod.PromoteSmallProps
import typingsSlinky.wixUiIconsCommon.publicMod.PublicProps
import typingsSlinky.wixUiIconsCommon.publicSmallMod.PublicSmallProps
import typingsSlinky.wixUiIconsCommon.rectangleLargeMod.RectangleLargeProps
import typingsSlinky.wixUiIconsCommon.rectangleLargeSmallMod.RectangleLargeSmallProps
import typingsSlinky.wixUiIconsCommon.redoMod.RedoProps
import typingsSlinky.wixUiIconsCommon.redoSmallMod.RedoSmallProps
import typingsSlinky.wixUiIconsCommon.refreshMod.RefreshProps
import typingsSlinky.wixUiIconsCommon.refreshSmallMod.RefreshSmallProps
import typingsSlinky.wixUiIconsCommon.refundMod.RefundProps
import typingsSlinky.wixUiIconsCommon.refundSmallMod.RefundSmallProps
import typingsSlinky.wixUiIconsCommon.renameMod.RenameProps
import typingsSlinky.wixUiIconsCommon.renameSmallMod.RenameSmallProps
import typingsSlinky.wixUiIconsCommon.replaceMod.ReplaceProps
import typingsSlinky.wixUiIconsCommon.replaceSmallMod.ReplaceSmallProps
import typingsSlinky.wixUiIconsCommon.revertMod.RevertProps
import typingsSlinky.wixUiIconsCommon.revertResetMod.RevertResetProps
import typingsSlinky.wixUiIconsCommon.revertSmallMod.RevertSmallProps
import typingsSlinky.wixUiIconsCommon.rotateLeftMod.RotateLeftProps
import typingsSlinky.wixUiIconsCommon.rotateLeftSmallMod.RotateLeftSmallProps
import typingsSlinky.wixUiIconsCommon.rotateRightMod.RotateRightProps
import typingsSlinky.wixUiIconsCommon.rotateRightSmallMod.RotateRightSmallProps
import typingsSlinky.wixUiIconsCommon.sceneryMod.SceneryProps
import typingsSlinky.wixUiIconsCommon.scenerySmallMod.ScenerySmallProps
import typingsSlinky.wixUiIconsCommon.searchMod.SearchProps
import typingsSlinky.wixUiIconsCommon.searchSmallMod.SearchSmallProps
import typingsSlinky.wixUiIconsCommon.sendMod.SendProps
import typingsSlinky.wixUiIconsCommon.sendSmallMod.SendSmallProps
import typingsSlinky.wixUiIconsCommon.sentenceCaseMod.SentenceCaseProps
import typingsSlinky.wixUiIconsCommon.sentenceCaseSmallMod.SentenceCaseSmallProps
import typingsSlinky.wixUiIconsCommon.settingsMod.SettingsProps
import typingsSlinky.wixUiIconsCommon.settingsSmallMod.SettingsSmallProps
import typingsSlinky.wixUiIconsCommon.shadowsMod.ShadowsProps
import typingsSlinky.wixUiIconsCommon.shadowsSmallMod.ShadowsSmallProps
import typingsSlinky.wixUiIconsCommon.shareMod.ShareProps
import typingsSlinky.wixUiIconsCommon.shareSmallMod.ShareSmallProps
import typingsSlinky.wixUiIconsCommon.sharpnessMod.SharpnessProps
import typingsSlinky.wixUiIconsCommon.sharpnessSmallMod.SharpnessSmallProps
import typingsSlinky.wixUiIconsCommon.siteAddMod.SiteAddProps
import typingsSlinky.wixUiIconsCommon.siteAddSmallMod.SiteAddSmallProps
import typingsSlinky.wixUiIconsCommon.siteDuplicateMod.SiteDuplicateProps
import typingsSlinky.wixUiIconsCommon.siteDuplicateSmallMod.SiteDuplicateSmallProps
import typingsSlinky.wixUiIconsCommon.siteMod.SiteProps
import typingsSlinky.wixUiIconsCommon.siteMoveMod.SiteMoveProps
import typingsSlinky.wixUiIconsCommon.siteMoveSmallMod.SiteMoveSmallProps
import typingsSlinky.wixUiIconsCommon.siteSearchMod.SiteSearchProps
import typingsSlinky.wixUiIconsCommon.siteSearchSmallMod.SiteSearchSmallProps
import typingsSlinky.wixUiIconsCommon.siteSmallMod.SiteSmallProps
import typingsSlinky.wixUiIconsCommon.sizeAndRatioMod.SizeAndRatioProps
import typingsSlinky.wixUiIconsCommon.sizeAndRatioSmallMod.SizeAndRatioSmallProps
import typingsSlinky.wixUiIconsCommon.smileMod.SmileProps
import typingsSlinky.wixUiIconsCommon.smileSmallMod.SmileSmallProps
import typingsSlinky.wixUiIconsCommon.sortAZMod.SortAZProps
import typingsSlinky.wixUiIconsCommon.sortAZSmallMod.SortAZSmallProps
import typingsSlinky.wixUiIconsCommon.sortAscendingMod.SortAscendingProps
import typingsSlinky.wixUiIconsCommon.sortAscendingSmallMod.SortAscendingSmallProps
import typingsSlinky.wixUiIconsCommon.sortDescendingMod.SortDescendingProps
import typingsSlinky.wixUiIconsCommon.sortDescendingSmallMod.SortDescendingSmallProps
import typingsSlinky.wixUiIconsCommon.sortZAMod.SortZAProps
import typingsSlinky.wixUiIconsCommon.sortZASmallMod.SortZASmallProps
import typingsSlinky.wixUiIconsCommon.soundCloudMod.SoundCloudProps
import typingsSlinky.wixUiIconsCommon.soundCloudSmallMod.SoundCloudSmallProps
import typingsSlinky.wixUiIconsCommon.soundMod.SoundProps
import typingsSlinky.wixUiIconsCommon.soundOffMod.SoundOffProps
import typingsSlinky.wixUiIconsCommon.soundOffSmallMod.SoundOffSmallProps
import typingsSlinky.wixUiIconsCommon.soundSmallMod.SoundSmallProps
import typingsSlinky.wixUiIconsCommon.squareRatioCheckedMod.SquareRatioCheckedProps
import typingsSlinky.wixUiIconsCommon.squareRatioCheckedSmallMod.SquareRatioCheckedSmallProps
import typingsSlinky.wixUiIconsCommon.squareRatioMod.SquareRatioProps
import typingsSlinky.wixUiIconsCommon.squareRatioSmallMod.SquareRatioSmallProps
import typingsSlinky.wixUiIconsCommon.starFilledMod.StarFilledProps
import typingsSlinky.wixUiIconsCommon.starMod.StarProps
import typingsSlinky.wixUiIconsCommon.statisticsMod.StatisticsProps
import typingsSlinky.wixUiIconsCommon.statisticsSmallMod.StatisticsSmallProps
import typingsSlinky.wixUiIconsCommon.statusAlertFilledMod.StatusAlertFilledProps
import typingsSlinky.wixUiIconsCommon.statusAlertFilledSmallMod.StatusAlertFilledSmallProps
import typingsSlinky.wixUiIconsCommon.statusAlertMod.StatusAlertProps
import typingsSlinky.wixUiIconsCommon.statusAlertPlainMod.StatusAlertPlainProps
import typingsSlinky.wixUiIconsCommon.statusAlertPlainSmallMod.StatusAlertPlainSmallProps
import typingsSlinky.wixUiIconsCommon.statusAlertSmallMod.StatusAlertSmallProps
import typingsSlinky.wixUiIconsCommon.statusCompleteFilledMod.StatusCompleteFilledProps
import typingsSlinky.wixUiIconsCommon.statusCompleteFilledSmallMod.StatusCompleteFilledSmallProps
import typingsSlinky.wixUiIconsCommon.statusCompleteMod.StatusCompleteProps
import typingsSlinky.wixUiIconsCommon.statusCompleteSmallMod.StatusCompleteSmallProps
import typingsSlinky.wixUiIconsCommon.statusCompletetFilledMod.StatusCompletetFilledProps
import typingsSlinky.wixUiIconsCommon.statusStopFilledMod.StatusStopFilledProps
import typingsSlinky.wixUiIconsCommon.statusStopFilledSmallMod.StatusStopFilledSmallProps
import typingsSlinky.wixUiIconsCommon.statusStopMod.StatusStopProps
import typingsSlinky.wixUiIconsCommon.statusStopSmallMod.StatusStopSmallProps
import typingsSlinky.wixUiIconsCommon.statusWarningFilledMod.StatusWarningFilledProps
import typingsSlinky.wixUiIconsCommon.statusWarningFilledSmallMod.StatusWarningFilledSmallProps
import typingsSlinky.wixUiIconsCommon.statusWarningMod.StatusWarningProps
import typingsSlinky.wixUiIconsCommon.statusWarningSmallMod.StatusWarningSmallProps
import typingsSlinky.wixUiIconsCommon.stopFilledMod.StopFilledProps
import typingsSlinky.wixUiIconsCommon.stopFilledSmallMod.StopFilledSmallProps
import typingsSlinky.wixUiIconsCommon.stopMod.StopProps
import typingsSlinky.wixUiIconsCommon.stopSmallMod.StopSmallProps
import typingsSlinky.wixUiIconsCommon.substractMod.SubstractProps
import typingsSlinky.wixUiIconsCommon.substractSmallMod.SubstractSmallProps
import typingsSlinky.wixUiIconsCommon.tableChartMod.TableChartProps
import typingsSlinky.wixUiIconsCommon.tableChartSmallMod.TableChartSmallProps
import typingsSlinky.wixUiIconsCommon.tagMod.TagProps
import typingsSlinky.wixUiIconsCommon.tagSmallMod.TagSmallProps
import typingsSlinky.wixUiIconsCommon.taskAddMod.TaskAddProps
import typingsSlinky.wixUiIconsCommon.taskAddSmallMod.TaskAddSmallProps
import typingsSlinky.wixUiIconsCommon.taskArchiveSmallMod.TaskArchiveSmallProps
import typingsSlinky.wixUiIconsCommon.taskCompleteMod.TaskCompleteProps
import typingsSlinky.wixUiIconsCommon.taskCompleteSmallMod.TaskCompleteSmallProps
import typingsSlinky.wixUiIconsCommon.temperatureMod.TemperatureProps
import typingsSlinky.wixUiIconsCommon.temperatureSmallMod.TemperatureSmallProps
import typingsSlinky.wixUiIconsCommon.templateMod.TemplateProps
import typingsSlinky.wixUiIconsCommon.templateSmallMod.TemplateSmallProps
import typingsSlinky.wixUiIconsCommon.textAlignCenterMod.TextAlignCenterProps
import typingsSlinky.wixUiIconsCommon.textAlignCenterSmallMod.TextAlignCenterSmallProps
import typingsSlinky.wixUiIconsCommon.textAlignLeftMod.TextAlignLeftProps
import typingsSlinky.wixUiIconsCommon.textAlignLeftSmallMod.TextAlignLeftSmallProps
import typingsSlinky.wixUiIconsCommon.textAlignRightMod.TextAlignRightProps
import typingsSlinky.wixUiIconsCommon.textAlignRightSmallMod.TextAlignRightSmallProps
import typingsSlinky.wixUiIconsCommon.textJustifyMod.TextJustifyProps
import typingsSlinky.wixUiIconsCommon.textJustifySmallMod.TextJustifySmallProps
import typingsSlinky.wixUiIconsCommon.thumbsUpFilledMod.ThumbsUpFilledProps
import typingsSlinky.wixUiIconsCommon.thumbsUpFilledSmallMod.ThumbsUpFilledSmallProps
import typingsSlinky.wixUiIconsCommon.thumbsUpMod.ThumbsUpProps
import typingsSlinky.wixUiIconsCommon.thumbsUpSmallMod.ThumbsUpSmallProps
import typingsSlinky.wixUiIconsCommon.timeMod.TimeProps
import typingsSlinky.wixUiIconsCommon.timeSmallMod.TimeSmallProps
import typingsSlinky.wixUiIconsCommon.toolboxMod.ToolboxProps
import typingsSlinky.wixUiIconsCommon.toolboxSmallMod.ToolboxSmallProps
import typingsSlinky.wixUiIconsCommon.transferMod.TransferProps
import typingsSlinky.wixUiIconsCommon.transferSmallMod.TransferSmallProps
import typingsSlinky.wixUiIconsCommon.transformSmallMod.TransformSmallProps
import typingsSlinky.wixUiIconsCommon.triangleLargeMod.TriangleLargeProps
import typingsSlinky.wixUiIconsCommon.triangleLargeSmallMod.TriangleLargeSmallProps
import typingsSlinky.wixUiIconsCommon.tshirtMod.TShirtProps
import typingsSlinky.wixUiIconsCommon.tshirtsmallMod.TShirtSmallProps
import typingsSlinky.wixUiIconsCommon.twitterMod.TwitterProps
import typingsSlinky.wixUiIconsCommon.twitterSmallMod.TwitterSmallProps
import typingsSlinky.wixUiIconsCommon.unarchiveMod.UnarchiveProps
import typingsSlinky.wixUiIconsCommon.unarchiveSmallMod.UnarchiveSmallProps
import typingsSlinky.wixUiIconsCommon.undoMod.UndoProps
import typingsSlinky.wixUiIconsCommon.undoSmallMod.UndoSmallProps
import typingsSlinky.wixUiIconsCommon.unionMod.UnionProps
import typingsSlinky.wixUiIconsCommon.unionSmallMod.UnionSmallProps
import typingsSlinky.wixUiIconsCommon.unlinkMod.UnlinkProps
import typingsSlinky.wixUiIconsCommon.unlinkSmallMod.UnlinkSmallProps
import typingsSlinky.wixUiIconsCommon.uploadExportMod.UploadExportProps
import typingsSlinky.wixUiIconsCommon.uploadExportSmallMod.UploadExportSmallProps
import typingsSlinky.wixUiIconsCommon.uploadMod.UploadProps
import typingsSlinky.wixUiIconsCommon.upperCaseMod.UpperCaseProps
import typingsSlinky.wixUiIconsCommon.upperCaseSmallMod.UpperCaseSmallProps
import typingsSlinky.wixUiIconsCommon.userAddMod.UserAddProps
import typingsSlinky.wixUiIconsCommon.userAddSmallMod.UserAddSmallProps
import typingsSlinky.wixUiIconsCommon.userBlockMod.UserBlockProps
import typingsSlinky.wixUiIconsCommon.userBlockSmallMod.UserBlockSmallProps
import typingsSlinky.wixUiIconsCommon.userJoinMod.UserJoinProps
import typingsSlinky.wixUiIconsCommon.userJoinSmallMod.UserJoinSmallProps
import typingsSlinky.wixUiIconsCommon.userLeaveMod.UserLeaveProps
import typingsSlinky.wixUiIconsCommon.userLeaveSmallMod.UserLeaveSmallProps
import typingsSlinky.wixUiIconsCommon.userMod.UserProps
import typingsSlinky.wixUiIconsCommon.userRemoveMod.UserRemoveProps
import typingsSlinky.wixUiIconsCommon.userRemoveSmallMod.UserRemoveSmallProps
import typingsSlinky.wixUiIconsCommon.userSmallMod.UserSmallProps
import typingsSlinky.wixUiIconsCommon.usersMod.UsersProps
import typingsSlinky.wixUiIconsCommon.usersSmallMod.UsersSmallProps
import typingsSlinky.wixUiIconsCommon.verticalRatioCheckedMod.VerticalRatioCheckedProps
import typingsSlinky.wixUiIconsCommon.verticalRatioCheckedSmallMod.VerticalRatioCheckedSmallProps
import typingsSlinky.wixUiIconsCommon.verticalRatioMod.VerticalRatioProps
import typingsSlinky.wixUiIconsCommon.verticalRatioSmallMod.VerticalRatioSmallProps
import typingsSlinky.wixUiIconsCommon.videoCameraMod.VideoCameraProps
import typingsSlinky.wixUiIconsCommon.videoCameraSmallMod.VideoCameraSmallProps
import typingsSlinky.wixUiIconsCommon.vignetteMod.VignetteProps
import typingsSlinky.wixUiIconsCommon.vignetteSmallMod.VignetteSmallProps
import typingsSlinky.wixUiIconsCommon.visibileHiddenMod.VisibileHiddenProps
import typingsSlinky.wixUiIconsCommon.visibleMod.VisibleProps
import typingsSlinky.wixUiIconsCommon.visibleSmallMod.VisibleSmallProps
import typingsSlinky.wixUiIconsCommon.volumeMod.VolumeProps
import typingsSlinky.wixUiIconsCommon.volumeSmallMod.VolumeSmallProps
import typingsSlinky.wixUiIconsCommon.whatsappMod.WhatsappProps
import typingsSlinky.wixUiIconsCommon.whatsappSmallMod.WhatsappSmallProps
import typingsSlinky.wixUiIconsCommon.wixChatFilledMod.WixChatFilledProps
import typingsSlinky.wixUiIconsCommon.wixChatFilledSmallMod.WixChatFilledSmallProps
import typingsSlinky.wixUiIconsCommon.wixChatMod.WixChatProps
import typingsSlinky.wixUiIconsCommon.wixChatSmallMod.WixChatSmallProps
import typingsSlinky.wixUiIconsCommon.wixFormsFilledMod.WixFormsFilledProps
import typingsSlinky.wixUiIconsCommon.wixFormsFilledSmallMod.WixFormsFilledSmallProps
import typingsSlinky.wixUiIconsCommon.wixFormsMod.WixFormsProps
import typingsSlinky.wixUiIconsCommon.wixFormsSmallMod.WixFormsSmallProps
import typingsSlinky.wixUiIconsCommon.wixMarketplaceMod.WixMarketplaceProps
import typingsSlinky.wixUiIconsCommon.wixMarketplaceSmallMod.WixMarketplaceSmallProps
import typingsSlinky.wixUiIconsCommon.xMod.XProps
import typingsSlinky.wixUiIconsCommon.yandexEnMod.YandexEnProps
import typingsSlinky.wixUiIconsCommon.yandexEnSmallMod.YandexEnSmallProps
import typingsSlinky.wixUiIconsCommon.yandexRuMod.YandexRuProps
import typingsSlinky.wixUiIconsCommon.yandexRuSmallMod.YandexRuSmallProps
import typingsSlinky.wixUiIconsCommon.youtubeFilledMod.YoutubeFilledProps
import typingsSlinky.wixUiIconsCommon.youtubeFilledSmallMod.YoutubeFilledSmallProps
import typingsSlinky.wixUiIconsCommon.youtubeMod.YoutubeProps
import typingsSlinky.wixUiIconsCommon.youtubeSmallMod.YoutubeSmallProps
import typingsSlinky.wixUiIconsCommon.zoomInMod.ZoomInProps
import typingsSlinky.wixUiIconsCommon.zoomInSmallMod.ZoomInSmallProps
import typingsSlinky.wixUiIconsCommon.zoomOutMod.ZoomOutProps
import typingsSlinky.wixUiIconsCommon.zoomOutSmallMod.ZoomOutSmallProps
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

@JSImport("wix-ui-icons-common/dist/es/src/general/dist", JSImport.Namespace)
@js.native
object mod extends js.Object {
  
  val Accessibility: ReactComponentClass[AccessibilityProps] = js.native
  
  val AccessibilitySmall: ReactComponentClass[AccessibilitySmallProps] = js.native
  
  val Add: ReactComponentClass[AddProps] = js.native
  
  val AddChannel: ReactComponentClass[AddChannelProps] = js.native
  
  val AddChannelSmall: ReactComponentClass[AddChannelSmallProps] = js.native
  
  val AddSmall: ReactComponentClass[AddSmallProps] = js.native
  
  val Adjust: ReactComponentClass[AdjustProps] = js.native
  
  val AdjustSmall: ReactComponentClass[AdjustSmallProps] = js.native
  
  val AdminAccess: ReactComponentClass[AdminAccessProps] = js.native
  
  val AdminAccessSmall: ReactComponentClass[AdminAccessSmallProps] = js.native
  
  val AlignBottom: ReactComponentClass[AlignBottomProps] = js.native
  
  val AlignBottomSmall: ReactComponentClass[AlignBottomSmallProps] = js.native
  
  val AlignCenterHorizontally: ReactComponentClass[AlignCenterHorizontallyProps] = js.native
  
  val AlignCenterHorizontallySmall: ReactComponentClass[AlignCenterHorizontallySmallProps] = js.native
  
  val AlignCenterVertically: ReactComponentClass[AlignCenterVerticallyProps] = js.native
  
  val AlignCenterVerticallySmall: ReactComponentClass[AlignCenterVerticallySmallProps] = js.native
  
  val AlignLeft: ReactComponentClass[AlignLeftProps] = js.native
  
  val AlignLeftSmall: ReactComponentClass[AlignLeftSmallProps] = js.native
  
  val AlignRight: ReactComponentClass[AlignRightProps] = js.native
  
  val AlignRightSmall: ReactComponentClass[AlignRightSmallProps] = js.native
  
  val AlignTop: ReactComponentClass[AlignTopProps] = js.native
  
  val AlignTopSmall: ReactComponentClass[AlignTopSmallProps] = js.native
  
  val AppMarket: ReactComponentClass[AppMarketProps] = js.native
  
  val AppMarketSmall: ReactComponentClass[AppMarketSmallProps] = js.native
  
  val Archive: ReactComponentClass[ArchiveProps] = js.native
  
  val ArchiveSmall: ReactComponentClass[ArchiveSmallProps] = js.native
  
  val ArrowDown: ReactComponentClass[ArrowDownProps] = js.native
  
  val ArrowDownRight: ReactComponentClass[ArrowDownRightProps] = js.native
  
  val ArrowDownRightSmall: ReactComponentClass[ArrowDownRightSmallProps] = js.native
  
  val ArrowDownSmall: ReactComponentClass[ArrowDownSmallProps] = js.native
  
  val ArrowLeft: ReactComponentClass[ArrowLeftProps] = js.native
  
  val ArrowLeftSmall: ReactComponentClass[ArrowLeftSmallProps] = js.native
  
  val ArrowRight: ReactComponentClass[ArrowRightProps] = js.native
  
  val ArrowRightSmall: ReactComponentClass[ArrowRightSmallProps] = js.native
  
  val ArrowUp: ReactComponentClass[ArrowUpProps] = js.native
  
  val ArrowUpSmall: ReactComponentClass[ArrowUpSmallProps] = js.native
  
  val Article: ReactComponentClass[ArticleProps] = js.native
  
  val ArticleSmall: ReactComponentClass[ArticleSmallProps] = js.native
  
  val Attachement: ReactComponentClass[AttachementProps] = js.native
  
  val Attachment: ReactComponentClass[AttachmentProps] = js.native
  
  val AttachmentSmall: ReactComponentClass[AttachmentSmallProps] = js.native
  
  val Automations: ReactComponentClass[AutomationsProps] = js.native
  
  val AutomationsFilled: ReactComponentClass[AutomationsFilledProps] = js.native
  
  val AutomationsFilledSmall: ReactComponentClass[AutomationsFilledSmallProps] = js.native
  
  val AutomationsSmall: ReactComponentClass[AutomationsSmallProps] = js.native
  
  val Background: ReactComponentClass[BackgroundProps] = js.native
  
  val BackgroundSmall: ReactComponentClass[BackgroundSmallProps] = js.native
  
  val Backward: ReactComponentClass[BackwardProps] = js.native
  
  val BackwardSmall: ReactComponentClass[BackwardSmallProps] = js.native
  
  val Badge: ReactComponentClass[BadgeProps] = js.native
  
  val BadgeSmall: ReactComponentClass[BadgeSmallProps] = js.native
  
  val BarChartSplit: ReactComponentClass[BarChartSplitProps] = js.native
  
  val BarChartSplitSmall: ReactComponentClass[BarChartSplitSmallProps] = js.native
  
  val Bing: ReactComponentClass[BingProps] = js.native
  
  val BingSmall: ReactComponentClass[BingSmallProps] = js.native
  
  val Block: ReactComponentClass[BlockProps] = js.native
  
  val BlockSmall: ReactComponentClass[BlockSmallProps] = js.native
  
  val BonusGift: ReactComponentClass[BonusGiftProps] = js.native
  
  val BonusGiftSmall: ReactComponentClass[BonusGiftSmallProps] = js.native
  
  val Bookmark: ReactComponentClass[BookmarkProps] = js.native
  
  val BookmarkFilled: ReactComponentClass[BookmarkFilledProps] = js.native
  
  val BookmarkFilledSmall: ReactComponentClass[BookmarkFilledSmallProps] = js.native
  
  val BookmarkSmall: ReactComponentClass[BookmarkSmallProps] = js.native
  
  val Bow: ReactComponentClass[BowProps] = js.native
  
  val BowSmall: ReactComponentClass[BowSmallProps] = js.native
  
  val Brightness: ReactComponentClass[BrightnessProps] = js.native
  
  val BrightnessSmall: ReactComponentClass[BrightnessSmallProps] = js.native
  
  val CahtFilledSmall: ReactComponentClass[CahtFilledSmallProps] = js.native
  
  val CancelOrder: ReactComponentClass[CancelOrderProps] = js.native
  
  val CancelOrderSmall: ReactComponentClass[CancelOrderSmallProps] = js.native
  
  val Cart: ReactComponentClass[CartProps] = js.native
  
  val CartSmall: ReactComponentClass[CartSmallProps] = js.native
  
  val Category: ReactComponentClass[CategoryProps] = js.native
  
  val CategorySmall: ReactComponentClass[CategorySmallProps] = js.native
  
  val Chat: ReactComponentClass[ChatProps] = js.native
  
  val ChatDisabed: ReactComponentClass[ChatDisabedProps] = js.native
  
  val ChatDisabled: ReactComponentClass[ChatDisabledProps] = js.native
  
  val ChatDisabledSmall: ReactComponentClass[ChatDisabledSmallProps] = js.native
  
  val ChatFilled: ReactComponentClass[ChatFilledProps] = js.native
  
  val ChatFilledSmall: ReactComponentClass[ChatFilledSmallProps] = js.native
  
  val ChatReply: ReactComponentClass[ChatReplyProps] = js.native
  
  val ChatReplySmall: ReactComponentClass[ChatReplySmallProps] = js.native
  
  val ChatSmall: ReactComponentClass[ChatSmallProps] = js.native
  
  val Check: ReactComponentClass[CheckProps] = js.native
  
  val ChevronDown: ReactComponentClass[ChevronDownProps] = js.native
  
  val ChevronDownCircle: ReactComponentClass[ChevronDownCircleProps] = js.native
  
  val ChevronDownCircleSmall: ReactComponentClass[ChevronDownCircleSmallProps] = js.native
  
  val ChevronDownLarge: ReactComponentClass[ChevronDownLargeProps] = js.native
  
  val ChevronDownLargeSmall: ReactComponentClass[ChevronDownLargeSmallProps] = js.native
  
  val ChevronDownSmall: ReactComponentClass[ChevronDownSmallProps] = js.native
  
  val ChevronLeft: ReactComponentClass[ChevronLeftProps] = js.native
  
  val ChevronLeftCircle: ReactComponentClass[ChevronLeftCircleProps] = js.native
  
  val ChevronLeftCircleSmall: ReactComponentClass[ChevronLeftCircleSmallProps] = js.native
  
  val ChevronLeftLarge: ReactComponentClass[ChevronLeftLargeProps] = js.native
  
  val ChevronLeftLargeSmall: ReactComponentClass[ChevronLeftLargeSmallProps] = js.native
  
  val ChevronLeftSmall: ReactComponentClass[ChevronLeftSmallProps] = js.native
  
  val ChevronRight: ReactComponentClass[ChevronRightProps] = js.native
  
  val ChevronRightCircle: ReactComponentClass[ChevronRightCircleProps] = js.native
  
  val ChevronRightCircleSmall: ReactComponentClass[ChevronRightCircleSmallProps] = js.native
  
  val ChevronRightLarge: ReactComponentClass[ChevronRightLargeProps] = js.native
  
  val ChevronRightLargeSmall: ReactComponentClass[ChevronRightLargeSmallProps] = js.native
  
  val ChevronRightSmall: ReactComponentClass[ChevronRightSmallProps] = js.native
  
  val ChevronUp: ReactComponentClass[ChevronUpProps] = js.native
  
  val ChevronUpCircle: ReactComponentClass[ChevronUpCircleProps] = js.native
  
  val ChevronUpCircleSmall: ReactComponentClass[ChevronUpCircleSmallProps] = js.native
  
  val ChevronUpLarge: ReactComponentClass[ChevronUpLargeProps] = js.native
  
  val ChevronUpLargeSmall: ReactComponentClass[ChevronUpLargeSmallProps] = js.native
  
  val ChevronUpSmall: ReactComponentClass[ChevronUpSmallProps] = js.native
  
  val CircleLarge: ReactComponentClass[CircleLargeProps] = js.native
  
  val CircleLargeSmall: ReactComponentClass[CircleLargeSmallProps] = js.native
  
  val CircleSmallFilled: ReactComponentClass[CircleSmallFilledProps] = js.native
  
  val CircleSmallFilledSmall: ReactComponentClass[CircleSmallFilledSmallProps] = js.native
  
  val Code: ReactComponentClass[CodeProps] = js.native
  
  val CodeSmall: ReactComponentClass[CodeSmallProps] = js.native
  
  val Collections: ReactComponentClass[CollectionsProps] = js.native
  
  val CollectionsSmall: ReactComponentClass[CollectionsSmallProps] = js.native
  
  val ColorDrop: ReactComponentClass[ColorDropProps] = js.native
  
  val ColorDropSmall: ReactComponentClass[ColorDropSmallProps] = js.native
  
  val Compose: ReactComponentClass[ComposeProps] = js.native
  
  val ComposeSmall: ReactComponentClass[ComposeSmallProps] = js.native
  
  val Confirm: ReactComponentClass[ConfirmProps] = js.native
  
  val ConfirmSmall: ReactComponentClass[ConfirmSmallProps] = js.native
  
  val ContentFilter: ReactComponentClass[ContentFilterProps] = js.native
  
  val ContentFilterSmall: ReactComponentClass[ContentFilterSmallProps] = js.native
  
  val Contrast: ReactComponentClass[ContrastProps] = js.native
  
  val ContrastSmall: ReactComponentClass[ContrastSmallProps] = js.native
  
  val Coupon: ReactComponentClass[CouponProps] = js.native
  
  val CouponSmall: ReactComponentClass[CouponSmallProps] = js.native
  
  val Crop: ReactComponentClass[CropProps] = js.native
  
  val CropRotate: ReactComponentClass[CropRotateProps] = js.native
  
  val CropRotateSmall: ReactComponentClass[CropRotateSmallProps] = js.native
  
  val CropSmall: ReactComponentClass[CropSmallProps] = js.native
  
  val CutOut: ReactComponentClass[CutOutProps] = js.native
  
  val CutOutSmall: ReactComponentClass[CutOutSmallProps] = js.native
  
  val Cutlery: ReactComponentClass[CutleryProps] = js.native
  
  val CutlerySmall: ReactComponentClass[CutlerySmallProps] = js.native
  
  val DataCollection: ReactComponentClass[DataCollectionProps] = js.native
  
  val DataCollectionSmall: ReactComponentClass[DataCollectionSmallProps] = js.native
  
  val Database: ReactComponentClass[DatabaseProps] = js.native
  
  val DatabaseSmall: ReactComponentClass[DatabaseSmallProps] = js.native
  
  val Date: ReactComponentClass[DateProps] = js.native
  
  val DateAdd: ReactComponentClass[DateAddProps] = js.native
  
  val DateAddSmall: ReactComponentClass[DateAddSmallProps] = js.native
  
  val DateAndTime: ReactComponentClass[DateAndTimeProps] = js.native
  
  val DateAndTimeSmall: ReactComponentClass[DateAndTimeSmallProps] = js.native
  
  val DateChecked: ReactComponentClass[DateCheckedProps] = js.native
  
  val DateCheckedSmall: ReactComponentClass[DateCheckedSmallProps] = js.native
  
  val DateSmall: ReactComponentClass[DateSmallProps] = js.native
  
  val Delete: ReactComponentClass[DeleteProps] = js.native
  
  val DeleteSmall: ReactComponentClass[DeleteSmallProps] = js.native
  
  val Desktop: ReactComponentClass[DesktopProps] = js.native
  
  val DesktopSmall: ReactComponentClass[DesktopSmallProps] = js.native
  
  val Dismiss: ReactComponentClass[DismissProps] = js.native
  
  val DismissSmall: ReactComponentClass[DismissSmallProps] = js.native
  
  val DistributeGlobe: ReactComponentClass[DistributeGlobeProps] = js.native
  
  val DistributeGlobeSmall: ReactComponentClass[DistributeGlobeSmallProps] = js.native
  
  val DistributeHorizontally: ReactComponentClass[DistributeHorizontallyProps] = js.native
  
  val DistributeHorizontallySmall: ReactComponentClass[DistributeHorizontallySmallProps] = js.native
  
  val DistributeSmall: ReactComponentClass[DistributeSmallProps] = js.native
  
  val DistributeVertically: ReactComponentClass[DistributeVerticallyProps] = js.native
  
  val DistributeVerticallySmall: ReactComponentClass[DistributeVerticallySmallProps] = js.native
  
  val Divider: ReactComponentClass[DividerProps] = js.native
  
  val DividerSmall: ReactComponentClass[DividerSmallProps] = js.native
  
  val DocDuplicate: ReactComponentClass[DocDuplicateProps] = js.native
  
  val DocExpire: ReactComponentClass[DocExpireProps] = js.native
  
  val DocExpireSmall: ReactComponentClass[DocExpireSmallProps] = js.native
  
  val DocMoveto: ReactComponentClass[DocMovetoProps] = js.native
  
  val DocMovetoSmall: ReactComponentClass[DocMovetoSmallProps] = js.native
  
  val DocSend: ReactComponentClass[DocSendProps] = js.native
  
  val DocSendSmall: ReactComponentClass[DocSendSmallProps] = js.native
  
  val Document: ReactComponentClass[DocumentProps] = js.native
  
  val DocumentExpire: ReactComponentClass[DocumentExpireProps] = js.native
  
  val DocumentExpireSmall: ReactComponentClass[DocumentExpireSmallProps] = js.native
  
  val DocumentSend: ReactComponentClass[DocumentSendProps] = js.native
  
  val DocumentSendSmall: ReactComponentClass[DocumentSendSmallProps] = js.native
  
  val DocumentSmall: ReactComponentClass[DocumentSmallProps] = js.native
  
  val Download: ReactComponentClass[DownloadProps] = js.native
  
  val DownloadImport: ReactComponentClass[DownloadImportProps] = js.native
  
  val DownloadImportSmall: ReactComponentClass[DownloadImportSmallProps] = js.native
  
  val DropShadowBottom: ReactComponentClass[DropShadowBottomProps] = js.native
  
  val DropShadowBottomSmall: ReactComponentClass[DropShadowBottomSmallProps] = js.native
  
  val DropShadowLeft: ReactComponentClass[DropShadowLeftProps] = js.native
  
  val DropShadowLeftSmall: ReactComponentClass[DropShadowLeftSmallProps] = js.native
  
  val DropShadowRight: ReactComponentClass[DropShadowRightProps] = js.native
  
  val DropShadowRightSmall: ReactComponentClass[DropShadowRightSmallProps] = js.native
  
  val Duplicate: ReactComponentClass[DuplicateProps] = js.native
  
  val DuplicateSmall: ReactComponentClass[DuplicateSmallProps] = js.native
  
  val Edit: ReactComponentClass[EditProps] = js.native
  
  val EditSmall: ReactComponentClass[EditSmallProps] = js.native
  
  val Email: ReactComponentClass[EmailProps] = js.native
  
  val EmailAlert: ReactComponentClass[EmailAlertProps] = js.native
  
  val EmailAlertSmall: ReactComponentClass[EmailAlertSmallProps] = js.native
  
  val EmailClick: ReactComponentClass[EmailClickProps] = js.native
  
  val EmailClickSmall: ReactComponentClass[EmailClickSmallProps] = js.native
  
  val EmailFilled: ReactComponentClass[EmailFilledProps] = js.native
  
  val EmailFilledSmall: ReactComponentClass[EmailFilledSmallProps] = js.native
  
  val EmailOpen: ReactComponentClass[EmailOpenProps] = js.native
  
  val EmailOpenSmall: ReactComponentClass[EmailOpenSmallProps] = js.native
  
  val EmailSend: ReactComponentClass[EmailSendProps] = js.native
  
  val EmailSendSmall: ReactComponentClass[EmailSendSmallProps] = js.native
  
  val EmailSmall: ReactComponentClass[EmailSmallProps] = js.native
  
  val EmptyTrash: ReactComponentClass[EmptyTrashProps] = js.native
  
  val EmptyTrashSmall: ReactComponentClass[EmptyTrashSmallProps] = js.native
  
  val Exclude: ReactComponentClass[ExcludeProps] = js.native
  
  val ExcludeSmall: ReactComponentClass[ExcludeSmallProps] = js.native
  
  val Exposure: ReactComponentClass[ExposureProps] = js.native
  
  val ExposureSmall: ReactComponentClass[ExposureSmallProps] = js.native
  
  val ExternalLink: ReactComponentClass[ExternalLinkProps] = js.native
  
  val ExternalLinkSmall: ReactComponentClass[ExternalLinkSmallProps] = js.native
  
  val FaceDisapointed: ReactComponentClass[FaceDisapointedProps] = js.native
  
  val FaceFemale: ReactComponentClass[FaceFemaleProps] = js.native
  
  val FaceFemaleSmall: ReactComponentClass[FaceFemaleSmallProps] = js.native
  
  val FaceFrowning: ReactComponentClass[FaceFrowningProps] = js.native
  
  val FaceGrining: ReactComponentClass[FaceGriningProps] = js.native
  
  val FaceNeutral: ReactComponentClass[FaceNeutralProps] = js.native
  
  val FaceSmiling: ReactComponentClass[FaceSmilingProps] = js.native
  
  val Facebook: ReactComponentClass[FacebookProps] = js.native
  
  val FacebookSmall: ReactComponentClass[FacebookSmallProps] = js.native
  
  val Favorite: ReactComponentClass[FavoriteProps] = js.native
  
  val FavoriteFilled: ReactComponentClass[FavoriteFilledProps] = js.native
  
  val FavoriteFilledSmall: ReactComponentClass[FavoriteFilledSmallProps] = js.native
  
  val FavoriteSmall: ReactComponentClass[FavoriteSmallProps] = js.native
  
  val Fax: ReactComponentClass[FaxProps] = js.native
  
  val FaxSmall: ReactComponentClass[FaxSmallProps] = js.native
  
  val FileDocumentSmall: ReactComponentClass[FileDocumentSmallProps] = js.native
  
  val FilterSmall: ReactComponentClass[FilterSmallProps] = js.native
  
  val Filters: ReactComponentClass[FiltersProps] = js.native
  
  val FiltersSmall: ReactComponentClass[FiltersSmallProps] = js.native
  
  val Flag: ReactComponentClass[FlagProps] = js.native
  
  val FlagFilled: ReactComponentClass[FlagFilledProps] = js.native
  
  val FlagFilledSmall: ReactComponentClass[FlagFilledSmallProps] = js.native
  
  val FlagSmall: ReactComponentClass[FlagSmallProps] = js.native
  
  val Folder: ReactComponentClass[FolderProps] = js.native
  
  val FolderFind: ReactComponentClass[FolderFindProps] = js.native
  
  val FolderFindSmall: ReactComponentClass[FolderFindSmallProps] = js.native
  
  val FolderMove: ReactComponentClass[FolderMoveProps] = js.native
  
  val FolderMoveSmall: ReactComponentClass[FolderMoveSmallProps] = js.native
  
  val FolderSmall: ReactComponentClass[FolderSmallProps] = js.native
  
  val FoodInStock: ReactComponentClass[FoodInStockProps] = js.native
  
  val FoodInStockSmall: ReactComponentClass[FoodInStockSmallProps] = js.native
  
  val FoodOutOfStock: ReactComponentClass[FoodOutOfStockProps] = js.native
  
  val FoodOutOfStockSmall: ReactComponentClass[FoodOutOfStockSmallProps] = js.native
  
  val Forward: ReactComponentClass[ForwardProps] = js.native
  
  val ForwardSmall: ReactComponentClass[ForwardSmallProps] = js.native
  
  val FunnelChart: ReactComponentClass[FunnelChartProps] = js.native
  
  val FunnelChartSmall: ReactComponentClass[FunnelChartSmallProps] = js.native
  
  val Gift: ReactComponentClass[GiftProps] = js.native
  
  val GiftSmall: ReactComponentClass[GiftSmallProps] = js.native
  
  val GitHub: ReactComponentClass[GitHubProps] = js.native
  
  val GitHubSmall: ReactComponentClass[GitHubSmallProps] = js.native
  
  val Globe: ReactComponentClass[GlobeProps] = js.native
  
  val Google: ReactComponentClass[GoogleProps] = js.native
  
  val GoogleSmall: ReactComponentClass[GoogleSmallProps] = js.native
  
  val Heart: ReactComponentClass[HeartProps] = js.native
  
  val HeartFilled: ReactComponentClass[HeartFilledProps] = js.native
  
  val HeartFilledSmall: ReactComponentClass[HeartFilledSmallProps] = js.native
  
  val HeartSmall: ReactComponentClass[HeartSmallProps] = js.native
  
  val HeatmapChart: ReactComponentClass[HeatmapChartProps] = js.native
  
  val HeatmapChartSmall: ReactComponentClass[HeatmapChartSmallProps] = js.native
  
  val Help: ReactComponentClass[HelpProps] = js.native
  
  val HelpCircle: ReactComponentClass[HelpCircleProps] = js.native
  
  val HelpCircleSmall: ReactComponentClass[HelpCircleSmallProps] = js.native
  
  val HelpSmall: ReactComponentClass[HelpSmallProps] = js.native
  
  val Hidden: ReactComponentClass[HiddenProps] = js.native
  
  val HiddenSmall: ReactComponentClass[HiddenSmallProps] = js.native
  
  val Highlights: ReactComponentClass[HighlightsProps] = js.native
  
  val HighlightsSmall: ReactComponentClass[HighlightsSmallProps] = js.native
  
  val Hint: ReactComponentClass[HintProps] = js.native
  
  val HintSmall: ReactComponentClass[HintSmallProps] = js.native
  
  val Home: ReactComponentClass[HomeProps] = js.native
  
  val HomeSmall: ReactComponentClass[HomeSmallProps] = js.native
  
  val HorizontalRatio: ReactComponentClass[HorizontalRatioProps] = js.native
  
  val HorizontalRatioChecked: ReactComponentClass[HorizontalRatioCheckedProps] = js.native
  
  val HorizontalRatioCheckedSmall: ReactComponentClass[HorizontalRatioCheckedSmallProps] = js.native
  
  val HorizontalRatioSmall: ReactComponentClass[HorizontalRatioSmallProps] = js.native
  
  val Hotel: ReactComponentClass[HotelProps] = js.native
  
  val HotelSmall: ReactComponentClass[HotelSmallProps] = js.native
  
  val Image: ReactComponentClass[ImageProps] = js.native
  
  val ImageSmall: ReactComponentClass[ImageSmallProps] = js.native
  
  val IndoorLight: ReactComponentClass[IndoorLightProps] = js.native
  
  val IndoorLightSmall: ReactComponentClass[IndoorLightSmallProps] = js.native
  
  val Info: ReactComponentClass[InfoProps] = js.native
  
  val InfoCircle: ReactComponentClass[InfoCircleProps] = js.native
  
  val InfoCircleSmall: ReactComponentClass[InfoCircleSmallProps] = js.native
  
  val InfoSmall: ReactComponentClass[InfoSmallProps] = js.native
  
  val Instagram: ReactComponentClass[InstagramProps] = js.native
  
  val InstagramSmall: ReactComponentClass[InstagramSmallProps] = js.native
  
  val Integrations: ReactComponentClass[IntegrationsProps] = js.native
  
  val IntegrationsSmall: ReactComponentClass[IntegrationsSmallProps] = js.native
  
  val Intersect: ReactComponentClass[IntersectProps] = js.native
  
  val IntersectSmall: ReactComponentClass[IntersectSmallProps] = js.native
  
  val Invoice: ReactComponentClass[InvoiceProps] = js.native
  
  val InvoiceSmall: ReactComponentClass[InvoiceSmallProps] = js.native
  
  val Languages: ReactComponentClass[LanguagesProps] = js.native
  
  val LanguagesSmall: ReactComponentClass[LanguagesSmallProps] = js.native
  
  val Layers: ReactComponentClass[LayersProps] = js.native
  
  val LayersSmall: ReactComponentClass[LayersSmallProps] = js.native
  
  val LayoutGallery: ReactComponentClass[LayoutGalleryProps] = js.native
  
  val LayoutGallerySmall: ReactComponentClass[LayoutGallerySmallProps] = js.native
  
  val LayoutGalleryWithPanel: ReactComponentClass[LayoutGalleryWithPanelProps] = js.native
  
  val LayoutGalleryWithPanelSmall: ReactComponentClass[LayoutGalleryWithPanelSmallProps] = js.native
  
  val LayoutList: ReactComponentClass[LayoutListProps] = js.native
  
  val LayoutListSmall: ReactComponentClass[LayoutListSmallProps] = js.native
  
  val LayoutListWithPanel: ReactComponentClass[LayoutListWithPanelProps] = js.native
  
  val LayoutListWithPanelSmall: ReactComponentClass[LayoutListWithPanelSmallProps] = js.native
  
  val LineChart: ReactComponentClass[LineChartProps] = js.native
  
  val LineChartSmall: ReactComponentClass[LineChartSmallProps] = js.native
  
  val LineChartSplit: ReactComponentClass[LineChartSplitProps] = js.native
  
  val LineChartSplitSmall: ReactComponentClass[LineChartSplitSmallProps] = js.native
  
  val Link: ReactComponentClass[LinkProps] = js.native
  
  val LinkSmall: ReactComponentClass[LinkSmallProps] = js.native
  
  val LinkedIn: ReactComponentClass[LinkedInProps] = js.native
  
  val LinkedInSmall: ReactComponentClass[LinkedInSmallProps] = js.native
  
  val List: ReactComponentClass[ListProps] = js.native
  
  val ListSmall: ReactComponentClass[ListSmallProps] = js.native
  
  val Location: ReactComponentClass[LocationProps] = js.native
  
  val LocationSmall: ReactComponentClass[LocationSmallProps] = js.native
  
  val LockLocked: ReactComponentClass[LockLockedProps] = js.native
  
  val LockLockedSmall: ReactComponentClass[LockLockedSmallProps] = js.native
  
  val LockUnlocked: ReactComponentClass[LockUnlockedProps] = js.native
  
  val LockUnlockedSmall: ReactComponentClass[LockUnlockedSmallProps] = js.native
  
  val LowerCase: ReactComponentClass[LowerCaseProps] = js.native
  
  val LowerCaseSmall: ReactComponentClass[LowerCaseSmallProps] = js.native
  
  val MagicWand: ReactComponentClass[MagicWandProps] = js.native
  
  val MagicWandSmall: ReactComponentClass[MagicWandSmallProps] = js.native
  
  val Map: ReactComponentClass[MapProps] = js.native
  
  val MapSmall: ReactComponentClass[MapSmallProps] = js.native
  
  val Merge: ReactComponentClass[MergeProps] = js.native
  
  val MergeSmall: ReactComponentClass[MergeSmallProps] = js.native
  
  val Minus: ReactComponentClass[MinusProps] = js.native
  
  val MinusSmall: ReactComponentClass[MinusSmallProps] = js.native
  
  val MirrorHorizontal: ReactComponentClass[MirrorHorizontalProps] = js.native
  
  val MirrorHorizontalSmall: ReactComponentClass[MirrorHorizontalSmallProps] = js.native
  
  val MirrorVertical: ReactComponentClass[MirrorVerticalProps] = js.native
  
  val MirrorVerticalSmall: ReactComponentClass[MirrorVerticalSmallProps] = js.native
  
  val Mobile: ReactComponentClass[MobileProps] = js.native
  
  val MobileSmall: ReactComponentClass[MobileSmallProps] = js.native
  
  val ModalSmall: ReactComponentClass[ModalSmallProps] = js.native
  
  val More: ReactComponentClass[MoreProps] = js.native
  
  val MoreSmall: ReactComponentClass[MoreSmallProps] = js.native
  
  val MoveTo: ReactComponentClass[MoveToProps] = js.native
  
  val MoveToSmall: ReactComponentClass[MoveToSmallProps] = js.native
  
  val MultipleChoices: ReactComponentClass[MultipleChoicesProps] = js.native
  
  val MultipleChoicesSmall: ReactComponentClass[MultipleChoicesSmallProps] = js.native
  
  val Music: ReactComponentClass[MusicProps] = js.native
  
  val MusicSmall: ReactComponentClass[MusicSmallProps] = js.native
  
  val NewFolder: ReactComponentClass[NewFolderProps] = js.native
  
  val NewFolderSmall: ReactComponentClass[NewFolderSmallProps] = js.native
  
  val Note: ReactComponentClass[NoteProps] = js.native
  
  val NoteSmall: ReactComponentClass[NoteSmallProps] = js.native
  
  val Notification: ReactComponentClass[NotificationProps] = js.native
  
  val NotificationSmall: ReactComponentClass[NotificationSmallProps] = js.native
  
  val Number: ReactComponentClass[NumberProps] = js.native
  
  val NumberSmall: ReactComponentClass[NumberSmallProps] = js.native
  
  val Objects: ReactComponentClass[ObjectsProps] = js.native
  
  val ObjectsSmall: ReactComponentClass[ObjectsSmallProps] = js.native
  
  val OpenModal: ReactComponentClass[OpenModalProps] = js.native
  
  val OpenModalSmall: ReactComponentClass[OpenModalSmallProps] = js.native
  
  val Order: ReactComponentClass[OrderProps] = js.native
  
  val OrderAdd: ReactComponentClass[OrderAddProps] = js.native
  
  val OrderAddSmall: ReactComponentClass[OrderAddSmallProps] = js.native
  
  val OrderSmall: ReactComponentClass[OrderSmallProps] = js.native
  
  val Overlay: ReactComponentClass[OverlayProps] = js.native
  
  val OverlaySmall: ReactComponentClass[OverlaySmallProps] = js.native
  
  val Pause: ReactComponentClass[PauseProps] = js.native
  
  val PauseFilled: ReactComponentClass[PauseFilledProps] = js.native
  
  val PauseFilledSmall: ReactComponentClass[PauseFilledSmallProps] = js.native
  
  val PauseSmall: ReactComponentClass[PauseSmallProps] = js.native
  
  val Payment: ReactComponentClass[PaymentProps] = js.native
  
  val PaymentSmall: ReactComponentClass[PaymentSmallProps] = js.native
  
  val PenNib: ReactComponentClass[PenNibProps] = js.native
  
  val PenNibAdd: ReactComponentClass[PenNibAddProps] = js.native
  
  val PenNibAddSmall: ReactComponentClass[PenNibAddSmallProps] = js.native
  
  val PenNibSmall: ReactComponentClass[PenNibSmallProps] = js.native
  
  val Phone: ReactComponentClass[PhoneProps] = js.native
  
  val PhoneFilled: ReactComponentClass[PhoneFilledProps] = js.native
  
  val PhoneFilledSmall: ReactComponentClass[PhoneFilledSmallProps] = js.native
  
  val PhoneSmall: ReactComponentClass[PhoneSmallProps] = js.native
  
  val PhotoCamera: ReactComponentClass[PhotoCameraProps] = js.native
  
  val PhotoCameraSmall: ReactComponentClass[PhotoCameraSmallProps] = js.native
  
  val PieChart: ReactComponentClass[PieChartProps] = js.native
  
  val PieChartSmall: ReactComponentClass[PieChartSmallProps] = js.native
  
  val Pin: ReactComponentClass[PinProps] = js.native
  
  val PinSmall: ReactComponentClass[PinSmallProps] = js.native
  
  val Pinterest: ReactComponentClass[PinterestProps] = js.native
  
  val PinterestSmall: ReactComponentClass[PinterestSmallProps] = js.native
  
  val Play: ReactComponentClass[PlayProps] = js.native
  
  val PlayFilled: ReactComponentClass[PlayFilledProps] = js.native
  
  val PlayFilledSmall: ReactComponentClass[PlayFilledSmallProps] = js.native
  
  val PlaySmall: ReactComponentClass[PlaySmallProps] = js.native
  
  val Premium: ReactComponentClass[PremiumProps] = js.native
  
  val PremiumSmall: ReactComponentClass[PremiumSmallProps] = js.native
  
  val Preview: ReactComponentClass[PreviewProps] = js.native
  
  val PreviewSmall: ReactComponentClass[PreviewSmallProps] = js.native
  
  val Print: ReactComponentClass[PrintProps] = js.native
  
  val PrintSmall: ReactComponentClass[PrintSmallProps] = js.native
  
  val Promote: ReactComponentClass[PromoteProps] = js.native
  
  val PromoteFilled: ReactComponentClass[PromoteFilledProps] = js.native
  
  val PromoteFilledSmall: ReactComponentClass[PromoteFilledSmallProps] = js.native
  
  val PromoteSmall: ReactComponentClass[PromoteSmallProps] = js.native
  
  val Public: ReactComponentClass[PublicProps] = js.native
  
  val PublicSmall: ReactComponentClass[PublicSmallProps] = js.native
  
  val RectangleLarge: ReactComponentClass[RectangleLargeProps] = js.native
  
  val RectangleLargeSmall: ReactComponentClass[RectangleLargeSmallProps] = js.native
  
  val Redo: ReactComponentClass[RedoProps] = js.native
  
  val RedoSmall: ReactComponentClass[RedoSmallProps] = js.native
  
  val Refresh: ReactComponentClass[RefreshProps] = js.native
  
  val RefreshSmall: ReactComponentClass[RefreshSmallProps] = js.native
  
  val Refund: ReactComponentClass[RefundProps] = js.native
  
  val RefundSmall: ReactComponentClass[RefundSmallProps] = js.native
  
  val Rename: ReactComponentClass[RenameProps] = js.native
  
  val RenameSmall: ReactComponentClass[RenameSmallProps] = js.native
  
  val Replace: ReactComponentClass[ReplaceProps] = js.native
  
  val ReplaceSmall: ReactComponentClass[ReplaceSmallProps] = js.native
  
  val Revert: ReactComponentClass[RevertProps] = js.native
  
  val RevertReset: ReactComponentClass[RevertResetProps] = js.native
  
  val RevertSmall: ReactComponentClass[RevertSmallProps] = js.native
  
  val RotateLeft: ReactComponentClass[RotateLeftProps] = js.native
  
  val RotateLeftSmall: ReactComponentClass[RotateLeftSmallProps] = js.native
  
  val RotateRight: ReactComponentClass[RotateRightProps] = js.native
  
  val RotateRightSmall: ReactComponentClass[RotateRightSmallProps] = js.native
  
  val Scenery: ReactComponentClass[SceneryProps] = js.native
  
  val ScenerySmall: ReactComponentClass[ScenerySmallProps] = js.native
  
  val Search: ReactComponentClass[SearchProps] = js.native
  
  val SearchSmall: ReactComponentClass[SearchSmallProps] = js.native
  
  val Send: ReactComponentClass[SendProps] = js.native
  
  val SendSmall: ReactComponentClass[SendSmallProps] = js.native
  
  val SentenceCase: ReactComponentClass[SentenceCaseProps] = js.native
  
  val SentenceCaseSmall: ReactComponentClass[SentenceCaseSmallProps] = js.native
  
  val Settings: ReactComponentClass[SettingsProps] = js.native
  
  val SettingsSmall: ReactComponentClass[SettingsSmallProps] = js.native
  
  val Shadows: ReactComponentClass[ShadowsProps] = js.native
  
  val ShadowsSmall: ReactComponentClass[ShadowsSmallProps] = js.native
  
  val Share: ReactComponentClass[ShareProps] = js.native
  
  val ShareSmall: ReactComponentClass[ShareSmallProps] = js.native
  
  val Sharpness: ReactComponentClass[SharpnessProps] = js.native
  
  val SharpnessSmall: ReactComponentClass[SharpnessSmallProps] = js.native
  
  val Site: ReactComponentClass[SiteProps] = js.native
  
  val SiteAdd: ReactComponentClass[SiteAddProps] = js.native
  
  val SiteAddSmall: ReactComponentClass[SiteAddSmallProps] = js.native
  
  val SiteDuplicate: ReactComponentClass[SiteDuplicateProps] = js.native
  
  val SiteDuplicateSmall: ReactComponentClass[SiteDuplicateSmallProps] = js.native
  
  val SiteMove: ReactComponentClass[SiteMoveProps] = js.native
  
  val SiteMoveSmall: ReactComponentClass[SiteMoveSmallProps] = js.native
  
  val SiteSearch: ReactComponentClass[SiteSearchProps] = js.native
  
  val SiteSearchSmall: ReactComponentClass[SiteSearchSmallProps] = js.native
  
  val SiteSmall: ReactComponentClass[SiteSmallProps] = js.native
  
  val SizeAndRatio: ReactComponentClass[SizeAndRatioProps] = js.native
  
  val SizeAndRatioSmall: ReactComponentClass[SizeAndRatioSmallProps] = js.native
  
  val Smile: ReactComponentClass[SmileProps] = js.native
  
  val SmileSmall: ReactComponentClass[SmileSmallProps] = js.native
  
  val SortAZ: ReactComponentClass[SortAZProps] = js.native
  
  val SortAZSmall: ReactComponentClass[SortAZSmallProps] = js.native
  
  val SortAscending: ReactComponentClass[SortAscendingProps] = js.native
  
  val SortAscendingSmall: ReactComponentClass[SortAscendingSmallProps] = js.native
  
  val SortDescending: ReactComponentClass[SortDescendingProps] = js.native
  
  val SortDescendingSmall: ReactComponentClass[SortDescendingSmallProps] = js.native
  
  val SortZA: ReactComponentClass[SortZAProps] = js.native
  
  val SortZASmall: ReactComponentClass[SortZASmallProps] = js.native
  
  val Sound: ReactComponentClass[SoundProps] = js.native
  
  val SoundCloud: ReactComponentClass[SoundCloudProps] = js.native
  
  val SoundCloudSmall: ReactComponentClass[SoundCloudSmallProps] = js.native
  
  val SoundOff: ReactComponentClass[SoundOffProps] = js.native
  
  val SoundOffSmall: ReactComponentClass[SoundOffSmallProps] = js.native
  
  val SoundSmall: ReactComponentClass[SoundSmallProps] = js.native
  
  val SquareRatio: ReactComponentClass[SquareRatioProps] = js.native
  
  val SquareRatioChecked: ReactComponentClass[SquareRatioCheckedProps] = js.native
  
  val SquareRatioCheckedSmall: ReactComponentClass[SquareRatioCheckedSmallProps] = js.native
  
  val SquareRatioSmall: ReactComponentClass[SquareRatioSmallProps] = js.native
  
  val Star: ReactComponentClass[StarProps] = js.native
  
  val StarFilled: ReactComponentClass[StarFilledProps] = js.native
  
  val Statistics: ReactComponentClass[StatisticsProps] = js.native
  
  val StatisticsSmall: ReactComponentClass[StatisticsSmallProps] = js.native
  
  val StatusAlert: ReactComponentClass[StatusAlertProps] = js.native
  
  val StatusAlertFilled: ReactComponentClass[StatusAlertFilledProps] = js.native
  
  val StatusAlertFilledSmall: ReactComponentClass[StatusAlertFilledSmallProps] = js.native
  
  val StatusAlertPlain: ReactComponentClass[StatusAlertPlainProps] = js.native
  
  val StatusAlertPlainSmall: ReactComponentClass[StatusAlertPlainSmallProps] = js.native
  
  val StatusAlertSmall: ReactComponentClass[StatusAlertSmallProps] = js.native
  
  val StatusComplete: ReactComponentClass[StatusCompleteProps] = js.native
  
  val StatusCompleteFilled: ReactComponentClass[StatusCompleteFilledProps] = js.native
  
  val StatusCompleteFilledSmall: ReactComponentClass[StatusCompleteFilledSmallProps] = js.native
  
  val StatusCompleteSmall: ReactComponentClass[StatusCompleteSmallProps] = js.native
  
  val StatusCompletetFilled: ReactComponentClass[StatusCompletetFilledProps] = js.native
  
  val StatusStop: ReactComponentClass[StatusStopProps] = js.native
  
  val StatusStopFilled: ReactComponentClass[StatusStopFilledProps] = js.native
  
  val StatusStopFilledSmall: ReactComponentClass[StatusStopFilledSmallProps] = js.native
  
  val StatusStopSmall: ReactComponentClass[StatusStopSmallProps] = js.native
  
  val StatusWarning: ReactComponentClass[StatusWarningProps] = js.native
  
  val StatusWarningFilled: ReactComponentClass[StatusWarningFilledProps] = js.native
  
  val StatusWarningFilledSmall: ReactComponentClass[StatusWarningFilledSmallProps] = js.native
  
  val StatusWarningSmall: ReactComponentClass[StatusWarningSmallProps] = js.native
  
  val Stop: ReactComponentClass[StopProps] = js.native
  
  val StopFilled: ReactComponentClass[StopFilledProps] = js.native
  
  val StopFilledSmall: ReactComponentClass[StopFilledSmallProps] = js.native
  
  val StopSmall: ReactComponentClass[StopSmallProps] = js.native
  
  val Substract: ReactComponentClass[SubstractProps] = js.native
  
  val SubstractSmall: ReactComponentClass[SubstractSmallProps] = js.native
  
  val TShirt: ReactComponentClass[TShirtProps] = js.native
  
  val TShirtSmall: ReactComponentClass[TShirtSmallProps] = js.native
  
  val TableChart: ReactComponentClass[TableChartProps] = js.native
  
  val TableChartSmall: ReactComponentClass[TableChartSmallProps] = js.native
  
  val Tag: ReactComponentClass[TagProps] = js.native
  
  val TagSmall: ReactComponentClass[TagSmallProps] = js.native
  
  val TaskAdd: ReactComponentClass[TaskAddProps] = js.native
  
  val TaskAddSmall: ReactComponentClass[TaskAddSmallProps] = js.native
  
  val TaskArchiveSmall: ReactComponentClass[TaskArchiveSmallProps] = js.native
  
  val TaskComplete: ReactComponentClass[TaskCompleteProps] = js.native
  
  val TaskCompleteSmall: ReactComponentClass[TaskCompleteSmallProps] = js.native
  
  val Temperature: ReactComponentClass[TemperatureProps] = js.native
  
  val TemperatureSmall: ReactComponentClass[TemperatureSmallProps] = js.native
  
  val Template: ReactComponentClass[TemplateProps] = js.native
  
  val TemplateSmall: ReactComponentClass[TemplateSmallProps] = js.native
  
  val TextAlignCenter: ReactComponentClass[TextAlignCenterProps] = js.native
  
  val TextAlignCenterSmall: ReactComponentClass[TextAlignCenterSmallProps] = js.native
  
  val TextAlignLeft: ReactComponentClass[TextAlignLeftProps] = js.native
  
  val TextAlignLeftSmall: ReactComponentClass[TextAlignLeftSmallProps] = js.native
  
  val TextAlignRight: ReactComponentClass[TextAlignRightProps] = js.native
  
  val TextAlignRightSmall: ReactComponentClass[TextAlignRightSmallProps] = js.native
  
  val TextJustify: ReactComponentClass[TextJustifyProps] = js.native
  
  val TextJustifySmall: ReactComponentClass[TextJustifySmallProps] = js.native
  
  val ThumbsUp: ReactComponentClass[ThumbsUpProps] = js.native
  
  val ThumbsUpFilled: ReactComponentClass[ThumbsUpFilledProps] = js.native
  
  val ThumbsUpFilledSmall: ReactComponentClass[ThumbsUpFilledSmallProps] = js.native
  
  val ThumbsUpSmall: ReactComponentClass[ThumbsUpSmallProps] = js.native
  
  val Time: ReactComponentClass[TimeProps] = js.native
  
  val TimeSmall: ReactComponentClass[TimeSmallProps] = js.native
  
  val Toolbox: ReactComponentClass[ToolboxProps] = js.native
  
  val ToolboxSmall: ReactComponentClass[ToolboxSmallProps] = js.native
  
  val Transfer: ReactComponentClass[TransferProps] = js.native
  
  val TransferSmall: ReactComponentClass[TransferSmallProps] = js.native
  
  val TransformSmall: ReactComponentClass[TransformSmallProps] = js.native
  
  val TriangleLarge: ReactComponentClass[TriangleLargeProps] = js.native
  
  val TriangleLargeSmall: ReactComponentClass[TriangleLargeSmallProps] = js.native
  
  val Twitter: ReactComponentClass[TwitterProps] = js.native
  
  val TwitterSmall: ReactComponentClass[TwitterSmallProps] = js.native
  
  val Unarchive: ReactComponentClass[UnarchiveProps] = js.native
  
  val UnarchiveSmall: ReactComponentClass[UnarchiveSmallProps] = js.native
  
  val Undo: ReactComponentClass[UndoProps] = js.native
  
  val UndoSmall: ReactComponentClass[UndoSmallProps] = js.native
  
  val Union: ReactComponentClass[UnionProps] = js.native
  
  val UnionSmall: ReactComponentClass[UnionSmallProps] = js.native
  
  val Unlink: ReactComponentClass[UnlinkProps] = js.native
  
  val UnlinkSmall: ReactComponentClass[UnlinkSmallProps] = js.native
  
  val Upload: ReactComponentClass[UploadProps] = js.native
  
  val UploadExport: ReactComponentClass[UploadExportProps] = js.native
  
  val UploadExportSmall: ReactComponentClass[UploadExportSmallProps] = js.native
  
  val UpperCase: ReactComponentClass[UpperCaseProps] = js.native
  
  val UpperCaseSmall: ReactComponentClass[UpperCaseSmallProps] = js.native
  
  val User: ReactComponentClass[UserProps] = js.native
  
  val UserAdd: ReactComponentClass[UserAddProps] = js.native
  
  val UserAddSmall: ReactComponentClass[UserAddSmallProps] = js.native
  
  val UserBlock: ReactComponentClass[UserBlockProps] = js.native
  
  val UserBlockSmall: ReactComponentClass[UserBlockSmallProps] = js.native
  
  val UserJoin: ReactComponentClass[UserJoinProps] = js.native
  
  val UserJoinSmall: ReactComponentClass[UserJoinSmallProps] = js.native
  
  val UserLeave: ReactComponentClass[UserLeaveProps] = js.native
  
  val UserLeaveSmall: ReactComponentClass[UserLeaveSmallProps] = js.native
  
  val UserRemove: ReactComponentClass[UserRemoveProps] = js.native
  
  val UserRemoveSmall: ReactComponentClass[UserRemoveSmallProps] = js.native
  
  val UserSmall: ReactComponentClass[UserSmallProps] = js.native
  
  val Users: ReactComponentClass[UsersProps] = js.native
  
  val UsersSmall: ReactComponentClass[UsersSmallProps] = js.native
  
  val VerticalRatio: ReactComponentClass[VerticalRatioProps] = js.native
  
  val VerticalRatioChecked: ReactComponentClass[VerticalRatioCheckedProps] = js.native
  
  val VerticalRatioCheckedSmall: ReactComponentClass[VerticalRatioCheckedSmallProps] = js.native
  
  val VerticalRatioSmall: ReactComponentClass[VerticalRatioSmallProps] = js.native
  
  val VideoCamera: ReactComponentClass[VideoCameraProps] = js.native
  
  val VideoCameraSmall: ReactComponentClass[VideoCameraSmallProps] = js.native
  
  val Vignette: ReactComponentClass[VignetteProps] = js.native
  
  val VignetteSmall: ReactComponentClass[VignetteSmallProps] = js.native
  
  val VisibileHidden: ReactComponentClass[VisibileHiddenProps] = js.native
  
  val Visible: ReactComponentClass[VisibleProps] = js.native
  
  val VisibleSmall: ReactComponentClass[VisibleSmallProps] = js.native
  
  val Volume: ReactComponentClass[VolumeProps] = js.native
  
  val VolumeSmall: ReactComponentClass[VolumeSmallProps] = js.native
  
  val Whatsapp: ReactComponentClass[WhatsappProps] = js.native
  
  val WhatsappSmall: ReactComponentClass[WhatsappSmallProps] = js.native
  
  val WixChat: ReactComponentClass[WixChatProps] = js.native
  
  val WixChatFilled: ReactComponentClass[WixChatFilledProps] = js.native
  
  val WixChatFilledSmall: ReactComponentClass[WixChatFilledSmallProps] = js.native
  
  val WixChatSmall: ReactComponentClass[WixChatSmallProps] = js.native
  
  val WixForms: ReactComponentClass[WixFormsProps] = js.native
  
  val WixFormsFilled: ReactComponentClass[WixFormsFilledProps] = js.native
  
  val WixFormsFilledSmall: ReactComponentClass[WixFormsFilledSmallProps] = js.native
  
  val WixFormsSmall: ReactComponentClass[WixFormsSmallProps] = js.native
  
  val WixMarketplace: ReactComponentClass[WixMarketplaceProps] = js.native
  
  val WixMarketplaceSmall: ReactComponentClass[WixMarketplaceSmallProps] = js.native
  
  val X: ReactComponentClass[XProps] = js.native
  
  val YandexEn: ReactComponentClass[YandexEnProps] = js.native
  
  val YandexEnSmall: ReactComponentClass[YandexEnSmallProps] = js.native
  
  val YandexRu: ReactComponentClass[YandexRuProps] = js.native
  
  val YandexRuSmall: ReactComponentClass[YandexRuSmallProps] = js.native
  
  val Youtube: ReactComponentClass[YoutubeProps] = js.native
  
  val YoutubeFilled: ReactComponentClass[YoutubeFilledProps] = js.native
  
  val YoutubeFilledSmall: ReactComponentClass[YoutubeFilledSmallProps] = js.native
  
  val YoutubeSmall: ReactComponentClass[YoutubeSmallProps] = js.native
  
  val ZoomIn: ReactComponentClass[ZoomInProps] = js.native
  
  val ZoomInSmall: ReactComponentClass[ZoomInSmallProps] = js.native
  
  val ZoomOut: ReactComponentClass[ZoomOutProps] = js.native
  
  val ZoomOutSmall: ReactComponentClass[ZoomOutSmallProps] = js.native
}
