package typingsSlinky.awsSdkClientCodecommitNode.getBranchExceptionsUnionMod

import typingsSlinky.awsSdkClientCodecommitNode.typesBranchDoesNotExistExceptionMod.BranchDoesNotExistException
import typingsSlinky.awsSdkClientCodecommitNode.typesBranchNameRequiredExceptionMod.BranchNameRequiredException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionIntegrityChecksFailedExceptionMod.EncryptionIntegrityChecksFailedException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyAccessDeniedExceptionMod.EncryptionKeyAccessDeniedException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyDisabledExceptionMod.EncryptionKeyDisabledException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyNotFoundExceptionMod.EncryptionKeyNotFoundException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyUnavailableExceptionMod.EncryptionKeyUnavailableException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidBranchNameExceptionMod.InvalidBranchNameException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryNameExceptionMod.InvalidRepositoryNameException
import typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryDoesNotExistExceptionMod.RepositoryDoesNotExistException
import typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryNameRequiredExceptionMod.RepositoryNameRequiredException
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryNameRequiredExceptionMod.RepositoryNameRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryDoesNotExistExceptionMod.RepositoryDoesNotExistException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryNameExceptionMod.InvalidRepositoryNameException
  - typingsSlinky.awsSdkClientCodecommitNode.typesBranchNameRequiredExceptionMod.BranchNameRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidBranchNameExceptionMod.InvalidBranchNameException
  - typingsSlinky.awsSdkClientCodecommitNode.typesBranchDoesNotExistExceptionMod.BranchDoesNotExistException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionIntegrityChecksFailedExceptionMod.EncryptionIntegrityChecksFailedException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyAccessDeniedExceptionMod.EncryptionKeyAccessDeniedException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyDisabledExceptionMod.EncryptionKeyDisabledException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyNotFoundExceptionMod.EncryptionKeyNotFoundException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyUnavailableExceptionMod.EncryptionKeyUnavailableException
*/
trait GetBranchExceptionsUnion extends js.Object

object GetBranchExceptionsUnion {
  @scala.inline
  implicit def apply(value: BranchDoesNotExistException): GetBranchExceptionsUnion = value.asInstanceOf[GetBranchExceptionsUnion]
  @scala.inline
  implicit def apply(value: BranchNameRequiredException): GetBranchExceptionsUnion = value.asInstanceOf[GetBranchExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionIntegrityChecksFailedException): GetBranchExceptionsUnion = value.asInstanceOf[GetBranchExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyAccessDeniedException): GetBranchExceptionsUnion = value.asInstanceOf[GetBranchExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyDisabledException): GetBranchExceptionsUnion = value.asInstanceOf[GetBranchExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyNotFoundException): GetBranchExceptionsUnion = value.asInstanceOf[GetBranchExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyUnavailableException): GetBranchExceptionsUnion = value.asInstanceOf[GetBranchExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidBranchNameException): GetBranchExceptionsUnion = value.asInstanceOf[GetBranchExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidRepositoryNameException): GetBranchExceptionsUnion = value.asInstanceOf[GetBranchExceptionsUnion]
  @scala.inline
  implicit def apply(value: RepositoryDoesNotExistException): GetBranchExceptionsUnion = value.asInstanceOf[GetBranchExceptionsUnion]
  @scala.inline
  implicit def apply(value: RepositoryNameRequiredException): GetBranchExceptionsUnion = value.asInstanceOf[GetBranchExceptionsUnion]
}

