package typingsSlinky.semanticUiApi.SemanticUI

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object ApiSettings {
  type Param = (typingsSlinky.semanticUiApi.PickImplapi | typingsSlinky.semanticUiApi.PickImplon | typingsSlinky.semanticUiApi.PickImplcache | typingsSlinky.semanticUiApi.PickImplstateContext | typingsSlinky.semanticUiApi.PickImplencodeParameters | typingsSlinky.semanticUiApi.PickImpldefaultData | typingsSlinky.semanticUiApi.PickImplserializeForm | typingsSlinky.semanticUiApi.PickImplthrottle | typingsSlinky.semanticUiApi.PickImplthrottleFirstRequ | typingsSlinky.semanticUiApi.PickImplinterruptRequests | typingsSlinky.semanticUiApi.PickImplloadingDuration | typingsSlinky.semanticUiApi.PickImplhideError | typingsSlinky.semanticUiApi.PickImplerrorDuration | typingsSlinky.semanticUiApi.PickImplaction | typingsSlinky.semanticUiApi.PickImplurl | typingsSlinky.semanticUiApi.PickImplurlData | typingsSlinky.semanticUiApi.PickImplresponse | typingsSlinky.semanticUiApi.PickImplresponseAsync | typingsSlinky.semanticUiApi.PickImplmockResponse | typingsSlinky.semanticUiApi.PickImplmockResponseAsync | typingsSlinky.semanticUiApi.PickImplmethod | typingsSlinky.semanticUiApi.PickImpldataType | typingsSlinky.semanticUiApi.PickImpldata | typingsSlinky.semanticUiApi.PickImplbeforeSend | typingsSlinky.semanticUiApi.PickImplbeforeXHR | typingsSlinky.semanticUiApi.PickImplonRequest | typingsSlinky.semanticUiApi.PickImplonResponse | typingsSlinky.semanticUiApi.PickImplsuccessTest | typingsSlinky.semanticUiApi.PickImplonSuccess | typingsSlinky.semanticUiApi.PickImplonComplete | typingsSlinky.semanticUiApi.PickImplonFailure | typingsSlinky.semanticUiApi.PickImplonError | typingsSlinky.semanticUiApi.PickImplonAbort | typingsSlinky.semanticUiApi.PickImplregExp | typingsSlinky.semanticUiApi.PickImplselector | typingsSlinky.semanticUiApi.PickImplclassName | typingsSlinky.semanticUiApi.PickImplmetadata | typingsSlinky.semanticUiApi.PickImplerror | typingsSlinky.semanticUiApi.PickImplnamespace | typingsSlinky.semanticUiApi.PickImplname | typingsSlinky.semanticUiApi.PickImplsilent | typingsSlinky.semanticUiApi.PickImpldebug | typingsSlinky.semanticUiApi.PickImplperformance | typingsSlinky.semanticUiApi.PickImplverbose) with typingsSlinky.semanticUiApi.PartialPickImplkeyofImpl
}
