package typingsSlinky.semanticUiApi.SemanticUI

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object ApiSettings {
  type Param = (typingsSlinky.semanticUiApi.anon.PickImplapi | typingsSlinky.semanticUiApi.anon.PickImplon | typingsSlinky.semanticUiApi.anon.PickImplcache | typingsSlinky.semanticUiApi.anon.PickImplstateContext | typingsSlinky.semanticUiApi.anon.PickImplencodeParameters | typingsSlinky.semanticUiApi.anon.PickImpldefaultData | typingsSlinky.semanticUiApi.anon.PickImplserializeForm | typingsSlinky.semanticUiApi.anon.PickImplthrottle | typingsSlinky.semanticUiApi.anon.PickImplthrottleFirstRequ | typingsSlinky.semanticUiApi.anon.PickImplinterruptRequests | typingsSlinky.semanticUiApi.anon.PickImplloadingDuration | typingsSlinky.semanticUiApi.anon.PickImplhideError | typingsSlinky.semanticUiApi.anon.PickImplerrorDuration | typingsSlinky.semanticUiApi.anon.PickImplaction | typingsSlinky.semanticUiApi.anon.PickImplurl | typingsSlinky.semanticUiApi.anon.PickImplurlData | typingsSlinky.semanticUiApi.anon.PickImplresponse | typingsSlinky.semanticUiApi.anon.PickImplresponseAsync | typingsSlinky.semanticUiApi.anon.PickImplmockResponse | typingsSlinky.semanticUiApi.anon.PickImplmockResponseAsync | typingsSlinky.semanticUiApi.anon.PickImplmethod | typingsSlinky.semanticUiApi.anon.PickImpldataType | typingsSlinky.semanticUiApi.anon.PickImpldata | typingsSlinky.semanticUiApi.anon.PickImplbeforeSend | typingsSlinky.semanticUiApi.anon.PickImplbeforeXHR | typingsSlinky.semanticUiApi.anon.PickImplonRequest | typingsSlinky.semanticUiApi.anon.PickImplonResponse | typingsSlinky.semanticUiApi.anon.PickImplsuccessTest | typingsSlinky.semanticUiApi.anon.PickImplonSuccess | typingsSlinky.semanticUiApi.anon.PickImplonComplete | typingsSlinky.semanticUiApi.anon.PickImplonFailure | typingsSlinky.semanticUiApi.anon.PickImplonError | typingsSlinky.semanticUiApi.anon.PickImplonAbort | typingsSlinky.semanticUiApi.anon.PickImplregExp | typingsSlinky.semanticUiApi.anon.PickImplselector | typingsSlinky.semanticUiApi.anon.PickImplclassName | typingsSlinky.semanticUiApi.anon.PickImplmetadata | typingsSlinky.semanticUiApi.anon.PickImplerror | typingsSlinky.semanticUiApi.anon.PickImplnamespace | typingsSlinky.semanticUiApi.anon.PickImplname | typingsSlinky.semanticUiApi.anon.PickImplsilent | typingsSlinky.semanticUiApi.anon.PickImpldebug | typingsSlinky.semanticUiApi.anon.PickImplperformance | typingsSlinky.semanticUiApi.anon.PickImplverbose) with typingsSlinky.semanticUiApi.anon.PartialPickImplkeyofImpl
}
