package typingsSlinky.activexLibreoffice.LibreOffice

import typingsSlinky.activexLibreoffice.activexLibreofficeStrings.SlashsingletonSlashcomDotsunDotstarDotbeansDottheIntrospection
import typingsSlinky.activexLibreoffice.activexLibreofficeStrings.SlashsingletonSlashcomDotsunDotstarDotconfigurationDotUpdate
import typingsSlinky.activexLibreoffice.activexLibreofficeStrings.SlashsingletonSlashcomDotsunDotstarDotconfigurationDottheDefaultProvider
import typingsSlinky.activexLibreoffice.activexLibreofficeStrings.SlashsingletonSlashcomDotsunDotstarDotdeploymentDotExtensionManager
import typingsSlinky.activexLibreoffice.activexLibreofficeStrings.SlashsingletonSlashcomDotsunDotstarDotdeploymentDotPackageInformationProvider
import typingsSlinky.activexLibreoffice.activexLibreofficeStrings.SlashsingletonSlashcomDotsunDotstarDotdeploymentDotthePackageManagerFactory
import typingsSlinky.activexLibreoffice.activexLibreofficeStrings.SlashsingletonSlashcomDotsunDotstarDotframeDottheAutoRecovery
import typingsSlinky.activexLibreoffice.activexLibreofficeStrings.SlashsingletonSlashcomDotsunDotstarDotframeDottheDesktop
import typingsSlinky.activexLibreoffice.activexLibreofficeStrings.SlashsingletonSlashcomDotsunDotstarDotframeDottheGlobalEventBroadcaster
import typingsSlinky.activexLibreoffice.activexLibreofficeStrings.SlashsingletonSlashcomDotsunDotstarDotframeDotthePopupMenuControllerFactory
import typingsSlinky.activexLibreoffice.activexLibreofficeStrings.SlashsingletonSlashcomDotsunDotstarDotframeDottheStatusbarControllerFactory
import typingsSlinky.activexLibreoffice.activexLibreofficeStrings.SlashsingletonSlashcomDotsunDotstarDotframeDottheToolbarControllerFactory
import typingsSlinky.activexLibreoffice.activexLibreofficeStrings.SlashsingletonSlashcomDotsunDotstarDotframeDottheUICommandDescription
import typingsSlinky.activexLibreoffice.activexLibreofficeStrings.SlashsingletonSlashcomDotsunDotstarDotloggingDotDocumentIOLogRing
import typingsSlinky.activexLibreoffice.activexLibreofficeStrings.SlashsingletonSlashcomDotsunDotstarDotloggingDotLoggerPool
import typingsSlinky.activexLibreoffice.activexLibreofficeStrings.SlashsingletonSlashcomDotsunDotstarDotreflectionDottheCoreReflection
import typingsSlinky.activexLibreoffice.activexLibreofficeStrings.SlashsingletonSlashcomDotsunDotstarDotresourceDotOfficeResourceLoader
import typingsSlinky.activexLibreoffice.activexLibreofficeStrings.SlashsingletonSlashcomDotsunDotstarDotscriptDotbrowseDottheBrowseNodeFactory
import typingsSlinky.activexLibreoffice.activexLibreofficeStrings.SlashsingletonSlashcomDotsunDotstarDotscriptDotproviderDottheMasterScriptProviderFactory
import typingsSlinky.activexLibreoffice.activexLibreofficeStrings.SlashsingletonSlashcomDotsunDotstarDotscriptDottheServiceDocumenter
import typingsSlinky.activexLibreoffice.activexLibreofficeStrings.SlashsingletonSlashcomDotsunDotstarDotsdbDotDataAccessDescriptorFactory
import typingsSlinky.activexLibreoffice.activexLibreofficeStrings.SlashsingletonSlashcomDotsunDotstarDottaskDotOfficeRestartManager
import typingsSlinky.activexLibreoffice.activexLibreofficeStrings.SlashsingletonSlashcomDotsunDotstarDottaskDottheJobExecutor
import typingsSlinky.activexLibreoffice.activexLibreofficeStrings.SlashsingletonSlashcomDotsunDotstarDotuiDotContextChangeEventMultiplexer
import typingsSlinky.activexLibreoffice.activexLibreofficeStrings.SlashsingletonSlashcomDotsunDotstarDotuiDottheModuleUIConfigurationManagerSupplier
import typingsSlinky.activexLibreoffice.activexLibreofficeStrings.SlashsingletonSlashcomDotsunDotstarDotuiDottheUICategoryDescription
import typingsSlinky.activexLibreoffice.activexLibreofficeStrings.SlashsingletonSlashcomDotsunDotstarDotuiDottheUIElementFactoryManager
import typingsSlinky.activexLibreoffice.activexLibreofficeStrings.SlashsingletonSlashcomDotsunDotstarDotuiDottheWindowContentFactoryManager
import typingsSlinky.activexLibreoffice.activexLibreofficeStrings.SlashsingletonSlashcomDotsunDotstarDotuiDottheWindowStateConfiguration
import typingsSlinky.activexLibreoffice.activexLibreofficeStrings.SlashsingletonSlashcomDotsunDotstarDotutilDottheMacroExpander
import typingsSlinky.activexLibreoffice.activexLibreofficeStrings.SlashsingletonSlashcomDotsunDotstarDotutilDottheOfficeInstallationDirectories
import typingsSlinky.activexLibreoffice.activexLibreofficeStrings.SlashsingletonSlashcomDotsunDotstarDotutilDotthePathSettings
import typingsSlinky.activexLibreoffice.com_.sun.star.beans.theIntrospection
import typingsSlinky.activexLibreoffice.com_.sun.star.configuration.Update
import typingsSlinky.activexLibreoffice.com_.sun.star.configuration.theDefaultProvider
import typingsSlinky.activexLibreoffice.com_.sun.star.container.XNameAccess
import typingsSlinky.activexLibreoffice.com_.sun.star.deployment.ExtensionManager
import typingsSlinky.activexLibreoffice.com_.sun.star.deployment.PackageInformationProvider
import typingsSlinky.activexLibreoffice.com_.sun.star.deployment.thePackageManagerFactory
import typingsSlinky.activexLibreoffice.com_.sun.star.frame.theAutoRecovery
import typingsSlinky.activexLibreoffice.com_.sun.star.frame.theDesktop
import typingsSlinky.activexLibreoffice.com_.sun.star.frame.theGlobalEventBroadcaster
import typingsSlinky.activexLibreoffice.com_.sun.star.frame.thePopupMenuControllerFactory
import typingsSlinky.activexLibreoffice.com_.sun.star.frame.theStatusbarControllerFactory
import typingsSlinky.activexLibreoffice.com_.sun.star.frame.theToolbarControllerFactory
import typingsSlinky.activexLibreoffice.com_.sun.star.frame.theUICommandDescription
import typingsSlinky.activexLibreoffice.com_.sun.star.logging.DocumentIOLogRing
import typingsSlinky.activexLibreoffice.com_.sun.star.logging.LoggerPool
import typingsSlinky.activexLibreoffice.com_.sun.star.reflection.theCoreReflection
import typingsSlinky.activexLibreoffice.com_.sun.star.resource.OfficeResourceLoader
import typingsSlinky.activexLibreoffice.com_.sun.star.script.browse.theBrowseNodeFactory
import typingsSlinky.activexLibreoffice.com_.sun.star.script.provider.theMasterScriptProviderFactory
import typingsSlinky.activexLibreoffice.com_.sun.star.script.theServiceDocumenter
import typingsSlinky.activexLibreoffice.com_.sun.star.sdb.DataAccessDescriptorFactory
import typingsSlinky.activexLibreoffice.com_.sun.star.task.OfficeRestartManager
import typingsSlinky.activexLibreoffice.com_.sun.star.task.theJobExecutor
import typingsSlinky.activexLibreoffice.com_.sun.star.ui.ContextChangeEventMultiplexer
import typingsSlinky.activexLibreoffice.com_.sun.star.ui.theModuleUIConfigurationManagerSupplier
import typingsSlinky.activexLibreoffice.com_.sun.star.ui.theUICategoryDescription
import typingsSlinky.activexLibreoffice.com_.sun.star.ui.theUIElementFactoryManager
import typingsSlinky.activexLibreoffice.com_.sun.star.ui.theWindowContentFactoryManager
import typingsSlinky.activexLibreoffice.com_.sun.star.ui.theWindowStateConfiguration
import typingsSlinky.activexLibreoffice.com_.sun.star.util.theMacroExpander
import typingsSlinky.activexLibreoffice.com_.sun.star.util.theOfficeInstallationDirectories
import typingsSlinky.activexLibreoffice.com_.sun.star.util.thePathSettings
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait AutomationScriptContext extends XNameAccess {
  @JSName("getByName")
  def getByName_singletoncomsunstarbeanstheIntrospection(aName: SlashsingletonSlashcomDotsunDotstarDotbeansDottheIntrospection): theIntrospection = js.native
  @JSName("getByName")
  def getByName_singletoncomsunstarconfigurationUpdate(aName: SlashsingletonSlashcomDotsunDotstarDotconfigurationDotUpdate): Update = js.native
  @JSName("getByName")
  def getByName_singletoncomsunstarconfigurationtheDefaultProvider(aName: SlashsingletonSlashcomDotsunDotstarDotconfigurationDottheDefaultProvider): theDefaultProvider = js.native
  @JSName("getByName")
  def getByName_singletoncomsunstardeploymentExtensionManager(aName: SlashsingletonSlashcomDotsunDotstarDotdeploymentDotExtensionManager): ExtensionManager = js.native
  @JSName("getByName")
  def getByName_singletoncomsunstardeploymentPackageInformationProvider(aName: SlashsingletonSlashcomDotsunDotstarDotdeploymentDotPackageInformationProvider): PackageInformationProvider = js.native
  @JSName("getByName")
  def getByName_singletoncomsunstardeploymentthePackageManagerFactory(aName: SlashsingletonSlashcomDotsunDotstarDotdeploymentDotthePackageManagerFactory): thePackageManagerFactory = js.native
  @JSName("getByName")
  def getByName_singletoncomsunstarframetheAutoRecovery(aName: SlashsingletonSlashcomDotsunDotstarDotframeDottheAutoRecovery): theAutoRecovery = js.native
  @JSName("getByName")
  def getByName_singletoncomsunstarframetheDesktop(aName: SlashsingletonSlashcomDotsunDotstarDotframeDottheDesktop): theDesktop = js.native
  @JSName("getByName")
  def getByName_singletoncomsunstarframetheGlobalEventBroadcaster(aName: SlashsingletonSlashcomDotsunDotstarDotframeDottheGlobalEventBroadcaster): theGlobalEventBroadcaster = js.native
  @JSName("getByName")
  def getByName_singletoncomsunstarframethePopupMenuControllerFactory(aName: SlashsingletonSlashcomDotsunDotstarDotframeDotthePopupMenuControllerFactory): thePopupMenuControllerFactory = js.native
  @JSName("getByName")
  def getByName_singletoncomsunstarframetheStatusbarControllerFactory(aName: SlashsingletonSlashcomDotsunDotstarDotframeDottheStatusbarControllerFactory): theStatusbarControllerFactory = js.native
  @JSName("getByName")
  def getByName_singletoncomsunstarframetheToolbarControllerFactory(aName: SlashsingletonSlashcomDotsunDotstarDotframeDottheToolbarControllerFactory): theToolbarControllerFactory = js.native
  @JSName("getByName")
  def getByName_singletoncomsunstarframetheUICommandDescription(aName: SlashsingletonSlashcomDotsunDotstarDotframeDottheUICommandDescription): theUICommandDescription = js.native
  @JSName("getByName")
  def getByName_singletoncomsunstarloggingDocumentIOLogRing(aName: SlashsingletonSlashcomDotsunDotstarDotloggingDotDocumentIOLogRing): DocumentIOLogRing = js.native
  @JSName("getByName")
  def getByName_singletoncomsunstarloggingLoggerPool(aName: SlashsingletonSlashcomDotsunDotstarDotloggingDotLoggerPool): LoggerPool = js.native
  @JSName("getByName")
  def getByName_singletoncomsunstarreflectiontheCoreReflection(aName: SlashsingletonSlashcomDotsunDotstarDotreflectionDottheCoreReflection): theCoreReflection = js.native
  @JSName("getByName")
  def getByName_singletoncomsunstarresourceOfficeResourceLoader(aName: SlashsingletonSlashcomDotsunDotstarDotresourceDotOfficeResourceLoader): OfficeResourceLoader = js.native
  @JSName("getByName")
  def getByName_singletoncomsunstarscriptbrowsetheBrowseNodeFactory(aName: SlashsingletonSlashcomDotsunDotstarDotscriptDotbrowseDottheBrowseNodeFactory): theBrowseNodeFactory = js.native
  @JSName("getByName")
  def getByName_singletoncomsunstarscriptprovidertheMasterScriptProviderFactory(aName: SlashsingletonSlashcomDotsunDotstarDotscriptDotproviderDottheMasterScriptProviderFactory): theMasterScriptProviderFactory = js.native
  @JSName("getByName")
  def getByName_singletoncomsunstarscripttheServiceDocumenter(aName: SlashsingletonSlashcomDotsunDotstarDotscriptDottheServiceDocumenter): theServiceDocumenter = js.native
  @JSName("getByName")
  def getByName_singletoncomsunstarsdbDataAccessDescriptorFactory(aName: SlashsingletonSlashcomDotsunDotstarDotsdbDotDataAccessDescriptorFactory): DataAccessDescriptorFactory = js.native
  @JSName("getByName")
  def getByName_singletoncomsunstartaskOfficeRestartManager(aName: SlashsingletonSlashcomDotsunDotstarDottaskDotOfficeRestartManager): OfficeRestartManager = js.native
  @JSName("getByName")
  def getByName_singletoncomsunstartasktheJobExecutor(aName: SlashsingletonSlashcomDotsunDotstarDottaskDottheJobExecutor): theJobExecutor = js.native
  @JSName("getByName")
  def getByName_singletoncomsunstaruiContextChangeEventMultiplexer(aName: SlashsingletonSlashcomDotsunDotstarDotuiDotContextChangeEventMultiplexer): ContextChangeEventMultiplexer = js.native
  @JSName("getByName")
  def getByName_singletoncomsunstaruitheModuleUIConfigurationManagerSupplier(aName: SlashsingletonSlashcomDotsunDotstarDotuiDottheModuleUIConfigurationManagerSupplier): theModuleUIConfigurationManagerSupplier = js.native
  @JSName("getByName")
  def getByName_singletoncomsunstaruitheUICategoryDescription(aName: SlashsingletonSlashcomDotsunDotstarDotuiDottheUICategoryDescription): theUICategoryDescription = js.native
  @JSName("getByName")
  def getByName_singletoncomsunstaruitheUIElementFactoryManager(aName: SlashsingletonSlashcomDotsunDotstarDotuiDottheUIElementFactoryManager): theUIElementFactoryManager = js.native
  @JSName("getByName")
  def getByName_singletoncomsunstaruitheWindowContentFactoryManager(aName: SlashsingletonSlashcomDotsunDotstarDotuiDottheWindowContentFactoryManager): theWindowContentFactoryManager = js.native
  @JSName("getByName")
  def getByName_singletoncomsunstaruitheWindowStateConfiguration(aName: SlashsingletonSlashcomDotsunDotstarDotuiDottheWindowStateConfiguration): theWindowStateConfiguration = js.native
  @JSName("getByName")
  def getByName_singletoncomsunstarutiltheMacroExpander(aName: SlashsingletonSlashcomDotsunDotstarDotutilDottheMacroExpander): theMacroExpander = js.native
  @JSName("getByName")
  def getByName_singletoncomsunstarutiltheOfficeInstallationDirectories(aName: SlashsingletonSlashcomDotsunDotstarDotutilDottheOfficeInstallationDirectories): theOfficeInstallationDirectories = js.native
  @JSName("getByName")
  def getByName_singletoncomsunstarutilthePathSettings(aName: SlashsingletonSlashcomDotsunDotstarDotutilDotthePathSettings): thePathSettings = js.native
}

