package typingsSlinky.preact.mod.createElement.JSX

import org.scalajs.dom.raw.EventTarget
import typingsSlinky.preact.anon.Html
import typingsSlinky.preact.mod.ComponentChildren
import typingsSlinky.preact.mod.PreactDOMAttributes
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait DOMAttributes[Target /* <: EventTarget */] extends PreactDOMAttributes {
  // Media Events
  var onAbort: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onAbortCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onAnimationEnd: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.AnimationEventHandler[Target]] = js.undefined
  var onAnimationEndCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.AnimationEventHandler[Target]] = js.undefined
  var onAnimationIteration: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.AnimationEventHandler[Target]] = js.undefined
  var onAnimationIterationCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.AnimationEventHandler[Target]] = js.undefined
  // Animation Events
  var onAnimationStart: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.AnimationEventHandler[Target]] = js.undefined
  var onAnimationStartCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.AnimationEventHandler[Target]] = js.undefined
  var onBlur: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.FocusEventHandler[Target]] = js.undefined
  var onBlurCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.FocusEventHandler[Target]] = js.undefined
  var onCanPlay: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onCanPlayCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onCanPlayThrough: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onCanPlayThroughCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  // Form Events
  var onChange: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onChangeCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  // MouseEvents
  var onClick: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onClickCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  // Composition Events
  var onCompositionEnd: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.CompositionEventHandler[Target]] = js.undefined
  var onCompositionEndCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.CompositionEventHandler[Target]] = js.undefined
  var onCompositionStart: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.CompositionEventHandler[Target]] = js.undefined
  var onCompositionStartCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.CompositionEventHandler[Target]] = js.undefined
  var onCompositionUpdate: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.CompositionEventHandler[Target]] = js.undefined
  var onCompositionUpdateCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.CompositionEventHandler[Target]] = js.undefined
  var onContextMenu: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onContextMenuCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  // Clipboard Events
  var onCopy: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.ClipboardEventHandler[Target]] = js.undefined
  var onCopyCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.ClipboardEventHandler[Target]] = js.undefined
  var onCut: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.ClipboardEventHandler[Target]] = js.undefined
  var onCutCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.ClipboardEventHandler[Target]] = js.undefined
  var onDblClick: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onDblClickCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onDrag: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.DragEventHandler[Target]] = js.undefined
  var onDragCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.DragEventHandler[Target]] = js.undefined
  var onDragEnd: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.DragEventHandler[Target]] = js.undefined
  var onDragEndCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.DragEventHandler[Target]] = js.undefined
  var onDragEnter: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.DragEventHandler[Target]] = js.undefined
  var onDragEnterCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.DragEventHandler[Target]] = js.undefined
  var onDragExit: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.DragEventHandler[Target]] = js.undefined
  var onDragExitCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.DragEventHandler[Target]] = js.undefined
  var onDragLeave: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.DragEventHandler[Target]] = js.undefined
  var onDragLeaveCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.DragEventHandler[Target]] = js.undefined
  var onDragOver: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.DragEventHandler[Target]] = js.undefined
  var onDragOverCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.DragEventHandler[Target]] = js.undefined
  var onDragStart: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.DragEventHandler[Target]] = js.undefined
  var onDragStartCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.DragEventHandler[Target]] = js.undefined
  var onDrop: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.DragEventHandler[Target]] = js.undefined
  var onDropCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.DragEventHandler[Target]] = js.undefined
  var onDurationChange: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onDurationChangeCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onEmptied: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onEmptiedCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onEncrypted: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onEncryptedCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onEnded: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onEndedCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onError: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onErrorCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  // Focus Events
  var onFocus: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.FocusEventHandler[Target]] = js.undefined
  var onFocusCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.FocusEventHandler[Target]] = js.undefined
  var onFormData: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onFormDataCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onGotPointerCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onGotPointerCaptureCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onInput: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onInputCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onInvalid: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onInvalidCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  // Keyboard Events
  var onKeyDown: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.KeyboardEventHandler[Target]] = js.undefined
  var onKeyDownCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.KeyboardEventHandler[Target]] = js.undefined
  var onKeyPress: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.KeyboardEventHandler[Target]] = js.undefined
  var onKeyPressCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.KeyboardEventHandler[Target]] = js.undefined
  var onKeyUp: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.KeyboardEventHandler[Target]] = js.undefined
  var onKeyUpCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.KeyboardEventHandler[Target]] = js.undefined
  // Image Events
  var onLoad: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onLoadCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onLoadStart: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onLoadStartCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onLoadedData: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onLoadedDataCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onLoadedMetadata: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onLoadedMetadataCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onLostPointerCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onLostPointerCaptureCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onMouseDown: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onMouseDownCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onMouseEnter: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onMouseEnterCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onMouseLeave: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onMouseLeaveCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onMouseMove: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onMouseMoveCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onMouseOut: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onMouseOutCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onMouseOver: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onMouseOverCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onMouseUp: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onMouseUpCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target]] = js.undefined
  var onPaste: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.ClipboardEventHandler[Target]] = js.undefined
  var onPasteCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.ClipboardEventHandler[Target]] = js.undefined
  var onPause: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onPauseCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onPlay: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onPlayCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onPlaying: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onPlayingCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onPointerCancel: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onPointerCancelCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onPointerDown: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onPointerDownCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onPointerEnter: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onPointerEnterCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onPointerLeave: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onPointerLeaveCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onPointerMove: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onPointerMoveCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onPointerOut: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onPointerOutCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  // Pointer Events
  var onPointerOver: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onPointerOverCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onPointerUp: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onPointerUpCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target]] = js.undefined
  var onProgress: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onProgressCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onRateChange: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onRateChangeCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onReset: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onResetCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  // UI Events
  var onScroll: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.UIEventHandler[Target]] = js.undefined
  var onScrollCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.UIEventHandler[Target]] = js.undefined
  var onSearch: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onSearchCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onSeeked: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onSeekedCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onSeeking: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onSeekingCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  // Selection Events
  var onSelect: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onSelectCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onStalled: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onStalledCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onSubmit: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onSubmitCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onSuspend: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onSuspendCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onTimeUpdate: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onTimeUpdateCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  // Details Events
  var onToggle: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  // Touch Events
  var onTouchCancel: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.TouchEventHandler[Target]] = js.undefined
  var onTouchCancelCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.TouchEventHandler[Target]] = js.undefined
  var onTouchEnd: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.TouchEventHandler[Target]] = js.undefined
  var onTouchEndCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.TouchEventHandler[Target]] = js.undefined
  var onTouchMove: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.TouchEventHandler[Target]] = js.undefined
  var onTouchMoveCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.TouchEventHandler[Target]] = js.undefined
  var onTouchStart: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.TouchEventHandler[Target]] = js.undefined
  var onTouchStartCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.TouchEventHandler[Target]] = js.undefined
  // Transition Events
  var onTransitionEnd: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.TransitionEventHandler[Target]] = js.undefined
  var onTransitionEndCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.TransitionEventHandler[Target]] = js.undefined
  var onVolumeChange: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onVolumeChangeCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onWaiting: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  var onWaitingCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target]] = js.undefined
  // Wheel Events
  var onWheel: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.WheelEventHandler[Target]] = js.undefined
  var onWheelCapture: js.UndefOr[typingsSlinky.preact.jsxMod.JSXInternal.WheelEventHandler[Target]] = js.undefined
}

object DOMAttributes {
  @scala.inline
  def apply[Target](
    children: js.UndefOr[Null | ComponentChildren] = js.undefined,
    dangerouslySetInnerHTML: Html = null,
    onAbort: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onAbortCapture: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onAnimationEnd: typingsSlinky.preact.jsxMod.JSXInternal.AnimationEventHandler[Target] = null,
    onAnimationEndCapture: typingsSlinky.preact.jsxMod.JSXInternal.AnimationEventHandler[Target] = null,
    onAnimationIteration: typingsSlinky.preact.jsxMod.JSXInternal.AnimationEventHandler[Target] = null,
    onAnimationIterationCapture: typingsSlinky.preact.jsxMod.JSXInternal.AnimationEventHandler[Target] = null,
    onAnimationStart: typingsSlinky.preact.jsxMod.JSXInternal.AnimationEventHandler[Target] = null,
    onAnimationStartCapture: typingsSlinky.preact.jsxMod.JSXInternal.AnimationEventHandler[Target] = null,
    onBlur: typingsSlinky.preact.jsxMod.JSXInternal.FocusEventHandler[Target] = null,
    onBlurCapture: typingsSlinky.preact.jsxMod.JSXInternal.FocusEventHandler[Target] = null,
    onCanPlay: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onCanPlayCapture: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onCanPlayThrough: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onCanPlayThroughCapture: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onChange: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onChangeCapture: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onClick: typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onClickCapture: typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onCompositionEnd: typingsSlinky.preact.jsxMod.JSXInternal.CompositionEventHandler[Target] = null,
    onCompositionEndCapture: typingsSlinky.preact.jsxMod.JSXInternal.CompositionEventHandler[Target] = null,
    onCompositionStart: typingsSlinky.preact.jsxMod.JSXInternal.CompositionEventHandler[Target] = null,
    onCompositionStartCapture: typingsSlinky.preact.jsxMod.JSXInternal.CompositionEventHandler[Target] = null,
    onCompositionUpdate: typingsSlinky.preact.jsxMod.JSXInternal.CompositionEventHandler[Target] = null,
    onCompositionUpdateCapture: typingsSlinky.preact.jsxMod.JSXInternal.CompositionEventHandler[Target] = null,
    onContextMenu: typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onContextMenuCapture: typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onCopy: typingsSlinky.preact.jsxMod.JSXInternal.ClipboardEventHandler[Target] = null,
    onCopyCapture: typingsSlinky.preact.jsxMod.JSXInternal.ClipboardEventHandler[Target] = null,
    onCut: typingsSlinky.preact.jsxMod.JSXInternal.ClipboardEventHandler[Target] = null,
    onCutCapture: typingsSlinky.preact.jsxMod.JSXInternal.ClipboardEventHandler[Target] = null,
    onDblClick: typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onDblClickCapture: typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onDrag: typingsSlinky.preact.jsxMod.JSXInternal.DragEventHandler[Target] = null,
    onDragCapture: typingsSlinky.preact.jsxMod.JSXInternal.DragEventHandler[Target] = null,
    onDragEnd: typingsSlinky.preact.jsxMod.JSXInternal.DragEventHandler[Target] = null,
    onDragEndCapture: typingsSlinky.preact.jsxMod.JSXInternal.DragEventHandler[Target] = null,
    onDragEnter: typingsSlinky.preact.jsxMod.JSXInternal.DragEventHandler[Target] = null,
    onDragEnterCapture: typingsSlinky.preact.jsxMod.JSXInternal.DragEventHandler[Target] = null,
    onDragExit: typingsSlinky.preact.jsxMod.JSXInternal.DragEventHandler[Target] = null,
    onDragExitCapture: typingsSlinky.preact.jsxMod.JSXInternal.DragEventHandler[Target] = null,
    onDragLeave: typingsSlinky.preact.jsxMod.JSXInternal.DragEventHandler[Target] = null,
    onDragLeaveCapture: typingsSlinky.preact.jsxMod.JSXInternal.DragEventHandler[Target] = null,
    onDragOver: typingsSlinky.preact.jsxMod.JSXInternal.DragEventHandler[Target] = null,
    onDragOverCapture: typingsSlinky.preact.jsxMod.JSXInternal.DragEventHandler[Target] = null,
    onDragStart: typingsSlinky.preact.jsxMod.JSXInternal.DragEventHandler[Target] = null,
    onDragStartCapture: typingsSlinky.preact.jsxMod.JSXInternal.DragEventHandler[Target] = null,
    onDrop: typingsSlinky.preact.jsxMod.JSXInternal.DragEventHandler[Target] = null,
    onDropCapture: typingsSlinky.preact.jsxMod.JSXInternal.DragEventHandler[Target] = null,
    onDurationChange: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onDurationChangeCapture: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onEmptied: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onEmptiedCapture: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onEncrypted: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onEncryptedCapture: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onEnded: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onEndedCapture: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onError: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onErrorCapture: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onFocus: typingsSlinky.preact.jsxMod.JSXInternal.FocusEventHandler[Target] = null,
    onFocusCapture: typingsSlinky.preact.jsxMod.JSXInternal.FocusEventHandler[Target] = null,
    onFormData: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onFormDataCapture: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onGotPointerCapture: typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onGotPointerCaptureCapture: typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onInput: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onInputCapture: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onInvalid: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onInvalidCapture: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onKeyDown: typingsSlinky.preact.jsxMod.JSXInternal.KeyboardEventHandler[Target] = null,
    onKeyDownCapture: typingsSlinky.preact.jsxMod.JSXInternal.KeyboardEventHandler[Target] = null,
    onKeyPress: typingsSlinky.preact.jsxMod.JSXInternal.KeyboardEventHandler[Target] = null,
    onKeyPressCapture: typingsSlinky.preact.jsxMod.JSXInternal.KeyboardEventHandler[Target] = null,
    onKeyUp: typingsSlinky.preact.jsxMod.JSXInternal.KeyboardEventHandler[Target] = null,
    onKeyUpCapture: typingsSlinky.preact.jsxMod.JSXInternal.KeyboardEventHandler[Target] = null,
    onLoad: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onLoadCapture: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onLoadStart: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onLoadStartCapture: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onLoadedData: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onLoadedDataCapture: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onLoadedMetadata: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onLoadedMetadataCapture: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onLostPointerCapture: typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onLostPointerCaptureCapture: typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onMouseDown: typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onMouseDownCapture: typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onMouseEnter: typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onMouseEnterCapture: typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onMouseLeave: typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onMouseLeaveCapture: typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onMouseMove: typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onMouseMoveCapture: typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onMouseOut: typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onMouseOutCapture: typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onMouseOver: typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onMouseOverCapture: typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onMouseUp: typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onMouseUpCapture: typingsSlinky.preact.jsxMod.JSXInternal.MouseEventHandler[Target] = null,
    onPaste: typingsSlinky.preact.jsxMod.JSXInternal.ClipboardEventHandler[Target] = null,
    onPasteCapture: typingsSlinky.preact.jsxMod.JSXInternal.ClipboardEventHandler[Target] = null,
    onPause: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onPauseCapture: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onPlay: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onPlayCapture: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onPlaying: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onPlayingCapture: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onPointerCancel: typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onPointerCancelCapture: typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onPointerDown: typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onPointerDownCapture: typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onPointerEnter: typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onPointerEnterCapture: typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onPointerLeave: typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onPointerLeaveCapture: typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onPointerMove: typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onPointerMoveCapture: typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onPointerOut: typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onPointerOutCapture: typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onPointerOver: typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onPointerOverCapture: typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onPointerUp: typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onPointerUpCapture: typingsSlinky.preact.jsxMod.JSXInternal.PointerEventHandler[Target] = null,
    onProgress: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onProgressCapture: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onRateChange: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onRateChangeCapture: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onReset: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onResetCapture: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onScroll: typingsSlinky.preact.jsxMod.JSXInternal.UIEventHandler[Target] = null,
    onScrollCapture: typingsSlinky.preact.jsxMod.JSXInternal.UIEventHandler[Target] = null,
    onSearch: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onSearchCapture: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onSeeked: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onSeekedCapture: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onSeeking: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onSeekingCapture: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onSelect: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onSelectCapture: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onStalled: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onStalledCapture: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onSubmit: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onSubmitCapture: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onSuspend: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onSuspendCapture: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onTimeUpdate: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onTimeUpdateCapture: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onToggle: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onTouchCancel: typingsSlinky.preact.jsxMod.JSXInternal.TouchEventHandler[Target] = null,
    onTouchCancelCapture: typingsSlinky.preact.jsxMod.JSXInternal.TouchEventHandler[Target] = null,
    onTouchEnd: typingsSlinky.preact.jsxMod.JSXInternal.TouchEventHandler[Target] = null,
    onTouchEndCapture: typingsSlinky.preact.jsxMod.JSXInternal.TouchEventHandler[Target] = null,
    onTouchMove: typingsSlinky.preact.jsxMod.JSXInternal.TouchEventHandler[Target] = null,
    onTouchMoveCapture: typingsSlinky.preact.jsxMod.JSXInternal.TouchEventHandler[Target] = null,
    onTouchStart: typingsSlinky.preact.jsxMod.JSXInternal.TouchEventHandler[Target] = null,
    onTouchStartCapture: typingsSlinky.preact.jsxMod.JSXInternal.TouchEventHandler[Target] = null,
    onTransitionEnd: typingsSlinky.preact.jsxMod.JSXInternal.TransitionEventHandler[Target] = null,
    onTransitionEndCapture: typingsSlinky.preact.jsxMod.JSXInternal.TransitionEventHandler[Target] = null,
    onVolumeChange: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onVolumeChangeCapture: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onWaiting: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onWaitingCapture: typingsSlinky.preact.jsxMod.JSXInternal.GenericEventHandler[Target] = null,
    onWheel: typingsSlinky.preact.jsxMod.JSXInternal.WheelEventHandler[Target] = null,
    onWheelCapture: typingsSlinky.preact.jsxMod.JSXInternal.WheelEventHandler[Target] = null
  ): DOMAttributes[Target] = {
    val __obj = js.Dynamic.literal()
    if (!js.isUndefined(children)) __obj.updateDynamic("children")(children.asInstanceOf[js.Any])
    if (dangerouslySetInnerHTML != null) __obj.updateDynamic("dangerouslySetInnerHTML")(dangerouslySetInnerHTML.asInstanceOf[js.Any])
    if (onAbort != null) __obj.updateDynamic("onAbort")(onAbort.asInstanceOf[js.Any])
    if (onAbortCapture != null) __obj.updateDynamic("onAbortCapture")(onAbortCapture.asInstanceOf[js.Any])
    if (onAnimationEnd != null) __obj.updateDynamic("onAnimationEnd")(onAnimationEnd.asInstanceOf[js.Any])
    if (onAnimationEndCapture != null) __obj.updateDynamic("onAnimationEndCapture")(onAnimationEndCapture.asInstanceOf[js.Any])
    if (onAnimationIteration != null) __obj.updateDynamic("onAnimationIteration")(onAnimationIteration.asInstanceOf[js.Any])
    if (onAnimationIterationCapture != null) __obj.updateDynamic("onAnimationIterationCapture")(onAnimationIterationCapture.asInstanceOf[js.Any])
    if (onAnimationStart != null) __obj.updateDynamic("onAnimationStart")(onAnimationStart.asInstanceOf[js.Any])
    if (onAnimationStartCapture != null) __obj.updateDynamic("onAnimationStartCapture")(onAnimationStartCapture.asInstanceOf[js.Any])
    if (onBlur != null) __obj.updateDynamic("onBlur")(onBlur.asInstanceOf[js.Any])
    if (onBlurCapture != null) __obj.updateDynamic("onBlurCapture")(onBlurCapture.asInstanceOf[js.Any])
    if (onCanPlay != null) __obj.updateDynamic("onCanPlay")(onCanPlay.asInstanceOf[js.Any])
    if (onCanPlayCapture != null) __obj.updateDynamic("onCanPlayCapture")(onCanPlayCapture.asInstanceOf[js.Any])
    if (onCanPlayThrough != null) __obj.updateDynamic("onCanPlayThrough")(onCanPlayThrough.asInstanceOf[js.Any])
    if (onCanPlayThroughCapture != null) __obj.updateDynamic("onCanPlayThroughCapture")(onCanPlayThroughCapture.asInstanceOf[js.Any])
    if (onChange != null) __obj.updateDynamic("onChange")(onChange.asInstanceOf[js.Any])
    if (onChangeCapture != null) __obj.updateDynamic("onChangeCapture")(onChangeCapture.asInstanceOf[js.Any])
    if (onClick != null) __obj.updateDynamic("onClick")(onClick.asInstanceOf[js.Any])
    if (onClickCapture != null) __obj.updateDynamic("onClickCapture")(onClickCapture.asInstanceOf[js.Any])
    if (onCompositionEnd != null) __obj.updateDynamic("onCompositionEnd")(onCompositionEnd.asInstanceOf[js.Any])
    if (onCompositionEndCapture != null) __obj.updateDynamic("onCompositionEndCapture")(onCompositionEndCapture.asInstanceOf[js.Any])
    if (onCompositionStart != null) __obj.updateDynamic("onCompositionStart")(onCompositionStart.asInstanceOf[js.Any])
    if (onCompositionStartCapture != null) __obj.updateDynamic("onCompositionStartCapture")(onCompositionStartCapture.asInstanceOf[js.Any])
    if (onCompositionUpdate != null) __obj.updateDynamic("onCompositionUpdate")(onCompositionUpdate.asInstanceOf[js.Any])
    if (onCompositionUpdateCapture != null) __obj.updateDynamic("onCompositionUpdateCapture")(onCompositionUpdateCapture.asInstanceOf[js.Any])
    if (onContextMenu != null) __obj.updateDynamic("onContextMenu")(onContextMenu.asInstanceOf[js.Any])
    if (onContextMenuCapture != null) __obj.updateDynamic("onContextMenuCapture")(onContextMenuCapture.asInstanceOf[js.Any])
    if (onCopy != null) __obj.updateDynamic("onCopy")(onCopy.asInstanceOf[js.Any])
    if (onCopyCapture != null) __obj.updateDynamic("onCopyCapture")(onCopyCapture.asInstanceOf[js.Any])
    if (onCut != null) __obj.updateDynamic("onCut")(onCut.asInstanceOf[js.Any])
    if (onCutCapture != null) __obj.updateDynamic("onCutCapture")(onCutCapture.asInstanceOf[js.Any])
    if (onDblClick != null) __obj.updateDynamic("onDblClick")(onDblClick.asInstanceOf[js.Any])
    if (onDblClickCapture != null) __obj.updateDynamic("onDblClickCapture")(onDblClickCapture.asInstanceOf[js.Any])
    if (onDrag != null) __obj.updateDynamic("onDrag")(onDrag.asInstanceOf[js.Any])
    if (onDragCapture != null) __obj.updateDynamic("onDragCapture")(onDragCapture.asInstanceOf[js.Any])
    if (onDragEnd != null) __obj.updateDynamic("onDragEnd")(onDragEnd.asInstanceOf[js.Any])
    if (onDragEndCapture != null) __obj.updateDynamic("onDragEndCapture")(onDragEndCapture.asInstanceOf[js.Any])
    if (onDragEnter != null) __obj.updateDynamic("onDragEnter")(onDragEnter.asInstanceOf[js.Any])
    if (onDragEnterCapture != null) __obj.updateDynamic("onDragEnterCapture")(onDragEnterCapture.asInstanceOf[js.Any])
    if (onDragExit != null) __obj.updateDynamic("onDragExit")(onDragExit.asInstanceOf[js.Any])
    if (onDragExitCapture != null) __obj.updateDynamic("onDragExitCapture")(onDragExitCapture.asInstanceOf[js.Any])
    if (onDragLeave != null) __obj.updateDynamic("onDragLeave")(onDragLeave.asInstanceOf[js.Any])
    if (onDragLeaveCapture != null) __obj.updateDynamic("onDragLeaveCapture")(onDragLeaveCapture.asInstanceOf[js.Any])
    if (onDragOver != null) __obj.updateDynamic("onDragOver")(onDragOver.asInstanceOf[js.Any])
    if (onDragOverCapture != null) __obj.updateDynamic("onDragOverCapture")(onDragOverCapture.asInstanceOf[js.Any])
    if (onDragStart != null) __obj.updateDynamic("onDragStart")(onDragStart.asInstanceOf[js.Any])
    if (onDragStartCapture != null) __obj.updateDynamic("onDragStartCapture")(onDragStartCapture.asInstanceOf[js.Any])
    if (onDrop != null) __obj.updateDynamic("onDrop")(onDrop.asInstanceOf[js.Any])
    if (onDropCapture != null) __obj.updateDynamic("onDropCapture")(onDropCapture.asInstanceOf[js.Any])
    if (onDurationChange != null) __obj.updateDynamic("onDurationChange")(onDurationChange.asInstanceOf[js.Any])
    if (onDurationChangeCapture != null) __obj.updateDynamic("onDurationChangeCapture")(onDurationChangeCapture.asInstanceOf[js.Any])
    if (onEmptied != null) __obj.updateDynamic("onEmptied")(onEmptied.asInstanceOf[js.Any])
    if (onEmptiedCapture != null) __obj.updateDynamic("onEmptiedCapture")(onEmptiedCapture.asInstanceOf[js.Any])
    if (onEncrypted != null) __obj.updateDynamic("onEncrypted")(onEncrypted.asInstanceOf[js.Any])
    if (onEncryptedCapture != null) __obj.updateDynamic("onEncryptedCapture")(onEncryptedCapture.asInstanceOf[js.Any])
    if (onEnded != null) __obj.updateDynamic("onEnded")(onEnded.asInstanceOf[js.Any])
    if (onEndedCapture != null) __obj.updateDynamic("onEndedCapture")(onEndedCapture.asInstanceOf[js.Any])
    if (onError != null) __obj.updateDynamic("onError")(onError.asInstanceOf[js.Any])
    if (onErrorCapture != null) __obj.updateDynamic("onErrorCapture")(onErrorCapture.asInstanceOf[js.Any])
    if (onFocus != null) __obj.updateDynamic("onFocus")(onFocus.asInstanceOf[js.Any])
    if (onFocusCapture != null) __obj.updateDynamic("onFocusCapture")(onFocusCapture.asInstanceOf[js.Any])
    if (onFormData != null) __obj.updateDynamic("onFormData")(onFormData.asInstanceOf[js.Any])
    if (onFormDataCapture != null) __obj.updateDynamic("onFormDataCapture")(onFormDataCapture.asInstanceOf[js.Any])
    if (onGotPointerCapture != null) __obj.updateDynamic("onGotPointerCapture")(onGotPointerCapture.asInstanceOf[js.Any])
    if (onGotPointerCaptureCapture != null) __obj.updateDynamic("onGotPointerCaptureCapture")(onGotPointerCaptureCapture.asInstanceOf[js.Any])
    if (onInput != null) __obj.updateDynamic("onInput")(onInput.asInstanceOf[js.Any])
    if (onInputCapture != null) __obj.updateDynamic("onInputCapture")(onInputCapture.asInstanceOf[js.Any])
    if (onInvalid != null) __obj.updateDynamic("onInvalid")(onInvalid.asInstanceOf[js.Any])
    if (onInvalidCapture != null) __obj.updateDynamic("onInvalidCapture")(onInvalidCapture.asInstanceOf[js.Any])
    if (onKeyDown != null) __obj.updateDynamic("onKeyDown")(onKeyDown.asInstanceOf[js.Any])
    if (onKeyDownCapture != null) __obj.updateDynamic("onKeyDownCapture")(onKeyDownCapture.asInstanceOf[js.Any])
    if (onKeyPress != null) __obj.updateDynamic("onKeyPress")(onKeyPress.asInstanceOf[js.Any])
    if (onKeyPressCapture != null) __obj.updateDynamic("onKeyPressCapture")(onKeyPressCapture.asInstanceOf[js.Any])
    if (onKeyUp != null) __obj.updateDynamic("onKeyUp")(onKeyUp.asInstanceOf[js.Any])
    if (onKeyUpCapture != null) __obj.updateDynamic("onKeyUpCapture")(onKeyUpCapture.asInstanceOf[js.Any])
    if (onLoad != null) __obj.updateDynamic("onLoad")(onLoad.asInstanceOf[js.Any])
    if (onLoadCapture != null) __obj.updateDynamic("onLoadCapture")(onLoadCapture.asInstanceOf[js.Any])
    if (onLoadStart != null) __obj.updateDynamic("onLoadStart")(onLoadStart.asInstanceOf[js.Any])
    if (onLoadStartCapture != null) __obj.updateDynamic("onLoadStartCapture")(onLoadStartCapture.asInstanceOf[js.Any])
    if (onLoadedData != null) __obj.updateDynamic("onLoadedData")(onLoadedData.asInstanceOf[js.Any])
    if (onLoadedDataCapture != null) __obj.updateDynamic("onLoadedDataCapture")(onLoadedDataCapture.asInstanceOf[js.Any])
    if (onLoadedMetadata != null) __obj.updateDynamic("onLoadedMetadata")(onLoadedMetadata.asInstanceOf[js.Any])
    if (onLoadedMetadataCapture != null) __obj.updateDynamic("onLoadedMetadataCapture")(onLoadedMetadataCapture.asInstanceOf[js.Any])
    if (onLostPointerCapture != null) __obj.updateDynamic("onLostPointerCapture")(onLostPointerCapture.asInstanceOf[js.Any])
    if (onLostPointerCaptureCapture != null) __obj.updateDynamic("onLostPointerCaptureCapture")(onLostPointerCaptureCapture.asInstanceOf[js.Any])
    if (onMouseDown != null) __obj.updateDynamic("onMouseDown")(onMouseDown.asInstanceOf[js.Any])
    if (onMouseDownCapture != null) __obj.updateDynamic("onMouseDownCapture")(onMouseDownCapture.asInstanceOf[js.Any])
    if (onMouseEnter != null) __obj.updateDynamic("onMouseEnter")(onMouseEnter.asInstanceOf[js.Any])
    if (onMouseEnterCapture != null) __obj.updateDynamic("onMouseEnterCapture")(onMouseEnterCapture.asInstanceOf[js.Any])
    if (onMouseLeave != null) __obj.updateDynamic("onMouseLeave")(onMouseLeave.asInstanceOf[js.Any])
    if (onMouseLeaveCapture != null) __obj.updateDynamic("onMouseLeaveCapture")(onMouseLeaveCapture.asInstanceOf[js.Any])
    if (onMouseMove != null) __obj.updateDynamic("onMouseMove")(onMouseMove.asInstanceOf[js.Any])
    if (onMouseMoveCapture != null) __obj.updateDynamic("onMouseMoveCapture")(onMouseMoveCapture.asInstanceOf[js.Any])
    if (onMouseOut != null) __obj.updateDynamic("onMouseOut")(onMouseOut.asInstanceOf[js.Any])
    if (onMouseOutCapture != null) __obj.updateDynamic("onMouseOutCapture")(onMouseOutCapture.asInstanceOf[js.Any])
    if (onMouseOver != null) __obj.updateDynamic("onMouseOver")(onMouseOver.asInstanceOf[js.Any])
    if (onMouseOverCapture != null) __obj.updateDynamic("onMouseOverCapture")(onMouseOverCapture.asInstanceOf[js.Any])
    if (onMouseUp != null) __obj.updateDynamic("onMouseUp")(onMouseUp.asInstanceOf[js.Any])
    if (onMouseUpCapture != null) __obj.updateDynamic("onMouseUpCapture")(onMouseUpCapture.asInstanceOf[js.Any])
    if (onPaste != null) __obj.updateDynamic("onPaste")(onPaste.asInstanceOf[js.Any])
    if (onPasteCapture != null) __obj.updateDynamic("onPasteCapture")(onPasteCapture.asInstanceOf[js.Any])
    if (onPause != null) __obj.updateDynamic("onPause")(onPause.asInstanceOf[js.Any])
    if (onPauseCapture != null) __obj.updateDynamic("onPauseCapture")(onPauseCapture.asInstanceOf[js.Any])
    if (onPlay != null) __obj.updateDynamic("onPlay")(onPlay.asInstanceOf[js.Any])
    if (onPlayCapture != null) __obj.updateDynamic("onPlayCapture")(onPlayCapture.asInstanceOf[js.Any])
    if (onPlaying != null) __obj.updateDynamic("onPlaying")(onPlaying.asInstanceOf[js.Any])
    if (onPlayingCapture != null) __obj.updateDynamic("onPlayingCapture")(onPlayingCapture.asInstanceOf[js.Any])
    if (onPointerCancel != null) __obj.updateDynamic("onPointerCancel")(onPointerCancel.asInstanceOf[js.Any])
    if (onPointerCancelCapture != null) __obj.updateDynamic("onPointerCancelCapture")(onPointerCancelCapture.asInstanceOf[js.Any])
    if (onPointerDown != null) __obj.updateDynamic("onPointerDown")(onPointerDown.asInstanceOf[js.Any])
    if (onPointerDownCapture != null) __obj.updateDynamic("onPointerDownCapture")(onPointerDownCapture.asInstanceOf[js.Any])
    if (onPointerEnter != null) __obj.updateDynamic("onPointerEnter")(onPointerEnter.asInstanceOf[js.Any])
    if (onPointerEnterCapture != null) __obj.updateDynamic("onPointerEnterCapture")(onPointerEnterCapture.asInstanceOf[js.Any])
    if (onPointerLeave != null) __obj.updateDynamic("onPointerLeave")(onPointerLeave.asInstanceOf[js.Any])
    if (onPointerLeaveCapture != null) __obj.updateDynamic("onPointerLeaveCapture")(onPointerLeaveCapture.asInstanceOf[js.Any])
    if (onPointerMove != null) __obj.updateDynamic("onPointerMove")(onPointerMove.asInstanceOf[js.Any])
    if (onPointerMoveCapture != null) __obj.updateDynamic("onPointerMoveCapture")(onPointerMoveCapture.asInstanceOf[js.Any])
    if (onPointerOut != null) __obj.updateDynamic("onPointerOut")(onPointerOut.asInstanceOf[js.Any])
    if (onPointerOutCapture != null) __obj.updateDynamic("onPointerOutCapture")(onPointerOutCapture.asInstanceOf[js.Any])
    if (onPointerOver != null) __obj.updateDynamic("onPointerOver")(onPointerOver.asInstanceOf[js.Any])
    if (onPointerOverCapture != null) __obj.updateDynamic("onPointerOverCapture")(onPointerOverCapture.asInstanceOf[js.Any])
    if (onPointerUp != null) __obj.updateDynamic("onPointerUp")(onPointerUp.asInstanceOf[js.Any])
    if (onPointerUpCapture != null) __obj.updateDynamic("onPointerUpCapture")(onPointerUpCapture.asInstanceOf[js.Any])
    if (onProgress != null) __obj.updateDynamic("onProgress")(onProgress.asInstanceOf[js.Any])
    if (onProgressCapture != null) __obj.updateDynamic("onProgressCapture")(onProgressCapture.asInstanceOf[js.Any])
    if (onRateChange != null) __obj.updateDynamic("onRateChange")(onRateChange.asInstanceOf[js.Any])
    if (onRateChangeCapture != null) __obj.updateDynamic("onRateChangeCapture")(onRateChangeCapture.asInstanceOf[js.Any])
    if (onReset != null) __obj.updateDynamic("onReset")(onReset.asInstanceOf[js.Any])
    if (onResetCapture != null) __obj.updateDynamic("onResetCapture")(onResetCapture.asInstanceOf[js.Any])
    if (onScroll != null) __obj.updateDynamic("onScroll")(onScroll.asInstanceOf[js.Any])
    if (onScrollCapture != null) __obj.updateDynamic("onScrollCapture")(onScrollCapture.asInstanceOf[js.Any])
    if (onSearch != null) __obj.updateDynamic("onSearch")(onSearch.asInstanceOf[js.Any])
    if (onSearchCapture != null) __obj.updateDynamic("onSearchCapture")(onSearchCapture.asInstanceOf[js.Any])
    if (onSeeked != null) __obj.updateDynamic("onSeeked")(onSeeked.asInstanceOf[js.Any])
    if (onSeekedCapture != null) __obj.updateDynamic("onSeekedCapture")(onSeekedCapture.asInstanceOf[js.Any])
    if (onSeeking != null) __obj.updateDynamic("onSeeking")(onSeeking.asInstanceOf[js.Any])
    if (onSeekingCapture != null) __obj.updateDynamic("onSeekingCapture")(onSeekingCapture.asInstanceOf[js.Any])
    if (onSelect != null) __obj.updateDynamic("onSelect")(onSelect.asInstanceOf[js.Any])
    if (onSelectCapture != null) __obj.updateDynamic("onSelectCapture")(onSelectCapture.asInstanceOf[js.Any])
    if (onStalled != null) __obj.updateDynamic("onStalled")(onStalled.asInstanceOf[js.Any])
    if (onStalledCapture != null) __obj.updateDynamic("onStalledCapture")(onStalledCapture.asInstanceOf[js.Any])
    if (onSubmit != null) __obj.updateDynamic("onSubmit")(onSubmit.asInstanceOf[js.Any])
    if (onSubmitCapture != null) __obj.updateDynamic("onSubmitCapture")(onSubmitCapture.asInstanceOf[js.Any])
    if (onSuspend != null) __obj.updateDynamic("onSuspend")(onSuspend.asInstanceOf[js.Any])
    if (onSuspendCapture != null) __obj.updateDynamic("onSuspendCapture")(onSuspendCapture.asInstanceOf[js.Any])
    if (onTimeUpdate != null) __obj.updateDynamic("onTimeUpdate")(onTimeUpdate.asInstanceOf[js.Any])
    if (onTimeUpdateCapture != null) __obj.updateDynamic("onTimeUpdateCapture")(onTimeUpdateCapture.asInstanceOf[js.Any])
    if (onToggle != null) __obj.updateDynamic("onToggle")(onToggle.asInstanceOf[js.Any])
    if (onTouchCancel != null) __obj.updateDynamic("onTouchCancel")(onTouchCancel.asInstanceOf[js.Any])
    if (onTouchCancelCapture != null) __obj.updateDynamic("onTouchCancelCapture")(onTouchCancelCapture.asInstanceOf[js.Any])
    if (onTouchEnd != null) __obj.updateDynamic("onTouchEnd")(onTouchEnd.asInstanceOf[js.Any])
    if (onTouchEndCapture != null) __obj.updateDynamic("onTouchEndCapture")(onTouchEndCapture.asInstanceOf[js.Any])
    if (onTouchMove != null) __obj.updateDynamic("onTouchMove")(onTouchMove.asInstanceOf[js.Any])
    if (onTouchMoveCapture != null) __obj.updateDynamic("onTouchMoveCapture")(onTouchMoveCapture.asInstanceOf[js.Any])
    if (onTouchStart != null) __obj.updateDynamic("onTouchStart")(onTouchStart.asInstanceOf[js.Any])
    if (onTouchStartCapture != null) __obj.updateDynamic("onTouchStartCapture")(onTouchStartCapture.asInstanceOf[js.Any])
    if (onTransitionEnd != null) __obj.updateDynamic("onTransitionEnd")(onTransitionEnd.asInstanceOf[js.Any])
    if (onTransitionEndCapture != null) __obj.updateDynamic("onTransitionEndCapture")(onTransitionEndCapture.asInstanceOf[js.Any])
    if (onVolumeChange != null) __obj.updateDynamic("onVolumeChange")(onVolumeChange.asInstanceOf[js.Any])
    if (onVolumeChangeCapture != null) __obj.updateDynamic("onVolumeChangeCapture")(onVolumeChangeCapture.asInstanceOf[js.Any])
    if (onWaiting != null) __obj.updateDynamic("onWaiting")(onWaiting.asInstanceOf[js.Any])
    if (onWaitingCapture != null) __obj.updateDynamic("onWaitingCapture")(onWaitingCapture.asInstanceOf[js.Any])
    if (onWheel != null) __obj.updateDynamic("onWheel")(onWheel.asInstanceOf[js.Any])
    if (onWheelCapture != null) __obj.updateDynamic("onWheelCapture")(onWheelCapture.asInstanceOf[js.Any])
    __obj.asInstanceOf[DOMAttributes[Target]]
  }
}

