package typingsSlinky.tensorflowTfjsLayers

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object layerSerializationMod {
  type LayerSerialization = typingsSlinky.tensorflowTfjsLayers.advancedActivationSerializationMod.AdvancedActivationLayerSerialization | typingsSlinky.tensorflowTfjsLayers.convolutionalDepthwiseSerializationMod.ConvolutionalDepthwiseLayerSerialization | typingsSlinky.tensorflowTfjsLayers.convolutionalSerializationMod.ConvolutionalLayerSerialization | typingsSlinky.tensorflowTfjsLayers.coreSerializationMod.CoreLayerSerialization | typingsSlinky.tensorflowTfjsLayers.embeddingsSerializationMod.EmbeddingLayerSerialization | typingsSlinky.tensorflowTfjsLayers.mergeSerializationMod.MergeLayerSerialization | typingsSlinky.tensorflowTfjsLayers.normalizationSerializationMod.NormalizationLayerSerialization | typingsSlinky.tensorflowTfjsLayers.paddingSerializationMod.PaddingLayerSerialization | typingsSlinky.tensorflowTfjsLayers.poolingSerializationMod.PoolingLayerSerialization | typingsSlinky.tensorflowTfjsLayers.recurrentSerializationMod.RecurrentLayerSerialization | typingsSlinky.tensorflowTfjsLayers.inputConfigMod.InputLayerSerialization
}
