package typingsSlinky.recurlyRecurlyJs

import org.scalajs.dom.raw.HTMLFormElement
import typingsSlinky.recurlyRecurlyJs.checkoutMod.CheckoutPricingInstance
import typingsSlinky.recurlyRecurlyJs.emitterMod.Emitter
import typingsSlinky.std.VoidFunction
import org.scalablytyped.runtime.StObject
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

object applePayMod {
  
  type ApplePay = js.Function1[/* config */ ApplePayConfig, ApplePayInstance]
  
  @js.native
  trait ApplePayConfig extends StObject {
    
    /**
      * Your ISO 3166 country code (ex: ‘US’). This is your country code as the merchant.
      */
    var country: String = js.native
    
    /**
      * ISO 4217 purchase currency (ex: ‘USD’)
      */
    var currency: String = js.native
    
    /**
      * If provided, tokens generated by the `recurly.ApplePay` instance will include customer billing address from the
      * form, overriding any billing address gathered from Apple Pay.
      *
      * See {@link https://developers.recurly.com/reference/recurly-js/index.html#getting-a-token|Getting a Token} for all
      * compatible fields.
      */
    var form: js.UndefOr[HTMLFormElement] = js.native
    
    /**
      * Purchase description to display in the Apple Pay payment sheet.
      */
    var label: String = js.native
    
    /**
      * If provided, will override `options.total` and provide the current total price on the CheckoutPricing instance
      * when the Apple Pay flow is initiated.
      */
    var pricing: js.UndefOr[CheckoutPricingInstance] = js.native
    
    /**
      * Total cost to display in the Apple Pay payment sheet. Required if `options.pricing` is not provided.
      */
    var total: String = js.native
  }
  object ApplePayConfig {
    
    @scala.inline
    def apply(country: String, currency: String, label: String, total: String): ApplePayConfig = {
      val __obj = js.Dynamic.literal(country = country.asInstanceOf[js.Any], currency = currency.asInstanceOf[js.Any], label = label.asInstanceOf[js.Any], total = total.asInstanceOf[js.Any])
      __obj.asInstanceOf[ApplePayConfig]
    }
    
    @scala.inline
    implicit class ApplePayConfigMutableBuilder[Self <: ApplePayConfig] (val x: Self) extends AnyVal {
      
      @scala.inline
      def setCountry(value: String): Self = StObject.set(x, "country", value.asInstanceOf[js.Any])
      
      @scala.inline
      def setCurrency(value: String): Self = StObject.set(x, "currency", value.asInstanceOf[js.Any])
      
      @scala.inline
      def setForm(value: HTMLFormElement): Self = StObject.set(x, "form", value.asInstanceOf[js.Any])
      
      @scala.inline
      def setFormUndefined: Self = StObject.set(x, "form", js.undefined)
      
      @scala.inline
      def setLabel(value: String): Self = StObject.set(x, "label", value.asInstanceOf[js.Any])
      
      @scala.inline
      def setPricing(value: CheckoutPricingInstance): Self = StObject.set(x, "pricing", value.asInstanceOf[js.Any])
      
      @scala.inline
      def setPricingUndefined: Self = StObject.set(x, "pricing", js.undefined)
      
      @scala.inline
      def setTotal(value: String): Self = StObject.set(x, "total", value.asInstanceOf[js.Any])
    }
  }
  
  /* Rewritten from type alias, can be one of: 
    - typingsSlinky.recurlyRecurlyJs.recurlyRecurlyJsStrings.token
    - typingsSlinky.recurlyRecurlyJs.recurlyRecurlyJsStrings.error
    - typingsSlinky.recurlyRecurlyJs.recurlyRecurlyJsStrings.ready
    - typingsSlinky.recurlyRecurlyJs.recurlyRecurlyJsStrings.shippingContactSelected
    - typingsSlinky.recurlyRecurlyJs.recurlyRecurlyJsStrings.paymentAuthorized
    - typingsSlinky.recurlyRecurlyJs.recurlyRecurlyJsStrings.shippingMethodSelected
    - typingsSlinky.recurlyRecurlyJs.recurlyRecurlyJsStrings.cancel
  */
  trait ApplePayEvent extends StObject
  object ApplePayEvent {
    
    @scala.inline
    def cancel: typingsSlinky.recurlyRecurlyJs.recurlyRecurlyJsStrings.cancel = "cancel".asInstanceOf[typingsSlinky.recurlyRecurlyJs.recurlyRecurlyJsStrings.cancel]
    
    @scala.inline
    def error: typingsSlinky.recurlyRecurlyJs.recurlyRecurlyJsStrings.error = "error".asInstanceOf[typingsSlinky.recurlyRecurlyJs.recurlyRecurlyJsStrings.error]
    
    @scala.inline
    def paymentAuthorized: typingsSlinky.recurlyRecurlyJs.recurlyRecurlyJsStrings.paymentAuthorized = "paymentAuthorized".asInstanceOf[typingsSlinky.recurlyRecurlyJs.recurlyRecurlyJsStrings.paymentAuthorized]
    
    @scala.inline
    def ready: typingsSlinky.recurlyRecurlyJs.recurlyRecurlyJsStrings.ready = "ready".asInstanceOf[typingsSlinky.recurlyRecurlyJs.recurlyRecurlyJsStrings.ready]
    
    @scala.inline
    def shippingContactSelected: typingsSlinky.recurlyRecurlyJs.recurlyRecurlyJsStrings.shippingContactSelected = "shippingContactSelected".asInstanceOf[typingsSlinky.recurlyRecurlyJs.recurlyRecurlyJsStrings.shippingContactSelected]
    
    @scala.inline
    def shippingMethodSelected: typingsSlinky.recurlyRecurlyJs.recurlyRecurlyJsStrings.shippingMethodSelected = "shippingMethodSelected".asInstanceOf[typingsSlinky.recurlyRecurlyJs.recurlyRecurlyJsStrings.shippingMethodSelected]
    
    @scala.inline
    def token: typingsSlinky.recurlyRecurlyJs.recurlyRecurlyJsStrings.token = "token".asInstanceOf[typingsSlinky.recurlyRecurlyJs.recurlyRecurlyJsStrings.token]
  }
  
  @js.native
  trait ApplePayInstance extends Emitter[ApplePayEvent] {
    
    def begin(): Unit = js.native
    def begin(cb: VoidFunction): Unit = js.native
    
    /**
      * @see {@link https://developers.recurly.com/reference/recurly-js/index.html#fn-applepayready|ApplePay.ready}
      */
    def ready(): Unit = js.native
    def ready(cb: VoidFunction): Unit = js.native
  }
}
