package typingsSlinky.awsSdkClientCodecommitNode.testRepositoryTriggersExceptionsUnionMod

import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionIntegrityChecksFailedExceptionMod.EncryptionIntegrityChecksFailedException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyAccessDeniedExceptionMod.EncryptionKeyAccessDeniedException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyDisabledExceptionMod.EncryptionKeyDisabledException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyNotFoundExceptionMod.EncryptionKeyNotFoundException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyUnavailableExceptionMod.EncryptionKeyUnavailableException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryNameExceptionMod.InvalidRepositoryNameException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryTriggerBranchNameExceptionMod.InvalidRepositoryTriggerBranchNameException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryTriggerCustomDataExceptionMod.InvalidRepositoryTriggerCustomDataException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryTriggerDestinationArnExceptionMod.InvalidRepositoryTriggerDestinationArnException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryTriggerEventsExceptionMod.InvalidRepositoryTriggerEventsException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryTriggerNameExceptionMod.InvalidRepositoryTriggerNameException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryTriggerRegionExceptionMod.InvalidRepositoryTriggerRegionException
import typingsSlinky.awsSdkClientCodecommitNode.typesMaximumBranchesExceededExceptionMod.MaximumBranchesExceededException
import typingsSlinky.awsSdkClientCodecommitNode.typesMaximumRepositoryTriggersExceededExceptionMod.MaximumRepositoryTriggersExceededException
import typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryDoesNotExistExceptionMod.RepositoryDoesNotExistException
import typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryNameRequiredExceptionMod.RepositoryNameRequiredException
import typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryTriggerBranchNameListRequiredExceptionMod.RepositoryTriggerBranchNameListRequiredException
import typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryTriggerDestinationArnRequiredExceptionMod.RepositoryTriggerDestinationArnRequiredException
import typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryTriggerEventsListRequiredExceptionMod.RepositoryTriggerEventsListRequiredException
import typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryTriggerNameRequiredExceptionMod.RepositoryTriggerNameRequiredException
import typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryTriggersListRequiredExceptionMod.RepositoryTriggersListRequiredException
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryDoesNotExistExceptionMod.RepositoryDoesNotExistException
  - typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryNameRequiredExceptionMod.RepositoryNameRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryNameExceptionMod.InvalidRepositoryNameException
  - typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryTriggersListRequiredExceptionMod.RepositoryTriggersListRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesMaximumRepositoryTriggersExceededExceptionMod.MaximumRepositoryTriggersExceededException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryTriggerNameExceptionMod.InvalidRepositoryTriggerNameException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryTriggerDestinationArnExceptionMod.InvalidRepositoryTriggerDestinationArnException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryTriggerRegionExceptionMod.InvalidRepositoryTriggerRegionException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryTriggerCustomDataExceptionMod.InvalidRepositoryTriggerCustomDataException
  - typingsSlinky.awsSdkClientCodecommitNode.typesMaximumBranchesExceededExceptionMod.MaximumBranchesExceededException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryTriggerBranchNameExceptionMod.InvalidRepositoryTriggerBranchNameException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryTriggerEventsExceptionMod.InvalidRepositoryTriggerEventsException
  - typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryTriggerNameRequiredExceptionMod.RepositoryTriggerNameRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryTriggerDestinationArnRequiredExceptionMod.RepositoryTriggerDestinationArnRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryTriggerBranchNameListRequiredExceptionMod.RepositoryTriggerBranchNameListRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryTriggerEventsListRequiredExceptionMod.RepositoryTriggerEventsListRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionIntegrityChecksFailedExceptionMod.EncryptionIntegrityChecksFailedException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyAccessDeniedExceptionMod.EncryptionKeyAccessDeniedException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyDisabledExceptionMod.EncryptionKeyDisabledException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyNotFoundExceptionMod.EncryptionKeyNotFoundException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyUnavailableExceptionMod.EncryptionKeyUnavailableException
*/
trait TestRepositoryTriggersExceptionsUnion extends js.Object

object TestRepositoryTriggersExceptionsUnion {
  @scala.inline
  implicit def apply(value: EncryptionIntegrityChecksFailedException): TestRepositoryTriggersExceptionsUnion = value.asInstanceOf[TestRepositoryTriggersExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyAccessDeniedException): TestRepositoryTriggersExceptionsUnion = value.asInstanceOf[TestRepositoryTriggersExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyDisabledException): TestRepositoryTriggersExceptionsUnion = value.asInstanceOf[TestRepositoryTriggersExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyNotFoundException): TestRepositoryTriggersExceptionsUnion = value.asInstanceOf[TestRepositoryTriggersExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyUnavailableException): TestRepositoryTriggersExceptionsUnion = value.asInstanceOf[TestRepositoryTriggersExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidRepositoryNameException): TestRepositoryTriggersExceptionsUnion = value.asInstanceOf[TestRepositoryTriggersExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidRepositoryTriggerBranchNameException): TestRepositoryTriggersExceptionsUnion = value.asInstanceOf[TestRepositoryTriggersExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidRepositoryTriggerCustomDataException): TestRepositoryTriggersExceptionsUnion = value.asInstanceOf[TestRepositoryTriggersExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidRepositoryTriggerDestinationArnException): TestRepositoryTriggersExceptionsUnion = value.asInstanceOf[TestRepositoryTriggersExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidRepositoryTriggerEventsException): TestRepositoryTriggersExceptionsUnion = value.asInstanceOf[TestRepositoryTriggersExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidRepositoryTriggerNameException): TestRepositoryTriggersExceptionsUnion = value.asInstanceOf[TestRepositoryTriggersExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidRepositoryTriggerRegionException): TestRepositoryTriggersExceptionsUnion = value.asInstanceOf[TestRepositoryTriggersExceptionsUnion]
  @scala.inline
  implicit def apply(value: MaximumBranchesExceededException): TestRepositoryTriggersExceptionsUnion = value.asInstanceOf[TestRepositoryTriggersExceptionsUnion]
  @scala.inline
  implicit def apply(value: MaximumRepositoryTriggersExceededException): TestRepositoryTriggersExceptionsUnion = value.asInstanceOf[TestRepositoryTriggersExceptionsUnion]
  @scala.inline
  implicit def apply(value: RepositoryDoesNotExistException): TestRepositoryTriggersExceptionsUnion = value.asInstanceOf[TestRepositoryTriggersExceptionsUnion]
  @scala.inline
  implicit def apply(value: RepositoryNameRequiredException): TestRepositoryTriggersExceptionsUnion = value.asInstanceOf[TestRepositoryTriggersExceptionsUnion]
  @scala.inline
  implicit def apply(value: RepositoryTriggerBranchNameListRequiredException): TestRepositoryTriggersExceptionsUnion = value.asInstanceOf[TestRepositoryTriggersExceptionsUnion]
  @scala.inline
  implicit def apply(value: RepositoryTriggerDestinationArnRequiredException): TestRepositoryTriggersExceptionsUnion = value.asInstanceOf[TestRepositoryTriggersExceptionsUnion]
  @scala.inline
  implicit def apply(value: RepositoryTriggerEventsListRequiredException): TestRepositoryTriggersExceptionsUnion = value.asInstanceOf[TestRepositoryTriggersExceptionsUnion]
  @scala.inline
  implicit def apply(value: RepositoryTriggerNameRequiredException): TestRepositoryTriggersExceptionsUnion = value.asInstanceOf[TestRepositoryTriggersExceptionsUnion]
  @scala.inline
  implicit def apply(value: RepositoryTriggersListRequiredException): TestRepositoryTriggersExceptionsUnion = value.asInstanceOf[TestRepositoryTriggersExceptionsUnion]
}

