package typingsSlinky.msDashRestDashAzure

import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureBooleans.`true`
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.AzureUSGovernment
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.DotcoreDotusgovcloudapiDotnet
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.DotdatabaseDotusgovcloudapiDotnet
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.DotvaultDotusgovcloudapiDotnet
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.NSlashA
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.`2013-04-05`
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.httpsColonSlashSlashbatchDotcoreDotusgovcloudapiDotnetSlash
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.httpsColonSlashSlashgalleryDotusgovcloudapiDotnetSlash
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.httpsColonSlashSlashgraphDotwindowsDotnetSlash
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.httpsColonSlashSlashloginDotmicrosoftonlineDotusSlash
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.httpsColonSlashSlashmanageDotwindowsazureDotusSlashpublishsettingsSlashindex
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.httpsColonSlashSlashmanagementDotcoreDotusgovcloudapiDotnet
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.httpsColonSlashSlashmanagementDotcoreDotusgovcloudapiDotnetColon8443Slash
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.httpsColonSlashSlashmanagementDotcoreDotusgovcloudapiDotnetSlash
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.httpsColonSlashSlashmanagementDotusgovcloudapiDotnet
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.httpsColonSlashSlashportalDotazureDotus
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait Anon_20130405ActiveDirectoryEndpointUrlActiveDirectoryGraphApiVersion extends js.Object {
  var activeDirectoryEndpointUrl: httpsColonSlashSlashloginDotmicrosoftonlineDotusSlash
  var activeDirectoryGraphApiVersion: `2013-04-05`
  var activeDirectoryGraphResourceId: httpsColonSlashSlashgraphDotwindowsDotnetSlash
  var activeDirectoryResourceId: httpsColonSlashSlashmanagementDotcoreDotusgovcloudapiDotnetSlash
  var azureDataLakeAnalyticsCatalogAndJobEndpointSuffix: NSlashA
  var azureDataLakeStoreFileSystemEndpointSuffix: NSlashA
  var batchResourceId: httpsColonSlashSlashbatchDotcoreDotusgovcloudapiDotnetSlash
  var galleryEndpointUrl: httpsColonSlashSlashgalleryDotusgovcloudapiDotnetSlash
  var keyVaultDnsSuffix: DotvaultDotusgovcloudapiDotnet
  var managementEndpointUrl: httpsColonSlashSlashmanagementDotcoreDotusgovcloudapiDotnet
  var name: AzureUSGovernment
  var portalUrl: httpsColonSlashSlashportalDotazureDotus
  var publishingProfileUrl: httpsColonSlashSlashmanageDotwindowsazureDotusSlashpublishsettingsSlashindex
  var resourceManagerEndpointUrl: httpsColonSlashSlashmanagementDotusgovcloudapiDotnet
  var sqlManagementEndpointUrl: httpsColonSlashSlashmanagementDotcoreDotusgovcloudapiDotnetColon8443Slash
  var sqlServerHostnameSuffix: DotdatabaseDotusgovcloudapiDotnet
  var storageEndpointSuffix: DotcoreDotusgovcloudapiDotnet
  var validateAuthority: `true`
}

object Anon_20130405ActiveDirectoryEndpointUrlActiveDirectoryGraphApiVersion {
  @scala.inline
  def apply(
    activeDirectoryEndpointUrl: httpsColonSlashSlashloginDotmicrosoftonlineDotusSlash,
    activeDirectoryGraphApiVersion: `2013-04-05`,
    activeDirectoryGraphResourceId: httpsColonSlashSlashgraphDotwindowsDotnetSlash,
    activeDirectoryResourceId: httpsColonSlashSlashmanagementDotcoreDotusgovcloudapiDotnetSlash,
    azureDataLakeAnalyticsCatalogAndJobEndpointSuffix: NSlashA,
    azureDataLakeStoreFileSystemEndpointSuffix: NSlashA,
    batchResourceId: httpsColonSlashSlashbatchDotcoreDotusgovcloudapiDotnetSlash,
    galleryEndpointUrl: httpsColonSlashSlashgalleryDotusgovcloudapiDotnetSlash,
    keyVaultDnsSuffix: DotvaultDotusgovcloudapiDotnet,
    managementEndpointUrl: httpsColonSlashSlashmanagementDotcoreDotusgovcloudapiDotnet,
    name: AzureUSGovernment,
    portalUrl: httpsColonSlashSlashportalDotazureDotus,
    publishingProfileUrl: httpsColonSlashSlashmanageDotwindowsazureDotusSlashpublishsettingsSlashindex,
    resourceManagerEndpointUrl: httpsColonSlashSlashmanagementDotusgovcloudapiDotnet,
    sqlManagementEndpointUrl: httpsColonSlashSlashmanagementDotcoreDotusgovcloudapiDotnetColon8443Slash,
    sqlServerHostnameSuffix: DotdatabaseDotusgovcloudapiDotnet,
    storageEndpointSuffix: DotcoreDotusgovcloudapiDotnet,
    validateAuthority: `true`
  ): Anon_20130405ActiveDirectoryEndpointUrlActiveDirectoryGraphApiVersion = {
    val __obj = js.Dynamic.literal(activeDirectoryEndpointUrl = activeDirectoryEndpointUrl.asInstanceOf[js.Any], activeDirectoryGraphApiVersion = activeDirectoryGraphApiVersion.asInstanceOf[js.Any], activeDirectoryGraphResourceId = activeDirectoryGraphResourceId.asInstanceOf[js.Any], activeDirectoryResourceId = activeDirectoryResourceId.asInstanceOf[js.Any], azureDataLakeAnalyticsCatalogAndJobEndpointSuffix = azureDataLakeAnalyticsCatalogAndJobEndpointSuffix.asInstanceOf[js.Any], azureDataLakeStoreFileSystemEndpointSuffix = azureDataLakeStoreFileSystemEndpointSuffix.asInstanceOf[js.Any], batchResourceId = batchResourceId.asInstanceOf[js.Any], galleryEndpointUrl = galleryEndpointUrl.asInstanceOf[js.Any], keyVaultDnsSuffix = keyVaultDnsSuffix.asInstanceOf[js.Any], managementEndpointUrl = managementEndpointUrl.asInstanceOf[js.Any], name = name.asInstanceOf[js.Any], portalUrl = portalUrl.asInstanceOf[js.Any], publishingProfileUrl = publishingProfileUrl.asInstanceOf[js.Any], resourceManagerEndpointUrl = resourceManagerEndpointUrl.asInstanceOf[js.Any], sqlManagementEndpointUrl = sqlManagementEndpointUrl.asInstanceOf[js.Any], sqlServerHostnameSuffix = sqlServerHostnameSuffix.asInstanceOf[js.Any], storageEndpointSuffix = storageEndpointSuffix.asInstanceOf[js.Any], validateAuthority = validateAuthority.asInstanceOf[js.Any])
  
    __obj.asInstanceOf[Anon_20130405ActiveDirectoryEndpointUrlActiveDirectoryGraphApiVersion]
  }
}

