package typingsSlinky.msDashRestDashAzure

import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureBooleans.`true`
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.Azure
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.DotcoreDotwindowsDotnet
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.DotdatabaseDotwindowsDotnet
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.DotvaultDotazureDotnet
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.`2013-04-05`
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.azuredatalakeanalyticsDotnet
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.azuredatalakestoreDotnet
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.httpsColonSlashSlashbatchDotcoreDotwindowsDotnetSlash
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.httpsColonSlashSlashgalleryDotazureDotcomSlash
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.httpsColonSlashSlashgoDotmicrosoftDotcomSlashfwlinkSlashQuestionmarkLinkIdEqualssign254432
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.httpsColonSlashSlashgraphDotwindowsDotnetSlash
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.httpsColonSlashSlashloginDotmicrosoftonlineDotcomSlash
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.httpsColonSlashSlashmanagementDotazureDotcomSlash
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.httpsColonSlashSlashmanagementDotcoreDotwindowsDotnet
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.httpsColonSlashSlashmanagementDotcoreDotwindowsDotnetColon8443Slash
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.httpsColonSlashSlashmanagementDotcoreDotwindowsDotnetSlash
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.httpsColonSlashSlashportalDotazureDotcom
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait Anon_20130405 extends js.Object {
  var activeDirectoryEndpointUrl: httpsColonSlashSlashloginDotmicrosoftonlineDotcomSlash
  var activeDirectoryGraphApiVersion: `2013-04-05`
  var activeDirectoryGraphResourceId: httpsColonSlashSlashgraphDotwindowsDotnetSlash
  var activeDirectoryResourceId: httpsColonSlashSlashmanagementDotcoreDotwindowsDotnetSlash
  var azureDataLakeAnalyticsCatalogAndJobEndpointSuffix: azuredatalakeanalyticsDotnet
  var azureDataLakeStoreFileSystemEndpointSuffix: azuredatalakestoreDotnet
  var batchResourceId: httpsColonSlashSlashbatchDotcoreDotwindowsDotnetSlash
  var galleryEndpointUrl: httpsColonSlashSlashgalleryDotazureDotcomSlash
  var keyVaultDnsSuffix: DotvaultDotazureDotnet
  var managementEndpointUrl: httpsColonSlashSlashmanagementDotcoreDotwindowsDotnet
  var name: Azure
  var portalUrl: httpsColonSlashSlashportalDotazureDotcom
  var publishingProfileUrl: httpsColonSlashSlashgoDotmicrosoftDotcomSlashfwlinkSlashQuestionmarkLinkIdEqualssign254432
  var resourceManagerEndpointUrl: httpsColonSlashSlashmanagementDotazureDotcomSlash
  var sqlManagementEndpointUrl: httpsColonSlashSlashmanagementDotcoreDotwindowsDotnetColon8443Slash
  var sqlServerHostnameSuffix: DotdatabaseDotwindowsDotnet
  var storageEndpointSuffix: DotcoreDotwindowsDotnet
  var validateAuthority: `true`
}

object Anon_20130405 {
  @scala.inline
  def apply(
    activeDirectoryEndpointUrl: httpsColonSlashSlashloginDotmicrosoftonlineDotcomSlash,
    activeDirectoryGraphApiVersion: `2013-04-05`,
    activeDirectoryGraphResourceId: httpsColonSlashSlashgraphDotwindowsDotnetSlash,
    activeDirectoryResourceId: httpsColonSlashSlashmanagementDotcoreDotwindowsDotnetSlash,
    azureDataLakeAnalyticsCatalogAndJobEndpointSuffix: azuredatalakeanalyticsDotnet,
    azureDataLakeStoreFileSystemEndpointSuffix: azuredatalakestoreDotnet,
    batchResourceId: httpsColonSlashSlashbatchDotcoreDotwindowsDotnetSlash,
    galleryEndpointUrl: httpsColonSlashSlashgalleryDotazureDotcomSlash,
    keyVaultDnsSuffix: DotvaultDotazureDotnet,
    managementEndpointUrl: httpsColonSlashSlashmanagementDotcoreDotwindowsDotnet,
    name: Azure,
    portalUrl: httpsColonSlashSlashportalDotazureDotcom,
    publishingProfileUrl: httpsColonSlashSlashgoDotmicrosoftDotcomSlashfwlinkSlashQuestionmarkLinkIdEqualssign254432,
    resourceManagerEndpointUrl: httpsColonSlashSlashmanagementDotazureDotcomSlash,
    sqlManagementEndpointUrl: httpsColonSlashSlashmanagementDotcoreDotwindowsDotnetColon8443Slash,
    sqlServerHostnameSuffix: DotdatabaseDotwindowsDotnet,
    storageEndpointSuffix: DotcoreDotwindowsDotnet,
    validateAuthority: `true`
  ): Anon_20130405 = {
    val __obj = js.Dynamic.literal(activeDirectoryEndpointUrl = activeDirectoryEndpointUrl.asInstanceOf[js.Any], activeDirectoryGraphApiVersion = activeDirectoryGraphApiVersion.asInstanceOf[js.Any], activeDirectoryGraphResourceId = activeDirectoryGraphResourceId.asInstanceOf[js.Any], activeDirectoryResourceId = activeDirectoryResourceId.asInstanceOf[js.Any], azureDataLakeAnalyticsCatalogAndJobEndpointSuffix = azureDataLakeAnalyticsCatalogAndJobEndpointSuffix.asInstanceOf[js.Any], azureDataLakeStoreFileSystemEndpointSuffix = azureDataLakeStoreFileSystemEndpointSuffix.asInstanceOf[js.Any], batchResourceId = batchResourceId.asInstanceOf[js.Any], galleryEndpointUrl = galleryEndpointUrl.asInstanceOf[js.Any], keyVaultDnsSuffix = keyVaultDnsSuffix.asInstanceOf[js.Any], managementEndpointUrl = managementEndpointUrl.asInstanceOf[js.Any], name = name.asInstanceOf[js.Any], portalUrl = portalUrl.asInstanceOf[js.Any], publishingProfileUrl = publishingProfileUrl.asInstanceOf[js.Any], resourceManagerEndpointUrl = resourceManagerEndpointUrl.asInstanceOf[js.Any], sqlManagementEndpointUrl = sqlManagementEndpointUrl.asInstanceOf[js.Any], sqlServerHostnameSuffix = sqlServerHostnameSuffix.asInstanceOf[js.Any], storageEndpointSuffix = storageEndpointSuffix.asInstanceOf[js.Any], validateAuthority = validateAuthority.asInstanceOf[js.Any])
  
    __obj.asInstanceOf[Anon_20130405]
  }
}

