package typingsSlinky.msDashRestDashAzure

import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureBooleans.`true`
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.AzureGermanCloud
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.DotcoreDotcloudapiDotde
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.DotdatabaseDotcloudapiDotde
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.DotvaultDotmicrosoftazureDotde
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.NSlashA
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.`2013-04-05`
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.httpsColonSlashSlashbatchDotmicrosoftazureDotdeSlash
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.httpsColonSlashSlashgalleryDotcloudapiDotdeSlash
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.httpsColonSlashSlashgraphDotcloudapiDotdeSlash
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.httpsColonSlashSlashloginDotmicrosoftonlineDotdeSlash
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.httpsColonSlashSlashmanageDotmicrosoftazureDotdeSlashpublishsettingsSlashindex
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.httpsColonSlashSlashmanagementDotcoreDotcloudapiDotde
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.httpsColonSlashSlashmanagementDotcoreDotcloudapiDotdeColon8443Slash
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.httpsColonSlashSlashmanagementDotcoreDotcloudapiDotdeSlash
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.httpsColonSlashSlashmanagementDotmicrosoftazureDotde
import typingsSlinky.msDashRestDashAzure.msDashRestDashAzureStrings.httpsColonSlashSlashportalDotmicrosoftazureDotdeSlash
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait Anon_20130405ActiveDirectoryEndpointUrlActiveDirectoryGraphApiVersionActiveDirectoryGraphResourceId extends js.Object {
  var activeDirectoryEndpointUrl: httpsColonSlashSlashloginDotmicrosoftonlineDotdeSlash
  var activeDirectoryGraphApiVersion: `2013-04-05`
  var activeDirectoryGraphResourceId: httpsColonSlashSlashgraphDotcloudapiDotdeSlash
  var activeDirectoryResourceId: httpsColonSlashSlashmanagementDotcoreDotcloudapiDotdeSlash
  var azureDataLakeAnalyticsCatalogAndJobEndpointSuffix: NSlashA
  var azureDataLakeStoreFileSystemEndpointSuffix: NSlashA
  var batchResourceId: httpsColonSlashSlashbatchDotmicrosoftazureDotdeSlash
  var galleryEndpointUrl: httpsColonSlashSlashgalleryDotcloudapiDotdeSlash
  var keyVaultDnsSuffix: DotvaultDotmicrosoftazureDotde
  var managementEndpointUrl: httpsColonSlashSlashmanagementDotcoreDotcloudapiDotde
  var name: AzureGermanCloud
  var portalUrl: httpsColonSlashSlashportalDotmicrosoftazureDotdeSlash
  var publishingProfileUrl: httpsColonSlashSlashmanageDotmicrosoftazureDotdeSlashpublishsettingsSlashindex
  var resourceManagerEndpointUrl: httpsColonSlashSlashmanagementDotmicrosoftazureDotde
  var sqlManagementEndpointUrl: httpsColonSlashSlashmanagementDotcoreDotcloudapiDotdeColon8443Slash
  var sqlServerHostnameSuffix: DotdatabaseDotcloudapiDotde
  var storageEndpointSuffix: DotcoreDotcloudapiDotde
  var validateAuthority: `true`
}

object Anon_20130405ActiveDirectoryEndpointUrlActiveDirectoryGraphApiVersionActiveDirectoryGraphResourceId {
  @scala.inline
  def apply(
    activeDirectoryEndpointUrl: httpsColonSlashSlashloginDotmicrosoftonlineDotdeSlash,
    activeDirectoryGraphApiVersion: `2013-04-05`,
    activeDirectoryGraphResourceId: httpsColonSlashSlashgraphDotcloudapiDotdeSlash,
    activeDirectoryResourceId: httpsColonSlashSlashmanagementDotcoreDotcloudapiDotdeSlash,
    azureDataLakeAnalyticsCatalogAndJobEndpointSuffix: NSlashA,
    azureDataLakeStoreFileSystemEndpointSuffix: NSlashA,
    batchResourceId: httpsColonSlashSlashbatchDotmicrosoftazureDotdeSlash,
    galleryEndpointUrl: httpsColonSlashSlashgalleryDotcloudapiDotdeSlash,
    keyVaultDnsSuffix: DotvaultDotmicrosoftazureDotde,
    managementEndpointUrl: httpsColonSlashSlashmanagementDotcoreDotcloudapiDotde,
    name: AzureGermanCloud,
    portalUrl: httpsColonSlashSlashportalDotmicrosoftazureDotdeSlash,
    publishingProfileUrl: httpsColonSlashSlashmanageDotmicrosoftazureDotdeSlashpublishsettingsSlashindex,
    resourceManagerEndpointUrl: httpsColonSlashSlashmanagementDotmicrosoftazureDotde,
    sqlManagementEndpointUrl: httpsColonSlashSlashmanagementDotcoreDotcloudapiDotdeColon8443Slash,
    sqlServerHostnameSuffix: DotdatabaseDotcloudapiDotde,
    storageEndpointSuffix: DotcoreDotcloudapiDotde,
    validateAuthority: `true`
  ): Anon_20130405ActiveDirectoryEndpointUrlActiveDirectoryGraphApiVersionActiveDirectoryGraphResourceId = {
    val __obj = js.Dynamic.literal(activeDirectoryEndpointUrl = activeDirectoryEndpointUrl.asInstanceOf[js.Any], activeDirectoryGraphApiVersion = activeDirectoryGraphApiVersion.asInstanceOf[js.Any], activeDirectoryGraphResourceId = activeDirectoryGraphResourceId.asInstanceOf[js.Any], activeDirectoryResourceId = activeDirectoryResourceId.asInstanceOf[js.Any], azureDataLakeAnalyticsCatalogAndJobEndpointSuffix = azureDataLakeAnalyticsCatalogAndJobEndpointSuffix.asInstanceOf[js.Any], azureDataLakeStoreFileSystemEndpointSuffix = azureDataLakeStoreFileSystemEndpointSuffix.asInstanceOf[js.Any], batchResourceId = batchResourceId.asInstanceOf[js.Any], galleryEndpointUrl = galleryEndpointUrl.asInstanceOf[js.Any], keyVaultDnsSuffix = keyVaultDnsSuffix.asInstanceOf[js.Any], managementEndpointUrl = managementEndpointUrl.asInstanceOf[js.Any], name = name.asInstanceOf[js.Any], portalUrl = portalUrl.asInstanceOf[js.Any], publishingProfileUrl = publishingProfileUrl.asInstanceOf[js.Any], resourceManagerEndpointUrl = resourceManagerEndpointUrl.asInstanceOf[js.Any], sqlManagementEndpointUrl = sqlManagementEndpointUrl.asInstanceOf[js.Any], sqlServerHostnameSuffix = sqlServerHostnameSuffix.asInstanceOf[js.Any], storageEndpointSuffix = storageEndpointSuffix.asInstanceOf[js.Any], validateAuthority = validateAuthority.asInstanceOf[js.Any])
  
    __obj.asInstanceOf[Anon_20130405ActiveDirectoryEndpointUrlActiveDirectoryGraphApiVersionActiveDirectoryGraphResourceId]
  }
}

