package typingsSlinky.awsSdkClientCodecommitNode

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation.{JSGlobalScope, JSGlobal, JSImport, JSName, JSBracketAccess}

@JSImport("@aws-sdk/client-codecommit-node/types/CreatePullRequestExceptionsUnion", JSImport.Namespace)
@js.native
object createPullRequestExceptionsUnionMod extends js.Object {
  
  /* Rewritten from type alias, can be one of: 
    - typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryNameRequiredExceptionMod.RepositoryNameRequiredException
    - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryNameExceptionMod.InvalidRepositoryNameException
    - typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryDoesNotExistExceptionMod.RepositoryDoesNotExistException
    - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionIntegrityChecksFailedExceptionMod.EncryptionIntegrityChecksFailedException
    - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyAccessDeniedExceptionMod.EncryptionKeyAccessDeniedException
    - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyDisabledExceptionMod.EncryptionKeyDisabledException
    - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyNotFoundExceptionMod.EncryptionKeyNotFoundException
    - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyUnavailableExceptionMod.EncryptionKeyUnavailableException
    - typingsSlinky.awsSdkClientCodecommitNode.typesClientRequestTokenRequiredExceptionMod.ClientRequestTokenRequiredException
    - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidClientRequestTokenExceptionMod.InvalidClientRequestTokenException
    - typingsSlinky.awsSdkClientCodecommitNode.typesIdempotencyParameterMismatchExceptionMod.IdempotencyParameterMismatchException
    - typingsSlinky.awsSdkClientCodecommitNode.typesReferenceNameRequiredExceptionMod.ReferenceNameRequiredException
    - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidReferenceNameExceptionMod.InvalidReferenceNameException
    - typingsSlinky.awsSdkClientCodecommitNode.typesReferenceDoesNotExistExceptionMod.ReferenceDoesNotExistException
    - typingsSlinky.awsSdkClientCodecommitNode.typesReferenceTypeNotSupportedExceptionMod.ReferenceTypeNotSupportedException
    - typingsSlinky.awsSdkClientCodecommitNode.typesTitleRequiredExceptionMod.TitleRequiredException
    - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidTitleExceptionMod.InvalidTitleException
    - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidDescriptionExceptionMod.InvalidDescriptionException
    - typingsSlinky.awsSdkClientCodecommitNode.typesTargetsRequiredExceptionMod.TargetsRequiredException
    - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidTargetsExceptionMod.InvalidTargetsException
    - typingsSlinky.awsSdkClientCodecommitNode.typesTargetRequiredExceptionMod.TargetRequiredException
    - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidTargetExceptionMod.InvalidTargetException
    - typingsSlinky.awsSdkClientCodecommitNode.typesMultipleRepositoriesInPullRequestExceptionMod.MultipleRepositoriesInPullRequestException
    - typingsSlinky.awsSdkClientCodecommitNode.typesMaximumOpenPullRequestsExceededExceptionMod.MaximumOpenPullRequestsExceededException
    - typingsSlinky.awsSdkClientCodecommitNode.typesSourceAndDestinationAreSameExceptionMod.SourceAndDestinationAreSameException
  */
  trait CreatePullRequestExceptionsUnion extends js.Object
}
