package typingsSlinky.awsSdk.iamMod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait UpdateSAMLProviderRequest extends js.Object {
  /**
    * An XML document generated by an identity provider (IdP) that supports SAML 2.0. The document includes the issuer's name, expiration information, and keys that can be used to validate the SAML authentication response (assertions) that are received from the IdP. You must generate the metadata document using the identity management software that is used as your organization's IdP.
    */
  var SAMLMetadataDocument: SAMLMetadataDocumentType = js.native
  /**
    * The Amazon Resource Name (ARN) of the SAML provider to update. For more information about ARNs, see Amazon Resource Names (ARNs) and AWS Service Namespaces in the AWS General Reference.
    */
  var SAMLProviderArn: arnType = js.native
}

object UpdateSAMLProviderRequest {
  @scala.inline
  def apply(SAMLMetadataDocument: SAMLMetadataDocumentType, SAMLProviderArn: arnType): UpdateSAMLProviderRequest = {
    val __obj = js.Dynamic.literal(SAMLMetadataDocument = SAMLMetadataDocument.asInstanceOf[js.Any], SAMLProviderArn = SAMLProviderArn.asInstanceOf[js.Any])
    __obj.asInstanceOf[UpdateSAMLProviderRequest]
  }
  @scala.inline
  implicit class UpdateSAMLProviderRequestOps[Self <: UpdateSAMLProviderRequest] (val x: Self) extends AnyVal {
    @scala.inline
    def duplicate: Self = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x)).asInstanceOf[Self]
    @scala.inline
    def combineWith[Other <: js.Any](other: Other): Self with Other = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x, other.asInstanceOf[js.Any])).asInstanceOf[Self with Other]
    @scala.inline
    def withSAMLMetadataDocument(value: SAMLMetadataDocumentType): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("SAMLMetadataDocument")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withSAMLProviderArn(value: arnType): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("SAMLProviderArn")(value.asInstanceOf[js.Any])
        ret
    }
  }
  
}

