package typingsSlinky.officeUiFabricReact.keytipDataTypesMod

import typingsSlinky.officeUiFabricReact.keytipTypesMod.IKeytipProps
import typingsSlinky.uifabricUtilities.baseComponentTypesMod.IBaseProps
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait IKeytipDataProps extends IBaseProps[IKeytip] {
  /**
    * String to add to the aria-describedby generated by this KeytipData
    * It will prepend this string to the generated aria-describedby property
    */
  var ariaDescribedBy: js.UndefOr[String] = js.native
  /**
    * T/F if this keytip should be disabled upon creation
    */
  var disabled: js.UndefOr[Boolean] = js.native
  /**
    * IKeytipProps to create from this KeytipData
    * If no keytipProps are defined, a keytip won't be registered
    */
  var keytipProps: js.UndefOr[IKeytipProps] = js.native
}

object IKeytipDataProps {
  @scala.inline
  def apply(): IKeytipDataProps = {
    val __obj = js.Dynamic.literal()
    __obj.asInstanceOf[IKeytipDataProps]
  }
  @scala.inline
  implicit class IKeytipDataPropsOps[Self <: IKeytipDataProps] (val x: Self) extends AnyVal {
    @scala.inline
    def duplicate: Self = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x)).asInstanceOf[Self]
    @scala.inline
    def combineWith[Other <: js.Any](other: Other): Self with Other = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x, other.asInstanceOf[js.Any])).asInstanceOf[Self with Other]
    @scala.inline
    def withAriaDescribedBy(value: String): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("ariaDescribedBy")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutAriaDescribedBy: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("ariaDescribedBy")(js.undefined)
        ret
    }
    @scala.inline
    def withDisabled(value: Boolean): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("disabled")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutDisabled: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("disabled")(js.undefined)
        ret
    }
    @scala.inline
    def withKeytipProps(value: IKeytipProps): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("keytipProps")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutKeytipProps: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("keytipProps")(js.undefined)
        ret
    }
  }
  
}

