package typingsSlinky.awsSdkClientCodecommitNode.getDifferencesExceptionsUnionMod

import typingsSlinky.awsSdkClientCodecommitNode.typesCommitDoesNotExistExceptionMod.CommitDoesNotExistException
import typingsSlinky.awsSdkClientCodecommitNode.typesCommitRequiredExceptionMod.CommitRequiredException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionIntegrityChecksFailedExceptionMod.EncryptionIntegrityChecksFailedException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyAccessDeniedExceptionMod.EncryptionKeyAccessDeniedException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyDisabledExceptionMod.EncryptionKeyDisabledException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyNotFoundExceptionMod.EncryptionKeyNotFoundException
import typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyUnavailableExceptionMod.EncryptionKeyUnavailableException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidCommitExceptionMod.InvalidCommitException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidCommitIdExceptionMod.InvalidCommitIdException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidContinuationTokenExceptionMod.InvalidContinuationTokenException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidMaxResultsExceptionMod.InvalidMaxResultsException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidPathExceptionMod.InvalidPathException
import typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryNameExceptionMod.InvalidRepositoryNameException
import typingsSlinky.awsSdkClientCodecommitNode.typesPathDoesNotExistExceptionMod.PathDoesNotExistException
import typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryDoesNotExistExceptionMod.RepositoryDoesNotExistException
import typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryNameRequiredExceptionMod.RepositoryNameRequiredException
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

/* Rewritten from type alias, can be one of: 
  - typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryNameRequiredExceptionMod.RepositoryNameRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesRepositoryDoesNotExistExceptionMod.RepositoryDoesNotExistException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidRepositoryNameExceptionMod.InvalidRepositoryNameException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidContinuationTokenExceptionMod.InvalidContinuationTokenException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidMaxResultsExceptionMod.InvalidMaxResultsException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidCommitIdExceptionMod.InvalidCommitIdException
  - typingsSlinky.awsSdkClientCodecommitNode.typesCommitRequiredExceptionMod.CommitRequiredException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidCommitExceptionMod.InvalidCommitException
  - typingsSlinky.awsSdkClientCodecommitNode.typesCommitDoesNotExistExceptionMod.CommitDoesNotExistException
  - typingsSlinky.awsSdkClientCodecommitNode.typesInvalidPathExceptionMod.InvalidPathException
  - typingsSlinky.awsSdkClientCodecommitNode.typesPathDoesNotExistExceptionMod.PathDoesNotExistException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionIntegrityChecksFailedExceptionMod.EncryptionIntegrityChecksFailedException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyAccessDeniedExceptionMod.EncryptionKeyAccessDeniedException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyDisabledExceptionMod.EncryptionKeyDisabledException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyNotFoundExceptionMod.EncryptionKeyNotFoundException
  - typingsSlinky.awsSdkClientCodecommitNode.typesEncryptionKeyUnavailableExceptionMod.EncryptionKeyUnavailableException
*/
trait GetDifferencesExceptionsUnion extends js.Object

object GetDifferencesExceptionsUnion {
  @scala.inline
  implicit def apply(value: CommitDoesNotExistException): GetDifferencesExceptionsUnion = value.asInstanceOf[GetDifferencesExceptionsUnion]
  @scala.inline
  implicit def apply(value: CommitRequiredException): GetDifferencesExceptionsUnion = value.asInstanceOf[GetDifferencesExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionIntegrityChecksFailedException): GetDifferencesExceptionsUnion = value.asInstanceOf[GetDifferencesExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyAccessDeniedException): GetDifferencesExceptionsUnion = value.asInstanceOf[GetDifferencesExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyDisabledException): GetDifferencesExceptionsUnion = value.asInstanceOf[GetDifferencesExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyNotFoundException): GetDifferencesExceptionsUnion = value.asInstanceOf[GetDifferencesExceptionsUnion]
  @scala.inline
  implicit def apply(value: EncryptionKeyUnavailableException): GetDifferencesExceptionsUnion = value.asInstanceOf[GetDifferencesExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidCommitException): GetDifferencesExceptionsUnion = value.asInstanceOf[GetDifferencesExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidCommitIdException): GetDifferencesExceptionsUnion = value.asInstanceOf[GetDifferencesExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidContinuationTokenException): GetDifferencesExceptionsUnion = value.asInstanceOf[GetDifferencesExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidMaxResultsException): GetDifferencesExceptionsUnion = value.asInstanceOf[GetDifferencesExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidPathException): GetDifferencesExceptionsUnion = value.asInstanceOf[GetDifferencesExceptionsUnion]
  @scala.inline
  implicit def apply(value: InvalidRepositoryNameException): GetDifferencesExceptionsUnion = value.asInstanceOf[GetDifferencesExceptionsUnion]
  @scala.inline
  implicit def apply(value: PathDoesNotExistException): GetDifferencesExceptionsUnion = value.asInstanceOf[GetDifferencesExceptionsUnion]
  @scala.inline
  implicit def apply(value: RepositoryDoesNotExistException): GetDifferencesExceptionsUnion = value.asInstanceOf[GetDifferencesExceptionsUnion]
  @scala.inline
  implicit def apply(value: RepositoryNameRequiredException): GetDifferencesExceptionsUnion = value.asInstanceOf[GetDifferencesExceptionsUnion]
}

