package typingsSlinky.awsSdk.sagemakerMod

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait TrainingSpecification extends js.Object {
  /**
    * A list of MetricDefinition objects, which are used for parsing metrics generated by the algorithm.
    */
  var MetricDefinitions: js.UndefOr[MetricDefinitionList] = js.native
  /**
    * A list of the HyperParameterSpecification objects, that define the supported hyperparameters. This is required if the algorithm supports automatic model tuning.&gt;
    */
  var SupportedHyperParameters: js.UndefOr[HyperParameterSpecifications] = js.native
  /**
    * A list of the instance types that this algorithm can use for training.
    */
  var SupportedTrainingInstanceTypes: TrainingInstanceTypes = js.native
  /**
    * A list of the metrics that the algorithm emits that can be used as the objective metric in a hyperparameter tuning job.
    */
  var SupportedTuningJobObjectiveMetrics: js.UndefOr[HyperParameterTuningJobObjectives] = js.native
  /**
    * Indicates whether the algorithm supports distributed training. If set to false, buyers can't request more than one instance during training.
    */
  var SupportsDistributedTraining: js.UndefOr[Boolean] = js.native
  /**
    * A list of ChannelSpecification objects, which specify the input sources to be used by the algorithm.
    */
  var TrainingChannels: ChannelSpecifications = js.native
  /**
    * The Amazon ECR registry path of the Docker image that contains the training algorithm.
    */
  var TrainingImage: Image = js.native
  /**
    * An MD5 hash of the training algorithm that identifies the Docker image used for training.
    */
  var TrainingImageDigest: js.UndefOr[ImageDigest] = js.native
}

object TrainingSpecification {
  @scala.inline
  def apply(
    SupportedTrainingInstanceTypes: TrainingInstanceTypes,
    TrainingChannels: ChannelSpecifications,
    TrainingImage: Image
  ): TrainingSpecification = {
    val __obj = js.Dynamic.literal(SupportedTrainingInstanceTypes = SupportedTrainingInstanceTypes.asInstanceOf[js.Any], TrainingChannels = TrainingChannels.asInstanceOf[js.Any], TrainingImage = TrainingImage.asInstanceOf[js.Any])
    __obj.asInstanceOf[TrainingSpecification]
  }
  @scala.inline
  implicit class TrainingSpecificationOps[Self <: TrainingSpecification] (val x: Self) extends AnyVal {
    @scala.inline
    def duplicate: Self = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x)).asInstanceOf[Self]
    @scala.inline
    def combineWith[Other <: js.Any](other: Other): Self with Other = (js.Dynamic.global.Object.assign(js.Dynamic.literal(), x, other.asInstanceOf[js.Any])).asInstanceOf[Self with Other]
    @scala.inline
    def withSupportedTrainingInstanceTypes(value: TrainingInstanceTypes): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("SupportedTrainingInstanceTypes")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withTrainingChannels(value: ChannelSpecifications): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("TrainingChannels")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withTrainingImage(value: Image): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("TrainingImage")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withMetricDefinitions(value: MetricDefinitionList): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("MetricDefinitions")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutMetricDefinitions: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("MetricDefinitions")(js.undefined)
        ret
    }
    @scala.inline
    def withSupportedHyperParameters(value: HyperParameterSpecifications): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("SupportedHyperParameters")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutSupportedHyperParameters: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("SupportedHyperParameters")(js.undefined)
        ret
    }
    @scala.inline
    def withSupportedTuningJobObjectiveMetrics(value: HyperParameterTuningJobObjectives): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("SupportedTuningJobObjectiveMetrics")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutSupportedTuningJobObjectiveMetrics: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("SupportedTuningJobObjectiveMetrics")(js.undefined)
        ret
    }
    @scala.inline
    def withSupportsDistributedTraining(value: Boolean): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("SupportsDistributedTraining")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutSupportsDistributedTraining: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("SupportsDistributedTraining")(js.undefined)
        ret
    }
    @scala.inline
    def withTrainingImageDigest(value: ImageDigest): Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("TrainingImageDigest")(value.asInstanceOf[js.Any])
        ret
    }
    @scala.inline
    def withoutTrainingImageDigest: Self = {
        val ret = this.duplicate
        ret.asInstanceOf[js.Dynamic].updateDynamic("TrainingImageDigest")(js.undefined)
        ret
    }
  }
  
}

