package typingsSlinky.astDashTypes.genNamedTypesMod

import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.AnyTypeAnnotation
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ArrayExpression
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ArrayPattern
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ArrayTypeAnnotation
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ArrowFunctionExpression
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.AssignmentExpression
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.AssignmentPattern
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.AwaitExpression
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.BigIntLiteral
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.BinaryExpression
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.BindExpression
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Block
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.BlockStatement
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.BooleanLiteral
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.BooleanLiteralTypeAnnotation
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.BooleanTypeAnnotation
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.BreakStatement
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.CallExpression
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.CatchClause
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ClassBody
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ClassDeclaration
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ClassExpression
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ClassImplements
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ClassMethod
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ClassPrivateMethod
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ClassPrivateProperty
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ClassProperty
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ClassPropertyDefinition
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Comment
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.CommentBlock
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.CommentLine
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ComprehensionBlock
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ComprehensionExpression
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ConditionalExpression
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ContinueStatement
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.DebuggerStatement
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Declaration
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.DeclareClass
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.DeclareExportAllDeclaration
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.DeclareExportDeclaration
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.DeclareFunction
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.DeclareInterface
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.DeclareModule
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.DeclareModuleExports
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.DeclareOpaqueType
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.DeclareTypeAlias
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.DeclareVariable
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.DeclaredPredicate
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Decorator
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Directive
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.DirectiveLiteral
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.DoExpression
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.DoWhileStatement
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.EmptyStatement
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.EmptyTypeAnnotation
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ExistentialTypeParam
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ExistsTypeAnnotation
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ExportAllDeclaration
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ExportBatchSpecifier
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ExportDeclaration
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ExportDefaultDeclaration
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ExportDefaultSpecifier
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ExportNamedDeclaration
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ExportNamespaceSpecifier
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ExportSpecifier
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Expression
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ExpressionStatement
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.File
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Flow
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.FlowPredicate
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.FlowType
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ForAwaitStatement
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ForInStatement
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ForOfStatement
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ForStatement
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Function
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.FunctionDeclaration
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.FunctionExpression
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.FunctionTypeAnnotation
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.FunctionTypeParam
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.GeneratorExpression
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.GenericTypeAnnotation
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Identifier
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.IfStatement
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Import
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ImportDeclaration
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ImportDefaultSpecifier
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ImportNamespaceSpecifier
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ImportSpecifier
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.InferredPredicate
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.InterfaceDeclaration
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.InterfaceExtends
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.InterfaceTypeAnnotation
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.InterpreterDirective
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.IntersectionTypeAnnotation
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.JSXAttribute
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.JSXClosingElement
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.JSXClosingFragment
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.JSXElement
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.JSXEmptyExpression
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.JSXExpressionContainer
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.JSXFragment
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.JSXIdentifier
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.JSXMemberExpression
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.JSXNamespacedName
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.JSXOpeningElement
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.JSXOpeningFragment
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.JSXSpreadAttribute
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.JSXSpreadChild
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.JSXText
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.LabeledStatement
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Line
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Literal
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.LogicalExpression
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.MemberExpression
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.MemberTypeAnnotation
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.MetaProperty
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.MethodDefinition
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.MixedTypeAnnotation
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ModuleSpecifier
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.NewExpression
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Node
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Noop
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.NullLiteral
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.NullLiteralTypeAnnotation
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.NullTypeAnnotation
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.NullableTypeAnnotation
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.NumberLiteralTypeAnnotation
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.NumberTypeAnnotation
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.NumericLiteral
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.NumericLiteralTypeAnnotation
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ObjectExpression
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ObjectMethod
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ObjectPattern
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ObjectProperty
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ObjectTypeAnnotation
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ObjectTypeCallProperty
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ObjectTypeIndexer
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ObjectTypeInternalSlot
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ObjectTypeProperty
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ObjectTypeSpreadProperty
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.OpaqueType
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.OptionalCallExpression
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.OptionalMemberExpression
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ParenthesizedExpression
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Pattern
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Position
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Printable
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.PrivateName
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Program
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Property
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.PropertyPattern
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.QualifiedTypeIdentifier
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.RegExpLiteral
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.RestElement
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.RestProperty
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ReturnStatement
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.SequenceExpression
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.SourceLocation
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Specifier
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.SpreadElement
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.SpreadElementPattern
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.SpreadProperty
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.SpreadPropertyPattern
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Statement
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.StringLiteral
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.StringLiteralTypeAnnotation
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.StringTypeAnnotation
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Super
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.SwitchCase
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.SwitchStatement
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSAnyKeyword
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSArrayType
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSAsExpression
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSBigIntKeyword
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSBooleanKeyword
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSCallSignatureDeclaration
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSConditionalType
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSConstructSignatureDeclaration
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSConstructorType
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSDeclareFunction
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSDeclareMethod
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSEnumDeclaration
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSEnumMember
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSExportAssignment
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSExpressionWithTypeArguments
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSExternalModuleReference
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSFunctionType
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSHasOptionalTypeAnnotation
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSHasOptionalTypeParameterInstantiation
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSHasOptionalTypeParameters
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSImportEqualsDeclaration
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSImportType
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSIndexSignature
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSIndexedAccessType
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSInferType
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSInterfaceBody
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSInterfaceDeclaration
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSIntersectionType
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSLiteralType
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSMappedType
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSMethodSignature
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSModuleBlock
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSModuleDeclaration
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSNamespaceExportDeclaration
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSNeverKeyword
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSNonNullExpression
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSNullKeyword
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSNumberKeyword
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSObjectKeyword
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSOptionalType
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSParameterProperty
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSParenthesizedType
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSPropertySignature
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSQualifiedName
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSRestType
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSStringKeyword
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSSymbolKeyword
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSThisType
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSTupleType
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSType
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSTypeAliasDeclaration
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSTypeAnnotation
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSTypeAssertion
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSTypeLiteral
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSTypeOperator
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSTypeParameter
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSTypeParameterDeclaration
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSTypeParameterInstantiation
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSTypePredicate
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSTypeQuery
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSTypeReference
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSUndefinedKeyword
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSUnionType
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSUnknownKeyword
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSVoidKeyword
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TaggedTemplateExpression
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TemplateElement
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TemplateLiteral
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ThisExpression
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ThisTypeAnnotation
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ThrowStatement
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TryStatement
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TupleTypeAnnotation
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TypeAlias
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TypeAnnotation
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TypeCastExpression
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TypeParameter
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TypeParameterDeclaration
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TypeParameterInstantiation
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TypeofTypeAnnotation
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.UnaryExpression
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.UnionTypeAnnotation
import typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.UpdateExpression
import typingsSlinky.astDashTypes.libTypesMod.Type
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

trait NamedTypes extends js.Object {
  var AnyTypeAnnotation: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.AnyTypeAnnotation]
  var ArrayExpression: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ArrayExpression]
  var ArrayPattern: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ArrayPattern]
  var ArrayTypeAnnotation: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ArrayTypeAnnotation]
  var ArrowFunctionExpression: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ArrowFunctionExpression]
  var AssignmentExpression: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.AssignmentExpression]
  var AssignmentPattern: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.AssignmentPattern]
  var AwaitExpression: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.AwaitExpression]
  var BigIntLiteral: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.BigIntLiteral]
  var BinaryExpression: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.BinaryExpression]
  var BindExpression: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.BindExpression]
  var Block: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Block]
  var BlockStatement: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.BlockStatement]
  var BooleanLiteral: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.BooleanLiteral]
  var BooleanLiteralTypeAnnotation: Type[
    typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.BooleanLiteralTypeAnnotation
  ]
  var BooleanTypeAnnotation: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.BooleanTypeAnnotation]
  var BreakStatement: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.BreakStatement]
  var CallExpression: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.CallExpression]
  var CatchClause: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.CatchClause]
  var ClassBody: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ClassBody]
  var ClassDeclaration: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ClassDeclaration]
  var ClassExpression: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ClassExpression]
  var ClassImplements: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ClassImplements]
  var ClassMethod: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ClassMethod]
  var ClassPrivateMethod: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ClassPrivateMethod]
  var ClassPrivateProperty: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ClassPrivateProperty]
  var ClassProperty: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ClassProperty]
  var ClassPropertyDefinition: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ClassPropertyDefinition]
  var Comment: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Comment]
  var CommentBlock: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.CommentBlock]
  var CommentLine: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.CommentLine]
  var ComprehensionBlock: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ComprehensionBlock]
  var ComprehensionExpression: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ComprehensionExpression]
  var ConditionalExpression: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ConditionalExpression]
  var ContinueStatement: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ContinueStatement]
  var DebuggerStatement: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.DebuggerStatement]
  var Declaration: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Declaration]
  var DeclareClass: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.DeclareClass]
  var DeclareExportAllDeclaration: Type[
    typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.DeclareExportAllDeclaration
  ]
  var DeclareExportDeclaration: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.DeclareExportDeclaration]
  var DeclareFunction: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.DeclareFunction]
  var DeclareInterface: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.DeclareInterface]
  var DeclareModule: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.DeclareModule]
  var DeclareModuleExports: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.DeclareModuleExports]
  var DeclareOpaqueType: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.DeclareOpaqueType]
  var DeclareTypeAlias: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.DeclareTypeAlias]
  var DeclareVariable: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.DeclareVariable]
  var DeclaredPredicate: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.DeclaredPredicate]
  var Decorator: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Decorator]
  var Directive: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Directive]
  var DirectiveLiteral: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.DirectiveLiteral]
  var DoExpression: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.DoExpression]
  var DoWhileStatement: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.DoWhileStatement]
  var EmptyStatement: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.EmptyStatement]
  var EmptyTypeAnnotation: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.EmptyTypeAnnotation]
  var ExistentialTypeParam: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ExistentialTypeParam]
  var ExistsTypeAnnotation: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ExistsTypeAnnotation]
  var ExportAllDeclaration: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ExportAllDeclaration]
  var ExportBatchSpecifier: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ExportBatchSpecifier]
  var ExportDeclaration: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ExportDeclaration]
  var ExportDefaultDeclaration: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ExportDefaultDeclaration]
  var ExportDefaultSpecifier: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ExportDefaultSpecifier]
  var ExportNamedDeclaration: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ExportNamedDeclaration]
  var ExportNamespaceSpecifier: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ExportNamespaceSpecifier]
  var ExportSpecifier: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ExportSpecifier]
  var Expression: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Expression]
  var ExpressionStatement: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ExpressionStatement]
  var File: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.File]
  var Flow: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Flow]
  var FlowPredicate: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.FlowPredicate]
  var FlowType: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.FlowType]
  var ForAwaitStatement: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ForAwaitStatement]
  var ForInStatement: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ForInStatement]
  var ForOfStatement: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ForOfStatement]
  var ForStatement: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ForStatement]
  var Function: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Function]
  var FunctionDeclaration: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.FunctionDeclaration]
  var FunctionExpression: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.FunctionExpression]
  var FunctionTypeAnnotation: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.FunctionTypeAnnotation]
  var FunctionTypeParam: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.FunctionTypeParam]
  var GeneratorExpression: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.GeneratorExpression]
  var GenericTypeAnnotation: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.GenericTypeAnnotation]
  var Identifier: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Identifier]
  var IfStatement: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.IfStatement]
  var Import: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Import]
  var ImportDeclaration: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ImportDeclaration]
  var ImportDefaultSpecifier: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ImportDefaultSpecifier]
  var ImportNamespaceSpecifier: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ImportNamespaceSpecifier]
  var ImportSpecifier: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ImportSpecifier]
  var InferredPredicate: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.InferredPredicate]
  var InterfaceDeclaration: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.InterfaceDeclaration]
  var InterfaceExtends: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.InterfaceExtends]
  var InterfaceTypeAnnotation: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.InterfaceTypeAnnotation]
  var InterpreterDirective: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.InterpreterDirective]
  var IntersectionTypeAnnotation: Type[
    typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.IntersectionTypeAnnotation
  ]
  var JSXAttribute: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.JSXAttribute]
  var JSXClosingElement: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.JSXClosingElement]
  var JSXClosingFragment: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.JSXClosingFragment]
  var JSXElement: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.JSXElement]
  var JSXEmptyExpression: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.JSXEmptyExpression]
  var JSXExpressionContainer: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.JSXExpressionContainer]
  var JSXFragment: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.JSXFragment]
  var JSXIdentifier: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.JSXIdentifier]
  var JSXMemberExpression: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.JSXMemberExpression]
  var JSXNamespacedName: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.JSXNamespacedName]
  var JSXOpeningElement: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.JSXOpeningElement]
  var JSXOpeningFragment: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.JSXOpeningFragment]
  var JSXSpreadAttribute: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.JSXSpreadAttribute]
  var JSXSpreadChild: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.JSXSpreadChild]
  var JSXText: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.JSXText]
  var LabeledStatement: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.LabeledStatement]
  var Line: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Line]
  var Literal: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Literal]
  var LogicalExpression: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.LogicalExpression]
  var MemberExpression: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.MemberExpression]
  var MemberTypeAnnotation: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.MemberTypeAnnotation]
  var MetaProperty: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.MetaProperty]
  var MethodDefinition: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.MethodDefinition]
  var MixedTypeAnnotation: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.MixedTypeAnnotation]
  var ModuleSpecifier: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ModuleSpecifier]
  var NewExpression: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.NewExpression]
  var Node: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Node]
  var Noop: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Noop]
  var NullLiteral: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.NullLiteral]
  var NullLiteralTypeAnnotation: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.NullLiteralTypeAnnotation]
  var NullTypeAnnotation: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.NullTypeAnnotation]
  var NullableTypeAnnotation: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.NullableTypeAnnotation]
  var NumberLiteralTypeAnnotation: Type[
    typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.NumberLiteralTypeAnnotation
  ]
  var NumberTypeAnnotation: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.NumberTypeAnnotation]
  var NumericLiteral: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.NumericLiteral]
  var NumericLiteralTypeAnnotation: Type[
    typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.NumericLiteralTypeAnnotation
  ]
  var ObjectExpression: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ObjectExpression]
  var ObjectMethod: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ObjectMethod]
  var ObjectPattern: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ObjectPattern]
  var ObjectProperty: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ObjectProperty]
  var ObjectTypeAnnotation: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ObjectTypeAnnotation]
  var ObjectTypeCallProperty: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ObjectTypeCallProperty]
  var ObjectTypeIndexer: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ObjectTypeIndexer]
  var ObjectTypeInternalSlot: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ObjectTypeInternalSlot]
  var ObjectTypeProperty: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ObjectTypeProperty]
  var ObjectTypeSpreadProperty: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ObjectTypeSpreadProperty]
  var OpaqueType: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.OpaqueType]
  var OptionalCallExpression: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.OptionalCallExpression]
  var OptionalMemberExpression: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.OptionalMemberExpression]
  var ParenthesizedExpression: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ParenthesizedExpression]
  var Pattern: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Pattern]
  var Position: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Position]
  var Printable: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Printable]
  var PrivateName: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.PrivateName]
  var Program: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Program]
  var Property: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Property]
  var PropertyPattern: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.PropertyPattern]
  var QualifiedTypeIdentifier: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.QualifiedTypeIdentifier]
  var RegExpLiteral: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.RegExpLiteral]
  var RestElement: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.RestElement]
  var RestProperty: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.RestProperty]
  var ReturnStatement: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ReturnStatement]
  var SequenceExpression: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.SequenceExpression]
  var SourceLocation: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.SourceLocation]
  var Specifier: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Specifier]
  var SpreadElement: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.SpreadElement]
  var SpreadElementPattern: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.SpreadElementPattern]
  var SpreadProperty: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.SpreadProperty]
  var SpreadPropertyPattern: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.SpreadPropertyPattern]
  var Statement: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Statement]
  var StringLiteral: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.StringLiteral]
  var StringLiteralTypeAnnotation: Type[
    typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.StringLiteralTypeAnnotation
  ]
  var StringTypeAnnotation: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.StringTypeAnnotation]
  var Super: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Super]
  var SwitchCase: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.SwitchCase]
  var SwitchStatement: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.SwitchStatement]
  var TSAnyKeyword: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSAnyKeyword]
  var TSArrayType: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSArrayType]
  var TSAsExpression: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSAsExpression]
  var TSBigIntKeyword: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSBigIntKeyword]
  var TSBooleanKeyword: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSBooleanKeyword]
  var TSCallSignatureDeclaration: Type[
    typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSCallSignatureDeclaration
  ]
  var TSConditionalType: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSConditionalType]
  var TSConstructSignatureDeclaration: Type[
    typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSConstructSignatureDeclaration
  ]
  var TSConstructorType: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSConstructorType]
  var TSDeclareFunction: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSDeclareFunction]
  var TSDeclareMethod: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSDeclareMethod]
  var TSEnumDeclaration: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSEnumDeclaration]
  var TSEnumMember: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSEnumMember]
  var TSExportAssignment: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSExportAssignment]
  var TSExpressionWithTypeArguments: Type[
    typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSExpressionWithTypeArguments
  ]
  var TSExternalModuleReference: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSExternalModuleReference]
  var TSFunctionType: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSFunctionType]
  var TSHasOptionalTypeAnnotation: Type[
    typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSHasOptionalTypeAnnotation
  ]
  var TSHasOptionalTypeParameterInstantiation: Type[
    typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSHasOptionalTypeParameterInstantiation
  ]
  var TSHasOptionalTypeParameters: Type[
    typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSHasOptionalTypeParameters
  ]
  var TSImportEqualsDeclaration: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSImportEqualsDeclaration]
  var TSImportType: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSImportType]
  var TSIndexSignature: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSIndexSignature]
  var TSIndexedAccessType: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSIndexedAccessType]
  var TSInferType: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSInferType]
  var TSInterfaceBody: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSInterfaceBody]
  var TSInterfaceDeclaration: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSInterfaceDeclaration]
  var TSIntersectionType: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSIntersectionType]
  var TSLiteralType: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSLiteralType]
  var TSMappedType: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSMappedType]
  var TSMethodSignature: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSMethodSignature]
  var TSModuleBlock: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSModuleBlock]
  var TSModuleDeclaration: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSModuleDeclaration]
  var TSNamespaceExportDeclaration: Type[
    typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSNamespaceExportDeclaration
  ]
  var TSNeverKeyword: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSNeverKeyword]
  var TSNonNullExpression: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSNonNullExpression]
  var TSNullKeyword: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSNullKeyword]
  var TSNumberKeyword: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSNumberKeyword]
  var TSObjectKeyword: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSObjectKeyword]
  var TSOptionalType: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSOptionalType]
  var TSParameterProperty: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSParameterProperty]
  var TSParenthesizedType: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSParenthesizedType]
  var TSPropertySignature: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSPropertySignature]
  var TSQualifiedName: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSQualifiedName]
  var TSRestType: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSRestType]
  var TSStringKeyword: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSStringKeyword]
  var TSSymbolKeyword: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSSymbolKeyword]
  var TSThisType: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSThisType]
  var TSTupleType: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSTupleType]
  var TSType: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSType]
  var TSTypeAliasDeclaration: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSTypeAliasDeclaration]
  var TSTypeAnnotation: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSTypeAnnotation]
  var TSTypeAssertion: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSTypeAssertion]
  var TSTypeLiteral: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSTypeLiteral]
  var TSTypeOperator: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSTypeOperator]
  var TSTypeParameter: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSTypeParameter]
  var TSTypeParameterDeclaration: Type[
    typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSTypeParameterDeclaration
  ]
  var TSTypeParameterInstantiation: Type[
    typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSTypeParameterInstantiation
  ]
  var TSTypePredicate: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSTypePredicate]
  var TSTypeQuery: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSTypeQuery]
  var TSTypeReference: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSTypeReference]
  var TSUndefinedKeyword: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSUndefinedKeyword]
  var TSUnionType: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSUnionType]
  var TSUnknownKeyword: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSUnknownKeyword]
  var TSVoidKeyword: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TSVoidKeyword]
  var TaggedTemplateExpression: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TaggedTemplateExpression]
  var TemplateElement: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TemplateElement]
  var TemplateLiteral: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TemplateLiteral]
  var ThisExpression: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ThisExpression]
  var ThisTypeAnnotation: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ThisTypeAnnotation]
  var ThrowStatement: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.ThrowStatement]
  var TryStatement: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TryStatement]
  var TupleTypeAnnotation: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TupleTypeAnnotation]
  var TypeAlias: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TypeAlias]
  var TypeAnnotation: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TypeAnnotation]
  var TypeCastExpression: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TypeCastExpression]
  var TypeParameter: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TypeParameter]
  var TypeParameterDeclaration: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TypeParameterDeclaration]
  var TypeParameterInstantiation: Type[
    typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TypeParameterInstantiation
  ]
  var TypeofTypeAnnotation: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.TypeofTypeAnnotation]
  var UnaryExpression: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.UnaryExpression]
  var UnionTypeAnnotation: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.UnionTypeAnnotation]
  var UpdateExpression: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.UpdateExpression]
  var VariableDeclaration: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.VariableDeclaration]
  var VariableDeclarator: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.VariableDeclarator]
  var Variance: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.Variance]
  var VoidTypeAnnotation: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.VoidTypeAnnotation]
  var WhileStatement: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.WhileStatement]
  var WithStatement: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.WithStatement]
  var YieldExpression: Type[typingsSlinky.astDashTypes.genNamedTypesMod.namedTypes.YieldExpression]
}

object NamedTypes {
  @scala.inline
  def apply(
    AnyTypeAnnotation: Type[AnyTypeAnnotation],
    ArrayExpression: Type[ArrayExpression],
    ArrayPattern: Type[ArrayPattern],
    ArrayTypeAnnotation: Type[ArrayTypeAnnotation],
    ArrowFunctionExpression: Type[ArrowFunctionExpression],
    AssignmentExpression: Type[AssignmentExpression],
    AssignmentPattern: Type[AssignmentPattern],
    AwaitExpression: Type[AwaitExpression],
    BigIntLiteral: Type[BigIntLiteral],
    BinaryExpression: Type[BinaryExpression],
    BindExpression: Type[BindExpression],
    Block: Type[Block],
    BlockStatement: Type[BlockStatement],
    BooleanLiteral: Type[BooleanLiteral],
    BooleanLiteralTypeAnnotation: Type[BooleanLiteralTypeAnnotation],
    BooleanTypeAnnotation: Type[BooleanTypeAnnotation],
    BreakStatement: Type[BreakStatement],
    CallExpression: Type[CallExpression],
    CatchClause: Type[CatchClause],
    ClassBody: Type[ClassBody],
    ClassDeclaration: Type[ClassDeclaration],
    ClassExpression: Type[ClassExpression],
    ClassImplements: Type[ClassImplements],
    ClassMethod: Type[ClassMethod],
    ClassPrivateMethod: Type[ClassPrivateMethod],
    ClassPrivateProperty: Type[ClassPrivateProperty],
    ClassProperty: Type[ClassProperty],
    ClassPropertyDefinition: Type[ClassPropertyDefinition],
    Comment: Type[Comment],
    CommentBlock: Type[CommentBlock],
    CommentLine: Type[CommentLine],
    ComprehensionBlock: Type[ComprehensionBlock],
    ComprehensionExpression: Type[ComprehensionExpression],
    ConditionalExpression: Type[ConditionalExpression],
    ContinueStatement: Type[ContinueStatement],
    DebuggerStatement: Type[DebuggerStatement],
    Declaration: Type[Declaration],
    DeclareClass: Type[DeclareClass],
    DeclareExportAllDeclaration: Type[DeclareExportAllDeclaration],
    DeclareExportDeclaration: Type[DeclareExportDeclaration],
    DeclareFunction: Type[DeclareFunction],
    DeclareInterface: Type[DeclareInterface],
    DeclareModule: Type[DeclareModule],
    DeclareModuleExports: Type[DeclareModuleExports],
    DeclareOpaqueType: Type[DeclareOpaqueType],
    DeclareTypeAlias: Type[DeclareTypeAlias],
    DeclareVariable: Type[DeclareVariable],
    DeclaredPredicate: Type[DeclaredPredicate],
    Decorator: Type[Decorator],
    Directive: Type[Directive],
    DirectiveLiteral: Type[DirectiveLiteral],
    DoExpression: Type[DoExpression],
    DoWhileStatement: Type[DoWhileStatement],
    EmptyStatement: Type[EmptyStatement],
    EmptyTypeAnnotation: Type[EmptyTypeAnnotation],
    ExistentialTypeParam: Type[ExistentialTypeParam],
    ExistsTypeAnnotation: Type[ExistsTypeAnnotation],
    ExportAllDeclaration: Type[ExportAllDeclaration],
    ExportBatchSpecifier: Type[ExportBatchSpecifier],
    ExportDeclaration: Type[ExportDeclaration],
    ExportDefaultDeclaration: Type[ExportDefaultDeclaration],
    ExportDefaultSpecifier: Type[ExportDefaultSpecifier],
    ExportNamedDeclaration: Type[ExportNamedDeclaration],
    ExportNamespaceSpecifier: Type[ExportNamespaceSpecifier],
    ExportSpecifier: Type[ExportSpecifier],
    Expression: Type[Expression],
    ExpressionStatement: Type[ExpressionStatement],
    File: Type[File],
    Flow: Type[Flow],
    FlowPredicate: Type[FlowPredicate],
    FlowType: Type[FlowType],
    ForAwaitStatement: Type[ForAwaitStatement],
    ForInStatement: Type[ForInStatement],
    ForOfStatement: Type[ForOfStatement],
    ForStatement: Type[ForStatement],
    Function: Type[Function],
    FunctionDeclaration: Type[FunctionDeclaration],
    FunctionExpression: Type[FunctionExpression],
    FunctionTypeAnnotation: Type[FunctionTypeAnnotation],
    FunctionTypeParam: Type[FunctionTypeParam],
    GeneratorExpression: Type[GeneratorExpression],
    GenericTypeAnnotation: Type[GenericTypeAnnotation],
    Identifier: Type[Identifier],
    IfStatement: Type[IfStatement],
    Import: Type[Import],
    ImportDeclaration: Type[ImportDeclaration],
    ImportDefaultSpecifier: Type[ImportDefaultSpecifier],
    ImportNamespaceSpecifier: Type[ImportNamespaceSpecifier],
    ImportSpecifier: Type[ImportSpecifier],
    InferredPredicate: Type[InferredPredicate],
    InterfaceDeclaration: Type[InterfaceDeclaration],
    InterfaceExtends: Type[InterfaceExtends],
    InterfaceTypeAnnotation: Type[InterfaceTypeAnnotation],
    InterpreterDirective: Type[InterpreterDirective],
    IntersectionTypeAnnotation: Type[IntersectionTypeAnnotation],
    JSXAttribute: Type[JSXAttribute],
    JSXClosingElement: Type[JSXClosingElement],
    JSXClosingFragment: Type[JSXClosingFragment],
    JSXElement: Type[JSXElement],
    JSXEmptyExpression: Type[JSXEmptyExpression],
    JSXExpressionContainer: Type[JSXExpressionContainer],
    JSXFragment: Type[JSXFragment],
    JSXIdentifier: Type[JSXIdentifier],
    JSXMemberExpression: Type[JSXMemberExpression],
    JSXNamespacedName: Type[JSXNamespacedName],
    JSXOpeningElement: Type[JSXOpeningElement],
    JSXOpeningFragment: Type[JSXOpeningFragment],
    JSXSpreadAttribute: Type[JSXSpreadAttribute],
    JSXSpreadChild: Type[JSXSpreadChild],
    JSXText: Type[JSXText],
    LabeledStatement: Type[LabeledStatement],
    Line: Type[Line],
    Literal: Type[Literal],
    LogicalExpression: Type[LogicalExpression],
    MemberExpression: Type[MemberExpression],
    MemberTypeAnnotation: Type[MemberTypeAnnotation],
    MetaProperty: Type[MetaProperty],
    MethodDefinition: Type[MethodDefinition],
    MixedTypeAnnotation: Type[MixedTypeAnnotation],
    ModuleSpecifier: Type[ModuleSpecifier],
    NewExpression: Type[NewExpression],
    Node: Type[Node],
    Noop: Type[Noop],
    NullLiteral: Type[NullLiteral],
    NullLiteralTypeAnnotation: Type[NullLiteralTypeAnnotation],
    NullTypeAnnotation: Type[NullTypeAnnotation],
    NullableTypeAnnotation: Type[NullableTypeAnnotation],
    NumberLiteralTypeAnnotation: Type[NumberLiteralTypeAnnotation],
    NumberTypeAnnotation: Type[NumberTypeAnnotation],
    NumericLiteral: Type[NumericLiteral],
    NumericLiteralTypeAnnotation: Type[NumericLiteralTypeAnnotation],
    ObjectExpression: Type[ObjectExpression],
    ObjectMethod: Type[ObjectMethod],
    ObjectPattern: Type[ObjectPattern],
    ObjectProperty: Type[ObjectProperty],
    ObjectTypeAnnotation: Type[ObjectTypeAnnotation],
    ObjectTypeCallProperty: Type[ObjectTypeCallProperty],
    ObjectTypeIndexer: Type[ObjectTypeIndexer],
    ObjectTypeInternalSlot: Type[ObjectTypeInternalSlot],
    ObjectTypeProperty: Type[ObjectTypeProperty],
    ObjectTypeSpreadProperty: Type[ObjectTypeSpreadProperty],
    OpaqueType: Type[OpaqueType],
    OptionalCallExpression: Type[OptionalCallExpression],
    OptionalMemberExpression: Type[OptionalMemberExpression],
    ParenthesizedExpression: Type[ParenthesizedExpression],
    Pattern: Type[Pattern],
    Position: Type[Position],
    Printable: Type[Printable],
    PrivateName: Type[PrivateName],
    Program: Type[Program],
    Property: Type[Property],
    PropertyPattern: Type[PropertyPattern],
    QualifiedTypeIdentifier: Type[QualifiedTypeIdentifier],
    RegExpLiteral: Type[RegExpLiteral],
    RestElement: Type[RestElement],
    RestProperty: Type[RestProperty],
    ReturnStatement: Type[ReturnStatement],
    SequenceExpression: Type[SequenceExpression],
    SourceLocation: Type[SourceLocation],
    Specifier: Type[Specifier],
    SpreadElement: Type[SpreadElement],
    SpreadElementPattern: Type[SpreadElementPattern],
    SpreadProperty: Type[SpreadProperty],
    SpreadPropertyPattern: Type[SpreadPropertyPattern],
    Statement: Type[Statement],
    StringLiteral: Type[StringLiteral],
    StringLiteralTypeAnnotation: Type[StringLiteralTypeAnnotation],
    StringTypeAnnotation: Type[StringTypeAnnotation],
    Super: Type[Super],
    SwitchCase: Type[SwitchCase],
    SwitchStatement: Type[SwitchStatement],
    TSAnyKeyword: Type[TSAnyKeyword],
    TSArrayType: Type[TSArrayType],
    TSAsExpression: Type[TSAsExpression],
    TSBigIntKeyword: Type[TSBigIntKeyword],
    TSBooleanKeyword: Type[TSBooleanKeyword],
    TSCallSignatureDeclaration: Type[TSCallSignatureDeclaration],
    TSConditionalType: Type[TSConditionalType],
    TSConstructSignatureDeclaration: Type[TSConstructSignatureDeclaration],
    TSConstructorType: Type[TSConstructorType],
    TSDeclareFunction: Type[TSDeclareFunction],
    TSDeclareMethod: Type[TSDeclareMethod],
    TSEnumDeclaration: Type[TSEnumDeclaration],
    TSEnumMember: Type[TSEnumMember],
    TSExportAssignment: Type[TSExportAssignment],
    TSExpressionWithTypeArguments: Type[TSExpressionWithTypeArguments],
    TSExternalModuleReference: Type[TSExternalModuleReference],
    TSFunctionType: Type[TSFunctionType],
    TSHasOptionalTypeAnnotation: Type[TSHasOptionalTypeAnnotation],
    TSHasOptionalTypeParameterInstantiation: Type[TSHasOptionalTypeParameterInstantiation],
    TSHasOptionalTypeParameters: Type[TSHasOptionalTypeParameters],
    TSImportEqualsDeclaration: Type[TSImportEqualsDeclaration],
    TSImportType: Type[TSImportType],
    TSIndexSignature: Type[TSIndexSignature],
    TSIndexedAccessType: Type[TSIndexedAccessType],
    TSInferType: Type[TSInferType],
    TSInterfaceBody: Type[TSInterfaceBody],
    TSInterfaceDeclaration: Type[TSInterfaceDeclaration],
    TSIntersectionType: Type[TSIntersectionType],
    TSLiteralType: Type[TSLiteralType],
    TSMappedType: Type[TSMappedType],
    TSMethodSignature: Type[TSMethodSignature],
    TSModuleBlock: Type[TSModuleBlock],
    TSModuleDeclaration: Type[TSModuleDeclaration],
    TSNamespaceExportDeclaration: Type[TSNamespaceExportDeclaration],
    TSNeverKeyword: Type[TSNeverKeyword],
    TSNonNullExpression: Type[TSNonNullExpression],
    TSNullKeyword: Type[TSNullKeyword],
    TSNumberKeyword: Type[TSNumberKeyword],
    TSObjectKeyword: Type[TSObjectKeyword],
    TSOptionalType: Type[TSOptionalType],
    TSParameterProperty: Type[TSParameterProperty],
    TSParenthesizedType: Type[TSParenthesizedType],
    TSPropertySignature: Type[TSPropertySignature],
    TSQualifiedName: Type[TSQualifiedName],
    TSRestType: Type[TSRestType],
    TSStringKeyword: Type[TSStringKeyword],
    TSSymbolKeyword: Type[TSSymbolKeyword],
    TSThisType: Type[TSThisType],
    TSTupleType: Type[TSTupleType],
    TSType: Type[TSType],
    TSTypeAliasDeclaration: Type[TSTypeAliasDeclaration],
    TSTypeAnnotation: Type[TSTypeAnnotation],
    TSTypeAssertion: Type[TSTypeAssertion],
    TSTypeLiteral: Type[TSTypeLiteral],
    TSTypeOperator: Type[TSTypeOperator],
    TSTypeParameter: Type[TSTypeParameter],
    TSTypeParameterDeclaration: Type[TSTypeParameterDeclaration],
    TSTypeParameterInstantiation: Type[TSTypeParameterInstantiation],
    TSTypePredicate: Type[TSTypePredicate],
    TSTypeQuery: Type[TSTypeQuery],
    TSTypeReference: Type[TSTypeReference],
    TSUndefinedKeyword: Type[TSUndefinedKeyword],
    TSUnionType: Type[TSUnionType],
    TSUnknownKeyword: Type[TSUnknownKeyword],
    TSVoidKeyword: Type[TSVoidKeyword],
    TaggedTemplateExpression: Type[TaggedTemplateExpression],
    TemplateElement: Type[TemplateElement],
    TemplateLiteral: Type[TemplateLiteral],
    ThisExpression: Type[ThisExpression],
    ThisTypeAnnotation: Type[ThisTypeAnnotation],
    ThrowStatement: Type[ThrowStatement],
    TryStatement: Type[TryStatement],
    TupleTypeAnnotation: Type[TupleTypeAnnotation],
    TypeAlias: Type[TypeAlias],
    TypeAnnotation: Type[TypeAnnotation],
    TypeCastExpression: Type[TypeCastExpression],
    TypeParameter: Type[TypeParameter],
    TypeParameterDeclaration: Type[TypeParameterDeclaration],
    TypeParameterInstantiation: Type[TypeParameterInstantiation],
    TypeofTypeAnnotation: Type[TypeofTypeAnnotation],
    UnaryExpression: Type[UnaryExpression],
    UnionTypeAnnotation: Type[UnionTypeAnnotation],
    UpdateExpression: Type[UpdateExpression]
  ): NamedTypes = {
    val __obj = js.Dynamic.literal(AnyTypeAnnotation = AnyTypeAnnotation.asInstanceOf[js.Any], ArrayExpression = ArrayExpression.asInstanceOf[js.Any], ArrayPattern = ArrayPattern.asInstanceOf[js.Any], ArrayTypeAnnotation = ArrayTypeAnnotation.asInstanceOf[js.Any], ArrowFunctionExpression = ArrowFunctionExpression.asInstanceOf[js.Any], AssignmentExpression = AssignmentExpression.asInstanceOf[js.Any], AssignmentPattern = AssignmentPattern.asInstanceOf[js.Any], AwaitExpression = AwaitExpression.asInstanceOf[js.Any], BigIntLiteral = BigIntLiteral.asInstanceOf[js.Any], BinaryExpression = BinaryExpression.asInstanceOf[js.Any], BindExpression = BindExpression.asInstanceOf[js.Any], Block = Block.asInstanceOf[js.Any], BlockStatement = BlockStatement.asInstanceOf[js.Any], BooleanLiteral = BooleanLiteral.asInstanceOf[js.Any], BooleanLiteralTypeAnnotation = BooleanLiteralTypeAnnotation.asInstanceOf[js.Any], BooleanTypeAnnotation = BooleanTypeAnnotation.asInstanceOf[js.Any], BreakStatement = BreakStatement.asInstanceOf[js.Any], CallExpression = CallExpression.asInstanceOf[js.Any], CatchClause = CatchClause.asInstanceOf[js.Any], ClassBody = ClassBody.asInstanceOf[js.Any], ClassDeclaration = ClassDeclaration.asInstanceOf[js.Any], ClassExpression = ClassExpression.asInstanceOf[js.Any], ClassImplements = ClassImplements.asInstanceOf[js.Any], ClassMethod = ClassMethod.asInstanceOf[js.Any], ClassPrivateMethod = ClassPrivateMethod.asInstanceOf[js.Any], ClassPrivateProperty = ClassPrivateProperty.asInstanceOf[js.Any], ClassProperty = ClassProperty.asInstanceOf[js.Any], ClassPropertyDefinition = ClassPropertyDefinition.asInstanceOf[js.Any], Comment = Comment.asInstanceOf[js.Any], CommentBlock = CommentBlock.asInstanceOf[js.Any], CommentLine = CommentLine.asInstanceOf[js.Any], ComprehensionBlock = ComprehensionBlock.asInstanceOf[js.Any], ComprehensionExpression = ComprehensionExpression.asInstanceOf[js.Any], ConditionalExpression = ConditionalExpression.asInstanceOf[js.Any], ContinueStatement = ContinueStatement.asInstanceOf[js.Any], DebuggerStatement = DebuggerStatement.asInstanceOf[js.Any], Declaration = Declaration.asInstanceOf[js.Any], DeclareClass = DeclareClass.asInstanceOf[js.Any], DeclareExportAllDeclaration = DeclareExportAllDeclaration.asInstanceOf[js.Any], DeclareExportDeclaration = DeclareExportDeclaration.asInstanceOf[js.Any], DeclareFunction = DeclareFunction.asInstanceOf[js.Any], DeclareInterface = DeclareInterface.asInstanceOf[js.Any], DeclareModule = DeclareModule.asInstanceOf[js.Any], DeclareModuleExports = DeclareModuleExports.asInstanceOf[js.Any], DeclareOpaqueType = DeclareOpaqueType.asInstanceOf[js.Any], DeclareTypeAlias = DeclareTypeAlias.asInstanceOf[js.Any], DeclareVariable = DeclareVariable.asInstanceOf[js.Any], DeclaredPredicate = DeclaredPredicate.asInstanceOf[js.Any], Decorator = Decorator.asInstanceOf[js.Any], Directive = Directive.asInstanceOf[js.Any], DirectiveLiteral = DirectiveLiteral.asInstanceOf[js.Any], DoExpression = DoExpression.asInstanceOf[js.Any], DoWhileStatement = DoWhileStatement.asInstanceOf[js.Any], EmptyStatement = EmptyStatement.asInstanceOf[js.Any], EmptyTypeAnnotation = EmptyTypeAnnotation.asInstanceOf[js.Any], ExistentialTypeParam = ExistentialTypeParam.asInstanceOf[js.Any], ExistsTypeAnnotation = ExistsTypeAnnotation.asInstanceOf[js.Any], ExportAllDeclaration = ExportAllDeclaration.asInstanceOf[js.Any], ExportBatchSpecifier = ExportBatchSpecifier.asInstanceOf[js.Any], ExportDeclaration = ExportDeclaration.asInstanceOf[js.Any], ExportDefaultDeclaration = ExportDefaultDeclaration.asInstanceOf[js.Any], ExportDefaultSpecifier = ExportDefaultSpecifier.asInstanceOf[js.Any], ExportNamedDeclaration = ExportNamedDeclaration.asInstanceOf[js.Any], ExportNamespaceSpecifier = ExportNamespaceSpecifier.asInstanceOf[js.Any], ExportSpecifier = ExportSpecifier.asInstanceOf[js.Any], Expression = Expression.asInstanceOf[js.Any], ExpressionStatement = ExpressionStatement.asInstanceOf[js.Any], File = File.asInstanceOf[js.Any], Flow = Flow.asInstanceOf[js.Any], FlowPredicate = FlowPredicate.asInstanceOf[js.Any], FlowType = FlowType.asInstanceOf[js.Any], ForAwaitStatement = ForAwaitStatement.asInstanceOf[js.Any], ForInStatement = ForInStatement.asInstanceOf[js.Any], ForOfStatement = ForOfStatement.asInstanceOf[js.Any], ForStatement = ForStatement.asInstanceOf[js.Any], Function = Function.asInstanceOf[js.Any], FunctionDeclaration = FunctionDeclaration.asInstanceOf[js.Any], FunctionExpression = FunctionExpression.asInstanceOf[js.Any], FunctionTypeAnnotation = FunctionTypeAnnotation.asInstanceOf[js.Any], FunctionTypeParam = FunctionTypeParam.asInstanceOf[js.Any], GeneratorExpression = GeneratorExpression.asInstanceOf[js.Any], GenericTypeAnnotation = GenericTypeAnnotation.asInstanceOf[js.Any], Identifier = Identifier.asInstanceOf[js.Any], IfStatement = IfStatement.asInstanceOf[js.Any], Import = Import.asInstanceOf[js.Any], ImportDeclaration = ImportDeclaration.asInstanceOf[js.Any], ImportDefaultSpecifier = ImportDefaultSpecifier.asInstanceOf[js.Any], ImportNamespaceSpecifier = ImportNamespaceSpecifier.asInstanceOf[js.Any], ImportSpecifier = ImportSpecifier.asInstanceOf[js.Any], InferredPredicate = InferredPredicate.asInstanceOf[js.Any], InterfaceDeclaration = InterfaceDeclaration.asInstanceOf[js.Any], InterfaceExtends = InterfaceExtends.asInstanceOf[js.Any], InterfaceTypeAnnotation = InterfaceTypeAnnotation.asInstanceOf[js.Any], InterpreterDirective = InterpreterDirective.asInstanceOf[js.Any], IntersectionTypeAnnotation = IntersectionTypeAnnotation.asInstanceOf[js.Any], JSXAttribute = JSXAttribute.asInstanceOf[js.Any], JSXClosingElement = JSXClosingElement.asInstanceOf[js.Any], JSXClosingFragment = JSXClosingFragment.asInstanceOf[js.Any], JSXElement = JSXElement.asInstanceOf[js.Any], JSXEmptyExpression = JSXEmptyExpression.asInstanceOf[js.Any], JSXExpressionContainer = JSXExpressionContainer.asInstanceOf[js.Any], JSXFragment = JSXFragment.asInstanceOf[js.Any], JSXIdentifier = JSXIdentifier.asInstanceOf[js.Any], JSXMemberExpression = JSXMemberExpression.asInstanceOf[js.Any], JSXNamespacedName = JSXNamespacedName.asInstanceOf[js.Any], JSXOpeningElement = JSXOpeningElement.asInstanceOf[js.Any], JSXOpeningFragment = JSXOpeningFragment.asInstanceOf[js.Any], JSXSpreadAttribute = JSXSpreadAttribute.asInstanceOf[js.Any], JSXSpreadChild = JSXSpreadChild.asInstanceOf[js.Any], JSXText = JSXText.asInstanceOf[js.Any], LabeledStatement = LabeledStatement.asInstanceOf[js.Any], Line = Line.asInstanceOf[js.Any], Literal = Literal.asInstanceOf[js.Any], LogicalExpression = LogicalExpression.asInstanceOf[js.Any], MemberExpression = MemberExpression.asInstanceOf[js.Any], MemberTypeAnnotation = MemberTypeAnnotation.asInstanceOf[js.Any], MetaProperty = MetaProperty.asInstanceOf[js.Any], MethodDefinition = MethodDefinition.asInstanceOf[js.Any], MixedTypeAnnotation = MixedTypeAnnotation.asInstanceOf[js.Any], ModuleSpecifier = ModuleSpecifier.asInstanceOf[js.Any], NewExpression = NewExpression.asInstanceOf[js.Any], Node = Node.asInstanceOf[js.Any], Noop = Noop.asInstanceOf[js.Any], NullLiteral = NullLiteral.asInstanceOf[js.Any], NullLiteralTypeAnnotation = NullLiteralTypeAnnotation.asInstanceOf[js.Any], NullTypeAnnotation = NullTypeAnnotation.asInstanceOf[js.Any], NullableTypeAnnotation = NullableTypeAnnotation.asInstanceOf[js.Any], NumberLiteralTypeAnnotation = NumberLiteralTypeAnnotation.asInstanceOf[js.Any], NumberTypeAnnotation = NumberTypeAnnotation.asInstanceOf[js.Any], NumericLiteral = NumericLiteral.asInstanceOf[js.Any], NumericLiteralTypeAnnotation = NumericLiteralTypeAnnotation.asInstanceOf[js.Any], ObjectExpression = ObjectExpression.asInstanceOf[js.Any], ObjectMethod = ObjectMethod.asInstanceOf[js.Any], ObjectPattern = ObjectPattern.asInstanceOf[js.Any], ObjectProperty = ObjectProperty.asInstanceOf[js.Any], ObjectTypeAnnotation = ObjectTypeAnnotation.asInstanceOf[js.Any], ObjectTypeCallProperty = ObjectTypeCallProperty.asInstanceOf[js.Any], ObjectTypeIndexer = ObjectTypeIndexer.asInstanceOf[js.Any], ObjectTypeInternalSlot = ObjectTypeInternalSlot.asInstanceOf[js.Any], ObjectTypeProperty = ObjectTypeProperty.asInstanceOf[js.Any], ObjectTypeSpreadProperty = ObjectTypeSpreadProperty.asInstanceOf[js.Any], OpaqueType = OpaqueType.asInstanceOf[js.Any], OptionalCallExpression = OptionalCallExpression.asInstanceOf[js.Any], OptionalMemberExpression = OptionalMemberExpression.asInstanceOf[js.Any], ParenthesizedExpression = ParenthesizedExpression.asInstanceOf[js.Any], Pattern = Pattern.asInstanceOf[js.Any], Position = Position.asInstanceOf[js.Any], Printable = Printable.asInstanceOf[js.Any], PrivateName = PrivateName.asInstanceOf[js.Any], Program = Program.asInstanceOf[js.Any], Property = Property.asInstanceOf[js.Any], PropertyPattern = PropertyPattern.asInstanceOf[js.Any], QualifiedTypeIdentifier = QualifiedTypeIdentifier.asInstanceOf[js.Any], RegExpLiteral = RegExpLiteral.asInstanceOf[js.Any], RestElement = RestElement.asInstanceOf[js.Any], RestProperty = RestProperty.asInstanceOf[js.Any], ReturnStatement = ReturnStatement.asInstanceOf[js.Any], SequenceExpression = SequenceExpression.asInstanceOf[js.Any], SourceLocation = SourceLocation.asInstanceOf[js.Any], Specifier = Specifier.asInstanceOf[js.Any], SpreadElement = SpreadElement.asInstanceOf[js.Any], SpreadElementPattern = SpreadElementPattern.asInstanceOf[js.Any], SpreadProperty = SpreadProperty.asInstanceOf[js.Any], SpreadPropertyPattern = SpreadPropertyPattern.asInstanceOf[js.Any], Statement = Statement.asInstanceOf[js.Any], StringLiteral = StringLiteral.asInstanceOf[js.Any], StringLiteralTypeAnnotation = StringLiteralTypeAnnotation.asInstanceOf[js.Any], StringTypeAnnotation = StringTypeAnnotation.asInstanceOf[js.Any], Super = Super.asInstanceOf[js.Any], SwitchCase = SwitchCase.asInstanceOf[js.Any], SwitchStatement = SwitchStatement.asInstanceOf[js.Any], TSAnyKeyword = TSAnyKeyword.asInstanceOf[js.Any], TSArrayType = TSArrayType.asInstanceOf[js.Any], TSAsExpression = TSAsExpression.asInstanceOf[js.Any], TSBigIntKeyword = TSBigIntKeyword.asInstanceOf[js.Any], TSBooleanKeyword = TSBooleanKeyword.asInstanceOf[js.Any], TSCallSignatureDeclaration = TSCallSignatureDeclaration.asInstanceOf[js.Any], TSConditionalType = TSConditionalType.asInstanceOf[js.Any], TSConstructSignatureDeclaration = TSConstructSignatureDeclaration.asInstanceOf[js.Any], TSConstructorType = TSConstructorType.asInstanceOf[js.Any], TSDeclareFunction = TSDeclareFunction.asInstanceOf[js.Any], TSDeclareMethod = TSDeclareMethod.asInstanceOf[js.Any], TSEnumDeclaration = TSEnumDeclaration.asInstanceOf[js.Any], TSEnumMember = TSEnumMember.asInstanceOf[js.Any], TSExportAssignment = TSExportAssignment.asInstanceOf[js.Any], TSExpressionWithTypeArguments = TSExpressionWithTypeArguments.asInstanceOf[js.Any], TSExternalModuleReference = TSExternalModuleReference.asInstanceOf[js.Any], TSFunctionType = TSFunctionType.asInstanceOf[js.Any], TSHasOptionalTypeAnnotation = TSHasOptionalTypeAnnotation.asInstanceOf[js.Any], TSHasOptionalTypeParameterInstantiation = TSHasOptionalTypeParameterInstantiation.asInstanceOf[js.Any], TSHasOptionalTypeParameters = TSHasOptionalTypeParameters.asInstanceOf[js.Any], TSImportEqualsDeclaration = TSImportEqualsDeclaration.asInstanceOf[js.Any], TSImportType = TSImportType.asInstanceOf[js.Any], TSIndexSignature = TSIndexSignature.asInstanceOf[js.Any], TSIndexedAccessType = TSIndexedAccessType.asInstanceOf[js.Any], TSInferType = TSInferType.asInstanceOf[js.Any], TSInterfaceBody = TSInterfaceBody.asInstanceOf[js.Any], TSInterfaceDeclaration = TSInterfaceDeclaration.asInstanceOf[js.Any], TSIntersectionType = TSIntersectionType.asInstanceOf[js.Any], TSLiteralType = TSLiteralType.asInstanceOf[js.Any], TSMappedType = TSMappedType.asInstanceOf[js.Any], TSMethodSignature = TSMethodSignature.asInstanceOf[js.Any], TSModuleBlock = TSModuleBlock.asInstanceOf[js.Any], TSModuleDeclaration = TSModuleDeclaration.asInstanceOf[js.Any], TSNamespaceExportDeclaration = TSNamespaceExportDeclaration.asInstanceOf[js.Any], TSNeverKeyword = TSNeverKeyword.asInstanceOf[js.Any], TSNonNullExpression = TSNonNullExpression.asInstanceOf[js.Any], TSNullKeyword = TSNullKeyword.asInstanceOf[js.Any], TSNumberKeyword = TSNumberKeyword.asInstanceOf[js.Any], TSObjectKeyword = TSObjectKeyword.asInstanceOf[js.Any], TSOptionalType = TSOptionalType.asInstanceOf[js.Any], TSParameterProperty = TSParameterProperty.asInstanceOf[js.Any], TSParenthesizedType = TSParenthesizedType.asInstanceOf[js.Any], TSPropertySignature = TSPropertySignature.asInstanceOf[js.Any], TSQualifiedName = TSQualifiedName.asInstanceOf[js.Any], TSRestType = TSRestType.asInstanceOf[js.Any], TSStringKeyword = TSStringKeyword.asInstanceOf[js.Any], TSSymbolKeyword = TSSymbolKeyword.asInstanceOf[js.Any], TSThisType = TSThisType.asInstanceOf[js.Any], TSTupleType = TSTupleType.asInstanceOf[js.Any], TSType = TSType.asInstanceOf[js.Any], TSTypeAliasDeclaration = TSTypeAliasDeclaration.asInstanceOf[js.Any], TSTypeAnnotation = TSTypeAnnotation.asInstanceOf[js.Any], TSTypeAssertion = TSTypeAssertion.asInstanceOf[js.Any], TSTypeLiteral = TSTypeLiteral.asInstanceOf[js.Any], TSTypeOperator = TSTypeOperator.asInstanceOf[js.Any], TSTypeParameter = TSTypeParameter.asInstanceOf[js.Any], TSTypeParameterDeclaration = TSTypeParameterDeclaration.asInstanceOf[js.Any], TSTypeParameterInstantiation = TSTypeParameterInstantiation.asInstanceOf[js.Any], TSTypePredicate = TSTypePredicate.asInstanceOf[js.Any], TSTypeQuery = TSTypeQuery.asInstanceOf[js.Any], TSTypeReference = TSTypeReference.asInstanceOf[js.Any], TSUndefinedKeyword = TSUndefinedKeyword.asInstanceOf[js.Any], TSUnionType = TSUnionType.asInstanceOf[js.Any], TSUnknownKeyword = TSUnknownKeyword.asInstanceOf[js.Any], TSVoidKeyword = TSVoidKeyword.asInstanceOf[js.Any], TaggedTemplateExpression = TaggedTemplateExpression.asInstanceOf[js.Any], TemplateElement = TemplateElement.asInstanceOf[js.Any], TemplateLiteral = TemplateLiteral.asInstanceOf[js.Any], ThisExpression = ThisExpression.asInstanceOf[js.Any], ThisTypeAnnotation = ThisTypeAnnotation.asInstanceOf[js.Any], ThrowStatement = ThrowStatement.asInstanceOf[js.Any], TryStatement = TryStatement.asInstanceOf[js.Any], TupleTypeAnnotation = TupleTypeAnnotation.asInstanceOf[js.Any], TypeAlias = TypeAlias.asInstanceOf[js.Any], TypeAnnotation = TypeAnnotation.asInstanceOf[js.Any], TypeCastExpression = TypeCastExpression.asInstanceOf[js.Any], TypeParameter = TypeParameter.asInstanceOf[js.Any], TypeParameterDeclaration = TypeParameterDeclaration.asInstanceOf[js.Any], TypeParameterInstantiation = TypeParameterInstantiation.asInstanceOf[js.Any], TypeofTypeAnnotation = TypeofTypeAnnotation.asInstanceOf[js.Any], UnaryExpression = UnaryExpression.asInstanceOf[js.Any], UnionTypeAnnotation = UnionTypeAnnotation.asInstanceOf[js.Any], UpdateExpression = UpdateExpression.asInstanceOf[js.Any])
  
    __obj.asInstanceOf[NamedTypes]
  }
}

