package typingsSlinky.vscodeDashLanguageserverDashProtocol

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object libProtocolMod {
  import typingsSlinky.vscodeDashLanguageserverDashProtocol.libProtocolDotColorProviderMod.ColorClientCapabilities
  import typingsSlinky.vscodeDashLanguageserverDashProtocol.libProtocolDotColorProviderMod.ColorServerCapabilities
  import typingsSlinky.vscodeDashLanguageserverDashProtocol.libProtocolDotConfigurationMod.ConfigurationClientCapabilities
  import typingsSlinky.vscodeDashLanguageserverDashProtocol.libProtocolDotDeclarationMod.DeclarationClientCapabilities
  import typingsSlinky.vscodeDashLanguageserverDashProtocol.libProtocolDotDeclarationMod.DeclarationServerCapabilities
  import typingsSlinky.vscodeDashLanguageserverDashProtocol.libProtocolDotFoldingRangeMod.FoldingRangeClientCapabilities
  import typingsSlinky.vscodeDashLanguageserverDashProtocol.libProtocolDotFoldingRangeMod.FoldingRangeServerCapabilities
  import typingsSlinky.vscodeDashLanguageserverDashProtocol.libProtocolDotImplementationMod.ImplementationClientCapabilities
  import typingsSlinky.vscodeDashLanguageserverDashProtocol.libProtocolDotImplementationMod.ImplementationServerCapabilities
  import typingsSlinky.vscodeDashLanguageserverDashProtocol.libProtocolDotTypeDefinitionMod.TypeDefinitionClientCapabilities
  import typingsSlinky.vscodeDashLanguageserverDashProtocol.libProtocolDotTypeDefinitionMod.TypeDefinitionServerCapabilities
  import typingsSlinky.vscodeDashLanguageserverDashProtocol.libProtocolDotWorkspaceFoldersMod.WorkspaceFoldersClientCapabilities
  import typingsSlinky.vscodeDashLanguageserverDashProtocol.libProtocolDotWorkspaceFoldersMod.WorkspaceFoldersInitializeParams
  import typingsSlinky.vscodeDashLanguageserverDashProtocol.libProtocolDotWorkspaceFoldersMod.WorkspaceFoldersServerCapabilities

  type ClientCapabilities = _ClientCapabilities with ImplementationClientCapabilities with TypeDefinitionClientCapabilities with WorkspaceFoldersClientCapabilities with ConfigurationClientCapabilities with ColorClientCapabilities with FoldingRangeClientCapabilities with DeclarationClientCapabilities
  type DocumentSelector = js.Array[String | DocumentFilter]
  type ExecuteCommandRegistrationOptions = ExecuteCommandOptions
  type InitializeParams = _InitializeParams with WorkspaceFoldersInitializeParams
  type ServerCapabilities = _ServerCapabilities with ImplementationServerCapabilities with TypeDefinitionServerCapabilities with WorkspaceFoldersServerCapabilities with ColorServerCapabilities with FoldingRangeServerCapabilities with DeclarationServerCapabilities
}
