package typingsSlinky.sugar.sugarjs.Number

import typingsSlinky.std.Intl.NumberFormatOptions
import typingsSlinky.sugar.sugarjs.Date.DateCreateOptions
import typingsSlinky.sugar.sugarjs.Range
import typingsSlinky.sugar.sugarjs.SugarDefaultChainable
import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

@js.native
trait ChainableBase[RawValue] extends js.Object {
  var raw: RawValue = js.native
  def abbr(): SugarDefaultChainable[java.lang.String] = js.native
  def abbr(precision: Double): SugarDefaultChainable[java.lang.String] = js.native
  def abs(): SugarDefaultChainable[Double] = js.native
  def acos(): SugarDefaultChainable[Double] = js.native
  def asin(): SugarDefaultChainable[Double] = js.native
  def atan(): SugarDefaultChainable[Double] = js.native
  def bytes(): SugarDefaultChainable[java.lang.String] = js.native
  def bytes(precision: Double): SugarDefaultChainable[java.lang.String] = js.native
  def bytes(precision: Double, binary: Boolean): SugarDefaultChainable[java.lang.String] = js.native
  def bytes(precision: Double, binary: Boolean, units: java.lang.String): SugarDefaultChainable[java.lang.String] = js.native
  def cap(): SugarDefaultChainable[Double] = js.native
  def cap(max: Double): SugarDefaultChainable[Double] = js.native
  def ceil(): SugarDefaultChainable[Double] = js.native
  def ceil(precision: Double): SugarDefaultChainable[Double] = js.native
  def chr(): SugarDefaultChainable[java.lang.String] = js.native
  def clamp(): SugarDefaultChainable[Double] = js.native
  def clamp(start: Double): SugarDefaultChainable[Double] = js.native
  def clamp(start: Double, end: Double): SugarDefaultChainable[Double] = js.native
  def cos(): SugarDefaultChainable[Double] = js.native
  def day(): SugarDefaultChainable[Double] = js.native
  def dayAfter(d: java.lang.String): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def dayAfter(d: java.lang.String, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def dayAfter(d: Double): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def dayAfter(d: Double, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def dayAfter(d: typingsSlinky.sugar.Date): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def dayAfter(d: typingsSlinky.sugar.Date, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def dayAgo(): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def dayBefore(d: java.lang.String): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def dayBefore(d: java.lang.String, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def dayBefore(d: Double): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def dayBefore(d: Double, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def dayBefore(d: typingsSlinky.sugar.Date): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def dayBefore(d: typingsSlinky.sugar.Date, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def dayFromNow(): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def days(): SugarDefaultChainable[Double] = js.native
  def daysAfter(d: java.lang.String): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def daysAfter(d: java.lang.String, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def daysAfter(d: Double): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def daysAfter(d: Double, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def daysAfter(d: typingsSlinky.sugar.Date): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def daysAfter(d: typingsSlinky.sugar.Date, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def daysAgo(): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def daysBefore(d: java.lang.String): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def daysBefore(d: java.lang.String, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def daysBefore(d: Double): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def daysBefore(d: Double, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def daysBefore(d: typingsSlinky.sugar.Date): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def daysBefore(d: typingsSlinky.sugar.Date, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def daysFromNow(): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def downto[T](num: Double): SugarDefaultChainable[typingsSlinky.sugar.Array[T]] = js.native
  def downto[T](
    num: Double,
    everyFn: js.Function3[/* el */ T, /* i */ Double, /* r */ Range, SugarDefaultChainable[Unit]]
  ): SugarDefaultChainable[typingsSlinky.sugar.Array[T]] = js.native
  def downto[T](num: Double, step: Double): SugarDefaultChainable[typingsSlinky.sugar.Array[T]] = js.native
  def downto[T](
    num: Double,
    step: Double,
    everyFn: js.Function3[/* el */ T, /* i */ Double, /* r */ Range, SugarDefaultChainable[Unit]]
  ): SugarDefaultChainable[typingsSlinky.sugar.Array[T]] = js.native
  def duration(): SugarDefaultChainable[java.lang.String] = js.native
  def duration(localeCode: java.lang.String): SugarDefaultChainable[java.lang.String] = js.native
  def exp(): SugarDefaultChainable[Double] = js.native
  def floor(): SugarDefaultChainable[Double] = js.native
  def floor(precision: Double): SugarDefaultChainable[Double] = js.native
  def format(): SugarDefaultChainable[java.lang.String] = js.native
  def format(place: Double): SugarDefaultChainable[java.lang.String] = js.native
  def hex(): SugarDefaultChainable[java.lang.String] = js.native
  def hex(pad: Double): SugarDefaultChainable[java.lang.String] = js.native
  def hour(): SugarDefaultChainable[Double] = js.native
  def hourAfter(d: java.lang.String): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def hourAfter(d: java.lang.String, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def hourAfter(d: Double): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def hourAfter(d: Double, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def hourAfter(d: typingsSlinky.sugar.Date): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def hourAfter(d: typingsSlinky.sugar.Date, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def hourAgo(): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def hourBefore(d: java.lang.String): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def hourBefore(d: java.lang.String, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def hourBefore(d: Double): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def hourBefore(d: Double, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def hourBefore(d: typingsSlinky.sugar.Date): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def hourBefore(d: typingsSlinky.sugar.Date, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def hourFromNow(): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def hours(): SugarDefaultChainable[Double] = js.native
  def hoursAfter(d: java.lang.String): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def hoursAfter(d: java.lang.String, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def hoursAfter(d: Double): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def hoursAfter(d: Double, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def hoursAfter(d: typingsSlinky.sugar.Date): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def hoursAfter(d: typingsSlinky.sugar.Date, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def hoursAgo(): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def hoursBefore(d: java.lang.String): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def hoursBefore(d: java.lang.String, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def hoursBefore(d: Double): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def hoursBefore(d: Double, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def hoursBefore(d: typingsSlinky.sugar.Date): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def hoursBefore(d: typingsSlinky.sugar.Date, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def hoursFromNow(): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def isEven(): SugarDefaultChainable[Boolean] = js.native
  def isInteger(): SugarDefaultChainable[Boolean] = js.native
  def isMultipleOf(num: Double): SugarDefaultChainable[Boolean] = js.native
  def isOdd(): SugarDefaultChainable[Boolean] = js.native
  def log(): SugarDefaultChainable[Double] = js.native
  def log(base: Double): SugarDefaultChainable[Double] = js.native
  def metric(): SugarDefaultChainable[java.lang.String] = js.native
  def metric(precision: Double): SugarDefaultChainable[java.lang.String] = js.native
  def metric(precision: Double, units: java.lang.String): SugarDefaultChainable[java.lang.String] = js.native
  def millisecond(): SugarDefaultChainable[Double] = js.native
  def millisecondAfter(d: java.lang.String): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def millisecondAfter(d: java.lang.String, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def millisecondAfter(d: Double): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def millisecondAfter(d: Double, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def millisecondAfter(d: typingsSlinky.sugar.Date): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def millisecondAfter(d: typingsSlinky.sugar.Date, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def millisecondAgo(): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def millisecondBefore(d: java.lang.String): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def millisecondBefore(d: java.lang.String, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def millisecondBefore(d: Double): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def millisecondBefore(d: Double, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def millisecondBefore(d: typingsSlinky.sugar.Date): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def millisecondBefore(d: typingsSlinky.sugar.Date, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def millisecondFromNow(): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def milliseconds(): SugarDefaultChainable[Double] = js.native
  def millisecondsAfter(d: java.lang.String): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def millisecondsAfter(d: java.lang.String, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def millisecondsAfter(d: Double): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def millisecondsAfter(d: Double, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def millisecondsAfter(d: typingsSlinky.sugar.Date): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def millisecondsAfter(d: typingsSlinky.sugar.Date, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def millisecondsAgo(): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def millisecondsBefore(d: java.lang.String): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def millisecondsBefore(d: java.lang.String, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def millisecondsBefore(d: Double): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def millisecondsBefore(d: Double, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def millisecondsBefore(d: typingsSlinky.sugar.Date): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def millisecondsBefore(d: typingsSlinky.sugar.Date, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def millisecondsFromNow(): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def minute(): SugarDefaultChainable[Double] = js.native
  def minuteAfter(d: java.lang.String): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def minuteAfter(d: java.lang.String, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def minuteAfter(d: Double): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def minuteAfter(d: Double, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def minuteAfter(d: typingsSlinky.sugar.Date): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def minuteAfter(d: typingsSlinky.sugar.Date, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def minuteAgo(): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def minuteBefore(d: java.lang.String): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def minuteBefore(d: java.lang.String, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def minuteBefore(d: Double): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def minuteBefore(d: Double, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def minuteBefore(d: typingsSlinky.sugar.Date): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def minuteBefore(d: typingsSlinky.sugar.Date, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def minuteFromNow(): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def minutes(): SugarDefaultChainable[Double] = js.native
  def minutesAfter(d: java.lang.String): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def minutesAfter(d: java.lang.String, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def minutesAfter(d: Double): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def minutesAfter(d: Double, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def minutesAfter(d: typingsSlinky.sugar.Date): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def minutesAfter(d: typingsSlinky.sugar.Date, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def minutesAgo(): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def minutesBefore(d: java.lang.String): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def minutesBefore(d: java.lang.String, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def minutesBefore(d: Double): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def minutesBefore(d: Double, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def minutesBefore(d: typingsSlinky.sugar.Date): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def minutesBefore(d: typingsSlinky.sugar.Date, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def minutesFromNow(): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def month(): SugarDefaultChainable[Double] = js.native
  def monthAfter(d: java.lang.String): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def monthAfter(d: java.lang.String, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def monthAfter(d: Double): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def monthAfter(d: Double, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def monthAfter(d: typingsSlinky.sugar.Date): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def monthAfter(d: typingsSlinky.sugar.Date, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def monthAgo(): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def monthBefore(d: java.lang.String): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def monthBefore(d: java.lang.String, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def monthBefore(d: Double): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def monthBefore(d: Double, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def monthBefore(d: typingsSlinky.sugar.Date): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def monthBefore(d: typingsSlinky.sugar.Date, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def monthFromNow(): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def months(): SugarDefaultChainable[Double] = js.native
  def monthsAfter(d: java.lang.String): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def monthsAfter(d: java.lang.String, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def monthsAfter(d: Double): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def monthsAfter(d: Double, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def monthsAfter(d: typingsSlinky.sugar.Date): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def monthsAfter(d: typingsSlinky.sugar.Date, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def monthsAgo(): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def monthsBefore(d: java.lang.String): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def monthsBefore(d: java.lang.String, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def monthsBefore(d: Double): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def monthsBefore(d: Double, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def monthsBefore(d: typingsSlinky.sugar.Date): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def monthsBefore(d: typingsSlinky.sugar.Date, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def monthsFromNow(): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def ordinalize(): SugarDefaultChainable[java.lang.String] = js.native
  def pad(): SugarDefaultChainable[java.lang.String] = js.native
  def pad(place: Double): SugarDefaultChainable[java.lang.String] = js.native
  def pad(place: Double, sign: Boolean): SugarDefaultChainable[java.lang.String] = js.native
  def pad(place: Double, sign: Boolean, base: Double): SugarDefaultChainable[java.lang.String] = js.native
  def pow(): SugarDefaultChainable[Double] = js.native
  def round(): SugarDefaultChainable[Double] = js.native
  def round(precision: Double): SugarDefaultChainable[Double] = js.native
  def second(): SugarDefaultChainable[Double] = js.native
  def secondAfter(d: java.lang.String): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def secondAfter(d: java.lang.String, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def secondAfter(d: Double): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def secondAfter(d: Double, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def secondAfter(d: typingsSlinky.sugar.Date): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def secondAfter(d: typingsSlinky.sugar.Date, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def secondAgo(): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def secondBefore(d: java.lang.String): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def secondBefore(d: java.lang.String, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def secondBefore(d: Double): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def secondBefore(d: Double, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def secondBefore(d: typingsSlinky.sugar.Date): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def secondBefore(d: typingsSlinky.sugar.Date, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def secondFromNow(): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def seconds(): SugarDefaultChainable[Double] = js.native
  def secondsAfter(d: java.lang.String): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def secondsAfter(d: java.lang.String, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def secondsAfter(d: Double): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def secondsAfter(d: Double, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def secondsAfter(d: typingsSlinky.sugar.Date): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def secondsAfter(d: typingsSlinky.sugar.Date, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def secondsAgo(): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def secondsBefore(d: java.lang.String): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def secondsBefore(d: java.lang.String, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def secondsBefore(d: Double): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def secondsBefore(d: Double, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def secondsBefore(d: typingsSlinky.sugar.Date): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def secondsBefore(d: typingsSlinky.sugar.Date, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def secondsFromNow(): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def sin(): SugarDefaultChainable[Double] = js.native
  def sqrt(): SugarDefaultChainable[Double] = js.native
  def tan(): SugarDefaultChainable[Double] = js.native
  def times[T](indexMapFn: js.Function1[/* i */ Double, SugarDefaultChainable[_]]): SugarDefaultChainable[T] = js.native
  def toExponential(): SugarDefaultChainable[java.lang.String] = js.native
  def toExponential(fractionDigits: Double): SugarDefaultChainable[java.lang.String] = js.native
  def toFixed(): SugarDefaultChainable[java.lang.String] = js.native
  def toFixed(fractionDigits: Double): SugarDefaultChainable[java.lang.String] = js.native
  def toLocaleString(locales: java.lang.String): SugarDefaultChainable[java.lang.String] = js.native
  def toLocaleString(locales: java.lang.String, options: NumberFormatOptions): SugarDefaultChainable[java.lang.String] = js.native
  def toLocaleString(locales: typingsSlinky.sugar.Array[java.lang.String]): SugarDefaultChainable[java.lang.String] = js.native
  def toLocaleString(locales: typingsSlinky.sugar.Array[java.lang.String], options: NumberFormatOptions): SugarDefaultChainable[java.lang.String] = js.native
  def toNumber(): SugarDefaultChainable[Double] = js.native
  def toPrecision(): SugarDefaultChainable[java.lang.String] = js.native
  def toPrecision(precision: Double): SugarDefaultChainable[java.lang.String] = js.native
  def upto[T](num: Double): SugarDefaultChainable[typingsSlinky.sugar.Array[T]] = js.native
  def upto[T](
    num: Double,
    everyFn: js.Function3[/* el */ T, /* i */ Double, /* r */ Range, SugarDefaultChainable[Unit]]
  ): SugarDefaultChainable[typingsSlinky.sugar.Array[T]] = js.native
  def upto[T](num: Double, step: Double): SugarDefaultChainable[typingsSlinky.sugar.Array[T]] = js.native
  def upto[T](
    num: Double,
    step: Double,
    everyFn: js.Function3[/* el */ T, /* i */ Double, /* r */ Range, SugarDefaultChainable[Unit]]
  ): SugarDefaultChainable[typingsSlinky.sugar.Array[T]] = js.native
  def week(): SugarDefaultChainable[Double] = js.native
  def weekAfter(d: java.lang.String): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def weekAfter(d: java.lang.String, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def weekAfter(d: Double): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def weekAfter(d: Double, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def weekAfter(d: typingsSlinky.sugar.Date): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def weekAfter(d: typingsSlinky.sugar.Date, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def weekAgo(): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def weekBefore(d: java.lang.String): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def weekBefore(d: java.lang.String, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def weekBefore(d: Double): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def weekBefore(d: Double, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def weekBefore(d: typingsSlinky.sugar.Date): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def weekBefore(d: typingsSlinky.sugar.Date, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def weekFromNow(): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def weeks(): SugarDefaultChainable[Double] = js.native
  def weeksAfter(d: java.lang.String): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def weeksAfter(d: java.lang.String, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def weeksAfter(d: Double): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def weeksAfter(d: Double, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def weeksAfter(d: typingsSlinky.sugar.Date): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def weeksAfter(d: typingsSlinky.sugar.Date, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def weeksAgo(): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def weeksBefore(d: java.lang.String): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def weeksBefore(d: java.lang.String, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def weeksBefore(d: Double): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def weeksBefore(d: Double, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def weeksBefore(d: typingsSlinky.sugar.Date): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def weeksBefore(d: typingsSlinky.sugar.Date, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def weeksFromNow(): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def year(): SugarDefaultChainable[Double] = js.native
  def yearAfter(d: java.lang.String): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def yearAfter(d: java.lang.String, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def yearAfter(d: Double): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def yearAfter(d: Double, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def yearAfter(d: typingsSlinky.sugar.Date): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def yearAfter(d: typingsSlinky.sugar.Date, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def yearAgo(): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def yearBefore(d: java.lang.String): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def yearBefore(d: java.lang.String, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def yearBefore(d: Double): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def yearBefore(d: Double, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def yearBefore(d: typingsSlinky.sugar.Date): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def yearBefore(d: typingsSlinky.sugar.Date, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def yearFromNow(): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def years(): SugarDefaultChainable[Double] = js.native
  def yearsAfter(d: java.lang.String): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def yearsAfter(d: java.lang.String, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def yearsAfter(d: Double): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def yearsAfter(d: Double, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def yearsAfter(d: typingsSlinky.sugar.Date): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def yearsAfter(d: typingsSlinky.sugar.Date, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def yearsAgo(): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def yearsBefore(d: java.lang.String): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def yearsBefore(d: java.lang.String, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def yearsBefore(d: Double): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def yearsBefore(d: Double, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def yearsBefore(d: typingsSlinky.sugar.Date): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def yearsBefore(d: typingsSlinky.sugar.Date, options: DateCreateOptions): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
  def yearsFromNow(): SugarDefaultChainable[typingsSlinky.sugar.Date] = js.native
}

