package typingsSlinky.semanticUiVisibility.SemanticUI

import scala.scalajs.js
import scala.scalajs.js.`|`
import scala.scalajs.js.annotation._

package object VisibilitySettings {
  type Param = (typingsSlinky.semanticUiVisibility.anon.PickImplonce | typingsSlinky.semanticUiVisibility.anon.PickImplcontinuous | typingsSlinky.semanticUiVisibility.anon.PickImpltype | typingsSlinky.semanticUiVisibility.anon.PickImplinitialCheck | typingsSlinky.semanticUiVisibility.anon.PickImplcontext | typingsSlinky.semanticUiVisibility.anon.PickImplrefreshOnLoad | typingsSlinky.semanticUiVisibility.anon.PickImplrefreshOnResize | typingsSlinky.semanticUiVisibility.anon.PickImplcheckOnRefresh | typingsSlinky.semanticUiVisibility.anon.PickImplzIndex | typingsSlinky.semanticUiVisibility.anon.PickImploffset | typingsSlinky.semanticUiVisibility.anon.PickImplincludeMargin | typingsSlinky.semanticUiVisibility.anon.PickImplthrottle | typingsSlinky.semanticUiVisibility.anon.PickImplobserveChanges | typingsSlinky.semanticUiVisibility.anon.PickImpltransition | typingsSlinky.semanticUiVisibility.anon.PickImplduration | typingsSlinky.semanticUiVisibility.anon.PickImplonTopVisible | typingsSlinky.semanticUiVisibility.anon.PickImplonTopPassed | typingsSlinky.semanticUiVisibility.anon.PickImplonBottomVisible | typingsSlinky.semanticUiVisibility.anon.PickImplonPassing | typingsSlinky.semanticUiVisibility.anon.PickImplonBottomPassed | typingsSlinky.semanticUiVisibility.anon.PickImplonTopVisibleRever | typingsSlinky.semanticUiVisibility.anon.PickImplonTopPassedRevers | typingsSlinky.semanticUiVisibility.anon.PickImplonBottomVisibleRe | typingsSlinky.semanticUiVisibility.anon.PickImplonPassingReverse | typingsSlinky.semanticUiVisibility.anon.PickImplonBottomPassedRev | typingsSlinky.semanticUiVisibility.anon.PickImplonOnScreen | typingsSlinky.semanticUiVisibility.anon.PickImplonOffScreen | typingsSlinky.semanticUiVisibility.anon.PickImplonLoad | typingsSlinky.semanticUiVisibility.anon.PickImplonAllLoaded | typingsSlinky.semanticUiVisibility.anon.PickImplonFixed | typingsSlinky.semanticUiVisibility.anon.PickImplonUnfixed | typingsSlinky.semanticUiVisibility.anon.PickImplonUpdate | typingsSlinky.semanticUiVisibility.anon.PickImplonRefresh | typingsSlinky.semanticUiVisibility.anon.PickImplclassName | typingsSlinky.semanticUiVisibility.anon.PickImplerror | typingsSlinky.semanticUiVisibility.anon.PickImplnamespace | typingsSlinky.semanticUiVisibility.anon.PickImplname | typingsSlinky.semanticUiVisibility.anon.PickImplsilent | typingsSlinky.semanticUiVisibility.anon.PickImpldebug | typingsSlinky.semanticUiVisibility.anon.PickImplperformance | typingsSlinky.semanticUiVisibility.anon.PickImplverbose) with typingsSlinky.semanticUiVisibility.anon.PartialPickImplkeyofImpl
}
